### PR TITLE
Restore taiko accuracy to ScoreV2 values

### LINKED ISSUE #9087: osu!taiko "Good"s give less accuracy/score compared to osu!stable
**Describe the bug:** In Stable, mistimed but correct hits in taiko give 50% accuracy (and 150 base score instead of 100), Lazer grants 33% like the rest of the gamemodes. I originally thought this might be intended, but seeing all the chatter about ppcalc/SR on Discord made me think you actually want complete parity and I should report this, just in case.

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=aRlsg2Qfk8k

**osu!lazer version:** 2020.515.0

### PR DESCRIPTION
**Pull request by smoogipoo**
This has been brought up as an inconsistency several times:
- Closes https://github.com/ppy/osu/discussions/25882
- Fixes https://github.com/ppy/osu/issues/9087

Note that this doesn't fix the accuracy circle/grade issue - that's an issue for all rulesets.

### CODE REVIEW

**Review by peppy — APPROVED** [review]

**Comment by bdach** [comment]
What does this mean for server-side usages of `Judgement.ToNumericResult()`?

https://github.com/ppy/osu-queue-score-statistics/blob/6d91b7738ad7adba513c86c382fb83b261dae5d6/osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs#L652
https://github.com/ppy/osu-queue-score-statistics/blob/6d91b7738ad7adba513c86c382fb83b261dae5d6/osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs#L741-L742

It appears that the import high scores command relies on the method to calculate accuracy, which will presumably be wrong for taiko scores now?

Isn't this the same sort of problem that we had with adding an `AffectsCombo` flag to `Judgement`, which implies that it is now necessary to construct all judgements on a beatmap to calculate the accuracy of a score correctly?

**Comment by smoogipoo** [comment]
because _of course_ there'd be something that references the raw values, why wouldn't there be...

**Comment by bdach** [comment]
Well to be more constructive than the above, I think this is _possibly_ salvageable if the method has a signature of `GetNumericResultFor(HitResult)` rather than accepting the judgement. Then the server-side usages can just construct the requisite score processor and go through that.

The `Judgement.ToNumericResult()` point still stands tho. Method should not be exposed outwardly anymore if it's not universally valid.

**Comment by smoogipoo** [comment]
Perhaps it's time to bite the bullet and not expose it publicly...

**Pull request merged**
