### PR TITLE
Stop UserProfileOverlay from recreating itself when a new user is shown

### LINKED ISSUE #11155: Profile header should imply it is loading new content when the user is changed
**Describe the bug:** 
When clicking on a new profile, the header will keep the old content active until the new content to replace it has been loaded. Instead, all the content should be replaced with placeholders while the new content is loading. 

**Screenshots or videos showing encountered issue:** 
https://youtu.be/ejpO3HY1bIE

**osu!lazer version:** 
2020.1204.0

### PR DESCRIPTION
**Pull request by jorolf**
Fixes #11155

### CODE REVIEW

**Comment by peppy** [comment]
Very similar PR to https://github.com/ppy/osu/pull/5138/files...

**Comment by jorolf** [comment]
They do different things though?

**Comment by EVAST9919** [comment]
@jorolf are you planning to update this?

**Comment by jorolf** [comment]
Before:

https://user-images.githubusercontent.com/12570757/102945807-254a4a00-44bf-11eb-8218-f8da7220b18a.mp4

After:

https://user-images.githubusercontent.com/12570757/102945911-62aed780-44bf-11eb-87b7-59a5659e5cc8.mp4

(Now that I look at it, it seems like the header isn't correctly vanishing everytime...)

**Comment by peppy** [comment]
I guess this approach is fine for now. I was intentionally not doing this because the idea is that each component should (eventually) have a placeholder state, avoiding reloading of individual components.

**Comment by peppy** [comment]
Honestly not sure this looks better than leaving previous content but whatever people think.

**Comment by peppy** [comment]
In fact never mind, let's not do this. The way it looks on master is better.

**Pull request closed without merging**
