### PR TITLE
Fix incorrect `base` call causing import optimisation to not work

### PR DESCRIPTION
**Pull request by peppy**
Open to suggestions on how to test this. The current import tests use a full game setup so it's hard to tell the different between an "optimised" reuse and a standard one. I've tested this on a real-world scenario and it's working as expected now, at least.

### CODE REVIEW

**Review by frenzibyte — DISMISSED** [review]
Scary that this could happen...

**Comment by bdach** [comment]
Not sure whether I wouldn't just drop the `base` branch altogether, given that the base implementation does `=> true`. Just feels like a bit of a much of muchness maybe. Bypassing `base` calls is also semi-bad but I think defensible in this case (the method is supposed to be pure).

As for testing... yeah I'm not sure much could be done. You could unit test it but the test would be dumb, and an integration test is probably going to be horrible to get to (would most likely have to uncouple a lot of things). So I think it's fine without a test - this type of errors should happen relatively rarely anyways...

**Comment by bdach** [comment]
Have pushed a commit with the intention of fixing the test failures. As it turns out the early import path was after a `delayEvents()` call but never flushed the events that could result from it firing, so I just moved the event delay start after the early path. Seemed to help when running tests locally.

**Comment by peppy** [comment]
Huge oversight there, good catch.

**Review by bdach — APPROVED** [review]

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
