### PR TITLE
Fix some argon circle layers not getting correct colour updates in editor

### LINKED ISSUE #20807: Changing combo in the editor doesn't update correctly with the Argon skin
### Discussed in https://github.com/ppy/osu/discussions/20804

<div type='discussions-op-text'>

<sup>Originally posted by **Gabixel** October 18, 2022</sup>
With the Argon skin, when you toggle the "new combo" option in an object that's in the past of the timeline, this happens:

image

Here's a video:

https://user-images.githubusercontent.com/43073074/196263661-7c891a02-e9bb-4e7b-9a32-cabe078ed8c0.mp4

</div>

### PR DESCRIPTION
**Pull request by peppy**
Kinda ugly, not sure how to handle better. The important change is running `ClearTransforms()` and reapplying the state change when accent colour changes.

Closes #20807.

### CODE REVIEW

**Review by smoogipoo — DISMISSED** [review]

**Comment by smoogipoo** [comment]
It's even more broken than before...

https://user-images.githubusercontent.com/1329837/196658833-ed3d5371-bfc1-4b2e-9f66-3c22c0e9d615.mp4

Notice how after I change the combo, the outer border is now completely gone.

**Comment by peppy** [comment]
That's super weird, it was working fine across multiple tests for me...

**Comment by peppy** [comment]
I don't know how to fix this. It's silly.

**Review by frenzibyte — APPROVED** [review]
Should work correctly now.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
