### PR TITLE
Fix breaks not showing unless already ordered in the beatmap file

### LINKED ISSUE #28717: Break not showing in lazer
### Type

Game behaviour

### Bug description

The game doesn't show the break countdown in lazer.
There are three breaks in this beatmap, and the first and second break show but the last doesn't.

### Screenshots or videos

image

image

### Version

2024.625.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16077902/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by frenzibyte**
- Closes #28717 

`BreakOverlay` shows and hides by populating transforms at the designated periods using `BeginAbsoluteSequence`. The logic expects the breaks list to be ordered chronologically, otherwise the transforms of the earlier break periods will overwrite any transforms made later (and therefore make later break periods not have the overlay visible as seen in #28717).

This can be solved locally in `BreakOverlay` by reordering the break periods before applying the transforms, but I feel it's generally natural to expect such lists to be ordered beforehand, so I solved this differently by changing `IBeatmap.Breaks` to be a `SortedList` instead (similar to `ControlPointInfo` etc.).

Before:

https://github.com/ppy/osu/assets/22781491/df9364df-382d-43c3-adb2-11eb7a3b9a63

After:

https://github.com/ppy/osu/assets/22781491/fd926c1b-4387-4939-aec5-96b33b4341e6

### CODE REVIEW

**Comment by bdach** [comment]
Did you look into whether this can be tested? I'd like it to be tested if at all possible.

**Comment by smoogipoo** [comment]
I have slight concerns about the amount of extra stuff we're doing every beatmap conversion. This is effectively doing an O(n log n) operation every convert, on top of what I'd already consider to be wasteful.

As I've mentioned previously, I'd like Beatmap to be treated as a plain old data model, whereas this is adding (albeit hidden) logic to it. The same is done at parse time for HitObjects.

Maybe it's not an issue here since it's breaks so N is expected to be very low, though.

I'll hand this off to another reviewer to evaluate whether my concerns are worthwhile at this point.

**Comment by bdach** [comment]
> This is effectively doing an O(n log n) operation every convert

Given I'd realistically expect n<10 in this case then I see this as a moot concern. I'll profile if you're concerned but I'm 99% sure this won't even show up.

A local sort could work but I think this is a good invariant to put down. We already enforce start time ordering on hitobjects and control points.

**Comment by frenzibyte** [comment]
> Did you look into whether this can be tested (the part where breaks do not display, specifically)? I'd like it to be tested if at all possible.

The problem with them not displaying is due to `BreakOverlay` taking an unordered list of break periods, i.e. due to unexpected behaviour. I'm not sure how I can write a test case for that. The best I can do is to write a test case that does all of the steps in https://github.com/ppy/osu/issues/28717#issuecomment-2213346552 and then check if the break periods are ordered or not, but I felt that would be too much.

I meant to add some videos showcasing the issue and compare between master & PR, but I had to leave desk abruptly. It's attached now.

> As I've mentioned previously, I'd like Beatmap to be treated as a plain old data model, whereas this is adding (albeit hidden) logic to it. The same is done at parse time for HitObjects.

I wouldn't mind following the path of simplicity myself. At first, I've had some concerns about using `SortedList`, but as mentioned above, it doesn't really matter since it can't be that large. I think `SortedList` just makes it more convenient to expose the data in an ordered fashion, and simplify code in many places. It doesn't include logic that could end up backfiring like bindables would.

Not using `SortedList` is also possible. Break periods are mutated in limited places, and we can make such places responsible for reordering the breaks.

**Comment by bdach** [comment]
> I'm not sure how I can write a test case for that

Surely you can imagine a way? Something like a player instance, with a manual backing clock and 2 breaks specified out of order? Seek to the middle of first break, assert that the overlay is showing?

**Comment by frenzibyte** [comment]
A realistic test case is what I mean, but I guess intentionally adding break periods out of order is technically possible (as one could do so in the `.osu` file), so sure, can do that.

**Comment by bdach** [comment]
### Profiling (release configuration, captured using tracing configuration)

On https://osu.ppy.sh/beatmapsets/972#osu/9007 (55 breaks, which I consider to be close to, if not the peak of sane edge cases):

image

On user's beatmap from the issue thread (3 breaks):

image

Based on these results I personally conclude that performance worries here are, as I suspected, unsubstantiated and not worthy of further scrutiny.

**Review by bdach — APPROVED** [review]

**Pull request merged**
