### PR TITLE
Fix song select filter and footer not absorbing input from carousel

### LINKED ISSUE #8412: Beatmaps behind FilterControl can be selected
**Screenshots or videos showing encountered issue:** 

FilterControl

**osu!lazer version:** 2020.320.1

### PR DESCRIPTION
**Pull request by Joehuu**
Resolves https://github.com/ppy/osu/issues/8412.

### CODE REVIEW

**Review by bdach — CHANGES_REQUESTED** [review]
Should block hover too:

image

**Comment by peppy** [comment]
This used to be a thing, weird it somehow disappeared.. Probably worth blaming to see how/why.

**Comment by naoey** [comment]
It was removed [here](https://github.com/ppy/osu/commit/c4bed0e6d29944cb6045267a3a4fdd17cf40bf34#diff-a01b1cbe157844fa32dc9168176bbcf8L195)

**Comment by peppy** [comment]
image

This doesn't really explain why..

**Review by peppy — APPROVED** [review]
Seems to feel correct

**Pull request merged**
