### PR TITLE
Fix pressing escape quickly unexpectedly exiting gameplay

### LINKED ISSUE #2033: Pressing escape on continuing causes the game to return to song select
Pressing esc right after continuing causes the game to exit to song select, instead of re-pausing or ignoring the second input.
https://streamable.com/4igjx

### PR DESCRIPTION
**Pull request by UselessToucan**
Resolves #2033

### CODE REVIEW

**Comment by peppy** [comment]
Doesn't this cause gameplay to instantly start again?

**Comment by UselessToucan** [comment]
> Doesn't this cause gameplay to instantly start again?

I guess it is critical only when you are in a hot place(for example, in the middle of a "star" pattern).
Also, I guess we can implement something like orange "click to continue" hitcircle which we have in osu! stable.

**Comment by Aergwyn** [comment]
>Also, I guess we can implement something like orange "click to continue" hitcircle which we have in osu! stable.

Can? I think it's needed because that thing is the greatest anti-cheat.

**Comment by peppy** [comment]
It needs to be implemented, but is likely out of the scope of this PR. In this PR, the delay should not be removed IMO.

**Review by peppy — APPROVED** [review]

**Pull request merged**
