### PR TITLE
Add precise rotation control to osu! editor

### LINKED ISSUE #12045: Mappers coming from stable expect key binding brings up a rotate control
currently there are a lot of editor shortcuts that almost all mappers use constantly (such as "ctrl + shift + r" for rotation) but in lazer this shortcut randomises the skin that you are using (even inside the editor)

as mappers have been relying on muscle memory shortcuts to streamline the mapping process for over a decade now, it feels weird to change or overwrite these,

one solution would be to just disable these new lazer shortcuts for *only* the editor and have the stable shortcuts take priority over them, how does this solution sound to you?

(editor section for a bank of all current shortcuts https://osu.ppy.sh/wiki/en/Shortcut_key_reference)

### PR DESCRIPTION
**Pull request by bdach**
- Closes https://github.com/ppy/osu/issues/12045
- [x] Depends on https://github.com/ppy/osu-framework/pull/5967
- [x] Depends on framework package w/ the above
- [x] Depends on https://github.com/ppy/osu/pull/24431

https://github.com/ppy/osu/assets/20418176/2939201e-5e5e-4e88-b5d4-8eed7a98dd58

A few notes:

- Rotation is clamped to [-180deg, 180deg] range. Textbox inputs above that will be clamped to the range on focus loss/commit (not shown on above video)
- Stable also has a direction toggle (clockwise/counterclockwise). I didn't add it back as it seemed pointless and led to ambiguity (180deg CCW = -180deg CW)
- The hotkey is <kbd>Ctrl</kbd>-<kbd>R</kbd> to avoid clash with the global "random skin" binding.

### CODE REVIEW

**Comment by Walavouchey** [comment]
i haven't tried this branch but instead of clamping, wouldn't it be better to conveniently convert the angle to the equivalent one within -180 and 180? then if you have say 240 in your head you can type that instead of doing mental arithmetic (to get -120)

**Comment by peppy** [comment]
> i haven't tried this branch but instead of clamping, wouldn't it be better to conveniently convert the angle to the equivalent one within -180 and 180? then if you have say 240 in your head you can type that instead of doing mental arithmetic (to get -120)

The best compromise if we want this would be to change the allowed range to `-360 .. 360`:

```diff
diff --git a/osu.Game.Rulesets.Osu/Edit/PreciseRotationPopover.cs b/osu.Game.Rulesets.Osu/Edit/PreciseRotationPopover.cs
index 86112d9751..f09d6b78e6 100644
--- a/osu.Game.Rulesets.Osu/Edit/PreciseRotationPopover.cs
+++ b/osu.Game.Rulesets.Osu/Edit/PreciseRotationPopover.cs
@@ -45,8 +45,8 @@ private void load()
                     {
                         Current = new BindableNumber<float>
                         {
-                            MinValue = -180,
-                            MaxValue = 180,
+                            MinValue = -360,
+                            MaxValue = 360,
                             Precision = 1
                         },
                         Instantaneous = true

```

@bdach thoughts on this? I think it's probably okay, and may lead to a better UX (more flexibility at the cost of less precision when dragging the slider, but let's be real: this control is mainly for typing a value in).

**Comment by bdach** [comment]
No objections to changing to [-360, 360]. While @Walavouchey's proposal is technically feasible, it'd be rather finicky to implement given the structure of things.

Will apply when able (unless I get preempted).

**Comment by peppy** [comment]
I can make that change, but curious if you had anything lined up to fix the popover tests already?

**Comment by bdach** [comment]
Hmm, wasn't expecting them to fail. Pretty sure they were green locally as it's tradition. You can leave be, I'll look closer on Saturday.

**Comment by Theighlin** [comment]
I'm not a mapper, but have a couple of suggestions upon trying the branch:
 - Is there a keybind to change from playfield centre to selection centre? I instinctively tried using TAB, but it didn't work.
 - Pressing enter does not close the popover. This is helpful if the value inserted is not correct and needs to be changed, but i'd say it's better to just have it close (for when there is no doubt about the operation) and undo and rotate again via keybinds if needed (enter should close the popover but not cancel the selection).
 - Textbox's "0" is not selected when opening the popover, typing the numbers after the 0 directly works fine, but looks weird and doesn't work for negative numbers. (waiting on https://github.com/ppy/osu-framework/pull/5823 ?)

Sorry if these were already known / out of scope of this PR / there are reasons i don't know it was done this way.

**Comment by bdach** [comment]
Test failures should be resolved. Allowed rotation range expanded to [-360, 360].

> Is there a keybind to change from playfield centre to selection centre? I instinctively tried using TAB, but it didn't work.

There is not. I intentionally did not make one because reproducing winforms tab behaviour would have been a massive pain (because presumably people would want to be able to tab between the textbox and the toggle or whatever).

> Pressing enter does not close the popover. This is helpful if the value inserted is not correct and needs to be changed, but i'd say it's better to just have it close

Need more opinions on this because I prefer it the way it is. Compare: photoshop free transform tool.

> Textbox's "0" is not selected when opening the popover, typing the numbers after the 0 directly works fine, but looks weird and doesn't work for negative numbers.

This requires the PR you mention yes.

**Review by peppy — APPROVED** [review]

**Pull request merged**
