### PR TITLE
Improve results displays in daily challenge screen

### PR DESCRIPTION
**Pull request by bdach**
- Continuation of https://github.com/ppy/osu/issues/28136
- [x] Depends on https://github.com/ppy/osu/pull/28659

osu_2024-07-04_13-28-53

This is _borderline_ two pulls in one and is a bit chunky as a result but I'm PRing in one go because I'm a bit tired of the ceremony at this point. Will split on request (by commits).

The deets:

## [Add results screen for displaying arbitrary daily challenge scores](https://github.com/ppy/osu/commit/b29e535ca5372abc5461c434839c37c869f7ea8e)

At this point its primary usage is the daily challenge event feed (click the "xxxx points" text to show the score), but the leaderboard will be using this too shortly.

Because the playlists results screen that exists in `master` is hard-coupled to showing the *local user's* best result on a given playlist by way of hard-coupling itself to the relevant API request, allowing show of *arbitrary* score by ID requires a whole bunch of subclassery as things stand. Oh well.

Class naming is... best effort, due to the above.

## [Replace old bad daily challenge leaderboard with new implementation](https://github.com/ppy/osu/commit/5fa586848d81a03251798b00fb702ed8cb7f4c68)

- Actually shows scores rather than playlist aggregates (which are useful... in playlists, where there is more than one item)
- Actually allows scores to be shown by clicking on them
- Doesn't completely break down visually on smaller window sizes

The general appearance is not as polished as the old one in details but I wanted something quick that we can get out by next weekend.

Also includes the naive method of refetching scores once a new top 50 score is detected. I can add a stagger if required.

At this point I'd personally generally say that we can end here for an initial release of this feature by whenever next release happens (tentative date is end of next week?), but am open to feedback if there is opposition.

### CODE REVIEW

**Comment by peppy** [comment]
@bdach can you check on tests here? i think they need a fix

**Comment by peppy** [comment]
This is feeling pretty good.

One thing I noticed is that clicking a score from the event feed then hitting back will return to the main menu rather than the daily challenge screen.

**Review by peppy — COMMENTED** [review]
Code wise I don't really have any qualms. Just one issue with results presentation.

**Review by peppy — APPROVED** [review]
Let's get in and keep move forward

**Comment by bdach** [comment]
> Update: on a second try I couldn't make this happen again...

I can't make this happen either.

> although after viewing results the event feed did empty out which felt a bit weird.

Well this is _sort of_ intentional, each event is only supposed to stay on screen for a set amount of time once shown and other screens being pushed don't really affect that in any capacity.

**Pull request merged**
