### PR TITLE
Autoscroll playlist on song change

### LINKED ISSUE #6368: Music player's list never jumps to now playing song
**Describe the bug:** It probably should when you open it and maybe when song changes

**Screenshots or videos showing encountered issue:** 

**osu!lazer version:** 2019.930

**Logs:**

### PR DESCRIPTION
**Pull request by UselessToucan**
resolves #6368

### CODE REVIEW

**Comment by bdach** [comment]
The actual change works fine, but I'm unconvinced it needs its own separate setting in its own separate section.

**Comment by UselessToucan** [comment]
> I'm unconvinced it needs its own separate setting in its own separate section

I may want not to have the autoscrolling. I.e. it should be configurable.

**Comment by iiSaLMaN** [comment]
@UselessToucan I believe what @bdach said is that it shouldn't have it's own sub-section. but rather, I think this shouldn't be in the audio section, but maybe in the UI sub-section.

**Comment by bdach** [comment]
> @UselessToucan I believe what @bdach said is that it shouldn't have it's own sub-section. but rather, I think this shouldn't be in the audio section, but maybe in the UI sub-section.

No, I actually don't think it needs to be a setting at all. I understand there might be a UX concern that autoscroll can interfere with the user manually scrolling to find a song, but that would be broken regardless of the setting. If we want to handle that cleanly then I guess a manual scroll could prevent an autoscroll until some event happens (i.e. user manually selects a song or closes the playlist).

**Comment by peppy** [comment]
Should be default behaviour and not a setting.

**Comment by peppy** [comment]
This fails if the playlist isn't visible at the point the scroll happens, but that is a separate issue which likely requires a framework fix, so I think it's fine to move ahead with this as-is.

**Pull request merged**
