### PR TITLE
Fix latency certifier

### PR DESCRIPTION
**Pull request by alion02**
Partially resolves #21868 by removing draw and update rate limits, as per [this wiki page](https://github.com/ppy/osu/wiki/Latency-and-unlimited-frame-rates#why-is-the-latency-certifier-running-at-unlimited-draw-frames). The FPS counter turning red after changing resolution while on the latency certifier screen is probably a framework-level problem that I am not experienced enough to deal with.

### CODE REVIEW

**Comment by peppy** [comment]
The frame rate is intentionally capped in the latency certifier. I haven't had a chance to reply to your thread yet, but I will try to do so at some point.

You can read the attached wiki article to get some more context.

Going to close this for now as I do not believe it's the correct direction.

**Comment by alion02** [comment]
Right now, the behavior of the latency certifier is changed by the action of changing the resolution. That much is clearly a bug. Also, the attached wiki article explicitly states that the latency certifier is "running at unlimited draw frames", which it currently is not.

**Comment by peppy** [comment]
The process was never intended to test draw (it can't, because the artificial limiting cannot limit in such a way). It is only intended to find a good frame limiter for a user between 60 and 1000.

**Comment by alion02** [comment]
Latency is not the only metric that matters when choosing a good frame limiter. What exactly is the issue that the latency certifier has when the user is using it in a way other than the intended? Is the resulting recommended frame limiter achieved invalid somehow?

**Comment by peppy** [comment]
If you're noticing changes above 1,000hz then the problem likely lies elsewhere.

In lazer we will only be supporting up to 1,000hz officially. We still have other improvements to make elsewhere (audio, nvidia reflex, newer renderer api). Please look forward to these to give you more options.

You are also welcome to remain on stable until lazer is comfortable to you.

I'll lock this thread for now as we generally have other goals right now and don't have discussions in PRs. You're welcome to open a discussion, but do understand that things are already very locked in and it will likely not result in any changes short term as too many other pieces of the puzzle are shifting.

**Pull request closed without merging**
