### PR TITLE
Add global key bindings for changing current game mode

### LINKED ISSUE #2509: Game mode change shortcuts not implemented
Using Ctrl+1, Ctrl+2 , Ctrl+3, Ctrl+4 to switch between gameplay modes like in stable isn't yet implemented.

### PR DESCRIPTION
**Pull request by UselessToucan**
resolves #2509 
https://youtu.be/JufcJZ6MCuo

### CODE REVIEW

**Comment by peppy** [comment]
Rulesets should never be hardcoded.

This functionality should be done inside the toolbar control that handles rulesets, and should be dynamic based on loaded rulesets.

**Comment by smoogipoo** [comment]
I don't know if we want this in the first place.

Also to add to @peppy 's comment the current implementation will throw an exception during gameplay.

**Comment by ocboogie** [comment]
@UselessToucan I can try to work on this if you would like?

**Comment by peppy** [comment]
Closing in favour of #2532.

**Pull request closed without merging**
