### PR TITLE
Fix SongSelect context menu priority

### LINKED ISSUE #22644: Song select context menu is not topmost on screen
### Type

Game behaviour

### Bug description

leaderboard appears on top of context menu. when trying to scroll the context menu it scrolls the leaderboard instead, the context menu should take priority. the menu made its way all the way over there cause I had a long collection name.

### Screenshots or videos

https://user-images.githubusercontent.com/43836438/218884103-e5bf8351-cf2b-4c86-bbdf-85cc494a424a.mp4

### Version

2023.207.0

### Logs

[input.log](https://github.com/ppy/osu/files/10737663/input.log)
[network.log](https://github.com/ppy/osu/files/10737664/network.log)
[performance.log](https://github.com/ppy/osu/files/10737665/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10737666/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10737667/updater.log)
[database.log](https://github.com/ppy/osu/files/10737668/database.log)

### PR DESCRIPTION
**Pull request by MaxKruse**
Fixes #22644 by changing the rendering order of elements to the following:

1. Wedge Background (used for highlighting the carousel area)
2. BeatmapDetails (leaderboards) 
3. An empty spacer container
4. The beatmap carousel
5. The FilterControl 
6. The BeatmapInfoWedge

This was my first time working with the drawables directly, if there are any semantinc issues I am already sorry - this seemed like the simplest solution.

Before:

https://user-images.githubusercontent.com/10248041/220471266-955a7b9f-ac29-42aa-b765-cbda657975bf.mp4

After:

https://user-images.githubusercontent.com/10248041/220471294-0ab8318b-1e1c-4d5f-b60a-711fc6e4cf93.mp4

### CODE REVIEW

**Comment by MaxKruse** [comment]
As a small consideration in cases this happens again: ContextMenus as of right now are always in the same "layer" as the element they stem from. This might not always be expected behaviour, context menus should be topmost everytime from a user's perspective. I think this would require a framework fix, though.

**Comment by mk56-spn** [comment]
> As a small consideration in cases this happens again: ContextMenus as of right now are always in the same "layer" as the element they stem from. This might not always be expected behaviour, context menus should be topmost everytime from a user's perspective. I think this would require a framework fix, though.

i dont think this would require a framework fix, something like invoking a menu thats a direct child of the osu screen you are on and adding it in at minimum depth *should* work fine unless im missing something

**Comment by peppy** [comment]
You haven't shown the edge case in your video of how the new behaviour looks when the context menu is under the wedge.

**Comment by MaxKruse** [comment]
> You haven't shown the edge case in your video of how the new behaviour looks when the context menu is under the wedge.

Before (master):

https://user-images.githubusercontent.com/10248041/220594714-2953c847-5828-499e-a108-d004022aab13.mp4


After (PR):

https://user-images.githubusercontent.com/10248041/220594209-0326f174-f64f-4ca0-a81d-48890ddd7f49.mp4

If the context menu is supposed to be above the beatmapinfo wedge as well, i am not sure how to achieve this due to the backdrop the `FilterControl` provides across the top.



> i dont think this would require a framework fix, something like invoking a menu thats a direct child of the osu screen you are on and adding it in at minimum depth _should_ work fine unless im missing something

i tried to figure out the logic behind the context menu rendering, but it seems very opaque to me and im not quite sure where to look for any behaviour relating to this.

**Comment by peppy** [comment]
All is relies on is where the parent `OsuContextMenuContainer` is.

For instance, this would achieve moving it above everything in song select:

```diff
diff --git a/osu.Game/Screens/Select/BeatmapCarousel.cs b/osu.Game/Screens/Select/BeatmapCarousel.cs
index 774ecc2c9c..2e0618effe 100644
--- a/osu.Game/Screens/Select/BeatmapCarousel.cs
+++ b/osu.Game/Screens/Select/BeatmapCarousel.cs
@@ -23,7 +23,6 @@
 using osu.Game.Configuration;
 using osu.Game.Database;
 using osu.Game.Graphics.Containers;
-using osu.Game.Graphics.Cursor;
 using osu.Game.Input.Bindings;
 using osu.Game.Screens.Select.Carousel;
 using osuTK;
@@ -164,18 +163,14 @@ private void loadBeatmapSets(IEnumerable<BeatmapSetInfo> beatmapSets)
         public BeatmapCarousel()
         {
             root = new CarouselRoot(this);
-            InternalChild = new OsuContextMenuContainer
+            InternalChildren = new Drawable[]
             {
-                RelativeSizeAxes = Axes.Both,
-                Children = new Drawable[]
+                setPool,
+                Scroll = new CarouselScrollContainer
                 {
-                    setPool,
-                    Scroll = new CarouselScrollContainer
-                    {
-                        RelativeSizeAxes = Axes.Both,
-                    },
-                    noResultsPlaceholder = new NoResultsPlaceholder()
-                }
+                    RelativeSizeAxes = Axes.Both,
+                },
+                noResultsPlaceholder = new NoResultsPlaceholder()
             };
         }
 
diff --git a/osu.Game/Screens/Select/SongSelect.cs b/osu.Game/Screens/Select/SongSelect.cs
index 661eec8e97..bf4e3884b0 100644
--- a/osu.Game/Screens/Select/SongSelect.cs
+++ b/osu.Game/Screens/Select/SongSelect.cs
@@ -25,6 +25,7 @@
 using osu.Game.Configuration;
 using osu.Game.Graphics;
 using osu.Game.Graphics.Containers;
+using osu.Game.Graphics.Cursor;
 using osu.Game.Graphics.UserInterface;
 using osu.Game.Input.Bindings;
 using osu.Game.Overlays;
@@ -175,105 +176,109 @@ private void load(AudioManager audio, OsuColour colours, ManageCollectionsDialog
                     RelativeSizeAxes = Axes.Y,
                     Width = 250,
                 },
-                new VerticalMaskingContainer
+                new OsuContextMenuContainer
                 {
-                    Children = new Drawable[]
+                    RelativeSizeAxes = Axes.Both,
+                    Child = new VerticalMaskingContainer
                     {
-                        new GridContainer // used for max width implementation
+                        Children = new Drawable[]
                         {
-                            RelativeSizeAxes = Axes.Both,
-                            ColumnDimensions = new[]
+                            new GridContainer // used for max width implementation
                             {
-                                new Dimension(),
-                                new Dimension(GridSizeMode.Relative, 0.5f, maxSize: 850),
-                            },
-                            Content = new[]
-                            {
-                                new Drawable[]
+                                RelativeSizeAxes = Axes.Both,
+                                ColumnDimensions = new[]
                                 {
-                                    wedgeBackground = new ParallaxContainer
+                                    new Dimension(),
+                                    new Dimension(GridSizeMode.Relative, 0.5f, maxSize: 850),
+                                },
+                                Content = new[]
+                                {
+                                    new Drawable[]
                                     {
-                                        ParallaxAmount = 0.005f,
-                                        RelativeSizeAxes = Axes.Both,
-                                        Alpha = 0,
-                                        Anchor = Anchor.Centre,
-                                        Origin = Anchor.Centre,
-                                        Child = new WedgeBackground
+                                        wedgeBackground = new ParallaxContainer
                                         {
+                                            ParallaxAmount = 0.005f,
                                             RelativeSizeAxes = Axes.Both,
-                                            Padding = new MarginPadding { Right = -150 },
+                                            Alpha = 0,
+                                            Anchor = Anchor.Centre,
+                                            Origin = Anchor.Centre,
+                                            Child = new WedgeBackground
+                                            {
+                                                RelativeSizeAxes = Axes.Both,
+                                                Padding = new MarginPadding { Right = -150 },
+                                            },
                                         },
-                                    },
-                                    carouselContainer = new Container
-                                    {
-                                        RelativeSizeAxes = Axes.Both,
-                                        Padding = new MarginPadding
+                                        carouselContainer = new Container
                                         {
-                                            Top = FilterControl.HEIGHT,
-                                            Bottom = Footer.HEIGHT
-                                        },
-                                        Child = new LoadingSpinner(true) { State = { Value = Visibility.Visible } }
-                                    }
-                                },
-                            }
-                        },
-                        FilterControl = new FilterControl
-                        {
-                            RelativeSizeAxes = Axes.X,
-                            Height = FilterControl.HEIGHT,
-                            FilterChanged = ApplyFilterToCarousel,
-                        },
-                        new GridContainer // used for max width implementation
-                        {
-                            RelativeSizeAxes = Axes.Both,
-                            ColumnDimensions = new[]
+                                            RelativeSizeAxes = Axes.Both,
+                                            Padding = new MarginPadding
+                                            {
+                                                Top = FilterControl.HEIGHT,
+                                                Bottom = Footer.HEIGHT
+                                            },
+                                            Child = new LoadingSpinner(true) { State = { Value = Visibility.Visible } }
+                                        }
+                                    },
+                                }
+                            },
+                            FilterControl = new FilterControl
                             {
-                                new Dimension(GridSizeMode.Relative, 0.5f, maxSize: 650),
+                                RelativeSizeAxes = Axes.X,
+                                Height = FilterControl.HEIGHT,
+                                FilterChanged = ApplyFilterToCarousel,
                             },
-                            Content = new[]
+                            new GridContainer // used for max width implementation
                             {
-                                new Drawable[]
+                                RelativeSizeAxes = Axes.Both,
+                                ColumnDimensions = new[]
                                 {
-                                    LeftArea = new Container
+                                    new Dimension(GridSizeMode.Relative, 0.5f, maxSize: 650),
+                                },
+                                Content = new[]
+                                {
+                                    new Drawable[]
                                     {
-                                        Origin = Anchor.BottomLeft,
-                                        Anchor = Anchor.BottomLeft,
-                                        RelativeSizeAxes = Axes.Both,
-                                        Padding = new MarginPadding { Top = left_area_padding },
-                                        Children = new Drawable[]
+                                        LeftArea = new Container
                                         {
-                                            beatmapInfoWedge = new BeatmapInfoWedge
+                                            Origin = Anchor.BottomLeft,
+                                            Anchor = Anchor.BottomLeft,
+                                            RelativeSizeAxes = Axes.Both,
+                                            Padding = new MarginPadding { Top = left_area_padding },
+                                            Children = new Drawable[]
                                             {
-                                                Height = WEDGE_HEIGHT,
-                                                RelativeSizeAxes = Axes.X,
-                                                Margin = new MarginPadding
+                                                beatmapInfoWedge = new BeatmapInfoWedge
                                                 {
-                                                    Right = left_area_padding,
-                                                    Left = -BeatmapInfoWedge.BORDER_THICKNESS, // Hide the left border
+                                                    Height = WEDGE_HEIGHT,
+                                                    RelativeSizeAxes = Axes.X,
+                                                    Margin = new MarginPadding
+                                                    {
+                                                        Right = left_area_padding,
+                                                        Left = -BeatmapInfoWedge.BORDER_THICKNESS, // Hide the left border
+                                                    },
                                                 },
-                                            },
-                                            new Container
-                                            {
-                                                RelativeSizeAxes = Axes.Both,
-                                                Padding = new MarginPadding
+                                                new Container
                                                 {
-                                                    Bottom = Footer.HEIGHT,
-                                                    Top = WEDGE_HEIGHT,
-                                                    Left = left_area_padding,
-                                                    Right = left_area_padding * 2,
+                                                    RelativeSizeAxes = Axes.Both,
+                                                    Padding = new MarginPadding
+                                                    {
+                                                        Bottom = Footer.HEIGHT,
+                                                        Top = WEDGE_HEIGHT,
+                                                        Left = left_area_padding,
+                                                        Right = left_area_padding * 2,
+                                                    },
+                                                    Child = BeatmapDetails = CreateBeatmapDetailArea().With(d =>
+                                                    {
+                                                        d.RelativeSizeAxes = Axes.Both;
+                                                        d.Padding = new MarginPadding { Top = 10, Right = 5 };
+                                                    })
                                                 },
-                                                Child = BeatmapDetails = CreateBeatmapDetailArea().With(d =>
-                                                {
-                                                    d.RelativeSizeAxes = Axes.Both;
-                                                    d.Padding = new MarginPadding { Top = 10, Right = 5 };
-                                                })
-                                            },
-                                        }
+                                            }
+                                        },
                                     },
-                                },
+                                }
                             }
                         }
-                    }
+                    },
                 },
                 new SkinComponentsContainer(new SkinComponentsContainerLookup(SkinComponentsContainerLookup.TargetArea.SongSelect))
                 {

```

I haven't checked whether this has any changes in behaviour, but it does fix the wedge issue:


https://user-images.githubusercontent.com/191335/220600536-5d336895-7edb-458b-bf42-9f315c394c37.mp4

**Comment by MaxKruse** [comment]
That seems to work just fine. Behaviour seems correct as far as i can tell, and was the only actual fix needed in this case - i worked into a very confusing and wrong direction at first. Thanks for the help here.

As the git history is honestly a mess due to my lack of ability, im going to re-PR this in a cleaner way

**Pull request closed without merging**
