### PR TITLE
Fix gameplay HUD load not always completing if initially hidden

### PR DESCRIPTION
**Pull request by smoogipoo**
This test was added in https://github.com/ppy/osu/pull/14337 to show that the failure case had been fixed. The PR set the expectation that HUD components should complete their load even if the HUD is set to not visible. However the test only passed because `ShowHud` animates the fadeout of components over 300ms such that there is a period where load can complete during the fadeout.
The failure case had not actually been fixed and we've been having intermittent test failures such as https://github.com/ppy/osu/pull/14474/checks?check_run_id=3407903613 since.

I'm not sure if there's a better way to do this than `Reload()` - ideally I'd like to inject some long-running-load component and control everything precisely, but this structure doesn't seem to lend itself to that. Accepting suggestions.

### CODE REVIEW

**Comment by frenzibyte** [comment]
Right, I was under the thought that schedulers invoke even when the drawable is hidden, but they're controlled by `IsPresent` as well, unlike transforms.

I would've gone for setting `AlwaysPresent` to true in `HUDOverlay` since that's the place it's hidden at, and where it would make sense to make the container always be present, but both solutions work anyways.

**Comment by smoogipoo** [comment]
Just understand that presence is a thing for optimisation purposes first and foremost. `AlwaysPresent` should not be used unless you've considered that and there's no better alternative.

**Review by frenzibyte — DISMISSED** [review]

**Comment by peppy** [comment]
Just to ease review of this, which scheduled invocations are relevant here?

**Comment by smoogipoo** [comment]
The LCA callback.

**Comment by peppy** [comment]
Right, had a feeling that was the case. A bit of a hidden schedule..

**Review by peppy — APPROVED** [review]

**Pull request merged**
