### PR TITLE
Fix Username overlap

### PR DESCRIPTION
**Pull request by DevSDK**
I've find something weird overlap username and timestamp in chat line.
Maybe, they register long name before username limitation.
I add normalizeUsername function that work substring and append '...' when username length over 15.

Before,
a
After,
b

- [x] Depends on #2075.

### CODE REVIEW

**Comment by Aergwyn** [comment]
Does it still work with usernames like "WWWWWWWWWWWWWWW"? The font is not monospaced so it could still overlap if they have wide characters (like W usually is). I like this idea though.

**Comment by DevSDK** [comment]
Well, Is completely broken like 
this:
c

Well, I can find solution that make fix-width username text and padding width change 200 to 250.

And see 
d

And you can see when normal Username length low of 15
e
And Username length higher of 15.
f

How do you think about this change? ;)

**Comment by Aergwyn** [comment]
I'm not sure. Looks like a waste of space in most cases.

I remember I did something once in a project where I calculated the expected width of the text and cut as much as needed to make it fit (with 3 dots taken into account).
I'm not sure if we'd be able to do something like that here so it would be more flexible. But I'm also not sure how expensive that would be.

**Comment by jorolf** [comment]
Maybe this should already be supported by SpriteText? I could imagine others using it too

**Comment by DevSDK** [comment]
Umm, I agree your opinion.
But, Not calculate width when property ```Text``` set some text in ```SpriteText``` .
So, I think other way that summery of every username character font-width and cut text when calculate value over 200.
I would like to hear your advice. THX :)

**Comment by FreezyLemon** [comment]
@jorolf Maybe this should be implemented in a class inheriting from SpriteText instead of SpriteText itself? I can see this getting very expensive for larger amounts of text, especially since in most cases, every word of text is its own SpriteText instance (so word wrapping works).
Also, not every SpriteText needs to calculate this exactly because word wrapping exists. The usual "procedure" would be to just wrap around a line, which is fine for most cases. This kind of thing should probably only be done if the text is in a confined space of some sorts.

**Comment by default0** [comment]
@FreezyLemon it is only expensive if it gets done (plus, depending on the exact implementation, something like ``AutoEllipsis`` might not be as bad as you imagine), so being able to toggle the behaviour via a bool on ``SpriteText`` is probably just as feasible and better API-wise, as it will be easier to discover the feature for users.

**Comment by Aergwyn** [comment]
Something for the chat messages themselves has to be done too because single words can escape the window if they're too long.

**Comment by FreezyLemon** [comment]
I was thinking about that possibility of a `bool` too, and it works just fine. I would prefer an inheriting class to split the logic a bit, but it's probably down to preference at this point.

The performance comment was not based on the "how expensive is this for a single sprite", but more on the sheer amount of sprites that get loaded. I've been working on the Chat for a bit now and it's quite an impact even with simple changes, since every single chatline gets loaded for the active channel (and every word in a chatline is its own spritetext instance).

**Comment by DevSDK** [comment]
Well, Username limit low of 15.
If we implement that calculate every username, It can be iterate maximum 15 in every chatline.
So, If we do that, we need width of every character.
So, It can be call CreateCharacterDrawable('D').DrawWidth maximum 15.
Humm. How can i choice that methods:

1. Make Fix-Width Username text and padding value set 200 to 250.

2. Calculate width every chatline and cut text when over 200.

Have a good day :)

**Review by kmoore43 — APPROVED** [review]

**Comment by peppy** [comment]
How were you testing this? There doesn't look to be a usable testcase.

**Comment by peppy** [comment]
Yes, it would be good to have a test case for this. It would probably involve taking the existing TestCaseChatDisplay and removing the online retrieval, adding dummy content

**Comment by DevSDK** [comment]
Oh I see. 
I'll try to write test code  as soon as possible like weekend  :)

**Comment by DevSDK** [comment]
I've updated my code. Please check it. :)

**Comment by peppy** [comment]
Added dependency on #2075.

**Comment by peppy** [comment]
The overlapping looks very weird and unwanted.

**Comment by DevSDK** [comment]
you've commented issue was seem to be "fixed-wide font issue" that I've changed . And I've find still overlap when I remove that fixed-wide code. So  I chage font-size  20 to 16 and remove fixed-width then it seem to image

image

**Comment by peppy** [comment]
I tested with the latest commits, if that's what you're asking.

**Comment by Aergwyn** [comment]
Jeez the amount of empty space looks horrible. I'd really love if we'd be able to determine how wide a certain text will be to determine if trimming is necessary. This way the amount of empty space could be minimized.

**Comment by peppy** [comment]
I've updated and resolved conflicts on this, but the character spacing is still as broken as last time it was visited.

**Comment by peppy** [comment]
Closing as abandoned.

**Pull request closed without merging**
