### PR TITLE
Add support for the auto sample addition bank in the editor

### PR DESCRIPTION
**Pull request by OliBomby**
Requires:
- [x] https://github.com/ppy/osu/pull/28863

UX works identical to osu! stable for addition samples only.

The implementation adds a new boolean property `EditorAutoBank` to `HitSampleInfo`. This seems like the best solution because it doesn't ever set the actual sample bank to `auto`, so the `HitSampleInfo` always has the correct bank and it doesn't need to inherit the bank before the deciphering the hitsound to play. With this the flow for gameplay is unchanged.

An alternative implementation where you set the `HitSampleInfo.Bank` to `auto` would require you to figure out the actual bank before playing the sample. This seems like a messier solution.
chrome_fEJHPxya9O
(idk how to embed the diff in a fancy way)

### CODE REVIEW

**Comment by peppy** [comment]
Forcefully rebasing this on https://github.com/ppy/osu/pull/28863 to avoid resolving conflicts twice. Honestly this could probably have been part of that PR since I have to review using this to test the full flow regardless 😅 .

**Comment by peppy** [comment]
Doesn't seem to work
https://github.com/user-attachments/assets/af2aff8b-da30-4324-8b5f-676bff73aed3

**Comment by OliBomby** [comment]
> Doesn't seem to work
> 
>  osu.2024-10-01.at.07.54.31.mp4

This is working as intended. You can't set Auto normal bank on selection because there is no fallback value, and you cant set addition bank on an object with no additions. You must add an addition first.

Maybe it should disable the options to better indicate this.

**Comment by peppy** [comment]
Yeah I dunno, it doesn't compute for me. Even with what you just said.

**Comment by OliBomby** [comment]
I've added a tooltip that explains why the addition banks are not usable when there are no addition samples in the selection.

Also I made it reset to auto sample bank whenever you clear the selection. This matches stable behaviour and prevents you from accidentally using a sample bank lingering from the last object you've selected.

Here's how it all works:

https://github.com/user-attachments/assets/1241ceca-0b72-40fa-970c-4fcf99896f78

**Comment by peppy** [comment]
My remaining apprehension is that "auto" mode for non-additions has a meaning only during placement, and that feels a bit weird. Could that button do anything during selection, or if not, maybe it should show a tooltip that it's only valid during placement?

**Review by peppy — COMMENTED** [review]
Code generally looks fine. One remaining concern as commented.

**Comment by OliBomby** [comment]
> My remaining apprehension is that "auto" mode for non-additions has a meaning only during placement, and that feels a bit weird. Could that button do anything during selection, or if not, maybe it should show a tooltip that it's only valid during placement?

There's no reasonable thing to inherit the bank from for non-additions. There's no beatmap-wide sample bank default, and inheriting from the previous object (like during placement) wouldn't make sense at all after placement. So I'll just show a tooltip explaining how it works.

**Comment by peppy** [comment]
Sure that works. I've also added a disabled state to better indicate that buttons are in a non-usable state:


https://github.com/user-attachments/assets/65aa3e9e-8892-40f2-89d7-2eb6f5622ab1

**Review by peppy — DISMISSED** [review]

**Comment by OliBomby** [comment]
I don't see the disable state working, am I missing something?

https://github.com/user-attachments/assets/2ab94f8d-8822-4d56-a2a2-e1b629823518

**Comment by peppy** [comment]
> I don't see the disable state working, am I missing something

Seems like some of my changes didn't get committed properly. I had exactly what you added in [5b92a9f](https://github.com/ppy/osu/pull/29648/commits/5b92a9ff595cbbc5c42f1f3d95d94c1c1c05f7ed) so all good 👍 .

**Review by peppy — APPROVED** [review]

**Pull request merged**
