### PR TITLE
Change default HoverSounds/HoverClickSounds samples

### PR DESCRIPTION
**Pull request by nekodex**
default samples -> button samples
soft samples -> default samples

- [x] depends on #13452
- [x] depends on ppy/osu-resources#127

### CODE REVIEW

**Comment by bdach** [comment]
There are a few remaining local references to the old sample names which haven't been updated in this pull:

https://github.com/ppy/osu/blob/98d40a7d30f235abb3c62e397505ac786d14b51e/osu.Game/Graphics/UserInterface/DrawableOsuMenuItem.cs#L39-L40
https://github.com/ppy/osu/blob/98d40a7d30f235abb3c62e397505ac786d14b51e/osu.Game/Overlays/ChangelogOverlay.cs#L44

I would update myself, but I'm not necessarily sure that I'll be able to discern whether the result is what is actually wanted there.

**Review by bdach — CHANGES_REQUESTED** [review]
see above

**Comment by peppy** [comment]
Already fixed one, guess I was too precise with my searching and didn't find the changelog one. Will apply a fix.

**Comment by bdach** [comment]
That's strange, I couldn't see some of those commits in the github UI until now, apparently...

**Pull request merged**
