### PR TITLE
Attempt to fix timeline test failures

### PR DESCRIPTION
**Pull request by peppy**
It's not ideal but it might be enough to make things roughly work? I get it's not disposing the track, but I'm not sure that matters too much.

https://github.com/ppy/osu/actions/runs/3891064940/jobs/6640854828
https://teamcity.ppy.sh/buildConfiguration/Osu_Build/20555?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildChangesSection=true&expandBuildTestsSection=true

### CODE REVIEW

**Comment by bdach** [comment]
So, two things confuse me here:

- First of all, the linked github actions run is failing on line 73, not line 74 which this is attempting to fix, i.e.

  https://github.com/ppy/osu/blob/8e022ad4f90c744d0f12716683c610a384920704/osu.Game/Tests/Visual/EditorClockTestScene.cs#L73

  as in it's the *old* track that's not loaded. The teamcity link looks broke because I don't see this particular test failing on that run.

- More as an aside rather than something relevant to the failure - how does this even work?

  https://github.com/ppy/osu/blob/8e022ad4f90c744d0f12716683c610a384920704/osu.Game/Tests/Visual/EditorClockTestScene.cs#L60-L62

  `Beatmap.Value` is first assigned a value, but then the base call does this:

  https://github.com/ppy/osu/blob/8e022ad4f90c744d0f12716683c610a384920704/osu.Game/Tests/Visual/OsuTestScene.cs#L166-L168

  so doesn't that nullify the assignment entirely? Fixing that doesn't seem to fix the failure in the CI runs, mind, just something I'm baffled by as I attempt to make sense of all this.

**Comment by bdach** [comment]
Never mind, point 2 can be disregarded because the value is transferred from `Beatmap` to `parentBeatmap` before the bind... Very confusing.

So I think this is just a "change this to fix the right line" situation. I'll grab this if anyone else doesn't mind.

**Comment by bdach** [comment]
Fixed `OldValue.Track` potentially not being loaded too in https://github.com/ppy/osu/pull/22134/commits/403dd71a23cb26b4e580edfa9f223c7b87343530. I left the `NewValue.Track` stuff in because I figure it may as well be there for safety.

Unrequesting review from myself since I essentially touched this enough that it feels wrong to approve & merge myself. Would appreciate a second go.

**Review by frenzibyte — COMMENTED** [review]
So I wanted to have an understanding as to why this was occurring in the first place, and it's boiling down to `MusicController` not being fully loaded at the point of accessing the track in the test scene. And it's nothing to do with asynchronous load, but simply that `OsuGameBase` has always been using `AddInternal` for global components, which actually places them ahead of game content rather than behind it (due to content logic in `Game` constructor), thus resulting in this bug in the first place.

I'll push a fix in another PR as an alternative to this in order to get more attention to this flaw, as I'm sure it'll bite us 10 times more than we work around in indirect ways.

**Comment by peppy** [comment]
Mostly wanted to get this PR'd to see what failures looked like, but will close in favour of https://github.com/ppy/osu/pull/22141 as this was about as hacky as you can get.

**Pull request closed without merging**
