### PR TITLE
Add iOS file import support

### LINKED ISSUE #5272: Import .osk/.osz through Files app on iOS
In iOS, the Files app could let you add resources that you want in an app that supports it, so which means you can import your skins and beatmaps through it as well. Just like on PC, players are allowed to import their skins through a folder and placing it on its desired file location.
**Example:**
76999420-2865-40DF-9617-D3DF03BF74DD
4DF85DB8-CA08-4480-B3E8-B978D0B05799

### PR DESCRIPTION
**Pull request by dtsdao**
Fixes #5272
Be able to accept files via "Copy to" in the share menu.

### CODE REVIEW

**Comment by dtsdao** [comment]
This feature is of vital importance so it would be nice if you release a new TestFlight recently.😝

**Comment by swoolcock** [comment]
Would prefer that we don’t register on `public.item`.  We should only be opening URLs we support.

**Comment by dtsdao** [comment]
> Would prefer that we don’t register on `public.item`. We should only be opening URLs we support.

OK. I'll add custom UTI and commit later.

**Comment by dtsdao** [comment]
@swoolcock I edited the `Info.plist`. It seems perfect now.

**Comment by swoolcock** [comment]
Have you tested this?

**Comment by dtsdao** [comment]
Sure. I tested on iOS Simulator. It accepts `.osz`, `.osk` and `.osr` and refuses `.tar` or other types.

**Comment by swoolcock** [comment]
Related to https://github.com/ppy/osu/issues/5274 as they will both need to be implemented eventually.

**Comment by dtsdao** [comment]
This needs lots of changes to the website and application.
It would be tons of work to finish the URI Scheme parsing on all platforms.😑
Looking forward to its being accomplished.😉

**Comment by peppy** [comment]
Please don't PR from `master` in the future.

**Review by peppy — APPROVED** [review]

**Pull request merged**
