### PR TITLE
Fix unsupported Velopack splash icon

### PR DESCRIPTION
**Pull request by smallketchup82**
- Should be deployed with https://github.com/ppy/osu-deploy/pull/173

Turns out that Velopack doesn't support transparent .png's as the splashicon, leading to issues like this on installation:
image

Velopack supports a:
- High Resolution JPG
- PNG with non-transparent background

This PR reuses https://github.com/ppy/osu/blob/master/osu.iOS/Assets.xcassets/AppIcon.appiconset/300076680-5cbe0121-ed68-414f-9ddc-dd993ac97e62.png for the icon. Though, alternative designs are welcome.

Preview:
image
You can use [this release](https://github.com/smallketchup82/osu/releases/tag/2024.907.3) to test it (you must not have lazer installed first)

See https://github.com/ppy/osu-deploy/pull/173 for testing details

### CODE REVIEW

**Comment by peppy** [comment]
@arflyte got anything to use here? if you can search up the specs required and provide something by wednesday that would be good.

**Comment by arflyte** [comment]
Not exactly sure what Velopack is. Made JPGs.

osu!cookie black BG
osu!Cookie RedGrey BG
osu!cookie white BG

Additionally, if it helps: 

https://www.figma.com/design/9dyAxJqsNqwRIiAJMAxeko/osu!Cookie-v4b?node-id=0-1&t=rvYv91eIyBvg8IJA-1

**Comment by bdach** [comment]
Velopack = installer. 

That said we already have opaque icon stuff for mobile platforms: see https://github.com/ppy/osu/blob/master/osu.iOS/Assets.xcassets/AppIcon.appiconset/300076680-5cbe0121-ed68-414f-9ddc-dd993ac97e62.png. Maybe we can do the same here rather than non-descript single colour fill?

**Comment by arflyte** [comment]
What do you guys actually need. I humbly request context and I WILL provide the goods.

**Comment by bdach** [comment]
We use an external tool to provide the game with an installer. It's called velopack. Currently it does this when launched (apology for janky video but it chooses itself to run on my primary monitor and I can't be bothered to change it just for this):

https://github.com/user-attachments/assets/2aebfdd6-0709-44f0-8342-04568b59a176

It displays a splash window while it's silent-installing and the splash window looks terrible because it can't do transparency anymore (it used to). We need something better - non-transparent - to replace it. Notably probably with a bit of a gap underneath so that the progress bar can stop clipping the bottom of the logo. Also notably [the docs](https://docs.velopack.io/packaging/operating-systems/windows#installing) claim animated GIFs are supported contrary to what the OP says but I did not test this myself at this time so I cannot verify the veracity of that claim.

Do note that we're not in control of the duration of display of the thing so it should probably be best to keep it a static image. Or if we wanna try animated then it should be like those "spinner"/"scrubber" style displays but osu!-themed probably. Maybe one of us should confirm whether GIF works first though to avoid a waste of time.

**Comment by arflyte** [comment]
Created 2 types of PNG, which rounded corners and sharp. And another with JPG. It's rectangle for stylistic purposes. It seems fairly quickly, so not sure if animated GIF is worth it.

The rounded corners has no gradient alpha channels, so try that one first, may fix the weird issues.

Velopack Rounded
Velopack Sharp
Velopack Sharp

**Comment by peppy** [comment]
Rounded corners obviously won't work. The bottom bar is not rounded.

@smallketchup82 want to test the very vertical images and see if they look good?

**Comment by peppy** [comment]
I still think we can do better than just the osu logo. Some kind of loading text? Something special to make new users feel special? This just feels a bit of a cop-out.

**Comment by smallketchup82** [comment]
If we don't want just a simple osu! logo, maybe we could draw from the fanart contests? Or do a contest specifically for the splash icon? That might be overkill for something that'll only display on windows, and will probably only show for 10 seconds, but it's an idea nevertheless. If I were a new player, I'd enjoy a cozy osu! themed drawing while installing.

**Comment by peppy** [comment]
@smallketchup82 is there a reason this PR isn't just opened at osu-deploy side? it doesn't seem that this resource needs to be over on this repository for any good reason.

**Comment by smallketchup82** [comment]
Not really no, I was just doing as was done before. It should be completely fine to move the image to osu-deploy. Would you like me to do that when I have the time to?

**Comment by peppy** [comment]
I think it's probably best to have it in the same place it's being used, yeah. Less moving pieces for making modifications.

**Comment by smallketchup82** [comment]
Will be closing this now, I'll move everything to [this PR](https://github.com/ppy/osu-deploy/pull/173)

**Pull request closed without merging**
