### PR TITLE
Fix beatmap overlay stats showing modded values

### LINKED ISSUE #18842: Mods selected in song select affect beatmap info overlay's statistics section
### Discussed in https://github.com/ppy/osu/discussions/18840

<div type='discussions-op-text'>

<sup>Originally posted by **cdwcgt** June 25, 2022</sup>
image
image

I guess this shouldn't happen
</div>

### PR DESCRIPTION
**Pull request by Cwazywierdo**
Closes #18842

### CODE REVIEW

**Comment by bdach** [comment]
I don't know that I agree with this resolution. The alternative way to ensure that global mods don't influence the display that doesn't require boolean flags would be to cache an `IBindable<IReadOnlyList<Mod>>` that is always empty over the game-global one in the beatmap overlay.

**Comment by frenzibyte** [comment]
They way I had thought about was to move the modded values logic into a `SongSelect`-specific component that inherits from the beatmap overlay component, but the bindable way sounds better if can be done simply.

**Comment by Cwazywierdo** [comment]
Implemented the fix as described. Works great and is definitely much simpler.

**Comment by frenzibyte** [comment]
Make sure to add test coverage for any changes you PR when feasible, I've added one for you given the simplicity. Have also added a comment to explain the purpose of that bindable as it almost looked like an unused property with no effects. Looks to work.

**Review by frenzibyte — APPROVED** [review]

**Pull request merged**
