### PR TITLE
Add setting for mouse players in NoScope mod

### PR DESCRIPTION
**Pull request by Semro**
Since it's really challenging to adjust aim after spinners and breaks (at least using mouse) I've added a setting to show cursor during these parts.

Closes https://github.com/ppy/osu/discussions/15140

### CODE REVIEW

**Review by alikindsys — COMMENTED** [review]
just some stuff i noticed while looking at the diffs for this pr, since said pr interested me.
be aware thats been a *long* time since i contributed to the project and my knowledge of the game internals could (and most likely is) wrong in some aspects.

**Comment by bdach** [comment]
I'm not sure that the way the breaks are currently handled here (adding absolute sequences) is going to work properly, given that the old logic that touches alpha is still around. The test needs to actually test the behaviour rather than being a display-only thing.

**Comment by Semro** [comment]
> I'm not sure that the way the breaks are currently handled here (adding absolute sequences) is going to work properly, given that the old logic that touches alpha is still around. The test needs to actually test the behaviour rather than being a display-only thing.

Did I understand right that the `Update` method should be replaced with `targetAlpha.BindValueChanged` in `ApplyToDrawableRuleset` to drop old logic? Or is there another way to handle breaks without adding absolute sequences?

**Comment by Semro** [comment]
> Having alpha changed both by `Update()` per-frame logic as well as absolute sequences applied in `ApplyToDrawableRuleset` is both confusing and (I'm relatively certain) incorrect because one will invariably end up overwriting the other at some point.
> 
> A solution that I'd recommend is having everything happen in `Update()`, by having some sort of tracker object which knows if the current time is inside a break/spinner interval. See [`BreakTracker`](https://github.com/ppy/osu/blob/master/osu.Game/Screens/Play/BreakTracker.cs) for inspiration.

Applied suggested changes.
It doesn't make sense to use `IApplicableToDrawableRuleset` anymore, using `IApplicableToBeatmap` instead as suggested [here](https://github.com/ppy/osu/pull/15126#discussion_r730218362)
Renamed settings, the previous implementation couldn't handle hiding cursor after spinners and breaks.

**Review by peppy — CHANGES_REQUESTED** [review]
Don't like this at all in its current state.

**Pull request closed without merging**
