### PR TITLE
Fix cursor rotating with barrel roll mod active

### LINKED ISSUE #28693: Enabling the mod Barrel Roll will cause the cursor to rotate with the game field
### Type

Cosmetic

### Bug description

Usually this isn't a problem, since most skin cursors look the same whether they're rotated or not
But it can look weird on some irregular cursors
Skin: [CS Skin ver.6.9 DUB Edition Remix.zip](https://github.com/user-attachments/files/16056885/CS.Skin.ver.6.9.DUB.Edition.Remix.zip)
Please change zip to osk

### Screenshots or videos

image

### Version

2024.625.2

### Logs

N/A

### PR DESCRIPTION
**Pull request by jhk2601**
Closes #28693 

Some may argue that cursor rotation is intended behavior but it looks odd and feels pretty janky, especially on abnormal cursors like the issue describes. Would be better if cursor rotation could be adjusted in existing switch statement but didn't want to mess with existing implementation to allow that and this way is simple and readable as well.

### CODE REVIEW

**Comment by bdach** [comment]
Honestly not sure what to think about this one in general. It feels to me that this being an issue that needs to be fixed is disputable in the first place. The cursor is on the playfield, the playfield is rotating - so why *wouldn't* the cursor rotate too?

The only reason I can conjure up to support this change is that skins with non-symmetrical cursors are affected more visually by this. But I honestly see the skin linked in the issue as a "meme skin" (it's trying to fake the player playing CS, for crying out loud), so I'm not sure it's serious enough to warrant adding carve-outs of this sort.

@ppy/team-client one of low priority I'd like to gather opinions about

**Comment by peppy** [comment]
I think it makes sense to not rotate the cursor with the platyfield. To me the concept of barrel roll is that the *hitobjects* are rotating. As a player I wouldn't expect it to affect the cursor.

**Comment by Susko3** [comment]
> As a player I wouldn't expect it to affect the cursor.

Yeah, since the movement of the cursor is unaffected by barel roll, its rotation should also be unaffected.

For example, if using [Windosu XP](https://osu.ppy.sh/community/forums/topics/1790353) (skin of the year 2023 runner-up) I would expect the "pointer" cursor to always point up.

**Comment by jhk2601** [comment]
> > As a player I wouldn't expect it to affect the cursor.
> 
> Yeah, since the movement of the cursor is unaffected by barel roll, its rotation should also be unaffected.
> 
> For example, if using [Windosu XP](https://osu.ppy.sh/community/forums/topics/1790353) (skin of the year 2023 runner-up) I would expect the "pointer" cursor to always point up.

Yeah this is a great example, considering that almost all cursors are symmetrical anyway we are only really dealing with edge cases like this here, and in those edge cases it is more logical and expected for the cursor to stay aligned. (also worth noting that it will feel jarring because the cursor doesn't APPEAR to be rotating when using a "normal" cursor, so it will feel like a setting was changed or something)

**Review by bdach — APPROVED** [review]
I guess this does what it says

**Pull request merged**
