### PR TITLE
Improve transition visuals of player load sequence

### PR DESCRIPTION
**Pull request by peppy**
Before:

https://user-images.githubusercontent.com/191335/195545076-14ca38e8-39c5-42bf-b994-37ca42ea8711.mp4

After:

https://user-images.githubusercontent.com/191335/195544659-da43f0ea-438f-49c1-83a2-f369858b6908.mp4

- [x] Depends on #20739 for no real reason (looks better)

### CODE REVIEW

**Comment by frenzibyte** [comment]
The transitions overall look good, but the scale of the settings overlay caused by the toolbar hide during switching to `Player` screen makes the transition feel somewhat off to me, as it makes the overlay move towards the centre:

https://user-images.githubusercontent.com/22781491/195985055-6753918b-2772-4cdd-b2f7-425243231268.mp4

I'm not completely fussed about it, but I think it could be salvaged by making the overlay transition to/from the right, i.e.:

https://user-images.githubusercontent.com/22781491/195985293-293ed562-e046-4960-8ef8-014cb386d487.mp4

```diff
diff --git a/osu.Game/Screens/Play/PlayerLoader.cs b/osu.Game/Screens/Play/PlayerLoader.cs
index b553818a2d..cb55d264f9 100644
--- a/osu.Game/Screens/Play/PlayerLoader.cs
+++ b/osu.Game/Screens/Play/PlayerLoader.cs
@@ -404,10 +404,12 @@ private void contentIn()
         {
             MetadataInfo.Loading = true;
 
-            settingsScroll.FadeInFromZero(400);
-
             content.FadeInFromZero(400);
             content.ScaleTo(1, 650, Easing.OutQuint).Then().Schedule(prepareNewPlayer);
+
+            settingsScroll.FadeInFromZero(400)
+                          .MoveToX(0, 650, Easing.OutQuint);
+
             lowPassFilter.CutoffTo(1000, 650, Easing.OutQuint);
             highPassFilter.CutoffTo(300).Then().CutoffTo(0, 1250); // 1250 is to line up with the appearance of MetadataInfo (750 delay + 500 fade-in)
 
@@ -421,7 +423,10 @@ protected virtual void ContentOut()
 
             content.ScaleTo(0.7f, CONTENT_OUT_DURATION * 2, Easing.OutQuint);
             content.FadeOut(CONTENT_OUT_DURATION, Easing.OutQuint);
-            settingsScroll.FadeOut(CONTENT_OUT_DURATION, Easing.OutQuint);
+
+            settingsScroll.FadeOut(CONTENT_OUT_DURATION, Easing.OutQuint)
+                          .MoveToX(settingsScroll.DrawWidth, CONTENT_OUT_DURATION * 2, Easing.OutQuint);
+
             lowPassFilter.CutoffTo(AudioFilter.MAX_LOWPASS_CUTOFF, CONTENT_OUT_DURATION);
             highPassFilter.CutoffTo(0, CONTENT_OUT_DURATION);
         }
```

May probably need further tweaking to feel better.

**Comment by peppy** [comment]
Yeah, while working on this I did realise that was the reason I originally added the delay. The toolbar height changing is annoying.

What you propose feels good but doesn't 100% resolve the issue. Maybe okay for now?

**Comment by peppy** [comment]
@frenzibyte I've applied your change in addition to a few tweaks. There's still a heap of changes I want to make but let's get this base set in first.

**Comment by smoogipoo** [comment]
Test failures are relevant

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
