### PR TITLE
Use default storage when accessing cache data

### PR DESCRIPTION
**Pull request by ms2mml**
Referencing the cache issue mentioned at the end of #10484.

During folder migration, the `cache` folder is ignored in migration. However, subsequent access to the cache uses `UnderlyingStorage` instead of `defaultStorage`. So even though the `cache` files aren't copied over to the migrated location, they will be recreated there, which defeats the purpose of ignoring them during migration.

In addition, the following edge case will cause an exception to be thrown.
1. Use the migration feature
2. Try to import a beatmap without exiting the game first
3. The game will throw an exception because the cache folder was not migrated, and subsequent access to the cache is trying to access the cache under the migrated path instead of the default path:
image
4. Upon restarting the game, the cache folder will be recreated under the migrated path

Stack trace for the exception above:
```
at System.IO.Enumeration.FileSystemEnumerator`1.CreateDirectoryHandle(String path, Boolean ignoreNotFound)
at System.IO.Enumeration.FileSystemEnumerator`1.Init()
at System.IO.Enumeration.FileSystemEnumerator`1..ctor(String directory, Boolean isNormalized, EnumerationOptions options)
at System.IO.Enumeration.FileSystemEnumerable`1..ctor(String directory, FindTransform transform, EnumerationOptions options, Boolean isNormalized)
at System.IO.Enumeration.FileSystemEnumerableFactory.UserFiles(String directory, String expression, EnumerationOptions options)
at System.IO.Directory.InternalEnumeratePaths(String path, String searchPattern, SearchTarget searchTarget, EnumerationOptions options)
at System.IO.Directory.GetFiles(String path, String searchPattern)
at osu.Framework.Platform.NativeStorage.GetFiles(String path, String pattern) in D:\src\vs\osu-framework\osu.Framework\Platform\NativeStorage.cs:line 45
at osu.Game.IO.WrappedStorage.GetFiles(String path, String pattern) in D:\src\vs\osu\osu.Game\IO\WrappedStorage.cs:line 68
at osu.Game.IO.WrappedStorage.GetFiles(String path, String pattern) in D:\src\vs\osu\osu.Game\IO\WrappedStorage.cs:line 68
at osu.Framework.IO.Stores.RawCachingGlyphStore.createCachedPageInfo(Int32 page) in D:\src\vs\osu-framework\osu.Framework\IO\Stores\RawCachingGlyphStore.cs:line 56
at osu.Framework.IO.Stores.RawCachingGlyphStore.LoadCharacter(Character character) in D:\src\vs\osu-framework\osu.Framework\IO\Stores\RawCachingGlyphStore.cs:line 40
at osu.Framework.IO.Stores.GlyphStore.Get(String name) in D:\src\vs\osu-framework\osu.Framework\IO\Stores\GlyphStore.cs:line 128
at osu.Framework.IO.Stores.ResourceStore`1.Get(String name) in D:\src\vs\osu-framework\osu.Framework\IO\Stores\ResourceStore.cs:line 131
at osu.Framework.Graphics.Textures.TextureStore.getTexture(String name, WrapMode wrapModeS, WrapMode wrapModeT) in D:\src\vs\osu-framework\osu.Framework\Graphics\Textures\TextureStore.cs:line 54
at osu.Framework.Graphics.Textures.TextureStore.Get(String name, WrapMode wrapModeS, WrapMode wrapModeT) in D:\src\vs\osu-framework\osu.Framework\Graphics\Textures\TextureStore.cs:line 132
at osu.Framework.IO.Stores.FontStore.Get(String name) in D:\src\vs\osu-framework\osu.Framework\IO\Stores\FontStore.cs:line 117
at osu.Framework.IO.Stores.FontStore.Get(String fontName, Char character) in D:\src\vs\osu-framework\osu.Framework\IO\Stores\FontStore.cs:line 144
at osu.Framework.Graphics.Sprites.SpriteText.load(ShaderManager shaders) in D:\src\vs\osu-framework\osu.Framework\Graphics\Sprites\SpriteText.cs:line 77
```

### CODE REVIEW

**Comment by peppy** [comment]
Thanks for the contribution!

My first thoughts here are that maybe we want to expose a `CreateCacheStorage` at a framework level (which defaults to just calling `CreateStorage` and completely separate that flow out. It miight be a better option as we have more components that might use cache, so they don't need to know about the magic "cache" directory and can instead use `game.CacheStorage` directly.

**Comment by ms2mml** [comment]
> Thanks for the contribution!
> 
> My first thoughts here are that maybe we want to expose a `CreateCacheStorage` at a framework level (which defaults to just calling `CreateStorage` and completely separate that flow out. It miight be a better option as we have more components that might use cache, so they don't need to know about the magic "cache" directory and can instead use `game.CacheStorage` directly.

Sure, I think having a framework level cache storage is a better idea as well. I will work on making the update.

**Comment by peppy** [comment]
@ms2mml just checking in on whether you're still going to look at this. if not i may make the framework-side amendment for you just to move things along.

**Comment by bdach** [comment]
I guess there's not much merit to these changes at this point, given that the framework change was merged?

**Comment by peppy** [comment]
In *theory* this should not be required any more. Would be good to test and make sure the failure cannot be repro'd.

**Comment by bdach** [comment]
I tested and as expected the `cache` directory is no longer part of any custom storage directory after migration, which means that the issue should be fixed.

Closing this PR as superseded by the framework change at ppy/osu-framework#3977.

**Pull request closed without merging**
