### PR TITLE
Decouple FilterControl.Ruleset from the game-wide ruleset bindable

### LINKED ISSUE #2451: Can not set value to "osu.Game.Rulesets.RulesetInfo"
- Play a song and **stay on scorescreen**.
- Open osu!direct and click on the Catch The Beat icon:  
image of osudirect
It will make osu!lazer unresponsive with this exception caught:
image of visual studio

### PR DESCRIPTION
**Pull request by UselessToucan**
resolves #2451 
https://youtu.be/TNqRcul3fdU

### CODE REVIEW

**Comment by smoogipoo** [comment]
I don't think direct and osu! should share the game-wide ruleset bindable in the first place. Agree, @peppy ?

**Comment by peppy** [comment]
I think that's the direction we were going in, yeah.

Also I thought this functionality already existed at an `OsuScreen` level or similar? I know that these buttons were already disabled when in play mode.

**Comment by smoogipoo** [comment]
The toolbar buttons are, but the osu!direct buttons weren't disabled, and they share the game-wide bindable hence triggering the exception. But I can't imagine why you'd want to disable the direct ones.

**Review by smoogipoo — CHANGES_REQUESTED** [review]
as commented

**Comment by UselessToucan** [comment]
https://youtu.be/5nEHYbTYhg4

**Review by smoogipoo — APPROVED** [review]
lgtm!

**Pull request merged**
