### PR TITLE
Lazy ruleset loading

### PR DESCRIPTION
**Pull request by miterosan**
Loads the rulessets lasily. This allows other code to run before the rulesets are determined.

### CODE REVIEW

**Comment by bdach** [comment]
Could you clarify what are the perceived, concrete benefits of this change?

(By the way, the xmldocs need spellchecking in places.)

**Comment by miterosan** [comment]
@bdach This changes allow the fix located in #6508

**Comment by miterosan** [comment]
Closing as this PR is not worth it for just one line change. Changes are included in #6510

**Comment by bdach** [comment]
Make sure to merge back the typo and CI-appeasing fixes back to the other one, though.

**Pull request closed without merging**
