### PR TITLE
Implement mania invert mod

### PR DESCRIPTION
**Pull request by smoogipoo**
Just fulfilling my quota to the mania community. This is one of the most requested mod ideas (https://osu.ppy.sh/community/forums/topics/148237).

Just one of about 3 mod ideas I have in mind.

### CODE REVIEW

**Comment by bdach** [comment]
How about `FontAwesome.Solid.YinYang` for the icon?

obraz

**Review by bdach — APPROVED** [review]
Looks really cool with the increased density - really similar to the one inverse map I had locally downloaded because of some issue :+1:

**Comment by peppy** [comment]
@smoogipoo can you confirm that this is ready for review? I think you mentioned something about changing it further.

**Comment by smoogipoo** [comment]
Already done in the last commit. This is ready for review.

**Comment by peppy** [comment]
As someone who has serious issues with timing and reading hold note releases and presses, this mod is my worst nightmare.

**Review by peppy — APPROVED** [review]

**Pull request merged**
