### PR TITLE
Reduce allocation overhead of song progress bars

### PR DESCRIPTION
**Pull request by EVAST9919**
d2af05b30e93f729ba40326bdaf51867817f65f2 require a bit of attention since even it seems like removed bindable doesn't do anything I could be missing something.

### CODE REVIEW

**Comment by peppy** [comment]
Can't really work with this. `CurrentTime` is getting set to two different values for different implementations. `TrackTime` is being provided via a weird flow which raises the question of how it even differs from `CurrentTime`.

Please understand the classes and variables first before refactoring or you're just going to create more work.

I think there probably needs to be a `TrackTime` and `CurrentTime` where they are clearly labelled as one being the frame stable playback time and one the audio time.

**Review by peppy — CHANGES_REQUESTED** [review]
As per comment

**Comment by peppy** [comment]
@EVAST9919 can you show the follow-up PR / diff so I can know what to expect and why this refactoring is required in the first place?

**Comment by EVAST9919** [comment]
> @EVAST9919 can you show the follow-up PR / diff so I can know what to expect and why this refactoring is required in the first place?

I guess [something like this](https://github.com/EVAST9919/osu/compare/progress-bar-improvements...EVAST9919:osu:progress-rework) where we don't use `SliderBar` as a base and with that avoid bindables altogether.

**Comment by peppy** [comment]
So just wondering, could we not have just added two lines to change the precision of the bindables on either class and not do any of this refactoring?

**Comment by EVAST9919** [comment]
> So just wondering, could we not have just added two lines to change the precision of the bindables on either class and not do any of this refactoring?

This works too

**Comment by peppy** [comment]
> > @EVAST9919 can you show the follow-up PR / diff so I can know what to expect and why this refactoring is required in the first place?
> 
> I guess [something like this](https://github.com/EVAST9919/osu/compare/progress-bar-improvements...EVAST9919:osu:progress-rework) where we don't use `SliderBar` as a base and with that avoid bindables altogether. Now that I think of it - these changes might as well be included in this pr probably?

can you push these changes to this branch? i'll decide whether to go down this path or something simpler.

**Review by peppy — APPROVED** [review]
Cleanup effort = nothing something i wanted to do with my time but ahwaaaaaaaaaaaaaaaaatever

**Pull request merged**
