### PR TITLE
Use generic Enum methods

### PR DESCRIPTION
**Pull request by turbedi**
Less code and potentially faster (reduces boxing)

### CODE REVIEW

**Comment by mk56-spn** [comment]
Code quality needs a look. Seems like you forgot to remove some "usings"

**Comment by bdach** [comment]
Needs testing on mobile. Last time we tried this mono would not comply.

**Comment by Susko3** [comment]
> Needs testing on mobile. Last time we tried this mono would not comply.

Works fine here with `osu.Android` debug and release.

**Review by bdach — APPROVED** [review]
Looks good, but I'm going to need confirmation that this doesn't break iOS either in order to feel safe with proceeding with this.

**Review by frenzibyte — APPROVED** [review]
All well on iOS.

**Pull request merged**
