### PR TITLE
Add keyboard selection to multiplayer lounge

### LINKED ISSUE #9473: Browse using arrow key in multiplayer lounge
**Describe the new feature:** 
Just like in song selection, you can use arrow key up and down to browse every room in multiplayer lounge and press enter to enter the room.

### PR DESCRIPTION
**Pull request by peppy**
- Closes #9473
- [x] Depends on #9476
- [x] Depends on #9477 
- [x] Investigate fast up/down selection causing a crash

### CODE REVIEW

**Comment by smoogipoo** [comment]
That was super dodgy - last commit I pushed fixes both the crash and duplicate playlist items (it seems).

**Comment by smoogipoo** [comment]
Doesn't fix the duplicate items, definitely happens after a web req though. Continuing to look into it.

**Comment by peppy** [comment]
Planning to make a framework change in line with that last "fix"? Seems flaky as it is.

**Comment by smoogipoo** [comment]
What framework change are you proposing to make?

**Comment by peppy** [comment]
I have no idea because I'm not sure what the fix is actually doing. But if `private set` is not valid in the `DependencyContainer` context due to breaking on use, it should likely be disallowed.

**Comment by smoogipoo** [comment]
Fair point.

**Review by smoogipoo — APPROVED** [review]
Looks fine to me. Last issue is a framework one (see mentioning PR).

**Pull request merged**
