### PR TITLE
Hide the game-wide cursor on touch input

### LINKED ISSUE #7437: Hide menu cursor on touch devices
**Describe the new feature:** Cursor showing up is not expected and looks bad on touch devices, and should be hidden. Cursor in std mode should not be hidden.

**Proposal designs of the feature:** When touch input is used, an invisible drawable would be drawn in place of the cursor.

### LINKED ISSUE #10046: Loading Layer blocks touch input
**Describe the bug:**
The loading animation seems to block input from touch devices when you try to press on it to move the cursor.
It seems to block input from overlays in front of it, too.

**Screenshots or videos showing encountered issue:** 
> **Loading Cover in PlayerLoader:**
loading cover

> **Trying to touch the (loading) Multiplayer lounge list:**
lounge

> **Trying to scroll the settings in the loading region of the Multi lounge:**
multiplayer lounge loading + settings

**osu!lazer version:** 2020.825.0

### PR DESCRIPTION
**Pull request by peppy**
I looked at fixing this locally on the `LoadingLayer` and while it is possible, this makes more sense.

Closes https://github.com/ppy/osu/issues/10046.
Closes https://github.com/ppy/osu/issues/7437.

Tested on iOS simulator only, but should be ample based on simplicity of implementation.

### CODE REVIEW

**Comment by frenzibyte** [comment]
I think this should be enough to close https://github.com/ppy/osu/issues/7437 as any touchscreen device should now have their cursor hidden on first touch input.

**Comment by peppy** [comment]
It will be hidden before the first touch input, too. It will only be unhidden on a non-touch input.

**Review by smoogipoo — APPROVED** [review]

**Review by frenzibyte — APPROVED** [review]

**Comment by ThatsNiceGuy** [comment]
this feels like pestering honestly but can we still have it be a toggle later?

**Comment by peppy** [comment]
No, there's no reason to have it displayed.

**Comment by HUOYI159** [comment]
I would love it to add a switch, because since the cursor disappeared, it's getting uncomfortable, because I'm stuck with the last version (Android) where the cursor appeared, and it makes OSU! It becomes more vivid

**Comment by HUOYI159** [comment]
I would love it to add a switch, because since the cursor disappeared, it's getting uncomfortable, because I'm stuck with the last version (Android) where the cursor appeared, and it makes OSU! It becomes more vivid

**Pull request merged**
