### PR TITLE
Fix `SkinImporter` adding to `skin.ini` when metadata already exists

### LINKED ISSUE #22681: Skin import adds redundant information to skin.ini
### Type

Game behaviour

### Bug description

During skin import, `SkinImporter` writes Name and Author fields to `skin.ini` regardless of them already existing, leading to strange cases like the linked image. In these cases, instead of grabbing the actual skin name that is specified at the top of the file, exports, deletions and sequential re-imports lead to the name being nested within itself and written to the end of `skin.ini` again leading to mangled names.

This should be a very short fix where a check for existing metadata occurs before calling `updateSkinIniMetadata`, and I can PR it myself if that is necessary.
https://github.com/ppy/osu/blob/6b1c8195bcba6eb3af2e1836d0799ff9e061f8c2/osu.Game/Skinning/SkinImporter.cs#L111-L112

### Screenshots or videos

image

### Version

2023.207.0

### Logs

[updater.log](https://github.com/ppy/osu/files/10774326/updater.log)
[database.log](https://github.com/ppy/osu/files/10774327/database.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10774328/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10774329/network.log)
[performance.log](https://github.com/ppy/osu/files/10774330/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/10774331/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/10774332/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/10774333/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/10774334/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/10774335/runtime.log)

### PR DESCRIPTION
**Pull request by rozukke**
Fixes #22681 

Prevents skins that have already been processed from being reprocessed again after being deleted. Fixes imports of lazer-exported skins, allowing for skin editing flow of export->delete->make changes->re-import.

### CODE REVIEW

**Comment by bdach** [comment]
This change weakens intentional protections against unique skins with the same `skin.ini` contents and fails several unit tests:



Please read https://github.com/ppy/osu/pull/14465 for context why this is being done and paper trail.

**Review by bdach — CHANGES_REQUESTED** [review]
as above

**Comment by bdach** [comment]
Based on [this comment](https://github.com/ppy/osu/issues/22681#issuecomment-1435704795) I'm just going to close this pull for now. @rozukke if you end up figuring something out we can reopen.

**Comment by rozukke** [comment]
I feel quite silly after taking a look over the relevant code again and found the actual one-liner solution that passes the skin import tests. I'm not 100% on whether commits are added automatically to closed PRs but the updated fix is on the same branch.

**Comment by bdach** [comment]
If you reopen the PR the commits will show.

**Pull request closed without merging**
