### PR TITLE
Allow dragging multiple slider path control points at once

### PR DESCRIPTION
**Pull request by bdach**
Select multiple control points of a slider path using <kbd>Ctrl</kbd>, then keep <kbd>Ctrl</kbd> held and drag any of the selected points to drag them all simultaneously (rather than one-at-a-time, which was the only option until this change).

https://user-images.githubusercontent.com/20418176/146836764-0b2f1645-a0cd-470c-b4f8-553e4b9700a3.mp4

I saw this suggested somewhere over the weekend, don't remember where (may have been a twitch chat message or something?) and figured that you might as well allow this. It's allowed for multiple objects anyway.

The move algorithm is largely the same, just moved to a higher level and adapted for multi-selection. I've had to make one more UX change, namely that deselection of path control points happens on mouse up rather than down as it used to. This is because a mouse down is ambiguous with this feature added - as in you don't know in advance if a mouse down is going to initiate a drag, or if it's just going to be a normal click. But as far as I can tell this behaviour is consistent with normal object selection anyhow:

https://github.com/ppy/osu/blob/698b6c4242dbc89d8b28d9b55be747505bd51796/osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs#L356-L374

### CODE REVIEW

**Comment by peppy** [comment]
Doesn't seem to use the correct origin point if you drag from the second of a two point selection:

https://user-images.githubusercontent.com/191335/146884672-d18482f5-7a1b-401a-ac41-c99207702cba.mp4

**Comment by bdach** [comment]
Hmm, looks like a missed edge case; the key will be that the head node is a part of the selection. I'll look into it...

**Comment by bdach** [comment]
Should be better now with the latest commits; I've also added a test case covering this.

**Comment by peppy** [comment]
I've only found one slight remaining breakage so far:
- Ctrl-select two control points
- Ctrl-right click one and attempt to change curve type of both
- Hovered point is incorrectly deselected, causing only the other control points' curve type to be updated.

**Comment by peppy** [comment]
One more (not sure if a regression from this PR, but definitely weird/wrong):

- Make selection of control points
- Control-leftclick on slider body to create a new point, but drag the point before releasing mouse
- Selected points are not deselected

This works correctly if you don't do the drag after point placement (first vs second placement in video)

https://user-images.githubusercontent.com/191335/147039656-ce646a52-b854-47f3-84b0-6eae1d4b88c7.mp4

**Comment by peppy** [comment]
Got a crash while testing further, but it looks likely unrelated. If you confirm I'll take a look into it separately:

```csharp


[runtime] 2021-12-22 05:20:48 [verbose]: Unhandled exception has been denied .
Unhandled exception. System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at osu.Framework.Bindables.BindableList`1.get_Item(Int32 index)
   at osu.Game.Rulesets.Osu.Edit.Blueprints.Sliders.SliderSelectionBlueprint.OnDrag(DragEvent e) in /Users/dean/Projects/osu/osu.Game.Rulesets.Osu/Edit/Blueprints/Sliders/SliderSelectionBlueprint.cs:line 170
   at osu.Framework.Graphics.Drawable.TriggerEvent(UIEvent e)
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.MouseButtonEventManager.handleDrag(InputState state, Vector2 lastPosition)
   at osu.Framework.Input.MouseButtonEventManager.HandlePositionChange(InputState state, Vector2 lastPosition)
   at osu.Framework.Input.InputManager.HandleMousePositionChange(MousePositionChangeEvent e)

```

**Comment by bdach** [comment]
Fixed cases from the two videos above. Couldn't reproduce the crash but I ended up touching the code that directly caused it, and it looks like that change should take care of it, too.

Hopefully this latest batch of changes holds up better. I didn't find anything wonky in a 10 minute torture session but as it looks maybe I'm just not very good at finding wonky behaviour...

**Comment by peppy** [comment]
I... don't yet know how I managed this, but the deselection didn't happen when placing a new point. Skip to the end of the video for the actual issue (ctrl-click to place a point leaves previous points selected) - only included the rest of the video for context that may allow reproducing.

https://user-images.githubusercontent.com/191335/147191691-b880c54e-441d-4a59-9246-9ebc03795b85.mp4

**Comment by bdach** [comment]
Looking at the frame-by-frame, somehow you've managed to find a way to completely displace the second control point while being at a considerable distance from it.

| before click | after click |
| :-: | :-: |
| image | image |

I'll have a closer look at the placement logic...

**Comment by peppy** [comment]
Super weird. I'd still expect deselection in that case though ;)

**Comment by bdach** [comment]
Turns out that was a bug in `master` but I've fixed that too, with test coverage.

**Review by peppy — APPROVED** [review]
Tried to break more and seems pretty good now. Good looks like an improvement in readability.

**Pull request merged**
