### PR TITLE
Attempt to set heath drain and gain to same as in stable

### PR DESCRIPTION
**Pull request by RaskiTech**
The biggest modification is that misses are now far more brutal than before - the same as in stable. I'm pretty sure I also solved the issue @kiwec was pointing out here: https://github.com/ppy/osu/issues/7975, where you couldn't really get HP back if you lost it.

Mainly this change is just fiddling with some constants, but it does the job :)

Edit:
I made a short video that shows the change well:
https://youtu.be/ZGYNaTuqiZM

### CODE REVIEW

**Review by peppy — CHANGES_REQUESTED** [review]

**Review by smoogipoo — CHANGES_REQUESTED** [review]
I'm confused by your recent changes. A 0.5 scaling factor to drain rate (prior to the changes) means that the lowest HP in the map is 50% of the health target. So in reverse I'd expect the health targets to be 50% higher, leading to the values: `0.975, 0.85, 0.75`.

**Comment by peppy** [comment]
@smoogipoo what's the path forward with this one? did you test how it feels in gameplay? should we try pushing it out in a release and get some more widespread feedback if it feels like the correct direction?

**Comment by smoogipoo** [comment]
Read the comments above, it needs more investigation and I haven't prioritised this.

**Comment by peppy** [comment]
The weird value you mentioned has since been changed. But I guess it will require re-checking everything with the new values, fair.

**Comment by smoogipoo** [comment]
No, it needs investigation into why 0.9699 can't be rounded up to 0.97, because apparently it creates a huge difference.

**Comment by peppy** [comment]
Right. Threading is weird in this one..

**Pull request closed without merging**
