### PR TITLE
Refactor `SeedSettingsControl` and `SettingsNumberBox`

### LINKED ISSUE #13389: Custom seed input field for random mod is completely invisible when not highlighted
**Describe the bug:** 
When not clicked, the input field is completely invisible and might be confusing to players as only the word "seed" is seen under the customisation window

**Screenshots or videos showing encountered issue:** 
osu_2021-06-08_20-27-50
osu_2021-06-08_20-31-52

**osu!lazer version:** 2021.608.0

### PR DESCRIPTION
**Pull request by hlysine**
Fixes #13389 

This fixes a regression in #13626

### CODE REVIEW

**Review by Joehuu — DISMISSED** [review]

**Comment by peppy** [comment]
This is an intertwined mess. I'm not sure how we got to this point, but `SettingsNumberBox` should contain 99% of the implementation here, to the point this class doesn't have to use one internal portion of that class.

**Comment by Henry-YSLin** [comment]
I've moved the internal portion of `SettingsNumberBox` to a new file and cleaned up `SeedSettingsControl`. The `string` to `int?` conversion is still handled by `SeedSettingsControl` since other uses of `SettingsNumberBox` expect a `string`.

**Comment by peppy** [comment]
The question I have then is "what is the use case for `string`"? Sounds like all usages would benefit from `int?`being the resultant type..

**Comment by Henry-YSLin** [comment]
True, but then shouldn't `OsuNumberBox.Current` gives `Bindable<int?>` from the start?

**Review by peppy — APPROVED** [review]
👍🏻  made a few minor changes but good otherwise

**Pull request merged**
