### PR TITLE
Simplify task logic in `ModPresetColumn`

### PR DESCRIPTION
**Pull request by peppy**
Not sure what this was doing previously.

### CODE REVIEW

**Comment by bdach** [comment]
I don't think I can agree with this. `latestLoadTask` was supposed to be a data race protection.

Picture this: async load A starts, then async load B starts. If async load B ends before async load A does for whatever reason, then the final state will be wrong, since the panels from load A will end up being used.

Notably this is no different from the logic that `ModColumn` uses, and was also grandfathered from the old mod overlay if I remember correctly.

**Comment by peppy** [comment]
The cancellation token should already guard against this. We use the same flow in other places and it's proven to be quite solid. Importantly, the actual final load is done in a scheduled fashion at the cancellation is checked at that point in time, so as long as it is refreshed each `LoadComponentsAsync` it should work correctly.

https://github.com/ppy/osu/blob/f8830c6850128456266c82de83273204f8b74ac0/osu.Game/Screens/Backgrounds/BackgroundScreenBeatmap.cs#L90-L91

https://github.com/ppy/osu/blob/f8830c6850128456266c82de83273204f8b74ac0/osu.Game/Overlays/BeatmapListingOverlay.cs#L153-L175

(more examples if you search for `LoadComponentAsync.*cancel`)

**Comment by bdach** [comment]
Alright, well, on further re-examination it appears that the old mod overlay did not do this, although I don't recall inventing this protection either myself. Very weird that this just blackholed in my brain but I guess we can see how removing this shakes out? I'm not 100% sure if this is safe either way but the end result is simpler for sure.

That said I have some couple minor issues with this so I'll be pushing some fixup commits shortly. I'll let you know once I'm done.

**Comment by bdach** [comment]
Fixups pushed:

* Changed one `?? false` nullable-boolean test to use `== true` instead (as I recall, there was universal agreement on the latter being more readable)
* Ported fix to `ModColumn` which used the exact same logic.

Please double-check that you're OK with the result.

**Review by bdach — APPROVED** [review]

**Pull request merged**
