### PR TITLE
Pause clean up

### PR DESCRIPTION
**Pull request by ocboogie**
I made a feature branch like you said
[Old pull request](https://github.com/ppy/osu/pull/624)

### CODE REVIEW

**Comment by peppy** [comment]
Please test my proposed fix for fail/pause contention.

**Comment by ocboogie** [comment]
Still got it to occur

I'll look into it some more

**Comment by peppy** [comment]
How are you reproducing so easing?

**Comment by ocboogie** [comment]
I'm playing [Kano - Yuudachi no Ribbon](https://osu.ppy.sh/s/556174) on extreme and I have a visual cue.
I don't click or do anything and I press escape here:

visual cue

**Comment by ocboogie** [comment]
I don't have permission to talk in Discord but yes i'm reading it

**Pull request merged**
