### PR TITLE
Fix results screen crashing for beatmaps with no online ID

### PR DESCRIPTION
**Pull request by swoolcock**
Likely regressed in #9086 

Logic taken from `ScoresRequest.getScores()`

### CODE REVIEW

**Comment by peppy** [comment]
What's the crash this is fixing specifically? Not sure this is the correct fix. Should probably be in `SoloResultsScreen` at very least.

Test coverage would be appreciated if possible.

**Comment by swoolcock** [comment]
`GetScoresRequest` constructor:
`throw new InvalidOperationException($"Cannot lookup a beatmap's scores without having a populated {nameof(BeatmapInfo.OnlineBeatmapID)}.");`

Found while testing my ruleset on an unsubmitted map.

**Comment by smoogipoo** [comment]
This should be fixed in `SoloResultsScreen` as mentioned.

**Comment by swoolcock** [comment]
> This should be fixed in `SoloResultsScreen` as mentioned.

No problem, will do.  I was going to put it there originally but I figured there would be code duplication if future screens needed to implement `FetchScores` and do the same check.

**Comment by peppy** [comment]
Consider a case such as local score display, where no online fetching or online id requirement is present.

**Review by smoogipoo — APPROVED** [review]
This is fine for now imo. We'll probably want to display the local leaderboard but that can be saved for a future PR, and fix this crash here for now.

**Comment by peppy** [comment]
Should be fine to merge, CI failures will be fixed separately.

**Pull request merged**
