### PR TITLE
Move input events to interfaces

### PR DESCRIPTION
**Pull request by UselessToucan**
Refactor Drawable input and interactions as proposed [here](https://github.com/ppy/osu-framework/issues/952)

- [ ] Depends on https://github.com/ppy/osu-framework/pull/1135.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Although I'm not sure if there's much of a point to not grouping e.g. OnHover and OnHoverLost, OnMouseDown and OnMouseUp, within the same interfaces, this looks okay to me. I'm going to wait for @Tom94 and @peppy to review this to make sure we're all on the same page.

**Review by smoogipoo — DISMISSED** [review]

**Comment by UselessToucan** [comment]
> I'm not sure if there's much of a point to not grouping e.g. OnHover and OnHoverLost, OnMouseDown and OnMouseUp, within the same interfaces

Sometimes they are used separately. For example, [ModButton](ModButton) handles `OnMouseDown` event, but does not handle `OnMouseUp`. In this particular example, grouping methods will force me to provide `OnMouseUp` implementation which we do not have.

**Comment by smoogipoo** [comment]
Well the implementation is just going to be `OnMouseUp() => false;`. Just saying I'm not sure it's worth segmenting it this far.

**Comment by peppy** [comment]
Blocked on framework changes (grouping the interfaces more broadly).

**Comment by smoogipoo** [comment]
See framework-side PR comments + issue thread.

**Pull request closed without merging**
