### PR TITLE
Make DateTooltip use OverlayColourProvider colours

### PR DESCRIPTION
**Pull request by EVAST9919**
Note: sometimes colours within different overlays not being updated due to https://github.com/ppy/osu-framework/issues/3231

### CODE REVIEW

**Comment by bdach** [comment]
I don't think it makes sense to merge this until the linked issue is resolved.

**Comment by EVAST9919** [comment]
Sure

**Comment by peppy** [comment]
Is there a reason the colourProvider is passed down rather than DI resolved from within the `DrawableDate`?

**Comment by EVAST9919** [comment]
> Is there a reason the colourProvider is passed down rather than DI resolved from within the `DrawableDate`?

[Smoogipoo's comment](https://github.com/ppy/osu-framework/issues/3230#issuecomment-581236135)

**Comment by peppy** [comment]
Right, which will probably be resolved when the underlying issue is resolved (which is blocking this).

**Comment by EVAST9919** [comment]
Gonna close this for now then, since there are 2 unresolved issues required for proper implementation.

**Pull request closed without merging**
