### PR TITLE
Decrease the time it takes to quick retry by ~650 ms

### PR DESCRIPTION
**Pull request by peppy**
Should help with https://github.com/ppy/osu/issues/9039.

### CODE REVIEW

**Comment by Givikap120** [comment]
Does this means that retry via "retry" button won't be affected?
Because I'm usually retrying using escape + retry

**Comment by Natelytle** [comment]
I'd second applying this change to the normal retry too, both forms of retrying are slower than stable I feel

**Comment by peppy** [comment]
Applying to normal retry means there's no delay to adjust settings, which is the reason this existed. If we want faster retry there I'll adjust it to 100 or 200 ms at very least.

**Comment by Givikap120** [comment]
> Applying to normal retry means there's no delay to adjust settings, which is the reason this existed. If we want faster retry there I'll adjust it to 100 or 200 ms at very least.

I would rather change the settings and then retry again than wait additional 650ms on each retry
Esp. considering that 99% of the time you don't adjust any settings

**Comment by peppy** [comment]
You're not making sense.

**Comment by Givikap120** [comment]
> You're not making sense.

Okay, I will rephrase
Does 0ms delay means that you can't adjust settings at all?
Or you still can adjust them during loading stage?

**Comment by peppy** [comment]
Please leave review for team members. You can test this once it goes live, thanks.

**Comment by ominoussage** [comment]
I have a suggestion: only instant retry with no beatmap loading screen if the player retried the map without changing any settings on the beatmap loading screen for at least 2 times. It's to ensure they can still change some settings before they startretry spamming (which is the main reason why players need an instant retry) and so that we won't need to find a perfect ms count for how quick a retry should be. 

It would reset if the player retries from the pause screen or exit the map entirely.

**Comment by rodrigopina360** [comment]
Quick related question (and sorry in advance if it's not the correct place to throw my thoughts), but wouldn't it be a more solid idea to have the settings overlay also visible when paused? 

Asking mainly from the experience of playing a map, retrying it to improve, and only remembering to apply the suggested offset after the settings are already gone. It also makes sense especially from the view of stable players, where map specific settings are already visible on the pause screen's "footer". If not a totally bad idea I could create an issue to attempt to elaborate further.

Either way having an improvement where players would care about it the most (retrying a map) is a lot better than no improvement at all, and personally I'd say it's more important to have this change validated, and leave discussion for later improvements, than to stall this change over said discussions.

**Comment by ominoussage** [comment]
> wouldn't it be a more solid idea to have the settings overlay also visible when paused? 
You can just press Ctrl + O while paused to access settings.

**Comment by bdach** [comment]
> Quick related question (and sorry in advance if it's not the correct place to throw my thoughts), but wouldn't it be a more solid idea to have the settings overlay also visible when paused?

this is tracked as https://github.com/ppy/osu/issues/3853 and out of scope of this PR

**Comment by bdach** [comment]
I'm not sure whether this will fully satisfy the crowd that are asking for faster retry but it's a start, I suppose. Any further gains are probably going to be a little difficult to achieve. (Although I will say that I slightly resent the "retry spam" thing as something that in the past has had a markedly negative impact on my personal enjoyment of the game when I was more actively playing, so I'm not particularly sympathetic to such arguments either.)

I think it's fine to confine this to quick retry. It's supposed to be *quick* retry after all. I can see the merit of not applying this to "normal" retry when *by definition* it takes more time to normal retry than quick retry, just by the virtue of number of keys you have to press *even if* you hyperoptimise it and don't use the mouse or something.

> I have a suggestion: only instant retry with no beatmap loading screen if the player retried the map without changing any settings on the beatmap loading screen for at least 2 times.

I hate this sort of thing because it's an automagic solution that takes control out of the user's hands and attempts to babysit them and do things for them. This being consciously controllable by choosing normal vs quick retry is more in line with how I'd want to see things done.

**Review by bdach — APPROVED** [review]

**Comment by peppy** [comment]
I ought adjust for the retry button slightly, as discussed above (start the load immediately but add 100ms delay). What do you think?

**Comment by bdach** [comment]
I don't have strong feelings on the UX side, but on the code side, if I'm thinking of the type of change that you might be thinking about, then I'd exercise caution to ensure it doesn't also kick in when *entering* a map from song select.

**Comment by peppy** [comment]
Let's merge this as-is. I'll post a follow-up PR if I do. It's a bit more complicated to implement nicely.

**Comment by broilerosu** [comment]
wouldnt it be smarter to remove the need for a delay and impliment a system where you can adjust the map settings by right clicking it or something or a keybind before playing the map or if you want to change it after loading the map you can have it on the pause menu people usally wont change offset until they hear the map so having it on pause menu would do wonders

**Comment by peppy** [comment]
I"m having trouble understanding how what you're saying is related to the change in this PR.

**Comment by broilerosu** [comment]
> I"m having trouble understanding how what you're saying is related to the change in this PR.

Yeah it might have been a bit off topic somewhat i was just reading some of the previous comments and how people thought the 650 ms wasnt enough and they wanted a more instant retry or close to stable retrying

**Comment by smoogipoo** [comment]
I have an old branch demonstrating that instant retry can be done: https://github.com/smoogipoo/osu/tree/instant-retry

It needs more work + consideration though, especially with things like the score token. If someone wants to take it on before any of us get to it, there's a starting point for you.

**Pull request merged**
