### PR TITLE
Fix storyboard videos being offset incorrectly

### PR DESCRIPTION
**Pull request by peppy**
Setting the PlaybackPosition will ignore the underlying clock with recent changes. `startAtCurrentTime = false` alone (plus a `+= offset` in `DrawableStoryboardVideo.LoadComplete`) isn't enough as we would need to delay the `PlaybackPosition` call to after the video runs its `LoadComplete`. Instead, let's just set the complete correct offset.

- [x] Depends on https://github.com/ppy/osu-framework/pull/3432

### CODE REVIEW

**Review by bdach — APPROVED** [review]
Tested as working and this way actually seems most correct and least prone to error in the future. 👍

**Review by smoogipoo — APPROVED** [review]

**Comment by smoogipoo** [comment]
I do agree that the nullability is ugly. I play to eventually split the lookups into stage and column enums, but I've merged them together for simplicity for now.

**Comment by smoogipoo** [comment]
Gonna merge this as there'll probably be another framework hotfix today anyway.

**Comment by peppy** [comment]
Yeah, this isn't actually dependent on the framework-side change with my final approach.

**Pull request merged**
