### PR TITLE
Fix floating mouse position not running correctly in single thread mode

### PR DESCRIPTION
**Pull request by peppy**
Noticed while testing on iOS. Previously, the interpolation was being done in input handling but using the update thread clock, leading to incorrect application.

### CODE REVIEW

**Comment by frenzibyte** [comment]
I can't follow how this would change anything, since the input handling is running on the update thread (propagated from `UserInputManager.Update()`), and the update thread clock should be processed properly before `UserInputManager.Update()`, making no difference between performing the interpolation in `OnMouseMove` or `Update()` (in addition, `OnMouseMove` is called per-frame due to the use of `IRequireHighFrequencyMousePosition`).

**Comment by peppy** [comment]
> I can't follow how this would change anything

It would previously run more than once per frame, meaning the values I had set were not system agnostic (depended on mouse polling rate).

**Comment by frenzibyte** [comment]
Ah I see, part of the confusion came from the fact that this is specific to single threaded, while I would imagine it being a problem regardless of execution mode.

**Comment by peppy** [comment]
Single thread mode reduces the input thread from 1000hz to 60 or 120, which makes this issue occur.

**Review by smoogipoo — APPROVED** [review]
Looks ok

**Pull request merged**
