### PR TITLE
Update resources

### PR DESCRIPTION
**Pull request by peppy**
Prereqs:
- [x] https://github.com/ppy/osu-resources/pull/67

### CODE REVIEW

**Review by smoogipoo — DISMISSED** [review]

**Review by smoogipoo — APPROVED** [review]

**Comment by smoogipoo** [comment]
Might as well bundle framework update along with this, just so that flashlight crashes don't happen as a result of this on desktop during debug.

**Comment by peppy** [comment]
Sure, just leave it open until framework is ready.

**Comment by iiSaLMaN** [comment]
I think this can be closed now? PR #5663 bumps the resources to 2019.809.0, and framework is currently updated to 2019.807.0

**Comment by peppy** [comment]
@smoogipoo here's your answer to why resources was out-of-date ;)

**Pull request closed without merging**
