### PR TITLE
Fix beatmap load not continuing when when settings slider is focused

### LINKED ISSUE #30716: Clicking Visual/Audio settings sliders on beatmap loading will keep them selected permanently
### Type

Game behaviour

### Bug description

Tapping any slider (this also applies to drag begin) on settings while the beatmap is loading will keep that slider selected, prompting the map to not load until it is unselected. While it is not game breaking, it is quite annoying sometimes.

Previously, moving the sliders would not keep them in a "selected" state.

### Screenshots or videos

image

### Version

2024.1115.3

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17790174/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by peppy**
Regressed with recent sliderbar focus changes.

Closes #30716.

### CODE REVIEW

**Comment by bdach** [comment]
Bit of an issue with this is that with this diff, keyboard adjustments of a focused slider don't delay the load sequence like a normal drag does:

https://github.com/user-attachments/assets/3a1f66d0-87a5-40c6-82fd-c9bb7f3a6f5a

which feels a bit anti-user. Normally this would be handled by I guess this:

https://github.com/ppy/osu/blob/ae98f63b511870c11aad3d4955a1a5454a0aad58/osu.Game/Screens/Play/PlayerLoader.cs#L120-L121

which internally does

https://github.com/ppy/osu/blob/2c0140f8651dd773d8acea7e8e07c102217e89ea/osu.Game/Input/IdleTracker.cs#L81-L86

but it appears in this case the key events never _reach_ the idle tracker.

Not sure what the solution to that is. It's getting increasingly difficult to attempt to handle these edge cases with generic heuristics as the ones we currently use to delay load.

**Comment by peppy** [comment]
Yeah that's a fair point.

I think the way forward is to just have pull-in settings and block load indefinitely while they are in use. Something like what is happening in https://github.com/ppy/osu/pull/30749, we'll see how that goes.

**Comment by bdach** [comment]
So just to confirm intent, do you see this PR still going in unchanged or are you looking to try applying some changes here still?

**Comment by peppy** [comment]
I think if that's the only issue, we should get this in as a preliminary fix until something else is decided upon.

**Review by bdach — APPROVED** [review]
Fair enough

**Pull request merged**
