### PR TITLE
Simplify legacy formulas in performance calculations

### PR DESCRIPTION
**Pull request by Givikap120**
Formulas I made are very safe (almost 0 value changes).
From the approval of pp committee of respective gamemodes I can simplify them further by removing questionable things like `Math.Max(0, SR - 0.1)` that have no clear purpose to me

### CODE REVIEW

**Comment by frenzibyte** [comment]
> Formulas I made are very safe (almost 0 value changes).

Looks like tests are saying otherwise, seeing differences by up to ±0.15 which sounds completely off.

**Comment by smoogipoo** [comment]
!diffcalc

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=catch

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=taiko

**Comment by Givikap120** [comment]
> > Formulas I made are very safe (almost 0 value changes).
> 
> Looks like tests are saying otherwise, seeing differences by up to ±0.15 which sounds completely off.

uh, I forgot that Star Rating formula is not "safe", it's completely new, I can fix this

**Review by stanriders — CHANGES_REQUESTED** [review]
I think it'd be better to link [this](https://github.com/ppy/osu/pull/13986) pr in the code somewhere instead of replacing a properly derived formulas with approximations.

**Comment by frenzibyte** [comment]
Is there a point in replacing it with approximations in that case then?

**Comment by stanriders** [comment]
Apart from it "looking better" it shouldn't affect anything at all

**Comment by smoogipoo** [comment]
!diffcalc

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=catch

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=taiko

**Comment by tsunyoku** [comment]
Closing this as it's pretty useless other than making it look "nicer" but in my opinion also makes derived formulas look more random which I don't think is particularly useful.

**Pull request closed without merging**
