### PR TITLE
Adjust osu!catch proportions

### PR DESCRIPTION
**Pull request by Hanamuke**
Adjusted playfield width and catcher plate width to better match stable's. I'm not pretending it's perfect but it's way better. Here is a comparison picture.
dsbuffer bmp

### CODE REVIEW

**Comment by Hanamuke** [comment]
Should I modify CATCHER_SIZE instead of the multiplier ?

**Comment by smoogipoo** [comment]
Yeah, would be better off adjusting `CATCHER_SIZE`.

My main issue holding this one back is that it makes the playfield a smaller height than the distance from the top of the screen to the catcher. This will affect scrolling speed.

Is it possible to instead make `PlayfieldArea => new Vector2(0.58f, 0.86f)` (preserve the previous height), and remove the content offset line you added in `CatchPlayfield`? Basically the size/position of the playfield should only be controlled by this variable.

**Comment by Hanamuke** [comment]
I don't which one would match stable but yes I can do that later today

**Comment by Hanamuke** [comment]
Since 1/0.86 =1.16, maybe this why i had to scale the preempt by 1.2 to get the right scrolling speed. I should be able to get rid of it now

**Comment by smoogipoo** [comment]
I think there is something more to this. This probably looks fine for you but won't work at different resolutions. What's currently in master is basically pixel perfect to osu!stable for me and peppy @ 1440x900:

Stable:

stable

Master:

old_lazer

This PR:

new_lazer

However at 4:3 aspect the scaling is off, suggesting that osu!lazer isn't doing it quite as expected.

**Comment by smoogipoo** [comment]
Closing as this has been reimplemented in https://github.com/ppy/osu/pull/3467

**Pull request closed without merging**
