### PR TITLE
Use separate database context per transaction

### PR DESCRIPTION
**Pull request by UselessToucan**
We might want to do this because
1. It will simplify DbContext lifetime management.
2. In my opinion, it is easier to maintain the code(because I do not need to understand how database contexts are shared).

Please note that it is not ready for merge right now. Look at my TODO comments. At least, `BeatmapStore.Beatmaps` and `BeatmapStore.BeatmapSets` properties should be fixed.

### CODE REVIEW

**Comment by peppy** [comment]
this undoes context sharing completely for no good reason

if you don’t understand something please ask questions rather than undoing changes!

**Comment by UselessToucan** [comment]
> this undoes context sharing completely

Yes. I may missed something, but Why context sharing is required?

> for no good reason

As I wrote in the description, it simplifies DbContext retrieval and disposal. [Weren't you interested in DbContext disposal?](https://github.com/ppy/osu/issues/1386#issue-266420950)

**Comment by peppy** [comment]
- the overhead of constantly creating contexts is quite large, especially when change-tracking. contexts do heavy internal caching.

- it isn't simplifying anything. you just replaced a `Func` with a `factory.Method` (and broke many pieces of the puzzle in the process).

**Comment by UselessToucan** [comment]
> it isn't simplifying anything

The context is disposed right after transaction => I do not need to think about disposing it.

Anyway, since 'the overhead of constantly creating contexts' is not acceptable, I am closing this PR.

**Comment by peppy** [comment]
with the previous logic you didn't need to think about disposing... it's to be handled centrally

**Pull request closed without merging**
