### PR TITLE
Add "Deflate" mod

### PR DESCRIPTION
**Pull request by MaxOhn**
This implements the Deflate mod very simple and straight forward.
The idea is that HitCircles are their own approach circles so they start off large and then decrease in size as an approach circle would do.
~~Preview: https://streamable.com/bzjy1~~
~~Preview: https://streamable.com/ghhx1~~
Preview: https://streamable.com/9ei0w

### CODE REVIEW

**Comment by qwewqa** [comment]
The change I made in 58e989fb9d925b7b1d160f05be813ffbe90c27b1 should also fix the oversized flash/explosion when hitting the note.

**Comment by peppy** [comment]
Sliders look really lame in this one. Might want to try and apply a similar effect to them, somehow.

**Comment by MaxOhn** [comment]
SliderBody's now deflate aswell, any nested objects of sliders don't adjust their positions yet though so that's a left to do for later 😃
Also a bug I've encountered by chance is that sliders look weird if they're at the very beginning of maps or something close to that at least.

**Comment by peppy** [comment]
This is a bit outdated now. We already have `OsuModGrow` merged, and the code for it looks similar. Did you want to try implementing again based off its implementation?

**Comment by MaxOhn** [comment]
Yeah already tried the mod, plays pretty cleanly. I'd love to get back into the mods at some point, I'll try to revisit it soon

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
@MaxOhn tidied this up further. Make sure to check the changes so you can see how much nicer it could have been :).

**Pull request merged**
