### PR TITLE
Alternate background colour of chat lines to better visually distinguish wrapped lines

### PR DESCRIPTION
**Pull request by normalid-awa**
Resolved: [#29129](https://github.com/ppy/osu/discussions/29129#discussioncomment-10165872) (first bullet point)

| Master | image |
|---------|-|
| PR | image |

For better accessibility, altering the chat message background color with the message id, unit test were added

### CODE REVIEW

**Comment by peppy** [comment]
Doesn't look great. Would need some design input if we're going to do this. Also the corners of the highlight should probably be rounded, and the rows with no change to colour should probably not create needless drawables.

**Comment by normalid-awa** [comment]
> Doesn't look great. Would need some design input if we're going to do this. Also the corners of the highlight should probably be rounded, and the rows with no change to colour should probably not create needless drawables.

would go something like this?
image
image

**Comment by bdach** [comment]
paging @arflyte

**Comment by peppy** [comment]
With less rounding sure.

Apply the other changes I proposed and I'll fix up the visuals.

(I don't think this needs flyte input)

**Comment by normalid-awa** [comment]
> With less rounding sure.
> 
> Apply the other changes I proposed and I'll fix up the visuals.
> 
> (I don't think this needs flyte input)

The changes were done, the rest is the visual

**Comment by peppy** [comment]
Made some visual and behavioural changes.

**Review by peppy — DISMISSED** [review]

**Comment by normalid-awa** [comment]
omg, didn't notice altering and alternating are two meanings. 
Also, may I change the unit test `TestBackgroundAltering` renames to `TestChatlineBackgroundAlternating`?It seems to make more sense and descriptive

**Comment by peppy** [comment]
> omg, I didn't notice altering and alternating are two meanings. Also, may I rename the unit test `TestBackgroundAltering` to `TestChatlineBackgroundAlternating`?It seems to make more sense and descriptive

Good catch, I've fixed that.

**Review by peppy — DISMISSED** [review]

**Comment by bdach** [comment]
This looks so weak on dark backgrounds it may as well be imperceptible.

On daily challenge screen:



In chat overlay:



Unless there is a follow-up change to change daily challenge screen chat to have a lighter background, I don't think this fully achieves what it claims it does.

**Comment by peppy** [comment]
Might depend on screen gamma, since it doesn't look too bad here.

To improve the situation, we'll probably want to turn off additive blending and choose a more appropriate colour (white doesn't work well at higher opacities). I'll have a fiddle.

**Comment by peppy** [comment]
I think this is feeling okay now, although there's some awkward overlap (admittedly was already an issue):

osu! 2024-07-30 at 06 58 03

I'll see what I can do about that while I'm here.

**Comment by peppy** [comment]
Now:

osu! 2024-07-30 at 07 03 18

**Review by bdach — APPROVED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
