### PR TITLE
Add proper scaling support to skin editor

### PR DESCRIPTION
**Pull request by peppy**
Handles selections roughly as expected, adjusting each item relative to the bounding box of all items. Code can probably be further optimised but I'm keeping it quite verbose for readability for the time being.

https://user-images.githubusercontent.com/191335/118852210-8874c700-b90d-11eb-9ab1-feba6fc54cbc.mp4

### CODE REVIEW

**Comment by peppy** [comment]
Blocking momentarily as I found an issue and a way to clean up the code more.

**Comment by peppy** [comment]
This is ready to go now.

**Comment by bdach** [comment]
I've thought about it some more and this is actually not very simple in the case of arbitrary rotation... See image, it can probably explain better than any of my words can.

bitmapa

I'd probably go with the "less bad" option and only add special casing when the rotation angle is a multiple of 90deg, though, just for simplicity. Alternatively we could consider having the selection box be not-always-upright and rotate along with the blueprint as well, which also gets rid of this issue (drags then always happen in component space).

**Comment by peppy** [comment]
Good call — I was 100% aware and went through the same thought process a few days ago, then completely forgot about that case while implementing this.

Will take a look today, I think it's best we get this right from the start.

**Comment by peppy** [comment]
I've applied changes. To keep things simple, I'm just falling back to aspect scale in all cases rotation isn't absolutely zero. I think rotation is an edge case to start with, and doing non-aspect scale on a rotated element is... likely never what the user wants. So this should be fine.

**Review by smoogipoo — APPROVED** [review]
Looks to work correctly. We'll need a "reset rotation" button at some point.

**Pull request merged**
