### PR TITLE
Fix legacy BpmMultiplier clamp value

### LINKED ISSUE #17143: Ranked convert map with low SV not converting correctly in taiko and mania
### Discussed in https://github.com/ppy/osu/discussions/17120

<div type='discussions-op-text'>

<sup>Originally posted by **zachmanthethird** March  6, 2022</sup>
Originally mentioned in #15747 and #15808
> https://osu.ppy.sh/b/1494828 At 02:32:949, there's a 0.01x velocity point with a slider that lasts until 02:35:949. In taiko and mania, this note lasts until approximately 03:03. 
> osu_2021-11-22_12-16-07
> osu_2021-11-22_12-35-31
> osu_2021-11-22_12-35-55

While originally discarded as a duplicate of #14835, I don't think that's the case. There will inevitably be maps with lower scroll speeds than the allowed limit, and lazer isn't calculating the duration properly for these modes. If std and catch aren't affected, why should taiko and mania?
For clarification, this is NOT about allowing lower scroll speeds. This is about ensuring duration is accurate to allow converts to be played. You can still set the SV to 1 but have the correct duration and have the map be playable. In its current state, the map isn't.</div>

### PR DESCRIPTION
**Pull request by sw1tchbl4d3r**
Resolves #17143
This ensures that BpmMultiplier stays below or at 10, which corresponds to a 0.1 slider velocity value, the minimum.
I'm not sure if this needs tests, seems like a one and done thing.

Seems to be the correct behaviour, as in stable, a 0.01 slider velocity value as seen in the example beatmap in the linked issue is treated exactly the same as a 0.1 slider velocity value, which also applies in beatmap conversion.

### CODE REVIEW

**Comment by bdach** [comment]
Not sure how valid this fix is. 0.01x SVs are valid on stable, but only in taiko and mania, as far as I can see. The only reason this change doesn't break mania-first maps is that `BpmMultiplier` is only ever used in conversion algorithm code right now.

**Comment by sw1tchbl4d3r** [comment]
We could alternatively clamp directly in the conversion logic code, but didn't want to touch it without confirmation due to the comments in that area.

**Review by peppy — COMMENTED** [review]
Looks okay conceptually, but I haven't checked how this plays out. @smoogipoo will know better I think.

**Comment by smoogipoo** [comment]
I think there's still a bit of work left on this one.

Of particular importance is this code when figuring out the beat length (in osu-stable):
```csharp
if (PlayMode == PlayModes.Taiko || PlayMode == PlayModes.OsuMania)
    mult = ControlPoints[samplePoint].BpmMultiplierMania;
else
    mult = ControlPoints[samplePoint].BpmMultiplier;
```
What are these two `BpmMultiplier`s?:
```csharp
internal float BpmMultiplier
{
    get
    {
        if (BeatLength >= 0) return 1;

        return OsuMathHelper.Clamp((float)-BeatLength, 10, 1000) / 100f;
    }
}

internal float BpmMultiplierMania
{
    get
    {
        if (BeatLength >= 0) return 1;

        return OsuMathHelper.Clamp((float)-BeatLength, 10, 10000) / 100f;
    }
}
```

Our `BpmMultiplier` implementation is equivalent of `BpmMultiplierMania` in osu-stable code:
https://github.com/ppy/osu/blob/9473c350b50c5c6aa6a10a674f45ccaa67158ecc/osu.Game/Beatmaps/Formats/LegacyDecoder.cs#L177-L183

There's a few things to notice here:
1. `PlayMode`, in this case, refers to the beatmap's play mode.
2. `BpmMultiplierMania` is used when the beatmap is taiko or mania specific.
3. `BpmMultiplier` is used when the beatmap is an osu! beatmap.
4. That little comment above the code in our implementation seems relevant. I'm not sure/don't think that the post-facto clamping is equivalent to doing it in-line.

This PR somehow needs to make sure that it's using the correct value. Either it defines two `BpmMultiplier` properties as stable does and do the checks within each converter, or it switches the implementation directly inside `LegacyDifficultyControlPoint` based on the beatmap's ruleset.

**Comment by smoogipoo** [comment]
@sw1tchbl4d3r The taiko code in particular runs for both taiko and non-taiko beatmaps I'm pretty sure, keep that in mind along with my comment above.

**Comment by sw1tchbl4d3r** [comment]
Thanks for the tips, since the control point doesn't know in which mode it was used I've gone with the two seperate variable way.

**Comment by sw1tchbl4d3r** [comment]
Also, I don't know if this is the correct place to ask or rather the discord, but I would like to get access to the stable code relating to taiko beatmap conversion, specifically the code that determines slider length, since this is the last missing piece of the problem.
As mentioned in the linked issue, there's something else going on in stable's conversion code that we're not replicating in lazer.
Specifically, this testcase ([.osu](https://sw1tchbl4d3.com/static/files/20658/low-sv-slider.osu), [.json](https://sw1tchbl4d3.com/static/files/20658/low-sv-slider-expected-conversion.json)) fails, because stable is making the slider longer than it should be, in the same 0.01x SV scenario seen in the example beatmap in the linked issue.

**Comment by bdach** [comment]
[As was mentioned in the issue thread](https://github.com/ppy/osu/issues/17143#issuecomment-1060203655) the taiko calcs are very sensitive to FP error (incurred by differences of FP behaviour between .NET Framework and .NET Core/.NET >=5).

**Comment by sw1tchbl4d3r** [comment]
It doesn't have to be perfect, but the difference isn't too small even after this change, on the example test, stable gives an end time for the drumroll of `3153`ms, while lazer currently gives `2538`ms, since this is half a second of error this could decide if a drumroll and a hit near this drumroll overlap or not, which could be an issue.
But, after further testing, it seems like the example map I made got into this state out of pure chance, I can't reliably reproduce creating a faulty map, so this seems to be an extremely unlikely case anyway.

**Comment by smoogipoo** [comment]
This is something that I'll have to look into personally, because I've gone through the calcs with a fine-toothed comb already all the way down to .NET internals.

**Comment by sw1tchbl4d3r** [comment]
All values are expected, according to [this script](https://gist.github.com/sw1tchbl4d3r/85a5d54acdb2ac0ac1550b21f09f9361), so seems good to go!
Basically just downloaded all of the changed maps, ran the script through the diff, imported both the original and clamped diffs into stable and lazer, then checked if they're the same on stable, and checked sr diff in lazer.

**Review by smoogipoo — APPROVED** [review]

**Comment by smoogipoo** [comment]
Also done a little bit of testing. @peppy requesting your review/merge

**Review by peppy — APPROVED** [review]
Without getting too deep into this, it looks okay.

**Pull request merged**
