### PR TITLE
Show mods that are incompatible with the current selection

### PR DESCRIPTION
**Pull request by hlysine**
Based on discussion #14304 

A red tint is applied to mods that are incompatible with the current selection. It is purely visual and the buttons are still clickable.
image

The tooltip of mod buttons also lists all the mods that are incompatible. The mods are listed in small icon form to keep the tooltip reasonably sized.
image

### CODE REVIEW

**Comment by peppy** [comment]
The red tint doesn't work well. @arflyte could you provide a proposal for this (in the current design)? Maybe a circle with a cross overlayed in the bottom right corner of the hexagon?

**Comment by Henry-YSLin** [comment]
> Maybe a circle with a cross overlayed in the bottom right corner of the hexagon?

Went ahead and tried this while waiting for flyte's opinion. It does look much better without confusing with unimplemented mods.
image

**Comment by peppy** [comment]
I think that's better, but the design needs some work. I'll modify it slightly to the point I'm happy to get this in. I think a proper design will come with the new skin selection screen design itself (cc @arflyte to add this to your list of considerations)

**Comment by peppy** [comment]
I've made some fixes to this and also updated the visuals to feel more in-line with expectations. The major fix was to use the selected mods bindable from the local selection context, rather than a potentially game-global one.

Seems fine otherwise.

https://user-images.githubusercontent.com/191335/130558675-6a375824-a93c-4ce7-b4cc-abf8e8e2e101.mp4

**Review by peppy — APPROVED** [review]

**Review by smoogipoo — APPROVED** [review]
lgtm

**Pull request merged**
