### PR TITLE
Added Launch Batch file

### PR DESCRIPTION
**Pull request by make-42**
Added Launch Batch file with "dotnet run --project osu.Desktop -c Releases" command

Add any details pertaining to developers above the break.

---

Add a sentence or two describing this change in plain english. This will be displayed on the [changelog](https://osu.ppy.sh/home/changelog). A single screenshot or short gif is also welcomed.

### CODE REVIEW

**Comment by jorolf** [comment]
https://github.com/ppy/osu/pull/4050#issuecomment-453770491
> Why do we need this? Most of us use an IDE which already does this

**Comment by TTACTICAL** [comment]
Ease of use

**Comment by nbvdkamp** [comment]
People that want ease of use (and only want to run osu.Desktop) should probably just use the installer instead of building themselves.

**Comment by jorolf** [comment]
Or they'll use an IDE

**Comment by tangalbert919** [comment]
You don't need an IDE to compile and then run something (lazer, in this instance).

Also, I'm certain this PR is just so people don't need to read the "Building and Running" section on the README (or even have working knowledge on why reading is important).

**Comment by smoogipoo** [comment]
Unnecessary for development.

**Pull request closed without merging**
