### PR TITLE
Add countdown settings to setup screen

### PR DESCRIPTION
**Pull request by bdach**
- [x] Depends on https://github.com/ppy/osu/pull/14580

osu_2021-08-30_22-37-40

Because the countdown is not yet implemented and there's a bit of conditional show/hide and parsing logic I added tests this time. Probably could have not bothered but oh well they're there now.

There's also an addition of a labelled textbox in this diff, but it's a 12-line class, and that's including using statements and the license header, so I really didn't want to bother splitting that out as well. I'll do it on request, I guess.

### CODE REVIEW

**Comment by peppy** [comment]
Two things I noticed:

- With the v2 interface things, I think we're supposed to be grouping related controls in the same rounded section, which would imply that the (expanding) countdown setting should appear within the same rounded box as the toggle. Though looking at figma, these boxes are likely going away so probably not a huge concern for the moment.
- Not a huge fan of the squishing (due to scale transform). Should probably be a masking transition + resize instead (also there's a sharp snap at the end due to the flow/autosize, but probably a harder one to fix):

20210831 133748 (dotnet)

**Comment by bdach** [comment]
The [old designs](https://github.com/ppy/osu/issues/2434#issuecomment-402936979) also had the rounded sections separated. Although as you said all of that is getting changed in the long run anyway, so I just did whatever's fastest.

I'll reassess the transition, though. Probably not the best, indeed, was just the first idea that sprang into my mind that wasn't an instant fade-out.

**Comment by peppy** [comment]
I think instant update is better than scale, if that's what it comes to. We can nail out the transitions later on (read: add back), either way.

**Comment by bdach** [comment]
I've tried a few things and none really held up to closer scrutiny, for two reasons:

* The jump you mention is caused by the fill flow excluding the countdown settings from `FlowingChildren` when their `IsPresent` becomes false. This exclusion causes the spacing for the items to also go away at that precise frame when presence changes, causing the (always 1-frame) jump.
* There are other places that do masking (news sidebar), but for autosized containers this is awkward (you have to turn autosize off and manually resize to 0 via a transform when hiding, but then when show is requested, it is required to turn it back on, apply autosize easing/duration, and ensure that the transform is gone to avoid exceptions being thrown).

So I've nuked it all, and the transitions are instant for now. It looks kinda janky but in slowmo everything I tried looked janky one way or another (or could crash).

**Review by peppy — APPROVED** [review]

**Pull request merged**
