### PR TITLE
Timing based hitcircle colouring implementation

### PR DESCRIPTION
**Pull request by mk56-spn**
PRing again with properly named commit(s) and cleaner code, implements the feature from https://github.com/ppy/osu/discussions/15220

example video: 
https://www.youtube.com/watch?v=30-IITUrvyE&ab_channel=Daysofthunder

Many thanks to apolloDW, spaceman_atlas and https://github.com/Tina-otoge for helping me get things fixed

### CODE REVIEW

**Review by bdach — CHANGES_REQUESTED** [review]

**Review by bdach — COMMENTED** [review]
Sorry but the latest changes just have me confused further.

**Comment by mk56-spn** [comment]
merge was neccesary to fix issues i was having with data due to realm updates

**Comment by bdach** [comment]
Is this ready for a re-review yet? Difficult to tell from the log alone.

**Comment by mk56-spn** [comment]
> Is this ready for a re-review yet? Difficult to tell from the log alone.

i wish lol its ballooned into a whole refactoring task to get it to work as a single toggle for both rulesets as suggested, ill bump this when its ready

**Comment by peppy** [comment]
It doesn't need to be a single toggle, don't worry too much. The bigger question is whether this is something we want in the first place, which I am still dwelling over.

**Comment by mk56-spn** [comment]
> It doesn't need to be a single toggle, don't worry too much. The bigger question is whether this is something we want in the first place, which I am still dwelling over.

well all i can say is after playing with it as my main option for jsut under a month it can change the way you play more than youd first think, it introduces a new layer to reading which ive very much enjoyed, as have the people  whove played my branch , ofcourse i understand that me saying a change i made is good isnt exactly  the most convincing argument on earth, but unless your uncertainty comes from a personal decision you wish to make rather than community opinion i think running a poll would solidify it one way or another.

**Comment by peppy** [comment]
The issue is combo colours, as I have already mentioned. I don't foresee this PR being merged without further discussion with mappers, and potentially design input to separate this colour coding from combo colours.

**Comment by peppy** [comment]
For what it's worth i've passed on the requirements I have for seeing this go forward to @arflyte. It's not going to be a high priority but I think we can find a way to move this forward that doesn't involve replacing the whole combo colour.

**Comment by mk56-spn** [comment]
> The issue is combo colours, as I have already mentioned. I don't foresee this PR being merged without further discussion with mappers, and potentially design input to separate this colour coding from combo colours.

yeah currently it just hijacks combo colour destroying that functionality, eitherway whatever you decide idgaf if my code gets binned ( hell id even be happy to  see it be the case if its for a better alternative) but id still like to help with whatever the imlementation ends up being if possible, ive grown quite attached to this little project and any experience is good experience since i plan to become a regular contributor with time

**Comment by mk56-spn** [comment]
ok so ik this is currently blocked but imma refactor it with what ive learnt since as a learning experience,  just a heads up to  feel free to ignore commits or comments made here for now

**Comment by smoogipoo** [comment]
Closing this due to inactivity. Waiting on whenever flyte addresses the requirements peppy supposedly proposed to him (that I have no idea about and there's no log of anywhere).

**Comment by peppy** [comment]
For the record, the requirements were for adding an element to hitobjects which can be styled based on colouring (ie. an element which doesn't replace combo colouring).

**Pull request closed without merging**
