### PR TITLE
Fix dialog going off-screen when UI scaling is applied

### PR DESCRIPTION
**Pull request by mulraf**
Regarding https://github.com/ppy/osu/issues/5040

New here, i never really programmed on a big project like this. It looks kinda makeshift / too easy and i hope it doesn't cause any other issues but i've seen nothing wrong and it fixed the issue for me. It was all dialog boxes that got cut off at the top (so also deleting all beatmaps etc.)

### CODE REVIEW

**Review by frenzibyte — CHANGES_REQUESTED** [review]
Did you test your changes, because the changes you made covered the description
popup

**Comment by iiSaLMaN** [comment]
The real fix here is to play with the spacing of the icon, title and description, reduce the bottom margin of the icon, reduce the spacing between each drawable, etc..

**Comment by mulraf** [comment]
sorry, didn't see this. i hope this fixes it (at least in the testing it worked for me now).

**Comment by peppy** [comment]
I made some fixes to reduce the number of padding/margins, instead using spacing on the main fillflow. This also reduces the weird negative padding.

**Review by peppy — APPROVED** [review]

**Review by smoogipoo — APPROVED** [review]

**Comment by swoolcock** [comment]
In future please create a branch rather than working directly from master.

**Pull request merged**
