### PR TITLE
Normalise trailing commas in code

### PR DESCRIPTION
**Pull request by Joehuu**

### CODE REVIEW

**Comment by peppy** [comment]
Was this applied using rider automation?

**Comment by Joehuu** [comment]
Using this, yep.
Screen Shot 2021-12-28 at 8 25 21 PM

It's your call on this, but I like having one choice and consistency. Another downside is having +1 commits on future PRs fixing this inspection for those people who don't check locally first.

**Comment by bdach** [comment]
Weakly against this. Not only does this incur a 1.4k-file diff, it feels too pedantic/scrutineering even for my tastes. Not to mention that trailing commas sometimes are *beneficial* for things like reading diffs and blame.

To expand on the last part: if you add something to a comma-delimited list that doesn't have a trailing comma, then you have to touch the last item before adding the new item, which causes 1 extra green line in diffs and obscures blame.

**Comment by peppy** [comment]
Not to mention it also potentially adds one extra pointless commit to traverse when blaming files.

**Comment by Joehuu** [comment]
I guess we can revisit this once https://github.com/github/feedback/discussions/5033 is supported on GitHub, as it can only be done locally right now.

**Comment by peppy** [comment]
I think we should leave this for now. It's not offensive enough to warrant such a large change in lines. Also shows that we aren't consistent until now and no one has really cared much.

**Pull request closed without merging**
