### PR TITLE
Improve song select display on ultrawide displays (or when UI scale is set low)

### PR DESCRIPTION
**Pull request by peppy**
Before:

image

After:

image

### CODE REVIEW

**Comment by power9maker** [comment]
Would it be possible to make a slider in settings to adjust size of this?

**Comment by peppy** [comment]
There is a slider already (UI Scale).

**Comment by power9maker** [comment]
Yes I know, but I mean a slider for how far apart songs (on the right) and song description (on the left) are. So you can go back to old style if you want to.

**Comment by peppy** [comment]
No, this is unnecessary.

**Comment by power9maker** [comment]
Just checked this and discovered you can't absolute scroll with right click on this black part
AbsoluteScroll

**Comment by peppy** [comment]
That sounds correct. Right click scroll should only apply within the carousel confines IMO.

**Comment by power9maker** [comment]
On stable you can right click basically anywhere to absolute scroll, while on lazer you have to aim between this black box I highlighted on screen in previous comment and the actuall songs. This area on my 21:9 isn't that big, which makes absolute scrolling less convenient and slower to use. 
Idk what others think about it, but that's what I do.

**Comment by peppy** [comment]
We'll likely improve the absolute scroll mechanic with a better scroll bar in the future.

**Review by smoogipoo — APPROVED** [review]
Seems to look okay.

**Pull request merged**
