### PR TITLE
Disable SSBO for now

### PR DESCRIPTION
**Pull request by peppy**
Too many performance issues reported. We're going to have to do more testing before pushing this out.
See https://github.com/ppy/osu/issues/24751.

### CODE REVIEW

**Comment by X9VoiD** [comment]
Doesn't seem like adding the environment variable fixes the performance regression on my machine by setting it here.
image

**Comment by peppy** [comment]
> Doesn't seem like adding the environment variable fixes the performance regression on my machine by setting it here.
> image

Could you test the latest release which has this PR already incorporated?

**Comment by Feodor0090** [comment]
It's even worse for me.
On 2023.908.1 with ssbo enabled (no envs touched) there was 120 fps in song select and ~200 in gameplay.
On 2023.908.2 there are only 75 in song select and 110-120 in osu! autoplay.

I had ~170 and ~300 in previous releases. I'm on linux with legacy gl renderer. Mesa is the latest.

**Comment by GuineaGuy99** [comment]
Performance aside this may also fix #24766 and #24767

**Comment by longnguyen2004** [comment]
The hotfix is in the latest release now, yet we're still seeing errors. Is the feature flag missing in some other related area of the code?

**Comment by X9VoiD** [comment]
> Could you test the latest release which has this PR already incorporated?

Unfortunately, it did not help.

**Comment by peppy** [comment]
More reports of things still broken:

https://github.com/ppy/osu/issues/24769#issuecomment-1712541519

**Comment by smoogipoo** [comment]
@X9VoiD Are you able to compile the game? Would be curious if running with `OSU_GRAPHICS_NO_SSBO=1` in combination with changing the following `60` values to `1` fixes the performance:

https://github.com/ppy/osu-framework/blob/fc5cd7ec2a5d5f7ec6b3e258350073c2e093f9bc/osu.Framework/Graphics/Rendering/Renderer.cs#L203

https://github.com/ppy/osu-framework/blob/fc5cd7ec2a5d5f7ec6b3e258350073c2e093f9bc/osu.Framework/Resources/Shaders/Internal/sh_MaskingInfo.h#L42

**Comment by X9VoiD** [comment]
Applying that on osu-framework/master, then building osu/disable-ssbo with `dotnet run --project osu.Desktop --configuration Release` causes a crash. It did not print out to console but the exception is logged to event viewer.

```
System.ArgumentOutOfRangeException: The size of the buffer must be at least 2. (Parameter 'uboSize')
   at osu.Framework.Graphics.Rendering.ShaderStorageBufferObjectStack`1..ctor(IRenderer renderer, Int32 uboSize, Int32 ssboSize) in C:\Users\oscar\projects\osu-framework\osu.Framework\Graphics\Rendering\ShaderStorageBufferObjectStack.cs:line 67
   at osu.Framework.Graphics.Rendering.Renderer.BeginFrame(Vector2 windowSize) in C:\Users\oscar\projects\osu-framework\osu.Framework\Graphics\Rendering\Renderer.cs:line 203
   at osu.Framework.Graphics.Veldrid.VeldridRenderer.BeginFrame(Vector2 windowSize) in C:\Users\oscar\projects\osu-framework\osu.Framework\Graphics\Veldrid\VeldridRenderer.cs:line 256
   at osu.Framework.Graphics.Rendering.Renderer.osu.Framework.Graphics.Rendering.IRenderer.BeginFrame(Vector2 windowSize) in C:\Users\oscar\projects\osu-framework\osu.Framework\Graphics\Rendering\Renderer.cs:line 1132
   at osu.Framework.Threading.DrawThread.OnInitialize() in C:\Users\oscar\projects\osu-framework\osu.Framework\Threading\DrawThread.cs:line 31
   at osu.Framework.Threading.GameThread.Initialize(Boolean withThrottling) in C:\Users\oscar\projects\osu-framework\osu.Framework\Threading\GameThread.cs:line 265
   at osu.Framework.Threading.GameThread.<createThread>g__runWork|66_0() in C:\Users\oscar\projects\osu-framework\osu.Framework\Threading\GameThread.cs:line 409
   at System.Threading.Thread.StartHelper.Callback(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Thread.StartCallback()
```

So I went ahead and changed 1's to 2. It worked however, performance is still not fixed.

**Pull request closed without merging**
