### PR TITLE
Remove default-to-cancel assumption on exiting popup dialogs

### LINKED ISSUE #6822: Dialog cancel button animates while others do not
Cancel button looks like it was hovered for a second
nice

### PR DESCRIPTION
**Pull request by mcendu**
Fix #6822 Aside from some minor refactoring in the same PR, I think that #6825 might be a better solution if the default-to-cancel assumption is correct.

### CODE REVIEW

**Comment by bdach** [comment]
I think we'd want to keep the effect of pressing the cancel button on hide for UX purposes.

**Comment by mcendu** [comment]
> I think we'd want to keep the effect of pressing the cancel button on hide when no action was triggered for UX purposes.

This assumption is not correct in some cases. I'll take the exit confirm dialog as an example here: When the player clicks the close window button the second time, the player is doing the equivalent of pressing "Good bye", instead of the cancel button.

**Comment by bdach** [comment]
I see - in that particular case could we possibly add a special path that would trigger the confirm button then? I'd say that'd be the best possible fix of all available.

**Comment by mcendu** [comment]
Please close this issue if #6825 is merged. The minor code refactor here is no longer necessary as the same change is featured in #6839

**Pull request closed without merging**
