### PR TITLE
Allow full osu!direct usage regardless of supporter status

### PR DESCRIPTION
**Pull request by peppy**
One more reason to try lazer, I guess? Updates the disclaimer screen a touch.

### CODE REVIEW

**Review by smoogipoo — APPROVED** [review]

**Comment by DustyTF** [comment]
It does not seem to work on iOS. It says after I clicked on the direct download button, it says an error occured. Even if I clicked on the beatmap itself, it still says that I need to be a supporter.

**Comment by peppy** [comment]
see https://github.com/ppy/osu/pull/4119

**Comment by Toybonnie1234512341** [comment]
Still doesn’t work

**Comment by peppy** [comment]
go away.

**Pull request merged**
