### PR TITLE
Improve mouse interactions at song select

### PR DESCRIPTION
**Pull request by peppy**
Spurred by https://github.com/ppy/osu/discussions/25181#discussioncomment-7337636, it seems we can easily fix this to be in line with users' expectations.

I think this feels much better than what we had.

### CODE REVIEW

**Review by Joehuu — DISMISSED** [review]
Seems to not break anything.

**Comment by bdach** [comment]
> Seems to not break anything.

I'm not sure I share the sentiment... This leads to some pretty random behaviours.

https://github.com/ppy/osu/assets/20418176/241213b1-4c9e-4fe0-8782-87bb2b277add

- Right clicking the headers on the left scrolls the carousel, but then changing hover resets it weirdly
- Scroll working through the gaps on the leaderboard

I'm also not sure what https://github.com/ppy/osu/pull/25182/commits/0ae0b0c353618b7289d6fe6b6aac7c34ad9b9886 even does?

**Comment by peppy** [comment]
> I'm also not sure what https://github.com/ppy/osu/commit/0ae0b0c353618b7289d6fe6b6aac7c34ad9b9886 even does?

It changes the reset area from being a tiny 250 width pixels to correctly being the left hand content.

I'm not sure the other issues you have are worth addressing until we get the redesign in. If you think it's important, we could block fall-through scroll operations in this region quite easily, though.

**Comment by bdach** [comment]
> I'm not sure the other issues you have are worth addressing until we get the redesign in. If you think it's important, we could block fall-through scroll operations in this region quite easily, though.

I think it would be best to fix this now by blocking input because I don't exactly have confidence in the redesign arriving anytime soon and I do find the issues above quite bad myself.

**Comment by peppy** [comment]
I've fixed the two issues pointed out.

**Review by bdach — APPROVED** [review]

**Pull request merged**
