### PR TITLE
Reduce spacing in settings items

### PR DESCRIPTION
**Pull request by peppy**
Felt like too much, maybe? Looking for more opinions.

| Before | After |
|:------:|:-----:|
| osu! 2021-09 at 06 38 55 | osu! 2023-07-21 at 06 39 23 |

### CODE REVIEW

**Comment by novialriptide** [comment]
I like it.

**Comment by Glinte** [comment]
The spacing between "Output device" and the dropdown box feels better before

**Comment by agatemosu** [comment]
It looks better, although I think the sliders look too spaced out

**Review by bdach — APPROVED** [review]
Sure, doesn't look much better or worse as far as I'm concerned, so I'm fine with going with it. Dunno if this is enough opinions for you already.

**Review by Joehuu — APPROVED** [review]
Seems better. The before and after images are swapped, so not sure how correct the other opinions are.

**Comment by bdach** [comment]
> so not sure how correct the other opinions are

If you're asking me, then I read the diff and checked out the code myself. So I know what I approved.

**Pull request merged**
