### PR TITLE
Fix hidden mod crashing in osu! ruleset

### LINKED ISSUE #11015: Hidden mod crashes with KeyNotFoundException
**Describe the crash:** 
the game suddenly crashed after going into the spectator mode (ingame).

**osu!lazer version:** 
2020.1128.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5616758/runtime.log)
[updater.log](https://github.com/ppy/osu/files/5616759/updater.log)
[database.log](https://github.com/ppy/osu/files/5616760/database.log)
[network.log](https://github.com/ppy/osu/files/5616761/network.log)
[performance.log](https://github.com/ppy/osu/files/5616762/performance.log)

### PR DESCRIPTION
**Pull request by smoogipoo**
Prereqs:
- [x] https://github.com/ppy/osu/pull/11073

Fixes https://github.com/ppy/osu/issues/11015

This became easier to repro after https://github.com/ppy/osu/pull/10985 hence the test I added.

This PR reworks `OsuModHidden` to look up the slider head rather than storing locally. It also moves the initial fade adjustment into `ApplyToBeatmap`- not sure why this wasn't done from the get-go.

### CODE REVIEW

**Comment by bdach** [comment]
To quote my previous PR:

> The reason the mapping of slider tails/repeats to heads is not done in ApplyToBeatmap() is that doing so badly breaks TestSceneSliderHidden in a way I'm not even sure how to fix, as the test ignores the current beatmap and just rolls its own hit objects.

Might not be an issue here as I haven't looked at the diff yet, but that was the rationale at the time.

**Comment by peppy** [comment]
On a quick check, the test scene seems to look and behave as one would expect.

**Comment by peppy** [comment]
Until it crashes:

```

[runtime] 2020-12-03 07:47:21 [error]: NUnit.Framework.AssertionException: :
[runtime] 2020-12-03 07:47:21 [error]: at osu.Framework.Logging.ThrowingTraceListener.Fail(String message1, String message2)
[runtime] 2020-12-03 07:47:21 [error]: at System.Diagnostics.TraceInternal.Fail(String message, String detailMessage)
[runtime] 2020-12-03 07:47:21 [error]: at System.Diagnostics.TraceInternal.TraceProvider.Fail(String message, String detailMessage)
[runtime] 2020-12-03 07:47:21 [error]: at osu.Game.Rulesets.Osu.Mods.OsuModHidden.getFadeOutParameters(DrawableOsuHitObject drawableObject) in /Users/dean/Projects/osu/osu.Game.Rulesets.Osu/Mods/OsuModHidden.cs:line 133
[runtime] 2020-12-03 07:47:21 [error]: at osu.Game.Rulesets.Osu.Mods.OsuModHidden.applyState(DrawableHitObject drawableObject, Boolean increaseVisibility) in /Users/dean/Projects/osu/osu.Game.Rulesets.Osu/Mods/OsuModHidden.cs:line 63
[runtime] 2020-12-03 07:47:21 [error]: at osu.Game.Rulesets.Osu.Mods.OsuModHidden.ApplyNormalVisibilityState(DrawableHitObject hitObject, ArmedState state) in /Users/dean/Projects/osu/osu.Game.Rulesets.Osu/Mods/OsuModHidden.cs:line 53
[runtime] 2020-12-03 07:47:21 [error]: at osu.Game.Rulesets.Mods.ModWithVisibilityAdjustment.<ApplyToDrawableHitObjects>b__10_0(DrawableHitObject o, ArmedState state) in /Users/dean/Projects/osu/osu.Game/Rulesets/Mods/ModWithVisibilityAdjustment.cs:line 86
[runtime] 2020-12-03 07:47:21 [error]: at osu.Game.Rulesets.Objects.Drawables.DrawableHitObject.updateState(ArmedState newState, Boolean force) in /Users/dean/Projects/osu/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs:line 459
```

**Comment by smoogipoo** [comment]
That is... scary. To say the least.

**Review by bdach — APPROVED** [review]
looks correct :+1:

**Review by peppy — APPROVED** [review]

**Pull request merged**
