### PR TITLE
Don't fetch `beatmapset` that already `PendingDelete` when import score

### PR DESCRIPTION
**Pull request by cdwcgt**
😐

fix that score can be import when `beatmapset` is `PendingDelete`

### CODE REVIEW

**Comment by cdwcgt** [comment]
First, while scores can be imported, there will be some visual errors when trying to open it due to the deleted beatmap.
and second, I'm writing a function to automatically search the missing beatmap which score need (rework of https://github.com/ppy/osu/pull/14044)
Unless we make changes to the process of importing scores from deleted pending beatmap like post a notification to to prompt the user that this beatmap is being deleted.

Or it should not import successfully

**Comment by peppy** [comment]
Okay let's just go with this for now. It's such a weird behaviour that I'm not sure what the correct path forward is (and I'm getting deja vu just typing this because I'm confident we've discussed this in the past).

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
My fault for not testing more in-depth, but this just doesn't work.

@cdwcgt please test your code before considering PR.

**Comment by cdwcgt** [comment]
Feels weird, I split it from my another branch(Implemented downloading of missing beatmap), maybe I miss something on it, because I tested on that branch without encountering problems

Looks like I would leave this patch fixed when that branch is ready

**Pull request merged**
