### PR TITLE
Block screen suspend while gameplay is active

### PR DESCRIPTION
**Pull request by peppy**
Adds very basic usage of framework-side implementation. Currently only supported on android and iOS. Wanted to get this in before we completely forget that the framework support exists for it.

- [x] Needs mobile device testing (will do this tomorrow)

### CODE REVIEW

**Comment by Game4all** [comment]
Tested this on my android device and it seems to work as intended (blocking screen suspension when the gameplay is paused).

However, that behaviour of only blocking screen suspension when gameplay is paused doesn't make much sense to me. Wouldn't it be better if the screen suspension was blocked during all the time the player is in gameplay? That means that the game could currently suspend on the user's device during gameplay if he weren't to have interaction with the device during a few seconds (you can reproduce this on this branch by enabling NoFail and not interacting with the device during a few seconds / or by hitting a very long break in a map).

**Comment by bdach** [comment]
That just looks like a forgotten negation in the `BindValueChanged` callback. Judging by PR title and commit message of add1265 I can't imagine it was intended to block suspension only during pause.

**Comment by Game4all** [comment]
I'm still of the opinion that the screen suspension should be blocked during gameplay even when it is paused (at least for now) given that the framework doesn't support resuming suspended activity on mobile devices.

**Comment by peppy** [comment]
Not supporting resuming is not a concern here. The idea is it should only avoid suspension during gameplay, not when paused.

**Comment by peppy** [comment]
@bdach no, the direction is actually correct here. if you pause the game your device should be allowed to go to sleep.

**Comment by swoolcock** [comment]
> ...given that the framework doesn't support resuming suspended activity on mobile devices.

Works fine on iOS, not Android.

**Comment by peppy** [comment]
Tested and confirmed working as intended.

**Review by smoogipoo — APPROVED** [review]
Looks ok

**Pull request merged**
