### PR TITLE
Add input toggles to the PlayerLoader screen

### PR DESCRIPTION
**Pull request by UselessToucan**
osu_2018-05-09_17-30-40

### CODE REVIEW

**Comment by peppy** [comment]
Mouse buttons maybe, but I'm not sure why we need mouse wheel here. It sounds like something you'd set once and leave it in place.

The loading screen should only contain quick-access settings which are regularly changed by users.

**Comment by peppy** [comment]
Why did you change the margins?

**Comment by UselessToucan** [comment]
For consistency with the player screen. In my opinion, it looks better this way.

**Comment by peppy** [comment]
let’s not. if you want such consistency the UI should be shared

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by UselessToucan** [comment]
osu_2018-05-21_18-54-08

**Review by peppy — APPROVED** [review]

**Pull request merged**
