### PR TITLE
Fix null reference while hiding toolbar on tests

### PR DESCRIPTION
**Pull request by frenzibyte**
Found while fixing something else relevant to here

### CODE REVIEW

**Comment by peppy** [comment]
Can you explain how this happens?

**Comment by bdach** [comment]
Also a test would be nice, if it's a scenario reproducible under tests.

**Comment by iiSaLMaN** [comment]
> Can you explain how this happens?

Hide the toolbar in test scenes.
 - `userButton` is never null on `PopOut`as it is only invoked on `LoadComplete` are after so I removed the null conditional for it, 
 - `userButton.StateContainer` is null as the button resolves the `LoginOverlay` which may or may not be null

> Also a test would be nice, if it's a scenario reproducible under tests.

There will be a test case I'm preparing for another PR that hides the toolbar for testing something.

**Comment by peppy** [comment]
A better title would be "Fix null reference while hiding toolbar in tests".

**Pull request merged**
