### PR TITLE
Don't attempt to submit score when nothing has been hit

### PR DESCRIPTION
**Pull request by peppy**
This is already guarded against web-side, but as the client was still submitting such scores would throw an error (ie. when retrying before a beatmap has started):

```csharp
2021-07-03 13:40:48 [verbose]: Request to https://osu.ppy.sh/api/v2/beatmaps/339640/solo/scores/5249156 failed with System.Net.WebException: UnprocessableEntity.
2021-07-03 13:40:48 [verbose]: Response was: {"error":"field cannot be empty: 'statistics'"}
2021-07-03 13:40:48 [verbose]: Failing request osu.Game.Online.Solo.SubmitSoloScoreRequest (osu.Game.Online.API.APIException: field cannot be empty: 'statistics'
2021-07-03 13:40:48 [verbose]: ---> System.Net.WebException: UnprocessableEntity
2021-07-03 13:40:48 [verbose]: --- End of inner exception stack trace ---)
```

### CODE REVIEW

**Comment by PercyDan54** [comment]
Test failure seems related

**Comment by peppy** [comment]
You're a smart one.

**Comment by bdach** [comment]
Just to confirm intent here: did this change mean to prohibit submitting scores with no _successful_ hit results, or just with no hit results whatsoever? Asking because this change is doing the former as-is, while what web _seems_ to be checking (from my rudimentary understanding of php) is the latter.

**Comment by peppy** [comment]
Have some commits in progress to fix the remaining issues.

**Comment by bdach** [comment]
One more rather minor point: I'd probably add `addFakeHit()` calls to `TestNoSubmissionOnResultsWithNoToken` and `TestNoSubmissionOnExitWithNoToken` in the submission test scene. The reason for that is, there are now two overlapping conditions which may prevent submission, and adding the fake hits would ensure that it is the "no token" part that is preventing submission, rather than the "no hit" part, avoiding potential false positives.

I can make that change, just wanted to confirm that it makes sense.

**Comment by peppy** [comment]
Sounds good

**Review by bdach — APPROVED** [review]

**Pull request merged**
