### PR TITLE
Bind Ctrl+R to Quick Retry

### PR DESCRIPTION
**Pull request by guzrdo**
Not sure if this was intentionally left out or just overlooked, but I noticed it didn't work in lazer and my muscle memory wants this in lazer so here it is.

### CODE REVIEW

**Comment by AlFasGD** [comment]
There already is a key binding for that using `~` this time. Honestly I think that it's better to leave it like that since it's easier and quicker than holding two keys.

**Comment by NickGuz** [comment]
Yeah I knew it was bound to tilde but in stable you could rebind that and still use ctrl+r, but I suppose it is a bit unnecessary.

**Comment by AlFasGD** [comment]
Instead, that must have been a bug in stable. Bindable functions are normally meant to only work when pressing the binded combination of buttons, excluding the default binding.

**Comment by peppy** [comment]
The real question is, did anyone use Ctrl+R? If not, I believe tilde is a better default.

**Comment by Lolihunter1337** [comment]
@peppy well i use it always instead of tilde

**Comment by Frontear** [comment]
I can't think of any reasons why someone would prefer `Ctrl + R` other than the fact that the combination may be intuitive. Regardless, most people have (1) grown accustomed to tilde, and (2) desire the simplicity of one key rather than a combination. So, the `~` (tidle) should remain default, and anyone who would prefer `Ctrl + R` can manually bind it later on.

**Comment by peppy** [comment]
Let's leave this as-is. Rationale: anyone who prefers Ctrl-R can re-bind it themselves.

**Pull request closed without merging**
