### PR TITLE
Correct DialogButton click animation

### PR DESCRIPTION
**Pull request by mcendu**
This PR is made to fix a possible bug in the click animation of `DialogButton`. In `PopupDialog` instances, after either of _OK_ or _Cancel_ is clicked, the dialog would (sometimes) also close. The close process seems to cause a `HoverLost` event to be fired alongside the expected `Click` event, causing the possibly incorrect behavior.
[Here is a demonstration of the original behavior.](https://github.com/ppy/osu/files/3840830/glitch.mkv.gz) Note how the cancel button behave when it is clicked.

### CODE REVIEW

**Comment by peppy** [comment]
Still reproduces in tests with your changes.

**Comment by mcendu** [comment]
> Still reproduces in tests with your changes.

How is the bug reproduced?

**Comment by peppy** [comment]
Run `TestSceneDialogButton`.

**Comment by peppy** [comment]
Please check and fix CI inspections.

**Comment by peppy** [comment]
Are you actually testing this? It seems to be getting more broken.

https://www.youtube.com/watch?v=s8Sx9GK6ROY

**Comment by EVAST9919** [comment]
Fixed via https://github.com/ppy/osu/pull/6825

**Comment by peppy** [comment]
Seems that way.

**Comment by mcendu** [comment]
This PR is intended to fix another bug, instead of #6822.

**Comment by peppy** [comment]
Feel free to reopen but please provide a hood explanation of what it’s fixing

**Pull request closed without merging**
