### PR TITLE
Remove mouse input from mania touch controls

### LINKED ISSUE #29378: osu!mania touch input shows up with "touch" setting disabled
### Type

Game behaviour

### Bug description

Using a laptop keyboard and DFG {SPACE] IOP keys, touchpad directly below those keys, wrist or palm sometimes clicks the touchpad. It would be expected for all touch inputs to be disabled with the touch option disabled, but for mania it is clearly not the case.

### Screenshots or videos

https://github.com/user-attachments/assets/20bcd3a2-287d-4e57-b743-9f19fee229ef

### Version

2024.731.0-lazer

### Logs

not working for some reason?
image

### PR DESCRIPTION
**Pull request by smoogipoo**
Resolves https://github.com/ppy/osu/issues/29378

I agree this is unnecessary.

### CODE REVIEW

**Comment by peppy** [comment]
I'm fine with giving this a try. The edge case would be a user with touch input that's being mapped to a mouse in windows (used to be a more common thing, but probably much less so these days as vendors want to make use of proper touch input that windows offers).

**Review by peppy — APPROVED** [review]

**Comment by bdach** [comment]
I don't normally advocate for toggles but we already have a toggle that this could be pulled under?

https://github.com/ppy/osu/blob/a71bc3a24ae1315673f3cb9dee8595aaa3202895/osu.Game/Overlays/Settings/Sections/Input/MouseSettings.cs#L78-L82

**Comment by smoogipoo** [comment]
Actually, that setting already works to disable this overlay. I'd be alright with that direction, depending on what @peppy says.

**Comment by peppy** [comment]
Honestly I say we just nuke it for now and see if a single person complains.

**Pull request merged**
