### PR TITLE
Fix volume overlay being blocked by other floating overlays

### LINKED ISSUE #2765: Only master volume can be changed while something else (e.g. notifications) has focus
While using the scroll wheel Master volume will change. When you hover over Effects or Music then that volume can be changed. But only when something else isn't opened, like notifications or music player.

### LINKED ISSUE #2898: While the notifications tab is open, the volume overlay still fades when hovered over

### PR DESCRIPTION
**Pull request by Joehuu**
Was part of #4447. Fixes #2765 & fixes #2898.

Changes depth of settings overlay. It now blocks music/login overlays if both are open instead of vise versa. Both are a reason it should be a `singleDisplaySideOverlays`.

It also changes load order, and I know there might be some lag (visual thing) but just putting this here.

---

### CODE REVIEW

**Comment by peppy** [comment]
I don't think this can exist in this load order – it means that a user will not be able to change the volume until everything above it has been loaded (in some extreme scenarios this can be 5-10 seconds).

**Comment by Joehuu** [comment]
Should I split `floatingOverlayContent` to `leftFloatingOverlayContent` and `rightFloatingOverlayContent`?

**Comment by peppy** [comment]
Does the resolve the load ordering? If not, we probably need to re-think the `loadComponentSingle...` method or use some kind of depth again.

**Review by peppy — APPROVED** [review]
works well

**Pull request merged**
