### PR TITLE
Option to disable beatmaps playing at the preview time in beatmap selection

### PR DESCRIPTION
**Pull request by GiantNuker**
Adds two toggles to settings, one to disable starting at the preview time when repeating a song, and one to disable preview time when selecting a new song.

By default starting from preview time when replaying is disabled.

### CODE REVIEW

**Comment by peppy** [comment]
Strong "no" from me in favour of not adding settings for every last thing. The preview / looping behaviour here is considered core game mechanics to me.

**Comment by Joehuu** [comment]
There's https://github.com/ppy/osu/issues/8918, closed though.

**Comment by GiantNuker** [comment]
Alright, I guess that makes sense. 

> In addition, I'd recommend searching issues (and opening them if not existing) before PRing changes like this, just to save effort.
I would've done it anyway just to use myself. Will search prs/issues before pring again though

**Comment by smoogipoo** [comment]
osu! is not a music player. The preview point is designed to get you right into the action and give you a taste of what to expect, which is imo crucial for enjoyment of a rhythm game.

Hard no from me too, sorry.

**Pull request closed without merging**
