### PR TITLE
Use greyscale instead of hue for the logo animation

### PR DESCRIPTION
**Pull request by jorolf**
- [x] Depends on https://github.com/ppy/osu-resources/pull/109

### CODE REVIEW

**Comment by peppy** [comment]
Any further documentation on the process here would be appreciated.

- what is this PR aiming to achieve?
- any comparison videos or methods you used to compare so we can objectively agree it's an improvement?

**Comment by bdach** [comment]
I've eyeballed it and the quality seems to have improved with less artifacts, at the cost of a lower number of colour levels available to work with (which leads to the animation looking a bit choppy in slow motion - but it plays too fast to notice with 100% speed, at least for me). An actual viewable comparison as part of the PR would be helpful however. Guess I can make one if need be.

**Comment by peppy** [comment]
Hmm, unfortunate about the frame rate, as one of the remaining goals was to increase it above 60fps.

**Comment by jorolf** [comment]
I couldn't increase the framerate anyway, the original mp4 only had 60 frames to work with. Making it greyscale also helped with finding all artifacts and applying some blur which helps a bit with the perceived framerate.

**Comment by jorolf** [comment]
I made a google drive folder with videos of the new, current and old animations:
https://drive.google.com/drive/folders/1IRQmlA7kFkmiHyghr9RVQiEgwUIiWzpy?usp=sharing
(I think the compression hit them really hard though, you might want to download them to compare them better)

**Comment by peppy** [comment]
In both new versions there's one frame which looks incorrect, right at the start of the animation:

**Comment by jorolf** [comment]
The video provided by flyte does have a pixel in that spot:
frame 1

However that dot should be grey instead of white

**Comment by peppy** [comment]
maybe we should omit / skip that frame since it feels out of place..

**Comment by jorolf** [comment]
That also includes the dot from the circle?

**Comment by peppy** [comment]
i mean it looks like the original video wasn't trimmed properly?

**Comment by jorolf** [comment]
I updated the google drive video to the current versions. I didn't exactly "remove" the frame but instead just removed the dots.

**Pull request merged**
