### PR TITLE
Add `CombinedGroupBadge`

### PR DESCRIPTION
**Pull request by stanriders**
Part of the https://github.com/ppy/osu/issues/22130

image

Not sure about the 2 badge case, @arflyte is this how it supposed to look?

### CODE REVIEW

**Comment by peppy** [comment]
@arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte @arflyte

**Comment by peppy** [comment]
@arflyte ????

**Comment by arflyte** [comment]
Wait I thought I replied to this. I think the design requires a revisit. What’s the general consensus of having it condensed into multiple dots?

It’s either just show the most important one, or that.

**Comment by peppy** [comment]
I still dislike having users with more than one badges in the first place, but if it is happening, it should be done in a consistent way and not require a hover to see what the badges mean. The dots feel too abstract and hard to initially understand for such an edge case. it's going to create a handful of like 20 users with some dots on their card that no one knows what means.

So either we show the full badges or stack them or something i dunno.

**Comment by arflyte** [comment]
Hmm true, I’ll try to figure a way to stack them. Let’s just show the most important one and probably hide the least important for now.

**Comment by stanriders** [comment]
As discussed here and by looking at the https://github.com/ppy/osu-design/discussions/1 it is obvious this is not the direction in which badges should be implemented

**Pull request closed without merging**
