### PR TITLE
Apply "classic" mod to all legacy scores

### LINKED ISSUE #5514: Replays are inaccurate
**Describe the bug:** Not sure how intended this is for now, but thought I'd at least mention it. Replays are currently very inaccurate, a replay might miss a slider or circle in lazer while that isn't happening in stable (or vice-versa, haven't seen that personally though). Besides that, replays can also just fail in lazer because of mismatches regarding how sliders are handled. 
An example for a missed note in lazer is the current top play of idke in [euphoria](https://osu.ppy.sh/beatmapsets/890438#osu/1861487). In lazer, the slider at around 1:50 will always be missed, whereas that doesn't happen in stable.

**osu!lazer version:** 5fa820cdd439c90e2f8a14c17ca138dace549e21

### PR DESCRIPTION
**Pull request by frenzibyte**
Should resolve #5514 

Not 100% sure about the way this is done, I was hoping legacy scores were separated to a `LegacyScoreInfo` class but it appears that such thing is not possible, so I've had to add it directly in the `ScoreInfo.Mods` getter instead.

### CODE REVIEW

**Comment by peppy** [comment]
Code-wise this seems fine, but probably needs further testing in terms of whether this provides correct/expected results. @frenzibyte did you happen to test with the replay in the linked issue?

I tested on an arbitrary score and the final accuracy and max combo with classic on had a larger deviance from stable than without. Of course, this could mean nothing.

**Review by peppy — DISMISSED** [review]
Tentatively think we should go forward with this and work out any kinks that may exist with classic mod itself.

**Comment by smoogipoo** [comment]
That sounds really wrong. Can you share the map/replay you tried with? I tested my original implementation across something like 10 scores from https://osu.ppy.sh/beatmapsets/743239#osu/1567435 and found them all to be more accurate.

The only edge case I know of is that sliders will award the final combo if you "miss" the tail, unlike stable. And we've decided to not fix that.

**Comment by peppy** [comment]
top score on https://osu.ppy.sh/beatmapsets/751894#osu/1582894


[Jakson playing Fractal Dreamers - Blue Haven (Gero) [Paradise].osr.zip](https://github.com/ppy/osu/files/6348978/Jakson.playing.Fractal.Dreamers.-.Blue.Haven.Gero.Paradise.osr.zip)

**Comment by frenzibyte** [comment]
> @frenzibyte did you happen to test with the replay in the linked issue?

Didn't notice there was a replay linked there, I've tested it ([web score link](https://osu.ppy.sh/scores/osu/2713366344)) and the results were:

| no classic | with classic |
|------------|--------------|
| CleanShot 2021-04-21 at 10 38 07 | CleanShot 2021-04-21 at 10 41 01 |

Improved a bit with classic mod, but not quite.

**Review by smoogipoo — DISMISSED** [review]

**Review by smoogipoo — APPROVED** [review]

**Comment by peppy** [comment]
@smoogipoo did you happen to take a look at the replay i linked above? curious what causes the different results.

**Comment by smoogipoo** [comment]
I haven't was about to make an issue linking to this thread for future tracking.

**Pull request merged**
