### PR TITLE
Fix skin version being incorrectly set to `1.0` when skin is missing `skin.ini`

### LINKED ISSUE #24939: Skin without skin.ini does not default to latest skin.ini verison
### Type

Cosmetic

### Bug description

**Description:**
In stable, a skin without a `skin.ini` file will default to the latest version, as [documented on the wiki](https://osu.ppy.sh/wiki/en/Skinning/skin.ini#latest). However, in lazer, a skin without a skin.ini file does not show this behaviour.

**Reproduction steps:**
1. Download [this skin](https://github.com/ppy/osu/files/12733048/ryuuta.zip) and open it in both stable and lazer. The skin only has one file, named `fruit-ryuuta.png`.
2. Play any osu!catch map.

**Expected behaviour**
Since the `fruit-ryuuta.png` should only work with skin version 2.3 and lower [as documented here], this sprite should not be used if the skin defaults to the latest version (which is version 2.7 as of posting this issue). As shown in the screenshots below, stable demonstrates this behaviour by ignoring the `fruit-ryuuta.png` file completely and replacing it with the default catcher.

**Actual behaviour**
It uses the `fruit-ryuuta.png` file as the catcher, also shown in the screenshots below

### Screenshots or videos

The skin as seen in lazer.
The skin as seen in lazer.

The skin as seen in stable.
The skin as seen in stable.

### Version

osu! 2023.924.1-lazer

### Logs

[updater.log](https://github.com/ppy/osu/files/12733054/updater.log)
[runtime.log](https://github.com/ppy/osu/files/12733055/runtime.log)
[performance.log](https://github.com/ppy/osu/files/12733056/performance.log)
[input.log](https://github.com/ppy/osu/files/12733057/input.log)
[database.log](https://github.com/ppy/osu/files/12733058/database.log)

### PR DESCRIPTION
**Pull request by peppy**
Closes https://github.com/ppy/osu/issues/24939.

### CODE REVIEW

**Comment by frenzibyte** [comment]
There's already a path where the version is returned as "latest" for skins with no `skin.ini`:

CleanShot 2023-09-27 at 11 44 21@2x

Since we're updating the underlying `SkinConfiguration` field instead (which I'm not against), the fallback value in the path above should probably be removed, and remove nullability of `LegacyVersion` while at it.

**Comment by peppy** [comment]
I considered that but am not too interested because all paths return nullable for these config values, and I don't want to refactor everything.

**Comment by frenzibyte** [comment]
Is it? Isn’t `LegacyVersion` 100% non-null with this PR now?

**Comment by peppy** [comment]
The field can be made non-null, sure. But it doesn't really help with the lookup paths.

**Comment by frenzibyte** [comment]
Sure, then at least keep a comment in the `GetConfig` path that the fallback shouldn’t exist and the field should be non-nullable etc., to clear up any potential confusion after this gets merged.

**Comment by peppy** [comment]
I don't feel confident adding a comment with those tests exists. Unless they don't exist for a reason I'd have to investigate what each means and then make a call on whether that direction is even feasible.

Let's leave this for another day. It's not important.

**Comment by frenzibyte** [comment]
Sure, I guess.

**Review by bdach — APPROVED** [review]

**Pull request merged**
