### PR TITLE
Make taiko classic mod emulate the classic "4:3" scroll speed

### PR DESCRIPTION
**Pull request by smoogipoo**
Should resolve https://github.com/ppy/osu/discussions/13047

| | stable | master | This PR |
| --- | --- | --- | ---|
| 4:3 | stable-4:3 | lazer-master-4:3 | lazer-4:3 |
| 16:9 | stable-16:9 | lazer-master-16:9 | lazer-16:9 |
| 5:4 | stable-5:4 | lazer-master-5:4 | lazer-5:4 |

Remaining differences are due to the hit target/`HitObjectContainer` being offset compared to stable.

I haven't taken the HD mod into account beyond removing the existing hackery which would would completely hide the hitobjects at 4:3 resolutions with this mod. I personally don't believe we really need to do this for the classic mod since it's meant more as a stop-gap measure to bring players into familiarity and can have a score/pp/prestige multiplier.

### CODE REVIEW

**Comment by peppy** [comment]
Going to merge this and wait for user feedback. Not really interested in looking into the details right now because this whole thing is a pretty subjective area.

**Comment by mouzedrift** [comment]
just to clarify in #13047 i'm also referring to the playfield height/size which still doesn't match stable (see comparison image).
comparison

**Comment by bdach** [comment]
The playfield size [was made to match at 16:9](https://github.com/ppy/osu/pull/14105).

**Comment by mouzedrift** [comment]
i've seen the PR but since smoogipoo said that this PR is *supposed* to resolve #13047 i would assume that 4:3 and other aspect ratios would match stable too since that's what the linked discussion is about.

**Pull request merged**
