### PR TITLE
Adjust default follow circle animations to feel nicer

### PR DESCRIPTION
**Pull request by peppy**
- [x] Depends on #19090 

Before:

https://user-images.githubusercontent.com/191335/179185413-6a1d4143-34d9-447f-8614-1578ace97eb8.mp4

After:

https://user-images.githubusercontent.com/191335/179185257-8fdd4c68-7bd1-4ce3-b010-bf3b457ed5ed.mp4

### CODE REVIEW

**Review by frenzibyte — DISMISSED** [review]
Feels better, but will wait for @smoogipoo's approval.

**Comment by goodtrailer** [comment]
I agree that it feels better when tracking is lost, but is this supposed to affect slider end animation as well? Personally, I think this animation feels really weird on slider ends.

**Comment by peppy** [comment]
> I agree that it feels better when tracking is lost, but is this supposed to affect slider end animation as well? Personally, I think this animation feels really weird on slider ends.

It isn't, that may be an oversight.

**Comment by peppy** [comment]
I've fixed this and adjusted the successful completion animation a touch.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
