### PR TITLE
Add "enter" hint to in-gameplay chatbox placeholder text

### LINKED ISSUE #29264: Add hint to press enter key for focusing in-gameplay chat
I've had to navigate through PRs to figure out that you can focus the chat by pressing <kbd>Enter</kbd>.

Right now the chat text box only shows "type message..." when unfocused, it should be "press enter to type message..." or something similar.

CleanShot 2024-08-03 at 06 50 15

### PR DESCRIPTION
**Pull request by kstefanowicz**
- Closes #29264

I don't know how to get to a multiplayer game in a debug build, so I was not able to confirm if this works.

### CODE REVIEW

**Comment by smoogipoo** [comment]
I'm not sure about:
1. The length of the placeholder in general. It feels too verbose but I'm not sure how to improve it.
2. The placeholder still saying "press enter [...]" while it already has focus.

Regarding the second from the above, I experimented with something like this:
```diff
diff --git a/osu.Game/Online/Chat/StandAloneChatDisplay.cs b/osu.Game/Online/Chat/StandAloneChatDisplay.cs
index 3a094cc074..e100b5fe5b 100644
--- a/osu.Game/Online/Chat/StandAloneChatDisplay.cs
+++ b/osu.Game/Online/Chat/StandAloneChatDisplay.cs
@@ -128,6 +128,9 @@ private void channelChanged(ValueChangedEvent<Channel> e)
 
         public partial class ChatTextBox : HistoryTextBox
         {
+            public Action Focus;
+            public Action FocusLost;
+
             protected override bool OnKeyDown(KeyDownEvent e)
             {
                 // Chat text boxes are generally used in places where they retain focus, but shouldn't block interaction with other
@@ -153,13 +156,17 @@ protected override void LoadComplete()
                 BackgroundFocused = new Color4(10, 10, 10, 255);
             }
 
+            protected override void OnFocus(FocusEvent e)
+            {
+                base.OnFocus(e);
+                Focus?.Invoke();
+            }
+
             protected override void OnFocusLost(FocusLostEvent e)
             {
                 base.OnFocusLost(e);
                 FocusLost?.Invoke();
             }
-
-            public Action FocusLost;
         }
 
         public partial class StandAloneDrawableChannel : DrawableChannel
diff --git a/osu.Game/Screens/OnlinePlay/Multiplayer/GameplayChatDisplay.cs b/osu.Game/Screens/OnlinePlay/Multiplayer/GameplayChatDisplay.cs
index 656071ad43..d1a73457e3 100644
--- a/osu.Game/Screens/OnlinePlay/Multiplayer/GameplayChatDisplay.cs
+++ b/osu.Game/Screens/OnlinePlay/Multiplayer/GameplayChatDisplay.cs
@@ -42,8 +42,13 @@ public GameplayChatDisplay(Room room)
 
             Background.Alpha = 0.2f;
 
-            TextBox.FocusLost = () => expandedFromTextBoxFocus.Value = false;
             TextBox.PlaceholderText = ChatStrings.InGameInputPlaceholder;
+            TextBox.Focus = () => TextBox.PlaceholderText = Resources.Localisation.Web.ChatStrings.InputPlaceholder;
+            TextBox.FocusLost = () =>
+            {
+                TextBox.PlaceholderText = ChatStrings.InGameInputPlaceholder;
+                expandedFromTextBoxFocus.Value = false;
+            };
         }
 
         protected override bool OnHover(HoverEvent e) => true; // use UI mouse cursor.
```

https://github.com/user-attachments/assets/ad2904f1-3f89-4062-bbe5-bbc247f1be8f

But I'm still not too sure about it. Need a secondary opinion.

**Comment by frenzibyte** [comment]
"press enter to chat..." could work better as a shorter placeholder.

**Comment by kstefanowicz** [comment]
> 1. The length of the placeholder in general. It feels too verbose but I'm not sure how to improve it.

"press enter to chat..." is definitely better, I will change that now

> 2. The placeholder still saying "press enter [...]" while it already has focus.

That implementation makes sense, agreed. I believe that multiplayer in-game is the only place where the chatbox _isn't_ in focus at all times, so the Focus events may be able to be applied to just `GameplayChatDisplay` and not the parent `StandAloneChatDisplay`

**Comment by peppy** [comment]
@kstefanowicz are you going to apply the proposed change to the placeholder text when focused?

**Comment by kstefanowicz** [comment]
Placeholder text hover change has been applied. Thank you for your patience.

**Review by smoogipoo — DISMISSED** [review]

**Review by smoogipoo — APPROVED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
