### PR TITLE
Add abort gameplay button to TestSceneMatchStartControl

### PR DESCRIPTION
**Pull request by smoogipoo**
Prereqs:
- [ ] https://github.com/ppy/osu/pull/17702

Resolves https://github.com/ppy/osu/pull/17604#issuecomment-1088217023

Probably the best that can be done?

### CODE REVIEW

**Comment by bdach** [comment]
This only works if you ready up in the test. If you don't ready up and just start the countdown, at the end of it all buttons will be disabled and nothing can be done to enable it again:

https://user-images.githubusercontent.com/20418176/161842843-4ed078f4-e9f7-4968-84cf-617825305717.mp4

**Comment by bdach** [comment]
This only works if you ready up in the test. If you don't ready up and just start the countdown, at the end of it all buttons will be disabled and nothing can be done to enable it again:

https://user-images.githubusercontent.com/20418176/161842843-4ed078f4-e9f7-4968-84cf-617825305717.mp4

**Comment by smoogipoo** [comment]
Will need to think about this one a bit more... The issue at face value is a difference between `TestMultiplayerClient` and the server in that countdowns shouldn't start gameplay if no users are ready (the server is doing this correctly).

But fixing that is not enough since `MatchStartControl` binds to `CurrentPlaylistItem` to check if the buttons should be enabled, which is a whole other can of worms. I think I'll look into removing `CurrentPlaylistItem` prior to this PR being merged.

**Comment by smoogipoo** [comment]
Closing as I don't think this is required anymore after https://github.com/ppy/osu/pull/17802

**Pull request closed without merging**
