### PR TITLE
Dialog popup interface

### PR DESCRIPTION
**Pull request by Feodor0090**
Adds interface for popups to allow displaying custom drawables via `DialogOverlay`.

`ClickableContainer` was chosen as base button type to allow exposing both `OsuButton`s and `DialogButton`s.

### CODE REVIEW

**Comment by peppy** [comment]
Could you please provide more context as to what this would be used for?

**Comment by Feodor0090** [comment]
> Could you please provide more context as to what this would be used for?

I'm trying to make a form for comment reporting. The best place to display it without implementing dublicates of DialogOverlay is DialogOverlay itself, so i wanted to extend it a little to allow pushing custom dialogs, not only `PopupDialog`.

**Comment by Feodor0090** [comment]
Initially i wanted to use popover too, but it's designed to be shown near an object. Frenzibyte recommended me to show it in the center of the screen (like web does) to gain more attention from user, and i agree that it will feel better.

If you are against this change, i will try to figure something with popover instead, or locally in CommentsContainer.

**Comment by smoogipoo** [comment]
I don't think the report dialog needs to be shown as a fullscreen overlay as you had it in the screenshots (and matching osu-web). Popover will work fine imo.

**Comment by Feodor0090** [comment]
Closing for now.

**Pull request closed without merging**
