### PR TITLE
Block input to ruleset container on fail

### LINKED ISSUE #3603: After failed map key overlay still counts key clicks
when you fail a map key overlay still counts key clicks but not updates key state(clicked/not clicked)
checked for mania and osu!standard
this doesn't occur when you pause the game

logs:
[database.log](https://github.com/ppy/osu/files/2489268/database.log)
[debug.log](https://github.com/ppy/osu/files/2489269/debug.log)
[network.log](https://github.com/ppy/osu/files/2489270/network.log)
[performance.log](https://github.com/ppy/osu/files/2489271/performance.log)
[runtime.log](https://github.com/ppy/osu/files/2489272/runtime.log)

### PR DESCRIPTION
**Pull request by plankp**
Fix #3603

### CODE REVIEW

**Comment by peppy** [comment]
Have you tried fixing this by instead making the fail overlay handle (and block) all events? basically add an override for `OnEvent` instead of the currently limited individual blocking overrides (see https://github.com/ppy/osu/blob/master/osu.Game/Screens/Play/GameplayMenuOverlay.cs#L157).

**Comment by plankp** [comment]
I couldn't get it to work(, but then it might have been because I was trying the wrong thing?)

**Comment by smoogipoo** [comment]
Yikes, it seems like `PassThroughInputManager`s bypass the whole `Handle()` stuff when they sync the input in their `Update()`.

This should like partly a framework bug, but `Handle()` should be the way to go here imo.

**Comment by smoogipoo** [comment]
See: https://github.com/ppy/osu-framework/issues/1966

**Comment by iiSaLMaN** [comment]
Can be closed as it's outdated

**Pull request closed without merging**
