### PR TITLE
Fix skin element "PlayerFlag" responding to clicks/hovers

### LINKED ISSUE #25529: The PlayerFlag skinning element is a button
### Type

Game behaviour

### Bug description

The PlayerFlag skinning element is a button that takes you to that player's country ranking.

### Screenshots or videos

https://github.com/ppy/osu/assets/67008763/04bc4290-9594-474c-9ead-4332e70f292a

### Version

2023.1114.1

### Logs

[legacy-ipc.log](https://github.com/ppy/osu/files/13428486/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/13428487/network.log)
[performance.log](https://github.com/ppy/osu/files/13428488/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13428489/runtime.log)
[updater.log](https://github.com/ppy/osu/files/13428490/updater.log)
[database.log](https://github.com/ppy/osu/files/13428491/database.log)
[input.log](https://github.com/ppy/osu/files/13428492/input.log)

### PR DESCRIPTION
**Pull request by yesseruser**
Fixes #25529.

Added BaseUpdateableFlag and BaseDrawableFlag classes that don't have tooltips or click functionality.
The UpdateableFlag class was renamed to ClickableUpdateableFlag.

### CODE REVIEW

**Comment by frenzibyte** [comment]
That's a lot of over-engineering. Why not just introduce a bool parameter on `UpdateableFlag` defining whether it's "interactive", similar to `UpdateableAvatar`? Then use that to decide whether to use `HoverSounds` or `HoverClickSounds` and whether to call "show profile overlay".

**Review by frenzibyte — CHANGES_REQUESTED** [review]
As above.

**Comment by peppy** [comment]
Why not just disable subtree input on the skinnable component and avoid *all* complexity?

**Comment by frenzibyte** [comment]
That sounds fine as well.

**Comment by yesseruser** [comment]
> Why not just disable subtree input on the skinnable component and avoid *all* complexity?

I'll rebase the branch and do that.

**Review by peppy — APPROVED** [review]

**Pull request merged**
