### PR TITLE
Update star rating in song select statistics when changing mods/mod settings

### PR DESCRIPTION
**Pull request by huoyaoyuan**
Thanks to #7303 , the implementation becomes very simple.
HardRock:
image
DoubleTime:
image

But, I'm afraid we are on the wrong way of beatmap details processing. There should be a centralized "Playable state of beatmap", in contrast of "original beatmap", and all the displaying should simply read from the playable state.

Also, there needs a redesign of beatmap info UI.

### CODE REVIEW

**Comment by peppy** [comment]
At very least, the colouring needs to change for SR. Orange on red is not a good look.

**Comment by huoyaoyuan** [comment]
image
Current implementation is not flexible enough. EZ makes the blue into green.

**Comment by EVAST9919** [comment]
No longer required after https://github.com/ppy/osu/pull/9637 merge

**Comment by huoyaoyuan** [comment]
Sure. But I wish to be mentioned when there's something going to replace my work, and I can take part in the discussion.

**Comment by peppy** [comment]
does this have functionality not in master still in terms of display?

**Comment by smoogipoo** [comment]
It doesn't.

@huoyaoyuan sorry about that - I forgot this PR existed.

**Pull request closed without merging**
