### PR TITLE
Use Multicore JIT

### PR DESCRIPTION
**Pull request by UselessToucan**
Since we don't use .NET Native or NGEN I guess we might want to use [Multicore JIT](https://blogs.msdn.microsoft.com/dotnet/2012/10/18/an-easy-solution-for-improving-app-launch-performance/) for the time being.

### CODE REVIEW

**Comment by smoogipoo** [comment]
1. This doesn't work with mono:
```
Unhandled Exception:
System.TypeLoadException: Could not resolve type with token 01000058 (from typeref, class/assembly System.Runtime.ProfileOptimization, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
  at osu.Desktop.Program.Main (System.String[] args) [0x00001] in <85d454740f6d44a8a463faf8be4156f0>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeLoadException: Could not resolve type with token 01000058 (from typeref, class/assembly System.Runtime.ProfileOptimization, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089)
  at osu.Desktop.Program.Main (System.String[] args) [0x00001] in <85d454740f6d44a8a463faf8be4156f0>:0 
```

It will need specific mono flags similar to `BackgroundStackTraceCollector`.

2. Environment.CurrentDirectory is actually going to return... well, the current directory. Not the application directory. This means that if there's a shortcut, the "CurrentDirectory" is the directory in which the shortcut exists, e.g. on the desktop.

We don't want this, instead we want the startup location for the application (`AppDomain.CurrentDomain.BaseDirectory` I think is what we want).

3. How does this work with debugging? Is the JITter able to infer that methods have changed?

**Comment by UselessToucan** [comment]
1. The only dev environment I have now is Windows 10 + .NET Framework. We may just not to use it on Mono for now, or I can try to setup Ubuntu+Mono environment.
2. Thank you for this note. I will check and fix it.
3. I googled about Multicore JIT before creating this PR and I did not see anything related to code editing while debugging.

**Comment by smoogipoo** [comment]
1 . It's fine to not use it on mono for now.

3 . I mean just general code editing. How does this handle it? It's just a cache after all, what's the process of invalidation for this?

Additionally, @peppy had some concerns that multicore JIT originally had some issues, so we're gonna need to test this thoroughly to make sure no random crashes occur.

**Review by smoogipoo — DISMISSED** [review]
This seems to be working okay.

**Comment by peppy** [comment]
Before merging this, it needs to be tested with an actual squirrel deploy to ensure compatibility (when an update is pushed, specifically).

**Comment by smoogipoo** [comment]
Just gonna run this CI a few more times in the meanwhile so I can see if it helps CI times at all :p

**Comment by peppy** [comment]
Tested with deployment, works well.

**Review by peppy — APPROVED** [review]

**Pull request merged**
