### PR TITLE
Add max combo and accuracy tooltips on leaderboards

### PR DESCRIPTION
**Pull request by Joehuu**
Problems:
The tooltip box is not the correct placement or size.
problem

### CODE REVIEW

**Comment by DrabWeb** [comment]
`ScoreComponentLabel` could pretty easily be adjusted to have the correct bounding box, if you want to do it in this PR.

**Comment by Joehuu** [comment]
Don't think I can do it. The combo and accuracy value lengths vary and need more than just changing the size of the box. Should be the same behavior as `BeatmapInfoWedge`.
beatmapinfowedge

**Comment by DrabWeb** [comment]
Override `Contains` to return true if the icon background (dark blue box) or the text contain the position.

E.g.
`public override bool Contains(Vector2 screenSpacePos) => iconBg.Contains(screenSpacePos) || text.Contains(screenSpacePos);`

**Comment by Joehuu** [comment]
When I copied that code, the tooltips don't show between the icon and value.
tooltips

**Comment by peppy** [comment]
Have you tried just making the labels autosize as they probably should be?

**Comment by DrabWeb** [comment]
Just did this in a different PR as it required a lot more changes than just adding a tooltip.

**Pull request closed without merging**
