### PR TITLE
Don't show epilepsy warning when storyboards are disabled

### PR DESCRIPTION
**Pull request by peppy**
I have more thoughts on this warning in general (which will likely see it removed or moved in the future) but this seems like a quick QOL fix for now.

As mentioned in https://github.com/ppy/osu/discussions/22861.

### CODE REVIEW

**Comment by sw1tchbl4d3r** [comment]
As a note, some taiko maps (and possibly other modes?) use the epilepsy warning not just for storyboards, but also for rapidly flashing/toggling kiai.
Examples are [this map](https://osu.ppy.sh/beatmapsets/1637599#taiko/3342421) and [this more gimmicky map](https://osu.ppy.sh/beatmapsets/1723138#taiko/3521672), which have neither storyboard nor video, but an epilepsy warning.
Not sure how that would be handled, if it's deemed subtle enough, etc.

**Comment by bdach** [comment]
I wanted to add testing here, but it's kind of painful given the timing-dependent nature of this behaviour. Best I can do is probably

```diff
diff --git a/osu.Game.Tests/Visual/Gameplay/TestScenePlayerLoader.cs b/osu.Game.Tests/Visual/Gameplay/TestScenePlayerLoader.cs
index 0c7991e0ca..dbd1ce1f6e 100644
--- a/osu.Game.Tests/Visual/Gameplay/TestScenePlayerLoader.cs
+++ b/osu.Game.Tests/Visual/Gameplay/TestScenePlayerLoader.cs
@@ -337,6 +337,23 @@ public void TestEpilepsyWarning(bool warning)
             restoreVolumes();
         }
 
+        [Test]
+        public void TestEpilepsyWarningWithDisabledStoryboard()
+        {
+            saveVolumes();
+            setFullVolume();
+
+            AddStep("disable storyboards", () => config.SetValue(OsuSetting.ShowStoryboard, false));
+            AddStep("change epilepsy warning", () => epilepsyWarning = true);
+            AddStep("load dummy beatmap", () => resetPlayer(false));
+
+            AddUntilStep("wait for current", () => loader.IsCurrentScreen());
+
+            AddUntilStep("epilepsy warning absent", () => getWarning() == null);
+
+            restoreVolumes();
+        }
+
         [Test]
         public void TestEpilepsyWarningEarlyExit()
         {
@@ -454,7 +471,7 @@ private void clickNotification()
             AddStep("click notification", () => notification.TriggerClick());
         }
 
-        private EpilepsyWarning getWarning() => loader.ChildrenOfType<EpilepsyWarning>().SingleOrDefault();
+        private EpilepsyWarning getWarning() => loader.ChildrenOfType<EpilepsyWarning>().SingleOrDefault(w => w.IsAlive);
 
         private partial class TestPlayerLoader : PlayerLoader
         {
diff --git a/osu.Game/Screens/Play/PlayerLoader.cs b/osu.Game/Screens/Play/PlayerLoader.cs
index be4229ade9..30ae5ee5aa 100644
--- a/osu.Game/Screens/Play/PlayerLoader.cs
+++ b/osu.Game/Screens/Play/PlayerLoader.cs
@@ -489,6 +489,7 @@ private void pushWhenLoaded()
                 {
                     // This goes hand-in-hand with the restoration of low pass filter in contentOut().
                     this.TransformBindableTo(volumeAdjustment, 0, CONTENT_OUT_DURATION, Easing.OutCubic);
+                    epilepsyWarning?.Expire();
                 }
 
                 pushSequence.Schedule(() =>
```

Other than that, this looks fine, just need opinion on the above test and/or confirmation if we still want this in light of the [comment above](https://github.com/ppy/osu/pull/22868#issuecomment-1481957101).

**Comment by peppy** [comment]
Test looks fine I think.

**Review by bdach — APPROVED** [review]
I've applied the test. Looks fine to me, but I didn't get an answer if we want to proceed with this still in light of concerns pointed out above, so I'll leave the final go/no-go decision to you.

**Pull request merged**
