### PR TITLE
Add support for traversing playlist items using next/previous bindings

### PR DESCRIPTION
**Pull request by peppy**
Addresses https://github.com/ppy/osu/discussions/18061.

### CODE REVIEW

**Comment by bdach** [comment]
This mostly works, except for when there's overflow, because you can use keyboard buttons to select an item that isn't actually visible on the scroll:

https://user-images.githubusercontent.com/20418176/166668541-2d2b6e8f-d6db-47cc-a682-b808dc8b1a89.mp4

Fixing is rather easy, though. Should go something like this:

```diff
diff --git a/osu.Game/Screens/OnlinePlay/DrawableRoomPlaylist.cs b/osu.Game/Screens/OnlinePlay/DrawableRoomPlaylist.cs
index d1b21ca1b0..30ae6b62c8 100644
--- a/osu.Game/Screens/OnlinePlay/DrawableRoomPlaylist.cs
+++ b/osu.Game/Screens/OnlinePlay/DrawableRoomPlaylist.cs
@@ -2,6 +2,7 @@
 // See the LICENCE file in the repository root for full licence text.
 
 using System;
+using System.Diagnostics;
 using System.Linq;
 using osu.Framework.Bindables;
 using osu.Framework.Graphics;
@@ -173,6 +174,21 @@ public bool ShowItemOwners
 
         protected virtual DrawableRoomPlaylistItem CreateDrawablePlaylistItem(PlaylistItem item) => new DrawableRoomPlaylistItem(item);
 
+        protected override void LoadComplete()
+        {
+            base.LoadComplete();
+
+            SelectedItem.BindValueChanged(_ => scrollToSelection());
+        }
+
+        private void scrollToSelection()
+        {
+            if (SelectedItem.Value == null) return;
+
+            Debug.Assert(ItemMap.TryGetValue(SelectedItem.Value, out var drawableItem));
+            ScrollContainer.ScrollIntoView(drawableItem);
+        }
+
         #region Key selection logic (shared with BeatmapCarousel and RoomsContainer)
 
         public bool OnPressed(KeyBindingPressEvent<GlobalAction> e)
```

Can push in and add tests if you like.

**Comment by peppy** [comment]
Oops. Looks good.

**Comment by bdach** [comment]
So apparently my change has unintended side effects...

https://user-images.githubusercontent.com/20418176/166675316-044c617a-3387-4c7c-87b9-eb35278bbb58.mp4

Note how the item scrolls into view ever so slightly. I'm guessing that I should look into fixing this...

**Comment by peppy** [comment]
You could probably add a `FinishTransforms(false)` on the `ScrollContainer` and call it a day. In theory.

I don't think it's to offensive and can be fixed later if preferred.

**Comment by bdach** [comment]
I've pushed what I have. Unfortunately `FinishTransforms(false)` doesn't fix it. I also tried to specify `animated: false` on the `ScrollIntoView()` call and it doesn't fix it either so I gave up.

Also had to add some schedules and extra bits because multiplayer tests were failing. If any of it is questionable I'll look into this again, but I'd like to walk away from this for now since dealing with it took more of my time than I would have liked.

**Comment by frenzibyte** [comment]
I've had a look on the scroll issue since it can get bad once reaching the created room (the added item would bounce and then come back to its correct position).

The reason why this is happening is because the `ScrollIntoView` call could be operating on a non-loaded drawable item (since `RearrangableListContainer` loads its items asynchronously), therefore trying to compute its position which is invalid at this point, since it hasn't received a parent yet.

This can be worked around by subscribing to `OnLoadComplete`, which is a bit silly, but about the only way I can see through this:
```diff
diff --git a/osu.Game/Screens/OnlinePlay/DrawableRoomPlaylist.cs b/osu.Game/Screens/OnlinePlay/DrawableRoomPlaylist.cs
index 840fc48613..b9b201919e 100644
--- a/osu.Game/Screens/OnlinePlay/DrawableRoomPlaylist.cs
+++ b/osu.Game/Screens/OnlinePlay/DrawableRoomPlaylist.cs
@@ -190,7 +190,10 @@ private void scrollToSelection()
             if (SelectedItem.Value == null || !ItemMap.TryGetValue(SelectedItem.Value, out var drawableItem))
                 return;
 
-            ScrollContainer.ScrollIntoView(drawableItem);
+            if (!drawableItem.IsLoaded)
+                drawableItem.OnLoadComplete += _ => ScrollContainer.ScrollIntoView(drawableItem);
+            else
+                ScrollContainer.ScrollIntoView(drawableItem);
         }
 
         #region Key selection logic (shared with BeatmapCarousel and RoomsContainer)
```

In addition, I've pushed some minor changes along with handling against `AllowSelection = false` playlists. Looks all good otherwise.

**Comment by peppy** [comment]
Should we be looking at a fix for `ScrollIntoView` at the framework end to fix this scenario?

**Comment by frenzibyte** [comment]
That's another thought I had, but I can only imagine that "fix" being to schedule the `ScrollIntoView` operation internally on the target drawable, something like:
```csharp
public void ScrollIntoView(Drawable target, bool animated)
{
    if (!target.IsLoaded)
        target.Schedule(() => ScrollIntoView(target, animated));
        
    // logic
}
```

Not sure if that's something you're fine with, but I recall we have discussed about this specific pattern long ago, and I'm not sure what the conclusion was.

**Comment by peppy** [comment]
If using scheduling, I'm not sure I'd want to schedule on the loading drawable. Probably some implementation using `Scheduler.AddOnce` across scroll operations, potentially storing the next target to a field until the operation can be achieved.

**Comment by frenzibyte** [comment]
Have pushed the workaround as permitted, everything looks good. @bdach would like your final review on this.

**Review by frenzibyte — APPROVED** [review]

**Review by bdach — APPROVED** [review]

**Pull request merged**
