### PR TITLE
Add "classic" mod setting for tracking slider ball with any action

### PR DESCRIPTION
**Pull request by frenzibyte**
Resolves a discrepancy with "classic" mod found in https://github.com/ppy/osu/issues/12532#issuecomment-826481278.

osu!lazer has special logic for limiting tracking slider ball only to the button/action that hit the slider head until it's the only action held, osu!stable on other hand doesn't care about that and lets any action held track the slider ball, from testing.

For compatibility with osu!stable's behaviour, a new setting for the "classic" mod has been added for allowing the slider ball to be tracked with any action, regardless of which hit the slider head first.

### CODE REVIEW

**Comment by peppy** [comment]
I'm not sure this needs to be a setting, but it does give us a way to expose to the user what classic mod is doing I guess?

**Comment by frenzibyte** [comment]
Well, I've went with consistency here, all other adjustments have a corresponding setting for them so /shrug.

**Comment by smoogipoo** [comment]
This hasn't been tested. Stable does have the limiting, but it seems like it only cares about the last frame or something like that - I need to look into the logic more. You can see how this change fails by holding one key down _before_ the slider and then pressing the slider with the other key and releasing it - tracking should stop.

**Comment by smoogipoo** [comment]
Also:
1. This should probably be fixed for the base SliderBall implementation.
2. `TestSceneSliderInput` should be used to test this - it would've immediately discovered the issue I pointed above.

**Comment by frenzibyte** [comment]
> This hasn't been tested. Stable does have the limiting, but it seems like it only cares about the last frame or something like that - I need to look into the logic more. You can see how this change fails by holding one key down _before_ the slider and then pressing the slider with the other key and releasing it - tracking should stop.

Ah, I see. Couldn't really tell since my only method of checking how stable works is arbitrarily testing cases on a regular osu!stable installation.

I will need osu!stable's code to match osu!lazer's implementation of it, or should I leave this to you instead?

**Comment by frenzibyte** [comment]
Closing in favour of the correct #12581

**Pull request closed without merging**
