### PR TITLE
Add combo break sound

### LINKED ISSUE #5102: Miss sound not playing
I'm not hearing the miss sound at all when I miss a note, not sure if a skin related issue or an issue invoking the sound

### PR DESCRIPTION
**Pull request by JackLee9355**
As present in stable. 
Depends on https://github.com/ppy/osu-resources/pull/60
Resolves https://github.com/ppy/osu/issues/5102

### CODE REVIEW

**Review by miterosan — DISMISSED** [review]
LGTM

**Comment by peppy** [comment]
Rather than pollute `Player` (we are trying to keep it as clean as possible), I'd consider making a class called `ComboSoundGenerator` or `ComboEffects` or similar. It should go inside the `LocalSkinOverride` to allow for beatmap skinnability (which your current implementation does not).

This could be expanded in the future to add combo sounds and possibly combo burst visual effects.

**Review by peppy — CHANGES_REQUESTED** [review]
As proposed

**Comment by welsar55** [comment]
Is this close to what you invisioned? Because this seems super odd to me. Currently this class is only used for loading assets. I will deal with the failed test if it is what you wanted.

**Comment by peppy** [comment]
Oh no, you've moved stuff into the `LocalSkinOverrideContainer`. That class should not be touched. By "inside" I meant you would make a new container and nest it inside the override container inside player (alongside `DrawableRuleset`).

```csharp
public class ComboSoundGenerator : CompositeDrawable
{
	public ComboSoundGenerator(ScoreProcessor processor)
	{
		...
	}
}
```

and in `Player`

**Comment by welsar55** [comment]
Yep I that makes way for sense 🤦‍♂ . Sorry for being an idiot.

**Comment by welsar55** [comment]
Also need osu-Resources build 627 but thats not on nuget yet.

**Comment by peppy** [comment]
I'm going to commit some supplementary changes to this one to fix up skin support (your method is fine but will not handle skin changes).

**Review by peppy — DISMISSED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
