### PR TITLE
Fix JuiceStream velocity calculation

### LINKED ISSUE #28534: Osu!Catch sliders overexaggerate the amount of drops in it, while editing in the editor
### Type

Game behaviour

### Bug description

Just trying to map in the lazer editor.
It occurs pretty frequently (maybe always) when adjusting a slider shape. I think it sometimes fixes itself, but I haven't experimented with that much. I'm pretty sure it's not beatmap specific.

### Screenshots or videos

https://github.com/ppy/osu/assets/104220939/a3eaefd6-1350-4b1f-92d6-2de8a81f1d2c

### Version

2024.521.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/15910863/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by smoogipoo**
- Closes https://github.com/ppy/osu/issues/28534 (for the majority case, see https://github.com/ppy/osu/pull/25725#issuecomment-2196563006)

This should match the calculations already present / recently made to `Slider`. Not sure why they weren't done for catch.

Spreadsheet here: https://docs.google.com/spreadsheets/d/1NA5JK947QmdUMv7Lnv56WXxCAuq-IOYsGWZ83GXAWB0/edit#gid=791502473 ([run]https://github.com/ppy/osu/actions/runs/7163776038)

Todo in this PR:
- [x] Add at least one test case beatmap
- [x] Validate results of spreadsheet above

### CODE REVIEW

**Comment by bdach** [comment]
So I generated expected conversions for all of the changes that changed SR with nomod: [conversions.zip](https://github.com/ppy/osu/files/13636323/conversions.zip)

And I have bad news. Some of the SR changes are fixes, and some are regression. The detailed breakdown is thus:

| Test | master | this PR | change |
| :- | :-: | :-: | :-: |
| Test("3091364") | ✔️ | ❌ | **regression** |
| Test("556909") | ❌ | ✔️ | fixed |
| Test("828828") | ❌ | ❌ | _still broken_ |
| Test("933615") | ❌ | ✔️ | fixed |
| Test("991733") | ❌ | ❌ | _still broken_ |
| Test("1009022") | ✔️ | ❌ | **regression** |
| Test("1392244") | ❌ | ❌ | still broken |
| Test("1514076") | ❌ | ❌ | still broken |
| Test("1653504") | ✔️ | ❌ | **regression** |
| Test("1654305") | ❌ | ✔️ | fixed |
| Test("1875197") | ✔️ | ❌ | **regression** |
| Test("1962756") | ❌ | ✔️ | fixed |
| Test("2041893") | ❌ | ❌ | _still broken_ |
| Test("2042351") | ❌ | ✔️ | fixed |
| Test("2077578") | ❌ | ❌ | _still broken_ |
| Test("2165315") | ❌ | ✔️ | fixed |
| Test("2186317") | ✔️ | ❌ | **regression** |
| Test("2195985") | ✔️ | ❌ | **regression** |
| Test("2256396") | ❌ | ✔️ | fixed |
| Test("2339801") | ✔️ | ❌ | **regression** |
| Test("2389697") | ❌ | ✔️ | fixed |
| Test("2638311") | ❌ | ✔️ | fixed |
| Test("2789383") | ❌ | ✔️ | fixed |
| Test("3335242") | ❌ | ❌ | _still broken_ |
| Test("3614534") | ❌ | ❌ | _still broken_ |
| Test("3620288") | ❌ | ❌ | _still broken_ |
| Test("3642792") | ❌ | ✔️ | fixed |
| Test("3652994") | ❌ | ❌ | _still broken_ |
| Test("3922638") | ❌ | ❌ | _still broken_ |
| Test("3942600") | ❌ | ✔️ | fixed |
| Test("3944076") | ❌ | ❌ | _still broken_ |
| Test("4044925") | ❌ | ❌ | _still broken_ |
| Test("4087902") | ✔️ | ❌ | | Test | master | this PR | change |
| :- | :-: | :-: | :-: |
| Test("3091364") | ✔️ | ❌ | regression |
| Test("556909") | ❌ | ✔️ | fixed |
| Test("828828") | ❌ | ❌ | still broken |
| Test("933615") | ❌ | ✔️ | fixed |
| Test("991733") | ❌ | ❌ | still broken |
| Test("1009022") | ✔️ | ❌ | regression |
| Test("1392244") | ❌ | ❌ | still broken |
| Test("1514076") | ❌ | ❌ | still broken |
| Test("1653504") | ✔️ | ❌ | regression |
| Test("1654305") | ❌ | ✔️ | fixed |
| Test("1875197") | ✔️ | ❌ | regression |
| Test("1962756") | ❌ | ✔️ | fixed |
| Test("2041893") | ❌ | ❌ | still broken |
| Test("2042351") | ❌ | ✔️ | fixed |
| Test("2077578") | ❌ | ❌ | still broken |
| Test("2165315") | ❌ | ✔️ | fixed |
| Test("2186317") | ✔️ | ❌ | regression |
| Test("2195985") | ✔️ | ❌ | regression |
| Test("2256396") | ❌ | ✔️ | fixed |
| Test("2339801") | ✔️ | ❌ | regression |
| Test("2389697") | ❌ | ✔️ | fixed |
| Test("2638311") | ❌ | ✔️ | fixed |
| Test("2789383") | ❌ | ✔️ | fixed |
| Test("3335242") | ❌ | ❌ | still broken |
| Test("3614534") | ❌ | ❌ | still broken |
| Test("3620288") | ❌ | ❌ | still broken |
| Test("3642792") | ❌ | ✔️ | fixed |
| Test("3652994") | ❌ | ❌ | still broken |
| Test("3922638") | ❌ | ❌ | still broken |
| Test("3942600") | ❌ | ✔️ | fixed |
| Test("3944076") | ❌ | ❌ | still broken |
| Test("4044925") | ❌ | ❌ | still broken |
| Test("4087902") | ✔️ | ❌ | **regression** |

Note that "still broken" may also mean "broken even further". I'm pretty sure I saw at least one case of this already.

Detailed test result reports:
[before.txt](https://github.com/ppy/osu/files/13636347/before.txt)
[after.txt](https://github.com/ppy/osu/files/13636346/after.txt)

I will attempt to investigate later, but I need to afk for a bit and just wanted to drop this here in the mean time...

**Comment by smoogipoo** [comment]
That's very helpful, thanks! If you get to it before me, it'd be good to test those with https://github.com/ppy/osu/pull/25726 merged on top of these changes, since they touch related code.

**Comment by bdach** [comment]
Updated summary:

| Test | master | #25725 | #25725 + #25726 | change |
| :- | :-: | :-: | :-: |
| Test("3091364") | ✔️ | ❌ | ❌ | **regression** |
| Test("556909") | ❌ | ✔️ | ✔️ | fixed |
| Test("828828") | ❌ | ❌ | ❌ | *still broken* |
| Test("933615") | ❌ | ✔️ | ✔️ | fixed |
| Test("991733") | ❌ | ❌ | ❌ | *still broken* |
| Test("1009022") | ✔️ | ❌ | ❌ | **regression** |
| Test("1392244") | ❌ | ❌ | ✔️ | fixed |
| Test("1514076") | ❌ | ❌ | ❌ | *still broken* |
| Test("1653504") | ✔️ | ❌ | ❌ | **regression** |
| Test("1654305") | ❌ | ✔️ | ✔️ | fixed |
| Test("1875197") | ✔️ | ❌ | ❌ | **regression** |
| Test("1962756") | ❌ | ✔️ | ✔️ | fixed |
| Test("2041893") | ❌ | ❌ | ❌ | *still broken* |
| Test("2042351") | ❌ | ✔️ | ✔️ | fixed |
| Test("2077578") | ❌ | ❌ | ❌ | *still broken* |
| Test("2165315") | ❌ | ✔️ | ✔️ | fixed |
| Test("2186317") | ✔️ | ❌ | ❌ | **regression** |
| Test("2195985") | ✔️ | ❌ | ❌ | **regression** |
| Test("2256396") | ❌ | ✔️ | ✔️ | fixed |
| Test("2339801") | ✔️ | ❌ | ❌ | **regression** |
| Test("2389697") | ❌ | ✔️ | ✔️ | fixed |
| Test("2638311") | ❌ | ✔️ | ✔️ | fixed |
| Test("2789383") | ❌ | ✔️ | ✔️ | fixed |
| Test("3335242") | ❌ | ❌ | ❌ | *still broken* |
| Test("3614534") | ❌ | ❌ | ❌ | *still broken* |
| Test("3620288") | ❌ | ❌ | ❌ | *still broken* |
| Test("3642792") | ❌ | ✔️ | ✔️ | fixed |
| Test("3652994") | ❌ | ❌ | ❌ | *still broken* |
| Test("3922638") | ❌ | ❌ | ✔️ | fixed |
| Test("3942600") | ❌ | ✔️ | ✔️ | fixed |
| Test("3944076") | ❌ | ❌ | ❌ | *still broken* |
| Test("4044925") | ❌ | ❌ | ✔️ | fixed |
| Test("4087902") | ✔️ | ❌ | ❌ | **regression** |

So it seems that things get _a little_ better, but not completely quite there yet.

Updated test report: [25725+25726.txt](https://github.com/ppy/osu/files/13639797/25725%2B25726.txt)

**Comment by bdach** [comment]
More details:

| Test | master | #25725 | #25726 | #25725 + #25726 | change |
| :- | :-: | :-: | :-: | :-: | :-: |
| Test("3091364") | ✔️ | ❌ | ✔️ | ❌ | **broken by #25725** |
| Test("556909") | ❌ | ✔️ | ❌ | ✔️ | fixed by #25725 |
| Test("828828") | ❌ | ❌ | ✔️ | ❌ | **broken by #25725** |
| Test("933615") | ❌ | ✔️ | ❌ | ✔️ | fixed by #25725 |
| Test("991733") | ❌ | ❌ | ❌ | ❌ | *still broken* |
| Test("1009022") | ✔️ | ❌ | ✔️ | ❌ | **broken by #25725** |
| Test("1392244") | ❌ | ❌ | ❌ | ✔️ | fixed by combination |
| Test("1514076") | ❌ | ❌ | ❌ | ❌ | *still broken* |
| Test("1653504") | ✔️ | ❌ | ✔️ | ❌ | **broken by #25725** |
| Test("1654305") | ❌ | ✔️ | ❌ | ✔️ | fixed by #25725 |
| Test("1875197") | ✔️ | ❌ | ✔️ | ❌ | **broken by #25725** |
| Test("1962756") | ❌ | ✔️ | ❌ | ✔️ | fixed by #25725 |
| Test("2041893") | ❌ | ❌ | ❌ | ❌ | *still broken* |
| Test("2042351") | ❌ | ✔️ | ❌ | ✔️ | fixed by #25725 |
| Test("2077578") | ❌ | ❌ | ❌ | ❌ | *still broken* |
| Test("2165315") | ❌ | ✔️ | ❌ | ✔️ | fixed by #25725 |
| Test("2186317") | ✔️ | ❌ | ✔️ | ❌ | **broken by #25725** |
| Test("2195985") | ✔️ | ❌ | ✔️ | ❌ | **broken by #25725** |
| Test("2256396") | ❌ | ✔️ | ❌ | ✔️ | fixed by #25725 |
| Test("2339801") | ✔️ | ❌ | ✔️ | ❌ | **broken by #25725** |
| Test("2389697") | ❌ | ✔️ | ❌ | ✔️ | fixed by #25725 |
| Test("2638311") | ❌ | ✔️ | ❌ | ✔️ | fixed by #25725 |
| Test("2789383") | ❌ | ✔️ | ❌ | ✔️ | fixed by #25725 |
| Test("3335242") | ❌ | ❌ | ✔️ | ❌ | **fixed by #25726 and then broken by #25725** |
| Test("3614534") | ❌ | ❌ | ❌ | ❌ | *still broken* |
| Test("3620288") | ❌ | ❌ | ❌ | ❌ | *still broken* |
| Test("3642792") | ❌ | ✔️ | ❌ | ✔️ | fixed by #25725 |
| Test("3652994") | ❌ | ❌ | ❌ | ❌ | *still broken* |
| Test("3922638") | ❌ | ❌ | ❌ | ✔️ | fixed by both pulls |
| Test("3942600") | ❌ | ✔️ | ❌ | ✔️ | fixed by #25725 |
| Test("3944076") | ❌ | ❌ | ❌ | ❌ | *still broken* |
| Test("4044925") | ❌ | ❌ | ❌ | ✔️ | fixed by both pulls |
| Test("4087902") | ✔️ | ❌ | ✔️ | ❌ | **broken by #25725** |

The 3335242 is case is especially maddening, only breaking down when both pulls are involved.

Either way, these results seem to indicate that the other pull seems to be a much less volatile improvement, as in it appears to both not introduce any star rating changes and lead to a net increase in test case passes, so I'll get that one in first, and see if I can get to any conclusions on this one later...

**Comment by bdach** [comment]
Looking into the failing cases more, every single one manifests by a last fruit in a juice stream moving temporally.

- In most cases, the last fruit is later by 1ms, and thus causes a hyperdash that was not there previously.
- In one case (3091364), the last fruit is earlier by ~0.000002ms, and becomes not-hyper.

You would ask, "why didn't this manifest in osu! if this PR brings the two in line?", and, well...

https://github.com/ppy/osu/blob/568bd85533f87321f497ddf07b16050828f63d50/osu.Game.Rulesets.Osu.Tests/OsuBeatmapConversionTest.cs#L87-L91

The test doesn't care about the object times being precisely equal. It just needs to be within 2ms. In fact, when the failing maps are plugged into the osu! conversion tests (as they are all converts), they would also fail conversion if the leniency on end time was turned off.

I'm not sure what to do with this information further yet, but there you go...

**Comment by smoogipoo** [comment]
Yeah... Unfortunately I don't see a way to get perfect conversion unless we use the exact calculations that osu!stable does (i.e. not using `double`s).

Personally, just from a code PoV, both the new changes look like they should match osu!stable just because the osu! implementation is geared to do so (even if it doesn't exactly due to `double` timing).

As for how to make further progress, I'm thinking we should only consider the position of hitobjects and not consider what are effectively "pixeljumps". I wouldn't be opposed to reverting https://github.com/ppy/osu/pull/25685/commits/6f73d78bc90a2ec78f1eb3137363db40ece6af2a either.

**Comment by bdach** [comment]
From the standpoint of considering catch gameplay mechanics or balance or whatever, I don't feel qualified to answer that question.

From a code quality / programming standpoint, to some degree I'd be in favour of merging this simply because it brings osu! and catch in line. If it just broke maps, I would have more reservations about it, but the fact that it breaks some and fixes some has me thinking we're probably never getting 100% accuracy of reproduction of stable calculations anyway.

**Comment by peppy** [comment]
I guess one way or another we should make a call on this. I'd be curious to see what a "float calculation" solution would look like (as in how bad it will look).

**Comment by bdach** [comment]
I'm actually going to make a shot-call on this now to get it in, and that is because this fixes a majority case of an _editor_ issue, namely https://github.com/ppy/osu/issues/28534.

That bug is caused by `TickDistanceMultiplier` not being updated correctly. On master, it is expected that that value _in catch specifically_ will be 1 pre-osu-file-format-v8 and equal to slider velocity post-osu-file-format-v8. This value not being updated correctly by the editor was causing ticks to generate using the wrong density.

This branch inverts the value, such that `TickDistanceMultiplier` is 1 over slider velocity pre-osu-file-format-v8 and 1 post-osu-file-format-v8. This means that this issue essentially disappears for post-v8 beatmaps, since they are loaded with the multiplier equal to 1 and will continue to use that multiplier undisturbed.

Note that there is still a 1% issue - if an _either osu! or catch_ beatmap that is v8 or earlier is edited and saved, tick spacing will inadvertently _change_ upon save, because of it being derived entirely based on osu! beatmap version, which is hardcoded in the encoder to be v128. That said this is a 1% issue and I'm not sure we need to act upon it until necessary.

See https://github.com/ppy/osu/pull/25725/commits/deeb2e99a2711ab9e9ef7bbd06249fb1723eab01 for testament to all of the above (test will fail when cherry-picked onto master, and passes here - hopefully on CI, too).

**Review by bdach — APPROVED** [review]

**Pull request merged**
