### PR TITLE
Adjust slider snaking and hitcircle fading to match stable

### PR DESCRIPTION
**Pull request by peppy**
PRing for further testing and confirmation. Values adjusted to match `osu-stable` 1:1 (in theory). If anyone feels like testing frame-by-frame video vs stable (or even just playing to see if it feels more correct) that would be appreciated.

### CODE REVIEW

**Review by smoogipoo — APPROVED** [review]

**Comment by l3lackShark** [comment]
Looks like everything's fine. https://www.youtube.com/watch?v=8thFYHb_YE4

**Comment by peppy** [comment]
@l3lackShark thanks for that. Can you also test with a lower AR beatmap (like disco prince) to make it easier to see potential discrepanciesn in the slider snaking?

**Comment by l3lackShark** [comment]
Sure!

**Comment by l3lackShark** [comment]
@peppy It's 1:1, checked on 0.1x speed. https://www.youtube.com/watch?v=aO0lDL1Kd4E

**Comment by peppy** [comment]
Thanks a lot!

**Comment by Aergwyn** [comment]
Going through both frame by frame there seems to be a 1 frame difference sometimes. Lazer seems to be a frame faster. Although stable seems to not snake at all for a frame every now and then so I'm not sure if Lazer ist just smoother with this.

**Comment by l3lackShark** [comment]
@Aergwyn Yeah I think that lazer just has more ticks on the actual animation. Plus there might be an error on my side. Please check both videos and confirm.

**Comment by l3lackShark** [comment]
If really needed, then I can record the footage in 240fps.

**Comment by Aergwyn** [comment]
Interesting would be a comparison to current master actually. The `ApproachCircle` appears later than on stable and I'm not sure if the change on `TimeFadeIn` could be responsible for this.

**Comment by l3lackShark** [comment]
@Aergwyn Original comparison was to current master or am I missing something?

**Comment by Aergwyn** [comment]
I meant this change compared to master to know if the approach circles changed.

**Comment by EVAST9919** [comment]
> @Aergwyn Original comparison was to current master or am I missing something?

He meant before and after this pr has been merged

**Comment by l3lackShark** [comment]
@Aergwyn The one on the right is the pre-merged branch. https://www.youtube.com/watch?v=wFukS3zq6_0

**Pull request merged**
