### PR TITLE
Revert forced cloning of ControlPointInfo

### LINKED ISSUE #11491: Reduce overhead of cloning beatmaps
https://github.com/ppy/osu/pull/11423 Added deep cloning of `ControlPointInfo` to `Beatmap.Clone()`. `BeatmapConverter` clones beatmaps, which could result in difficulty calculation then causing many clones when there are many mod combinations.

### PR DESCRIPTION
**Pull request by peppy**
Probagbly best to leave this how it was for the time being, given that
it can inadvertently cause performance issues in diffcalc and other
areas that may not be immediately visible.

This reverts commit 3c3e860dbc34d37855b79786a1abb754af1667e8.

Closes https://github.com/ppy/osu/issues/11491.

### CODE REVIEW

**Comment by bdach** [comment]
So I checked under debug by breakpointing, and if mod combinations in diffcalc are the main performance concern, then this change doesn't entirely alleviate it, because difficulty calculation calls `GetPlayableBeatmap()` anyway:

https://github.com/ppy/osu/blob/778efc5108e55dee8f2d9c1ac2f91c2e8b5c5537/osu.Game/Rulesets/Difficulty/DifficultyCalculator.cs#L38-L48

I guess with this change at least the clones aren't fired on conversion, which saves half of the calls. In the case of mods, this could probably be improved further by checking if any of the mods is `IApplicableToBeatmap`, but that still doesn't do much for the editor, which would have to defensively clone to prevent pollution of the working beatmap cache with unsaved control point changes.

I'm fine with the change on principle but not approving just yet to discuss the above.

**Comment by smoogipoo** [comment]
Beatmap conversion is actually done for each mod combination to get to a clean slate. I was hoping this could be done only for each case where it's required, similar to the way beatmap difficulty is handled. And even then, there's nothing stopping someone from currently doing something like:
```csharp
public class ModTest : Mod, IApplicableToBeatmap
{
    public void ApplyToBeatmap(IBeatmap beatmap)
    {
        beatmap.BeatmapInfo.BaseDifficulty.CircleSize = 5;
    }
}
```
And breaking everything, as the guard is only done for `IApplicableToDifficulty`.

This is all to say that the above model could be followed - make a mod `IApplicableToControlPoints` for rulesets and have the editor clone it all the time by itself, but I just want to point out that it's still quite unsafe.

**Comment by peppy** [comment]
So the temporary action is to move the copy into `Editor.cs` itself?

**Comment by smoogipoo** [comment]
I'd be fine with that.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
