### PR TITLE
Fix `SliderPath.Version` bindings not being correctly cleaned up on path changes

### LINKED ISSUE #19864: Reversing a slider multiplies bindings
### Type

Performance

### Bug description

I made a fairly large slider with multiple perfect curve type segments and reversed it a few hundred times with Ctrl+G and I noticed the game because extremely sluggish when moving around the slider or the first anchor of the slider. I checked the bindings on the `version` bindable and found it had a lot more bindings than before reversing the slider a bunch of times. I suspect this is the cause of the lag. I also tried flipping the slider a few hundred times but that did not cause any lag

### Screenshots or videos

image

### Version

4ef8e00a78f9801c41a7cfc889a82d06a6129852

### Logs

[runtime.log](https://github.com/ppy/osu/files/9385708/runtime.log)

### PR DESCRIPTION
**Pull request by peppy**
Closes https://github.com/ppy/osu/issues/19864.

Ouch. Again.

### CODE REVIEW

**Comment by smoogipoo** [comment]
I'm so confused how this is not immediately crashing. Am I missing something? It looks like the list is being modified during the foreach?

**Comment by peppy** [comment]
I'm honestly... not sure.

It does make me wonder if we should make some changes to `IContainer` to better avoid this situation? Like renaming `RemoveAll` to `RemoveAllWithoutDisposing` and adding `RemoveAndDisposeAll` which calls `RemoveAndDisposeImmediately` (naming unsure).

**Comment by smoogipoo** [comment]
I think this is just a failing of the custom o!f enumerator that's never throwing exceptions... https://github.com/ppy/osu-framework/blob/0894ea15a0b54c5f6fea478aa45f20356f68bbdb/osu.Framework/Graphics/Containers/Container.cs#L472-L495

This PR should be using a `.ToArray()`.

**Comment by peppy** [comment]
Tracking larger concern at https://github.com/ppy/osu-framework/issues/5378

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
