### PR TITLE
Bump android TargetFrameworkVersion

### PR DESCRIPTION
**Pull request by Morilli**
Necessary after #5241.

### CODE REVIEW

**Comment by peppy** [comment]
Can you explain where the necessity comes from? I'm not doubting you, but I was able to submit to the play store, compile for two devices and emulators as-is.

**Comment by Morilli** [comment]
I'm judging this from the error message I'm getting:
``The TargetFrameworkVersion (27) must not be lower than targetSdkVersion (28). You should either, increase the `$(TargetFrameworkVersion)` of your project. Or decrease the `android:targetSdkVersion` in your `AndroidManifest.xml` to correct this issue.``
And from this reference statement at https://docs.microsoft.com/de-de/xamarin/android/app-fundamentals/android-api-levels?tabs=windows:
image

**Comment by TheComputerGuy96** [comment]
> Can you explain where the necessity comes from? I'm not doubting you, but I was able to submit to the play store, compile for two devices and emulators as-is.

I bet you have turned up caching to 11 😅

But seriously, have you done "Clean osu.Android" before building? If yes, then maybe there are cache files somewhere else

**Comment by peppy** [comment]
My build was on a fresh checkout. I've tried again since and it's still looking fine. But the above documentation looks correct, thanks.

**Pull request merged**
