### PR TITLE
Add a filter checkbox on Multiplayer screens

### PR DESCRIPTION
**Pull request by Naeferith**
The framed element is concerned

Check Box
_- flyte's design -_

This is how the element is reacting on the visual test  : Check Box

### CODE REVIEW

**Comment by peppy** [comment]
Did you try deriving from OsuCheckBox instead of duplicating most of the code? I think you should be able to.

**Comment by Naeferith** [comment]
I'll try to do so. Am I authorised to modify OsuCheckBox then ? (mostly to add font/colour setter)

**Comment by peppy** [comment]
Sure. keep in mind (as i said) the multiplayer design isn't final so i can't guarantee this design of checkbox will still be required, but it's still good practice :).

**Comment by peppy** [comment]
Closing for the time being as it looks like we are standardising checkboxes across the game to use a singular design. Keep the branch around in case that decision changes!

**Pull request closed without merging**
