### PR TITLE
Skip the pause cooldown when in intro / break time

### LINKED ISSUE #31124: can't pause immediately after unpausing when in intro/break
### Type

Game behaviour

### Bug description

when you unpause in the intro or break you have a 1 second-ish delay before you can pause again. this is especially annoying when its the end of a break and you can't pause before gameplay continues.

### Screenshots or videos

_No response_

### Version

idk, as long as i can remember

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18137560/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by peppy**
Had a quick look at adding test coverage in `TestScenePause` but the setup to get into either of these states seems a bit annoying..

Closes https://github.com/ppy/osu/issues/31124.

### CODE REVIEW

**Comment by bdach** [comment]
Change seems ok in empirical testing but I would like to have some automated here as well. What would you say to the following?:

```diff
diff --git a/osu.Game.Tests/Visual/Gameplay/TestScenePause.cs b/osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
index 6aa2c4e40d..7855c138ab 100644
--- a/osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
+++ b/osu.Game.Tests/Visual/Gameplay/TestScenePause.cs
@@ -12,6 +12,7 @@
 using osu.Framework.Logging;
 using osu.Framework.Screens;
 using osu.Framework.Testing;
+using osu.Game.Beatmaps;
 using osu.Game.Configuration;
 using osu.Game.Graphics.Containers;
 using osu.Game.Graphics.Cursor;
@@ -19,6 +20,7 @@
 using osu.Game.Rulesets.UI;
 using osu.Game.Screens.Play;
 using osu.Game.Skinning;
+using osu.Game.Storyboards;
 using osuTK;
 using osuTK.Input;
 
@@ -28,6 +30,12 @@ public partial class TestScenePause : OsuPlayerTestScene
     {
         protected new PausePlayer Player => (PausePlayer)base.Player;
 
+        protected override WorkingBeatmap CreateWorkingBeatmap(IBeatmap beatmap, Storyboard storyboard = null)
+        {
+            beatmap.AudioLeadIn = 4000;
+            return base.CreateWorkingBeatmap(beatmap, storyboard);
+        }
+
         private readonly Container content;
 
         protected override Container<Drawable> Content => content;
@@ -202,6 +210,7 @@ public void TestUserPauseWhenPauseNotAllowed()
         [Test]
         public void TestUserPauseDuringCooldownTooSoon()
         {
+            AddStep("seek to gameplay", () => Player.GameplayClockContainer.Seek(0));
             AddStep("move cursor outside", () => InputManager.MoveMouseTo(Player.ScreenSpaceDrawQuad.TopLeft - new Vector2(10)));
 
             pauseAndConfirm();
@@ -213,9 +222,23 @@ public void TestUserPauseDuringCooldownTooSoon()
             confirmNotExited();
         }
 
+        [Test]
+        public void TestUserPauseDuringIntroSkipsCooldown()
+        {
+            AddStep("seek before gameplay", () => Player.GameplayClockContainer.Seek(-5000));
+            AddStep("move cursor outside", () => InputManager.MoveMouseTo(Player.ScreenSpaceDrawQuad.TopLeft - new Vector2(10)));
+
+            pauseAndConfirm();
+
+            resume();
+            pauseViaBackAction();
+            confirmPaused();
+        }
+
         [Test]
         public void TestQuickExitDuringCooldownTooSoon()
         {
+            AddStep("seek to gameplay", () => Player.GameplayClockContainer.Seek(0));
             AddStep("move cursor outside", () => InputManager.MoveMouseTo(Player.ScreenSpaceDrawQuad.TopLeft - new Vector2(10)));
 
             pauseAndConfirm();

```

(If you happen to run test browser and notice `TestQuickExitDuringCooldownTooSoon` failing, that happens on master as well, and I'm choosing to ignore it for the time being :see_no_evil:)

**Comment by peppy** [comment]
Sure that works for me.

**Review by bdach — DISMISSED** [review]

**Comment by bdach** [comment]
Aaaaand the other test randomly starts failing because github runners are made of loose straw and surrounding tree sticks and apparently the audio track can skip 300ms in a frame or something making all of this pointless. That said I don't think my test changes specifically would break that.

Stick a `[FlakyTest]` on it and call it a day or what?

**Comment by frenzibyte** [comment]
`FlakyTest` for now and demote to ignored if failure persists IMO.

**Comment by peppy** [comment]
time to ignore the test? 😅

**Review by bdach — APPROVED** [review]

**Pull request merged**
