### PR TITLE
Fix ruleset shaders not being able to reference framework parts

### LINKED ISSUE #23116: `RulesetShaderManager` fails to retrieve shaders bundled with the ruleset
### Type

Other

### Bug description

Most likely introduced with https://github.com/ppy/osu/pull/23034.
Easiest way to recreate: in `TestSceneRulesetDependencies` in `TestRetrieveShader` change `LoadRaw` strings to a single `Dependencies.Get<ShaderManager>().Load("TestVertex", "TestFragment");` - it will fail, but as far as my understanding goes - it should not.

Ruleset example: https://github.com/EVAST9919/lazer-swing
Drawable in question: https://github.com/EVAST9919/lazer-swing/blob/master/osu.Game.Rulesets.Swing/Objects/Drawables/Pieces/PathSliderBody.cs

### Screenshots or videos

_No response_

### Version

master

### Logs

[runtime.log](https://github.com/ppy/osu/files/11138778/runtime.log)

### PR DESCRIPTION
**Pull request by EVAST9919**
Closes https://github.com/ppy/osu/issues/23116
Full explanation [here](https://github.com/ppy/osu/issues/23116#issuecomment-1494853209).

### CODE REVIEW

**Review by bdach — CHANGES_REQUESTED** [review]
as above

**Comment by bdach** [comment]
Actually as it turns out reverting the commit I mentioned above is insufficient. This PR still breaks the previous fix, shaders are recomputed every time gameplay is entered. And that in turn is because the raw lookups are no longer failing, so the fallback shader manager is never even queried for the shaders that already have been preloaded...

Needs to be rethought entirely. Goals are:

- have ruleset shaders be able to include framework-internal parts
- but also not have rulesets load shaders on every gameplay enter

**Comment by peppy** [comment]
Yeah, was gonna say. This isn't going to work great.

I think we *could* make this work with an osu-side-change but at this point it may be best to re-think the structure in general? Maybe add some nullable to the mix?

**Comment by bdach** [comment]
I'm not sure what adding nullable would do here. Even assuming `LoadRaw()` returns `null` instead of throwing, what changes? The lookup of each shader part still must fallback to the parent shader manager, at which point we're right where we started. And not letting consumers mix custom and framework parts isn't an option, it must work or else we may not permit shaders at all.

Maybe our lookup order is just wrong. Trying parent manager first and only then trying to compile anything if nothing is found would fix this. Not sure if it would have any other unintended consequences, though.

**Comment by EVAST9919** [comment]
Another thing to consider - ruleset shaders recompilation.
Something like `ShaderManager.AddStore' would be the best option imo, so it can search through all the available stores, not only main one. Game-wide caching is still there and ability to mix framework/ruleset shaders too.

**Comment by bdach** [comment]
> Another thing to consider - ruleset shaders recompilation.

Can you elaborate? I don't understand what that is supposed to mean.

**Comment by EVAST9919** [comment]
> Can you elaborate? I don't understand what that is supposed to mean.

`RuseletShaderManager` is being created each time we enter the gameplay. Even if we solve the issue of referencing the framework parts - caching won't work for ruleset-specific shaders. So we need to avoid creating new `RulesetShaderManager` as a whole and somehow cache ruleset shaders in the game's main `ShaderManager`, Which my theoretical approach described above should solve.

**Comment by EVAST9919** [comment]
Superseded by https://github.com/ppy/osu/pull/23201

**Pull request closed without merging**
