### PR TITLE
Rewrite BreakOverlay to work with rewinding

### PR DESCRIPTION
**Pull request by peppy**
No longer relies on Schedule calls (could not be rewound).
Also no longer sucks.

- [x] ppy/osu-framework#1437 first.

### CODE REVIEW

**Review by smoogipoo — CHANGES_REQUESTED** [review]
As commented below...

**Comment by smoogipoo** [comment]
Did you test this with the `2s, 2s` and `0.5s, 0.7s, 1s, 2s` testcases in TestCaseBreakOverlay, and within `Player`? Neither of those seem to be working correctly.

**Comment by peppy** [comment]
Yep, all of these tested!

You need to merge transform fixes first. The high prio one breaking everything game-wide

**Comment by smoogipoo** [comment]
This is without any sort of rewinding though. I mentioned those because they're broken.

**Comment by smoogipoo** [comment]
lgtm.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
