### PR TITLE
Add 'trackfollowcircle' to settings

### PR DESCRIPTION
**Pull request by LO-oE**
Adds the ability to enable and disable the TrackFollowCircle feature in the ruleset settings.
Shotcut_00_00_25_217
on
Shotcut_00_00_15_850
off

### CODE REVIEW

**Comment by peppy** [comment]
As mentioned elsewhere, I don't think this is the correct direction to go. I don't want to clutter the settings up with these (likely) per-skin decisions.

In addition, we're not yet sure if the moving initial circle tracking is even a good idea from a gameplay perspective. I think if anyone we probably were leaning towards turning it off (as it only affects outwards snaking?)

**Comment by Feodor0090** [comment]
This already exists, isn't it?

изображение

**Comment by LO-oE** [comment]
Okay, thanks for the quick reply. I didn't realize this change also affected the actual hit area of the object.
And it's true that too many options would clutter the settings eventually, but giving the player an option to control this behavior would defenitely be nice, as most skins use transparency to some degree and it might be confusing to players.

**Comment by LO-oE** [comment]
> This already exists, isn't it?
> 
> изображение

Yes, but only for the classic mod and not in the actual lazer nomod gameplay.

**Comment by mk56-spn** [comment]
> > This already exists, isn't it?
> > изображение
> 
> Yes, but only for the classic mod and not in the actual lazer nomod gameplay.

you can just disable everything except for that setting then i think?, that should be equivalent

**Pull request closed without merging**
