### PR TITLE
Ignore short spinners for Relax mod

### PR DESCRIPTION
**Pull request by PercyDan54**

### CODE REVIEW

**Review by frenzibyte — DISMISSED** [review]
I think this is fine? not sure, osu!stable seems to hold regardless of the required spins from what I've seen on https://osu.ppy.sh/beatmapsets/132#osu/296.

**Comment by PercyDan54** [comment]
> I think this is fine? not sure, osu!stable seems to hold regardless of the required spins from what I've seen on https://osu.ppy.sh/beatmapsets/132#osu/296.

Does stable even simulate keypresses?
I use https://osu.ppy.sh/b/1901200 to test and Auto in stable even fails this map.

**Comment by PercyDan54** [comment]
> @PercyDan54 Please provide a clear and proper explanation for why this change is being proposed, as the opening post is blank and your comment links a random map with no real context.

It's just I thought about this when playing that random map . It doesn't actually cause problems with that map but we did the same change to Autoplay so I think it's fine to apply this to Relax

**Comment by bdach** [comment]
What you gave is not a complete explanation, so I'll try:

As far as I can tell, the purpose of this change to not automatically hold down the mouse button in relax for spinners that are too short to actually require spinning (as they will automatically complete on their own anyway). An example of this is the map [linked by you above](https://github.com/ppy/osu/pull/16856#issuecomment-1036971774).

Is my understanding correct?

**Comment by PercyDan54** [comment]
> What you gave is not a complete explanation, so I'll try:
> 
> As far as I can tell, the purpose of this change to not automatically hold down the mouse button in relax for spinners that are too short to actually require spinning (as they will automatically complete on their own anyway). An example of this is the map [linked by you above](https://github.com/ppy/osu/pull/16856#issuecomment-1036971774).
> 
> Is my understanding correct?

Yes. The change makes Relax not holding down the button if the spinner doesn't require any spin

**Review by smoogipoo — APPROVED** [review]
Seems reasonable to me

**Pull request merged**
