### PR TITLE
Avoid drawing segments of cursor trail near current cursor position

### LINKED ISSUE #14317: Legacy cursor trail shouldn't render the segment in the very middle
Smooth cursor trail doesn't render the segment in the very middle on stable but does on lazer. I have not checked how disjointed trail acts.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/11320483/129487644-0960dd25-9e5f-4aa6-a8da-b764abe447df.mp4

https://user-images.githubusercontent.com/11320483/129487671-7e9f73ad-08e6-4af6-af10-2a635232ad4d.mp4

[skin used (gdrive link)](https://drive.google.com/file/d/1MSEU7AiOjFIisJM74lDsxEx_hVgmrU1A/view?usp=sharing)

**osu!lazer version:** 

2021.815.0-lazer

master is at f49c9673ccf415b46d8e14f46fb2c35ab2f86e02 (*copied wrong rev before, wrong git log was open)

### PR DESCRIPTION
**Pull request by LittleEndu**
Closes https://github.com/ppy/osu/issues/14317

This PR avoids drawing legacy* cursor trail segments that are near the current cursor position. ~~As drawing those segments looks really weird when the trail is big, the fix is done in `CursorTrail` instead of `LegacyCursorTrail` as the issue title would suggest, because I think all future cursor trails would benefit from this.~~

Trail in this PR:

https://user-images.githubusercontent.com/11320483/129617810-4e8df244-51da-4af1-9c35-943da2cd56ee.mp4

Trail in release 2021.815.0-lazer:

https://user-images.githubusercontent.com/11320483/129617834-d8fde5bb-a18e-4fb5-8834-5bfbac7affc4.mp4

### CODE REVIEW

**Comment by bdach** [comment]
I'm not sure I agree with the premise here. The bottom trail looks more correct to me (due no gap between the cursor "plus" and the trail). So I'm not sure this behaviour should be applied universally as done here, rather than being legacy skin only.

**Comment by smoogipoo** [comment]
Yeah, I'm not sure on this either. But it does seem like stable does it on purpose.

**Comment by peppy** [comment]
This was 100% added to make the default skin look good/correct on stable, without custom skins in mind. @LittleEndu are you ballparking the distance here based on visual comparison with stable?

**Comment by LittleEndu** [comment]
I'm not sure what distance you are referring to but yes, I haven't actually measured anything, this is all just ballparked.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
