### PR TITLE
Implement EditorMenuBar inside a test case

### LINKED ISSUE #1181: Implement menu bar
To be used in the editor, reference:
image

### PR DESCRIPTION
**Pull request by smoogipoo**
Prereqs:
- [x] https://github.com/ppy/osu-framework/pull/1001

Closes #1181

Haven't implemented all the menus (because they'll change), but there's something there  ¯\_(ツ)_/¯

### CODE REVIEW

**Comment by peppy** [comment]
removing milestone (already present in issue)

**Comment by smoogipooo** [comment]
Oops I forgot I created that - added to PR description.

**Comment by peppy** [comment]
@smoogipooo shall we get this merged in today?

**Comment by smoogipooo** [comment]
Sounds good

**Review by peppy — APPROVED** [review]

**Pull request merged**
