### PR TITLE
Use framework extension method for FromHex

### LINKED ISSUE #8143: OsuColour hex code parsing can be removed
It can be removed upon the merging of https://github.com/ppy/osu-framework/pull/3332.

### PR DESCRIPTION
**Pull request by peppy**
Closes #8143

### CODE REVIEW

**Comment by iiSaLMaN** [comment]
Should be closing https://github.com/ppy/osu/issues/8143

**Comment by smoogipoo** [comment]
We should consider making this an extension method on Color4 instead. Using `Color4Extensions` everywhere is ugly.

**Comment by smoogipoo** [comment]
Turns out you can't have non-instanced extension methods... Let's go with this for now.

**Review by smoogipoo — APPROVED** [review]

**Comment by swoolcock** [comment]
As a reminder, we will need to move away from osuTK `Color4` eventually.

**Pull request merged**
