### PR TITLE
Check realm file can be written to before attempting further initialisation

### LINKED ISSUE #28018: No beatmaps found after Vulkan related crash
### Type

Other

### Bug description

I was testing out the new experimental renderers and was running into crashes similar to #22960. In my case, the game usually crashes after a differing number of beatmap restarts rather than whenever I started a beatmap.

I tried updating my graphics card drivers to see if that would fix the crashing. After updating the driver, the game crashed but my screen had flickering stripes instead of just freezing as it did before the driver update. I opened the game and my beatmap library is gone. My library consisted of imports from stable, files downloaded in client, and files downloaded and opened into lazer.

The first-time setup allows me to import maps from stable but I'm not sure if there's a way to rescan the beatmaps in the lazer files. I obviously can download the beatmaps again, but I'm not sure if that would clobber any of the lazer replays.

### Screenshots or videos

osu_2024-04-27_22-15-23

### Version

2024.412.1-lazer

### Logs

[compressed-logs.zip](https://github.com/ppy/osu/files/15140843/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by peppy**
Rather than creating a "corrupt" realm file in such cases, the game will now refuse to start. This behaviour is usually what we want. In most cases a second click on the game will start it successfully (the previous instance's file handles are still doing stuff, or windows defender is being silly).

Closes https://github.com/ppy/osu/issues/28018.

### CODE REVIEW

**Comment by peppy** [comment]
I figured tests may have issue with this (seems to only happen on windows). Will investigate further.

**Comment by bdach** [comment]
Windows issue doesn't look fixed.

The interesting part of the exception traces is this:

```
    at Microsoft.Win32.SafeHandles.SafeFileHandle.CreateFile(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String fullPath, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.Strategies.OSFileStreamStrategy..ctor(String path, FileMode mode, FileAccess access, FileShare share, FileOptions options, Int64 preallocationSize, Nullable`1 unixCreateMode)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at osu.Framework.Platform.FlushingStream..ctor(String path, FileMode mode, FileAccess access)
   at osu.Framework.Platform.NativeStorage.GetStream(String path, FileAccess access, FileMode mode)
   at osu.Game.IO.WrappedStorage.GetStream(String path, FileAccess access, FileMode mode) in D:\a\osu\osu\osu.Game\IO\WrappedStorage.cs:line 73
   at osu.Game.Database.RealmAccess.<prepareFirstRealmAccess>b__27_0() in D:\a\osu\osu\osu.Game\Database\RealmAccess.cs:line 316
   at osu.Game.Utils.FileUtils.AttemptOperation(Action action, Int32 attempts, Boolean throwOnFailure) in D:\a\osu\osu\osu.Game\Utils\FileUtils.cs:line 54
   at osu.Game.Database.RealmAccess.prepareFirstRealmAccess() in D:\a\osu\osu\osu.Game\Database\RealmAccess.cs:line 314
```

Note the `CreateFile()` call at the top of the stack, which is weird since there _is_ a `storage.Exists(Filename)` check before the actual attempt to access. Looks like a race. Possibly just moving the check inside the attempted operation thing makes this less likely to occur at least.

**Comment by peppy** [comment]
> Note the CreateFile() call at the top of the stack, which is weird since there is a storage.Exists(Filename) check before the actual attempt to access. Looks like a race. Possibly just moving the check inside the attempted operation thing makes this less likely to occur at least.

Unfortunately I don't think it's that simple.

The awkward part is that realm is mostly okay with shared file handles having access to the realm file, so the check I've added is too stringent. I have concern that this could trigger incorrectly for normal users too.

A better way of handling this may be to match the specific realm error message string and do the permission check at that point before assuming corrupt?

**Comment by bdach** [comment]
> Unfortunately I don't think it's that simple.

Yeah that did absolutely nothing, the tests are still failing. Probably matching the specific exception message is better/safer at this stage.

**Comment by peppy** [comment]
I've pushed 0bfad74907be51a9755e43cad6f44db372b57f21, a bit ugly structurally (and untested on windows yet).

**Review by bdach — DISMISSED** [review]

**Comment by bdach** [comment]
Last commit should go in https://github.com/ppy/osu/pull/28033.

**Comment by peppy** [comment]
Bad cherry-pick, oops. Have force pushed away.

**Review by bdach — APPROVED** [review]

**Pull request merged**
