### PR TITLE
Beatmap framework

### PR DESCRIPTION
**Pull request by peppy**
Opening this PR earlier rather than later to get more eyes on it.

The aim of this pull request is to lay out the basic framework for which we will build implementations around, for BeatmapSets, Beatmaps, HitObjects and everything related.

### CODE REVIEW

**Comment by Gluestick** [comment]
Any reason not to move `Creator` to `Metadata`? Currently, .osu files list the creator as metadata.

Slightly related: .osu files also look like you can have beatmaps with different metadata in the same mapset, but I could be wrong about that one. If this is the case, `Metadata` should probably be part of `Beatmap`, not `BeatmapSet`.

**Comment by tsudoko** [comment]
Are `Beatmap` and `Metadata` classes going to be used in caches (e.g. osu!.db)? If so, will osu!lazer not let the users choose between displaying Unicode and ASCII metadata?

**Comment by peppy** [comment]
@Gluestick `Metadata` was intended to keep song-related info (the audio portion). The reason it is in both `BeatmapSet` and `Beatmap` is *so* that a beatmap can override it if necessary. I believe `Creator` is sligbtly more top-level than `Metadata`

@tsudoko I think you can probably tell that the classes are not a complete implementation. There is still a lot missing, including, as you mention, unicode counterparts for some fields.

**Comment by smoogipooo** [comment]
Looks okay for the most part. My only two issues at this point in time are:
1) The naming of the hit object base. Why choose BaseHit over HitObjectBase? 
2) Not really a fan of the ConvertAll stuff you're doing in the renderers - mostly the getter. Would also prefer if that was hidden away in the abstract class, perhaps calling a "ProcessHit" method or similar.

**Comment by peppy** [comment]
@smoogipooo addressed all your concerns here.

**Pull request merged**
