### PR TITLE
Add inline disclaimer displays on player loader

### LINKED ISSUE #6480: Non-ranked map disclaimer
**Describe the missing feature:** 
osu!stable warns the player that a map isn't ranked. osu!lazer should probably reimplement this. The warning should only appear inside `PlayerLoader` (or as another form), since if you skip a map in stable the warning is still visible, interferring with gameplay.

**Proposal designs of the feature:** 
image

I would take care of this issue as a PR, if the design is set.

### PR DESCRIPTION
**Pull request by bdach**
- Supersedes / closes https://github.com/ppy/osu/pull/22167
- Closes https://github.com/ppy/osu/issues/6480

https://github.com/ppy/osu/assets/20418176/fa05ffb5-a0ea-46f3-b499-9a1fe30fc86e

Unsure if hiding/showing the epilepsy one on settings toggle is overkill or not. Probably can just nuke that behaviour if we don't care, but since it was there already kinda I decided to keep it.

### CODE REVIEW

**Comment by peppy** [comment]
The floaty design kinda looks bad, doesn't it?

I think it needs a background as proposed originally.

**Comment by bdach** [comment]
I wouldn't have PR'd if I thought it looked bad, but I can add backgrounds :shrug: Mostly confused at this point because the internal design conversation seemed to indicate no background was the winner but whatever.

First and foremost I just want to get this goddamned thing in, in _any_ shape or form.

**Comment by peppy** [comment]
It might be okay. Also a bit weird that it appears before the actual song information 🤔 .

**Comment by bdach** [comment]
Updated version:

https://github.com/ppy/osu/assets/20418176/f2866bd0-5110-486a-9a16-191880c3a8eb

Also added https://github.com/ppy/osu/pull/27616/commits/a78210c88f6d3d519c4aa884033b3a30e8e82657 because I feel it's a bit hard to read the disclaimers start to end with the delay to match metadata.

I'm not pushing anything further here for now, if you wanna tweak UX to your design it's probably better that you do it directly.

**Comment by peppy** [comment]
> Also added https://github.com/ppy/osu/commit/a78210c88f6d3d519c4aa884033b3a30e8e82657 because I feel it's a bit hard to read the disclaimers start to end with the delay to match metadata.

Yep, this was my hoped for UX from the outset so good call.

**Comment by peppy** [comment]
I've made some (mostly) visual adjustments, seems fine otherwise.

**Review by peppy — APPROVED** [review]

**Pull request merged**
