### PR TITLE
Add sanity check in Relax's effectiveMissCount calculation

### LINKED ISSUE #15486: PP counter showing -2147483648 under certain conditions
### Discussed in https://github.com/ppy/osu/discussions/15483

<div type='discussions-op-text'>

<sup>Originally posted by **Ratchet0203** November  5, 2021</sup>
When Relax mod is enabled, you have a max combo of 1 and have gotten a 100 or a 50, the pp counter will display the 32-bit signed integer. I figured this out when I was about to play a map and had to adjust my mouse. I got a 100 on the first slider and I caught the bug out of the corner of my eye as I restarted. I've experimented further with the bug, and this may have to do with the Relax pp formula counting 100s and 50s as misses, as this doesn't occur without Relax, and having all misses doesn't break the counter either. I have attached an example video of me recreating this bug on another attempt.

https://user-images.githubusercontent.com/47193790/140449423-2825be89-2c5a-4d36-8f90-99d8ce4e0626.mp4

Only the conditions I've listed are consistent, however. The counter doesn't always break on the first object. Sometimes, it takes a moment, as shown below.

https://user-images.githubusercontent.com/47193790/140450786-72edc99a-dee0-41c7-ae3d-afc0c5888c3a.mp4

I've also experimented with other mods, and none of them, even classic (which changes the rules for how combo works), seem to change anything.

Lazer version: 2021.1105.0
Logs (as exiting map after recording second video):
[performance-input.log](https://github.com/ppy/osu/files/7480178/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/7480179/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/7480180/runtime.log)
[updater.log](https://github.com/ppy/osu/files/7480181/updater.log)
[database.log](https://github.com/ppy/osu/files/7480182/database.log)
[network.log](https://github.com/ppy/osu/files/7480183/network.log)
[performance.log](https://github.com/ppy/osu/files/7480184/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/7480185/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/7480186/performance-draw.log)</div>

### PR DESCRIPTION
**Pull request by Wieku**
Fixes #15486

osu_2021-11-07_06-02-55

### CODE REVIEW

**Comment by peppy** [comment]
I don't understand how this fix works. Feels like it probably needs an inline comment with explanation.

**Comment by bdach** [comment]
For what it's worth a similar thing is already done elsewhere:

https://github.com/ppy/osu/blob/ae54e79b4c2c67c1173cad48ad168e596923f4a2/osu.Game.Rulesets.Osu/Difficulty/OsuPerformanceCalculator.cs#L268-L269

This change does seem to make some sense given that other clamp. Maybe the inline comment should be duplicated there?

**Review by bdach — DISMISSED** [review]
looks to work

**Review by peppy — APPROVED** [review]

**Comment by bdach** [comment]
Since this is more like a bugfix rather than an actual diffcalc change I'm going to cut the red tape and merge this.

Not necessary to backport to `osu-performance` as [it just doesn't give anything for relax](https://github.com/ppy/osu-performance/blob/785f53760110dcdf8e857b7e7252f67040920d8c/src/performance/osu/OsuScore.cpp#L76-L83).

**Pull request merged**
