### PR TITLE
Add a toggle for star fountains during gameplay

### PR DESCRIPTION
**Pull request by HenintsoaSky**
- Addresses #29830

Adds an option under Gameplay > General Settings that allows users to enable/disable star fountains during gameplay.

image

### CODE REVIEW

**Comment by frenzibyte** [comment]
Thanks for the contribution!

We generally avoid adding new options to the settings without a convincing reason to do so, has there been any discussion elsewhere prior to the submission of this PR?

**Comment by peppy** [comment]
For added context, this was done until now by skins making transparent images for the star sprite. Which isn't optimal as it means stars disappear from everywhere in the game.

Not strongly against this one existing.

**Comment by Joehuu** [comment]
Just noting there was an alternative solution in https://github.com/ppy/osu/discussions/29792#discussioncomment-10773684.

**Comment by frenzibyte** [comment]
Usually we will hold off such PRs until we have top-level skin settings in that case, but I'll be of the opinion on getting this one in given the argument of "I want my star fountains everywhere else except in gameplay" as mentioned in https://github.com/ppy/osu/pull/30894#issuecomment-2503101964 / https://github.com/ppy/osu/discussions/29792#discussioncomment-10774710

**Comment by peppy** [comment]
> Just noting there was an alternative solution in [#29792 (comment)](https://github.com/ppy/osu/discussions/29792#discussioncomment-10773684).

That's why this felt so familiar.

"Alternative" sure that's one way of looking at it 😅

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
