### PR TITLE
Adds mod setting `DisableFollowPoints` to the Flashlight mod

### PR DESCRIPTION
**Pull request by o-dasher**
Based on the discussion brought up by #18905

> Maybe add a subsetting for flashlight that forces follow points off? this allows for players to choose whether they want a harder but more rewarding experience( iirc followpoints are considered for pp ) or an easier one.

This adds the option for this being possible, although the pp part should be discussed by the pp comitee and such, it is still a fun option to play with regardless.

### CODE REVIEW

**Comment by peppy** [comment]
I really don't know about adding this as a *flashlight* setting.

**Comment by o-dasher** [comment]
> I really don't know about adding this as a *flashlight* setting.

I think this being a flashlight setting is fine after all the mod settings are passed to the server, so it would fit the purpouse of future performance adjust when this option is enabled/disabled, this is brought up in the discussion that i mentioned by the way.

**Comment by mk56-spn** [comment]
> I think this being a flashlight setting is fine after all the mod settings are passed to the server, so it would fit the purpouse of future performance adjust when this option is enabled/disabled, this is brought up in the discussion that i mentioned by the way. and it is way more intuitive this being a mod setting that it can possibly give a hint for the player that this affects the pp (not now but you get it).

hey! , since im the person who made the original discussion i just thought id add my thoughts , i still think it should be an option, but one housed where other mods can access it potentially, due to with the possible addition of mods such as the one i PRed recently ( freeze frame ) and looking back blinds being a thing as well i feel it shouldn't be an FL setting, that said this is totally on me for not foreseeing additional uses

**Comment by o-dasher** [comment]
> > I think this being a flashlight setting is fine after all the mod settings are passed to the server, so it would fit the purpose of future performance adjust when this option is enabled/disabled, this is brought up in the discussion that i mentioned by the way. and it is way more intuitive this being a mod setting that it can possibly give a hint for the player that this affects the pp (not now but you get it).
> 
> hey! , since im the person who made the original discussion i just thought id add my thoughts , i still think it should be an option, but one housed where other mods can access it potentially, due to with the possible addition of mods such as the one i PRed recently ( freeze frame ) and looking back blinds being a thing as well i feel it shouldn't be an FL setting, that said this is totally on me for not foreseeing additional uses

I think this would require some UI changes before this being possible, but yeah i also though on something like that, it would be a nice thing to have like a side panel with some mod settings that can affect multiple mods.

**Comment by mk56-spn** [comment]
> > > I think this being a flashlight setting is fine after all the mod settings are passed to the server, so it would fit the purpose of future performance adjust when this option is enabled/disabled, this is brought up in the discussion that i mentioned by the way. and it is way more intuitive this being a mod setting that it can possibly give a hint for the player that this affects the pp (not now but you get it).
> > 
> > 
> > hey! , since im the person who made the original discussion i just thought id add my thoughts , i still think it should be an option, but one housed where other mods can access it potentially, due to with the possible addition of mods such as the one i PRed recently ( freeze frame ) and looking back blinds being a thing as well i feel it shouldn't be an FL setting, that said this is totally on me for not foreseeing additional uses
> 
> I think this would require some UI changes before this being possible, but yeah i also though on something like that, it would be a nice thing to have like a side panel with some mod settings that can affect multiple mods based on the selected mods.
> 
> should this be closed and moved into an issue?

not for me to say if it should be closer, although id err on yes it should since this isnt the direction forward it seems, as for whether you  should open an issue i think a discussion would be a better fit since its not an issue per say, i also amended my post with the new info, and ill link whatever discussion you create for this

**Comment by peppy** [comment]
I think this should be done at a skin level. Or potentially be implemented as its own mod ("no foresight" or something).

Going to close for now as I do not think this is the correct place to add a setting and would prefer further discussion before adding settings like this to existing (ie. stable) mods for the short term. We just don't have the bandwidth to ensure a "simple setting" like this will bite us in the butt months down the line.

**Comment by o-dasher** [comment]
Follow up discussion: #20388

**Pull request closed without merging**
