### PR TITLE
Prevent tags overflowing on beatmap info overlay

### LINKED ISSUE #19505: Tags overflow in beatmap info
### Type

Cosmetic

### Bug description

Having a lot of tags on a beatmap causes it to overflow on the beatmap info screen.

### Screenshots or videos

Lazer:
osu-oveflow-lazer
Web:
osu-overflow-web

### Version

Development build (https://github.com/ppy/osu/commit/998e3b74d60180ddfeb4ee63b25b886e4f3db9f7)

### Logs

[network.log](https://github.com/ppy/osu/files/9229323/network.log)
[performance.log](https://github.com/ppy/osu/files/9229324/performance.log)
[runtime.log](https://github.com/ppy/osu/files/9229325/runtime.log)

### PR DESCRIPTION
**Pull request by gepbird**
Closes https://github.com/ppy/osu/issues/19505.

Having too much tags in a beatmap info overlay causes it to overflow (screenshot of this is in the issue).
On the website this issue is solved by limiting the number of tags, but in my opinion using a scrollable container looks better.

osu-overflow-fix-many-tags

### CODE REVIEW

**Comment by bdach** [comment]
The general expectation is that overlays should 100% match between web and the game client. So if the tag area is to become scrollable, it should also become scrollable in web.

**Comment by gutyina70** [comment]
Fixing tags overflow with scrollable containers were brought up in web too (https://github.com/ppy/osu-web/issues/5983 and https://github.com/ppy/osu-web/pull/8787) with the conclusion of @arflyte will be making hover popup for tags.

I'm looking forward to that PR being merged.

**Comment by smoogipoo** [comment]
Personally I'm not against merging this as it is given how simple of a change it is, but [the design](https://www.figma.com/file/HDSXf4LPPV7hnD5wrWYG4jix/Web%2FBeatmap-Info?node-id=0%3A1) has been updated to include the tags hover overflow.

The design also has a block background for each tag which is going to require some considerations since TFC doesn't have support for this...

**Comment by peppy** [comment]
I'd rather not add this, because nested scroll containers is really bad UX.

I'd be okay with adding masking as a temporary fix (to hide the overflow).

**Comment by gutyina70** [comment]
I see a lot has changed in the design (I assume the top left is the closest to the final) and it will probably take some time to implement it in both web and lazer.

Probably the best option right now is to use masking as a temporary fix.

**Review by peppy — APPROVED** [review]

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
