### PR TITLE
Fix hard crash when clicking play button with no map selected

### LINKED ISSUE #1507: osu!lazer crashing when clicking the play button without a beatmap selected
Steps to replicate the crash:

1. Open osu! and go to the solo play section
2. Search for a beatmap that you don't so that the game shows you "no beatmaps available"
image
3. Click the play button (bottom right corner)

The thrown exception is this:
image

> Exception thrown: 'osu.Game.Rulesets.UI.BeatmapInvalidForRulesetException' in osu.Game.dll
Exception thrown: 'System.NotImplementedException' in osu.Game.dll
[runtime:error] Could not load this beatmap sucessfully (System.NotImplementedException: The method or operation is not implemented.
   at osu.Game.Beatmaps.DummyWorkingBeatmap.DummyRulesetInfo.DummyRuleset.CreateRulesetContainerWith(WorkingBeatmap beatmap, Boolean isForCurrentRuleset) in C:\Users\pettemat\Projects\osu\osu.Game\Beatmaps\DummyWorkingBeatmap.cs:line 59
   at osu.Game.Screens.Play.Player.load(AudioManager audio, OsuConfigManager config, APIAccess api) in C:\Users\pettemat\Projects\osu\osu.Game\Screens\Play\Player.cs:line 119)!
[runtime:error] Could not load this beatmap sucessfully (System.NotImplementedException: The method or operation is not implemented.
   at osu.Game.Beatmaps.DummyWorkingBeatmap.DummyRulesetInfo.DummyRuleset.CreateRulesetContainerWith(WorkingBeatmap beatmap, Boolean isForCurrentRuleset) in C:\Users\pettemat\Projects\osu\osu.Game\Beatmaps\DummyWorkingBeatmap.cs:line 59
   at osu.Game.Screens.Play.Player.load(AudioManager audio, OsuConfigManager config, APIAccess api) in C:\Users\pettemat\Projects\osu\osu.Game\Screens\Play\Player.cs:line 119)!
Exception thrown: 'System.NullReferenceException' in osu.Game.dll
An exception of type 'System.NullReferenceException' occurred in osu.Game.dll but was not handled in user code
Object reference not set to an instance of an object.

### PR DESCRIPTION
**Pull request by peppy**
Resolves #1507.

### CODE REVIEW

**Review by MattiaPette — APPROVED** [review]

**Comment by smoogipoo** [comment]
Why can we even enter play with no map selected? This should be blocked at a SongSelect level...

**Comment by peppy** [comment]
it shows a cool message at the loader though ;P

**Review by smoogipoo — CHANGES_REQUESTED** [review]
Also, this is still throwing an exception that's getting pushed to the notification manager. I would prefer that to be a custom notification, perhaps even following what's displayed in the loader ("No beatmaps available. Please load a beatmap.")

**Comment by MattiaPette** [comment]
I talked about this in the discord server. This is still a functional fix
and the next move will probably be to remove the notification. It's the
best fix for now (imho)

Il 15 nov 2017 16:11, "Dan Balasescu" <notifications@github.com> ha scritto:

**Comment by peppy** [comment]
The exception needs to be handled better for *all exceptions from player*, not just this one.

**Review by smoogipoo — APPROVED** [review]

**Comment by peppy** [comment]
disagree that such cases should be handled at song select. player should be responsible for this and return the user to song select on failure.

**Comment by smoogipoo** [comment]
How much do you want to think about how many states Player can have?
* Can be given a DummyWorkingBeatmap that has no audio and just throws NotImplementedExceptions, we need to handle all cases where those are potentially used.
* Can be given a beatmap with no audio track at all if the beatmap has a null track (apparently possible for BeatmapManagerWorkingBeatmap). Who knows what other catastrophic failures this causes in Player atm.
* Can be given a beatmap with no hitobjects, in which case we want to send the user to song select.
* Can be given a beatmap that can't be converted to the user's ruleset, in which case we want to fall back to the beatmap's ruleset and try again.
* Can be goiven a beatmap that can't be converted to the user's ruleset, and fails to actually generate any hit objects when "converted" by the beatmap's ruleset, in which case we want to send the user to song select.

It feels to me like Player is doing too much validation of state already, and I would like to not add more to this.

**Comment by peppy** [comment]
- DummyWorkingBetamap should return a `NotAValidBeatmapException` or similar
- no audio track should still run using a virtual clock (pretty sure this already works)
- no hitobjects already has an exception thrown
- incorrect conversions already have exceptions thrown

these should still all be handled at player.

**Pull request merged**
