### PR TITLE
Changes to performance calculation

### PR DESCRIPTION
**Pull request by TextAdventurer12**
This contains a change to length bonus [to this curve](https://www.desmos.com/calculator/nxyj4v47r4), which generally nerfs longer maps, especially those greater than 2000 objects. There is also a nerf to the high AR bonus, and a small reduction to accuracy PP, as well as capping the accuracy length bonus at lower object count.

Values when combined with the other difficulty calculation changes (#28843 + #28844 + #28845 + #28846) can be seen [here](https://pp.huismetbenen.nl/rankings/players/kermit-rebalance) (onion access only)

### CODE REVIEW

**Review by stanriders — APPROVED** [review]
lgtm

**Review by tsunyoku — APPROVED** [review]

**Comment by smoogipoo** [comment]
!diffcalc

**Comment by smoogipoo** [comment]
!diffcalc

**Comment by smoogipoo** [comment]
!diffcalc

**Comment by smoogipoo** [comment]
!diffcalc

**Comment by TextAdventurer12** [comment]
Closing this because what this aims to fix needs much better solutions and this just ends up tainting values

**Pull request closed without merging**
