### PR TITLE
Adjust rate-change mod multiplier formula to almost match original proposal

### PR DESCRIPTION
**Pull request by DarkbitNetwork**
Original proposal in question: [#19711](https://github.com/ppy/osu/discussions/19711)

## Introduction
With lazer being close to "release", I decided to submit this PR to balance the mod multiplier <s>before the game mechanics are locked in and no new change can be made</s> (Apparently not, see [discord conversation](https://discord.com/channels/188630481301012481/1097318920991559880/1183760542251356220)). This PR adjusts the rate-change mod (more specifically: DT/NC, and HT/DC) multiplier to use the formula proposed in https://github.com/ppy/osu/discussions/19711#discussion-4297590 with some modifications to make it "better" (for the lack of better words).

## The reasons behind this PR:
1. HDHR is worth more than the default rate DT alone which is x1.12 > x1.1, despite DT increasing difficulty by more than both HDHR combined.
2. HT at default rate having the same multiplier as HT at 0.7x speed. (See also: https://github.com/ppy/osu/pull/23177#issuecomment-1510190525)
3. HT multiplier is far too lenient, it's a lot easier to beat NM score with HT even at default rate because playing with HT reduces difficulty a lot more than you think, making it easier to get higher scores with HT.
3.1. HT at default rate is worth more than NF despite it being much easier than playing with NF.

## Formula
Where `x` is the current rate, and `y` is mod multiplier. 
"Current formula" in Desmos refers to the formula used in the master branch

#### DT multiplier formula:
* Original formula: y = 1.12<sup>log<sub>1.5</sub>(x)</sup>
* Modified formula: y = round(1.12<sup>log<sub>1.5</sub>(floor(x * 20) / 20)</sup> * 100) / 100
* Desmos: https://www.desmos.com/calculator/7d2clzwqxy
#### HT multiplier formula:
* Original formula (HT): y = 0.3<sup>log<sub>0.75</sub>(x)</sup>
* Modified formula (HT): y = round(0.3<sup>log<sub>0.75</sub>(floor(x * 20) / 20)</sup> * 100) / 100
* Desmos: https://www.desmos.com/calculator/c3nnftew45

For DT, the multiplier is in the range [1.00, 1.21].
For HT, the multiplier is in the range [0.05, 0.81].

#### The difference between the original formula and the modified formula:
1. Stepping is used over continuous sequences (See https://github.com/ppy/osu/discussions/19711#discussioncomment-5569049 for reasoning)
2. Mod multiplier is rounded to the nearest 2 decimal places. The original formula can have up to 4 decimal places despite every other mod being limited to 2 decimal places.

## Merging this PR will result in the following changes:
1. The multiplier will now change for every 0.05x rate instead of every 0.1x rate. (See reason 2 for why)
2. DT/HT mod multiplier at default rate now matches stable being x1.12, and x0.3 respectively.
3. The formula is no longer linear, making it harder to figure out what's the multiplier at a certain rate, though I'm not sure if this can be a potential issue.
4. The multiplier difference between DT and HDHR is now basically equal. (Technically HDHR is 0.0036x more than DT but whatever)

## Current/Potential Issue:
1. Code quality check (on my branch) is failing and I have no idea how to fix it.
2. Local and online scores with rate-change mods set before this PR (assuming this PR gets merged) aren't adjusted to the new multiplier (from my testing)
3. Beatmap Spotlights (Autumn 2023) is currently ongoing so merging this PR now may cause some issues.

### CODE REVIEW

**Comment by bdach** [comment]
> before the game mechanics are locked in and no new change can be made

This is not a thing. See [relevant discord conversation](https://discord.com/channels/188630481301012481/1097318920991559880/1183760542251356220).

**Comment by bdach** [comment]
I was personally probably going to do just that actually.

**Comment by TextAdventurer12** [comment]
I think that it would be better if DT only could beat HDHR, since it's almost always more difficult to play with DT than HDHR, and a lot of very high level DT only plays are hidden beyond HDHR plays in scorev1 where the multipliers are the same

**Comment by longnguyen2004** [comment]
A word about the 0.3x HT multiplier: It has been said that the value [is arbitrary](https://github.com/ppy/osu/pull/23177), and isn't even the same across rulesets in stable (mania HT is 0.5x for example). Keep this in mind when doing multiplier tweaks, because mania HT scores will drop by 40% after conversion, which I'm not sure if players are going to be happy with.

**Comment by peppy** [comment]
As a heads up, this will not be considered from our end until next year at earliest. We are task saturated for the forseeable future.

**Comment by DarkbitNetwork** [comment]
Closing this as I don't believe that the rate-change mod multiplier should be adjusted before there's agreed upon mod multiplier post-#24166

**Pull request closed without merging**
