### PR TITLE
Specify `texelSize` value in the `Triangles` background

### LINKED ISSUE #22427: Triangles animation doesn't show in various places until you open the settings
### Type

Cosmetic

### Bug description

some places are:
- song select
- pause menu (ingame)

the triangles skin never shows any triangles even after opening the settings but i'm not sure if they were removed or not since i never check that skin. 

### Screenshots or videos

https://user-images.githubusercontent.com/43358824/214760760-fc06733e-1f64-4955-ae76-0a500dc750e2.mp4

### Version

commit 9ed0b8ccfaeec972f9bf2a0f2d64ccb407100d71

### Logs

[network.log](https://github.com/ppy/osu/files/10506397/network.log)
[performance.log](https://github.com/ppy/osu/files/10506398/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10506399/runtime.log)
[updater.log](https://github.com/ppy/osu/files/10506400/updater.log)
[database.log](https://github.com/ppy/osu/files/10506401/database.log)
[input.log](https://github.com/ppy/osu/files/10506402/input.log)

### PR DESCRIPTION
**Pull request by EVAST9919**
- Closes https://github.com/ppy/osu/issues/22427.
- [x] Depends on resources bump

There were 2 issues involved:
1. Initially `texelSize` was 0 (as intended), however it was being reset as soon as other components using `TriangleBorder` shader were introduced to the scene. (resolved by this pr)
2. When `texelSize` is 0 - nothing was being rendered to the screen due to div-by-zero situation in the shader (there was a confirmation that non-zero texelSize works as expected, but no confirmation yet that it works with 0 value)

### CODE REVIEW

**Comment by peppy** [comment]
For my own sanity, is this `textureSize` going to be set to a value in the future? Because this makes very little sense as it stands.

**Comment by EVAST9919** [comment]
> For my own sanity, is this `textureSize` going to be set to a value in the future? Because this makes very little sense as it stands.

Well, I wasn't planning to do so. Due to triangels having various sizes we would need to set a different "texelSize" value for each of them, which is insanely expensive. Thus we need to use one single value.
And now the question is: which value to use? As shown in [this comment](https://github.com/ppy/osu/issues/22427#issuecomment-1407382365) `texelSize` computed for an average triangle (size 100) will result in big triangles becoming blurry, so we may just use 0 for all of them.

**Comment by bdach** [comment]
The explanation above makes sense to me given that I am aware of all the details, but this really needs to be conveyed better in actual source via an inline comment (why the value is just a constant 0 rather than per-triangle, and why it is explicitly set to zero on every `Draw()` call).

**Comment by peppy** [comment]
Right, that explanation is exactly what I wanted. Could you add it inline in the source code as a multi-line comment?

**Review by peppy — APPROVED** [review]

**Comment by bdach** [comment]
@mouzedrift just for my conscience of mind, could you give this a branch a test and see if it fixes the issue with the missing triangles? It by all means should, as long as our guesstimated root cause is correct, but since I cannot replicate to begin with I'd rather confirm first.

**Comment by mouzedrift** [comment]
this PR fixes the issue 👍

**Comment by bdach** [comment]
Thanks again!

**Review by bdach — APPROVED** [review]

**Pull request merged**
