### PR TITLE
First pass osu!taiko "argon" skin

### PR DESCRIPTION
**Pull request by peppy**
- Missing kiai flashes
- Input drum is a bit.. "best effort". Will be able to improve this when the framework `CircularProgress` comes online with `EdgeEffect` support. In theory

Also

- [x] Depends on https://github.com/ppy/osu/pull/21148
- [x] Depends on https://github.com/ppy/osu/pull/21150
- [x] Depends on https://github.com/ppy/osu/pull/21151

### CODE REVIEW

**Comment by Feodor0090** [comment]
Is judgments visibility intended to be such? They are too transparent and quick, and barely noticeable with side vision, at least for me.

**Comment by peppy** [comment]
> Is judgments visibility intended to be such? They are too transparent and quick, and barely noticeable with side vision, at least for me.

You mean the "great" popup? You'd want it to last for longer?

**Comment by peppy** [comment]
I've adjusted the location and tween of the hit results, should be a bit more visible now.

**Review by bdach — APPROVED** [review]
Code reads okay

**Pull request merged**
