### PR TITLE
Add ability to save a failed score and replay to local leaderboards

### PR DESCRIPTION
**Pull request by santerinogelainen**
Related to #8721

Adds the ability to save your score to local leaderboards if you failed the map. Since the whole score is saved, you can also watch the replay through the scores info page.

This also means the addition of a new ScoreRank (ScoreRank.F). This could cause major problems to existing architecture but my knowledge of the code base is limited.

### CODE REVIEW

**Comment by bdach** [comment]
I'm 99% sure introducing the F rank should be a stand-alone pull request, and probably a huge one, at that. Two immediate breakages off the top of my head from what you've done here:

* No support in `DrawableRank` (how will an F rank show? probably like a D - in which case it needs to be changed to avoid visual confusion)
* Because ranks are stored as the underlying enum values in the database, doing what you've done here will cause all local scores to be bumped down one rank.

**Review by bdach — CHANGES_REQUESTED** [review]
as above - this PR does not make sense without assessing the impact of adding the F rank properly

**Comment by santerinogelainen** [comment]
@bdach Alright, I kinda figured. I'm closing this for now since assessing the impact of the F-rank is most likely too big of a task for me right now. I can reopen if the F-rank gets implemented at some point, or some other solution is found that does not require adding a new ScoreRank.

**Comment by peppy** [comment]
Not sure this needs to be closed immediately. Seems like this is mostly usable apart from that oversight. Will take a look sometime this week.

**Pull request closed without merging**
