### PR TITLE
Add repo-size "shield"/badge to README.md

### PR DESCRIPTION
**Pull request by Rudxain**
Since this repo is quite big, it would be a good idea to "warn" users who clone/download the repo so they can estimate how much time, data, and storage they'll need

### CODE REVIEW

**Comment by Coppertine** [comment]
This does not look useful at all

**Comment by Rudxain** [comment]
> This does not look useful at all

Why?

**Comment by Rudxain** [comment]
> I don't think it has legitimate uses to it.

I also thought that, but some people have slow internet, or use mobile data, or may clone the repo in a low-capacity (embedded and mobile) device before cloning it on a "better" device. There's many things that users may do that we can't account for

**Comment by peppy** [comment]
While I'm not against adding more badges for metrics, I don't think this one is of much use. The "limited bandwidth" use case doesn't hold out great when you realise the size of nuget downloads on first build/restore.

**Pull request closed without merging**
