### PR TITLE
Fix `PreviewTrack`s not being disposed correctly

### LINKED ISSUE #19581: Preview tracks are not recycled
### Discussed in https://github.com/ppy/osu/discussions/19577

<div type='discussions-op-text'>

<sup>Originally posted by **cdwcgt** August  4, 2022</sup>
I'm not sure it is a performace problem but it seens like lazer never try to recycle them.
But when the preview of the same song is played again, it will be reused.
Maybe to prevent downloading again?
Should a time limit be set for recycling?
in the video, after playing the preview music, `Track` stat didn't decrease

https://user-images.githubusercontent.com/34775378/182855621-87baebeb-0228-4028-aefa-0d2128bd28fc.mp4

</div>

### PR DESCRIPTION
**Pull request by peppy**
Closes #19581.

### CODE REVIEW

**Comment by smoogipoo** [comment]
I haven't reviewed the specifics of this change, but it only applies to the beatmap set overlay. The same issue occurs with the beatmap cards.

**Comment by peppy** [comment]
I did check and cards to handle correctly when performing a new search. Would you expect an earlier disposal than that?

**Comment by smoogipoo** [comment]
Hmm, I suppose that may be fine. They're just not disposed when the overlay is closed which I thought was weird.

**Comment by peppy** [comment]
I agree, but that goes for the cards themselves. Maybe it should reset after x seconds or minutes or not being used? Dunno.

**Review by smoogipoo — DISMISSED** [review]

**Comment by peppy** [comment]
I've added the same `LoadComponentAsync` safety to the card button as well, at least.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
