### PR TITLE
Add toggle for solo gameplay leaderboard

### PR DESCRIPTION
**Pull request by nanashi-1**

### CODE REVIEW

**Comment by peppy** [comment]
Thanks for the contribution. Rather than adding more individual toggles like this in settings, we intend to move customisation of the gameplay UI completely to the layout editor.

I'm not sure if it's worth implementing in this way short term when it will be replaced in the near future. Arguably we could add this temporarily and migrate away in the near future.

That said, this is applying to multiplayer, replays, etc.

It shouldn't

**Comment by nanashi-1** [comment]
> Thanks for the contribution. Rather than adding more individual toggles like this in settings, we intend to move customisation of the gameplay UI completely to the layout editor.
> 
> I'm not sure if it's worth implementing in this way short term when it will be replaced in the near future. Arguably we could add this temporarily and migrate away in the near future.
> 
> That said, this is applying to multiplayer, replays, etc.
> 
> It shouldn't

The gameplay leaderboard adds a lot of lag on lower-end systems like mine. This could be a temporary fix before the customization is moved to the layout editor.

**Comment by peppy** [comment]
I've fixed all the issues I pointed out, but please check through my commits so you can understand what was required.

Importantly, we prefer sticking to existing code rather than reimplementing these kinds of things in slightly different ways each time.

**Review by peppy — DISMISSED** [review]

**Comment by smoogipoo** [comment]
It looks weird when it shows then hides on gameplay restart with the setting is toggled off.

**Comment by peppy** [comment]
Good catch, I've reversed the animation to start hidden and fade in only when required.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
