### PR TITLE
Fix daily challenge results screen fetching scores beginning from the user's highest

### LINKED ISSUE #29240: Daily Challenge results start loading from personal best on subsequent scores
### Type

Game behaviour

### Bug description

When setting a score which is ranked lower on the leader-board than a previously obtained score on the Daily Challenge, the result screen starts at the position of that personal best and scrolls backwards, loading all scores between the personal best and the new score.

### Screenshots or videos

https://github.com/user-attachments/assets/722cfb5f-5bf1-47e4-ac2c-0df957590551

### Version

2024.731.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16460360/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by frenzibyte**
- Closes https://github.com/ppy/osu/issues/29240

Note that using the scoreid-based endpoint for fetching scores excludes the user's highest score for some reason, this can be seen in the video below as my highest score with total score 118,509 is omitted from the results screen. It's sort of a minor detail to care about so I'm not considering it a blocker for this p:0 issue.

Video snippet of testing the new code on dev server:

https://github.com/user-attachments/assets/87ba9137-9dd5-4f3b-85ba-76f4c19a809e

### CODE REVIEW

**Review by bdach — CHANGES_REQUESTED** [review]
> This made more sense in playlists where the results screen shows the average scores of all players

That's... not how it works? In playlists the results screen shows everyone's _best score on the particular playlist item_. You're confusing that with the leaderboard on the _playlists lounge_, which shows _the sum of best plays across all playlist items_, not the average. Nothing ever shows the average. I dunno where it would _ever make sense_ to show an "average score".

In light of that I question the entire premise of this pull request in that it's doing something special to daily challenge. What's the guarantee that this doesn't happen on standard playlists? From testing on production (with a release build) I'm pretty sure this will not be a problem that is unique to daily challenge.

What I _believe_ to be happening here is that the request fetches the user's best score on the playlist, while the results screen shows the completed play, and there's a gap of missing scores in between, so the automatic page fetch logic attempts to load every available score between user's best and current to fill the gap. And if that is the case then this is only monkey patching the issue in daily challenge, without fixing the same issue in playlists, for no reason whatsoever.

**Comment by frenzibyte** [comment]
I used the wrong word, I meant the sum not the average, you could have assumed that part.

> What I believe to be happening here is that the request fetches the user's best score on the playlist, while the results screen shows the completed play, and there's a gap of missing scores in between, so the automatic page fetch logic attempts to load every available score between user's best and current to fill the gap.

I will assume you're not implying that I should've stated this in the PR description, this part should be clear by the title alone.

> And if that is the case then this is only monkey patching the issue in daily challenge, without fixing the same issue in playlists, for no reason whatsoever.

Well hey then I am utterly confused about why are we even using the `ShowPlaylistUserScoreRequest` endpoint at all.

**Comment by bdach** [comment]
> Well hey then I am utterly confused about why are we even using the `ShowPlaylistUserScoreRequest` endpoint at all.

This bug has probably been in playlists all these years but nobody either noticed or bothered to report it. The other request that takes in a score ID was added for daily challenge specifically.

**Comment by bdach** [comment]
> Well hey then I am utterly confused about why are we even using the `ShowPlaylistUserScoreRequest` endpoint at all.

This bug has probably been in playlists all these years but nobody either noticed or bothered to report it. The other request that takes in a score ID was added for daily challenge specifically.

**Comment by bdach** [comment]
Not sure how this happened but test failures in the test that was specifically adjusted here

**Comment by frenzibyte** [comment]
My bad, I rushed out a push yesterday without double-checking tests.

**Comment by frenzibyte** [comment]
Fixed test failure and also took some time to rethink the `PlaylistItemResultsScreen` structure to make more sense with the changes applied to the endpoint. Tested to work correctly on all of playlists, multiplayer, and daily challenge.

**Review by bdach — APPROVED** [review]
seems fine, even for the code quality improvement aspect of it (no more weird nullable score ctor params)

**Pull request merged**
