### PR TITLE
Fixes on improper Catcher Size in gameplay, minor fixes on fruit borders and an important fix on Juice Stream producing

### PR DESCRIPTION
**Pull request by frankhjwx**
### Resize Catcher Size
Regarding https://github.com/ppy/osu/issues/2063, I'm fixing the catcher size by making it smaller by 1.5x, but I guess there should be some more elegant way fixing this. I can't get the current catcher info so I think dev team can help me get a more accurate value.
### Rework the borders of Fruits and FruitDrops
Current borders feel more like Hidden mode, with 500ms fadeout. I tried 100/200/50 for test and found that 50 works pretty nice, so I rewrite the border fadeout to 50. Also I added the borders to FruitDroplets.
### Rewrite JuiceStream producing method to prevent stackings of Fruits & droplets
This is some serious issue inside current lazer version. Causing by random shift float numbers, there can be fruitdrops&droplets stacking over a fruit, which is not supposed to be seen in this gamemode, so I added judgements to make sure there will be no stackings.

### CODE REVIEW

**Comment by frankhjwx** [comment]
### Other fixes
According to the code style, I split the Border generating program out seperately and threw it into **using osu.Game.Rulesets.Catch.Objects.Drawable.Pieces;**

**Comment by peppy** [comment]
Thanks for the contribution. Please check the [CI build issues](https://ci.appveyor.com/project/peppy/osu/build/master-8853) and fix them up so we can review this further.

**Comment by frankhjwx** [comment]
thx @peppy I'm not familiar with code collabing project so I'm trying, I'll let you know in discord when this pr is ready

**Comment by Xinnoh** [comment]
Looks improved but the offset where stuff is caught needs to be moved down a bit, you see too much of the catcher body
screen shot 2018-05-18 at 12 06 17 pm

This issue is amplified with higher cs, this is CS 4.5 + HR, may need some math adjustment
screen shot 2018-05-18 at 12 09 23 pm

**Comment by Xinnoh** [comment]
Oops my bad on the second issue. The code is working correctly, HR was bugged out for some reason.

**Comment by frankhjwx** [comment]
Closing this repo since I'm doing a bunch more updates on other codes implementing catch gameplay.

**Comment by frankhjwx** [comment]
So reopening this since we're going to make slight changes in side one repo uwu

**Comment by peppy** [comment]
This should also be split into individual PRs per change.  I can't review multiple changes in a single PR; if I disagree with one the overhead for rejecting or asking for changes is too high.

**Comment by frankhjwx** [comment]
ok, I'll do this then.

**Comment by frankhjwx** [comment]
ok, so close this and I'm going to make separate prs

**Pull request closed without merging**
