### PR TITLE
Clean Up and using arranged from A to Z

### PR DESCRIPTION
**Pull request by johnneijzen**
Here i have update it

### CODE REVIEW

**Comment by huoyaoyuan** [comment]
There's an option "put `System` on the top of `using`s". We should get agreement on this.

**Comment by johnneijzen** [comment]
I know there way put system top instead but it gonna lot longer is there are 679 files to check since intellisense sort using only does one per file at time.

**Comment by peppy** [comment]
As mentioned in the previous PR, this is useless unless we have something in place at CI to ensure the order. And even then, in a language like c# where order doesn't matter in the first place, I'm not sure this is even required. Especially since visual studio doesn't respect the ordering when adding new using statements.

**Comment by smoogipooo** [comment]
Let's not do this just yet, we'll do this as a post-processing pass and/or enforce it at a dotSettings/CI level.

**Pull request closed without merging**
