### PR TITLE
Fix startup tournament population not recovering from null beatmaps

### PR DESCRIPTION
**Pull request by peppy**
Matches already updated implementation in `addSeedingBeatmaps`.

Can reproduce a non-recoverable startup crash if adding a new beatmap from the round editor which doesn't have a valid `beatmap_id`.``

### CODE REVIEW

**Comment by bdach** [comment]
I mean, sure, but how much does this repopulation really help if you still can get the client to crash after a beatmap lookup failure because of stuff like this?

https://github.com/ppy/osu/blob/7c78fcd6f53183ec8593f227cd2109105be9e391/osu.Game.Tournament/Screens/Editors/RoundEditorScreen.cs#L249-L253

1. Start a perfectly good bracket
2. Add a map to a round, supply bogus beatmap ID
3. Lookup will fail and set a `null` beatmap
4. Go to bracket screen, select a match from the round that got the bogus beatmap in step (2)

yields

```
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'beatmap')
   at System.ArgumentNullException.Throw(String paramName)
   at osu.Game.Tournament.Components.TournamentBeatmapPanel..ctor(TournamentBeatmap beatmap, String mod) in /home/dachb/Documents/opensource/osu/osu.Game.Tournament/Components/TournamentBeatmapPanel.cs:line 35
   at osu.Game.Tournament.Screens.MapPool.MapPoolScreen.updateDisplay() in /home/dachb/Documents/opensource/osu/osu.Game.Tournament/Screens/MapPool/MapPoolScreen.cs:line 270
   at osu.Game.Tournament.Screens.MapPool.MapPoolScreen.CurrentMatchChanged(ValueChangedEvent`1 match) in /home/dachb/Documents/opensource/osu/osu.Game.Tournament/Screens/MapPool/MapPoolScreen.cs:line 228
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.set_Value(T value)
   at osu.Game.Tournament.Screens.Ladder.Components.DrawableMatchTeam.setCurrent() in /home/dachb/Documents/opensource/osu/osu.Game.Tournament/Screens/Ladder/Components/DrawableMatchTeam.cs:line 54
   at osu.Game.Tournament.Screens.Ladder.Components.DrawableMatchTeam.OnClick(ClickEvent e) in /home/dachb/Documents/opensource/osu/osu.Game.Tournament/Screens/Ladder/Components/DrawableMatchTeam.cs:line 150
```

If we wanna fully quell these, every single set to `Beatmap` should be ensured non-null.

**Review by bdach — CHANGES_REQUESTED** [review]
see above

**Comment by peppy** [comment]
Rather than enforcing non-null I've gone in the other direction. Felt easier to implement.

image

**Comment by bdach** [comment]
Nullable-related code inspections in map pool screen need fixing.

**Comment by bdach** [comment]
I've applied a few follow-up changes. Please check those; https://github.com/ppy/osu/pull/24357/commits/b7ddb5c94678f7ece81c628f0a28160a98953c94 is of particular concern, with rationale explained in commit message.

**Review by bdach — APPROVED** [review]

**Pull request merged**
