### PR TITLE
Reattach any orphaned scores when a beatmap is imported

### PR DESCRIPTION
**Pull request by Cootz**
I saw [discussion](https://github.com/ppy/osu/discussions/24047) about scores not being restored after beatmap re-installation. This shouldn't be the case as scores are still persist in database but don't re-assign to newly imported beatmap. This PR fixes it.
Showcase:

https://github.com/ppy/osu/assets/50776304/7efab42a-e034-476f-b666-49ba85e13f58

### CODE REVIEW

**Comment by peppy** [comment]
Tests

**Comment by Cootz** [comment]
I've read #24069 recently. Technically, this PR resolves the same issue; it's even semi-matching the second suggested way, but re-linking is done on attached scores. I decided not to detach scores to avoid dead records in the database. It also doesn't re-link scores when populating `BeatmapInfo` (because it causes weird `BeatmapSet` duplicates), but rather does it in `PreImport`.
My point is that we need to discuss whether this PR closes the issue.

**Comment by peppy** [comment]
I've made some minor changes.

I think this is fine to get in as a preliminary fix, as it's the simpler method of resolving this for users. We can implement a the other part of the proposal later.

**Review by peppy — APPROVED** [review]

**Review by peppy — DISMISSED** [review]

**Comment by bdach** [comment]
> I decided not to detach scores to avoid dead records in the database

I don't get this argument since the records are half-"dead" anyway. They are filtered out on the UI side post-https://github.com/ppy/osu/pull/22539 anyways. If anything I'd _prefer_ that they detach fully from the beatmap because the current state is a weird footgun where you can go back from a score to a beatmap that doesn't match it. I even started reading the tests and got deeply confused as to why modifying a beatmap doesn't unlink the backlink from the score to the beatmap.

I guess out of scope here. But I'd like to see that gone, and I'm probably going to go and add TODOs about this in the relevant tests.

**Review by bdach — APPROVED** [review]

**Pull request merged**
