### PR TITLE
Add interpolation to repeat point during sliding

### LINKED ISSUE #3045: return arrow snaking in sliders
when snaking in sliders in short, broken sliders, return arrow should change angle laniently 

video (look at 0:17-0:19):
https://drive.google.com/open?id=19Fo2yqGgePvna4lna9wr2ykZPuPo_TC3

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/60911863-return-arrow-snaking-in-sliders?utm_campaign=plugin&utm_content=tracker%2F4707269&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F4707269&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by peppy**
Closes #3045.

- [x] Depends on #3141.

### CODE REVIEW

**Review by smoogipoo — CHANGES_REQUESTED** [review]
as commented

**Comment by peppy** [comment]
This would probably require a rewrite of all the slider tests. The current testcase doesn't apply correct variables at all, and as such the repeat arrow never appears before a slider finishes snaking.

**Comment by peppy** [comment]
Extra test not required after dependency is merged (makes existing tests usable for this).

**Review by smoogipoo — DISMISSED** [review]
Looks fine to me.

**Pull request merged**
