### PR TITLE
Update framework

### PR DESCRIPTION
**Pull request by peppy**
Reverts d7d569cf4e68acdbcc9cec844337f93bdb207a54, which was temporarily committed to fix some serious issues with SDL3. New framework target version now defaults back to SDL2.

### CODE REVIEW

**Comment by peppy** [comment]
@smoogipoo there's a few cases of `InputManager.ChangeFocus` in tests which I'm not sure how to fix. Can you take a look and propose a solution?

**Comment by bdach** [comment]
In the framework-side changes the solution seems to just be to [cast `InputManager` to `IFocusManager`](https://github.com/ppy/osu-framework/pull/6286/files#diff-e1e6de72b4745e0be54f56499be4289aadc5804003e59b5274a5f5d7deb40efdL146)? I wanted to just unthinkingly apply that everywhere (although it seems dubious to me that that is required, but it passed review sooooo)

**Comment by peppy** [comment]
There's also one failing test (`TestSceneOsuDropdown` doesn't manage to perform the actions it needs to). I'll look at a fix unless a branch already exists.

**Comment by smoogipoo** [comment]
Wow. That test is really dodge.

**Comment by peppy** [comment]
> Wow. That test is really dodge.

Is it? I can't figure what broke it, but one would assume calling `Open()` should work, and it isn't anymore.

**Comment by smoogipoo** [comment]
For `TestSceneFilterControl`, I propose this change: https://github.com/ppy/osu-framework/pull/6297

**Comment by smoogipoo** [comment]
> but one would assume calling `Open()` should work

All I'll say is there's a reason `private` and `public` exist. I'll add back support for everything this is doing in o!f.

**Comment by smoogipoo** [comment]
Should be supported by https://github.com/ppy/osu-framework/pull/6298

**Pull request merged**
