### PR TITLE
Remove peak strain reduction

### PR DESCRIPTION
**Pull request by TextAdventurer12**
Stops reducing the peak strains in PP. Peak strain reduction is now less needed because combo scaling removal allows for a better balancing of most plays on these maps

### CODE REVIEW

**Comment by smoogipoo** [comment]
!diffcalc

**Comment by smoogipoo** [comment]
!diffcalc

**Review by apollo-dw — APPROVED** [review]

**Comment by smoogipoo** [comment]
!diffcalc

**Comment by smoogipoo** [comment]
!diffcalc

**Review by stanriders — CHANGES_REQUESTED** [review]
This looks very misleading. I think a better way would be to make those fields `abstract` in `OsuStrainSkill` and make all skills inheriting it specify it explicitly.

**Comment by tsunyoku** [comment]
> This looks very misleading. I think a better way would be to make those fields `abstract` in `OsuStrainSkill` and make all skills inheriting it specify it explicitly.

what are you referring to? the intent is to remove reduction at all.. no?

**Comment by stanriders** [comment]
> > This looks very misleading. I think a better way would be to make those fields `abstract` in `OsuStrainSkill` and make all skills inheriting it specify it explicitly.
> 
> what are you referring to? the intent is to remove reduction at all.. no?

It was only removing custom reduction in `Speed` before

@TextAdventurer12 please don't add logic changes to merge commits, it's very confusing

**Comment by smoogipoo** [comment]
Will re-run the spreadsheet generator after conflicts are resolved here.

**Comment by TextAdventurer12** [comment]
oops I renamed the branch and it closed this PR
sorry for the notif, I'll re-pr alongside some other new stuff

**Pull request closed without merging**
