### PR TITLE
Fix black screens on startup

### PR DESCRIPTION
**Pull request by peppy**
RatioAdjust was calculating in its update method without a valid parent size.

### CODE REVIEW

**Comment by smoogipooo** [comment]
So this is a tricky one for me to click merge for three reasons:
1. I replicated the issue once, even with this.
2. Following ^, I could no longer ever replicate or even hit the return.
3. I believe this should be handled better at a GameHost level since an easy way to replicate this is by resizing the window such that the height becomes 0. How do you feel about limiting window size to a minimum of (1, 1)? @Tom94

**Comment by smoogipooo** [comment]
Following ^ the change would basically be:

**Comment by peppy** [comment]
sounds fine to me

**Comment by peppy** [comment]
Closing in favour of framework-side change as suggested.

**Comment by Tom94** [comment]
Limiting the window to at least 1 pixel sounds reasonable to me.

**Pull request closed without merging**
