### PR TITLE
Replace emoji unicode with `[emoji]`

### LINKED ISSUE #24011: The game incorrectly treats Emoji as a URL
### Type

Game behaviour

### Bug description

send emoji
Click on the sent emoji
Note: The game currently does not support displaying Emoji, you may have to click around to find the sent message

### Screenshots or videos

https://github.com/ppy/osu/assets/74862110/57cb4944-0ea2-4368-8d50-b180b8d44efa

### Version

2023.621

### Logs

[runtime.log](https://github.com/ppy/osu/files/11844680/runtime.log)
[network.log](https://github.com/ppy/osu/files/11844686/network.log)
[database.log](https://github.com/ppy/osu/files/11844687/database.log)
[performance.log](https://github.com/ppy/osu/files/11844688/performance.log)

### PR DESCRIPTION
**Pull request by andrewhong04**
Fixes: https://github.com/ppy/osu/issues/24011

### CODE REVIEW

**Comment by bdach** [comment]
Okay, first of all, what is that original code. What was it doing even. It's completely not discussed in the [original PR](https://github.com/ppy/osu/pull/1667) why emoji are changed into empty links. I _presume_ it may be a way to make emoji disappear (more on why in a second), but if it was, it probably makes top 5 for the most scuffed hacks I've seen around these parts. So I'm wholeheartedly in favour of removal.

A few things, however. Most importantly, applying this diff naively as is leads to this happening if a message with emoji in it gets posted:



We _probably_ don't want all those question marks there. I _think_ that's what the original code might have been doing, in its own extremely strange and misguided way. I'm _not_ asking to add emoji support - while we're _probably_ eventually going to have to, it's going to be a... complicated one to figure out. The saner makeshift way to handle this than what `master` does would be to strip emoji _as text_, before doing any link parsing. Just do a `Regex.Replace()` the emoji regex for empty string.

Also tests need fixing.

**Review by bdach — CHANGES_REQUESTED** [review]
as above

**Comment by novialriptide** [comment]
`TestAllSamplesStopDuringSeek` is failing, but I don't think that's because of my end... Could someone re-run the tests?

**Comment by peppy** [comment]
We could probably add a new font with the emoji range quite easily (and from my recollection, the osu!stable emoji do match unicode standards).. Not sure if that should be done in this PR or not though. Probably hiding or replacing with something that isn't a `?` but implies an emoji is there..

**Comment by bdach** [comment]
> `TestAllSamplesStopDuringSeek` is failing, but I don't think that's because of my end... Could someone re-run the tests?

Please ignore, that test is flaky.

> We could probably add a new font with the emoji range quite easily (and from my recollection, the osu!stable emoji do match unicode standards).. Not sure if that should be done in this PR or not though. 

It's probably the way I would go yeah, but the "font" part is going to be a bit of an issue there. Ideally the font would be in colour, maybe even twemoji-derived. From what I've been looking at bmfont can handle it, but not sure our font stack will.

> Probably hiding or replacing with something that isn't a `?` but implies an emoji is there..

Not sure what character to pick... Maybe just `[emoji]` as a string or something...?

**Comment by peppy** [comment]
`[emoji]` seems fine.

**Review by bdach — APPROVED** [review]

**Pull request merged**
