### PR TITLE
Beatmap options overlay + Song Select Buttons

### PR DESCRIPTION
**Pull request by RemieRichards**
<B>Changes:</B>
* Adds PopUpDialog Class, an OverlayContainer Subclass designed for Popup dialogs
* Adds PopUpDialogButton Class, styled buttons for PopUpDialogs
* Adds DeleteBeatmapDialog - Partly wired up, The exit/close functionality is wired up at the moment.
* Adds SongSelectOptionsContainer Class, a Container for SongSelectOptionsButtons
* Adds SongSelectOptionsButton Class, Buttons for the Song Select Options (Remove from Unplayed, Delete Beatmap, etc.)
* Adds 3 buttons to PlaySongSelect:
    - Mods
    - Random - Partly Functional, always picks the first difficulty of a Beatmap Set as opposed to Stable's "recommended" difficulty.
    - Options - Functional, Pops open the SongSelectOptionsContainer

<B>Todo:</B>
- [x] Update to match designs now I have them.
- [x] Wait for https://github.com/ppy/osu-framework/pull/364 Merger/Judgement and Update
- [x] Generalise BeatmapOptionsOverlay to a PopUpDialog Class
- [x] Song Select Buttons should expand colour/light on Hover, not Click
- [x] Back Button superseded by https://github.com/ppy/osu/pull/199, update once merged.
- [x] Fix Conflicts from #199
- [x] Implement Song Select Beatmap Options menu
- [x] Wait for https://github.com/ppy/osu-framework/pull/376 Merger and Update (Will conflict and not compile until then)
- [x] https://github.com/ppy/osu-framework/pull/386 Merger and Update
- [x] Fix conflicts

<B>Gifs:</B>

Song Select Toolbar Buttons:
SongSelectBottomBarButtons

Song Select Options:
SongSelectOptions

Random Button+Beatmap Options Overlay: (Huge gif, won't embed)
http://i.imgur.com/AoibXQo.gif

### CODE REVIEW

**Comment by peppy** [comment]
As discussed, the code should be used for more than just the delete map popup. There should be a base PopUpDialog class that can be extended by adding buttons/overriding the text and icons used in subclasses.

Here's how things look for the specific flow you've implemented here. The first level menu is actually different from how you implemented it, so you may want to adjust to be more like this (slowed down to 25% speed).



Also get rid of all your global stuff in OsuGame. It shouldn't exist.

**Comment by peppy** [comment]
https://streamable.com/81yy
https://streamable.com/cgjw

i have no idea what is going on, but it's not right

**Comment by RemieRichards** [comment]
Sorry this took a while, I'll look into it when I get home, I believe I know what's up + how to fix.

**Comment by RemieRichards** [comment]
@peppy Sorry communication's been a bit poor on my end, I'm on trial for a new job so my time's been elsewhere. Anything you need from me regarding this? (If it's more appropriate for the discord that's fine)

**Comment by peppy** [comment]
i'm going to continue this on my end since there's a lot to fix and i want to see it in the game

**Comment by RemieRichards** [comment]
Completely fair.

**Comment by peppy** [comment]
Going to close this one. I've reimplemented the footer area in #295. The other two components of this should be completed in separate pull requests (one for the dialog and one for the second level options display).

Note that after further discussion with flyte, the second level options display may not need to exist (all the options in it are directly related to a ranking display or a beatmap, which means a right-click contextual menu may suit better here).

**Pull request closed without merging**
