### PR TITLE
Refactor OsuButton and TriangleButton inheritance relation

### PR DESCRIPTION
**Pull request by Rekkonnect**
Split from #3078

### CODE REVIEW

**Comment by smoogipoo** [comment]
Testcase?

**Comment by smoogipoo** [comment]
This should derive TriangleButton, set the `Triangles` alpha to 0, and apply the required changes to `CornerRadius`. Almost the same thing is done in `DrawableRadioButton`.

**Review by smoogipoo — CHANGES_REQUESTED** [review]
As commented.

**Review by smoogipoo — COMMENTED** [review]
@peppy requesting review.

**Comment by peppy** [comment]
Are you aware these buttons are all disabled int he testcase? Seems like a very weird `TestCase`...

**Comment by peppy** [comment]
Also I'd recommend adding some padding and maybe colours something to the testcase... it looks like a half-assed 2016 testcase

**Review by smoogipoo — DISMISSED** [review]

**Comment by smoogipoo** [comment]
@peppy re-review plz, removed the testcase because it didn't really test anything

**Review by peppy — APPROVED** [review]

**Pull request merged**
