### PR TITLE
Select text in beat divisor popover automatically

### PR DESCRIPTION
**Pull request by peppy**
- [x] Depends on https://github.com/ppy/osu-framework/pull/5823.

### CODE REVIEW

**Comment by bdach** [comment]
So I wanted to revive this. Seeing that the changes in the framework PR made the `SelectAll()` method no longer force focus, I applied this diff:

```diff
diff --git a/osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs b/osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs
index 7eba1fe1cd..86ac58354e 100644
--- a/osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs
+++ b/osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs
@@ -342,7 +342,11 @@ protected override void LoadComplete()
                 BeatDivisor.BindValueChanged(_ => updateState(), true);
                 divisorTextBox.OnCommit += (_, _) => setPresetsFromTextBoxEntry();
 
-                divisorTextBox.SelectAll();
+                Schedule(() =>
+                {
+                    GetContainingInputManager().ChangeFocus(divisorTextBox);
+                    divisorTextBox.SelectAll();
+                });
             }
 
             private void setPresetsFromTextBoxEntry()

```

But it doesn't work, because news flash: calling `SelectAll()` doesn't work if it is called before `TextBox`'s `LoadComplete()`. Why? [Because of this.](https://github.com/ppy/osu-framework/blob/f1981a30fe42f456c43b18616b541e69dfaa9022/osu.Framework/Graphics/UserInterface/TextBox.cs#L222) The `SelectAll()` call gets basically overridden by that because `setText()` resets selection bounds.

Something like this works:

```diff
diff --git a/osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs b/osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs
index 7eba1fe1cd..b33edb9edb 100644
--- a/osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs
+++ b/osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs
@@ -321,7 +321,7 @@ public CustomDivisorPopover()
                     Spacing = new Vector2(10),
                     Children = new Drawable[]
                     {
-                        divisorTextBox = new OsuNumberBox
+                        divisorTextBox = new AutoSelectTextBox
                         {
                             RelativeSizeAxes = Axes.X,
                             PlaceholderText = "Beat divisor"
@@ -341,8 +341,6 @@ protected override void LoadComplete()
                 base.LoadComplete();
                 BeatDivisor.BindValueChanged(_ => updateState(), true);
                 divisorTextBox.OnCommit += (_, _) => setPresetsFromTextBoxEntry();
-
-                divisorTextBox.SelectAll();
             }
 
             private void setPresetsFromTextBoxEntry()
@@ -590,5 +588,16 @@ public bool Active
                 }
             }
         }
+
+        private partial class AutoSelectTextBox : OsuNumberBox
+        {
+            protected override void LoadComplete()
+            {
+                base.LoadComplete();
+
+                GetContainingInputManager().ChangeFocus(this);
+                SelectAll();
+            }
+        }
     }
 }

```

but at this point I question the validity of the `SelectAll()` method as implemented.

**Comment by peppy** [comment]
Would it for some reason require a double-schedule to be correctly after the base `LoadComplete`?

**Comment by bdach** [comment]
Double scheduling appeared to work too yes, but I didn't post that version as too cursed to live.

**Comment by peppy** [comment]
I'm more curious why a single schedule doesn't work. It doesn't look like `setText()` is scheduling or anything.

**Comment by bdach** [comment]
The double schedule is needed because the single schedule we're talking about is not placed on the textbox's parent rather than the textbox itself, and so the sequence is:

- parent `LoadComplete()`
- parent scheduler update
- textbox `LoadComplete()`

The textbox `LoadComplete()` contains the `setText()` call that resets the selection.

**Comment by peppy** [comment]
I see.

I'm okay with the subclassing – that's how I expected this PR to be fixed (and how I tested) with the framework side change.

**Review by bdach — APPROVED** [review]

**Pull request merged**
