### PR TITLE
mask the settings overlay

### PR DESCRIPTION
**Pull request by jorolf**
so that you can't see this:
image

### CODE REVIEW

**Comment by peppy** [comment]
Not sure if this is expected behaviour; will have to consult designer-san.

**Comment by peppy** [comment]
@arflyte need your opinion here (should the settings be visible under the toolbar or not?)

**Comment by jorolf** [comment]
settings are not visible at all under the toolbar because the scrollcontainer is masked.
what this is fixing is only the header.

**Comment by peppy** [comment]
right you have a point.

**Review by peppy — APPROVED** [review]

**Pull request merged**
