### PR TITLE
Fix best rank badge not handling legacy scores properly

### LINKED ISSUE #19302: Achieved rank does not change if getting a better rank.
### Type

Other

### Bug description

The "A" rank is an imported score. Getting a better rank does not update the shown rank on a difficulty.

### Screenshots or videos

https://user-images.githubusercontent.com/34138240/180503521-40baba8d-95c9-4236-b2af-6996a20cc928.mp4

### Version

2022.719.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/9169972/runtime.log)
[network.log](https://github.com/ppy/osu/files/9169973/network.log)
[database.log](https://github.com/ppy/osu/files/9169974/database.log)
[performance.log](https://github.com/ppy/osu/files/9169975/performance.log)

### PR DESCRIPTION
**Pull request by frenzibyte**
- Closes #19302 

The previous code of best rank badge orders scores by `TotalScore`, which could be in different algorithms based on the score type (standardised for lazer scores, classic/stable for legacy scores).

I have simply fixed this by using `OrderByTotalScoreAsync` instead, but was stumbled by the fact that `TopLocalRank` becomes non-present when no rank is set, meaning scheduling any callback will never invoke back unless I add yet another condition to the `IsPresent` flag to handle that.

Therefore I went ahead and refactored `TopLocalRank` to not hack around core drawable properties for presence.

### CODE REVIEW

**Comment by bdach** [comment]
I'm honestly not sure about this solution. Do we really want to be doing on-the-fly score recomputing and re-sorting everywhere? With online sources this is probably unavoidable, sure, but with local scores?

Surely this could be also fixed by recomputing total score for legacy scores to standardised, to adhere to expectations?

**Comment by bdach** [comment]
For reference, lazer scores are already always imported and stored with standardised total score, regardless of the current user preference for scoring style (https://github.com/ppy/osu/pull/10768). That's also why I'm proposing the alternate route, just so that we have 100% consistency and uniformity in the score collection in DB.

As long as scoring styles don't reorder scores (which they don't, that was one of the core assumptions for having them), this makes it so that overwriting legacy score with standardised will fix the issue without having to recompute total score for _all_ local scores every time the top rank badge needs to show/update.

**Comment by frenzibyte** [comment]
That is also the alternate path I had in mind as well, but that makes me question the purpose of `OrderByTotalScoreAsync` in that case, which is also used for local leaderboards in song select.

But I’m going to assume the real use comes in online leaderboards that contains legacy scores, which despite no longer being a thing now, it’ll return later.

**Comment by bdach** [comment]
For what it's worth I'd personally be interested to hear other thoughts on this matter first before proceeding in either direction.

**Comment by peppy** [comment]
I'm also very hesitant about this route. Having a "top rank" badge fetch all scores for a beatmap, recalculate beatmap's difficulty then perform an async sort just to get the rank seems wrong.

**Comment by peppy** [comment]
Probably best to wait on https://github.com/ppy/osu/issues/19519 before attempting to fix this. I'm hoping it makes things a lot simpler.

**Comment by frenzibyte** [comment]
> As an aside, I still really dislike the order method having to exist in the first place. Maybe that can go away once we include enough statistics in `SoloScoreInfo` itself?

I believe the ordering method will still have to exist since we can't order just by `BaseScore`/`BonusScore`, we have to compute the total score using `ScoreManager.GetTotalScore`. It won't be asynchronous more though, it'll serve to be a synchronous helper method if anything.

**Comment by peppy** [comment]
@frenzibyte I think this can be revisited now, when you get a chance to look into it.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
