### PR TITLE
Add setting to always hide epilepsy warning

### PR DESCRIPTION
**Pull request by ghost**
#20249

Also can someone help me out with the `.idea/.idea.osu.Desktop/.idea/vcs.xml` file? Somehow modified it and can't get it back to the way it was before (hence the 2 useless commits)

### CODE REVIEW

**Comment by Rian8337** [comment]
Was there a discussion regarding this? I don't see why the epilepsy warning should be toggleable and I really don't think it should. It is there for a good purpose, and it's only displayed at the start of the gameplay for a few seconds, so it doesn't affect user experience that much.

The only reasonable condition to disable epilepsy warning is when neither storyboard nor video is active, IMO.

**Comment by Coppertine** [comment]
Mappers do intentionally enable Epilepsy warning for excesive Kiai times and / or kiai with high bpm sections.

**Comment by Rian8337** [comment]
Ah, I see. In that case I don't think this should be an option at all.

**Comment by peppy** [comment]
I'm not going to approve this one as I'm unsure it's the correct direction (see discussion in linked issue). Will wait for more opinions from team

**Comment by smoogipoo** [comment]
Yeah I don't think this is the correct direction either. I agree with the concerns raised in the issue.

Initially I was thinking this could be a session-wide disable, but it depends on where the line is drawn. And perhaps it could be a more prominent warning in the future that is displayed every time but doesn't take up additional time at the loading screen?

**Comment by peppy** [comment]
If we are keeping the "mapper can choose" part, then it probably makes more sense to show it as part of the existing loading delay, rather than adding extra delay.

If we're taking it into our own hands then showing separately makes sense, as I believe even people without epilepsy can be annoyed by intense flashing and would be wanting to know about such beatmaps. Depending on demand there could also be an automatic storyboard disable for intense flashing.

Let's continue this one in discussion.

**Pull request closed without merging**
