### PR TITLE
Fix legacy score calculators using incorrect mod multipliers

### LINKED ISSUE #24653: osu! ruleset ScoreV1 simulation underestimates total score
### Type

Other

### Bug description

With `[ HD HR DT FL ]`, the [SV1 simulator](https://github.com/ppy/osu/blob/d70df88fa007c7a3f5b4e3e2d600e7fa634ee2f5/osu.Game.Rulesets.Osu/Difficulty/OsuLegacyScoreSimulator.cs) estimates https://osu.ppy.sh/beatmapsets/1#osu/75 at `2052734`.

```
AccuracyScore = 61200
ComboScore = 1960834
legacyBonusScore = 30700
```

There are several scores on the leaderboard above this value, even non-FCs.

We should probably investigate this and try to match it better, because this is used for SV1 -> SV2 conversion of legacy scores.

### Screenshots or videos

_No response_

### Version

d70df88fa007c7a3f5b4e3e2d600e7fa634ee2f5

### Logs

-

### PR DESCRIPTION
**Pull request by smoogipoo**
Supersedes https://github.com/ppy/osu/pull/24685
Fixes https://github.com/ppy/osu/issues/24653

For those that have access to it, you can refer to this method in the osu-stable source: https://github.com/peppy/osu-stable-reference/blob/1531237b63392e82c003c712faa028406073aa8f/osu!/GameplayElements/Scoring/ModManager.cs#L180-L194

There's no real good way to test this right now, except by manually setting `DifficultyCalculator.ComputeLegacyScoringValues` to `true` and then breakpointing in the SV1 calculation block. The reason is because score by itself is kind-of meaningless on its own unless you're drilling down into something specific/you know what you're looking for - in this case the calculated total legacy score, which isn't exposed yet (maybe an osu-tools command is a good fit).

Also, I was told not to worry about allocations of `new ManiaRuleset().RulesetInfo` (both in the allocation of the objects _and_ the finalisable `RealmObject` that `RulesetInfo` inherits).

Spreadsheets:
- osu: https://docs.google.com/spreadsheets/d/1jddPiIXAoRx-8qCV-5lXvuCQnI6Xi3Unvkk-d7M9jZk/edit
- taiko: https://docs.google.com/spreadsheets/d/1TP9mXkdfrJ8EkgtiRXFHnsZ2KcH2jHylgS7vQI6JETs/edit
- catch: https://docs.google.com/spreadsheets/d/1775wvruC_H4Lp6bEt6DoXi-tz--QuPu3vw4OVj8Omvw/edit
    - Lazer doesn't have the correct multiplier for HT in catch (stable: 0.3, lazer: 0.7).
- mania: https://docs.google.com/spreadsheets/d/1_d0JHD2vToH3585_7SDex4uMMUayd08cd-m5L2iVidk/edit
    - Lazer doesn't have mod multipliers for keymods.

Spreadsheet TBD.

### CODE REVIEW

**Comment by bdach** [comment]
From the source alone this seems pretty much okay, no major objections.

- Not sure why this is in draft state - is that for the spreadsheet?
- Is there any particular testing worth running, aside from like smoke tests to make sure the game launches?

**Comment by smoogipoo** [comment]
Yeah, draft state because I want to get some spreadsheets out.

**Comment by smoogipoo** [comment]
Moving this into ready for review because the osu spreadsheet (added to description) looks okay and fairly closely matches the previous PR (differences between spreadsheets are that the previous one was processed over top-10000 whereas this one is top-1000, and the previous one contained the `scoreMultiplier` prevision bug).

**Comment by smoogipoo** [comment]
Something does not look right with catch. Almost like the HT multiplier isn't added in. Blocked while investigating.

**Comment by smoogipoo** [comment]
Okay, turns out this is fine to go ahead. I justified some of the changes in the description.

**Comment by bdach** [comment]
So I've looked at this from a few directions. I don't think there's much reason left not to get this in anymore.

The sheets generally look good. The only thing approaching suspicious there is this row on the catch sheet:



as it generally should not be possible for a HT score to reach 1 million (save for _egregious_ bonus, and even then). But upon closer investigation I believe this is likely another case of [the rounding issue I found a while back](https://discord.com/channels/188630481301012481/188630652340404224/1154367700378865715), which underestimates the map-dependent "score multiplier" and thus has a major impact on maximum total. The calculated `difficultyPeppyStars` in this case before rounding is 4.5, which is the same as I had in my case. And manually forcing the rounding to return 5 (via debugger) caused a way more reasonable total to be spit out.

I'm not sure how much this rounding issue is going to be a problem for us. Maybe we should reconsider fixing it. I'm not entirely sure _how_ we would do it exactly, though...

**Review by bdach — APPROVED** [review]

**Pull request merged**
