### PR TITLE
Fix exception when dragging after deleting object

### PR DESCRIPTION
**Pull request by smoogipoo**

### CODE REVIEW

**Comment by bdach** [comment]
Did this relate to #9063 in any way?

**Comment by peppy** [comment]
I think that was the intention, yeah.

**Comment by smoogipoo** [comment]
The issue lists a different exception that I couldn't replicate, so I hesitate to call it fixed. I found this one instead.

**Comment by peppy** [comment]
Is the exception you got a different one from that issue? Can't find any documentation of the exception this is fixing.

**Comment by smoogipoo** [comment]
Yeah, this one's a nullref:
```
[runtime] 2020-06-24 03:26:02 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
[runtime] 2020-06-24 03:26:02 [error]: at osu.Game.Rulesets.Edit.OverlaySelectionBlueprint.GetInstantDelta(Vector2 screenSpacePosition) in /home/smgi/Repos/osu/osu.Game/Rulesets/Edit/OverlaySelectionBlueprint.cs:line 37
[runtime] 2020-06-24 03:26:02 [error]: at osu.Game.Screens.Edit.Compose.Components.MoveSelectionEvent..ctor(SelectionBlueprint blueprint, Vector2 screenSpacePosition) in /home/smgi/Repos/osu/osu.Game/Screens/Edit/Compose/Components/MoveSelectionEvent.cs:line 34
[runtime] 2020-06-24 03:26:02 [error]: at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer.moveCurrentSelection(DragEvent e) in /home/smgi/Repos/osu/osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs:line 405
[runtime] 2020-06-24 03:26:02 [error]: at osu.Game.Screens.Edit.Compose.Components.BlueprintContainer.OnDrag(DragEvent e) in /home/smgi/Repos/osu/osu.Game/Screens/Edit/Compose/Components/BlueprintContainer.cs:line 187
```

Basically because the blueprint is removed from the hierarchy its `Parent` becomes null, which is used by `GetInstantDelta()`.

**Comment by peppy** [comment]
I *think* the linked issue is likely going to be fixed by this though. The whole pathway in that exception is through the blueprint that is correctly cleaned up in this PR>

**Pull request merged**
