### PR TITLE
Fix beatmap background displayed if storyboard is hidden on "Cinema" mod

### LINKED ISSUE #12380: Beatmap background shown behind storyboard in Cinema mod if storyboard is disabled
**Describe the bug:** 

When playing with Cinema mod, the storyboard/video will always be shown, regardless of `Storyboard / Video` toggle.
When `Storyboard / Video` is disabled, the background will be shown under the storyboard. This is unwanted behavior.

Can be seen on https://osu.ppy.sh/beatmapsets/470977

To reproduce: start the game with Cinema mod, and then toggle `Storyboard / Video` during "gameplay".

**Screenshots or videos showing encountered issue:** 

How it looks normally:
osu_2021-04-12_16-07-43

How it looks with storyboard disabled:
osu_2021-04-12_16-07-40
The beatmap background is displayed in addition to the storyboard. During normal gameplay, disabling `Storyboard / Video` will disable the storyboard, and show the background.

**osu!lazer version:** 2021.410.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/6297328/network.log)
[performance.log](https://github.com/ppy/osu/files/6297329/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6297330/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6297331/updater.log)

### PR DESCRIPTION
**Pull request by frenzibyte**
Closes #12380 

The issue was happening due to `DimmableBackground` not hiding its content when `ShowStoryboard` is false, regardless of whether the user settings are ignored.

Also merges `EnableUserDim` and `IgnoreUserSettings` to one as they both share the same purpose, which is ignoring the user's configuration.

### CODE REVIEW

**Comment by peppy** [comment]
Just to confirm intention here: this removes the ability to disable storyboards when cinema mode is enabled. I think this is fine, but it wasn't explicitly mentioned anywhere in your PR.

I think combining the two variables is fine. They were originally separated because one had larger scope than the other, but I think that may have since been reduced.

**Review by peppy — APPROVED** [review]

**Comment by frenzibyte** [comment]
Yeah, it's to remove the whole ability to disable storyboards, it's already done but this PR fixes a remaining part of it that still doesn't respect that (`DimmableBackground`).

**Comment by Joehuu** [comment]
Song select seems to have regressed.

**Comment by frenzibyte** [comment]
Turns out to be because of `BackgroundScreenBeatmap` usually initializes its `DimmableBackground` with the user settings ignored (`EnableUserDim = new Bindable<bool>();`), it's really bad that such massive regression did not get caught by the relevant test scene, although it's written to actually check for that.

Will fix and add proper test cases for the regression. I have no idea how I couldn't notice it.

**Pull request merged**
