### PR TITLE
Update realm to latest version

### PR DESCRIPTION
**Pull request by peppy**
Contains minor changes to async usage in line with upstream API changes.

I believe a feedback issue we were seeing with offset changes (the only component using async write flow) may have been resolved by these upstream changes (see [release notes](https://github.com/realm/realm-dotnet/releases/tag/10.14.0)) but am not investigating further just yet.

### CODE REVIEW

**Comment by peppy** [comment]
Unfortunately doesn't seem to heavily improve test performance on macOS, still testing older versions for confirmation whether it regressed.

master:

Rider 2022-06-03 at 04 33 53

this PR:

Rider 2022-06-03 at 05 12 15

**Comment by peppy** [comment]
Realm 10.7.0:

Rider 2022-06-03 at 05 49 49

Re-run `master` for confirmation:

Rider 2022-06-03 at 06 21 28


So it's safe to say that this PR helps improve things but as per the mention in the realm release notes, the `10.7.1` regression in performance is still well visible...

**Review by smoogipoo — APPROVED** [review]

**Comment by peppy** [comment]
One more point of reference, this is this PR (Realm 10.14.0) using ramdisk (my standard setup since i found the performance regression):

Rider 2022-06-03 at 06 53 02

Shows that the cause of my test performance regression was 100% the realm change, as this matches the times of the 10.7.0 run. I'll probably report this upstream when I get a chance.

**Comment by smoogipoo** [comment]
Here's a data point from linux:

image

**Pull request merged**
