### PR TITLE
Update resolution handling logic.

### PR DESCRIPTION
**Pull request by peppy**
Depends on https://github.com/ppy/osu-framework/pull/19.

### CODE REVIEW

**Comment by peppy** [comment]
Contains fixes for future osu-framework merges. Will update once things are back in line.

**Comment by smoogipooo** [comment]
`error: no such remote ref f04d863000ef9ca588052cc3163876b7efe1ccad`

**Comment by peppy** [comment]
working on it... my automated stuff broke ;x

**Comment by smoogipooo** [comment]
👌 🙆

**Pull request merged**
