### PR TITLE
Allow 10k to be played on a single stage

### LINKED ISSUE #8780: Add 10K single player. Make osu!mania maps with 10 keys default as single player 10K.
Currently osu!lazer defaults 10K maps as 5K + 5K (split stages), since most (if not all) players play this key count as 10K single player (one stage with 10 columns), I propose the next changes to osu!lazer:

- Making 10K default as single player, except if the user uses the coop (osu!stable) mod or dual stages (osu!lazer) mod.
- Making 10K skin as default one stage with 10 columns (not split stages) (very important)
- Adding a separate option (from 5K + 5K), named as "10K" in the osu!mania key configuration options menu as default for maps with 10 keys.
- Defining a default single player key configuration layout for 10K maps, examples that 10k players tend to use (images):

[Example 1 works with ANSI, ISO or JIS if has a numpad](https://i.ppy.sh/e807acc4ca57e8946543aa95efc8ea311cf4dd78/687474703a2f2f7075752e73682f6d675958622e6a7067)
[Example 2 works with ANSI, ISO or JIS](https://i.ppy.sh/a5c63436294a4ee8eadbcf4527cfe93e31c61e1c/68747470733a2f2f692e696d6775722e636f6d2f57794d36324f792e6a7067)
[Example 3 works with ANSI, ISO or JIS](https://i.ppy.sh/727fae3fcc6c586ce73ef6b649f5171ba7616306/68747470733a2f2f692e696d6775722e636f6d2f4d536c586c68332e6a7067)
[Example 4 works with ANSI ( \ can be used instead of Enter for ANSI), ISO or JIS](https://i.ppy.sh/49afe0f13043ba237ca81d084badce88ead77e2e/68747470733a2f2f692e696d6775722e636f6d2f4965357354304d2e6a7067)

Another layout used in this video: [Example 5 works well with ISO thou still usable with ANSI or JIS, in this case it was used on an ANSI layout keyboard](https://www.youtube.com/watch?v=Gx-keGVnybI) Used US-en ISO and ANSI layout characters for the next variations of the layout used in the video:
`A S D F spacebar rightalt L ; ' enter` for ISO, ANSI or JIS: 
(JIS might have : instead of ' in some cases)
`Q W E R spacebar rightalt P [ ] \` for ANSI , enter instead of \ for ISO and JIS:
(JIS in some cases: `Q W E R spacebar rightalt P @ [ enter` )
`A S D F spacebar rightalt ; ' \ enter` for ISO or JIS:
(JIS in some cases: `A S D F spacebar rightalt ; : ] enter`)
- Adding a 10K mod in the keycount modifier mod for osu!standard converted maps.
- Adding 10K to the editor as a full fledged single player keycout (like 1-9k).
Related threads: [Make osu!mania 10k rankable. ](https://osu.ppy.sh/community/forums/topics/379786?n=1) (old but still active)

### PR DESCRIPTION
**Pull request by smoogipoo**
Resolves https://github.com/ppy/osu/issues/8780

Default keybindings: `A S D F V N J K L ;`
A little different from the proposal, mainly because our second hand bindings start on J rather than K.

Not implementing the 10K mod yet, because that needs implementation for 20K via dual stages and I couldn't figure out good bindings for that.

Probably want to clean this up at some point.

### CODE REVIEW

**Comment by Emanuel-de-Jong** [comment]
First off, thank you for listening to the community and adding the 10K key count so quickly!

The 10K community is currently voting for what would be good 20K keybindings. The vote will take until tomorrow so that people from all timezones have a fair chance. The current options are:
- qwerg huiop asdfv njkl;
- wertg huiop asdfv njkl;

But people can suggest other keybindings as well. We are trying to keep them to osu standards though. Would the options already available be acceptable?
And would it be possible to add the 10K mod and dual stages after this so that 10K will be a fully supported key count?

**Comment by CraDow** [comment]
Nice layout for 10K smoogipoo, although I don't see a point in implementing 10k+10k (10k+dual stages), if code integrity requires that be it.

**Comment by smoogipoo** [comment]
Added support for 10K mod + 20K via dual stages.

@peppy I think it's better to think of dual stages as being played on two separate keyboards. So in the process of this I've changed the bindings for dual stages.

From:
```
p1: qwer s xcvb
p2: 7890 i kl;'
```

To:
```
p1: qwer v iop[
p2: sdfg b jk;l
```

With the new bindings, for 20K:
```
p1: qwer vm iop[
p2: sdfg bn jkl;
```

I can revert if you feel these are worse, but I really don't think anyone will be playing DS with one keyboard anyway, since you can play at most 3+3K without hitting USB rollover limits anyway (at least on most keyboards).

**Comment by enoslayd** [comment]
> First off, thank you for listening to the community and adding the 10K key count so quickly!
> 
> The 10K community is currently voting for what would be good 20K keybindings. The vote will take until tomorrow so that people from all timezones have a fair chance. The current options are:
> - qwerg huiop asdfv njkl;
> - wertg huiop asdfv njkl;
> 
> But people can suggest other keybindings as well. We are trying to keep them to osu standards though. Would the options already available be acceptable?
> And would it be possible to add the 10K mod and dual stages after this so that 10K will be a fully supported key count?

Link?

**Review by CraDow — DISMISSED** [review]
To the point that I understand it looks good.

**Comment by CraDow** [comment]
> > First off, thank you for listening to the community and adding the 10K key count so quickly!
> > The 10K community is currently voting for what would be good 20K keybindings. The vote will take until tomorrow so that people from all timezones have a fair chance. The current options are:
> > 
> > * qwerg huiop asdfv njkl;
> > * wertg huiop asdfv njkl;
> > 
> > But people can suggest other keybindings as well. We are trying to keep them to osu standards though. Would the options already available be acceptable?
> > And would it be possible to add the 10K mod and dual stages after this so that 10K will be a fully supported key count?
> 
> Link?

https://discord.gg/PwzcUzk

**Comment by CraDow** [comment]
@enoslayd check https://github.com/ppy/osu/issues/8780#issuecomment-616235292

**Review by bdach — COMMENTED** [review]
Not a mania player, so can't comment on the keybindings, but the source looks sane, and all 20 keys did work when I tested them.

**Review by peppy — APPROVED** [review]

**Pull request merged**
