### PR TITLE
Remove localisation of "hide" string to fix incorrect case

### PR DESCRIPTION
**Pull request by peppy**

### CODE REVIEW

**Comment by Joehuu** [comment]
I found two more cases after looking again at my changes. Should be `ToLower()`.

image

**Review by bdach — APPROVED** [review]

**Comment by smoogipoo** [comment]
Is this some language-specific nuance? Curious why hide was changed but not "edit", which was changed alongside it in the breaking PR.

**Comment by smoogipoo** [comment]
Oh... It's just about title casing? We already have `LocalisableString.ToTitle()`, is there a reason that wasn't used?

**Comment by frenzibyte** [comment]
Because sentence casing is preferred over title casing in some cases, or at least that's why I think https://github.com/ppy/osu-framework/pull/5127 was opened.

**Comment by smoogipoo** [comment]
Ah. Then the original question still remains for why "edit" wasn't reverted.

**Comment by peppy** [comment]
Edit seems to be the correct case already in the localisation.

**Pull request merged**
