### PR TITLE
Fix default progress graph not updating after flip

### LINKED ISSUE #23375: Default song progress not being updated when flipped
### Type

Cosmetic

### Bug description

Pretty much the title

### Screenshots or videos

https://user-images.githubusercontent.com/100224757/235765908-bffea6dd-1f31-4ba3-ab37-36906888d45c.mp4

### Version

2023.419.0

### Logs

not needed

### PR DESCRIPTION
**Pull request by timiimit**
Closes #23375 

This is just a dirty hack to make progress update at the right time by checking if parent scale has changed. When flip happens, graph hides immediately in order to not show it positioned incorrectly.

There is just 1 bug where player flips the graph while FadeIn TransformSequence is in progress. If that happens alpha should go back to 0, but i am not sure how TransformSequence can be aborted.

Let me know if this should instead be fixed in some other way.

### CODE REVIEW

**Comment by bdach** [comment]
This fix is indeed pretty hacky. The framework has a dedicated invalidation system that is supposed to be intended for this sort of thing, and `SquareGraph` looks to be crudely reinventing it. The way I'd expect this to look idiomatically is as follows:

```diff
diff --git a/osu.Game/Screens/Play/SquareGraph.cs b/osu.Game/Screens/Play/SquareGraph.cs
index 57b7c84e89..db41230036 100644
--- a/osu.Game/Screens/Play/SquareGraph.cs
+++ b/osu.Game/Screens/Play/SquareGraph.cs
@@ -15,6 +15,7 @@
 using osuTK.Graphics;
 using osu.Framework.Graphics.Shapes;
 using osu.Framework.Allocation;
+using osu.Framework.Layout;
 using osu.Framework.Threading;
 
 namespace osu.Game.Screens.Play
@@ -51,7 +52,7 @@ public int[] Values
                 if (value == values) return;
 
                 values = value;
-                graphNeedsUpdate = true;
+                layout.Invalidate();
             }
         }
 
@@ -71,23 +72,25 @@ public Color4 FillColour
 
         private ScheduledDelegate scheduledCreate;
 
-        private bool graphNeedsUpdate;
+        private readonly LayoutValue layout = new LayoutValue(Invalidation.DrawSize | Invalidation.MiscGeometry);
 
-        private Vector2 previousDrawSize;
+        public SquareGraph()
+        {
+            AddLayout(layout);
+        }
 
         protected override void Update()
         {
             base.Update();
 
-            if (graphNeedsUpdate || (values != null && DrawSize != previousDrawSize))
+            if (!layout.IsValid)
             {
                 columns?.FadeOut(500, Easing.OutQuint).Expire();
 
                 scheduledCreate?.Cancel();
                 scheduledCreate = Scheduler.AddDelayed(RecreateGraph, 500);
 
-                previousDrawSize = DrawSize;
-                graphNeedsUpdate = false;
+                layout.Validate();
             }
         }
 
```

**Review by bdach — CHANGES_REQUESTED** [review]
as above

**Comment by bdach** [comment]
The caching was intentional to prevent redrawing the container every frame. Removing the caching as you have it is wrong.

**Comment by timiimit** [comment]
Now i used `LayoutValue` as you recommended. I needed `DrawInfo` instead of `MiscGeometry`. Im not exactly sure what is supposed to make it invalidate, but it is invalidated when flipped in skin editor.

I also changed the way graph is generated. Previously it was fully recreated each time almost anything changed, now columns are added or removed based on `DrawWidth` of container. When there is no difference in number of columns in graph, only a redraw is forced, but no other expensive operation is performed. Due to this faster implementation, i removed the 500ms scheduled delay and fading (which was probably only added to hide the fact that it was a slow operation).

Because graph is now instantly updated without any delay, the test for this graph doesn't succeed. I would like to know if it is okay that i removed the delay and fading or not. I remember that many times when i was playing in the past this container faded for no apparent reason. it changed size slightly and it suddenly disappeared for a second. it never made sense to me.

If it is okay to remove the delay, then i'm not sure if the test is even needed.

**Comment by timiimit** [comment]
Wait nvm, i am wrong again

**Comment by timiimit** [comment]
Alright, i finished this. I need to learn to do one thing at a time. I undid all optimization and things that are irrelevant to this PR.

**Comment by bdach** [comment]
> I need to learn to do one thing at a time.

Generally a good idea, yes.

**Review by bdach — APPROVED** [review]

**Pull request merged**
