### PR TITLE
[readme] Make the logo less big and match screen size

### PR DESCRIPTION
**Pull request by tutacat**
Use vmin for the width and make smaller. Reduce pixel size for fallback.

### CODE REVIEW

**Comment by bdach** [comment]
The current size [seems to have been chosen intentionally](https://github.com/ppy/osu/commit/376d228add3a4fa34a0d16fbd2af635fd20a994d#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5), so I dunno about this.

**Comment by peppy** [comment]
yeah i dunno, feels too small with this change?

**Comment by jvyden** [comment]
at this size, it looks better when left-aligned:
image

i think i still prefer the big logo over that, though.

**Comment by tutacat** [comment]
The problem is a fixed pixel size, for example 500px, depends on the
screen. It feels on the big side at 1080p, but at say 4k/5k it will feel
much more reasonable. It doesn't need to be that size exactly. It could
just be the same size even, but using something like em or vmin (vmin is a
fraction of the displays smallest dimension, so it doesn't get too
tall/wide for example.

It could be 33vmin (fallback 350px) or 40vmin (fallback 430px), as a
suggestion. Just on a smaller screen it feels a little large when taking up
close to half of the height (500px at 1080p is 46% of the height)

**Comment by tutacat** [comment]
Whereas on a 4k display,  500px height is just 23% of the display height

**Pull request closed without merging**
