### PR TITLE
Clear selected components on SkinEditor hide

### LINKED ISSUE #18716: osu! crashes when exiting song select whilst holding "SkinnableSprite"
### Type

Crash to desktop

### Bug description

When you are in the Skin Editor screen hold a sprite just like I did in the video and press escape to the Osu Logo Screen

### Screenshots or videos

https://user-images.githubusercontent.com/70040605/173876882-12814cf6-8e00-4f10-b714-ca621b0a94f2.mp4

### Version

2022.615.0

### Logs

[logs.zip](https://github.com/ppy/osu/files/8911293/logs.zip)

### PR DESCRIPTION
**Pull request by ggliv**
Resolves #18716.

Skin components should not be adjustable when the skin editor is not present. This change clears all selected components when `SkinEditor` is hidden to prevent any operations from taking place while it is not visible.

### CODE REVIEW

**Comment by bdach** [comment]
This is not the correct way to fix this. See below video:

https://user-images.githubusercontent.com/20418176/174331530-dfe95511-0bc2-458a-a7a2-0677ddb58129.mp4

I could let slide the fact that the resize works again after the skin editor is toggled off and on again, but the rotation tooltip should *not* be showing after the skin editor is hidden. Likely the thing to do here is to drop selection entirely when the skin editor is hidden.

**Comment by frenzibyte** [comment]
Test coverage would be good, can't imagine it being hard for this.

**Comment by ggliv** [comment]
> I could let slide the fact that the resize works again after the skin editor is toggled off and on again, but the rotation tooltip should _not_ be showing after the skin editor is hidden. Likely the thing to do here is to drop selection entirely when the skin editor is hidden.


Nice catch, I didn't notice that while testing. The tooltip is still visible even after selected components are cleared. This seems to also be an issue elsewhere, may be out of scope of this PR.

https://user-images.githubusercontent.com/47010459/174495867-2075dce9-d252-46e7-a5de-092c4da8a298.mp4

**Comment by peppy** [comment]
I'm already looking to fix this, but just for future knowledge, your test wasn't actually doing what you thought it was:

JetBrains Rider 2022-06-20 at 04 43 16

Adding the highlighted line causes the test to fail, implying that no selection was happening in the first place and it was asserting a noop.

**Review by peppy — DISMISSED** [review]

**Comment by peppy** [comment]
I've added actual repro coverage in a new test method. Looks good to me otherwise.

**Review by peppy — APPROVED** [review]

**Pull request merged**
