### PR TITLE
Update hue of certain colour schemes

### PR DESCRIPTION
**Pull request by frenzibyte**
Noticed while going through this, the [original palette in the figma designs](https://user-images.githubusercontent.com/22781491/125310750-8a6e6b80-e33b-11eb-95a0-7d1e0682d3fd.png) show that hue of `Orange` (aka "Custard") is 45°, and osu!web seems to have updated to that in https://github.com/ppy/osu-web/commit/2a2337ebf74ad0df7e69ae750ba8f7d9c2f586fb.

Also updated the attached link inline with the latest commit (permalink).

### CODE REVIEW

**Comment by bdach** [comment]
What about green? It's also wrong. Not a fan of drip-feeding these updates, I'd say that if these hues are to be touched then everything should match the latest reference even if it doesn't on web. 10 degrees of hue difference is not likely to be noticeable anyway.

Also you should probably link to [the actual figma file](https://www.figma.com/file/VIkXMYNPMtQem2RJg9k2iQ/Asset%2FColours?node-id=0%3A1) rather than a random github image.

**Comment by frenzibyte** [comment]
Eh didn't notice that one, would've updated it here otherwise, good find.

**Comment by smoogipoo** [comment]
@arflyte / @nanaya the osu-web `green` hue is different to the one listed in the design:

osu!web (H:115): https://github.com/ppy/osu-web/blob/5a536d217a21582aad999db50a981003d3ad5659/app/helpers.php#L1618-L1628
design (H:125): https://www.figma.com/file/VIkXMYNPMtQem2RJg9k2iQ/Asset%2FColours?node-id=0%3A1

Which one is the more recent/correct value?

**Comment by nanaya** [comment]
I have vague memory the section hue isn't actually related to the basic colours hue

**Comment by smoogipoo** [comment]
I see, so the values we should reference are these:
https://github.com/ppy/osu-web/blob/5a536d217a21582aad999db50a981003d3ad5659/resources/assets/less/colors.less#L132-L143 ?

Will go ahead and merge this since it seems to match those.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
