### PR TITLE
Select all text when focusing sample bank/volume textboxes in editor (and number boxes in general)

### PR DESCRIPTION
**Pull request by frenzibyte**
Coming from https://github.com/ppy/osu/issues/28713 (see second part of https://github.com/ppy/osu/issues/28713#issuecomment-2208794428 & https://github.com/ppy/osu/issues/28713#issuecomment-2209919975). This improves the experience of modifying sample bank/volume of each object on the go.

https://github.com/ppy/osu/assets/22781491/8d20f9f4-a208-42a0-92c5-5e36f2a0df46

### CODE REVIEW

**Review by smoogipoo — DISMISSED** [review]
I tend to think of this as an anti-pattern, but maybe it's alright. Requesting a second review.

**Comment by peppy** [comment]
In my experience, some apps do this and others don't, and some do it in only some places rather than everywhere.

But I can agree that this is in general – once the user is aware of what is going on – a usability and efficiency improvement.

Willing to ship and see what feedback is.

**Review by peppy — APPROVED** [review]

**Comment by aL1NaZ4R** [comment]
Volume textbox doesn't do this.

**Comment by frenzibyte** [comment]
Open an issue thread

**Pull request merged**
