### PR TITLE
Add the ability for PerformFromMenuRunner to inspect nested screen stacks

### PR DESCRIPTION
**Pull request by peppy**
Addresses https://github.com/ppy/osu/issues/11365 (when performing the action while at song select). Not sure if this is enough to close the issue - we probably want to warn/block the user from exiting their multiplayer game if they try to change beatmaps from the match screen, for instance. Or somehow convey the update to the screen in a way it can handle it.

Adding a test for this is a bit awkward but can probably do one in the navigation section if required.

### CODE REVIEW

**Comment by smoogipoo** [comment]
I think this will break in the following scenario:
```
stack -> screen -> screen
           |
           v
         stack -> target_screen -> screen

>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>> right is top of stack (current screen)
```
Where target_screen is found and made current in the sub-screenstack but the parenting screen is not made current in the top-level screenstack.

Tempted to merge since this isn't a case that we currently have but I'll leave that to your discretion.

**Review by smoogipoo — DISMISSED** [review]

**Comment by peppy** [comment]
Hmm, I think that should be a pretty easy one to fix? Just need to do a `MakeCurrent` when the recursive call returns `true`.

**Comment by smoogipoo** [comment]
Sounds correct

**Review by smoogipoo — APPROVED** [review]
Seems ok

**Pull request merged**
