### PR TITLE
Apply safe area padding and edge snapping

### PR DESCRIPTION
**Pull request by swoolcock**
WIP for design and implementation discussion.

Depends on https://github.com/ppy/osu-framework/pull/2420

Developed on desktop by hardcoding `Window.SafeAreaPadding.Value = new MarginPadding(100)`.
Tested on iPhone X and iPad Pro 12.9".

* Overlays and the screen stack are padded with a `SafeAreaContainer`.
* Backgrounds, `ParallaxContainer`s, etc. are wrapped in individual `EdgeSnappingContainer`s.
* `BeatmapInfoWedge` is wrapped in a masking container to hide the sheared edge effect.

WIP examples:

Screen Shot 2019-06-28 at 9 52 22 pm

Screen Shot 2019-06-28 at 9 52 54 pm

### CODE REVIEW

**Comment by swoolcock** [comment]
Added some screenshots of current progress.

**Comment by peppy** [comment]
This PR needs a quite involved conflict resolution / updating.

**Comment by swoolcock** [comment]
Yep, it’s sitting on hold until I get the video stuff in.

**Comment by swoolcock** [comment]
I'm going to rework this slightly to be "opt-in" rather than "opt-out", as it will allow us to PR safe area changes to individual screens.

**Comment by peppy** [comment]
Closing this one as it is stale and likely won't merge well with the changes over the last couple of years.

While this PR has some issues visually which meant it was never merged, the underlying system @swoolcock made for handling safe areas is solid, but for whatever reason we haven't used it osu! side (likely due to the stalemate on this PR?).

I am going to open a simpler initial osu!-side implementation to add basic support and we can build on that going forward (to reach something similar to what is done in this PR).

**Pull request closed without merging**
