### PR TITLE
Add score processed callback to spectator client

### PR DESCRIPTION
**Pull request by bdach**
Another small piece to facilitate https://github.com/ppy/osu/issues/18877.

This isn't all, of course. More will come, but for now I'm getting this out so that the `osu-spectator-server` pull I'm about to open can be tested if someone wants to do so.

### CODE REVIEW

**Comment by peppy** [comment]
So the plan is to just send the ID to the client and leave subsequent fetching to it?

**Comment by bdach** [comment]
That was the plan yeah. There will be a "watcher" game-level component responsible for re-querying API after each "score processed" notification received, and providing the required statistics deltas to display to the user post-completion. It could be used elsewhere if need be (user profile?)

**Comment by peppy** [comment]
I think that's fine, just wanted to confirm intentions.

Wondering if we'll eventually want to send more details than just the ID, but that can come later once we better understand the flows.

**Review by peppy — APPROVED** [review]

**Comment by bdach** [comment]
I think I may end up reversing course on what I stated above. I failed to appropriately consider many failure cases which make retrieving data reliably on the client side very dicey.

If I were to change direction I'd probably be looking to completely reverse course and move all of the data retrieval to the queue processor, and push that all the way through redis and osu-server-spectator. I don't know yet. While I have a thing that passes the tests I wrote, it sucks and I'm trying to not sunk-cost-fallacy myself into going with a subpar solution.

**Pull request merged**
