### PR TITLE
Move ModOverlay to SongSelect

### PR DESCRIPTION
**Pull request by smoogipoo**
As we discussed, edit mode isn't going to use `SongSelect`, so the only places where `SongSelect` will be used exist in the context of playability (play, multi) where mods are required.

### CODE REVIEW

**Comment by peppy** [comment]
Should I be waiting until the `Move everything from PlaySongSelect into SongSelect`? ;)

**Comment by smoogipoo** [comment]
Moved things that shouldn't be at the base SongSelect out

**Comment by peppy** [comment]
Okay, so this is ready for review?

**Comment by smoogipoo** [comment]
Yeah

**Review by peppy — APPROVED** [review]

**Pull request merged**
