### PR TITLE
Match capability of animating legacy skin elements with osu!(stable)

### LINKED ISSUE #25011: Investigate elements that are possibly animatable in lazer (but shouldn't be)
Came out of https://github.com/ppy/osu/issues/24973, [and the relevant discord discussion](https://discord.com/channels/188630481301012481/188630652340404224/1159246285040259072).

On checking, we seem to be using `.GetAnimation()` on some elements where we should probably not be, namely:

- `hitcircleoverlay` / `sliderstartcircleoverlay` / `sliderendcircleoverlay` (100% wrong, was patched in stable: https://github.com/ppy/osu-stable-issues/issues/950 - it can even be seen animating in test scenes)

  https://github.com/ppy/osu/blob/66824ce8caa75db4ce44f55d3ccebd39457c5dec/osu.Game.Rulesets.Osu/Skinning/Legacy/LegacyMainCirclePiece.cs#L79-L83
- `reversearrow` (needs to be cross-checked against stable)
  https://github.com/ppy/osu/blob/66824ce8caa75db4ce44f55d3ccebd39457c5dec/osu.Game.Rulesets.Osu/Skinning/Legacy/LegacyReverseArrow.cs#L42-L46
- `taikohitcircle` / `taikobigcircle` (needs to be cross-checked against stable; the `overlay` variants are 100% fine to be animatable, but the others - probably not so much)
  https://github.com/ppy/osu/blob/66824ce8caa75db4ce44f55d3ccebd39457c5dec/osu.Game.Rulesets.Taiko/Skinning/Legacy/LegacyCirclePiece.cs#L50-L63

Could probably be accompanied by a full sweep of `.GetAnimation()` usages across rulesets to ensure no funny business as a bonus.

### PR DESCRIPTION
**Pull request by frenzibyte**
- Closes #25011 

I've took the opportunity to do a full check on all sprite elements across stable code and wiki with regards to whether they're animatable and their specifications. Here's a table I've compiled from that, containing all animatable sprites and their framerates:
| Name | Framerate in stable |
|------|-----------|
| `hit{...}` | 60 FPS |
| `scorebar-colour` | `AnimationFramerate` FPS |
| `follow-point` | `AnimationFramerate` FPS |
| `sliderb` | velocity / 150 * 60 fps or 60 fps at minimum
| `sliderfollowcircle` | `AnimationFramerate` FPS |
| `taiko{hit,big}circleoverlay` | 2 FPS (2 frames only) |
| `pippidon{...}` | BPM-dependant FPS |
| `fruit-catcher-{...}`/`fruit-ryuuta` | `AnimationFramerate` FPS |
| `mania-hit{...}` | 20 FPS |
| `mania-stage-bottom` | 60 FPS |
| `mania-stage-light` | `LightFramePerSecond` FPS |
| `mania-note{...}`/`mania-note{...}T` | 60 FPS |
| `mania-note{...}L` | 33.33 FPS |
| `lighting{L,N}` | length / 170 fps or 60 fps at minimum |
| `menu-back` | `AnimationFramerate` FPS |
| `play-skip` | `AnimationFramerate` FPS |

In this PR, few skin elements have been corrected to match the above table.

Notes:
 - The framerate of `sliderb` will be implemented in a separate PR to reduce review complexity.
 - There are three places where `mania-stage-light` is used in stable. The [dominant usage](https://github.com/peppy/osu-stable-reference/blob/3ea48705eb67172c430371dcfc8a16a002ed0d3d/osu!/GameModes/Play/Rulesets/Mania/Stage/ColumnMania.cs#L184) (controlling display of the sprite when a key is pressed), loads the texture as an animation rather than a static sprite. Other usages are [both in here](https://github.com/peppy/osu-stable-reference/blob/3ea48705eb67172c430371dcfc8a16a002ed0d3d/osu!/GameModes/Play/Rulesets/Mania/Stage/StageMania.cs#L150-L158), and I'm not sure when any of these display in stable (the first doesn't even look visible at all, it's set to a transparent colour and never looked at again).

   I have confirmed all of this checks out with real gameplay in stable:

   https://github.com/ppy/osu/assets/22781491/b3da2a90-64bb-4efc-8545-e6776d38ce79
 - I have noticed that the `reverse-arrow` sprite is set to be animatable in lazer, meanwhile it isn't on stable and doesn't look to have ever been. I've removed animation support, but intentionally kept it on a separate commit in case we want to don't want to match stable and give the opportunity to animate slider reverse arrows (it would look cool, but this is all legacy so I'm not sure it makes sense to add that).

 - I've [refactored](https://github.com/ppy/osu/commit/ab3b51e4a0a9042d1b20d08d64b2c47b2b6848bb) the circle piece loading logic to make more sense with regards to what's animatable and what's not (at first it looked like the `taikobigcircle` sprite is animatable, but it's actually not because that component was stopped at BDL and never ran again.

### CODE REVIEW

**Comment by bdach** [comment]
Test failures require attention

**Comment by peppy** [comment]
Test failures require attention

**Comment by frenzibyte** [comment]
As we discussed before, I'm following a pattern where anything I have is pushed until I loop back and mention that the PR is ready for re-review. I will rely on GitHub CI to notify me if a test is broke after I make a change, so that I can move on to the next task without being burdened by the run length of the tests.

**Comment by peppy** [comment]
That sounds very inefficient.

**Comment by frenzibyte** [comment]
Sure, I'll change my workflow to run tests locally on a branch as I look at another task. I vaguely remember coming across some issues as a result of changing branches while tests are running, but I'll check that again.

**Comment by bdach** [comment]
https://git-scm.com/docs/git-worktree may help

**Comment by peppy** [comment]
> Sure, I'll change my workflow to run tests locally on a branch as I look at another task. I vaguely remember coming across some issues as a result of changing branches while tests are running, but I'll check that again.

As long as you don't compile, this is a feasible strategy. Else, as already mentioned, worktrees can easily achieve this with almost zero overhead.

**Review by peppy — APPROVED** [review]

**Pull request merged**
