### PR TITLE
Fix user status dropdown having no padding around items

### PR DESCRIPTION
**Pull request by Joehuu**
Fixes https://github.com/ppy/osu/issues/7489.

### CODE REVIEW

**Comment by EVAST9919** [comment]
I don't think this is what this issue is about.
The issue is that the menu itself don't have rounded corners

**Comment by Joehuu** [comment]
In https://github.com/ppy/osu/issues/7489#issuecomment-573094514, I thought smoogipoo said the non-rounded menu was the design, and the fix was making the padding the same on all dropdowns.

**Comment by recapitalverb** [comment]
Yeah, I should have edited my issue to correctly address the real issue.

**Review by peppy — APPROVED** [review]

**Comment by smoogipoo** [comment]
Could apply a similar removal to the corner radius (and margin?). It's smaller here than in other dropdowns iirc.

**Comment by Joehuu** [comment]
Yep, there are all kinds of properties being changed in these dropdowns. Will standardize them.

**Pull request merged**
