### PR TITLE
Fix feedback from realm writes causing offset slider to jump around

### LINKED ISSUE #17141: Beatmap offset slider jumps around on rapid adjustments due to realm feedback
We need a way of ignoring the realm feedback in cases like this, since it might be delayed by the async refresh flow.

### Discussed in https://github.com/ppy/osu/discussions/17110

<div type='discussions-op-text'>

<sup>Originally posted by **Walavouchey** March  6, 2022</sup>
it's only this slider as far as I know

https://user-images.githubusercontent.com/36758269/156895638-480d958a-685f-489b-a0d2-2be82a26f499.mp4

[logs.zip](https://github.com/ppy/osu/files/8191222/logs.zip)

Version: 2022.306.0-lazer</div>

### PR DESCRIPTION
**Pull request by peppy**
Closes #17141

Curious on thoughts about this solution. I *think* it's correct, and if it is we may be able to apply similar logic to a helper class implementation for future usages.

@Walavouchey can you please test against this and see if it resolves the issue for you? I've basically confirmed it works by adding `Thread.Sleep`s but a second confirmation would be helpful.

### CODE REVIEW

**Comment by Walavouchey** [comment]
The particular issue of the slider jumping around seems to have been fixed 👍

**Comment by bdach** [comment]
If I'm honest I don't really get what this fix is supposed to fix, or even where to put the appropriate `Thread.Sleep()` to reproduce this... Would appreciate spelling it out for me if possible.

**Comment by peppy** [comment]
> If I'm honest I don't really get how this fix is supposed to fix, or even where to put the appropriate `Thread.Sleep()` to reproduce this... Would appreciate spelling it out for me if possible.

The main issue was that after a write, the change callback arriving from realm could be a "feedback" event triggered from the slider bar being dragged. The change I've made stops this from happening as it will ignore the first callback if a write has recently been performed.

But while explaining this, I've realised there is a potential edge case where an external component is also writing to the value and the incorrect value changed callback could get suppressed..

I think the only real way to handle this is to split out the write flow completed (ie. via `OnUserChanged` handling in the slider bar) or to only read from realm on initialisation and then use bindable flow from that point on. Having two methods of information flow (`Bindable` and realm subscriptions) with different threading considerations is going to be a PITA to handle. What's more, we can't just force synchronisation from realm because it comes with a potential blocking overhead.

I was thinking making a `RealmBindable` and keeping all guarantees of reads/writes in that implementation may be a path forward, but not yet ready to commit to that.

I'll keep this PR open (with a minor fix) to hopefully promote further discussion, if someone else sees a potential alternative path forward.

**Comment by bdach** [comment]
Just to confirm my understanding - we're talking about this sort of feedback, right?:

```
user sets offset value to +5ms via slider
user sets offset value to +10ms via slider
slider moves back to +5ms because of the realm subscription firing
```

If that is the case then I'd probably suggest dropping the realm subscription entirely. It's not like there is some other place that can modify the beatmap offset while on the player loader screen, is there? That would be easiest/cleanest option I think. Am I missing some reason why that subscription needs to live?

**Comment by peppy** [comment]
Your understanding is correct.

An yes, right now that's the case (the subscription is not required), but a next step would be adding a hornet to adjust it, as an example.

I was hoping to figure out a good structure to protect against this going forward, since the same issue will affect any realm data bind which is written to in more than one place.

**Comment by bdach** [comment]
The one surefire way I know how to do this - borrowed from distributed systems and optimistic concurrency checking mechanisms - would be to timestamp every model with the date of the latest update (or equivalent, like row version), and use that to determine whether data from an incoming subscription event can be safely discarded in favour of the local model. But it feels a bit like killing a fly with a cannon, to a degree.

**Comment by peppy** [comment]
Yeah, that was my first thought, but I don't think we want to go down that path.

I may consider removing the subscription event short term if I don't come up with a good solution to this, and revisit in the future.

**Review by smoogipoo — APPROVED** [review]

**Comment by peppy** [comment]
Not sure merging this is a great idea considering the above conversation, but I guess it "works" for now (until something else starts writing to the property).

**Pull request merged**
