### PR TITLE
Bring back skin background source

### LINKED ISSUE #13388: Background not change to a skin background when using a skin
**Describe the bug:** 
After update to latest version (2021.608.0) I normally set a background source to a skin but after I update it's not use a background from skin. It always an osu!lazer default background. I change to other skin and it's still not change.

Before Update (I capture this on 2021.602.0 yesterday) :
CleanShot 2564-06-08 at 04 21 24@2x

After Update :
CleanShot 2564-06-09 at 02 24 35

**Screenshots or videos showing encountered issue:** 
https://youtu.be/xAXOnzFTd2Y

**osu!lazer version:** 
2021.608.0

**Skin that I test in a video:**
https://drive.google.com/drive/folders/1qC-sqQg9TY3VRlru_-NvvBwiJ-xzOcap?usp=sharing

**Logs:**
[database.log](https://github.com/ppy/osu/files/6618985/database.log)
[network.log](https://github.com/ppy/osu/files/6618986/network.log)
[performance-audio.log](https://github.com/ppy/osu/files/6618987/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6618988/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6618989/performance-update.log)
[performance.log](https://github.com/ppy/osu/files/6618990/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6618991/runtime.log)

### PR DESCRIPTION
**Pull request by bdach**
Closes #13388.

In addition to bringing back the source, the optimisation from #13362 is extended onto default and user skin backgrounds via `IEquatable<Background>` implementations, [as suggested in the review of that PR](https://github.com/ppy/osu/pull/13362/files#r646432518).

### CODE REVIEW

**Comment by peppy** [comment]
I believe this is going to cause the usual background cycling to stop working when the "Skin" option is selected but the skin is not providing a background. Previously each call to `Next()` would still cycle through the default backgrounds in this case.

Not sure how important this is. Skins don't support cycling themselves, so (once we add back the osu!classic menu background, if that's not already a thing) this may only be an issue with the "skin" option set with default lazer skin.

**Comment by bdach** [comment]
I was aware of that, but assumed it was unimportant, as the beatmap source potentially has the same problem (just manifests more rarely). I can try to fix, though, if that assumption was wrong.

**Comment by peppy** [comment]
Generally "Next" is called when the beatmap changes, to give some kind of main menu transition, which is why I wasn't too concerned about the beatmap case (99.999% of beatmaps have a background, so this wouldn't cause any regression... although now that I think about it it would still be an issue if the user was not a supporter).

**Comment by peppy** [comment]
One direction you may want to consider is splitting up `Next` into the case of "next track" vs "settings have changed". Not sure if that will help with implementation but it might.

**Comment by bdach** [comment]
I think there's a way to make it work inside the `Equals()` implementations, as the background sources all have a fallback execution branch that could be leveraged to set a flag which can be checked in `Equals()` or something, but it may read a touch awkward. Not sure yet.

**Comment by bdach** [comment]
Actually no, I take that back. In general, doing the perfectly minimal number of background replacements requires creating the new background and waiting for its BDL to complete to see if it successfully retrieved something. Which is exactly what the optimisation sought to reduce, so it's a bit of a chicken-and-egg problem.

**Comment by peppy** [comment]
Maybe a flag being like `DidUseFallbackTexture` which could be checked? Worst case it's checked before BDL completes and returns `false` and causes another default background load.

**Comment by bdach** [comment]
Well that's the thing, it'll always get checked before BDL. Because a candidate background has to pass these "should background be replaced" checks before it is even allowed to run its BDL. I could move the checks so that they only happen before actually adding the background, but at that point the majority of the work has been done.

**Comment by peppy** [comment]
Right.. so maybe a good solution for now would be to only provide the skin background version if the selected user skin is not the `DefaultSkin`? Since the rotation is only ever present on that skin type.

**Comment by bdach** [comment]
Sounds simple enough. Will probably end up breaking the test added here but I'll see what I can do.

**Comment by bdach** [comment]
Have added the proposed default skin check, along with more tests for the background rotation.

**Review by peppy — APPROVED** [review]

**Pull request merged**
