### PR TITLE
Even moar options

### PR DESCRIPTION
**Pull request by ddevault**
Dropdown options

### CODE REVIEW

**Comment by SirCmpwn** [comment]
There's a bug here I still need to sort out - try opening dropdowns twice.

**Comment by SirCmpwn** [comment]
I left a number of the dropdowns unimplemented as out of scope for this PR, each one probably deserves its own PR (skin selection, resolution options, etc)

**Comment by peppy** [comment]
nope.

image

come on dude. every time.

**Comment by peppy** [comment]
For what it's worth, in the framework there's already a test of styling sliders to a style closer to what we are looking for. You may want to move that subclass across to this project and use it.

**Comment by SirCmpwn** [comment]
Pulled in that dropdown and adjusted it to our needs, but didn't put much effort into it since it's not really worth it until we actually style it properly imo

**Comment by peppy** [comment]
difficulty range should be float/double https://puu.sh/sBHfl/841862bc5a.gif
also having both stars and slider bars is redundant. choose one or the other for now.

can't drag upwards on sliderbars to scroll (see textbox's implementation). ,maybe out of scope of this PR but still is wrong.

sliderbars aren't styled either

**Comment by peppy** [comment]
Are values supposed to save? because they don't.

**Comment by SirCmpwn** [comment]
Hmm, it was saving for me when I tested it. I'll take another look.

**Comment by SirCmpwn** [comment]
>Are values supposed to save? because they don't.
>- - -
>difficulty range should be float/double https://puu.sh/sBHfl/841862bc5a.gif
>also having both stars and slider bars is redundant. choose one or the other for now.

fixed

>sliderbars aren't styled either
>- - -
>can't drag upwards on sliderbars to scroll (see textbox's implementation). ,maybe out of scope of this PR but still is wrong.

out of scope

**Comment by peppy** [comment]
did you check that it saves? because it still doesn't (not checkboxes nor sliderbars)

**Comment by SirCmpwn** [comment]
Yes. Both of them save correctly for me.

**Pull request merged**
