### PR TITLE
Respect "Prefer metadata in original language" toggle in beatmap deletion dialog

### LINKED ISSUE #30242: Delete beatmap dialog uses romanised name
### Type

Cosmetic

### Bug description

When you try to delete a beatmap, it shows the Romanized name of the artist and the beatmap name.

I suppose the dialog code is in this line if it helps:
https://github.com/ppy/osu/blob/master/osu.Game/Screens/Select/BeatmapDeleteDialog.cs#L17

### Screenshots or videos

osu_2024-10-12_16-19-44

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17350585/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by tryh4rd3rr**
This commit fixes #30242. This fix maintains the format from before, but supports the original unicode metadata.

### CODE REVIEW

**Comment by shinmorisawa** [comment]
Note: I have removed the string interpolation. If that maybe an issue, please notify me.

**Comment by bdach** [comment]
If you wish to continue PRing changes, then please make sure that you're PRing from a topic branch and not `master`. This is mentioned in [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#submitting-pull-requests); please read them if you have not done so yet.

**Review by bdach — APPROVED** [review]

**Comment by shinmorisawa** [comment]
> If you wish to continue PRing changes, then please make sure that you're PRing from a topic branch and not `master`. This is mentioned in [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md#submitting-pull-requests); please read them if you have not done so yet.

ok thank you will do that now. :)

**Comment by bdach** [comment]
please do not merge master either unless there are conflicts or specifically instructed to, that is also listed in contributing guidelines

**Comment by shinmorisawa** [comment]
oh ok sorry

**Pull request merged**
