### PR TITLE
Add support for legacy spinner SPM counter

### PR DESCRIPTION
**Pull request by frenzibyte**
First step towards https://github.com/ppy/osu/issues/10815, apparently simplest of them all.

Few notes:
 - since the spinner usually set `TimeStarted` and fade the counter afterwards on the same frame (i.e. same time), I've ensured the counter fades in with start time set to `TimeStarted` on `DefaultSpinner`, may be an overthought thing, but I've done it anyways to avoid any potential regression somehow in the future.
 - currently osu!lazer's difficulty graph on progress bar conflicts with the legacy SPM counter, going to assume it's fine for now until maybe hide difficulty graphs completely on legacy HUDs, probably something to track in an issue thread or otherwise.
 - the legacy SPM background and counter can probably be grouped in one container that has the move transform applied to, but I wanted to have things 1:1 with osu!stable on that.

Quick comparsions horizontally and vertically between osu!stable and osu!lazer, looks to match perfectly (colour difference is due to beatmap background, fwiw):
image

image

- [x] Depends on https://github.com/ppy/osu-resources/pull/121

### CODE REVIEW

**Comment by peppy** [comment]
The vertical (mis)alignment of the SPN number is unfortunate. But I guess it's a bit too late to fix that now as it may break user skins.

**Comment by peppy** [comment]
20210330 134919 (dotnet)

Is this intended?

Also may be worth checking a few user skins; one I found looks like the spin counter is just floating in the middle of nowhere:

20210330 134948 (dotnet)

Not sure if an actual issue, but worth grabbing some top player skins and checking for any weirdness.

**Review by peppy — CHANGES_REQUESTED** [review]
As posted.

**Comment by frenzibyte** [comment]
About scaling down the gameplay would do so for the SPM counter? yeah that's not fixable since it's inside the drawable spinner, once the SPM counter is part of the HUD that can be fixed.

**Comment by frenzibyte** [comment]
> 20210330 134919 (dotnet)
> 
> Is this intended?

Unfortunately, yes. That's not fixable since it's inside the drawable spinner, which means being under the gameplay scaling container. Once the SPM counter becomes part of the HUD, that can be fixed.

> 
> Also may be worth checking a few user skins; one I found looks like the spin counter is just floating in the middle of nowhere:
> 
> 20210330 134948 (dotnet)
> 
> Not sure if an actual issue, but worth grabbing some top player skins and checking for any weirdness.

All the skins I was testing with looked to work properly, but perhaps I didn't have enough 😛, will examine what's wrong but need a link to the skin you're encountering this on.

For what it's worth, I was testing with these skins in video: https://drive.google.com/file/d/13UQC7W3KXJ4pli1CxbMUhbhYWqVOzRMO/view

**Comment by frenzibyte** [comment]
> I'm not even sure what's wrong with the first screenshot there. Is it the lack of a gap between the spinner and the spm counter?

that's what I'm thinking

**Comment by peppy** [comment]
I guess we can just update the default skin to make it not require a screen edge (or add some kind of border?).

**Comment by peppy** [comment]
For the time being I'm updating the classic skin to no longer anchor against the edge visually. Depending on how people respond to their skins looking weird we can decide how to handle this going forward.

20210412 133458 (dotnet)

@smoogipoo can you confirm you're okay with this direction? In general we haven't been updating the classic skin at all but this feels like the best option here for the time being.

20210412 133720 (dotnet)

**Review by peppy — DISMISSED** [review]
Looks good from a code perspective, pending confirmation on the `osu-resources` change.

**Comment by smoogipoo** [comment]
Sure let's go with this for now.

**Review by smoogipoo — DISMISSED** [review]

**Comment by peppy** [comment]
FWIW @frenzibyte tested 14 skins and only 4 relied on anchoring to the edge (the rest were floating).

**Review by peppy — APPROVED** [review]

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
