### PR TITLE
Implement ProfileSubSection

### PR DESCRIPTION
**Pull request by EVAST9919**
An abstract class for PaginatedContainer. Also will be used for medals and history graph sections in the future

### CODE REVIEW

**Comment by peppy** [comment]
Are there other cases that use the header and missing text? If not, they shouldn't be in the base class.

**Comment by EVAST9919** [comment]
Almost every subsection use header and missing besides "kudosu", "me" and "recent activity". Anyway making a base class without all of that will be better than passing nulls in the ctor

**Comment by EVAST9919** [comment]
Okay, this one is a slightly different solution but it will give us fully controllable different variations (header without missing, missing without header, both, none of them)

**Comment by peppy** [comment]
What's the reason for this in the first place? I mean does something use PaginatedContainer which isn't a profile sub section? If not, why are the classes separated?

**Comment by EVAST9919** [comment]
It's vice versa. In the future there'll be subsections, but without "pagination" logic (by "pagination" I mean having some items in the container and "Show More" button). For example Medals section (have 2 subsections without pagination) and history graphs.

**Comment by EVAST9919** [comment]
To be clear:
- `ProfileSubSection` - Container with Header and Missing text
- 'PaginatedContainer : ProfileSubSection' - uses "pagination logic"
- `containers mentioned before : ProfileSubSection` - do their things without using "pagination logic"

**Comment by peppy** [comment]
please add the above to xmldoc and potentially change naming to better identify where these containers are used. ie. why isn't `PaginatedContainer `a `ProfileSubSection`? or `PaginatedProfileSubSection`? it's completely changed the naming convention.

**Comment by EVAST9919** [comment]
Will be reopened when this will be actually usable

**Pull request closed without merging**
