### PR TITLE
Fix occasional failures on `TestSceneTimelineZoom` due to zoom being transformed over time

### PR DESCRIPTION
**Pull request by peppy**
See
https://teamcity.ppy.sh/buildConfiguration/Osu_Build/1115?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&isReloaded=true&expandBuildTestsSection=true

### CODE REVIEW

**Comment by smoogipoo** [comment]
Am I missing something? Every path down `Zoom_set()` sets `zoomTarget` immediately, which is returned by `Zoom_get()`.

**Comment by peppy** [comment]
https://github.com/ppy/osu/blob/f8830c6850128456266c82de83273204f8b74ac0/osu.Game/Screens/Edit/Compose/Components/Timeline/ZoomableScrollContainer.cs#L101-L115

JetBrains Rider-EAP 2022-06-30 at 08 55 50

**Comment by smoogipoo** [comment]
Yeah I understand that, but both that method and `setZoomTarget()` set `zoomTarget` immediately, which is the value returned by `Zoom_get()`.

**Comment by peppy** [comment]
Not sure then. Must be something else. Can close this if so.

**Comment by smoogipoo** [comment]
Only thing I can imagine is the track isn't loaded yet and it's hitting this thing:
https://github.com/ppy/osu/blob/5a346edc6370b2268efacd9b1464d7adc0368db6/osu.Game/Screens/Edit/Compose/Components/Timeline/Timeline.cs#L143-L155

**Pull request closed without merging**
