### PR TITLE
Fix osu! logo being mispositioned in song select on very wide resolutions

### PR DESCRIPTION
**Pull request by peppy**
| Before | After |
| :---: | :---: |
| CleanShot 2024-01-29 at 11 46 48 | CleanShot 2024-01-29 at 11 46 24 |

### CODE REVIEW

**Review by bdach — DISMISSED** [review]
is it weird that i have been on an ultrawide screen for years now and never noticed

**Comment by bdach** [comment]
Transition into player loader looks broken:

https://github.com/ppy/osu/assets/20418176/a0320a78-913f-483c-a1fe-870e0560c192

Not sure how to fix either.

**Review by bdach — CHANGES_REQUESTED** [review]
^

**Comment by bdach** [comment]
I suppose something like the following works, albeit it's a little cursed...

```diff
diff --git a/osu.Game/Screens/OsuScreen.cs b/osu.Game/Screens/OsuScreen.cs
index f719ef67c9..20ea1c5692 100644
--- a/osu.Game/Screens/OsuScreen.cs
+++ b/osu.Game/Screens/OsuScreen.cs
@@ -255,6 +255,7 @@ protected virtual void LogoArriving(OsuLogo logo, bool resuming)
             logo.RelativePositionAxes = Axes.Both;
             logo.Triangles = true;
             logo.Ripple = true;
+            logo.Margin = new MarginPadding();
         }
 
         private void applyArrivingDefaults(bool isResuming)
diff --git a/osu.Game/Screens/Select/SongSelect.cs b/osu.Game/Screens/Select/SongSelect.cs
index 50467bc089..cc872575d7 100644
--- a/osu.Game/Screens/Select/SongSelect.cs
+++ b/osu.Game/Screens/Select/SongSelect.cs
@@ -642,21 +642,24 @@ protected override void LogoArriving(OsuLogo logo, bool resuming)
         {
             base.LogoArriving(logo, resuming);
 
-            logo.Anchor = Anchor.BottomRight;
-            logo.Origin = Anchor.Centre;
-            logo.RelativePositionAxes = Axes.None;
-
-            Vector2 position = new Vector2(-76, -36);
+            Vector2 position = new Vector2(1);
+            MarginPadding margin = new MarginPadding
+            {
+                Right = 380,
+                Bottom = 180
+            };
 
             if (logo.Alpha > 0.8f)
             {
                 logo.MoveTo(position, 500, Easing.OutQuint);
+                logo.TransformTo(nameof(Margin), margin, 500, Easing.OutQuint);
             }
             else
             {
                 logo.Hide();
                 logo.ScaleTo(0.2f);
                 logo.MoveTo(position);
+                logo.Margin = margin;
             }
 
             logo.FadeIn(logo_transition, Easing.OutQuint);

```

**Comment by peppy** [comment]
I was hoping for something like this, but for whatever reason it doesn't work as it stands...

```diff
diff --git a/osu.Game/Screens/OsuScreen.cs b/osu.Game/Screens/OsuScreen.cs
index f719ef67c9..288e5e2d20 100644
--- a/osu.Game/Screens/OsuScreen.cs
+++ b/osu.Game/Screens/OsuScreen.cs
@@ -248,11 +248,19 @@ public override bool OnExiting(ScreenExitEvent e)
         /// </summary>
         protected virtual void LogoArriving(OsuLogo logo, bool resuming)
         {
+            var centre = logo.ScreenSpaceDrawQuad.Centre;
+
             logo.Action = null;
             logo.FadeOut(300, Easing.OutQuint);
+
+            logo.RelativePositionAxes = Axes.None;
+
             logo.Anchor = Anchor.TopLeft;
             logo.Origin = Anchor.Centre;
+            logo.Position = logo.Parent!.ToLocalSpace(centre);
+
             logo.RelativePositionAxes = Axes.Both;
+
             logo.Triangles = true;
             logo.Ripple = true;
         }

```

**Comment by bdach** [comment]
I mean it appears to work fine _into_ player loader but not entirely fine when _exiting_ back out, and that part is probably due to the `BottomRight` anchor spec no?

**Comment by peppy** [comment]
Yeah, I guess we'd need an API for changing anchor (and maintaining position) if we want to do that.

**Comment by peppy** [comment]
@bdach final attempt:

```diff
diff --git a/osu.Game/Screens/Menu/OsuLogo.cs b/osu.Game/Screens/Menu/OsuLogo.cs
index 25101730e7..f2e2e25fa6 100644
--- a/osu.Game/Screens/Menu/OsuLogo.cs
+++ b/osu.Game/Screens/Menu/OsuLogo.cs
@@ -486,5 +486,12 @@ public void SetupDefaultContainer(Container container)
             defaultProxyTarget.Add(this);
             defaultProxyTarget.Add(proxy = CreateProxy());
         }
+
+        public void ChangeAnchor(Anchor anchor)
+        {
+            var previousAnchor = AnchorPosition;
+            Anchor = anchor;
+            Position -= AnchorPosition - previousAnchor;
+        }
     }
 }
diff --git a/osu.Game/Screens/OsuScreen.cs b/osu.Game/Screens/OsuScreen.cs
index f719ef67c9..2e8f85423d 100644
--- a/osu.Game/Screens/OsuScreen.cs
+++ b/osu.Game/Screens/OsuScreen.cs
@@ -250,9 +250,12 @@ protected virtual void LogoArriving(OsuLogo logo, bool resuming)
         {
             logo.Action = null;
             logo.FadeOut(300, Easing.OutQuint);
-            logo.Anchor = Anchor.TopLeft;
+
             logo.Origin = Anchor.Centre;
+
+            logo.ChangeAnchor(Anchor.TopLeft);
             logo.RelativePositionAxes = Axes.Both;
+
             logo.Triangles = true;
             logo.Ripple = true;
         }
diff --git a/osu.Game/Screens/Select/SongSelect.cs b/osu.Game/Screens/Select/SongSelect.cs
index 50467bc089..a603934a9d 100644
--- a/osu.Game/Screens/Select/SongSelect.cs
+++ b/osu.Game/Screens/Select/SongSelect.cs
@@ -642,9 +642,8 @@ protected override void LogoArriving(OsuLogo logo, bool resuming)
         {
             base.LogoArriving(logo, resuming);
 
-            logo.Anchor = Anchor.BottomRight;
-            logo.Origin = Anchor.Centre;
             logo.RelativePositionAxes = Axes.None;
+            logo.ChangeAnchor(Anchor.BottomRight);
 
             Vector2 position = new Vector2(-76, -36);
 

```

**Comment by bdach** [comment]
Seems solid enough. Have applied patch myself to speed up proceedings.

**Review by bdach — APPROVED** [review]

**Pull request merged**
