### PR TITLE
Fix game crashes due to attempting localisation load for unsupported locales

### LINKED ISSUE #13570: Osu!Lazer opens, but crashes when the game loads
**Describe the bug:** i updated osu!lazer right now, when i opened it, it loaded to the black screen where the message "this game is a work in progress" but it crashes before the message appears

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/81386229/122623166-72276b80-d071-11eb-8143-fc8d17e99daf.mp4

**osu!lazer version:** 2021.619.0

**Logs:**

[database.log](https://github.com/ppy/osu/files/6679598/database.log)
[network.log](https://github.com/ppy/osu/files/6679599/network.log)
[performance.log](https://github.com/ppy/osu/files/6679600/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6679601/runtime.log)

### PR DESCRIPTION
**Pull request by bdach**
Closes #13570.

Tested to boot on the android device I have available. Besides disabling the offending language this pull will also log any errors if this happens with another language in the future.

Might be worth running past a Windows 7/8 machine or VM, since these issues also seem to happen there and I do not have such an environment easily available.

Branch is intentionally rooted at the release tag for ease of testing (realm does not work on android).

### CODE REVIEW

**Comment by CYAinideXDMi** [comment]
I would like to point out that "Tagalog" is not the official language of the Philippines. "Tagalog" refers to either the people or the dialect. The correct name of our language is simply "Filipino".

**Comment by bdach** [comment]
@CYAinideXDMi your point is probably best raised over at https://github.com/ppy/osu-web as that's where the string originally came from.

**Comment by CYAinideXDMi** [comment]
@bdach Noted. May I ask where I might be able to contribute to the translations, while I'm at it?

**Comment by peppy** [comment]
Scroll down on the linked page and read, please. https://github.com/ppy/osu-web#contributing

**Pull request merged**
