### PR TITLE
Add some tests for catch editor blueprints

### PR DESCRIPTION
**Pull request by ekrctb**
- Some tests of placement blueprints are added.
- `TestSceneJuiceStreamSelectionBlueprint` is just for visual inspections, and no actual test steps are there. I'm not sure what can be tested, and the design is currently changing.
- In selection blueprint test scenes, not DHO is added, and `DrawableObject` is `null`.
- Both selection and placement blueprint test scenes use common `CatchEditorTestSceneContainer`, which provide the necessary dependencies (scrolling playfield).

### CODE REVIEW

**Comment by bdach** [comment]
> In selection blueprint test scenes, not DHO is added, and `DrawableObject` is null.

Is there a particular reason why this is the case? Because I'm not sure I agree with most of the changes here related to this point - especially things like null-checks in `HitObjectSelectionBlueprint` that seem to have been added just for this pull, while mania seems to do just fine without such workarounds:

https://github.com/ppy/osu/blob/bd3f8b78ccafc51d8131c5def1443d5e1f9d66f9/osu.Game.Rulesets.Mania.Tests/Editor/TestSceneHoldNoteSelectionBlueprint.cs#L19-L29

**Comment by ekrctb** [comment]
> > In selection blueprint test scenes, not DHO is added, and `DrawableObject` is null.
> 
> Is there a particular reason why this is the case? Because I'm not sure I agree with most of the changes here related to this point - especially things like null-checks in `HitObjectSelectionBlueprint` that seem to have been added just for this pull, while mania seems to do just fine without such workarounds:

With #12782 and #13499, I think the direction is to reduce the dependency of DHO from the blueprint if possible.
The catch selection blueprints are written in a way that doesn't require DHO, it should be tested that it works without DHO.
Thus, the null-conditional operator added <https://github.com/ppy/osu/pull/13823/files#diff-5bdb04b41add627000615486374e163de1fa92613cc5c1cb5168394f90b6529fR24> is not a workaround, but a change towards the direction of not requiring DHOs in selected blueprints. I could split that change, but it is included in this PR because it is only tested by the added test scene.
Also, it reduces the scope, so the test is a test of the blueprint, not a test of DHOs.

**Comment by bdach** [comment]
While it's true that DHOs should not be relied on for layout I'm not sure whether removing them from blueprints entirely is a viable way forward. There are things that cannot be (and arguably should never be) fetched from the hitobject, like the combo/accent colour, which timeline blueprints (which are also selection blueprints) rely on.

The reason I'm hesitant to allow nulls there is that now it gets very fuzzy as to whether the DHO in a selection blueprint is null or not, and half-depends on the ruleset implementation. I'd prefer they get passed in but obsoleted as a property or something, if the direction is indeed to drop them altogether somehow.

**Comment by smoogipoo** [comment]
I do agree with the direction to drop DHOs from blueprints completely.

I also agree with the path taken in this PR, but one thing I'd add is `[CanBeNull]` to `HitObjectSelectionBlueprint.DrawableObject`.

**Comment by ekrctb** [comment]
There is some consideration is needed for `ScreenSpaceSelectionPoint` and `SelectionQuad` to make `DrawableObject` `[CanBeNull]`. Perhaps the properties would be `abstract`, but that would need a separate PR.
I'm thinking this PR as-is is fine because it is not overly committing anything to be out of the scope of this PR (adding tests). If that is unacceptable, I can make DHO present on the selection blueprint test scene.

**Review by smoogipoo — APPROVED** [review]
I think this is fine as-is.

**Pull request merged**
