### PR TITLE
Silence important notifications during first-run setup

### LINKED ISSUE #18449: Opening Notification overlay closes First run setup wizard
### Type

Game behaviour

### Bug description

Opening Notification overlay closes first run setup wizard
This is problem after the game updates. First, the first run setup wizard opens and then you get the changelog notification which opens notification overlay thus closes the first run setup wizard

Its also problem when importing content from stable version using the first setup wizard. Importing from stable opens the notification overlay with progress bar and closes the first run setup wizard

### Screenshots or videos

https://user-images.githubusercontent.com/48604271/170805380-29501031-e766-4b56-9d32-348473341ead.mp4

https://user-images.githubusercontent.com/48604271/170805384-3fc5730d-452b-46c3-bbbd-51751d5a180e.mp4

https://user-images.githubusercontent.com/48604271/170805385-ed25f0cd-3e27-4144-a453-74bb29b9db66.mp4

### Version

2022.523.0-lazer

### Logs

[runtime.log](https://github.com/ppy/osu/files/8790294/runtime.log)
[performance.log](https://github.com/ppy/osu/files/8790295/performance.log)
[network.log](https://github.com/ppy/osu/files/8790296/network.log)

### PR DESCRIPTION
**Pull request by frenzibyte**
- Closes #18449 

Went with the simplest option of resolving the first-run setup overlay via DI and not showing notifications overlay if setup is visible. 

I was initially going for a more general way of blocking all overlays from being open if first-run setup is visible, but not sure that's a good approach UX-wise as it blocks the user from intentionally closing the overlay by opening another one, and `NotificationOverlay` showing itself programmatically on post is kind of a special case that should be handled locally instead.

Also, since opening up notifications overlay on important notifications is an implementation detail of `NotificationOverlay`, I've had to create a `OsuGame`-based test scene with first-run setup open, in order to have test coverage for this behaviour. I think it'll be helpful for future cases as well.

### CODE REVIEW

**Comment by peppy** [comment]
Is there a reason for not using the existing flow of disabling the notification from being posted in the first place (the one already used in gameplay etc.)? The way you've implemented this will create a nuance in UX, as the post occurs but the notification overlay is not shown. I think this also means that after the first run overlay is closed, it won't be shown (while the existing flow guarantees that will happen).

**Comment by peppy** [comment]
Is there a reason for not using the existing flow of disabling the notification from being posted in the first place (the one already used in gameplay etc.)? The way you've implemented this will create a nuance in UX, as the post occurs but the notification overlay is not shown. I think this also means that after the first run overlay is closed, it won't be shown (while the existing flow guarantees that will happen).

**Comment by bdach** [comment]
I'm not sure the overlay activation mode thing is going to help much here. That is used so that screens can suppress showing overlays, but the first run setup *is* an overlay.

That said I have big reservations about having the notification overlay directly access and depend on the first run setup overlay, so I don't really find myself agreeing with any of the code here on a conceptual level.

**Comment by peppy** [comment]
For sure, I wasn't suggesting to use the activation mode, but block the posting in a similar way rather than blocking the display of the overlay.

**Comment by frenzibyte** [comment]
Didn't notice this flow, seems pretty good to use.

**Comment by bdach** [comment]
Test failures look relevant.

**Comment by peppy** [comment]
Not hugely happy with pulling in `FirstRunOverlay` into `NotificationOverlay` but it'll do for now.

I tidied up the DI logic a bit, but looks to work well otherwise 👍 .

**Review by peppy — APPROVED** [review]

**Pull request merged**
