### PR TITLE
Fix slider ticks playing back at infinite rate while making changes to a slider in the editor

### PR DESCRIPTION
**Pull request by peppy**
This is the easiest way I could think of fixing this. The good part is that this should also help with any other blueprints across all rulesets that are hitting a similar issue.

Addresses concerns raised in https://github.com/ppy/osu/discussions/19714.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Not sure I agree with this arbitrary schedule for something named as generic as `UpdateInProgress` from a component as global as `EditorBeatmap`. Maybe that's just me.

Test failure needs attention.

**Comment by peppy** [comment]
An alternative is to move it to `Editor` and make the `UpdateInProgress` just an `UpdateInvoked` action instead.

**Comment by smoogipoo** [comment]
That sounds better, but I wouldn't consider it a requirement for this PR unless others agree.

**Comment by peppy** [comment]
I've moved the debounce flow into `Editor` instead.

As for the test failure, turns out it is quite important... and relies on the `SamplePlaybackDisabled` flag being updated via event flow (in this particular case, from `OnSuspending` during the transition to gameplay, to stop slider track sounds from playing).

I've just restored the original event-based flow for now.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
