### PR TITLE
Fix crashing TestSceneMedalOverlay

### PR DESCRIPTION
**Pull request by EVAST9919**
Also fixes the scale of the medals since they became 2x web-side

### CODE REVIEW

**Comment by peppy** [comment]
Did you test this? It changes the display logic.

**Comment by EVAST9919** [comment]
Not sure which part are you referring to

**Comment by peppy** [comment]
You're allowing the drawable to complete loading before the medal does. The animation starts potentially before the medal is visible, as a result.

**Comment by EVAST9919** [comment]
I pushed a possible fix, but not sure why `Show()` can't be triggered. (Moving `Show()` out of the callback works)

**Comment by peppy** [comment]
`LoadComponentAsync` schedules the callback to self. In your case, self is not present so will not display. I've updated this to work as you'd expect.

**Review by peppy — APPROVED** [review]

**Pull request merged**
