### PR TITLE
Fix calculation of most common beat length for mania scroll speed

### LINKED ISSUE #16406: Broken scroll speed on some osu!mania beatmaps with many timing points
### Discussed in https://github.com/ppy/osu/discussions/16400

<div type='discussions-op-text'>

<sup>Originally posted by **kadoen** January 11, 2022</sup>
I've found some beatmaps where in osu!lazer the scroll speed is much higher than it should be, even though all their BPM changes are normalized and in stable they work fine, with the same scroll speed as other maps. Specifically these:

 - https://osu.ppy.sh/beatmapsets/1581966#mania/3230598
 - https://osu.ppy.sh/beatmapsets/327318#mania/726470
 - https://osu.ppy.sh/beatmapsets/545484#mania/1166680

What these have in common is a large amount of timing points, but I've tried other maps with many timing points (many more than the #3 example) and they work OK. An example of this would be https://osu.ppy.sh/beatmapsets/1592995#mania/3253520.
This phenomenon has also been tested by 2 other people with the same result.</div>

### PR DESCRIPTION
**Pull request by smoogipoo**
Fixes https://github.com/ppy/osu/issues/16406

Tested on beatmaps mentioned in the issue.

### CODE REVIEW

**Comment by peppy** [comment]
Any further reading as to where the issue lay exactly? I'm not 100% familiar with the way this is intended to work. Was the previous code intending to do the same as that helper function but existed before the function did?

**Comment by smoogipoo** [comment]
You'd have to go back to osu-stable for how the code works (`Beatmap.BeatsPerMinuteRange.Z`), but it does calculate the most common BPM. Whereas the code in lazer was calculating the single longest duration, which isn't necessarily the longest section overall.

That being said, hold off on this for a bit since it seems the last beatmap in the issue which was reported to work okay previously, is now broken, and wasn't part of my initial testing (the first 3 beatmaps mentioned).

**Comment by smoogipoo** [comment]
Comment above seems to be a separate issue addressed in https://github.com/ppy/osu/pull/16409. This can go as is.

**Review by bdach — APPROVED** [review]
while i'm a mania layperson, i've checked the maps and the bpm values and things seem to check out

**Review by peppy — APPROVED** [review]

**Pull request merged**
