### PR TITLE
Fix game crash when using "Bubbles" mod on a beatmap with no hit circles

### PR DESCRIPTION
**Pull request by LeaUndercover**
Fixes bubbles mod crashing when no HitCircle is placed in a map like in Issue #24444

First PR tell me if you want me to change anything

### CODE REVIEW

**Comment by frenzibyte** [comment]
Without checking the mod in game, the code looks like it wants `HitCircle`s specifically. Have you checked how it would look in game if it's calculating the radius of a slider or a spinner instead? Video attachment would be good to have.

**Comment by Fabiano1337** [comment]
The Code needs the HitCircle only for its Radius and TimePreempt Attributes, which seem to be the same on a Slider or Spinner.

Here is a comparison from latest (left) to my changes (right)
https://github.com/ppy/osu/assets/28962347/b01e38ed-9510-42bb-a979-f3348a231da9

Also here is a video of what happens if a Spinner is the first Object in a map

https://github.com/ppy/osu/assets/28962347/c45bd4f8-6fc1-4fc5-9e7b-7d4dd325b18a

**Comment by Fabiano1337** [comment]
Closed by accident

**Comment by frenzibyte** [comment]
The videos you attached appear to be corrupted.

**Comment by frenzibyte** [comment]
`Radius` and `TimePreempt` look to be all computed at `ApplyDefaultsToSelf` without any difference between object types, so this looks fine.

**Review by frenzibyte — APPROVED** [review]

**Comment by frenzibyte** [comment]
@Fabiano1337 As a tip for future contributions, avoid opening PRs from the `master` branch. Read [the contributing guidelines](https://github.com/ppy/osu/blob/d18bd2d2acdc32f77ce5cc03d089ed329e91ca17/CONTRIBUTING.md) for more information.

**Pull request merged**
