### PR TITLE
Adjust LN value scaling to bring overrated LN maps more in line

### PR DESCRIPTION
**Pull request by Hydria**
One of the biggest issues that came out of the last fix made towards bringing LNs more in line was that the scaling was too harsh on the formula, causing, as the biggest ranked example, [Duplicity Shade](https://osu.ppy.sh/beatmapsets/1698284#mania/3469849) to fall from 12.04 on nomod to only 11.41 stars on halftime, meaning that an SS on HT was worth the same as ~98.7% on NM.

After some talks with the community about what scaling works best, we finally settled on this smoother formula, also increasing the release_threshold to bring LN maps that are still severely overrated more in line again.

This will affect only LN heavy maps, mainly in the 6+* range, and we've pulled a list of 6+* maps and ran them through NM/DT/HT tests [as shown here](https://docs.google.com/spreadsheets/d/1P0AxfdKvMHwWBQder4ZkFGO1fC9eADSGCryA5-UGriU/edit?usp=sharing) to show the extent of the SR changes being applied.

Duplicity Shade in this example goes from 11.58 NM -> 9.85 HT, a 1.73* difference, up from 0.63*, meaning an SS now matches ~94% acc on a NM run.

The other maps affected in this list are well-known, heavily overrated maps due to their LN abuse. Rice-style maps and actually difficult LN maps are essentially unaffected by this change.

---

SR/PP sheet: https://docs.google.com/spreadsheets/d/1zRlycntHiptir4GtEE5TTqsspTqR1vqVpaSjFS9EVW4/edit#gid=1700775385
As of https://github.com/ppy/osu/pull/24109/commits/7d8cef83e6821c3d1f58d4175a3e551f23f94c90

### CODE REVIEW

**Comment by bdach** [comment]
While I'm not qualified to review this change on merit, I've taken the liberty of editing the title of the PR to omit the problematic beatmap's name. While I understand this change may be intended to fix that one case in particular I'd like to think that we don't hotfix specific maps but rather under- or overrated patterns, and the spreadsheet even shows that (other maps are also affected). So to avoid overfocusing on this one beatmap I think it's better to focus on the bigger problem which is overrated LNs.

**Comment by Hydria** [comment]
That's fine then, my bad.

**Comment by Eve-ning** [comment]
Hello, here's the requested sheet. 

Only maps where SR changed more than +- 0.01 are shown:

|    |   sr_master |   sr_compare |   delta | beatmap                                                                                    |
|---:|------------:|-------------:|--------:|:-------------------------------------------------------------------------------------------|
|  0 |       14.9  |        14.25 |   -0.66 | Gram vs. Camellia - Ragnarok (_Kobii) [The Last Omen // 7K]                                |
|  1 |       11.29 |        10.78 |   -0.51 | Gram vs. Camellia - Ragnarok (_Kobii) [Twilight // Leni's 6K]                              |
|  2 |        8.23 |         7.98 |   -0.26 | xi - Blue Zenith (riunosk) [#0000FF]                                                       |
|  3 |        7.5  |         7.25 |   -0.25 | Camellia - d:for the DELTA (Camellia's "PLANETARY//DUBSTEP" Remix) (Dergo) [c:Culmination] |
|  4 |        6.22 |         6.09 |   -0.13 | xi - Blue Zenith (riunosk) [#0000FF]                                                       |
|  5 |        8.9  |         8.77 |   -0.13 | BlackY - FLOWER -SPRING Long VER.- (Kawawa) [As Flowers Bloom And Fall]                    |
|  6 |        7.26 |         7.14 |   -0.12 | Camellia - Beyond the Geostationary Orbit Level (Leniane) [Equatorial]                     |
|  7 |        7.45 |         7.34 |   -0.12 | FELT - Life [Eris's "a Fate Encounter" mix] ([OSC]Amagai) [4K // Lunatic]                  |
|  8 |        6.08 |         5.97 |   -0.11 | Yunomi - Game Over (feat. TORIENA) (Jakads) [[EX] Insert [1] Coin(s) to Continue . . .]    |
|  9 |        6.67 |         6.56 |   -0.11 | Gram vs. Camellia - Ragnarok (_Kobii) [Twilight // Leni's 6K]                              |
| 10 |        8.33 |         8.23 |   -0.1  | Poppin'Party - KIZUNA MUSIC (Lude) [Crescendo]                                             |
| 11 |        7.83 |         7.73 |   -0.1  | SELEN - Reverse World (Kyousuke-) [Extra: Inverse]                                         |
| 12 |        5.26 |         5.16 |   -0.09 | cillia - FIRST (juankristal) [MX]                                                          |
| 13 |       10.81 |        10.73 |   -0.09 | Gram vs. Camellia - Ragnarok (_Kobii) [The Last Omen // 7K]                                |
| 14 |        5.44 |         5.36 |   -0.08 | Camellia feat. Nanahira - Konran Shoujo Soflan-chan!! (Jakads) [GRAVITY]                   |
| 15 |        9.93 |         9.85 |   -0.07 | Maverick - Shironaga Star Jet -aquamarine mix- (_Kobii) [Cosmic Journey // 7K]             |
| 16 |        6.4  |         6.34 |   -0.07 | kamome sano - starlights feat. TEA (K a b i -) [Moonlight at Dawn // Turrim's 4K]          |
| 17 |        5.57 |         5.51 |   -0.07 | Camellia - d:for the DELTA (Camellia's "PLANETARY//DUBSTEP" Remix) (Dergo) [c:Culmination] |
| 18 |        6.97 |         6.9  |   -0.07 | i_o - Possession (Abraxos) [/I SAID COME ON\]                                              |
| 19 |        9.2  |         9.13 |   -0.07 | Lime - Smiling (Kawawa) [Be Happy]                                                         |
| 20 |        4.76 |         4.7  |   -0.06 | kamome sano - starlights feat. TEA (K a b i -) [Moonlight at Dawn // Turrim's 4K]          |
| 21 |        7.75 |         7.69 |   -0.06 | lapix - Discloze (Extended) (Alternater) [Sevillanas]                                      |
| 22 |        7.22 |         7.16 |   -0.06 | Kobaryo feat. HiTNEX-X - SUPER MEMORIES ([RT]Alleyne) [The Power of Memory]                |
| 23 |        7.62 |         7.57 |   -0.06 | tokiwa - Memoirs feat. Aitsuki Nakuru (_Kobii) [7K Everlasting Memory]                     |
| 24 |        8.2  |         8.14 |   -0.06 | Gram vs. Camellia - Ragnarok (_Kobii) [Twilight // Leni's 6K]                              |
| 25 |        4.68 |         4.62 |   -0.05 | SELEN - Reverse World (Kyousuke-) [Extra: Inverse]                                         |
| 26 |        5.23 |         5.17 |   -0.05 | Camellia - Beyond the Geostationary Orbit Level (Leniane) [Equatorial]                     |
| 27 |        9.34 |         9.29 |   -0.05 | Gram vs. Camellia - Ragnarok (_Kobii) [Cataclysmic Destruction // riunosk's 4K]            |
| 28 |        4.21 |         4.16 |   -0.05 | Camellia - Beyond the Geostationary Orbit Level (Leniane) [Equatorial]                     |
| 29 |        5.05 |         5    |   -0.05 | xi - Blue Zenith (riunosk) [#0000FF]                                                       |
| 30 |        5.8  |         5.75 |   -0.05 | Maverick - Shironaga Star Jet -aquamarine mix- (_Kobii) [Cosmic Journey // 7K]             |
| 31 |        6.08 |         6.03 |   -0.05 | WEAVER - S.O.S. (Asherz007) [6K Udon!]                                                     |
| 32 |        7.64 |         7.59 |   -0.05 | James Landino & Kabuki - Birdsong (_Kobii) [Birbcore]                                      |
| 33 |        6.08 |         6.04 |   -0.04 | Camellia - Newspapers for Magicians (Leniane) [Grimoire for Spells]                        |
| 34 |        6.1  |         6.06 |   -0.04 | Poppin'Party - KIZUNA MUSIC (ATing) [Taisetsu na Uta]                                      |
| 35 |        8.47 |         8.43 |   -0.04 | DJ Genki VS Camellia feat. moimoi - YELL! (Turrim) [Solitude]                              |
| 36 |        8.55 |         8.5  |   -0.04 | Gram vs. Camellia - Ragnarok (_Kobii) [The Last Omen // 7K]                                |
| 37 |        8.16 |         8.12 |   -0.04 | Mastermind(xi+nora2r) - Dreadnought (Kyousuke-) [LordRaika's 7K Onslaught]                 |
| 38 |        5.77 |         5.74 |   -0.04 | SELEN - Reverse World (Kyousuke-) [Extra: Inverse]                                         |
| 39 |        5.52 |         5.49 |   -0.03 | MAZARE - Mazare Party (Insp1r3) [JAKARE's 6K Extra]                                        |
| 40 |        4.94 |         4.91 |   -0.03 | Yunomi - Game Over (feat. TORIENA) (Jakads) [[EX] Insert [1] Coin(s) to Continue . . .]    |
| 41 |        3.9  |         3.88 |   -0.03 | kamome sano - starlights feat. TEA (K a b i -) [Moonlight at Dawn // Turrim's 4K]          |
| 42 |        6.11 |         6.08 |   -0.03 | Minase Inori - Lucky Clover (Amiichii) [Lucky]                                             |
| 43 |        8.08 |         8.05 |   -0.03 | MisoilePunch ~Takenoko Soe~ - Staring at star (Murumoo) [HEAVENLY]                         |
| 44 |        7.08 |         7.05 |   -0.03 | Ice vs. Morimori Atsushi - RE:UNION -Duo Blade Against- (Critical_Star) [KK's Extra]       |
| 45 |        6.22 |         6.2  |   -0.02 | Poppin'Party - KIZUNA MUSIC (Lude) [Crescendo]                                             |
| 46 |        4.53 |         4.5  |   -0.02 | Camellia - d:for the DELTA (Camellia's "PLANETARY//DUBSTEP" Remix) (Dergo) [c:Culmination] |
| 47 |        3.63 |         3.61 |   -0.02 | Endorfin. - Fatalism (_Kobii) [Predestination]                                             |
| 48 |        4.31 |         4.29 |   -0.02 | Camellia feat. Nanahira - Konran Shoujo Soflan-chan!! (Jakads) [EXHAUST]                   |
| 49 |        9.62 |         9.6  |   -0.02 | Ironami - Melty Sweets (_Kobii) [HEAVENLY]                                                 |
| 50 |        5.83 |         5.81 |   -0.02 | Chroma - lost memory (Youwhang) [a light received from you.]                               |
| 51 |        7.15 |         7.13 |   -0.02 | Maverick - Shironaga Star Jet -aquamarine mix- (_Kobii) [Cosmic Journey // 7K]             |
| 52 |        7.36 |         7.34 |   -0.02 | Camellia feat. Nanahira - Konran Shoujo Soflan-chan!! (Jakads) [GRAVITY]                   |
| 53 |        6.21 |         6.19 |   -0.02 | you vs. ETIA. - Shang A Lang (kamome sano Remix) (_Kobii) [Brilliance // 4K]               |
| 54 |        8.13 |         8.11 |   -0.02 | Umeboshi Chazuke - Bison Charge (_Asha) [Ayayaa's Nebula]                                  |
| 55 |        4.37 |         4.36 |   -0.02 | Camellia - Newspapers for Magicians (Leniane) [Grimoire for Spells]                        |
| 56 |        5.16 |         5.15 |   -0.02 | Kobaryo feat. HiTNEX-X - SUPER MEMORIES ([RT]Alleyne) [The Power of Memory]                |
| 57 |        4.52 |         4.5  |   -0.02 | you vs. ETIA. - Shang A Lang (kamome sano Remix) (_Kobii) [Brilliance // 4K]               |
| 58 |        5.99 |         5.98 |   -0.02 | Endorfin. - Fatalism (_Kobii) [Predestination]                                             |
| 59 |        8.79 |         8.78 |   -0.01 | Sakuzyo - Fracture Ray (Kuo Kyoka) [CS' Forbidden Memories]                                |
| 60 |        8.25 |         8.24 |   -0.01 | Yunomi - Game Over (feat. TORIENA) (Jakads) [[EX] Insert [1] Coin(s) to Continue . . .]    |
| 61 |        8.08 |         8.06 |   -0.01 | Sakuzyo feat. Nikki Simmons - Destr0yer (Critical_Star) [Annihilation Nova]                |
| 62 |        4.41 |         4.39 |   -0.01 | Camellia feat. Nanahira - Konran Shoujo Soflan-chan!! (Jakads) [GRAVITY]                   |
| 63 |        6.75 |         6.73 |   -0.01 | Camellia - Quaoar (-MysticEyes) [Celestial]                                                |
| 64 |        6.17 |         6.15 |   -0.01 | Camellia - crystallized (-mint-) [myself, my voice]                                        |
| 65 |        5.38 |         5.37 |   -0.01 | lapix - Kill The Beat (Tofu1222) [juankristal's Ultra Stage]                               |
| 66 |        6.64 |         6.63 |   -0.01 | Lime - Smiling (Kawawa) [Be Happy]                                                         |
| 67 |        6.23 |         6.21 |   -0.01 | penoreri - Lord=Crossight (Aras25) [Shin's 6K EXHAUST]                                     |
| 68 |        5.61 |         5.6  |   -0.01 | penoreri - Prayer (_Kobii) [EXHAUST]                                                       |
| 69 |        3.87 |         3.86 |   -0.01 | cillia - FIRST (juankristal) [MX]                                                          |
| 70 |        5.16 |         5.14 |   -0.01 | Kitauji Quartet - Vivace! (TV Size) (KeppSado) [Kobi's Euphonium]                          |
| 71 |        6.48 |         6.46 |   -0.01 | BilliumMoto - Four Veiled Stars (- Aries -) [Insane]                                       |
| 72 |        7.21 |         7.2  |   -0.01 | OISHII - ONIGIRI FREEWAY (Mentholzzz) [Unagi Onigiri "UHD"]                                |
| 73 |        7.27 |         7.26 |   -0.01 | wa. - Black Lotus (Insp1r3) [Blooming]                                                     |
| 74 |       14.44 |        14.43 |   -0.01 | xi - Last Resort (Kroytz) [Jakads' LASTING LEGACY]                                         |
| 75 |        9.27 |         9.25 |   -0.01 | LeaF - Doppelganger (Jinjin) [Alter Ego]                                                   |

image

**Review by Eve-ning — APPROVED** [review]
lgtm

we had a discussion of integrating another bug fix, but it'll extend the scope too much, and had too many side-effects, so we'll just push this for now.

**Comment by Hydria** [comment]
Converted to draft whilst we look at implementing a small but crucial fix to how LNs are calculated

**Comment by Eve-ning** [comment]
Top 250 most affected maps (Aug 2023 Dataset)

https://gist.github.com/Eve-ning/966eac5e47f844e55fdfd5e6a16fc6fd

**Review by Eve-ning — APPROVED** [review]
LGTM.

I requested the LN fixes for non-deterministic cases to be included as they are logically trivial and have a substantial benefit to balancing maps that are primarily Holds.

This will thus also fix #22756

**Review by Thaumic-Executor — COMMENTED** [review]
okay i am happy to see release threshold bigger lol

**Comment by smoogipoo** [comment]
I've added an SR/PP sheet for this in the OP. Please check it to make sure the values are as expected :)

**Comment by Hydria** [comment]
reviewed by me and few other people ; the changes are looking like pretty much as we hoped for them to do, a couple of normal maps do get hit in the crossfire and some are unfortunately a bit underrated now, but those are minor in comparison to the massive change it makes to overrated maps (now bringing them _a lot_ more in line). from some further investigation as well this seems to bring people's top 50 scores closer by ~14-34% which is nice to see.

overall, approved.

**Review by smoogipoo — APPROVED** [review]

**Comment by Cheshire1922** [comment]
nerfing ln pp but refusing to rank more rice maps that are actually worth something, wild
I have many examples of rice maps being way too hard for their low star rating, which makes them not even appear in my top 100(under 428pp)
revert this lol

**Pull request merged**
