### PR TITLE
Add an interface for leaderboards

### PR DESCRIPTION
**Pull request by frenzibyte**
Used later on for In-game leaderboards, having one type for all types of leaderboards to be exact.

### CODE REVIEW

**Comment by peppy** [comment]
Interfaces need completed xmldoc.

**Comment by peppy** [comment]
Also please explain what this is for. We generally don't just add PRs with single lines containing potential code cruft like this.

**Comment by iiSaLMaN** [comment]
@peppy We need to assign a leaderboard for in-game leaderboard to retrieve scores, top score, and other useful stuff, but we can't define the leaderboard with type `Leaderboard` because it has generic arguments that we don't really know and it differ from multiplayer leaderboard (`Leaderboard<MatchLeaderboardScope, APIRoomScoreInfo>`) to song select leaderboard (`Leaderboard<BeatmapLeaderboardScope, ScoreInfo>`).

**Comment by peppy** [comment]
This doesn’t sound like it’ll work. You’ll still want a base class for the dynamic leaderboard implementation. The way you describe it above sounds like you’re planning on making two separate leaderboards for solo/multi.

**Comment by iiSaLMaN** [comment]
> This doesn’t sound like it’ll work. You’ll still want a base class for the dynamic leaderboard implementation. The way you describe it above sounds like you’re planning on making two separate leaderboards for solo/multi.

I don't think you understood me correctly, This interface is useful for defining a property that we can assign with any types of leaderboard, we can't use `Leaderboard` directly because it needs generic arguments.

**Comment by peppy** [comment]
Okay. Will leave this open until a usage is PR’D separately

**Comment by frenzibyte** [comment]
Closing this PR as stale and unused for the time being.

**Pull request closed without merging**
