### PR TITLE
Add back autosize easing in `SettingsToolboxGroup`

### PR DESCRIPTION
**Pull request by integerrr**
`ExpandingContainers` currently have no expanding animation, which is the result from removing autosize easing in `SettingsToolboxGroup` in #20740 as part of the change to improve song select -> player loader transition. Now that this transition has been further changed (e.g. #21112), I've played around with adding the autosize easing back in and personally it feels ok even on player loader screen.

### CODE REVIEW

**Review by Joehuu — DISMISSED** [review]

**Comment by bdach** [comment]
I dunno about this. It feels like this is reverting an intentional change in how the toolboxes appear on the loader.

Before:

https://user-images.githubusercontent.com/20418176/209876211-88f85bb7-3412-4328-9d1e-5e3a80d70105.mp4

After:

https://user-images.githubusercontent.com/20418176/209876227-116fa134-03b3-4ba3-8115-5c97acf9b4cf.mp4

Note that on the "before" variant there is only vertical movement both on fade in and out. In the "after" variant fade in has both horizontal and vertical movement, but fade out only has vertical.

**Comment by frenzibyte** [comment]
I'm not sure this effect should be toggled only in some places? So toggling toolboxes in other screens after load animates smoothly, while in player loader it changes immediately? That sounds broken. What's wanted here is for the toolbox to not animate when entering the screen, which can be achieved by applying the easing after the toolbox first receives its expanded size.

**Comment by peppy** [comment]
This should not be per usage behaviour. If it's going to be added back, it should be everywhere. But I'm pretty sure I removed it for a reason.

**Comment by bdach** [comment]
Commit that removed the easing is https://github.com/ppy/osu/pull/20740/commits/6b42f1931acf432dcc058298d9520229aeb33a12. Commit message mentions:

> It just feels like unnecessary motion.

which is probably what I was talking about in https://github.com/ppy/osu/pull/21821#issuecomment-1366940348. I think this is a close situation so I'm going to do just that.

**Comment by peppy** [comment]
I believe it was due to the global toolbar contracting while the settings panels were expanding, creating a very weird visual effect.

**Comment by frenzibyte** [comment]
That being said, this really feels weird:

https://user-images.githubusercontent.com/22781491/210170846-b6f41fc3-2a46-498a-93ac-e3382a0ddc79.mp4

It should either not animate at all or always animate but not on initial display (what I touched on in https://github.com/ppy/osu/pull/21821#issuecomment-1368388300).

**Comment by peppy** [comment]
That does look broken, yes.

**Pull request closed without merging**
