### PR TITLE
Fixed a problem that caused an exception when ActiveCountdowns is null

### PR DESCRIPTION
**Pull request by azutake**
Fixed "Value cannot be null" when creating a multiplayer room.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Thanks, but this was an issue with serialisation and fixed in https://github.com/ppy/osu/pull/20236. It [can't actually](https://github.com/ppy/osu/actions/runs/3064295225/jobs/4948328454) be null in normal operation.

**Comment by azutake** [comment]
@smoogipoo Really? I am testing with the latest code but it occurs. Do you reproduce it there?
The way to reproduce it is simple, just create a multiplay room.

**Comment by azutake** [comment]
@smoogipoo Uh, are you saying that this problem will not be resolved until the server side deployment is complete?

**Comment by smoogipoo** [comment]
Correct. You won't be able to use dev builds to play on `osu.ppy.sh`, and the `dev.ppy.sh` server has not yet been updated either.

**Comment by azutake** [comment]
I see, Thank you kindly for sharing!

**Pull request closed without merging**
