### PR TITLE
Fix resume cursor following gameplay cursor scale setting

### LINKED ISSUE #25331: Radius of resume cursor incorrectly changes with "gameplay cursor" setting
### Type

Game behaviour

### Bug description

As in the title, resume cursor window scales with Gameplay Cursor size.

### Screenshots or videos

cursor at 0.1x size, closest to resume window
image
cursor at 2.0x size, closest to resume window 
image
(excat size of cursor in 1:1 ratio between the sizes)

### Version

2023.1026.0-lazer

### Logs

-

### PR DESCRIPTION
**Pull request by frenzibyte**
- Closes https://github.com/ppy/osu/issues/25331

I was going to write a test case for this but I've had spent too much time trying to figure out how to logically get the size of a drawable at 1x scale without getting into technical details (like fetching the container that's actually being scaled), so I gave up on it.

### CODE REVIEW

**Comment by peppy** [comment]
Obvious from the diff, but this breaks visuals:

2023-11-06 12 34 49@2x


I would only expect the hit area to change, not the visual, I think?

**Review by peppy — COMMENTED** [review]
As commented

**Comment by frenzibyte** [comment]
> Obvious from the diff, but this breaks visuals:
> 
> 2023-11-06 12 34 49@2x
> 
> I would only expect the hit area to change, not the visual, I think?

It seems I misunderstood the intention of that issue thread. I was looking at it with stable in mind, which the resume cursor there stays visually at 1x.

**Comment by peppy** [comment]
I'm not sure which makes more sense, would wait for more opinions. To me having two different cursor sizes looks very weird.

**Comment by bdach** [comment]
Tend to agree with @peppy here.

**Comment by peppy** [comment]
I added test coverage of this that was missing.

**Review by peppy — APPROVED** [review]

**Pull request merged**
