### PR TITLE
Add github actions workflow for diffcalc consistency checks

### PR DESCRIPTION
**Pull request by smoogipoo**
This is a new workflow as part of my ongoing work to streamline the diffcalc PR review process.

- Listens for `!pp check [id]` by repository members in new pull request comments.
- Fetches latest beatmaps + data from https://data.ppy.sh.
    - Note: Currently broken due to an issue with the latest dumps that I've reported to @peppy. It will start working again after new dumps are made.
- Runs [osu-difficulty-calculator](https://github.com/ppy/osu-difficulty-calculator) on both master and the PR.
- Generates a resulting table containing SR differences > 0.1

Example run: https://github.com/smoogipoo/osu/actions/runs/1197759722
Blocking PR until the run completes.

### CODE REVIEW

**Comment by smoogipoo** [comment]
I've tried filtering this per-ruleset (e.g. `!pp check 1`), but it doesn't seem straight-forward to do this with GH actions other that by failing the other jobs. I can add that if requested, but it's probably fine doing all rulesets for the time being?

**Comment by bdach** [comment]
Steps can also run conditionally. You could try copying/moving the comment check to the inner step which should already have received the matrix variable, and check if the comment specifies a given ruleset?

**Comment by smoogipoo** [comment]
Doesn't that require the step to fail the job? Unless I add it to every step?

**Comment by bdach** [comment]
I guess... Another thing to try could be maybe seeing if the matrix spec can read variables/expressions and glue the ruleset IDs from that somehow...

**Comment by smoogipoo** [comment]
Added back the check, just as failing the entire job: https://github.com/smoogipoo/osu/actions/runs/1197759722

**Comment by LittleEndu** [comment]
But can't you return 0 (or have it be successful some other way) so it is all green? Makes more sense for a step that doesn't need to run to always be successful

**Comment by bdach** [comment]
It has to short circuit the job. Which it won't do if it succeeds.

Cancelling somehow would be an alternative but I can't see how that could be achieved.

**Comment by bdach** [comment]
Is there an example where the 'print diffs' step actually prints anything? I can't see any output in the linked example in the OP, and I would have liked to have a look at what that output looks like.

**Comment by smoogipoo** [comment]
I've started another run here: https://github.com/smoogipoo/osu/actions/runs/1205154023 which should generate differences.

**Comment by bdach** [comment]
Checked it out, looks alright. The raw output maybe isn't overly friendly but pasting to something like libreoffice works well enough.

I think this is in a good enough state to get in. My remaining comments are minor enough that they can be iterated on later.

**Review by bdach — DISMISSED** [review]

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
@smoogipoo is this good to go? i can't see any issues with it if so.

**Comment by smoogipoo** [comment]
Yes, it's good togo.

**Pull request merged**
