### PR TITLE
Improve missing beatmap failure logging on score import

### LINKED ISSUE #21910: Insufficient logging on importing scores without associated beatmaps
### Type

Other

### Bug description

If an imported score has no associated beatmap an error will appear but there are no further details in the logs.
 
---

runtime.log:
```
2022-12-28 23:19:30 [verbose]: ⚠️ No corresponding beatmap for the score could be found.
2022-12-28 23:19:40 [verbose]: ⚠️ No corresponding beatmap for the score could be found.
2022-12-28 23:19:50 [verbose]: ⚠️ No corresponding beatmap for the score could be found.
```

database.log:
```
2022-12-28 23:19:28 [verbose]: [cedd6] Beginning import from 4441e76267524c0f2ed64b02251c4ada-133133587393591863.osr...
2022-12-28 23:19:28 [verbose]: [cedd6] Import successfully completed!
2022-12-28 23:19:28 [verbose]: [4a23a] Found existing (optimised) score for Cheery Pattern playing DZIDZIO - Yalta (wajinshu) [YOSHIKAWA HOSHI's Insane] (ID 2f770f3c-73ad-492c-a098-8cdd9ac3a8de) – skipping import.
2022-12-28 23:19:28 [verbose]: [33cc7] Found existing (optimised) score for Cheery Pattern playing DZIDZIO - Yalta (wajinshu) [YOSHIKAWA HOSHI's Insane] (ID 6a9028cc-4dc5-496a-a078-c0b47a369386) – skipping import.
2022-12-28 23:19:28 [verbose]: [b1f67] Found existing (optimised) score for Cheery Pattern playing DZIDZIO - Yalta (wajinshu) [YOSHIKAWA HOSHI's Insane] (ID a9240a74-758e-4c19-b896-7c7f03da1074) – skipping import.
2022-12-28 23:19:28 [verbose]: [c3732] Found existing (optimised) score for Cheery Pattern playing DZIDZIO - Yalta (wajinshu) [YOSHIKAWA HOSHI's Insane] (ID 5c73afad-b6ca-4c51-bcf1-e49fa180a2a5) – skipping import.
2022-12-28 23:19:28 [verbose]: [69b9f] Found existing (optimised) score for Cheery Pattern playing DZIDZIO - Yalta (wajinshu) [YOSHIKAWA HOSHI's Insane] (ID 723bb65d-64cf-43ae-90f6-5302bf97876e) – skipping import.
2022-12-28 23:19:29 [verbose]: [d1a64] Found existing (optimised) score for Cheery Pattern playing Lite Show Magic (t+pazolite vs C-Show) - Crack Traxxxx (Fatfan Kolek) [Dariano's Normal] (ID 8ca9d8e5-e496-49d6-b069-b9e20d49c1dd) – skipping import.
2022-12-28 23:19:29 [verbose]: [ed8fa] Found existing (optimised) score for Cheery Pattern playing Lite Show Magic (t+pazolite vs C-Show) - Crack Traxxxx (Fatfan Kolek) [Dariano's Normal] (ID ad6cb020-b8fb-44ad-8d0b-32c36c9f79b7) – skipping import.
2022-12-28 23:19:29 [verbose]: [eb2ca] Found existing (optimised) score for Cheery Pattern playing Lite Show Magic (t+pazolite vs C-Show) - Crack Traxxxx (Fatfan Kolek) [Dariano's Normal] (ID 9c7a2c64-05e3-4c62-bec4-5d9c573a0adb) – skipping import.
2022-12-28 23:19:29 [verbose]: [ac8e4] Found existing (optimised) score for Cheery Pattern playing Lite Show Magic (t+pazolite vs C-Show) - Crack Traxxxx (Fatfan Kolek) [Dariano's Normal] (ID 17a6d137-395f-4e0b-8501-b734b7d6e4d3) – skipping import.
2022-12-28 23:19:29 [verbose]: [bbf75] Found existing (optimised) score for Cheery Pattern playing BiSH - HiDE the BLUE (Nao Tomori) [Laura's Insane] (ID 1189b916-df12-4f0c-86e1-724f161a2baf) – skipping import.
2022-12-28 23:19:29 [verbose]: [2d88f] Found existing (optimised) score for Cheery Pattern playing BiSH - HiDE the BLUE (Nao Tomori) [Laura's Insane] (ID 0052a394-8675-421a-8b32-12908dc59b86) – skipping import.
2022-12-28 23:19:29 [verbose]: [5495e] Found existing (optimised) score for Cheery Pattern playing BiSH - HiDE the BLUE (Nao Tomori) [Laura's Insane] (ID faeba31d-573d-40cc-9111-4f0713ac03dc) – skipping import.
2022-12-28 23:19:29 [verbose]: [6fa16] Found existing (optimised) score for Cheery Pattern playing BiSH - HiDE the BLUE (Nao Tomori) [Laura's Insane] (ID f82d0bfc-1fb7-49b0-a349-4b950018fc48) – skipping import.
2022-12-28 23:19:29 [verbose]: [6ed4a] Found existing (optimised) score for Cheery Pattern playing BiSH - HiDE the BLUE (Nao Tomori) [Laura's Insane] (ID 81516f6b-bcaa-4afd-8d75-42622afbe670) – skipping import.
2022-12-28 23:19:30 [verbose]: [6dbc1] Found existing (optimised) score for Cheery Pattern playing toby fox - Uwa!! So HEATS!! (GanyuMyMommy) [futsuu] (ID cc1a76c5-7aab-47ca-bc03-c978e170ca82) – skipping import.
2022-12-28 23:19:30 [verbose]: [30599] Found existing (optimised) score for Cheery Pattern playing saradisk - 210 - Maikaze (Nozhomi) [Destroyer] (ID 92fb42fb-db65-429b-886e-96de85d83fb7) – skipping import.
2022-12-28 23:19:30 [verbose]: [94211] Beginning import from 44a6083528f8cfb339e003f0493bf06e-133074802709694306.osr...
2022-12-28 23:19:30 [verbose]: [94211] Import successfully completed!
2022-12-28 23:19:30 [verbose]: [57bd5] Beginning import from 44ae2bb17164926b7b1e62f2f709cb3e-132974038833054994.osr...
2022-12-28 23:19:31 [verbose]: [57bd5] Import successfully completed!
2022-12-28 23:19:31 [verbose]: [577c2] Found existing (optimised) score for Cheery Pattern playing Hanasaka Yui(CV: M.A.O) - Harumachi Clover (KuranteMelodii) [Halation] (ID 85ff39a4-7ca7-4b16-b9b1-d0d426fd0325) – skipping import.
2022-12-28 23:19:34 [verbose]: [69292] Found existing (optimised) score for Cheery Pattern playing Hanasaka Yui(CV: M.A.O) - Harumachi Clover (KuranteMelodii) [Halation] (ID d93e2ea6-18be-4be2-a05b-bd241a58c37e) – skipping import.
2022-12-28 23:19:34 [verbose]: [34db0] Found existing (optimised) score for Cheery Pattern playing Hanasaka Yui(CV: M.A.O) - Harumachi Clover (KuranteMelodii) [Halation] (ID 5d53be54-8f8d-42df-989e-de53d7363b2f) – skipping import.
2022-12-28 23:19:34 [verbose]: [e8e59] Found existing (optimised) score for Cheery Pattern playing Hanasaka Yui(CV: M.A.O) - Harumachi Clover (KuranteMelodii) [Halation] (ID c465d017-cf06-4cf3-bc5d-70b6e1eb682a) – skipping import.
2022-12-28 23:19:34 [verbose]: [f9214] Found existing (optimised) score for Cheery Pattern playing SawanoHiroyuki[nZk]:mizuki - aLIEz (TV size) (xxdeathx) [Desperate's Normal+] (ID 1f5293ee-1d24-4ba5-911f-e9a6a97faced) – skipping import.
2022-12-28 23:19:34 [verbose]: [8737d] Found existing (optimised) score for Cheery Pattern playing Toby Fox - Dialtone (mrowswares) [[[osu!]] [[CS0]] NORMAL] (ID 5d71d591-2ec9-4426-99ac-f47c2a18ae1d) – skipping import.
2022-12-28 23:19:34 [verbose]: [6c0e3] Found existing (optimised) score for Cheery Pattern playing DOES - Guren (Kagetsu) [Kage] (ID fe6efab6-3afd-452e-9e4d-a6b1b19e85a6) – skipping import.
2022-12-28 23:19:34 [verbose]: [4d685] Found existing (optimised) score for Cheery Pattern playing DOES - Guren (Kagetsu) [Kage] (ID 77894df5-d506-480b-9b39-1f3f8fc340b5) – skipping import.
2022-12-28 23:19:34 [verbose]: [8e768] Found existing (optimised) score for Cheery Pattern playing DOES - Guren (Kagetsu) [Kage] (ID 170ac908-e298-4227-baaf-345bac807656) – skipping import.
2022-12-28 23:19:34 [verbose]: [8d483] Found existing (optimised) score for Cheery Pattern playing Nakanomori Ayako - Get the glory (TV Size) (xandeez nuts) [PotatoDew's Insane] (ID 1e7734db-c5f5-4f3a-8bcb-14672dc728c6) – skipping import.
2022-12-28 23:19:35 [verbose]: [7a546] Found existing (optimised) score for Cheery Pattern playing Cass2 - Gravity Falls Theme Song- 16 Bit Mix (Venix) [Alphabet's Insane] (ID ff19c659-3cbe-4540-bc18-d30abaef73f0) – skipping import.
2022-12-28 23:19:37 [verbose]: [5af27] Found existing (optimised) score for Cheery Pattern playing Cass2 - Gravity Falls Theme Song- 16 Bit Mix (Venix) [Alphabet's Insane] (ID 352eff69-d5e1-4081-bc2f-c28cd47e8f57) – skipping import.
2022-12-28 23:19:38 [verbose]: [ee7cf] Found existing (optimised) score for Cheery Pattern playing Cass2 - Gravity Falls Theme Song- 16 Bit Mix (Venix) [Alphabet's Insane] (ID d87773ca-b902-4c41-ab73-0bc87ba5db21) – skipping import.
2022-12-28 23:19:40 [verbose]: [db9e6] Found existing (optimised) score for Cheery Pattern playing Cass2 - Gravity Falls Theme Song- 16 Bit Mix (Venix) [Alphabet's Insane] (ID 2451113f-e8de-4b59-a6a9-651e02a14229) – skipping import.
2022-12-28 23:19:40 [verbose]: [071a5] Found existing (optimised) score for Cheery Pattern playing Cass2 - Gravity Falls Theme Song- 16 Bit Mix (Venix) [Alphabet's Insane] (ID ff30abe4-9b54-45bf-99bd-8d86852f9baf) – skipping import.
2022-12-28 23:19:40 [verbose]: [fb37b] Found existing (optimised) score for Cheery Pattern playing Cass2 - Gravity Falls Theme Song- 16 Bit Mix (Venix) [Alphabet's Insane] (ID e9eafa1e-e3d6-4ba8-bc6c-933c3084a12b) – skipping import.
2022-12-28 23:19:40 [verbose]: [73e32] Found existing (optimised) score for Cheery Pattern playing Cass2 - Gravity Falls Theme Song- 16 Bit Mix (Venix) [Alphabet's Insane] (ID 1936d247-143e-448a-aca9-0fd43a6a4ed8) – skipping import.
2022-12-28 23:19:41 [verbose]: [dcfe6] Found existing (optimised) score for Cheery Pattern playing Cass2 - Gravity Falls Theme Song- 16 Bit Mix (Venix) [Alphabet's Insane] (ID 9f1e673a-5c57-4cdb-9094-e37c42e0c15f) – skipping import.
2022-12-28 23:19:41 [verbose]: [3876e] Found existing (optimised) score for Cheery Pattern playing Cass2 - Gravity Falls Theme Song- 16 Bit Mix (Venix) [Alphabet's Insane] (ID 2287e8d1-f343-4e5d-b5cd-b331ecdd5285) – skipping import.
2022-12-28 23:19:41 [verbose]: [d88fa] Found existing (optimised) score for Cheery Pattern playing Cass2 - Gravity Falls Theme Song- 16 Bit Mix (Venix) [Alphabet's Insane] (ID c49ce37e-22e2-4fdf-a299-3e7fe85a72c6) – skipping import.
2022-12-28 23:19:41 [verbose]: [48b4a] Found existing (optimised) score for Cheery Pattern playing Cass2 - Gravity Falls Theme Song- 16 Bit Mix (Venix) [Alphabet's Insane] (ID bed3e41e-1e90-451a-8b50-4b1c4fe766c8) – skipping import.
2022-12-28 23:19:41 [verbose]: [7e726] Found existing (optimised) score for Cheery Pattern playing Cass2 - Gravity Falls Theme Song- 16 Bit Mix (Venix) [Alphabet's Insane] (ID 91111990-9b3b-4f39-83d9-95f0d15a1c39) – skipping import.
2022-12-28 23:19:41 [verbose]: [1ff34] Found existing (optimised) score for Cheery Pattern playing Apocalyptica - Hall of the Mountain King (pishifat) [Insane] (ID 7cf296fe-102f-43d6-8c64-f088404a01ac) – skipping import.
2022-12-28 23:19:41 [verbose]: [d95aa] Beginning import from 44f052585d12f3ff39807dc41e7f7252-132964763474234045.osr...
2022-12-28 23:19:42 [verbose]: [d95aa] Import successfully completed!
2022-12-28 23:19:42 [verbose]: [f0474] Found existing (optimised) score for Cheery Pattern playing ViViD - HIKARI (TV Size) (Log Off Now) [browiec's Hyper] (ID adcb0633-2377-4914-80ac-fb038e5da5c7) – skipping import.
2022-12-28 23:19:42 [verbose]: [f1aa4] Found existing (optimised) score for Cheery Pattern playing ViViD - HIKARI (TV Size) (Log Off Now) [browiec's Hyper] (ID d045cc7a-5a66-4ec8-a38a-837f1620230c) – skipping import.
2022-12-28 23:19:42 [verbose]: [7a45e] Found existing (optimised) score for Cheery Pattern playing ViViD - HIKARI (TV Size) (Log Off Now) [browiec's Hyper] (ID 903ffb8e-6ef8-4985-909a-6fe775260567) – skipping import.
2022-12-28 23:19:42 [verbose]: [fc151] Found existing (optimised) score for Cheery Pattern playing ViViD - HIKARI (TV Size) (Log Off Now) [browiec's Hyper] (ID 3e7dabe4-fb07-46ed-9937-b07eed6adcb0) – skipping import.
2022-12-28 23:19:43 [verbose]: [04e69] Found existing (optimised) score for Cheery Pattern playing Hatsuki Yura - Drivi'n greedy - Nhato Remix - (Kamio Misuzu) [Moon] (ID 8dec1276-f666-4c8f-9677-1e5bdd4701e4) – skipping import.
2022-12-28 23:19:43 [verbose]: [a7b7a] Found existing (optimised) score for Cheery Pattern playing I love you Orchestra - Coconut Love (eiri-) [Expert] (ID e06a6713-cb78-4d20-966c-7b2f1f94cc89) – skipping import.
```

### Screenshots or videos

image

### Version

2022.1228.0-lazer

### Logs

[updater.log](https://github.com/ppy/osu/files/10316871/updater.log)
[performance.log](https://github.com/ppy/osu/files/10316873/performance.log)
[database.log](https://github.com/ppy/osu/files/10316880/database.log)
[network.log](https://github.com/ppy/osu/files/10316881/network.log)
[Uploading runtime.log…]()

### PR DESCRIPTION
**Pull request by frenzibyte**
- Closes #21910 

As per https://github.com/ppy/osu/issues/21910#issuecomment-1375176456. Not 100% sure on the approach I took here (verbose database log + error information log). I initially thought about replacing the error information log with manual notification posting, but that doesn't get limited after hitting a certain count like logging does when forwarded as notifications, so it breaks the game when too many scores don't have the beatmap present.

### CODE REVIEW

**Comment by peppy** [comment]
osu! 2023-01-10 at 03 36 53

I don't think this is helpful to a user at all, and less friendly than what was already there.

If you're insisting on changing the messaging to the user, it should be only displaying one notification after a stable import if there were any missing scores: "x scores could not be imported as the relevant beatmap was not found".

**Comment by frenzibyte** [comment]
The "hash" filename was supposed to be the name of the accessible score file the user can check through in stable folder to check out why it's failing (and shouldn't be a hash in the case of  properly-named score file import), but if you don't find it as an improvement to the user at all, I'll look into your proposed behavior.

**Comment by peppy** [comment]
I don't think anyone is going to use that to do anything, no.

**Comment by frenzibyte** [comment]
I've updated the realm importer to display as you proposed:

CleanShot 2023-01-10 at 13 31 01

Feels more informative now at least, I'm fine with it. We could also add "check logs for more info" at the end of the message, but I think it's already obvious.

**Review by peppy — APPROVED** [review]

**Pull request merged**
