### PR TITLE
Use OnlineViewContainer for BeatmapDetails

### LINKED ISSUE #11910: Beatmap details preview is stuck in loading when offline
**Describe the bug:** 
Beatmap details preview is stuck in loading when offline
**Screenshots or videos showing encountered issue:** 
osu_2021-02-26_19-32-58
**osu!lazer version:** 
2021.220.0
**Logs:**
not useful here

### PR DESCRIPTION
**Pull request by PercyDan54**
Fixes #11910

I'm stuck at positioning when moved ratings and failRetry into one container, so I kept them in their original containers. But ratings will be hidden when offline

### CODE REVIEW

**Comment by bdach** [comment]
Kind of an ill-mannered move to just PR this with no notice given someone was already working on it.

**Comment by PercyDan54** [comment]
> Kind of an ill-mannered move to just PR this with no notice given someone was already working on it.

Sorry I didn't know someone else is working on it, so what should I do next? mention him?

**Comment by bdach** [comment]
> Sorry I didn't know someone else is working on it

...How is this possible? Did you not read the issue thread, which you opened and then linked to this PR, at all?

@owen-young heads up that you've been pre-empted, unfortunately, although I haven't yet looked at the diff to be able to tell whether this is up to standard.

**Comment by owen-young** [comment]
Thanks for the heads-up. I'll keep an eye on this PR and if it gets accepted, I will cease work on my branch.

**Comment by peppy** [comment]
I've done some refactors to the point that this is completely new code. @smoogipoo requesting re-review.

**Comment by smoogipoo** [comment]
Is this a precursor PR?
image

There's still a huge loading spinner over the entire content, and actually overflows the content a bit causing that background stacking effect.

**Comment by peppy** [comment]
Yep, that's intentional, as that's used for reloading content (has always been that way). Can probably be improved at a later stage. Not sure about the padding though, can look at that if you aren't already.

**Comment by peppy** [comment]
Have resolved the padding issue.

**Comment by smoogipoo** [comment]
Yeah I get that it's always been that way, but I thought this PR was supposed to fix that. As it is it doesn't really fix the PR mentioned in the OP does it?

And just so we're on the same page - it's always visible while not logged in.

**Comment by peppy** [comment]
20210406 171046 (dotnet)

This is what you should be seeing when not logged in

**Comment by smoogipoo** [comment]
What I posted in the screenshot above is all that I'm seeing... I can tell it's partly working because I have the placeholder text, but also have the big spinner.

**Comment by peppy** [comment]
Have added a missing check which may have caused it to become visible when it shouldn't be (on changing beatmaps to one with an online ID while offline).

**Comment by smoogipoo** [comment]
Cool, that did it.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
