### PR TITLE
Add playlist length to match settings overlay

### LINKED ISSUE #11002: Multiplayer playlist can be longer than lobby duration
**osu!lazer version:** 2020.1128.0

### PR DESCRIPTION
**Pull request by smoogipoo**
Fixes https://github.com/ppy/osu/issues/11002 ?

Various displays at different lengths:
Screenshot_2020-12-01_19-59-08

Screenshot_2020-12-01_19-59-20

Screenshot_2020-12-01_19-59-34

### CODE REVIEW

**Comment by bdach** [comment]
Rate-changing mods don't affect the runtime while they probably should, but that's an issue that we have all over the place so I wouldn't necessarily hold up this PR for that as having this is better than nothing. Adjusting the runtime to mods can happen as part of #10580 or something.

**Review by bdach — DISMISSED** [review]

**Review by peppy — DISMISSED** [review]

**Comment by peppy** [comment]
@smoogipoo I've added this display to the room screen as well. This required a slight change to the osu-web transformer, which should be deployed today. Please sanity check code changes.

**Comment by peppy** [comment]
Is deployed now

image

**Comment by smoogipoo** [comment]
Can also be added to the room inspector in the listing. I'll do it.

**Review by peppy — DISMISSED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
