### PR TITLE
Fix editor seeks on a precision scroll device being too fast when track is playing

### LINKED ISSUE #23155: scrolling in the editor is much faster while the song is unpaused, compared to paused
### Type

Game behaviour

### Bug description

I am using a freescroll mouse; if I use freescroll, then pause/unpause the editor, the speed of scrolling varies greatly. I don't know what the 'correct' behaviour here would be, but I believe the existing behaviour is incorrect.

### Screenshots or videos

[HEADPHONE WARNING](https://youtu.be/bpqmz-jKj4M)

### Version

2023.403.1-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/11180708/network.log)
[performance.log](https://github.com/ppy/osu/files/11180709/performance.log)
[runtime.log](https://github.com/ppy/osu/files/11180710/runtime.log)
[updater.log](https://github.com/ppy/osu/files/11180711/updater.log)
[database.log](https://github.com/ppy/osu/files/11180712/database.log)
[input.log](https://github.com/ppy/osu/files/11180713/input.log)

### PR DESCRIPTION
**Pull request by peppy**
Closes https://github.com/ppy/osu/issues/23155.

### CODE REVIEW

**Comment by bdach** [comment]
I'm not really sure how to test this because I don't own any "precise scrolling" devices. It seems to be mostly a macOS thing as far as I can tell, because I have a free scrolling mouse and it is not being treated as "precise" by windows. I don't even know if *anything* can be precise on windows as we have things (as per https://github.com/ppy/osu-framework/pull/5186#issuecomment-1132064369), so I don't know if this pull fixes the issue reporter's problem, either.

**Comment by peppy** [comment]
Completely forgot that we aren't properly detecting this on windows. Kind of unfortunate that microsoft dropped the ball with offering a proper API for it (I do wonder how other apps manage).

So I guess we either:
- Go with the fix in the PR and wait for that situation to possibly improve at some point in the future, or never.
- Implement a local fix, for instance looking for non-integer `ScrollDelta`s and handling differently locally.

Opinions on this?

**Comment by bdach** [comment]
I don't think fixing locally is a good idea, personally. Probably would just go with this if it works okay on mac and call it a day for now.

**Comment by peppy** [comment]
I'll double check tonight as I haven't tested this, but I imagine it will work.

**Comment by peppy** [comment]
While this does work, I'm not sure it feels good. The better answer may be to reduce the seek multiplier or only apply it to backwards seeks (to offset the forwards playback of the track making it very hard to seek backwards).

Will double-check stable. I think it only applies to backwards and if so we should do the same here, for all kinds of scroll and not just precision.

**Comment by peppy** [comment]
Stable applies in both directions, and I think it makes sense to. The inline comment in lazer's code explains why we do this. I don't think tweaking further without more feedback is required. Usually you're not toggling pause while seeking in the way the user did to notice this behaviour, and without doing so, seeking feels natural enough in both cases.

**Pull request closed without merging**
