### PR TITLE
Fix crash when resetting offset after a play with no hit events

### LINKED ISSUE #30573: Crash when resetting offset
### Type

Crash to desktop

### Bug description

Was trying to reset the offset for a beatmap when the game crashed.
Tried to reproduce but I have no idea what I specifically did to cause the crash.

### Screenshots or videos

_No response_

### Version

2024.1009.1.0

### Logs

[1731189581.runtime.log](https://github.com/user-attachments/files/17689846/1731189581.runtime.log)

### PR DESCRIPTION
**Pull request by peppy**
Closes https://github.com/ppy/osu/issues/30573.

### CODE REVIEW

**Comment by frenzibyte** [comment]
Coming from https://github.com/ppy/osu/issues/30573#issuecomment-2475734368, I think it would be a better fix if the beatmap offset control makes sure the graph won't actually possibly receive less than 10 hit events and display the "play is too short" message.

Right now it doesn't do so for the specific case I mentioned in the comment: A slider at the beginning of a beatmap with such a slow velocity that makes it generate more than 10 ticks, and is played with classic mod enabled. Instead, it shows this broken graph:

CleanShot 2024-11-14 at 03 45 33

**Comment by peppy** [comment]
Sure, that seems like a valid fix in addition to what is here, not replacing it.

**Comment by peppy** [comment]
Looking into this further, I believe the extra fix is out of scope and should be handled separately. It's weird and I don't want to spend the time on it right now, as I'll need to re-learn hitobjects and stuff.

**Review by bdach — APPROVED** [review]
Now that the circumstances of this are actually understood, I'm fine merging this (but will look into follow-up changes related to the conversation above).

**Pull request merged**
