### PR TITLE
Show editor file choosers in a popover rather than inline

### LINKED ISSUE #14367: File select dialog in editor can only be closed by selecting a file
**Describe the bug:** 
In the setup page of the editor, when expanding a file select dialog (Background/Audio Track), that dialog can't be collapsed without selecting a file. I was expecting clicking the button that expands the dialog a second time to close it again.

**Screenshots or videos showing encountered issue:** 
https://streamable.com/ogkrxf

**osu!lazer version:** 
2021.809.0-lazer

**Logs:**
n/a

### PR DESCRIPTION
**Pull request by peppy**
Supersedes and closes #14370.
Closes #14367.

There's some issues with display, but that goes for all popovers at the moment, and will be resolved by localising the `PopoverContainer`s. This can come as a separate step I think.

https://user-images.githubusercontent.com/191335/130422688-cb1dc498-d3d7-4e43-a3b8-4cf83ff6f92a.mp4

### CODE REVIEW

**Comment by frenzibyte** [comment]
I've pushed a relatively small change to make the popover hide on file selection, following the same behaviour as previously.

**Review by frenzibyte — APPROVED** [review]
Hesitant to merge this with the current layout issues (although they come from popovers in general and the same applies to the colour picker), so I'll leave an approval.

**Comment by bdach** [comment]
> I've pushed a relatively small change to make the popover hide on file selection, following the same behaviour as previously.

That's not the only thing that last change does, though? Some containers look to also have been removed. While it may be fine to do this as they seem to no longer be necessary, I think that should have also been mentioned.

**Comment by frenzibyte** [comment]
It's a matter of cleanup from the fact that there are no usages of `Target`, but sure, could've gone for just removing the container only without the containing flow.

**Comment by bdach** [comment]
I would have split that off to a separate commit (and mentioned that I removed them), but whatever. Seems to be a good change anyhow.

**Comment by bdach** [comment]
Just going to note that with the file chooser being narrower now the breadcrumb control gets clipped more often:

2021-08-23-181245_861x116_scrot

But that's a shortcoming of the framework control rather than this pull, so I'm looking away for now. It probably needs a horizontal scroll above the breadcrumb fill flow. Rest looks fine for now.

**Review by bdach — APPROVED** [review]

**Pull request merged**
