### PR TITLE
Remove extra commas in vscode build configuration

### PR DESCRIPTION
**Pull request by johnneijzen**
Make launch.json a valid JSON file

### CODE REVIEW

**Comment by peppy** [comment]
Hmm, for me it works even with the commas. Does it happen to not work at your end?

**Comment by johnneijzen** [comment]
it works even with extra commas. I was just making sure it follows JSON standard because some code reviewer programs and JSON validator were giving me a warning. if you wondering about standard here: http://www.json.org/

**Comment by peppy** [comment]
vscode config files also support inline comments which is against spec. not sure we should be caring too much, though.

**Comment by johnneijzen** [comment]
It's your choice.

**Comment by Aergwyn** [comment]
Out of curiosity can you point out the line on that page that mentions commas not being allowed at the end if nothing follows after? It doesn't look like it's against any standard because it only says that values are to be separated by a comma.

**Comment by johnneijzen** [comment]
An array is an ordered collection of values. An array begins with [ (left bracket) and ends with ] (right bracket). Values are separated by , (comma).
so example [something ,] meaning that comma is not separating another value. so some JSON validator will say Expecting 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '[' but got ']'

https://stackoverflow.com/questions/201782/can-you-use-a-trailing-comma-in-a-json-object

**Review by peppy — APPROVED** [review]

**Pull request merged**
