### PR TITLE
Hide unnecessary lines on empty BeatmapInfoWedge

### PR DESCRIPTION
**Pull request by Aergwyn**
This bugged me for a while. It hides the unnecessary lines for author and other beatmap stats if there is no real beatmap loaded.

qq

If this is worth exploring I'd also continue on this and look into expanding tests on the BeatmapInfoWedge.

- [x] extend VisualTests

### CODE REVIEW

**Comment by peppy** [comment]
I'd prefer if you avoided references to `DummyWorkingBeatmap` and just based it on what is present or not present in the `WorkingBeatmap` itself.

Also further visual tests would be much appreciated in any area of the game (I'm really hoping we can get much more coverage in tests).

**Comment by peppy** [comment]
I've checked with flyte and we both agree that the information should not move vertically even if other pieces are not available. It feels very weird switching between beatmaps where the vertical positioning of text fades to a new location

**Comment by Aergwyn** [comment]
I'm going to look into preventing that then. (Soon™)

**Comment by peppy** [comment]
The additional tests added in this PR are useful, at least.

**Comment by Aergwyn** [comment]
Can you try this? It doesn't move anymore and is only half a pixel off the original position.

**Review by peppy — APPROVED** [review]

**Pull request merged**
