### PR TITLE
The best score now shouldn't appear twice.

### LINKED ISSUE #25117: The score is shown twice on the result screen
### Type

Cosmetic

### Bug description

When I click the score in a local leaderboard It's shown twice on the result screen.

### Screenshots or videos

image

### Version

2023.1008.1

### Logs

[runtime.log](https://github.com/ppy/osu/files/12896466/runtime.log)
[performance-audio.log](https://github.com/ppy/osu/files/12896467/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/12896468/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/12896469/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/12896470/performance-update.log)
[database.log](https://github.com/ppy/osu/files/12896472/database.log)
[input.log](https://github.com/ppy/osu/files/12896474/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12896475/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12896476/network.log)
[performance.log](https://github.com/ppy/osu/files/12896477/performance.log)
[updater.log](https://github.com/ppy/osu/files/12896478/updater.log)

### PR DESCRIPTION
**Pull request by yesseruser**
I was unable to test this properly.
Fixes #25117.

### CODE REVIEW

**Comment by bdach** [comment]
> I was unable to test this properly.

What does this mean? Did you or did you not test this?

I'm like 99% confident this pull does nothing. Comparing by guid as you have it will not deduplicate local scores against online instances of the same score. The _actual_ issue will be fixed by https://github.com/ppy/osu/pull/24794 instead.

**Comment by yesseruser** [comment]
> What does this mean? Did you or did you not test this?

I did not; I was unable to get the online scores in a debug build.

**Comment by bdach** [comment]
> I was unable to get the online scores in a debug build.

What does _this_ mean?

Leaderboards should be working fine on the development instance. You should not need to run release for this.

**Comment by yesseruser** [comment]
I'll t

> > I was unable to get the online scores in a debug build.
> 
> What does _this_ mean?
> 
> Leaderboards should be working fine on the development instance. You should not need to run release for this.

I meant the Release build configuration. It seems it does not resolve the issue and therefore I am closing this PR.

**Comment by bdach** [comment]
Please test before opening next time.

**Pull request closed without merging**
