### PR TITLE
Fix intermittent failure in beatmap carousel tests

### PR DESCRIPTION
**Pull request by frenzibyte**
https://teamcity.ppy.sh/buildConfiguration/Osu_Build/20489?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildTestsSection=true

```
TearDown : System.AggregateException : One or more errors occurred. (Collection was modified; enumeration operation may not execute.)
  ----> System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
--TearDown
   at osu.Framework.Testing.TestScene.checkForErrors()
   at osu.Framework.Testing.TestScene.RunTestsFromNUnit()
--InvalidOperationException
   at System.Collections.Generic.List`1.Enumerator.MoveNext()
   at System.Linq.Enumerable.OfTypeIterator[TResult](IEnumerable source)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at osu.Game.Screens.Select.Carousel.SetPanelContent.getDifficultyIcons() in /opt/buildagent/work/ecd860037212ac52/osu.Game/Screens/Select/Carousel/SetPanelContent.cs:line 105
   at osu.Game.Screens.Select.Carousel.SetPanelContent.load() in /opt/buildagent/work/ecd860037212ac52/osu.Game/Screens/Select/Carousel/SetPanelContent.cs:line 39
```

I've managed to reproduce this semi-reliably by placing a thread sleep of 1ms at `SetPanelContent`'s BDL, apply 100 repetitions on `TestCarouselSelectsBackwardsWhenDistanceIsShorter`, then use rider's functionality of running the test until failure.

After a bit of effort in logging pieces of information, it appears that this is occurring in the following scenario:
 - Test adds beatmapsets to carousel, and carousel beatmapset cards are loading
 - Test changes ruleset to taiko
 - Beatmap carousel re-sorts each beatmapset items list due to change in filter criteria caused by ruleset switch
 - While carousel is re-sorting, one card is loading and it's iterating through the beatmapset's items list for loading difficulty icons

And after carousel is done re-sorting the beatmapset that the card is loading difficulty icons for, the exception gets thrown as per above.

Simplest fix as far as I can see is to just postpone loading difficulty icons until `LoadComplete`, where it should be safe to iterate through the beatmapset items. Need more opinions on the fix though (slight concern I have with this is shifting load overhead to the update thread, but I hope it's not that much on just difficulty icons).

One other way would be to retrieve icons in constructor and load them in BDL, but not sure it's worth the complexity.

In addition, I've pushed two other changes to make the test actually work for me locally when running it separately (not as part of the whole test fixture).

### CODE REVIEW

**Comment by bdach** [comment]
> One other way would be to retrieve icons in constructor and load them in BDL, but not sure it's worth the complexity.

At face value I would tend to prefer that I think. One thing is that as far as I can tell the ctor solution won't eliminate all of the update thread overheads that this solution carries, because the beatmaps list still has to be copied out on the update thread (from empirical testing, it appears that `SetPanelContent`'s ctor runs on update thread). Other than that it still seems like a better solution, but I'm maybe not seeing what the complexity there would be in that.

Would it be anything more than creating the icon drawables in ctor, storing them to a field, and adding them from the field in BDL? Doesn't sound very complex at all, and seems preferable to a blocking drawable load on update thread (and there may be a good few of these on screen at a given time - although `DelayedLoadWrapper` should be ensuring that there's not *too* many)

**Comment by frenzibyte** [comment]
I meant like the mental overhead that would come with the other solution, since it's not completely known what thread would create the `SetPanelContent`, so you can't guarantee whether it would always be created from a safe thread (in practice, it'll be update thread because it's wrapped under `DelayedLoadWrapper`, but I'm not fully confident unless you still think it's better).

**Comment by bdach** [comment]
I suppose you don't strictly know which thread is calling the ctor, but you *should* know that at the point of ctor the value list should be good for reading / copying out.

Beatmap carousel feels like an area where it's super important to optimise aggressively, so I think I'd prefer ctor and I don't really think it's something that needs benchmarking / measurement since it seems to be a strictly better choice performance-wise to me. But I think I'd like to hear some other thoughts on this first given it's a tie on opinions right now.

**Comment by peppy** [comment]
I was hesitant to do this in the past because I believe there was actually a case where the icon load can cause an overhead (a stutter during carousel load) but it's probably fine to prioritise reliability and revisit this if we notice the stutter in the future. In theory these icons should all be in a cached state due to the toolbar.

**Review by peppy — APPROVED** [review]

**Pull request merged**
