### PR TITLE
 Add filtering by friends to spotlights in RankingsOverlay

### PR DESCRIPTION
**Pull request by EVAST9919**
Screenshot_1

### CODE REVIEW

**Comment by bdach** [comment]
I know this is what the web design is, but it looks off to me (in both places). Unless there are plans that aren't revealed for this yet I don't really understand what all that spacing is for.

**Comment by EVAST9919** [comment]
Yeah. Would be better to just move it to the right of the selected spotlight info, in case there are no plans regarding this part yet

**Comment by smoogipoo** [comment]
I would do that - make it match the performance page. It looks pretty bad as is.

**Comment by EVAST9919** [comment]
Reworked

**Review by smoogipoo — APPROVED** [review]
I think this is fine for now.

**Pull request merged**
