### PR TITLE
Add dim offset property to UserDimContainer

### PR DESCRIPTION
**Pull request by frenzibyte**
Dependency for #5639, allowing to adjust the dim of `UserDimContainer` content without manually changing user dim level

- [x] Depends on #5638

### CODE REVIEW

**Comment by nyquillerium** [comment]
I'm not sure if this is the direction we want to take with this component. The intended use for it was to isolate user dimming logic such that it doesn't fight with anything else to apply dim to the background. Any other component applying dim to the background should be doing so additively, as that was the original intention.

Additional blur is applied from within this component because we optimize away the additional `BufferedContainer` by doing so, which saves us an additional post-process pass.

**Comment by iiSaLMaN** [comment]
> I'm not sure if this is the direction we want to take with this component. The intended use for it was to isolate user dimming logic such that it doesn't fight with anything else to apply dim to the background. Any other component applying dim to the background should be doing so additively, as that was the original intention.
> 
> Additional blur is applied from within this component because we optimize away the additional `BufferedContainer` by doing so, which saves us an additional post-process pass.

What do you mean by additively, directly changing the UserDimLevel?

**Comment by nyquillerium** [comment]
As in, you should try to apply dim directly to the background from whatever component you want to apply dim from instead of having the logic in `UserDimContainer`.

After taking a closer look though I see you're trying to apply a subtractive value to the dim, at which point this may be the only way to approach this.

**Comment by peppy** [comment]
I would name this `DimAdjust` or `DimOffset` if anything. The xmldoc for this bindable/property should mention that "sometimes we need to apply a temporary offset to the dim applied" or similar.

I'm not sure if this is the direction we want to take or if this requires a re-think (see how aggregate values of audio components are done for a potential path forward) but I guess update this first and we'll see how it looks and feels.

**Comment by iiSaLMaN** [comment]
> I'm not sure if this is the direction we want to take or if this requires a re-think (see how aggregate values of audio components are done for a potential path forward) but I guess update this first and we'll see how it looks and feels.

You mean adding something like `ApplyAdjustment(Type.Dim, dimOnBreak);`, I actually like that

**Comment by peppy** [comment]
This might be okay, but I'm not merging without seeing usage in #5639.

**Review by peppy — APPROVED** [review]

**Comment by iiSaLMaN** [comment]
> This might be okay, but I'm not merging without seeing usage in #5639.

Usage pushed.

**Comment by peppy** [comment]
@iiSaLMaN please update on this PR – is it still required?

**Comment by iiSaLMaN** [comment]
Closing as unrequired.

**Pull request closed without merging**
