### PR TITLE
Fix auto advance screens sometimes not advancing

### PR DESCRIPTION
**Pull request by ILW8**
In the tournament client, auto advance screens and screen switching will appear to not work.

To reproduce: 
- Open lazer tournament client, select a match, and go to gameplay screen. 
- Open a shell to the directory containing the ipc files
- Run `echo Playing >ipc-state.txt && sleep 2; echo Ranking >ipc-state.txt; sleep 2; echo Idle >ipc-state.txt; echo "Switch to mappool screen manually now\!"`
- When the above returns, manually press M/click the Map Pool button and wait a few seconds

Now, the next time auto advance screen tries to go to the Gameplay screen (or user manually switches to Gameplay screen), the Gameplay screen will execute its scheduled task to switch to the Mappool screen.

### CODE REVIEW

**Comment by peppy** [comment]
I have a strong feeling this will cancel the following `contract`, potentially something we don't want?

https://github.com/ppy/osu/blob/7bc8908ca9c026fed1d831eb6e58df7624a8d614/osu.Game.Tournament/Screens/Gameplay/GameplayScreen.cs#L220

**Comment by ILW8** [comment]
Now calls `contract` if the current state is `TourneyState.Ranking`. 

Alternatively we could store the scheduled delegate for contract as a different variable name as `scheduledOperation` (`scheduledContract` for example), but I think that's not as clean.

**Comment by peppy** [comment]
Hmm, the way you've fixed this is very convoluted and obfuscates the original problem. The contract logic should probably just be run when the screen is returned to from being hidden? As in, the whole logic block, not just some local additional code.

**Comment by ILW8** [comment]
Something like this?
```diff
index 73193e6dbd..cc45b47826 100644
--- a/osu.Game.Tournament/Screens/Gameplay/GameplayScreen.cs
+++ b/osu.Game.Tournament/Screens/Gameplay/GameplayScreen.cs
@@ -234,17 +234,17 @@ private void stateChanged(ValueChangedEvent<TourneyState> state)
 
         public override void Hide()
         {
-            if (scheduledOperation != null)
-            {
-                scheduledOperation.Cancel();
-
-                if (State.Value == TourneyState.Ranking)
-                    contract();
-            }
+            scheduledOperation?.Cancel();
 
             base.Hide();
         }
 
+        public override void Show()
+        {
+            stateChanged(new ValueChangedEvent<TourneyState>(lastState, State.Value));
+            base.Show();
+        }
+
         private partial class ChromaArea : CompositeDrawable
         {
             [Resolved]
```

**Comment by peppy** [comment]
I've made some further changes and tidy-ups to get this in a mergeable state. Please make sure to check the changes I applied.

**Review by peppy — APPROVED** [review]

**Pull request merged**
