### PR TITLE
Account for path width correctly in LineGraph

### LINKED ISSUE #4163: RankChartLineGraph gets clipped at the bottom
**Describe your problem:** The rank history chart in the user profile overlay gets clipped at the very bottom.

**Screenshots or videos showing encountered issue:** 
clipped rank chart
clipped rank chart

**osu!lazer version:** 2019.126.0 (commit 718136a8928db9f1a3cd9122f33d6bb650820c90)

**Logs:** N/A

I tried fixing this myself but didn't immediately find the cause, since simply offsetting all vertex positions in the graph doesn't change the visible result, and all values are within the expected bounds. Perhaps framework-level?

### PR DESCRIPTION
**Pull request by nyquillerium**
~~While this fixes the fact that LineGraphs were not properly accounting for PathWidth, the path seems to be _still_ off by one pixel.~~

~~This seems to be a result of Path trying to account for pathWidth incorrectly, as minY is being set to -1 at a position of 0.~~

- Closes #4163.

### CODE REVIEW

**Comment by peppy** [comment]
How was this validated? Tests incoming for this? Screenshots of which existing tests you used to ensure correctness?

**Comment by nyquillerium** [comment]
Before:
screen shot 2019-03-07 at 1 59 46 pm
After:
screen shot 2019-03-07 at 2 02 24 pm

Validated visually using TestCaseUserProfile and TestCaseRankGraph. I will add some asserts to the latter case after I figure out what is causing the additional pixel of inaccuracy.

**Comment by peppy** [comment]
Is the circle even aligned any more? It looks to be less aligned than before.

Also I'd recommend a visual test which draws the line at the extremities and provides a border to compare against.

**Comment by nyquillerium** [comment]
The circle looks to be at the same alignment as before (probably because circle calculations are done independently from line calculations)

Will do re:visual tests.

**Review by peppy — APPROVED** [review]

**Pull request merged**
