### PR TITLE
Fix chat line background shifting with every new message at max history

### LINKED ISSUE #29572: Chat background colours will occasionally alternate on new message when scrolled up
### Type

Cosmetic

### Bug description

When scrolled up in a chat box, a new message being sent will sometimes cause the background colours to alternate without moving the chat messages. This video is shown from the Daily Challenge chatbox but I've observed it happening in the F8 chat as well.
Unfortunately I don't know exactly how to replicate it as it doesn't seem to happen every time, but it happens often enough that I figured it was worth a report.

### Screenshots or videos

https://github.com/user-attachments/assets/374bb5e4-a867-4767-9957-1ee9e0133e63

### Version

2024.817.0

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16721327/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by smoogipoo**
Fixes https://github.com/ppy/osu/issues/29572

Fix is pretty straightforward - only run when a new message arrives.

### CODE REVIEW

**Comment by peppy** [comment]
I had this in update to handle cases like deletion:


https://github.com/user-attachments/assets/fdc07493-2e92-4724-9a9f-398453c1e963


```diff
diff --git a/osu.Game.Tests/Visual/Online/TestSceneChatOverlay.cs b/osu.Game.Tests/Visual/Online/TestSceneChatOverlay.cs
index 3cf6c2f311..4642042123 100644
--- a/osu.Game.Tests/Visual/Online/TestSceneChatOverlay.cs
+++ b/osu.Game.Tests/Visual/Online/TestSceneChatOverlay.cs
@@ -505,6 +505,7 @@ public void TestKeyboardNextChannel()
         }
 
         [Test]
+        [Solo]
         public void TestRemoveMessages()
         {
             AddStep("Show overlay with channel", () =>
@@ -527,6 +528,28 @@ public void TestRemoveMessages()
                 });
             });
 
+            AddStep("Send message from bad user", () =>
+            {
+                testChannel1.AddNewMessages(new Message
+                {
+                    ChannelId = testChannel1.Id,
+                    Content = "Message from bad user",
+                    Timestamp = DateTimeOffset.Now,
+                    Sender = testUser,
+                });
+            });
+
+            AddStep("Send message from another user", () =>
+            {
+                testChannel1.AddNewMessages(new Message
+                {
+                    ChannelId = testChannel1.Id,
+                    Content = "Message from another user",
+                    Timestamp = DateTimeOffset.Now,
+                    Sender = testUser1,
+                });
+            });
+
             AddStep("Remove messages from other user", () =>
             {
                 testChannel1.RemoveMessagesFromUser(testUser.Id);

```

**Review by peppy — COMMENTED** [review]
Has an issue

**Comment by smoogipoo** [comment]
I honestly expect that behaviour? The alternative is, what, a message gets removed 200 lines up when the user is scrolled all the way to the bottom, and all their lines alternate?

If deletions are happening often enough for that to be an issue I feel like it'd be more of an issue the way it is currently.

**Comment by peppy** [comment]
If we want to prefer lines not changing when scrolled to the bottom, the alternating pattern could be applied from the bottom instead. But having it break on deletions feels very weird.

**Comment by bdach** [comment]
I think deletions need to be handled if we want this issue to be gone for good.

I'm not sure handling it will be so complicated. Sketch of an implementation:

- Keep boolean flag indicating the colour of the last chat row
- Once a new message is added to the channel, flip the flag
- If the latest message is deleted from the channel, flip the flag
- On every flag change update all rows' backgrounds, going from the latest message backwards

The timestamp handling would be a little more complex though and might require a second pass top-down.

**Comment by smoogipoo** [comment]
Will close then since it seems this is not the appropriate direction.

**Pull request closed without merging**
