### PR TITLE
Add winner of Triangles mapping competition as a bundled beatmap

### PR DESCRIPTION
**Pull request by jai-x**
https://osu.ppy.sh/home/news/2022-10-06-results-triangles

- [x] Depends on https://github.com/ppy/osu-web/issues/9509

### CODE REVIEW

**Comment by jai-x** [comment]
I've just realised this doesn't work unless the beatmap has been added to the `/client-resources/bundled` path.

**Comment by peppy** [comment]
Have to check the changes requested have been applied to the storyboard, but should be good otherwise.

**Comment by peppy** [comment]
Waiting on another change to be applied to the storyboard.

**Comment by peppy** [comment]
Storyboard is now fixed, this is good to go!

**Review by peppy — APPROVED** [review]

**Pull request merged**
