### PR TITLE
Make the music controller's track seekable again if it was seeked to its very end

### PR DESCRIPTION
**Pull request by marco-stephan**
Updated Video: https://streamable.com/46qr7

- [ ] Depends on https://github.com/ppy/osu-framework/pull/757
- [ ] Depends on https://github.com/ppy/osu-framework/issues/824

### CODE REVIEW

**Comment by peppy** [comment]
Just as food for thought, in discussing this with @Tom94 he mentioned that expected behaviour would be to have the next song not start playing until the mouse is released (ie. maintain seeking in the current track as long as dragging).

**Comment by MrTheMake** [comment]
Updated as discussed in discord

**Comment by MrTheMake** [comment]
Dragging a track to its very end and releasing the drag doesn't actually skip to the next song. This is a framework issue though as track.IsRunning isn't updated when seeked to a track's end. @peppy, you mentioned once that you are planing to rework the track's pending action system. Is this still up-to-date?

**Comment by MrTheMake** [comment]
Once https://github.com/ppy/osu-framework/issues/824 is solved, this should be completed.

**Comment by MrTheMake** [comment]
Closing for now

**Pull request closed without merging**
