### PR TITLE
Add option to show/hide slider tail circle.

### PR DESCRIPTION
**Pull request by simonglob**
This change allow the player to hide or show slider tail circles.

Default value is set to true.

### CODE REVIEW

**Comment by bdach** [comment]
Why?

**Comment by jeenyuhs** [comment]
> > This change allow the player to hide or show slider tail ends.
> 
> Why?

Some skins (usually older) still have slider trail circles, so I thought it would be nice to have an option to show or hide it, like the cursor trail option

**Comment by bdach** [comment]
It is already possible to remove slider tail circles from legacy skins, by editing the skin.

So I'd say this toggle is not necessary and don't find myself ever agreeing to merge this in its current form.

**Comment by jeenyuhs** [comment]
The ability to change the slider trail circle isn't available in the skin layout editor, and yes you can change it from the skin folder, in ones osu! folder. But if you have already imported the skin into osu!lazer, it won't update with the latest changes to that skin without reimporting it through setup wizard.

or is there another osu skin folder, i'm unaware of?

https://github.com/ppy/osu/assets/45692977/07837722-f330-44f5-beb8-fa845e24793b

@bdach

**Comment by bdach** [comment]
> But if you have already imported the skin into osu!lazer, it won't update with the latest changes to that skin without reimporting it through setup wizard.

Yes, it will be required to reimport the skin. For now this is the desired flow.

A better flow for customising / compiling skins was planned for the skin editor, but crucially it was planned for the *skin editor* and not a settings toggle.

I'm gonna go ahead and close this as not required / incorrect direction.

**Pull request closed without merging**
