### PR TITLE
Make Autoplay more lazy on fast reverse sliders

### PR DESCRIPTION
**Pull request by PercyDan54**
osu_2020-09-18_20-47-39

### CODE REVIEW

**Comment by bdach** [comment]
Please don't make commits using the web interface.

Have you tested this code at all? Are you able to provide an explanation as to what this change is supposed to do?

**Comment by PercyDan54** [comment]
> 
> 
> Please don't make commits using the web interface.
> 
> Have you tested this code at all? Are you able to provide an explanation as to what this change is supposed to do?

Sorry this is my first pr, feel free to point out any other mistakes.
I've tested it with several beatmaps with fast reverse sliders.
As known, fast reverse sliders can be simply completed with cursor hovering above it instead of always following like Auto did.This attempts to change that behaviour

**Comment by bdach** [comment]
For what it's worth I don't necessarily think that this needed fixing. Special casing this feels off to me.

**Comment by PercyDan54** [comment]
> 
> 
> For what it's worth I don't necessarily think that this needed fixing. Special casing this feels off to me.

This is not a bug.
Just wanted to make auto more smooth.
Ignore this if you want.

**Pull request closed without merging**
