### PR TITLE
Add button in playlists/multiplayer to access the osu-web page

### PR DESCRIPTION
**Pull request by Layendan**
https://github.com/user-attachments/assets/bf901852-221e-4ea5-8beb-d77d58994ea8

Add a button to multiplayer lobbies that allows users to open the room in the browser.

### CODE REVIEW

**Comment by Layendan** [comment]
I thought this would only work on multiplayer and did not realize that it would also show in playlists. Tested on both and made sure that they all work. Should be good to review.

**Comment by smoogipoo** [comment]
Design wise, is this what we really want to do @peppy? It feels shocking to me to add this random symbol everywhere in the game - is that just me?

I ask because this probably would guide other fixes. For example, the room name no longer truncates correctly:

| master | pr |
| --- | --- |
| Screenshot 2024-12-09 at 10 13 30 | Screenshot 2024-12-09 at 10 12 45 |

Fixing the above is non-trivial due to the sizing situation involved.

**Comment by cl8n** [comment]
I agree w/ you, on top of not looking great to have symbols anchored to the end of text like this, it feels like it's suggesting you can see something more on the web page, but that kind of begs the question of why it wouldn't be shown in the game in the first place..?

for a component like drawableroom that isn't obviously guiding the user to more pages, I think the "view in browser" and "copy link" buttons fit better as context menu options on the entire panel, no icon needed

**Comment by peppy** [comment]
The explicit icon should only be used in places that people are expected to regularly be copying links. In multiplayer, it's arguable that it should be there because in stable, for instance, the website shows history which isn't visible in the game. It's also useful for sharing the link in a tournament context.

It *definitely* should not show in every multiplayer game in the list.

Also I agree with context menu support. If we keep the icon in the multiplayer *room* header, I'd still see context menu support also added at the listing / room in addition, to give users one more way to do the same thing.

**Comment by Layendan** [comment]
Yeah tbh I wasn't too happy myself at how the design ended up looking like. I think at this point it would be better to add the "view in browser" and "copy link" options to the context menu and remove the button entirely, but I would like to argue that it should be available everywhere (both listings and rooms).

**Comment by peppy** [comment]
> but I would like to argue that it should be available everywhere (both listings and rooms).

as i said, in context menu is fine. but the icon should *not* display in a listing.

**Comment by smoogipoo** [comment]
Let's close this then because it doesn't sound like anything is salvageable.

**Pull request closed without merging**
