### PR TITLE
Move mod incompatibility logic to "local player" mod select overlays

### LINKED ISSUE #14531: Mod incompatibility indicators shouldn't show on free mod overlay
**Describe the bug:** Any mod can be selected, so it doesn't make sense. It is also broken (see video).

**Screenshots or videos showing encountered issue:** 

(enabling sudden death and perfect shows these indicators on every mod)

https://user-images.githubusercontent.com/35318437/131184180-6a8f9b18-aba8-4c4c-9008-5d8410c259e9.mov

**osu!lazer version:** Since https://github.com/ppy/osu/pull/14441

### PR DESCRIPTION
**Pull request by frenzibyte**
Closes #14531 

- `LocalPlayerModSelectOverlay` (song select, multiplayer user mods):

    CleanShot 2021-08-28 at 02 41 40

- `FreeModSelectOverlay`:

    CleanShot 2021-08-28 at 02 41 19

The moving of the tooltip logic turned out to be a bit more involved, due to tooltips being shared and having the potential of being used somewhere where it shouldn't be, due to the same content type matching (makes me wonder whether the tooltip container should also consider the type of the tooltip provided by the currently hovered drawable, before considering reusing the previously created tooltip).

That's the reason I've switched tooltips to instead rely on `ModButton`s being the content and defined a protected `TargetContentType` to be able to separate "local player mod tooltips content" and "regular mod tooltips content" apart.

Definitely unsure about the solution (given that there's no other tooltip providers that provide theirselves as the content), but that's as far as I can think of right now. Alternatively, private classes can be defined to be able to separate, but I wasn't sure if it's worth it if I can provide the `ModButton` itself as the content.

### CODE REVIEW

**Comment by bdach** [comment]
i was going to review this but @frenzibyte apparently has ongoing framework changes for the tooltip-touching portion of this, so abstaining from review and marking this as blocked.

**Comment by peppy** [comment]
@frenzibyte can this be unblocked now?

**Comment by frenzibyte** [comment]
Yep, I'll get to it.

**Comment by peppy** [comment]
I've done some renaming on this, mainly removing the whole `LocalPlayer` notation, since it doesn't read well and doesn't really make sense. Also your new classes are now explicitly `IncompatibilityDisplaying`, as that's why they exist.

**Review by peppy — APPROVED** [review]

**Pull request merged**
