### PR TITLE
Tournament Client MatchHeader fixes

### PR DESCRIPTION
**Pull request by rodrigopina360**
* When a match in the bracket is selected, the team score in the MatchHeader doesn't show up in the Map Pool screen.
* When right-clicking a match that wasn't previously selected, the context menu automatically hides before the user can select an option.
* When selecting a completed match and showing the Gameplay screen, the score previously saved gets reset.
* When a match without points was selected, the warmup check was made before the match was started, leading to a null comparison.

### CODE REVIEW

**Comment by peppy** [comment]
For future reference, please split out individual changes/fixes into separate commits (or pull requests if they are large enough). It's very hard to review multiple fixes in a single commit, as I don't know what is fixing what, and need to cross-reference two or three sources at once to try and understand what is going on .

**Comment by peppy** [comment]
To clarify: you are adding score display to the map pool screen where it never existed before, correct? The default was false and it was not being enabled on that screen in the first place, so this is an actual visual and functional change, not a bug fix.

**Comment by Pinossaur** [comment]
Not really, the score display is always showing on the mappool screen, up to the point where you change the current match. Currently, to have the score display working you have to first select the match you want to change. Save the changes, restart the client, and then it'll work.

**Comment by Pinossaur** [comment]
Yeah, what I just said was the current behavior present in the master branch, the changed I made are supposed to make it so the score display is always on by default, and only off when nedded, in the case of warmups. I had changed the value of showScores in the constructor because when teams are changed, the gameplay screen creates a new instance of the score display, and it always defaulted to either true when specified in the declaration, or false.

**Comment by peppy** [comment]
I've split out two of these fixes which were trivial to understand.

For the remaining two, could you please provide a video and potentially PR the changes as separate PRs so I can try to understand what is being fixed? I'm still struggling to follow the code changes (especially the `StartMatch` / `CancelMatch` calls being moved around).

Will close this PR for now.

**Pull request closed without merging**
