### PR TITLE
Update TabControl in User Overlay in line with the web version

### PR DESCRIPTION
**Pull request by EVAST9919**
59682131-3df8e600-91de-11e9-97ae-042f27a136d5

### CODE REVIEW

**Comment by peppy** [comment]
Is there a reason you aren't using `OverlayHeaderTabControl`?

**Comment by EVAST9919** [comment]
`OverlayHeaderTabControl` based on strings as values and we want to use ProfileSection

**Comment by EVAST9919** [comment]
umm, got it now

**Comment by peppy** [comment]
Ah, sorry, misread your change here (didn't see the move/rename of code).

**Comment by peppy** [comment]
This seems to have broken layout. Items are now getting pushed around:

https://puu.sh/DHSCN/c08ced6164.mov

**Comment by peppy** [comment]
@EVAST9919 just a ping to make sure you saw my last message on this PR.

**Comment by EVAST9919** [comment]
@peppy fixed

**Review by peppy — DISMISSED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
