### PR TITLE
Improve vertical flexibility of BeatmapSetOverlay's header

### PR DESCRIPTION
**Pull request by frenzibyte**
- Avoid overlapping between beatmap info and details
- Make header expandable (mostly for beatmap availability box and beatmaps with many difficulties)

### CODE REVIEW

**Comment by peppy** [comment]
What issue is this fixing? Screenshots? Tests?

**Comment by iiSaLMaN** [comment]
it's a dependency for #4986 and #5015, I thought it would be better to put it in a separate PR as it's a small change

**Comment by peppy** [comment]
Each PR should stand alone. Please provide at very least screenshots showing before and after of broken displays.

**Comment by iiSaLMaN** [comment]
Here's screenshots on PR #4986 before and after these changes
- Before
AvailabilityBefore
- After
AvailabilityAfter

**Comment by peppy** [comment]
Thanks

**Review by peppy — APPROVED** [review]

**Pull request merged**
