### PR TITLE
Compute total score without mods during standardised score conversion

### PR DESCRIPTION
**Pull request by bdach**
- Next step for https://github.com/ppy/osu/issues/27685
- [x] Will require scoring sheets to confirm there are no other unexpected changes in scoring conversion other than ±1 point from rounding (opening as draft until they arrive)

This is going to be used by server-side flows. Note that the server-side overload of `UpdateFromLegacy()` was not calling `LegacyScoreDecoder.PopulateTotalScoreWithoutMods()`.

Computing the score without mods inline reduces reflection overheads from constructing mod instances, which feels pretty important for upcoming server-side flows.

There is one weird kink in the treatment of stable scores with score V2 active - they get the *legacy* multipliers unapplied for them because that made the most sense. For all intents and purposes this matters mostly for client-side replays with score V2. I'm not sure whether scores with SV2 ever make it to submission in stable.

There may be minute differences in converted score due to rounding shenanigans but I don't think it's worth doing a reverify for this. They will most likely get kinked out when we perform the server-side operations.

### CODE REVIEW

**Comment by bdach** [comment]
!diffcalc
GENERATORS=score

**Comment by bdach** [comment]
!diffcalc
GENERATORS=score
RULESET=catch

**Comment by bdach** [comment]
!diffcalc
GENERATORS=score
RULESET=mania

**Comment by bdach** [comment]
I can't conclusively prove this because I failed to turn up a concrete counterexample in an hour of trying, but I'm *reasonably* sure that the above empty spreadsheets are a lie. See https://github.com/smoogipoo/diffcalc-sheet-generator/issues/9.

I believe that this should and will cause fluctuations in score by 1 point and no more, but at this point without the sheet generator as a tool I am not sure how to conclusively prove this. Not sure how to proceed with this further.

**Comment by smoogipoo** [comment]
Let's try this again.

!diffcalc
GENERATORS=score

**Comment by smoogipoo** [comment]
Looks like it worked this time :)

**Comment by smoogipoo** [comment]
!diffcalc
GENERATORS=score
RULESET=taiko

**Comment by smoogipoo** [comment]
!diffcalc
GENERATORS=score
RULESET=catch

**Comment by smoogipoo** [comment]
!diffcalc
GENERATORS=score
RULESET=mania

**Comment by bdach** [comment]
Well the sheets _would_ have looked good... except the catch ones don't. [They contain completely unexplained increases by more than +/-1 score](https://github.com/ppy/osu/pull/28277#issuecomment-2132057562). The increase seems to be related to the legacy maximum score simulation changing *somehow* (somehow this branch had more bonus). And in local testing it looks like *somehow* merging master fixes this which is a *very* scary thing to learn.

I'll investigate this in more detail but I just *know* this is going to be half a day down the drain and I don't want to get into it right now so I'll leave it for tomorrow. For now I'll just re-queue a catch sheet to see what happens.........

!diffcalc
GENERATORS=score
RULESET=catch

**Comment by bdach** [comment]
Sheet looks better and I'm 99% sure whatever the aforementioned issue is it won't have been caused by this pull, so undrafting (but will still look into what happened with that catch stuff tomorrow).

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
