### PR TITLE
Allow player to change initial spinner spin

### PR DESCRIPTION
**Pull request by LittleEndu**
I spin CCW and find it really annoying that the spinner initially spins CW.

### CODE REVIEW

**Comment by peppy** [comment]
I don't think this should be a configuration setting. We should probably make the animation comfortable for people that spin in both directions instead.

**Comment by LittleEndu** [comment]
If you make a new animation that doesn't have any angular momentum then it doesn't feel like a spinner. If you have an animation that has momentum in both directions then it would just feel like the spinner is broken.

Just felt like players who spin only one way would like the option (this could even be supported for skins) and players who spin both directions shouldn't really care.

**Comment by level6ascend** [comment]
lol watch this

**Comment by smoogipoo** [comment]
@arflyte any thoughts on this?

**Comment by arflyte** [comment]
I have to agree if the initial spin is against the usual spin direction it would be weird, but adding a config setting for it doesn't feel like a solution. I'll try to figure out the best visual cues for the spinner that works for both direction.

**Comment by smoogipoo** [comment]
Let's close this one for now then, awaiting directions from designer-san.

**Pull request closed without merging**
