### PR TITLE
Change editor timestamp regex to not match non-editor ones

### PR DESCRIPTION
**Pull request by LittleEndu**
`\d\d:\d\d:\d\d\d? [^-]*` would match any timestamp that had something written after it.

`\d\d:\d\d:\d\d\d? \((\d,?)+\)` only matches timestamps that are copied from the editor.

### CODE REVIEW

**Comment by bdach** [comment]
This regex is too restrictive. It already won't match mania object timestamps:

https://github.com/ppy/osu/blob/8555a465ac4f204f36dbce90fdc4900c6e5d1c74/osu.Game.Rulesets.Mania/Edit/ManiaHitObjectComposer.cs#L123-L124

Also see:

https://github.com/ppy/osu/blob/8555a465ac4f204f36dbce90fdc4900c6e5d1c74/osu.Game/Screens/Edit/Compose/ComposeScreen.cs#L92-L103

If the composer doesn't override `ConvertSelectionToString()` there will be no content in the parens.

Really the issue if anything is that the hyphen should also be matched but discarded, and the actual timestamp should be a taken from a capture group rather than the entire match. (I do slightly wonder about the futility of doing that as well but if autolink is desired in chat then something will have to give.)

**Review by bdach — CHANGES_REQUESTED** [review]
see above

**Comment by LittleEndu** [comment]
🤔 Wouldn't it be wise to just copy the regex from web then?

https://github.com/ppy/osu-web/blob/651a9bac2b60d031edd7e33b8073a469bf11edaa/resources/assets/coffee/_classes/beatmap-discussion-helper.coffee#L10

**Comment by bdach** [comment]
I suppose that works for the default rulesets in the shorter run, at least. Probably a substantial amount of time left yet until custom rulesets are to be taken into serious consideration in this regard.

**Comment by bdach** [comment]
So just for the record, the regex from web doesn't really fix what the OP wants it to fix. Bare timestamps with anything written after them are still matched. But I guess I see no harm in unifying.

Also going to skip adding tests because that's what web already uses, I think...?

**Review by bdach — APPROVED** [review]

**Comment by LittleEndu** [comment]
> Bare timestamps with anything written after them are still matched.

But only if they have 3 digits of millisecond precision which is unlikely for other timestamps. This also does fix the case where everything after posting a timestamp is matched by the regex; the regex used in web only matches the timestamp or timestamp & hitobjects in parenthesis (so the "anything" needs to be valid hitobject information copied from editor). 

And yeah, this regex has been used in beatmap discussions for 15 months, if it had any issues mappers would have found them already, so tests are probably not needed at this point.

**Pull request merged**
