### PR TITLE
Toggle overlays only if it is acceptable

### LINKED ISSUE #2507: Toolbar toggle-able during gameplay
Opening the toolbar using Ctrl+T during gameplay allows you to skip throughout the song, open options, the social browser, chat and osu!direct

https://youtu.be/2AFc67lD7RY

Edit: The Toolbar is pretty much toggle-able everywhere which could present problems in things like the editor.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/58248263-toolbar-toggle-able-during-gameplay?utm_campaign=plugin&utm_content=tracker%2F4707269&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F4707269&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UselessToucan**
resolves #2507 
https://youtu.be/qjafr2RJk6k

### CODE REVIEW

**Comment by peppy** [comment]
Not sure I agree with this.

**Comment by smoogipoo** [comment]
Yeah idk about this, the only part that's bad about the issue thread mentioned is that the track can be seeked.

**Comment by UselessToucan** [comment]
Why opening toolbar during gameplay considered normal use-case? Anyway during gameplay you won't have free time for playing around with all these overlays(except pause, which is handled here).

**Comment by UselessToucan** [comment]
I think replay/break are separate use-cases. They can be handled along with the pause.

**Comment by peppy** [comment]
I still tend to disagree with disabling global overlays. I'd sooner see the gameplay automatically pausing when they are triggered.

**Comment by peppy** [comment]
Similar functionality can now be achieved via #2577.

**Pull request closed without merging**
