### PR TITLE
Fix editor potentially leaving a dangling beatmap if exiting during load too fast

### LINKED ISSUE #14878: Empty beatmap is created when pressing edit and backing out of it quickly
Related to #10628
> Exiting empty beatmap setup should not prompt "save changes" 

**Expected behavior:** 
- Empty beatmap shouldn't exist. 
- Setup prompt must be shown, preventing Reproduction Step 3.

**What actually happened:**
- No setup prompt was shown but an empty beatmap was created.

**Reproducibility:** Very Reproducible

**Reproduction steps:**
1. Click on play (doesn't have to be in the song select screen)
2. Back out and click on edit
3. Press ESC repeatedly as soon as edit is clicked on
4. Go on song select and scroll to the very top

**osu!lazer version & specifics**
- 2021.927.0-lazer
- Arch Linux, Kernel 5.13.19-xanmod1-1

**Logs**
[runtime.log](https://github.com/ppy/osu/files/7244395/runtime.log) [database.log](https://github.com/ppy/osu/files/7244401/database.log) 

**Video showing the bug**

https://user-images.githubusercontent.com/53419401/135097475-3b2601a9-b75e-466e-8807-224a33de1559.mp4

### PR DESCRIPTION
**Pull request by Cootz**
Reduce amount of dummy beatmaps generated by editor.

| branch | video |
| ---- | ---- |
| Main | <video src="https://user-images.githubusercontent.com/50776304/235228985-d774b76a-cd61-4c78-adde-9dd2dfd346e0.mp4"> |
| This PR | <video src="https://user-images.githubusercontent.com/50776304/235229287-a24403b1-4e97-4a40-a51e-7d3f972fdff7.mp4"> |

Fixes #14878

### CODE REVIEW

**Comment by MatthieuHernandez** [comment]
Can you stach together your first 2 commits? _(you can use a git rebase with a fixup to do that)_

**Comment by Cootz** [comment]
Crap, shouldn't touch it (

**Comment by MatthieuHernandez** [comment]
Your first commit is empty, you can drop in and stack your 2 tests commits, moreover the CI does not pass everywhere, I can help you to look at that if you want.

**Comment by peppy** [comment]
I've fixed up the test to read a bit better (and added some explanation as to what it is testing).

Seems fine otherwise.

**Comment by peppy** [comment]
I've fixed up the test to read a bit better (and added some explanation as to what it is testing).

Seems fine otherwise.

**Review by peppy — APPROVED** [review]

**Pull request merged**
