### PR TITLE
Add option for user to turn off kiai flashing

### LINKED ISSUE #21569: Kiai pulses in osu!taiko are too aggressive
### Type

Game behaviour

### Bug description

Currently, the kiai pulses in taiko are too intense to the point where it goes from annoying/hassle to read on more normal BPM, to actually making eyes hurt, and posing a very concerning risk for epileptic players.
I've used argon skin for these examples but the same issue applies to all skins.

here's an example: https://osu.ppy.sh/beatmapsets/1895673#taiko/3906737

## lazer
https://user-images.githubusercontent.com/62819481/206293976-9d293a2f-0395-44e1-8f11-9c253435a290.mp4

## stable
https://user-images.githubusercontent.com/62819481/206294659-14b71737-438a-4391-abb9-c47ebb5bd73f.mp4

here's a more extreme example: https://osu.ppy.sh/beatmapsets/1732016#taiko/3540250

## lazer
https://user-images.githubusercontent.com/62819481/206294839-48099fa0-9771-4dd5-a99b-69b281fc9f72.mp4

## stable

https://user-images.githubusercontent.com/62819481/206295232-2897e3c3-e8ce-48d5-8edd-563698cca670.mp4

As you can see, the pulses in stable are much more subtle, to the point they're barely noticeable, which makes playing actually bearable. i think adjusting the current intensity of the pulses is a very needed change as of now, because frankly it makes taiko unbearable to play most of the time.

### Screenshots or videos

_No response_

### Version

2022.1207.0-lazer

### Logs

N/A

### LINKED ISSUE #21747: Kiai flashes in osu! ruleset are way too strong
### Type

Cosmetic

### Bug description

Same as #21569 but in osu! ruleset.

It gets really distracting when using skins with colorful hitcircles. Stable has the flashing too, but its way more subtle.

### Screenshots or videos

_No response_

### Version

2022.1208.0

### Logs

-

### PR DESCRIPTION
**Pull request by ArgentumHeart**
- Closes #21569 
- Closes #21747 

Not sure if necessary to replace on/off switch with slider which changes the intensity of the flashing.

### CODE REVIEW

**Comment by ItsShamed** [comment]
In my opinion, this setting should target all rulesets and not only "flashes", since it wouldn't make really sense to only target osu!standard as there are other rulesets that are affected by Kiai (e.g. Taiko). 
Although this is to be reconsidered, I also think that this should be enforced to custom rulesets as there are some that implements Kiai effects too during gameplay (e.g. [Sentakki](https://github.com/LumpBloom7/sentakki)).

**Comment by ArgentumHeart** [comment]
@ItsShamed Right now its affecting all rulesets which use kiai flashing from skins in any way (leaving some pressure on mode developers to respect the setting if they're reimplementing some skin-related stuff)

Not sure about Sentakki, let me check manually.

p.s. maybe I went the wrong way implementing this, I've spent only few days with codebase. Please feel free to suggest

**Comment by peppy** [comment]
Let's remove more of the game from the game until there's no game left.

There hasn't been a toggle for kiai in stable so I'd hope we don't disable it here either.

I think if anything, this should be a slider which allows changing the intensity, and as already mentioned, should be applied to all kiai elements, not just some (and should not be an osu! ruleset specific setting). It should have a range of something like 10% ~ 100% but not go down to zero.

Individual kiai effects which are seen as distracting by many should also be adjusted to be less distracting.

As for this PR, I'm going to close it since code style is incorrect and it's not really the direction I see things going. Thanks for your submission and feel free to work towards the direction above in a new PR if you feel up to it, but also please read the contribution guide and look at existing naming conventions.

**Comment by ArgentumHeart** [comment]
@peppy Can you suggest any general direction of research for implementing this please?

**Comment by peppy** [comment]
That's basically what my last message was. Feel free to ask about any specifics.

**Comment by ArgentumHeart** [comment]
Currently my understanding: get a slider 10-100 and value as 0.1-1. Go through every kiai effect implementation in current modes and apply multiplier at the highest point of hierarchy to the alpha value of each effect. 
Does this sound correct to you?

**Comment by peppy** [comment]
Sounds about right. Also the configuration setting should be global, next to things like `BeatmapColours`.

**Comment by ArgentumHeart** [comment]
ok, and also include it to the widgets? (right after song selection, before the gameplay)

**Comment by peppy** [comment]
Not necessary, no. Those settings panels are only for settings that users would change per beatmap.

**Comment by bdach** [comment]
I'll also say that the current kiai effect implementation should probably be cross checked against stable to see if it matches IMO. It's where I would have started work on the issues mentioned, to the point where I probably wouldn't even do the slider until it's confirmed that the intensity is the same as stable.

**Comment by peppy** [comment]
For sure.

**Pull request closed without merging**
