### PR TITLE
Change `ResourceStore` provided to `Skin` to be a fallback, not replacement

### PR DESCRIPTION
**Pull request by peppy**
This seems like the safest direction for now. With this change, a modification like what happened in https://github.com/ppy/osu/pull/25443 will not break lookups anymore.

### CODE REVIEW

**Comment by bdach** [comment]
Accidental or intentional draft? :sweat_smile:

**Comment by peppy** [comment]
You guessed it.

**Comment by bdach** [comment]
Blaming back yields https://github.com/ppy/osu/commit/35d2f973a39b533ed1cb7392d31d1d8299e9b0c9, so I'm going to wait for the CI run before doing any serious review.

**Comment by peppy** [comment]
Tests did pass locally, for whatever that is worth. I think the previous method was not correctly doing fallback, based on the commit you linked.

**Review by bdach — APPROVED** [review]
Well I checked a few things and saw no breakage so I'm just gonna merge this and hope for the best.

**Pull request merged**
