### PR TITLE
Optimize restart

### PR DESCRIPTION
**Pull request by ocboogie**
It was creating a new instance of the Player class on each restart which increases memory and so lags the game heavily.
Still could be optimized more: On each restart it reloads all the elements

### CODE REVIEW

**Comment by ocboogie** [comment]
Oh wait I didn't

**Comment by ocboogie** [comment]
I could optimize it way more if I could add child objects under other child objects (Pretty much `Insert`)
Like `Add()` but not on top.

**Comment by peppy** [comment]
You can set `Depth` to gain control over insert order.

Alternatively you can make `Container`s in the order you want at ctor time and then add to those targets.

**Comment by ocboogie** [comment]
Well I'll try that thanks

**Comment by ColdVolcano** [comment]
I think you'll need to update the testcase for it to go 👍

**Comment by ocboogie** [comment]
It works fine on my side?

**Comment by ocboogie** [comment]
Nvm

**Comment by peppy** [comment]
Superseded by https://github.com/ppy/osu/pull/644.

**Pull request closed without merging**
