### PR TITLE
Revamp scoring game-wide for more intuitive exponential and standardised scoring calculations

### PR DESCRIPTION
**Pull request by smoogipoo**
Basically a massive rewrite of everything to do with `ScoreProcessor`, but I think it turned out super nice.

* Added `AffectsAccuracy` to Judgement.
  * If true -> the hit result counts towards accuracy % and the standardised accuracy portion.
* Made `AffectsCombo = false` add score to the bonus portion instead.
* No more awkward scaling factor for the standardised model.
* Cleaner/(a bit more accurate?)/more intuitive exponential scoring method.
* Lots and lots and lots of cleanup.
* Made OsuScoreProcessor consider slider ticks.

### CODE REVIEW

**Comment by smoogipooo** [comment]
Remaining issues fixed. WIP label removed.

**Comment by smoogipooo** [comment]
Applied changes as discussed. Score is now based on:
* baseScore/maxBaseScore : Ratio of raw score to the maximum raw score achievable.
* highestCombo/maxHighestCombo  : Ratio of the highest combo achieved to the maximum combo possible in the map.
* bonusScore : Added on top of the 1000000 score.

Such that: `totalScore = 10000 * (ComboPortion * baseScore/maxBaseScore + highestCombo/maxHighestCombo) + bonusScore`

Exponential scaling remains as `(baseScore + bonusScore) * highestCombo`

As discussed, we will later add in accuracy scoring as a minor factor to the calculation, but I'll for that until all rulesets share hitwindows and have perfect scoring values.

**Comment by peppy** [comment]
I think this definitely either needs the ComboPortion/BasePortion combined into one variable, or an exception when they don't add up to 1.

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
👍

**Pull request merged**
