### PR TITLE
Add setting to show the song difficulty graph

### PR DESCRIPTION
**Pull request by Aergwyn**
I did a bit of reordering in `SongProgress` to comply to the usual project standards a bit more. I didn't want to rearrange everything as otherwise it'd basically mark everything as changed and that would be too awkward to review.

Preview: https://streamable.com/nb254

### CODE REVIEW

**Comment by peppy** [comment]
Can still see the bars at certain aspect ratios:

image

Also I'd recommend this setting is called "Show difficulty graph in progress bar" or something like that. Hard to know what to expect when it's phrased the way you have it.

**Comment by Aergwyn** [comment]
I see why that can happen and actually it has nothing to do with aspect ratio. The graph only moves down it's own height while being on top of the bar. I just didn't notice because the graph not always shows boxes at full height. Will add a step that generates one so it should be easier to check.

**Comment by swoolcock** [comment]
Moving forward we'll have to be mindful of that kind of "move down by its own height" method of hiding things, as elements may be pushed in by safe area insets making these calculations incorrect.

**Comment by Aergwyn** [comment]
Good point. I have an idea for that already and am working on it.

**Comment by Aergwyn** [comment]
All concerns should be addressed now.

**Review by peppy — APPROVED** [review]

**Pull request merged**
