### PR TITLE
Simplify osu! high-bpm acute angle jumps bonus

### PR DESCRIPTION
**Pull request by stanriders**
This change simplifies acute angle jump bonus:

1. Removes velocity cap
2. Removes requirement for previous jump to also be acute
3. Makes angle repetition penalty harsher
4. Changes the start of the distance curve to be at a full diameter instead of radius
5. Separates wiggle buff into a separate bonus from highbpm jump bonus

https://pp.huismetbenen.nl/rankings/players/acute-jumps-rework

### CODE REVIEW

**Comment by tsunyoku** [comment]
@smoogipoo could we get a sheet for this please?

**Comment by frenzibyte** [comment]
!diffcalc
RULESET=osu

**Comment by frenzibyte** [comment]
!diffcalc
RULESET=osu

**Comment by tsunyoku** [comment]
!diffcalc
RULESET=osu

**Comment by stanriders** [comment]
!diffcalc
RULESET=osu

**Review by tsunyoku — DISMISSED** [review]

**Review by tsunyoku — APPROVED** [review]

**Pull request merged**
