### PR TITLE
Add multiplayer match settings

### LINKED ISSUE #2723: Multiplayer match screen
multiplayer_settings_c

multiplayer_settings_b

Should implement the match screen interface and it's individual components.

### PR DESCRIPTION
**Pull request by naoey**
Attempt at finishing remainder of match screen as there wasn't any activity on that issue in the past month.

Not entirely sure how the UI is expected to behave. It's implemented to save changes immediately atm, but on second look at the design I noticed the random yellow box which might be intended to be a "save" button?

- Closes #2723

---

Adds the settings portion of the multiplayer match screen.

### CODE REVIEW

**Comment by naoey** [comment]
Should I pull in DrabWeb's implementation in a new PR and fix up any issues remaining with it instead?

**Comment by smoogipoo** [comment]
Just wondering, which implementation are you referring to?

**Comment by smoogipoo** [comment]
Took a look at both and the designs, and I think that'd be worthwhile to do.

My main concerns with this PR are:
1. I'm not sure about having an enum for the game type, and having the icons hard-baked into `DrawableGameType`. Much preferred how it was before, OR make GameType into a class with a `GetVisualRepresentation()` method.
2. Flyte intended to make this an overlay, judging by the designs, so it looks like @DrabWeb 's implementation is more accurate. This would also remove the whole "commit on focus lost" thing you've got going on here.

**Comment by naoey** [comment]
Alright, I'll get that in a new PR soon.

**Pull request closed without merging**
