### PR TITLE
Replace all MathHelper.Clamp usages with Math.Clamp

### PR DESCRIPTION
**Pull request by turbedi**
.NET Standard 2.1 implements Math.Clamp , use it instead of MathHelper.Clamp from osuTK.

### CODE REVIEW

**Comment by huoyaoyuan** [comment]
For not reviewed ones, you can use `get rebase master` `git push -f` to get cleaner history.

**Comment by peppy** [comment]
Please don't force push.

**Comment by turbedi** [comment]
I tried to squash the commits, but somehow made it even worse.. Haven't used git for a while.
Any idea how to fix the commit history? Otherwise I can create a new PR.

**Comment by peppy** [comment]
The history is fine. Fix the [CI reported issues](https://ci.appveyor.com/project/peppy/osu/builds/28993211), though.

**Comment by turbedi** [comment]
CI issues fixed

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
