### PR TITLE
Disallow parsing key "Version" for legacy beatmap skins

### LINKED ISSUE #6433: Beatmap skin configuration decoding potentially conflicts with beatmap configuration
Beatmap skin decoding potentially conflicts with beatmap configuration decoding, this applies for `Version` where on beatmap configuration, it gives the difficulty name of the beatmap, on the other hand for skin configuration, it gives the legacy version for this skin.

Will take a look at it.

### PR DESCRIPTION
**Pull request by frenzibyte**
Closes #6433

### CODE REVIEW

**Comment by bdach** [comment]
Could you provide an example of a beatmap that hits this problem? Are you sure this ambiguity cannot be resolved by checking the file section?

**Comment by iiSaLMaN** [comment]
> Could you provide an example of a beatmap that hits this problem?

Basically, any beatmap, check the referenced issue for more information.

> Are you sure this ambiguity cannot be resolved by checking the file section?

You mean early return on the `Metadata` section? that's another way to do it. (seems nicer than filtering the key `Version`)

**Comment by bdach** [comment]
The issue does not have the kind of info I'd want either. I'd want to see an actual example file.

I looked at the wiki, and if the information there is correct, skin version should be in `[General]`, and beatmap version should be in `[Metadata]` - does that sound correct? If it does, you need to inspect the section parameter and switch on it appropriately to handle both without having to ignore one.

**Comment by iiSaLMaN** [comment]
https://github.com/ppy/osu/issues/6433#issuecomment-555733478

**Pull request closed without merging**
