### PR TITLE
Fixed Taiko Flashlight only appearing after first object has been hit

### PR DESCRIPTION
**Pull request by IzTheCodeMan**
Fixes https://github.com/ppy/osu/issues/20905

### CODE REVIEW

**Comment by IzTheCodeMan** [comment]
I found a slight issue with timing, im fixing right now, ill update the pr.

**Comment by peppy** [comment]
This doesn't make sense. It's already being done in the base class:


https://github.com/ppy/osu/blob/84fdd2e107dc3045a295eef5668bea8cd58e24cd/osu.Game/Rulesets/Mods/ModFlashlight.cs#L131

**Comment by IzTheCodeMan** [comment]
> This doesn't make sense. It's already being done in the base class:
> 
> https://github.com/ppy/osu/blob/84fdd2e107dc3045a295eef5668bea8cd58e24cd/osu.Game/Rulesets/Mods/ModFlashlight.cs#L131

Some maps start with no break time, it seems.

**Comment by peppy** [comment]
I think maybe you're misunderstanding, the `true` argument in the line I linked means it's running the exact same code you added, in the exact same location at the exact same point in time.

**Comment by IzTheCodeMan** [comment]
> I think maybe you're misunderstanding, the `true` argument in the line I linked means it's running the exact same code you added, in the exact same location at the exact same point in time.

image

Alright, it seems to change it late, so I think it might be something else, Im going to do more debugging, just give me a few minutes, ill get this fixed.

**Comment by IzTheCodeMan** [comment]
> I think maybe you're misunderstanding, the `true` argument in the line I linked means it's running the exact same code you added, in the exact same location at the exact same point in time.

Alright I figured out the issue, Do you have an idea of how I could add a delay to the start of a map with no break, I need to do this to give the flashlight time to expad.

**Comment by IzTheCodeMan** [comment]
> I think maybe you're misunderstanding, the `true` argument in the line I linked means it's running the exact same code you added, in the exact same location at the exact same point in time.

image

Something about this, I cant seem to figure out what.

**Pull request closed without merging**
