### PR TITLE
Random song when entering the select screen without a beatmap selected

### LINKED ISSUE #1617: Song select should choose a random song on entering
When entering song select and the theme song is playing, a random selection should be made, rather than loading the first-ever imported beatmap.

### PR DESCRIPTION
**Pull request by MattiaPette**
Fixes #1617

### CODE REVIEW

**Comment by peppy** [comment]
that's... a compact fix

**Comment by MattiaPette** [comment]
Indeed

**Comment by Aergwyn** [comment]
What happens if you delete/hide a beatmapset? It would select a random one in that case too?

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
@Aergwyn this function is only called on initial load, so that should not be an issue.

**Comment by Aergwyn** [comment]
Oh. That is indeed really simple then. Awesome!

**Pull request merged**
