### PR TITLE
Reduce height of song progress handle

### LINKED ISSUE #3602: key overlay and repeat time marker shouldn't cover each other
osu_2018-10-17_22-46-29-4
osu_2018-10-17_22-46-29-5

### PR DESCRIPTION
**Pull request by plankp**
Fix #3602

### CODE REVIEW

**Comment by smoogipoo** [comment]
Now it overlaps the time:

image

Idk, perhaps we should rethink this?

**Comment by plankp** [comment]
It already overlaps time before the change

**Comment by KoziLord** [comment]
Maybe make the time get bigger and go up a bit?

**Comment by plankp** [comment]
It moves the time, percentage stuff and the key press counter higher up if we are replaying (when there is scroll handle)

**Comment by peppy** [comment]
Honestly this design is going to change going forward, so this change seems completely pointless (there are so many other larger issues than this). But I guess it's better than what we had? I don't know.

**Review by peppy — APPROVED** [review]

**Pull request merged**
