### PR TITLE
Add mod display and unranked indicator to new song select footer

### PR DESCRIPTION
**Pull request by frenzibyte**
- Part of #22204 

Preview:

https://github.com/ppy/osu/assets/22781491/32b236aa-9cbb-44b9-9e01-dbb87499a637

https://github.com/ppy/osu/assets/22781491/eed34aba-2462-4c8a-ba8e-e88f59fd799e

Notes:
 - I've had to disable display of extended information for mods such as DT, as displaying only one of them eats up the whole display:
   
   CleanShot 2024-05-10 at 02 51 11

   I'm not sure what's the best way to display those, or if this indicates a flaw in the current design of the mod display (cc @peppy).

 - There is supposed to be a drop-shadow behind the background of the "mod display" part of the bar above the button, but when adding it, the bottom left edge of the display becomes overfilled with shadow, making it look ugly:
CleanShot 2024-05-10 at 06 59 51
It may not be as noticable (maybe because of the background being dark though). If there is nothing looking off with the image above then I can add the drop shadow ([diff](https://github.com/ppy/osu/commit/3de49bbef2cc804257fd15f244da3c6bbcd42508), for real testing).
 - There are different other ways for displaying the unranked indicator proposed in [discord](https://discord.com/channels/188630481301012481/188630652340404224/1238275598804324365), such as adding a red outline to the mod display, or adding a warning icon next to the mod display with an explanatory tooltip. I'm not really a fan of any of those proposals as it sort-of defeats the purpose of the indicator, which is to make the user well informed about their mod selection without having them hover over it.

### CODE REVIEW

**Comment by cl8n** [comment]
the right edge of the unranked indicator doesn't seem to align (in the sheared sense...) with the button below it

**Comment by peppy** [comment]
> I've had to disable display of extended information for mods such as DT

Is it hard to have it display until it doesn't fit? And potentially in the tooltip?

I'm wondering if we need a compact version which shows that there are non-default settings while not being the full settings text (just a slightly extended colour bar).

**Comment by EVAST9919** [comment]
> There is supposed to be a drop-shadow behind the background of the "mod display" part of the bar above the button, but when adding it, the bottom left edge of the display becomes overfilled with shadow, making it look ugly

Figma uses gaussian blur for shadows while o!f uses linear fade (hacky repurposed masking shader). I have a way to fake gaussian blur for simple shapes without any overhead, but there's no way to change that without big refactoring unfortunately.

**Comment by frenzibyte** [comment]
> > I've had to disable display of extended information for mods such as DT
> 
> Is it hard to have it display until it doesn't fit? And potentially in the tooltip?

It's possible, but with only one customised mod, adding any other mod will fall back to text mode. The tooltip I added for "X mods" text already shows the mod in its extended form.

**Comment by Joehuu** [comment]
Might need https://github.com/ppy/osu/discussions/19750 to distinguish rate adjust mods without having the extended information state. Still want to see the rate multiplier though.

I feel like the tooltip for 5+ mods seems to be lacking information in it's current state. Individual mod tooltips show the mod name and settings modified but doesn't in this grouped 5+ mod tooltip. Was recommending to reuse or copy the mod preset tooltip that has this information w/ consistent mod icons.

Also `TestSceneFooterButtonModsV2` crashes with that tooltip:
```
[runtime] 2024-05-11 04:07:12 [error]: An unhandled error has occurred.
[runtime] 2024-05-11 04:07:12 [error]: osu.Framework.Allocation.DependencyNotRegisteredException: The type FooterButtonModsV2+ModCountText+ModTooltip has a dependency on OverlayColourProvider, but the dependency is not registered.
```

**Comment by frenzibyte** [comment]
> I feel like the tooltip for 5+ mods seems to be lacking information in it's current state. Individual mod tooltips show the mod name and settings modified but doesn't in this grouped 5+ mod tooltip. Was recommending to reuse or copy the mod preset tooltip that has this information w/ consistent mod icons.

I went with a different design myself because the purpose of this tooltip is to show what the display couldn't due to its insufficient width. Adding extra information like the name next to the mod feels too much information to me, and even if we add it, it feels weird that we're only showing this extra information *only* when there are too many mods selected.

**Review by peppy — APPROVED** [review]
one step forward

**Pull request merged**
