### PR TITLE
Fix timing points being blocked by buttons in the editor

### LINKED ISSUE #29761: `Select closest to current time` button will block some information
### Type

Cosmetic

### Bug description

Appears in situations where there are many control points

The information of the last few control points is blocked by the button

### Screenshots or videos

image

### Version

2024.906.1

### Logs

NA

### PR DESCRIPTION
**Pull request by SchiavoAnto**
Would fix #29761.

### CODE REVIEW

**Comment by bdach** [comment]
Sound idea but pretty terrible execution. The background shouldn't be peering behind the buttons like it currently is.

osu_2024-09-08_13-43-27

If you can figure out how to give that a background that matches the pieces around it then I think we have something we can ship. Not sure what background colour to give it, maybe try something like `Background2` from `OverlayColourProvider`.

**Review by bdach — CHANGES_REQUESTED** [review]
as above

**Comment by SchiavoAnto** [comment]
I successfully added a background color, `Background2` as you suggested. Tried `Background6` too to be similar to the settings section on the right but thought it looked better with the one you suggested.
Let me know if there are other things to change.

**Comment by bdach** [comment]
@SchiavoAnto I've made a few adjustments here. Please ask if something is unclear.

@peppy requesting double-check for visuals at the least:

osu_2024-09-08_16-31-34

**Review by bdach — APPROVED** [review]

**Comment by peppy** [comment]
Seems fine I think.

**Review by peppy — APPROVED** [review]

**Pull request merged**
