### PR TITLE
Fix potential endless taiko beatmap conversion

### PR DESCRIPTION
**Pull request by smoogipoo**
Visible on https://osu.ppy.sh/beatmapsets/321566#osu/1270556

This eventually also needs a cancellation token too, but it should suffice for now - I don't believe `tickSpacing` can get small and pass this check without the duration also being small since they're both relative to beat length.

### CODE REVIEW

**Comment by peppy** [comment]
Confident this won't break any normal beatmaps?

**Review by peppy — DISMISSED** [review]

**Comment by smoogipoo** [comment]
Hmmm, I'll run this on my set of ranked beatmaps. Should take ~30min. May need to allow at least one hit.

**Comment by smoogipoo** [comment]
There's no differences over my set of 90k ranked/loved/approved beatmaps, so I'm fairly certain this won't break normal beatmaps.

**Comment by smoogipoo** [comment]
Hold off, I got another OOM on my unranked set.

**Comment by smoogipoo** [comment]
Not sure what happened, I think I might've recomputed with stable when I ran into the OOM again.

image

Seems to complete on my set of unranked beatmaps too, so I'll unblock this PR.

**Pull request merged**
