### PR TITLE
Add player settings to multi spectator screen

### PR DESCRIPTION
**Pull request by Sheppsu**
I'm creating this for #29709 so the analysis settings have a place to go, but it's also nice to have the player settings on the multi spectator screen.

Looks like this:

https://github.com/user-attachments/assets/806e9ae3-64d2-4c72-bf63-4485f721d428

### CODE REVIEW

**Comment by peppy** [comment]
If we're going to do this, please make it do the settings expand when moving the cursor near the right of the screen, or when hovering the cog.

**Comment by minisbett** [comment]
How about adding it below the leaderboard and chat instead? With a similar transparency to the chat & how it is in single player

**Comment by Sheppsu** [comment]
Now expands and contracts from hovering the right side of the screen:

https://github.com/user-attachments/assets/e76e7f6d-b459-48b2-b1f5-79fec9247310

**Comment by Sheppsu** [comment]
Makes sense. Changes look good 👍

**Review by peppy — DISMISSED** [review]

**Comment by peppy** [comment]
Requesting a second opinion as I wrote a lot of this now.

**Comment by bdach** [comment]
Are the settings supposed to show during _normal gameplay_...?

https://github.com/user-attachments/assets/1cdc73b7-5c7b-4243-ba40-bfc9e5f5cf3e

I feel like that's not going to go over well with users...

**Comment by peppy** [comment]
Nope, that looks like a regression from my refactors.

**Review by bdach — APPROVED** [review]
seems fine

**Pull request merged**
