### PR TITLE
Include Flashlight in total SR calculation

### PR DESCRIPTION
**Pull request by MBmasher**
Based on https://github.com/ppy/osu/pull/13986 and https://github.com/ppy/osu/pull/14217

https://github.com/ppy/osu/pull/14217 needs to be merged before this.

similarly to https://github.com/ppy/osu/pull/13986, this is just a visual change and affects only total SR.

### CODE REVIEW

**Review by stanriders — DISMISSED** [review]
I'm fine with this, it might be a bit controversial (like some maps being 9+ stars while being mechanically 4*) but I think it's correct way forward and we can adjust if this somehow breaks star rating medals or something else.

**Review by emu1337 — DISMISSED** [review]
Personally I don't think visuals belong in SR but according to the recent community survey on pp & sr, 75% of people want "subjective" skills to be included in star rating, so that would imply that this change should be accepted.

**Review by smoogipoo — APPROVED** [review]

**Comment by peppy** [comment]
If we're going halfway and adding FL into star rating, I'd be curious to hear thoughts on how a "complete blind" beatmap would be rated in star rating. Would it get an infinite rating? Is there an upper cap to the "memorisation" skill? Should we be calling this "Memorisation" rather than "Flashlight" to account for future similar mods (ie. if we are going to also add star rating adjustments for something like "Blinds")?;

**Comment by MBmasher** [comment]
@peppy 
The Flashlight skill was written with the Flashlight mod in mind. In my opinion it's completely fine to have a skill centered around a specific mod. In fact I think it could be a good idea to even make a skill for Hidden in the future. Compare this to mods such as HR and DT, all they do is change timing between objects or certain difficulty attributes, so plays done with those mods could technically be treated as nomod plays.

Flashlight plays are not pure memory plays (as opposed to other mods such as taiko, where HDFL plays are _pure_ memorisation), so I don't think it would be a good idea to encompass **everything** memory into this skill, this should stay separate.

**Comment by peppy** [comment]
So just for me and the 99% that hasn't attempted to understand the math here: how much would you see a 100% memorisation be worth as an addition in star rating? Is that somehow different because it's "not what flashlight does" or soemthing?

**Comment by MBmasher** [comment]
> Is that somehow different because it's "not what flashlight does" or soemthing?

Yes, flashlight is only partly memorisation. I can't provide any insight into what would happen in a 100% memorisation scenario because such scenario doesn't really exist and this Flashlight skill wasn't written to accomodate that. If one were to exist (such as blinds mod) the calculation for that needs to be separate to this.

**Comment by peppy** [comment]
Seems very hand-wavy to me but maybe I'm an outlier and the average player will better understand this.

**Comment by MBmasher** [comment]
Right, I'm just trying to understand what you meant by "how much is a 100% memorisation worth in SR". Is that in the context of Flashlight?

**Comment by peppy** [comment]
I'm not sure. I'd just expect something to be calculated based on the size of visibility from 0 to 100% hidden. But I'm in the camp that doesn't agree this can really be represented in a good way in SR, so I'll just abstain from comment/attempt-to-understand on this occasion.

Maybe something worth factoring in when trying to explain this to the public though.

**Pull request merged**
