### PR TITLE
Fixes for WorkingBeatmap

### PR DESCRIPTION
**Pull request by huoyaoyuan**

### CODE REVIEW

**Comment by peppy** [comment]
Seems like added complexity with no real performance gain. Acquiring non-contended locks is as good as free. Have you actually found cases where this offers an improvement?

Either way, if we are enforcing "use only on x thread" then it needs to be in the public xmldoc for those properties/methods.

**Comment by huoyaoyuan** [comment]
Well, how about setting them during creation? Is anything not fast enough?

**Comment by peppy** [comment]
Not sure what you men by during construction. Main question is: was there an issue in the first place?

**Comment by peppy** [comment]
Shall we get this merged without the locking changes?

**Comment by huoyaoyuan** [comment]
I think removing 2 locks are reducing complexity.
If still unsure about that, I can open a new pull request just fix casing.

**Comment by peppy** [comment]
If we're limiting stuff to a particular thread then ThreadSafety should be used.

Alternately we could just use locks and not limit it...

**Comment by huoyaoyuan** [comment]
Closing and opening a new one for the fix.

**Pull request closed without merging**
