### PR TITLE
Rename "difficulty multiplier" to "score multiplier" and add more animation hinting

### PR DESCRIPTION
**Pull request by peppy**
- [x] Depends on #24801 

Slight vertical bump indicating direction of change of multiplier, and rename to make the actual text make sense. It's not a difficulty multiplier, it's a score multiplier.

https://github.com/ppy/osu/assets/191335/fbdb4834-de82-4483-9e2c-ade4cd3460a2

### CODE REVIEW

**Comment by Joehuu** [comment]
Can we reconsider flipping the red and green colours to indicate the "score" increase/decrease instead of the "difficulty" increase/decrease? Relevant discussion here (read all): https://github.com/ppy/osu/discussions/18194#discussioncomment-2717967.

**Comment by Tanza3D** [comment]
the white flash when the value changes is kind of jarring, i can see the usage of it but probably best to make it a bit less bright?

**Comment by peppy** [comment]
> the white flash when the value changes is kind of jarring, i can see the usage of it but probably best to make it a bit less bright?

I originally had it less bright but the goal was to give the user a cue that it's changing (especially when adjusting settings that may only change it at certain cut-off), and going for anything less bright didn't seem to work great for this.

I'll see if I can reduce it slightly.

**Comment by peppy** [comment]
@Tanza3D Here's an updated version of the flash effect, that both catches attention better and flashes less intensely:

https://github.com/ppy/osu/assets/191335/e2f38639-a25a-4733-8d4a-8ad4a2a42c76

**Comment by Tanza3D** [comment]
ah yeah, i'd say that's better

**Review by bdach — APPROVED** [review]

**Pull request merged**
