### PR TITLE
Disallow binding multiple bindings in a single section to one key

### PR DESCRIPTION
**Pull request by bdach**
- [x] Depends on https://github.com/ppy/osu/pull/25104
- Another part of addressing https://github.com/ppy/osu/issues/24780

https://github.com/ppy/osu/assets/20418176/e82135ef-ccaa-465b-94f2-3f0773dc32ba

I'm still not entirely happy with how this turned out code-wise, but it feels _okay_ to try and PR this. The complicating factors are mostly thus:

- The obvious path is when a conflict is generated by a user attempting to assign a key to a binding that's already taken. But a conflict can also arise when _reverting_ a binding to the default value, if the default key is already assigned to something nonstandard elsewhere. And finally, reverting the entire section _cannot_ lead to a conflict, but that means that you can't write a revert of the whole section as "just revert every binding sequentially" - you have to ignore conflicts when you're doing that.
- Up until now the flow of data was one-directional and without cross-dependencies. Now, changing one binding row may change another, so there needs to be some amount of decoupling between display and the actual writes (so that the user sees what they put in), and something to ensure that if a binding assignment changes another assignment, then both are reloaded. This just kinda takes the nuclear approach and reloads the whole section, but _without_ recreating the drawables (some bindables were added to facilitate this).

Due to diff size migration of users' configs wherein keys are already double-bound, and some extra protections against external tampering, will come as separate pull requests.

### CODE REVIEW

**Comment by peppy** [comment]
In terms of UX, this looks pretty good. I'd maybe consider changing the "Apply new" button to use a "dangerous" button colour, though.

**Comment by bdach** [comment]
> I'd maybe consider changing the "Apply new" button to use a "dangerous" button colour, though.

I did wonder about doing that but wasn't 100% decided on it so I left it be for the time being... Applied though, sure.

**Comment by peppy** [comment]
@bdach I've made some changes (most of which you are already aware of). Can you check that they all look okay to you?

**Review by peppy — DISMISSED** [review]

**Comment by bdach** [comment]
Changes look fine, thanks :+1: I did touch one thing, and it's the... localisations - https://github.com/ppy/osu/pull/25105/commits/ea766b792d886907dbc9862a45556530bc93629a changed the member names, but those aren't actually really surfaced that much to translators, it's the inner localisation keys that are:



so I just updated them to match.

**Review by peppy — APPROVED** [review]

**Pull request merged**
