### PR TITLE
Wait longer before confirming test players are cleaned up

### PR DESCRIPTION
**Pull request by peppy**

### CODE REVIEW

**Comment by smoogipoo** [comment]
This seems super dodgy.

**Comment by peppy** [comment]
`Exit()` has a transition associated with it, which wasn't playing in time.

**Comment by smoogipoo** [comment]
In that case i would rather an until step for the player being exited.

**Comment by peppy** [comment]
Can do

**Comment by smoogipoo** [comment]
Shall we go with this for now then?

**Comment by peppy** [comment]
yeah, rolled back to sane state

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
