### PR TITLE
Use long type where required in multiplayer

### PR DESCRIPTION
**Pull request by smoogipoo**
Went through the database models and noticed these were wrong. Note that `MultiplayerSettings.BeatmapId` is also wrong, but that one's a bit more involved because `BeatmapInfo.OnlineBeatmapId` is also wrong, but that has game-wide impacts.

### CODE REVIEW

**Comment by bdach** [comment]
I've ran a basic string search over `RoomID` and `PlaylistItemID`, and I believe that `APIUserScoreAggregate.RoomID` might need to be changed from `int` to `long` as well? Unsure if oversight, or intentionally left as-is.

**Comment by smoogipoo** [comment]
Good catch, just an oversight.

**Comment by peppy** [comment]
Where are you seeing that `beatmap_id` is wrong? In the database it's generally a `MEDIUMINT` and will only ever potentially expand to `INT` in the future.

**Review by peppy — APPROVED** [review]

**Comment by smoogipoo** [comment]
You're right that it's mediumint in the database. Not sure where I saw that, so all good.

**Pull request merged**
