### PR TITLE
Adjust clock usage in line with framework changes

### PR DESCRIPTION
**Pull request by peppy**
- [x] Depends on https://github.com/ppy/osu-framework/pull/6001.

Very much a draft, PRing for visibility and because all tests pass and game behaves roughly as expected.

- This removes four workarounds/hacks. Wow.
- I've implemented this in the "lowest number of changes" way possible. I had another branch which tried to tidy things up more but it turned out too complex. Will save that for a follow-up.

Hacks removed which should be manually tested:
- https://github.com/ppy/osu/pull/24451
- https://github.com/ppy/osu/pull/20203
- https://github.com/ppy/osu/pull/19973
- https://github.com/ppy/osu/pull/24449

### CODE REVIEW

**Comment by Theighlin** [comment]
Something is not right with playback on some maps. Testing with both PRs up to date as of writing and local checkout.

https://github.com/ppy/osu/assets/53081750/4e4858c7-2c26-44a4-9848-4e74a9d2ce78

https://osu.ppy.sh/beatmapsets/1601364#osu/3315708
https://osu.ppy.sh/beatmapsets/1841885#osu/3783209

**Comment by peppy** [comment]
Thanks, can reproduce. Of note, this doesn't happen when retrying.

**Comment by peppy** [comment]
As usual, this was a regression from an "innocent" code refactor. I've fixed this (framework side) and will push in a bit after I add test coverage.

**Comment by peppy** [comment]
Fixed in 6651bae15ba29ac97b636b08d0673dcd3e227f6b

**Comment by peppy** [comment]
Test failures look relevant here, I'll investigate.

**Review by bdach — APPROVED** [review]
I've read the diff _somewhat_ carefully, tested the workarounds removed mentioned in the OP, playtested some more. I can't see a reason not to merge this at present.

I am _heavily_ leaning on the test coverage, and won't pretend to rule out the possibility of future issues. But this _seems_ to be pretty good as is.

**Pull request merged**
