### PR TITLE
Change the map name from Romanized to Unicode in the map deletion dialog

### PR DESCRIPTION
**Pull request by AmicioEspyy**
#30242 I think just changing “Title” to “TitleUnicode” within the file that handles the dialog should solve the problem.

### CODE REVIEW

**Comment by LittleEndu** [comment]
The issue isn't that the dialog should show one or the other but that the dialog should take into account user settings.
Also the dialog should show both the title *and* the artist in the format the user has selected in the settings

**Comment by Fran4end** [comment]
> The issue isn't that the dialog should show one or the other but that the dialog should take into account user settings. Also the dialog should show both the title _and_ the artist in the format the user has selected in the settings

so the issue is not solved? i would try to contribute, but is my first time, can i try?

**Comment by shinmorisawa** [comment]
> The issue isn't that the dialog should show one or the other but that the dialog should take into account user settings. Also the dialog should show both the title _and_ the artist in the format the user has selected in the settings

yes.

**Review by tryh4rd3rr — CHANGES_REQUESTED** [review]
should take into account user settings.

**Comment by smoogipoo** [comment]
We have `IBeatmapInfo.GetDisplayTitleRomanisable()` that might be enough for this.

**Comment by shinmorisawa** [comment]
> We have `IBeatmapInfo.GetDisplayTitleRomanisable()` that might be enough for this.

i have been playing around with this, but it doesn't seem to be working.

**Comment by peppy** [comment]
There's many other places this is wrong. Fixing just this one seems like a shortcoming.

**Comment by shinmorisawa** [comment]
I have made a pull request fixing this issue. #30274

**Comment by shinmorisawa** [comment]
> We have `IBeatmapInfo.GetDisplayTitleRomanisable()` that might be enough for this.

It is.

**Comment by bdach** [comment]
Superseded by aforementioned pull

**Pull request closed without merging**
