### PR TITLE
Add simple UI control for `OverridableBindable`

### PR DESCRIPTION
**Pull request by frenzibyte**
As in the base commit's description:
> Previously, handling of the custom difficulty values in the Difficulty Adjust mod was quite awkward, as the mod attempted to track both the base difficulty and user adjustments in a single bindable property, which could expectedly fail in some scenarios.
>
> To alleviate that, add an `OverridableBindable` more geared to this use case, that allows switching a bindable between a "base", immutable mode, and a "custom", mutable mode. The former will be used when there are no user difficulty adjustments applied, while the latter shall be used when the user enables adjusting a particular difficulty aspect.

- [ ] Depends on #11387 
- [ ] Depends on ppy/osu-framework#4118
- [ ] Depends on framework bump.

### CODE REVIEW

**Comment by frenzibyte** [comment]
Failure above is known fwiw, which ppy/osu-framework#4118 is fixing.

**Comment by peppy** [comment]
Is this changing this original UX? When checking the "i want to customise this value" what value is it inheriting?

Would be nice for the tests to cover these scenarios to state intent.

**Comment by frenzibyte** [comment]
Yeah actually now when enabling the checkbox, it'll use whatever `CustomValue` has, instead of making `CustomValue` inherit base value first, will fix in the underlying PR.

**Comment by smoogipoo** [comment]
With the recent changes to the DA mod, I don't think this is relevant anymore.

**Pull request closed without merging**
