### PR TITLE
Allow scrolling through DimmedLoadingLayer

### PR DESCRIPTION
**Pull request by EVAST9919**

### CODE REVIEW

**Comment by smoogipoo** [comment]
Is there a reason for this?

**Comment by peppy** [comment]
Definitely need context on where/why/what this is fixing.

**Comment by EVAST9919** [comment]
Example: you can't scroll beatmap overlay while you are looking at scores and decided to change some parameters and waiting for new scores loaded. The same thing can be applied to rankings overlay: you can't scroll it while waiting for stuff to be loaded. 
To be clear: by unability to scroll mean you can't use scroll wheel while hovering loading layer.

**Comment by bdach** [comment]
To clarify: by *scrolling through* you mean something like the following?
```
ParentScrollingContainer      // this will be scrollable with this PR while the child is being loaded
    ChildScrollingContainer   // this is being loaded
        DimmedLoadingLayer
```
I'd say this needs a test scene regardless.

**Comment by EVAST9919** [comment]
Currently this layer blocks any input when visible, and that's expected. But I can't scroll beatmap overlay, while scores are loading and I'm hovering this layer. And in the future this will became a problem for other overlays too. So that's why I decided to allow scrolling.
Screenshot_1

**Comment by peppy** [comment]
Have checked all scenarios where this is used, and believe this is better/more correct feeling behaviour.

**Review by peppy — APPROVED** [review]

**Pull request merged**
