### PR TITLE
Add support for skinnable "retry" sound

### PR DESCRIPTION
**Pull request by peppy**
https://github.com/ppy/osu/discussions/24131

### CODE REVIEW

**Comment by bdach** [comment]
Switching to `DrawableSample` makes the retry sample cut off abruptly as player is exited.

Master:

https://github.com/ppy/osu/assets/20418176/e4c730d9-5f9b-4f11-ba4a-ddce46a20c52

This PR:

https://github.com/ppy/osu/assets/20418176/5535f465-3911-4f7d-9350-0c30d346d672

**Review by bdach — CHANGES_REQUESTED** [review]
see above

**Comment by peppy** [comment]
Not sure how that didn't happen to me in testing more reliably..

**Comment by peppy** [comment]
Luckily the fix wasn't too bad this time..

**Review by bdach — APPROVED** [review]

**Pull request merged**
