### PR TITLE
Fix DateTime display sizing on results screen

### LINKED ISSUE #6592: Date and time spacing issue at result screen
**Describe the bug:** When the date and time is too long, no additional spacing / padding is provided.

This issue happenened on Windows, and when I checked Linux for a similar issue, it isn't an issue as my time was in 24 hour format (no am/pm text). 

**Screenshots or videos showing encountered issue:** 
osu_2019-10-25_00-06-29

**osu!lazer version:** 2019.1021.0

**Logs:** Not needed

### PR DESCRIPTION
**Pull request by peppy**
Closes https://github.com/ppy/osu/issues/6592.

### CODE REVIEW

**Review by frenzibyte — CHANGES_REQUESTED** [review]
What do you think about using a `TextFlowContainer`?

**Comment by peppy** [comment]
I dunno, what's the point?

**Comment by iiSaLMaN** [comment]
It seems more suitable for a fill-flow of sprite texts, nothing more.

**Comment by peppy** [comment]
There's an intentional spacing increase on this display class, though.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
