### PR TITLE
Add resume leniency/delay for scrolling rulesets

### PR DESCRIPTION
**Pull request by vis256**
#10202

### CODE REVIEW

**Comment by peppy** [comment]
I would also hope it is at least applied to all rulesets.

As for countdown, I think it can be added later, on the condition that we match stable 1:1 initially.

**Comment by vis256** [comment]
> Issue mentions all three scrolling rulesets yet this fixes only taiko.

done

> Delay doesn't really "match stable"; in stable the time between pressing Esc and gameplay resume is 800ms. But this only happens because the 800ms is the required time for the pause menu to fully hide on stable ([see relevant code](https://github.com/peppy/osu-stable-reference/blob/013c3010a9d495e3471a9c59518de17006f9ad89/osu!/GameModes/Play/Player.cs#L2979)). Otherwise the unpause is instant.

increased to 800

**Comment by smoogipoo** [comment]
Thanks for the PR. I'm not a big fan of adding the property to `Ruleset` as it leads me to believe our existing support for resumes isn't good enough. Because of that, I've gone ahead and implemented this as a `ResumeOverlay` in https://github.com/ppy/osu/pull/27079, which appears to work correctly and will allow us to display a countdown/etc pretty easily.

**Comment by frenzibyte** [comment]
I'm going to close this in favour of https://github.com/ppy/osu/pull/27079

**Pull request closed without merging**
