### PR TITLE
Resume song after quiting instead of restarting

### PR DESCRIPTION
**Pull request by KrisztianBui**
Fix for https://github.com/ppy/osu/issues/4684

### CODE REVIEW

**Comment by peppy** [comment]
I'm not sure how this change makes sense code-wise. Can you explain how you got to this solution?

**Comment by bkrisztian01** [comment]
Pressing the Quit button calls OnExiting and it goes all the way through, but now I realized pressing the Retry button and Alt+F4-ing does the same thing

**Comment by bkrisztian01** [comment]
There are 3 cases: resume, retry or quit beatmap. I compared the variables in every cases and the only difference was the ValidForResume variable. I updated the pull request.

**Comment by bkrisztian01** [comment]
I fixed the code inspection warnings, can I get an approval?

**Comment by peppy** [comment]
This needs an inline comment explaining what it's doing.

**Comment by peppy** [comment]
Closing as invalid solution. This should be done at song select I believe, and not involve the gameplay clock.

**Pull request closed without merging**
