### PR TITLE
Allow calculating strains trough the beatmap instead overall difficulty and create endpoint for difficulty graph in gameplay

### PR DESCRIPTION
**Pull request by ticotaco72**
will be needed for #2992

### CODE REVIEW

**Comment by ticotaco72** [comment]
Note: this doesn't count sliders in osu and places without hit objects aren't always 0s. I'm thinking about how to include this. I think that possible solution is to add ruleset specific class which will take calculatestrain and beatmap etc. And modify strains. Is it good direction? I'll add this in second pr

**Comment by HoLLy-HaCKeR** [comment]
So this is a replacement for #4479?

**Comment by ticotaco72** [comment]
@HoLLy-HaCKeR no, cause #4479 gives value for strains but including earlier strains and weighting them, and here are raw strains

**Comment by ticotaco72** [comment]
Ready for review. This refactors difficulty calculators a bit, and adds endpoint for graph in gameplay, which adds all needed recalculations, that e.g. when there's no objects the are no strains

**Comment by ticotaco72** [comment]
I'll link it to difficulty graph in other pr soon

**Comment by peppy** [comment]
While cleaning up pull requests, we found that your contributions here were forgotten about either due to dangling reviews or going direction we did not fully agree with. Given its age and inactivity, we're going to close this for now.

If you're still interested in seeing this change happen, either by bringing this pull request up-to-date or re-opening as a fresh one, please let us know in this thread before doing so and we will elaborate on what needs to be done (and whether it's a change we see being mergeable in the future).

**Pull request closed without merging**
