### PR TITLE
Fetch existing private message channels on re-joining

### PR DESCRIPTION
**Pull request by peppy**
- [x] Depends on https://github.com/ppy/osu-web/pull/6139.

### CODE REVIEW

**Comment by smoogipoo** [comment]
I works but when re-joining a PM the initial messages are retrieved in the incorrect order:

image

Unsure whether this is an osu!web problem.

**Comment by peppy** [comment]
Ah yep, that's osu-web side. @nanaya is looking into it.

**Review by smoogipoo — APPROVED** [review]

**Comment by smoogipoo** [comment]
Have approved for merge, in-case there's no additional fixes required osu!side.

**Comment by peppy** [comment]
https://github.com/ppy/osu-web/pull/6145

**Pull request merged**
