### PR TITLE
Add volume dip to track during fail sequence

### PR DESCRIPTION
**Pull request by nekodex**
- [x] Depends on ppy/osu-resources#169
- [x] Depends on resource bump

Pairs with the new gameplay fail sample (ppy/osu-resources#169) to help it remain audible (esp. for louder songs)

### CODE REVIEW

**Review by frenzibyte — COMMENTED** [review]
Code-wise seems fine.

**Comment by peppy** [comment]
Dunno. Let's see what people say.

**Review by peppy — APPROVED** [review]

**Comment by Bryceed** [comment]
There could be an alternative with the jumpscare, an option that can be activated in the menu or integrated in some mode (such as hard rock, hardcore, etc.). 

I was already missing that "awakening" in the standard (and now also in lazer), to regain focus after a while playing the game and some occasions. 

*Jumpscare only happens when we're distracted, and for a game that demands a lot of our focus and being ready to react quickly, it helped a lot in that regard.

**Comment by peppy** [comment]
I don't understand what you're trying to say. Do you dislike the new sound / volume dip?

**Comment by Bryceed** [comment]
It's not a criticism of the current system, I liked it, the question is about the replacement.

Because there are occasions when this "jumpscare" helped to regain focus [at least I can say for myself, the "scare" was only when I was getting distracted], which was good, as I tried to pay more attention in the next attempts.

I feel that with the current system we lost that "Hey, wake up! Pay more attention...", and there is no option (even if it was turned off by default) to have this "feedback" that the game gave us back.

**Comment by peppy** [comment]
By system you mean the new sound? Or am i missing something?

**Comment by Bryceed** [comment]
I believe there were visual changes as well, no? It was something very smooth, I didn't get to look at the source code before

**Comment by peppy** [comment]
There were not.

**Comment by Bryceed** [comment]
Really. I'm sorry I didn't see it before but it got really smooth, at least for me, the scare was something that helped.

But again, it's just a feedback, not a criticism of the current change, but what it ended up taking away from the game.

**Pull request merged**
