### PR TITLE
Fix PerformFromMenuRunner failing if CurrentScreen is null

### PR DESCRIPTION
**Pull request by peppy**
Found this while testing. If the window decoration close button is used to exit the game, there's a potential that a `PerformFromMenu` operation is started which can never resolve the menu (due to the screen already being switched to `IntroTriangles` to play the outro). This means the scheduled operations will continue to run while the game shuts down. During this process, the screen stack may be empty for one (or more?) frames, which causes the nullref.

### CODE REVIEW

**Comment by bdach** [comment]
Seems reasonable - but while we're here, the following also caught my attention:

https://github.com/ppy/osu/blob/6ebb267c66d5135527378b163ae72abb2f308ce1/osu.Game/PerformFromMenuRunner.cs#L139-L143

This is also potentially calling `getCurrentScreen()` again and potentially getting a different screen than `checkCanComplete()` - maybe worth passing it down instead of calling locally?

**Comment by peppy** [comment]
Can we just inline it? Looks like it's only used in one place.

**Comment by bdach** [comment]
Yeah that also works.

**Comment by bdach** [comment]
Have pushed that in. I'm hopefully competent enough to be able to inline a method correctly but you can have a second look to be sure.

**Review by bdach — APPROVED** [review]

**Pull request merged**
