### PR TITLE
Add rate mods "Quick Time" and "Slow Time"

### PR DESCRIPTION
**Pull request by awesomecuber**
Many rhythm games (Etterna comes to mind) have many rate mods such as 1.1x, 1.2x, 0.9x, etc. This allows for players to have virtually any chart be a good difficulty for them.

The gap between nomod and double time is huge, likewise for halftime and nomod. It seems fitting to add more mods in order to make the gaps between rates less vast.

Quick Time is 1.25x (right between nomod and doubletime) and Slow Time is 0.9x (around halfway between halftime and nomod, maybe change to 0.875x?). The score multiplier for Slow time is 0.7x and the score multiplier for Quick Time is 1.2x (I changed Double Time multiplier to 1.4x). I'd be flexible with change in any of this.

Mod icons and the name of the mods should probably be changed lol

### CODE REVIEW

**Comment by abraker95** [comment]
I think it's better to have a selection of rates instead adding mods for each individual rate.

**Comment by awesomecuber** [comment]
> I think it's better to have a selection of rates (and possibly custom ones too) instead adding mods for each individual rate.

I probably agree with you, but that's a pretty big departure from what's currently in place. Perhaps that should be the end goal, but for now I think adding a couple more mods is an immediate improvement.

**Comment by peppy** [comment]
I'm also unsure if adding more mods is the correct direction, but maybe there's no harm in adding these until we have mod settings implemented?

**Comment by iiSaLMaN** [comment]
What do you think about adding it as a multi mod, after nightcore, so the cycle will go DoubleTime -> Nightcore -> QuickTime -> ...

**Comment by awesomecuber** [comment]
> I'm also unsure if adding more mods is the correct direction, but maybe there's no harm in adding these until we have mod settings implemented?

I think it's unquestionably an improvement over what is currently implemented.


> What do you think about adding it as a multi mod, after nightcore, so the cycle will go DoubleTime -> Nightcore -> QuickTime -> ...

Quick Time is currently before Double Time in the multi mod (and Slow Time is before Half Time), which makes sense to me since then the rate progressively increases/decreases.

**Comment by iiSaLMaN** [comment]
> Quick Time is currently before Double Time in the multi mod (and Slow Time is before Half Time), which makes sense to me since then the rate progressively increases/decreases.

Will definitely uncomfortable to stable users.

**Comment by awesomecuber** [comment]
> > Quick Time is currently before Double Time in the multi mod (and Slow Time is before Half Time), which makes sense to me since then the rate progressively increases/decreases.
> 
> Will definitely be uncomfortable to stable users.

That's true, I would be flexible to reordering the mods. Personally, I value internal consistency over similarity to stable, but I totally understand the concern.

**Comment by TPGPL** [comment]
maybe instead of adding additional mods modyfing beatmap's speed, there would be a slider changing beatmap's speed; feels like a more suitable solution

**Comment by awesomecuber** [comment]
> maybe instead of adding additional mods modyfing beatmap's speed, there would be a slider changing beatmap's speed; feels like a more suitable solution

Maybe I'm too attached to my own proposal lol, but I feel like just being able to use any rate (or increments of 0.1x or 0.05x) wouldn't feel like osu! anymore. By adding these two mods, the player is able to challenge themselves on vastly more maps while not being confusing or clunky to use.

That being said, maybe it is objectively better to have a slider or something to select rate. But that doesn't exist currently, and adding these two mods is an objective improvement for now. I really appreciate the discussion!

**Comment by iiSaLMaN** [comment]
> > maybe instead of adding additional mods modyfing beatmap's speed, there would be a slider changing beatmap's speed; feels like a more suitable solution
> 
> Maybe I'm too attached to my own proposal lol, but I feel like just being able to use any rate (or increments of 0.1x or 0.05x) wouldn't feel like osu! anymore. By adding these two mods, the player is able to challenge themselves on vastly more maps while not being confusing or clunky to use.
> 
> That being said, maybe it is objectively better to have a slider or something to select rate. But that doesn't exist currently, and adding these two mods is an objective improvement for now. I really appreciate the discussion!

Maybe add the slider as a custom option in the mod select overlay and selecting DT / HT will set the slider automatically, possibly a bindable that automatically selects DT / HT if matches the time rate or a hidden mod will be selected and shown in `HUDOverlay.ModDisplay` if the time rate is custom "Custom Time?", that should be comfortable for stable users and new users.

**Comment by awesomecuber** [comment]
> Maybe add the slider as a custom option in the mod select overlay and selecting DT / HT will set the slider automatically, possibly a bindable that automatically selects DT / HT if the slider value matches the time rate or a hidden mod will be selected and shown in `HUDOverlay.ModDisplay` if the time rate is custom "Custom Time?", that should be comfortable for stable users and new users.

Looking from the perspective of the player, this to me seems more complicated than just picking a system and sticking with it. If a slider is implemented, I have faith in the players to be able to drag the slider to 1.5x if they want to play to what they know as DT. If there is no slider implemented, then there's no reason to have a confusing "Custom Time" mod.

**Comment by iiSaLMaN** [comment]
By complicated, do you mean to the end-user or the developer? if the end-user, I don't think so, the slider will change itself if the end-user selects DT or HT mod, Custom Time will only appear once the end-user goes to that slider and pick a custom timing, as the slider will go to the bottom of the mod select overlay in "custom" category or something

**Comment by awesomecuber** [comment]
> By complicated, do you mean to the end-user or the developer? if the end-user, I don't think so, the slider will change itself if the end-user selects DT or HT mod, Custom Time will only appear once the end-user goes to that slider and pick a custom timing, as the slider will go to the bottom of the mod select overlay in "custom" category or something

So you want to have rate-change mods and a rate-change slider both be in the mod selection screen at the same time? My stance is basically that if we're opting to include many increments for rates, we might as well remove the rate-change mods and use a slider. That's simpler than having both and will be easy for stable users to get accustomed to.

I'm not so sure that having that many possible rates is a great idea in the first place (for osu!standard), but that's a separate discussion. Regardless, I think we all agree that having a few additional mods for rates is vastly better than just having DT and HT.

**Comment by abraker95** [comment]
The biggest issue I have with this is that, while a step in the right direction, it also seems like a step in the wrong direction. While offering more rates to play with is cool, I feel it's a feature better suited for when mod settings is a thing. In my opinion, adding two additional rates as mods feels like a burn to a wound because this seems like so little compared to what is actually desired.

**Comment by iiSaLMaN** [comment]
> The biggest issue I have with this is that, while a step in the right direction, it also seems like a step in the wrong direction. While offering more rates to play with is cool, I feel it's a feature better suited for when mod settings is a thing. In my opinion, adding two additional rates as mods feels like a burn to a wound because this seems like so little compared to what is actually desired.

You should've opened a proposal issue before PR-ing to know what would be better for it.

**Comment by awesomecuber** [comment]
> The biggest issue I have with this is that, while a step in the right direction, it also seems like a step in the wrong direction. While offering more rates to play with is cool, I feel it's a feature better suited for when mod settings is a thing. In my opinion, adding two additional rates as mods feels like a burn to a wound because this seems like so little compared to what is actually desired.

I don't get that impression when playing with the new mods. My impression is that this is a good balance between the simplicity of having mods for rates and the benefit of more play options. As a player, I feel that having these extra mods bridge the gap between nomod and DT (and nomod and HT), and I don't really feel the need to be able to have the granular control over the rate that a slider would provide.

> You should've opened a proposal issue before PR-ing to know what would be better for it.

My bad! I'm new to this. This took me like 10 minutes to do so I'm not too heartbroken if it turns out that this is deemed a negative addition.

**Comment by peppy** [comment]
Thanks for the discussion points.

Let's save this for when we realise mod-level settings. I think we can wait a bit longer and it will lead to a more elegant implementation.

**Pull request closed without merging**
