### PR TITLE
Fix touch device difficulty reduction not affecting star rating

### PR DESCRIPTION
**Pull request by stanriders**
This should fix TD scores getting star rating achievements and also makes calculating TD star rating possible.

SR is calculated as `x^0.8`.

### CODE REVIEW

**Review by apollo-dw — DISMISSED** [review]

**Comment by smoogipoo** [comment]
The intention here is for this to apply to osu-stable as well, correct?

**Comment by peppy** [comment]
This is a pretty big change right? @apollo-dw does the approval mean you've already looked at the statistical changes of this somewhere else? Would be good to link that in this PR if so.

Personally I'm not sure about this, and would need know more about how the number was attained.

**Comment by smoogipoo** [comment]
> would need know more about how the number was attained.

The number seems to have just been transferred from ppcalc -> diffcalc, so it's factored into the aim attribute rather than being considered after the fact when calculating PP. But values shouldn't change as a result.

My primary concern is performance, not sure how many mod combinations is too many to have if we're still writing everything to the DB rather than processing on the fly as I suggested we do (via `osu-beatmap-difficulty-lookup-cache`).

**Comment by peppy** [comment]
Right, I see..

**Comment by stanriders** [comment]
> The intention here is for this to apply to osu-stable as well, correct?
Correct, this change is mostly a fix for the achievements

> This is a pretty big change right? 
Currently the same reduction is being applied in pp calc, so no, PP shouldn't change at all

**Comment by apollo-dw** [comment]
Yeah, there should be no value changes.



> not sure how many mod combinations is too many

For the record, the only other mod I can foresee being added into the combinations as far as stable goes is HD - in case there was number crunching you were intending to do.

**Comment by smoogipoo** [comment]
@Ephemeralis what's your thoughts on this w.r.t medals?

**Comment by Ephemeralis** [comment]
Missed this, sorry.

I don't think we've ever actually considered TD in the design of any achievement. If the broad consensus is to directly scale difficulty downwards on TD plays then I have no qualms with keeping things consistent and having that apply to medals/achievements as well.

**Comment by smoogipoo** [comment]
I pinged you because there was no consensus, and thought you might know. What would you suggest, a twitter survey or something?

**Comment by Ephemeralis** [comment]
An osugame or peppy twitter 24hr one would probably get you enough of an indication to act on, yeah. I don't imagine it's a hugely controversial topic given how few people actually play TD these days.

It does kind of have implications for mobile in the future though, come to think of it.

**Comment by stanriders** [comment]
From my observation, usually most of the people don't consider TD pass/FC medals "real" and some even want them revoked. Difficulty is already being scaled down directly, this is just a matter of visualizing. As for mobile, it would probably need a proper calculation done instead of aim*0.8 anyway, I remember @yeahbennou did something in regards of TD calculation

**Comment by peppy** [comment]
I think we should decide whether this should be added to the next diffcalc batch, or close it for now and revisit later.

**Comment by stanriders** [comment]
> I think we should decide whether this should be added to the next diffcalc batch, or close it for now and revisit later.

I believe that's up to @Ephemeralis ? There aren't any logic or pp changes here, just medals awarding pretty much

**Comment by Ephemeralis** [comment]
Did we not end up running a poll on this? It's definitely not a call I feel comfortable making, because while I can understand people are fairly critical of TD as an input style, it's a bit of a huge thing to just kind of blanket prevent them from attaining star medals.

I have no idea how to really fairly handle this. Increase the SR requirements for TD plays by like... some random percentage to reflect the ease of play? 33%? I seriously have no clue.

**Comment by peppy** [comment]
If it's just about medal awarding, can we see spreadsheets from this change to determine whether it actually makes any of the medals unachievable?

**Comment by stanriders** [comment]
> I have no idea how to really fairly handle this. Increase the SR requirements for TD plays by like... some random percentage to reflect the ease of play? 33%? I seriously have no clue.

This is pretty much what it does - makes **aim** SR requirement for medals 20% higher. PP for TD plays is already scaled down by (roughly) 20% on aim so I don't see why medals should differ here. 

Ideally, again, TD star rating should be calculated properly instead of just blanket nerfing, but that's a task for some other time.

**Comment by Ephemeralis** [comment]
This sounds reasonable enough, then. 

I don't think this'll make anything non-achievable at a glance through existing medal designs - the main ones it'll affect are the progression pass/FC medals for the higher SR variants. There's a good argument to make there that we should have an entirely different course of TD-specific SR pass/FC medals (since they're very different skillsets), and that something that can be perhaps looked at when mobile play (and therefore wider TD adoption) becomes more prevalent. For the meantime, this seems fine.

**Comment by smoogipoo** [comment]
Should this also be removed from `computeFlashlightValue()`?

**Comment by stanriders** [comment]
> Should this also be removed from `computeFlashlightValue()`?

@MBmasher does TD make flashlight any easier?

**Comment by MBmasher** [comment]
I mean TD already affects FL pp so yeah that should be changed

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
