### PR TITLE
Implement IControlPointInfo interface

### PR DESCRIPTION
**Pull request by Peter-io**
As mentioned in https://github.com/ppy/osu/issues/2583

BeatmapDifficulty already has interface but ControlPointInfo does not

### CODE REVIEW

**Comment by bdach** [comment]
Is there a point to this, or is this adding an interface for the sake of adding an interface? Because if it's the latter then I'm not particularly interested.

**Comment by Peter-io** [comment]
> Is there a larger point to this, or is this adding an interface for the sake of adding an interface? Because if it's the latter then I'm not particularly interested.
Mainly to address issue I linked

**Comment by bdach** [comment]
Except this doesn't address the linked issue and it's even apparent from the diff. If it did, I'd expect _many_ more changes from the enforced mutability.

Why? Sure, you've added an interface there, but _there are still mutation operation exposed on the interface_. Example: `IControlPointInfo` exposes `ControlPointGroup`s which are freely mutable via `Add()`/`Remove()`. The groups contain `ControlPoint`s which are again freely mutable.

If this is to address the linked issue then you'll have to apply readonly interfaces _all the way_ in the class graph. At which point you're likely to run into https://github.com/ppy/osu/pull/25467-level issues which we still as a core team have not developed an answer for.

**Comment by Peter-io** [comment]
> Except this doesn't address the linked issue and it's even apparent from the diff. If it did, I'd expect _many_ more changes from the enforced immutability.
> 
> Why? Sure, you've added an interface there, but _there are still mutation operation exposed on the interface_. Example: `IControlPointInfo` exposes `ControlPointGroup`s which are freely mutable via `Add()`/`Remove()`. The groups contain `ControlPoint`s which are again freely mutable.
> 
> If this is to address the linked issue then you'll have to apply readonly interfaces _all the way_ in the class graph. At which point you're likely to run into #25467 issues which we still as a core team have not developed an answer for.


Alright i see now thanks for mentioning this

**Pull request closed without merging**
