### PR TITLE
Add pinned comment section in comment container

### PR DESCRIPTION
**Pull request by gagahpangeran**
Screenshot from 2021-08-13 19-43-26

### CODE REVIEW

**Review by frenzibyte — DISMISSED** [review]
Since pinned comments are also included in the `response.Comments` collection when requesting comments of a "commentable type", that can cause components such as the "no comments placeholder" to no longer appear when there's only pinned comments in `Comments`.

---

Also, the spacing applied on the flow containing the username and the pinned tag is incorrect, that was already there but might as well change it here and not make the pinned tag look silly:

CleanShot 2021-08-13 at 17 29 57

(notice all `.comment__row-item`s apply a margin of 5px horizontal and 2px vertical)

---

Also also tests currently fail on `TestSceneOfflineCommentsContainer` due to `PinnedComments` not initialised in the returned test comment bundle.

**Comment by gagahpangeran** [comment]
> Since pinned comments are also included in the `response.Comments` collection when requesting comments of a "�commentable type", that can cause components such as the "no comments placeholder" to no longer appear when there's only pinned comments in `Comments`.

osu-web doesn't show no comments placeholder when there's only pinned comment.

Screenshot from 2021-08-13 22-48-11

**Comment by frenzibyte** [comment]
How does that look in osu!lazer? seems fine if it matches how web displays it, I was imagining it to show 0px height on the content area leaving only the comments header at the bottom of the comments container.

**Comment by gagahpangeran** [comment]
It's same.

Screenshot from 2021-08-13 23-46-39

**Comment by frenzibyte** [comment]
FWIW this is still missing the spacing change to make the pinned tag layout, as I mentioned in my previous review:
> Also, the spacing applied on the flow containing the username and the pinned tag is incorrect, that was already there but might as well change it here and not make the pinned tag look silly:
> 
> CleanShot 2021-08-13 at 17 29 57
> 
> (notice all `.comment__row-item`s apply a margin of 5px horizontal and 2px vertical)

It currently has 10px spacing applied.

**Comment by bdach** [comment]
I don't follow. The margin is 5px horizontal for both items, so 10px spacing would be correct? Margins do not fold into each other.

If anything is missing it's at most the 2px vertical one.

**Comment by frenzibyte** [comment]
Right, nevermind. Seems the font scaling on osu!lazer made me think it's supposed to be 5px spacing while it's actually correct currently.

**Review by bdach — DISMISSED** [review]

**Comment by bdach** [comment]
Going to temporarily block pending resolution of https://github.com/ppy/osu-web/issues/8007.

**Review by peppy — APPROVED** [review]

**Pull request merged**
