### PR TITLE
Fix lounge sub screen loading layer displaying in the background

### PR DESCRIPTION
**Pull request by frenzibyte**
Now displaying over the rooms container, exactly as it was before.

https://user-images.githubusercontent.com/22781491/129881043-747d2c7d-d2e7-43b1-b26e-4fd1b1ab60cb.mp4

### CODE REVIEW

**Comment by smoogipoo** [comment]
This was an intentional change. But I think it does look silly for the _spinner_ to be in the background.

**Comment by frenzibyte** [comment]
Yeah, thought it's supposed to be after the rooms container as it was originally, what was the reason behind having it in the background?

**Comment by smoogipoo** [comment]
Because it dims the whole background rather than a box.

**Comment by frenzibyte** [comment]
Since the lounge already has a dark background, what do you think about hiding the dim itself:

https://user-images.githubusercontent.com/22781491/129889405-87739fe9-abdb-4ccc-b740-dcb9577e32e6.mp4

**Comment by peppy** [comment]
This regresses the reason I moved it.

**Comment by frenzibyte** [comment]
Yeah, I'll have a think about this.

**Comment by frenzibyte** [comment]
I've flipped the layout around to make the loading layer block the rooms area, while it extends the full screen, and keep the header at the top in front of it.

CleanShot 2021-08-19 at 04 07 01

**Comment by frenzibyte** [comment]
Regarding the above test failures, they have regressed by https://github.com/ppy/osu/pull/14274 but were hidden until now due to the loading layer not actually blocking anything previously.

The regression was that previously playlists test scenes were able to function properly by having an `InitialRoomsReceived` bindable that's set to true by default in `BasicTestRoomManager`, but since now that bindable has been moved to the `ListingPollingComponent`, there's no possible and simple way to set that bindable directly from a test scene.

One solution I have (and which I've pushed) is refactoring `BasicTestRoomManager` to become like `TestRequestHandlingMultiplayerRoomManager` and handle all API requests and trigger success on them, and have the logic shared between them. Seems to pass on visual testing, but waiting for CI results now.

**Comment by peppy** [comment]
@smoogipoo need your review on the testing changes for sanity.

**Review by peppy — APPROVED** [review]
Looks okay from a drawable / UI perspective.

**Review by smoogipoo — APPROVED** [review]
Good stuff on the tests, I'd hoped to do this eventually.

**Pull request merged**
