### PR TITLE
Refactor and fix intermittent beatmap difficulty cache tests

### PR DESCRIPTION
**Pull request by frenzibyte**
As it was pointed out that the queues aren't really testing anything given that bindable changes get canceled when another one comes, I've removed them from the test scene, resolving intermittent test failures along with it.

### CODE REVIEW

**Comment by smoogipoo** [comment]
This won't resolve the intermittent test failures. Those will be caused by everything being async, and you're using `AddAssert`.

**Comment by frenzibyte** [comment]
Although they work asynchronously, the method for computing the value (`ComputeValueAsync`) is overriden to return `Task.FromResult(new StarDiffuclty(...))` to avoid the computation from taking any longer.

It should only take one update frame for the bindable to update, but I might be misunderstanding.

**Comment by smoogipoo** [comment]
`GetDifficultyAsync()` invokes `GetAsync()` which internally has an `await` that fires off a task, and it also has a `ContinueWith` on top of that which fires another task, that then schedules the bindable value update.

**Comment by frenzibyte** [comment]
I've switched to until steps now for extra safety.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
