### PR TITLE
Allow cancelling existing download request of a model

### PR DESCRIPTION
**Pull request by frenzibyte**
- Adds a method to cancel existing download request of a model.
- Dependency for resolving #6125

### CODE REVIEW

**Comment by peppy** [comment]
I'm not sure why the notification change is required (and the addition of the "package" class). Can't you just use the existing code and cancel the request?

**Comment by iiSaLMaN** [comment]
> I'm not sure why the notification change is required (and the addition of the "package" class). Can't you just use the existing code and cancel the request?

If it's fine for the notifications to remain there as `Cancelled`, sure.

**Comment by peppy** [comment]
The discord link doesn't work. Please post here what you need to ask.

**Comment by iiSaLMaN** [comment]
I was asking you if cancelling a download request from out of the notifications overlay should close the downlaod notification immediately or keep it, I went with closing it immediately.

Here's how it looks with keeping the notification: https://streamable.com/mw39s

**Comment by peppy** [comment]
That looks fine for now.

**Pull request closed without merging**
