### PR TITLE
add search to options overlay

### PR DESCRIPTION
**Pull request by jorolf**

### CODE REVIEW

**Comment by peppy** [comment]
You can't code like this.

You need to make a common container to contain common logic. You can't just copy and paste logic across n classes.

**Comment by peppy** [comment]
Also I'm pretty sure `SearchContainer` should just be made into a flow container. because every scenario i can ever think of it being used will be a flow container.

if not we're just going to have all these local implementations across the codebase.

**Review by peppy — CHANGES_REQUESTED** [review]
see comments

**Comment by Jorolf** [comment]
So should I create a OptionContainer that implements IFilterable and override FilterTerms in the Option classes (OptionSlider, OptionDropdown, etc.)?

**Comment by peppy** [comment]
I would say that options in general need some reworking to separate the contained control from the container that holds it.

For instance, we want the ability to "revert to default" like in osu-stable, which is currently going to be a pain to implement. I think we need an OptionItem class which is then passed a bindable control (`OsuCheckbox`, `OsuSlider` etc.) as a parameter.

I'll probably look into this today as it will likely be quite a large change.

**Comment by peppy** [comment]
Please rebase/reimplement on top of https://github.com/ppy/osu/pull/718.

**Pull request closed without merging**
