### PR TITLE
Add card size switcher to beatmap listing overlay

### PR DESCRIPTION
**Pull request by bdach**
Probably going to call wraps on #14216 with this one, if it passes review.

https://user-images.githubusercontent.com/20418176/147287819-75576386-cc46-4214-97dd-7af219bbb9a9.mp4

I'm not happy with the fact that this adds another async process to the beatmap listing overlay. I know that web does this instantly, but on the other side, for there to be *no* loads, all card sizes would have to reside in one drawable and change on the fly, [judging by the designs](https://www.figma.com/file/bONtBvDRWNfOuiYpueD2ms/Web%2FSearch-Result-(with-Beatmap-Listing)?node-id=46%3A248). And there are [six card sizes designed](https://www.figma.com/file/oYJ9WkzXGvbPWBz6NxeyGr/UI%2FBeatmap-Card?node-id=112%3A2350), with quite subtle but substantial differences in appearance and behaviour. As such, my confidence of making all six work in a single drawable implementation without it devolving to an inscrutable mess is near zero, unless they are substantially streamlined to make this more feasible.

I also toyed with another approach, namely adding a `SwitchableBeatmapCard` that would nest a card of the correct size and `LoadComponentAsync()` the right one once a card size switch was requested ([see this branch](https://github.com/ppy/osu/compare/master...bdach:beatmap-card/extra-on-listing-BUSTED-2?expand=1)), but unfortunately that turned out to be prohibitively slow to the point of dipping FPS into the single digits, most likely due to incurring hundreds of individual `LoadComponentAsync()` calls, saturating the thread pool and causing extensive CPU load.

Note that the card size setting is not persisted anywhere. Web seems to silently persist it in local storage, without a visible setting in the account settings screen, but then also uses that local storage value on other screens (like the user profile) that don't have a size switcher. Not super sure about this behaviour so I didn't implement it.

### CODE REVIEW

**Comment by peppy** [comment]
The async load is super unfortunate (web does this much better than us as a result) and also caused my game to stutter. I can see this as being fine in the short run, but needs to be resolved at a later point.

Curious if there's a reason the larger size is more wide than the normal one? My expectations are that width shouldn't change, similar to osu-web.

**Comment by bdach** [comment]
> I can see this as being fine in the short run, but needs to be resolved at a later point.

Do you have any ideas about how that could be done? Because to be honest I'm not sure I do, at least not without significantly streamlining designs as I mentioned in the OP 

> Curious if there's a reason the larger size is more wide than the normal one?

The dimensions of both sizes (height & width) were taken directly from figma. Not sure how it came out that web does variable width, but that is going to be somewhat tricky to achieve due to spacings between cards (putting 0.5 relative width won't work reliably in fill flows), and I've also seen informal opinions that not forcing 2 cards per line is nicer because it allows more stuff to fit on the screen.

**Comment by peppy** [comment]
Variable width is something we can figure out later, but they should match for now at least.

**Comment by peppy** [comment]
I think this is okay for now. There's some performance concerns with the fact that 16,000 drawables for a single page of results can cause update and draw spikes, but as this is an online overlay (and the issue is also present on `master`) that can be resolved at a later point in time. Quite low priority for now.

Also think the code quality of `BeatmapListingOverlay` is quite lacking, but that's not this PR's fault. Needs a rewrite at some point.

@bdach please check over my last two commits and make sure you're okay with the changes.

**Review by peppy — APPROVED** [review]

**Comment by bdach** [comment]
Latest changes look good, thanks :+1:

**Pull request merged**
