### PR TITLE
Set Correct values for addDelayedMovements() function

### PR DESCRIPTION
**Pull request by johnneijzen**
it is duplicate from the one on line 97.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Here's the relevant code from osu!stable:

```
                    //Make the cursor stay at a hitObject as long as possible (mainly for autopilot).
                    if (h.StartTime - HitObjectManager.HITTABLE_RANGE > last.EndTime + hitObjectManager.HitWindow50 + 50)
                    {
                        if (!(last is Spinner) && h.StartTime - last.EndTime < 1000) AddFrameToReplay(replay, new bReplayFrame(last.EndTime + hitObjectManager.HitWindow50, last.EndPosition.X, last.EndPosition.Y, pButtonState.None));
                        if (!(h is Spinner)) AddFrameToReplay(replay, new bReplayFrame(h.StartTime - HitObjectManager.HITTABLE_RANGE, h.Position.X, h.Position.Y, pButtonState.None));
                    }
                    else if (h.StartTime - hitObjectManager.HitWindow50 > last.EndTime + hitObjectManager.HitWindow50 + 50)
                    {
                        if (!(last is Spinner) && h.StartTime - last.EndTime < 1000) AddFrameToReplay(replay, new bReplayFrame(last.EndTime + hitObjectManager.HitWindow50, last.EndPosition.X, last.EndPosition.Y, pButtonState.None));
                        if (!(h is Spinner)) AddFrameToReplay(replay, new bReplayFrame(h.StartTime - hitObjectManager.HitWindow50, h.Position.X, h.Position.Y, pButtonState.None));
                    }
                    else if (h.StartTime - hitObjectManager.HitWindow100 > last.EndTime + hitObjectManager.HitWindow100 + 50)
                    {
                        if (!(last is Spinner) && h.StartTime - last.EndTime < 1000) AddFrameToReplay(replay, new bReplayFrame(last.EndTime + hitObjectManager.HitWindow100, last.EndPosition.X, last.EndPosition.Y, pButtonState.None));
                        if (!(h is Spinner)) AddFrameToReplay(replay, new bReplayFrame(h.StartTime - hitObjectManager.HitWindow100, h.Position.X, h.Position.Y, pButtonState.None));
                    }
```

It looks like one of these conditionals is wrong.

**Review by smoogipoo — CHANGES_REQUESTED** [review]
As commented.

**Comment by johnneijzen** [comment]
i have look up HitResult
HitResult.Great = 300
HitResult.Good = 100
HitResult.Meh = 50
HitResult.Miss = 0

based on osu!stable code I think
first condition supposed to be HitResult.Miss
second condition supposed to be HitResult.Meh
third condition supposed to be HitResult.Good

**Comment by smoogipoo** [comment]
Sounds about right

**Comment by johnneijzen** [comment]
Found Cause of this mistake it happen during this commit
https://github.com/ppy/osu/commit/b15f184261885ce7ca032737cdf0043fe8895938#diff-6a517b1f5ef61bdcc38d771d55109c98

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
