### PR TITLE
Fix settings section not being selected when the search term changes

### PR DESCRIPTION
**Pull request by rednir**
Currently in `SectionsContainer` the selected section only updates on scroll. This PR makes it so the selected section also updates when the number of present children change (for instance when the search term changes)

Master:
https://user-images.githubusercontent.com/10225220/130475573-64e08ce0-1884-4fcd-87ca-415afcd4e5f5.mp4

This change:
https://user-images.githubusercontent.com/10225220/130475578-2178291e-228b-46a7-9df1-0c09aca66f29.mp4

### CODE REVIEW

**Comment by peppy** [comment]
This seems like a pretty inefficient method. You're running two LINQ calls each update method.

Might work better to handle invalidation of some kind and just null the `lastKnownScroll`value at that point.

**Comment by rednir** [comment]
Made that a lot more complicated than it needed to be.

**Comment by peppy** [comment]
Not quite what I meant, but that does look like a saner change. I *did* think I added handling for this.. was just being bypassed.

**Review by bdach — APPROVED** [review]
seems fair

**Review by frenzibyte — APPROVED** [review]

**Pull request merged**
