### PR TITLE
Add timeline support for hit objects with multiple combos and multiple internal durations

### PR DESCRIPTION
**Pull request by OliBomby**
Part of #21499

### CODE REVIEW

**Review by peppy — COMMENTED** [review]
As commented

**Comment by OliBomby** [comment]
> Ignoring the test failures, I'm really not digging this direction.
> 
> It's adding a lot of complexity to the way combos, hitobjects, nested objects work. It feels to me that too much of the hitobject hierarchy is changing just to allow an editor tool to exist.
> 
> Consider a scenario where new hitobjects are added and start to use these interfaces in new and unknown ways. I would have no idea whether they will be handled correctly. There's no clear definition over what the `RelativeTime` / multiple combos would/should be used for.

Maybe we can refine the interfaces a bit so their purpose is clear and it cant be misused.

> I'm just wondering if this is the correct way forward, as opposed to having the stream tool in the editor which can be used to create the stream then "render it out" to hit circles, avoiding the changes required to hitobjects. I could imagine this being done by storing and updating the combos of individual hitcircles from within the blueprint tool's code.

I really wanted to have the stream creation tool interact with the timeline because allows the user to see the times of all the control points which makes the UX a whole lot more intuitive. This is the best solution i could find to make it happen, because the timeline requires hitobjects and it addresses the concern of supporting more custom hitobjects.

**Comment by peppy** [comment]
@OliBomby could you please see if this will work?

```diff
diff --git a/osu.Game.Tests/Visual/Editing/TestSceneTimelineHitObjectBlueprint.cs b/osu.Game.Tests/Visual/Editing/TestSceneTimelineHitObjectBlueprint.cs
index 5a14ecb416..9543390474 100644
--- a/osu.Game.Tests/Visual/Editing/TestSceneTimelineHitObjectBlueprint.cs
+++ b/osu.Game.Tests/Visual/Editing/TestSceneTimelineHitObjectBlueprint.cs
@@ -12,6 +12,7 @@
 using osu.Framework.Graphics.UserInterface;
 using osu.Framework.Testing;
 using osu.Game.Graphics.UserInterface;
+using osu.Game.Rulesets.Objects;
 using osu.Game.Rulesets.Objects.Types;
 using osu.Game.Rulesets.Osu.Objects;
 using osu.Game.Screens.Edit.Compose.Components.Timeline;
@@ -97,7 +98,7 @@ public void TestMultipleDurationObjects()
             AddStep("add object with multiple durations", () =>
             {
                 EditorBeatmap.Clear();
-                EditorBeatmap.Add(new TestMultipleRelativeTimeHitObject(2700, 500, 3));
+                EditorBeatmap.Add(new TestMultipleRelativeTimeHitObject(2700, 500, 10));
             });
 
             AddStep("hold down last drag bar", () =>
@@ -135,7 +136,7 @@ public void TestMultipleDurationObjects()
             AddAssert("object has later time", () => EditorBeatmap.HitObjects.OfType<IHasMultipleRelativeTimes>().Single().TimeObjects[^2].RelativeTime > lastTime);
         }
 
-        public class TestMultipleRelativeTimeHitObject : OsuHitObject, IHasMultipleRelativeTimes, IHasMultipleComboInformation
+        public class TestMultipleRelativeTimeHitObject : HitObject, IHasMultipleRelativeTimes, IHasMultipleComboInformation
         {
             public double EndTime => StartTime + Duration;
             public double Duration { get => comboTimeObjects.Last().RelativeTime; set => comboTimeObjects.Last().RelativeTime = value; }
diff --git a/osu.Game/Beatmaps/BeatmapProcessor.cs b/osu.Game/Beatmaps/BeatmapProcessor.cs
index 625c5beabd..f895c1a18b 100644
--- a/osu.Game/Beatmaps/BeatmapProcessor.cs
+++ b/osu.Game/Beatmaps/BeatmapProcessor.cs
@@ -1,9 +1,6 @@
 ﻿// Copyright (c) ppy Pty Ltd <contact@ppy.sh>. Licensed under the MIT Licence.
 // See the LICENCE file in the repository root for full licence text.
 
-#nullable disable
-
-using System.Linq;
 using osu.Game.Rulesets.Objects.Types;
 
 namespace osu.Game.Beatmaps
@@ -22,21 +19,20 @@ public BeatmapProcessor(IBeatmap beatmap)
 
         public virtual void PreProcess()
         {
-            IHasComboInformation lastObj = null;
+            IHasComboInformation? lastObj = null;
 
             bool isFirst = true;
 
-            foreach (var hitObject in Beatmap.HitObjects.OfType<IHasComboInformation>())
+            foreach (var hitObject in Beatmap.HitObjects)
             {
-                if (hitObject is IHasMultipleComboInformation mult)
+                if (hitObject is IHasComboInformation combo)
+                    process(combo);
+
+                foreach (var nested in hitObject.NestedHitObjects)
                 {
-                    foreach (var comboObject in mult.ComboObjects)
-                    {
-                        process(comboObject);
-                    }
+                    if (nested is IHasComboInformation nestedCombo)
+                        process(nestedCombo);
                 }
-                else
-                    process(hitObject);
 
                 void process(IHasComboInformation obj)
                 {
diff --git a/osu.Game/Rulesets/Objects/HitObject.cs b/osu.Game/Rulesets/Objects/HitObject.cs
index 0d9ca855fc..55ae0a9857 100644
--- a/osu.Game/Rulesets/Objects/HitObject.cs
+++ b/osu.Game/Rulesets/Objects/HitObject.cs
@@ -129,7 +129,7 @@ public void ApplyDefaults(ControlPointInfo controlPointInfo, IBeatmapDifficultyI
             CreateNestedHitObjects(cancellationToken);
 
             // Objects implementing IHasMultipleComboInformation handle this binding themselves
-            if (this is IHasComboInformation hasCombo && this is not IHasMultipleComboInformation)
+            if (this is IHasComboInformation hasCombo)
             {
                 foreach (HitObject hitObject in nestedHitObjects)
                 {

```

Basically, I've removed all usages of `IHasMultipleComboInformation` from everywhere but the timeline by making your new hit object extend `HitObject` rather than `OsuHitObject` (so it *doesn't* have combo information itself). I've also added support for nested hitobjects to have `IHasComboinformation`.

The end goal is to be able to get your requirements in without complicating the beatmap / combo processing with new interfaces / paths. Obviously the nested handling is new, but it's also in line with how we handle nested objects elsewhere so I don't think anyone on the team would be against this.

I haven't tested if this will work, will leave that for you to test as you know the final picture better than I do.

If the above change looks to work, the next step would be to tidy up usages in the timeline view. Maybe the two interfaces you have could be combined into one? Also would want to tidy up the `updateColour` method and calling structure of it, can give more feedback on that if everything else sounds good.

**Comment by bdach** [comment]
A few things:

- In principle I could agree with nested objects implementing `IHasComboInformation`, *but* I'm not sure how that's going to play out in practice. My worry is that we liberally clear and recreate nested hitobjects on each defaults application, and therefore we may not be able really store any actual relevant data there. [Relevant example of an issue caused by exactly this](https://github.com/ppy/osu/issues/15618#issuecomment-968288164).
- But on the flipside I also agree that I'd loath to see `IHasMultipleComboInformation`, and would go even further - all that "relative time" interface stuff that's also in this pull *also* needs to go IMO. No other object type has done anything like this, *including* existing nested objects which are *also* by their nature hard-coupled to their parenting object's start time. If there is need to regenerate, then so be it.

To that end:

- I am guessing that all of that combo stuff is to allow starting a new combo mid-stream? In that case, can we just... not do that? Is it so important to allow this? Does it ever make sense in mapping to do that?
- I'm not really sure what that "relative time" stuff is supposed to facilitate exactly so I'm not sure I have anything to suggest there. But if anything I'd say that the stream tool should be doing all of its nested object accounting in absolute time like everything else does.

**Comment by OliBomby** [comment]
@peppy I tried your solution but it isn't practical. I can't add `HitObjects` to an `OsuBeatmap` because it expects only `OsuHitobjects`. It possible to remove `IHasComboInformation` from `OsuHitObject` to achieve your idea, but this requires a lot of refactoring to fix everything that ever interacts with the combo information of a `OsuHitObject`.
Also I don't think storing the combo information in the nested hit objects will work anyways because of what dbach mentioned.

@bdach 
> * I am guessing that all of that combo stuff is to allow starting a new combo mid-stream? In that case, can we just... not do that? Is it so important to allow this? Does it ever make sense in mapping to do that?

New-combo's mid-stream are very commonly used to show each segment of the stream or a speed change. Since the main feature of the `Stream` object is to quickly create a stream with multiple segments, it should be able to have new-combo's mid-stream.

> * I'm not really sure what that "relative time" stuff is supposed to facilitate exactly so I'm not sure I have anything to suggest there. But if anything I'd say that the stream tool should be doing all of its nested object accounting in absolute time like everything else does.

The relative time stuff is not related directly to the nested hit objects. They are used by the control points of the `Stream` which each have a time relative to the `Stream` start. It can probably be changed to use absolute time, but I'd still need an interface if I want to have the timeline interact with these control points.


I'm thinking maybe it's possible to make the whole timeline ruleset specific. That way an `OsuTimelineBlueprintContainer` can directly reference the types of the ruleset hit objects and handle them specifically, and no interfaces would have to be added to the main osu.Game project.

**Comment by OliBomby** [comment]
I made a little infographic to help think about the different interfaces required for the `Stream` hit object idea.

paintdotnet_TfKnjeofwI

Basically I need to expose a list of objects which have a time value and `IHasComboInformation` and a list of objects which just have a time value. Currently there is no interface that says an object has a 'time' value, maybe `IHasStartTime` would make more sense than the proposed `IHasRelativeTime`?

I could potentially change the `IHasMultipleComboInformation` interface to instead expose a list of `T : HitObject, IHasComboInformation`, so it tells the beatmap processor which nested hit objects to process combos for instead of the parent object. We can't simply let the beatmap processor process combos on all nested hit objects because a lot of them inherit `OsuHitObject` which has `IHasComboInformation`. This approach would not require an interface that exposes a 'time' value.

**Comment by peppy** [comment]
@OliBomby do you have a new solution for this? would always be appreciated to make a note when closing a PR so we know what the deal is (generally we don't close PRs unless they are no longer valid, which I would disagree is the case here).

**Comment by OliBomby** [comment]
I figured the current approach was never gonna be good. The interfaces introduced in this PR dont make sense for any reasonable hit object. They are only there to edit arbitrary properties of some mapping meta-construct. That's why I want to pivot the design to not use hit objects and instead introduce a new kind of object for these mapping meta-constructs.

As for timeline support. Not sure yet how that's gonna look. I think I'll let them have custom blueprints which sit on top of the hit objects in the timeline.

**Pull request closed without merging**
