### PR TITLE
fix hp drain for osu!mania

### PR DESCRIPTION
**Pull request by Comprobar**

### CODE REVIEW

**Comment by bdach** [comment]
...and by "fix", you mean "turn off".

rather strange to PR this *before* the [upcoming community meeting on this exact topic.](https://twitter.com/ppy/status/1479489107873366016) UTC 01:00, if you're inclined to come and listen.

**Comment by cabritinha123** [comment]
mf just fixed the game with one number

**Comment by bdach** [comment]
going to preemptively lock this thread to avoid "funny" comments like the one above.

discussion may resume *after* the upcoming community meeting if removing drain is determined to be the correct course of action.

**Comment by peppy** [comment]
If this is a serious contribution, please reopen with some kind of documentation as to the goal of the change.

**Pull request closed without merging**
