### PR TITLE
Initial implementation of Wiki Overlay

### LINKED ISSUE #5250: Implement wiki overlay
It would be really convenient have in-game wiki, especially for the new players, it would also increase it's visibility thus increasing the amount of contributions.

### PR DESCRIPTION
**Pull request by gagahpangeran**
FIrst implementation of wiki overlay!

Closes #5250

Depends on :
- [x]  #12949
- [x] https://github.com/ppy/osu-resources/pull/124

I split this into 4 chain PRs so it's easier to review.

Known issue:
- Sitemap link will only return blank page because it's separate route in osu!web and there is no API for it yet.

Not implemented yet:
- Search / suggestion bar. (There's no API for it now AFAIK)
- Wiki locale support.
- Sidebar for table of content. (will do in after extract sidebar logic from `NewsSidebar`)

The implementation of `WikiOverlay` is similar with `NewsOverlay`. I have a plan to create abstract class `ArticleOverlay` so I can reuse the logic of its Sidebar, but it's for another day.

For now, `WikiOverlay` is pretty much functional.

### CODE REVIEW

**Comment by peppy** [comment]
In testing I came across this:

```csharp
[runtime] 2021-05-30 14:18:29 [error]: An unhandled error has occurred.
[runtime] 2021-05-30 14:18:29 [error]: System.ArgumentException: Document URL (w
iki/Interface/) must be an absolute URI.
[runtime] 2021-05-30 14:18:29 [error]: at osu.Framework.Graphics.Containers.Mark
down.MarkdownContainer.set_DocumentUrl(String value)
[runtime] 2021-05-30 14:18:29 [error]: at osu.Game.Overlays.Wiki.Markdown.WikiMa
rkdownContainer.set_CurrentPath(String value) in Y:\osu\osu.Game\Overlays\Wiki\M
arkdown\WikiMarkdownContainer.cs:line 18
[runtime] 2021-05-30 14:18:29 [error]: at osu.Game.Overlays.WikiOverlay.onSucces
s(APIWikiPage response) in Y:\osu\osu.Game\Overlays\WikiOverlay.cs:line 72
[runtime] 2021-05-30 14:18:29 [error]: at osu.Game.Overlays.WikiOverlay.<>c__Dis
playClass11_0.<onPathChanged>b__2() in Y:\osu\osu.Game\Overlays\WikiOverlay.cs:l
ine 48
```

**Comment by gagahpangeran** [comment]
Ah, this looks like happen after removing `Schedule` in https://github.com/ppy/osu/pull/12948/commits/eeb6647bc50986ff123e483888df59f1af4b721b.

When `CurrentPath` is set, the `DocumentUrl` is still null then throws the error.

Screenshot from 2021-05-30 21-49-29


Adding back `Schedule` resolves this issue, but I'm not sure that's the best way to do it.

```csharp
        public string CurrentPath
        {
            set => Schedule(() => DocumentUrl = $"{DocumentUrl}wiki/{value}");
        }
```

Any suggestion?

**Comment by bdach** [comment]
Was quite baffled at the suggestion of fixing a simple data setter with a schedule, but as it turns out, it's due to this logic:

https://github.com/ppy/osu/blob/f3bde258a2e519acd119020d45896608f3fb81d8/osu.Game/Graphics/Containers/Markdown/OsuMarkdownContainer.cs#L26-L34

which runs somewhere around BDL time, hence the schedule. Honestly I think `WikiMarkdownContainer` shouldn't be doing this song and dance of "let's rely on base execution order for a setter"; I'd advocate for resolving `IAPIProvider` in `WikiMarkdownContainer` and explicitly resolve absolute URIs using it. Yes it's a bit redundant but I think it's miles better than putting that schedule there...

That said it'd require some wiggling around in the container to allow for setting `CurrentPath` safely before BDL. The pattern that is wanted here is probably something like

```csharp
private string currentPath;

public string CurrentPath
{
	set
	{
		currentPath = value;

		if (isLoaded)
			SetDocument();
	}
}

protected override LoadComplete()
{
	SetDocument();
}

public void SetDocument() => DocumentUrl = $"{api.WebsiteRootUrl}/{currentPath}";
```

Could also do the same thing but via making `currentPath` a bindable and making `SetDocument()` the value change callback.

**Comment by peppy** [comment]
@bdach you can see why i suggested the current method in the original review. what you propose will render the document twice in normal usages, so needs a bit more consideration (updating the url causes an invalidation after the base framework class BDL render).

**Comment by gagahpangeran** [comment]
For now, I add back the schedule as temporary solution so other component is testable. Will change it later after find the best solution to do it.

**Comment by peppy** [comment]
I will be revisiting this today as that schedule can not exist. There was no need to add it back, but just leave it for now that's fine.

**Comment by peppy** [comment]
Some content looks like links but are not links:

20210601 135606 (dotnet)

**Review by peppy — DISMISSED** [review]

**Comment by gagahpangeran** [comment]
Oh, that should be inline code. The text color is the same as link, but it should have background colour and use monospace font. I mentioned it before as known issue in https://github.com/ppy/osu/pull/12688. Because for now, o!f doesn't support background colour in inline text (or maybe I don't know how to do it).

Will open an issue for visibility.

**Comment by peppy** [comment]
@bdach for now I've just inlined the absolute URL generation at each location to keep things simple. Obviously could be better, but I think it will require some framework-side changes to make the asynchronous loading still work correctly. Doesn't seem worth the effort with so few use cases right now, can revisit later.

**Review by peppy — APPROVED** [review]

**Pull request merged**
