### PR TITLE
Enable AOT on android release builds

### PR DESCRIPTION
**Pull request by peppy**
Not sure about interpreter fallback, will need to test with some users.

### CODE REVIEW

**Comment by bdach** [comment]
Fails to boot on one of my test devices with

```
[ERROR] FATAL UNHANDLED EXCEPTION: System.PlatformNotSupportedException: Arg_PlatformNotSupported
   at System.Text.ASCIIUtility.GetIndexOfFirstNonAsciiByte_Intrinsified(Byte* , UIntPtr )
   at System.Text.Unicode.Utf8Utility.GetPointerToFirstInvalidByte(Byte* , Int32 , Int32& , Int32& )
   at System.Text.UTF8Encoding.GetCharCount(Byte* , Int32 )
   at System.String.CreateStringFromEncoding(Byte* bytes, Int32 byteLength, Encoding encoding)
   at System.Text.Encoding.GetString(Byte* , Int32 )
   at System.String.CreateStringForSByteConstructor(Byte* pb, Int32 numBytes)
   at System.String.Ctor(SByte* value)
   at System.Runtime.InteropServices.Marshal.PtrToStringAnsi(IntPtr )
   at Java.Interop.TypeManager.GetClassName(IntPtr )
   at Android.Runtime.JNIEnv.RegisterJniNatives(IntPtr , Int32 , IntPtr , IntPtr , Int32 )
```

Seemingly relevant upstream hit is https://github.com/dotnet/runtime/issues/73003, but that weirds me out since that's apparently a .NET 7 issue? Maybe caused by the fact that I have the .NET 7 SDK installed...

Needs further investigation (i.e. me uninstalling .NET 7 I guess).

**Comment by bdach** [comment]
As an update, tried a few things today.

1. Updated framework and game to `net7.0` and `net7.0-android` runtimes with these changes.

    **Result:** Game dies at boot with different crash:

    ```
    * Assertion at /__w/1/s/src/mono/mono/mini/aot-runtime.c:5081, condition `plt_entry' not met
    Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 29015 (sh.ppy.osulazer), pid 29015 (sh.ppy.osulazer)
    Explicit concurrent copying GC freed 32(52KB) AllocSpace objects, 10(3552KB) LOS objects, 49% free, 3130KB/6261KB, paused 62.275ms,50us total 74.794ms
    Process name is sh.ppy.osulazer, not key_process
    Cmdline: sh.ppy.osulazer
    pid: 29015, tid: 29015, name: sh.ppy.osulazer  >>> sh.ppy.osulazer <<<
        #01 pc 0000000000039f1c  /data/app/~~trKX6eeyJbcNzzZfStqtKg==/sh.ppy.osulazer-FSlPBmiEJgojeIHRSbSnyQ==/lib/arm64/libmonodroid.so (xamarin::android::internal::MonodroidRuntime::mono_log_handler(char const*, char const*, char const*, int, void*)+144) (BuildId: a8466986ce0a58d7eb3a452ef823ee9785ed332d)
        #02 pc 00000000002daa24  /data/app/~~trKX6eeyJbcNzzZfStqtKg==/sh.ppy.osulazer-FSlPBmiEJgojeIHRSbSnyQ==/lib/arm64/libmonosgen-2.0.so (BuildId: 2886a74d114d6e7dd505447cfe4ef4ebcf5f2771)
        #03 pc 00000000002dab50  /data/app/~~trKX6eeyJbcNzzZfStqtKg==/sh.ppy.osulazer-FSlPBmiEJgojeIHRSbSnyQ==/lib/arm64/libmonosgen-2.0.so (BuildId: 2886a74d114d6e7dd505447cfe4ef4ebcf5f2771)
        #04 pc 00000000002dab94  /data/app/~~trKX6eeyJbcNzzZfStqtKg==/sh.ppy.osulazer-FSlPBmiEJgojeIHRSbSnyQ==/lib/arm64/libmonosgen-2.0.so (BuildId: 2886a74d114d6e7dd505447cfe4ef4ebcf5f2771)
        #05 pc 0000000000252ff8  /data/app/~~trKX6eeyJbcNzzZfStqtKg==/sh.ppy.osulazer-FSlPBmiEJgojeIHRSbSnyQ==/lib/arm64/libmonosgen-2.0.so (BuildId: 2886a74d114d6e7dd505447cfe4ef4ebcf5f2771)
        #06 pc 0000000000265bc0  /data/app/~~trKX6eeyJbcNzzZfStqtKg==/sh.ppy.osulazer-FSlPBmiEJgojeIHRSbSnyQ==/lib/arm64/libmonosgen-2.0.so (BuildId: 2886a74d114d6e7dd505447cfe4ef4ebcf5f2771)
    ```

    Can't find any upstream bugs that would match the above failing assertion.

2. Updated framework and game to `net7.0` and `net7.0-android` runtimes with these changes, added `<AndroidEnableProfiledAot>false</AndroidEnableProfiledAot>` mostly just to see what happens.

    **Result:** Fails to compile with `precompiling failed for Microsoft.Extensions.DependencyInjection`. Only semi-relevant upstream issue I can find is https://github.com/dotnet/linker/issues/2898.

3. Updated framework and game to `net7.0` and `net7.0-android` runtimes with these changes, removed `<EnableLLVM>true</EnableLLVM>`.

    **Result:** Works, but no performance improvement.

3. Removed `<EnableLLVM>true</EnableLLVM>` from this branch with no further changes.

    **Result:** Works, but no performance improvement.

So I dunno. If you think this is worth exploring further, I'll continue, but it's likely going to be a bit of a proejct which will likely also require isolating and reporting to upstreams where applicable.

**Comment by peppy** [comment]
> Removed <EnableLLVM>true</EnableLLVM> from this branch with no further changes.

This one's interesting. Does it imply that no-LLVM means no AOT?

I think the next steps would be to get the .NET team more involved. Or give up and wait for .net 8 or whatever.

Without AOT, we are likely incurring randomly excessive overheads on things like `Dictionary` operations (resulting in https://github.com/ppy/veldrid/pull/27, you'll have to follow discord discussions if you want to read the whole history..) which is going to really limit android performance.

**Comment by bdach** [comment]
> This one's interesting. Does it imply that no-LLVM means no AOT?

Xamarin's docs on this are terrible/non-existent, so here follows a confabulation of what is happening based pretty much solely on watching build logs.

There seem to be at least 2 disparate AOT processes on android:

- The first takes in `.dll` files and spits out `.dll.so` files. Notably, at least on my machine, this _is already happening on_ `master`, and only stops happening if I _explicitly turn it off_ via `<AotAssemblies>false</AotAssemblies>`.
- The second takes in `.dll.so` files and spits out `.dll.llvm-so` files. As per [this](https://learn.microsoft.com/en-us/xamarin/android/deploy-test/release-prep/?tabs=windows#llvm-optimizing-compiler) doc, that should make go faster:

  > The LLVM Optimizing Compiler will create smaller and faster compiled code and convert AOT-compiled assemblies into native code, but at the expense of slower build times.

  This does _not_ run on `master` right now, is steered by `<EnableLLVM>`, and causes the variety of epic failures listed above.

**Comment by bdach** [comment]
@fanyang-mono thanks for the heads up. I see that this has been reported upstream now, kinda fell down the back of the couch on our end so to speak. I'm not sure I'll be able to isolate this properly as our project is rather large and it takes time to do so but I might try to fetch you the binlog as requested [here](https://github.com/dotnet/runtime/issues/95406#issuecomment-1877210927) if time permits.

**Comment by peppy** [comment]
I don't believe this is relevant or correct anymore as of net80.

**Pull request closed without merging**
