### PR TITLE
Don't share single scheduler across all model managers

### LINKED ISSUE #5346: Finishing a beatmap while importing maps freezes the game
**Describe the bug:** When a beatmap import is running (in my case the ``Import beatmaps from stable`` option) and a map is finished, the game just freezes for a long time, but never long than the beatmap import takes. This is a relatively major issue because it forces you to either wait multiple minutes or force-close the game.

**Screenshots or videos showing encountered issue:** https://streamable.com/hka2w

**osu!lazer version:** 2019.704.0 / master

**Logs:** (Couldn't find anything related to this)

### PR DESCRIPTION
**Pull request by smoogipoo**
Fixes #5346

### CODE REVIEW

**Comment by peppy** [comment]
Sure this is the right fix here? Was this after or before our conversation about the issue? Just wondering if you investigated further and found something beyond our discussion.

**Comment by smoogipoo** [comment]
We didn't really discuss it. The issue is the threadpool is just super saturated with all the beatmap import tasks, that the score import one doesn't get run for a very long time.

**Comment by peppy** [comment]
Even considering the single concurrency of the import job? Is it the web requests saturating or something else?

**Comment by smoogipoo** [comment]
The single concurrency is the issue, in-fact. It's not the web request pool but the import pool itself, which contain a mix of post-download async continuations and the initial async tasks themselves (which decompress archives/parse beatmaps/etc).

It's just that there's so many of _those_ tasks that are enqueued to run before the score import task.

**Comment by peppy** [comment]
Right, that makes more sense. I think this solution is an OK temporary one, but we probably need to re-think the asynchronocitiy of these import tasks as a whole at some point in the future

**Comment by smoogipoo** [comment]
Yeah probably. In a similar vein I think that if a user downloads a specific beatmap/drags it in, then we should prioritise the import of that one instead.

Maybe we just need something like a reverse-priority threadpool scheduler.

**Review by peppy — APPROVED** [review]

**Pull request merged**
