### PR TITLE
Cache buffered background to fix multiplayer lounge performance

### LINKED ISSUE #14276: Low fps on the new lounge design screen
**Describe the bug:** 
currently i get around 40-50 fps (sometimes even less) on the new lounge design screen which feels a bit weird since i get around 150 fps on the beatmap selection screen. i know that performance is a constant WIP but it feels weird having so low fps on a simple screen like that while the beatmap selection screen works just fine.

**Screenshots or videos showing encountered issue:** 
image

**osu!lazer version:** 
7725336008939d115c27060ae652e46171d0a59e

**Logs:**
[database.log](https://github.com/ppy/osu/files/6983707/database.log)
[network.log](https://github.com/ppy/osu/files/6983708/network.log)
[performance.log](https://github.com/ppy/osu/files/6983710/performance.log)
[runtime.log](https://github.com/ppy/osu/files/6983711/runtime.log)

OS: windows 10
CPU: i5-4440
iGPU: intel hd graphics 4600
RAM: 8 gb

### PR DESCRIPTION
**Pull request by peppy**
Consider this a request for comment. It's the cleanest solution I can come up with without dropping either the blur, or use of `ModelBackedDrawable`.

Intended to resolve https://github.com/ppy/osu/issues/14276.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Have you considered setting `BufferedContainer.FrameBufferScale = new Vector2(0.5f)`? We don't need to blur at full res either.

**Comment by peppy** [comment]
In addition to this? Sounds good if so.

**Comment by smoogipoo** [comment]
In addition, yes.

**Comment by gagahpangeran** [comment]
In empty lounge I get 100fps+, but in lounge with many rooms I still get about 50fps.

Could the caching also applied to `BufferedContainer` in `DrawableRoom`?

Especially this background.

https://github.com/ppy/osu/blob/f49c9673ccf415b46d8e14f46fb2c35ab2f86e02/osu.Game/Screens/OnlinePlay/Lounge/Components/DrawableRoom.cs#L161-L176

**Comment by smoogipoo** [comment]
Makes sense, but have you tested that doing that improves it for you? I'm curious by how much.

**Comment by gagahpangeran** [comment]
By removing `BufferedContainer` in `DrawableRoom` on latest commit in this changes, I get solid 90fps+ in lounge with many rooms :+1:

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
