### PR TITLE
Fix `KeyCounterDisplay` potentially getting stuck invisible due to autosize masking

### LINKED ISSUE #14793: Re-enabling the key overlay will make it appear only after closing the settings
**Describe the bug:** As shown in the video (when the HUD visibility is set to "always"), if you turn off the key overlay everything works correctly. However, when you re-enable it, the key overlay seems to appear only after closing the settings.

**Screenshots or videos showing encountered issue:**

https://user-images.githubusercontent.com/43073074/133889010-11a2fb17-726e-421f-8677-2591d38dbc22.mp4

**osu!lazer version:** `2021.916.0`

### PR DESCRIPTION
**Pull request by peppy**
Closes #14793. Open to alternative suggestions, but this seems the simplest way to resolve the issue in this case.

### CODE REVIEW

**Comment by bdach** [comment]
A possible alternative may be just to disable masking altogether:

```csharp
protected override bool ComputeIsMaskedAway(RectangleF maskingBounds) => false;
```

[There are other places that also do this](https://github.com/ppy/osu/blob/f5a5b87cf6e633e237b7595b1ef9cbf3dffe3da7/osu.Game.Rulesets.Catch/Edit/Blueprints/Components/ScrollingPath.cs#L74-L75), but I don't claim that doing that is super pretty either. I could live with either, personally.

**Review by bdach — APPROVED** [review]
approving but not merging yet to get more opinions / response to the above

**Comment by peppy** [comment]
A benefit of using `Size=` is that the top level container always has a valid size.

**Comment by smoogipoo** [comment]
I think I prefer this the way it is. I still feel a bit uneasy overriding masking-related functions,

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
