### PR TITLE
Catch unable to push child windows to inactive parent

### LINKED ISSUE #2681: Entering and exiting editor rapidly causes a crash
```
Unhandled Exception:
System.InvalidOperationException: Cannot push a child screen to a non-current screen.
  at osu.Framework.Screens.Screen.Push (osu.Framework.Screens.Screen screen) [0x00037] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Game.Screens.BackgroundScreen.Push (osu.Framework.Screens.Screen screen) [0x0003b] in <f8e4495d335e40f8819d6d08c1332f28>:0 
  at osu.Game.Screens.BackgroundScreen.<Push>b__4_0 (osu.Framework.Screens.Screen d) [0x00000] in <f8e4495d335e40f8819d6d08c1332f28>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable+<>c__DisplayClass2_0`1[TLoadable].<LoadComponentAsync>b__0 () [0x0000a] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Graphics.Drawable+<>c__DisplayClass15_1.<LoadAsync>b__2 () [0x00026] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Threading.ScheduledDelegate.RunTask () [0x0000e] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Threading.Scheduler.Update () [0x0024b] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Graphics.Drawable.UpdateSubTree () [0x000a1] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree () [0x00001] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree () [0x00068] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree () [0x00068] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree () [0x00068] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Platform.GameHost.UpdateFrame () [0x000c1] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Threading.GameThread.ProcessFrame () [0x0007d] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Threading.GameThread.runWork () [0x0002d] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at System.Threading.ThreadHelper.ThreadStart_Context (System.Object state) [0x00014] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Threading.ExecutionContext.RunInternal (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00071] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state, System.Boolean preserveSyncCtx) [0x00000] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Threading.ExecutionContext.Run (System.Threading.ExecutionContext executionContext, System.Threading.ContextCallback callback, System.Object state) [0x0002b] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
  at System.Threading.ThreadHelper.ThreadStart () [0x00008] in <0f9df4881040473f9da7cf6c2e2cb8c3>:0 
--- End of stack trace from previous location where exception was thrown ---
  at osu.Framework.Platform.GameHost+<>c__DisplayClass78_0.<exceptionHandler>b__0 () [0x00001] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Threading.Scheduler.Update () [0x0024b] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Threading.GameThread.ProcessFrame () [0x00053] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Threading.InputThread.RunUpdate () [0x00000] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Platform.GameHost.<Run>b__98_1 (System.Object <p0>, OpenTK.FrameEventArgs <p1>) [0x00013] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at (wrapper delegate-invoke) System.EventHandler`1[OpenTK.FrameEventArgs].invoke_void_object_TEventArgs(object,OpenTK.FrameEventArgs)
  at OpenTK.GameWindow.OnUpdateFrame (OpenTK.FrameEventArgs e) [0x00000] in <edcf1e8e608f476d924f831c867f7cf6>:0 
  at OpenTK.GameWindow.OnUpdateFrameInternal (OpenTK.FrameEventArgs e) [0x00010] in <edcf1e8e608f476d924f831c867f7cf6>:0 
  at OpenTK.GameWindow.RaiseUpdateFrame (System.Diagnostics.Stopwatch watch, System.Double elapsed, System.Double& timestamp) [0x0000c] in <edcf1e8e608f476d924f831c867f7cf6>:0 
  at OpenTK.GameWindow.DispatchUpdateFrame (System.Diagnostics.Stopwatch watch) [0x00022] in <edcf1e8e608f476d924f831c867f7cf6>:0 
  at OpenTK.GameWindow.Run (System.Double updates_per_second, System.Double frames_per_second) [0x000f8] in <edcf1e8e608f476d924f831c867f7cf6>:0 
  at OpenTK.GameWindow.Run () [0x00000] in <edcf1e8e608f476d924f831c867f7cf6>:0 
  at osu.Framework.Platform.GameWindow.Run () [0x00000] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Framework.Platform.GameHost.Run (osu.Framework.Game game) [0x0016e] in <2dfef38b0d6c4ec8a1da33ba64a2903d>:0 
  at osu.Desktop.Program.Main (System.String[] args) [0x000be] in <92f80ffa1d3d4f5b9ef9d31e56276303>:0 
```

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/59012685-entering-and-exiting-editor-rapidly-causes-a-crash?utm_campaign=plugin&utm_content=tracker%2F4707269&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F4707269&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### LINKED ISSUE #2797: Entering and exiting songlist rapidly causing a crash
[runtime.log](https://github.com/ppy/osu/files/2100378/runtime.log)

Works a bit different than the Editor one can get a video if needed

### PR DESCRIPTION
**Pull request by SparticKnight**
Catch System.InvalidOperationException on entering and exiting the editor too fast.
Closes #2681, closes #2797

### CODE REVIEW

**Comment by peppy** [comment]
This is likely not the solution we're looking for. Rather than catching all exceptions, checking the state of the screen is probably enough.

**Comment by SparticKnight** [comment]
so you don't like the way I did it? I didn't think it was an issue. if you reeealy want ill do what you said but I don't see how this is a bad solution

**Comment by peppy** [comment]
Google on why catching-all is generally a bad idea.

**Comment by SparticKnight** [comment]
I mean.... it wasn't like that at first but your checking is weird. but alright...

**Comment by peppy** [comment]
If you check the `IsCurrent` property before performing the push, the exception will likely never occur. Give it a try.

**Comment by SparticKnight** [comment]
// Make sure the in-progress loading is complete before pushing the screen.
            while (screen.LoadState < LoadState.Ready)
                Thread.Sleep(1);
            if (base.IsCurrent) { base.Push(screen); }
        }
        protected override void Update()
        {
            base.Update();
            Content.Scale = new Vector2(1 + x_movement_amount / DrawSize.X * 2);
        }
unless im missing something. this doesn't look possible

**Comment by SparticKnight** [comment]
For some reason, somehow, it's trying to destroy that screen when that screen is not the current screen.

**Comment by SparticKnight** [comment]
ok then... it looks like everything is good here

**Comment by peppy** [comment]
This doesn't match our code styling elsewhere. Please remove the `{}` as it is unnecessary. Also please commit using commit messages that are meaningful.

**Comment by SparticKnight** [comment]
done

**Comment by peppy** [comment]
You also changed the formatting by removing two other newlines which *were* necessary..

**Comment by SparticKnight** [comment]
oops. i wasnt thinking.

**Comment by SparticKnight** [comment]
ok sorry this took so long i got busy, but i re-added the newlines and that should be good.

**Review by Aergwyn — APPROVED** [review]

**Comment by Themayu** [comment]
What I don't understand is how `if (IsCurrentScreen) { base.Push(screen); }` causes the test suite to fail on AppVeyor, while `if (IsCurrentScreen) {base.Push(screen);}` does not. I mean, in this situation whitespace should be ignored when linking and building the output machine code for that statement...

**Comment by peppy** [comment]
Both passed. If you look at the appveyor log the failure was an unrelated sporadic test fail.

**Comment by SparticKnight** [comment]
i dont understand that either, i now know never to use appveyor for dev builds lol... but maybe it isnt a bad idea to learn as it can keep shit under controll

**Comment by SparticKnight** [comment]
nevermind then, hes right

**Comment by peppy** [comment]
This fix doesn't solve the issue at hand. While it no longer crashes, the background can end up in an unstable state now:

image

**Review by peppy — CHANGES_REQUESTED** [review]
As stated

**Comment by peppy** [comment]
See #2842 for correct solution.

**Pull request closed without merging**
