### PR TITLE
Make freemod selection overlay taller in multiplayer room

### PR DESCRIPTION
**Pull request by timiimit**
This is something that's really been annoying me and probably others too, there was only space for one row of mods and tiny space for customization. This change makes the mod selection full screen.

P.S. This is my first ever pull request so I hope I did everything correctly.

### CODE REVIEW

**Comment by bdach** [comment]
For added visual context, because this PR has none:

| master | this PR |
| :-: | :-: |
| osu_2021-05-18_20-17-01 | osu_2021-05-18_20-19-23 |

In general I don't have much of an issue with making the overlay taller, but I think a height of 1 is overkill. As to why, let me use a quick mockup:

obraz

It's very difficult to even tell that the overlay is an overlay at this height, and both the back button and <kbd>Esc</kbd> attempt to exit the room entirely. I think there's a middle ground to be struck here (`0.7f` or similar maybe?)

**Comment by timiimit** [comment]
Sorry for not including images of visual changes. 0.7 sounds like a reasonable value, I'll change it. Also is there a way to debug multiplayer features with osu.Desktop? The only way I found to get to a room was with tests.

**Comment by bdach** [comment]
You can also use the game but that requires creating a separate account for dev via the in-game registration flow (when running in debug, the developer instance of the website located at `dev.ppy.sh` is used, with an entirely separate user pool than the production/release `osu.ppy.sh`).

**Comment by timiimit** [comment]
So clicking the "I understand. This account isn't for me." is alright on local debug?
image

**Comment by bdach** [comment]
As long as it's debug/dev, yes, it should be fine. If you're feeling extra paranoid you can check `network.log`/console output to make sure the endpoints being hit are really from `dev.ppy.sh`.

**Comment by peppy** [comment]
I've refactored this to use the `HEIGHT` constant, rather than a local specification. The relative height doesn't scale well when running in a very portrait-orientated screen. Not sure it wasn't done this way from day one..

**Review by peppy — APPROVED** [review]

**Pull request merged**
