### PR TITLE
Remove rounding of slider velocity (when applied as scroll speed)

### LINKED ISSUE #25862: osu!taiko slider velocities are rounded to 2 decimal points, causing patterns to look staggered and unnatural
### Type

Game behaviour

### Bug description

In stable, you can input sv's up to 16 decimal places. Lazer has rounded all of these sv's to 2 decimal places, causing patterns that use continuous sv's for speed ups and slow downs to look staggered at times, making it uncomfortable to read.

Many taiko mappers have become accustomed to using external programs that will generate sv slow downs and speed ups, so a sizeable number of ranked taiko maps and world cup tournament maps have these 16 decimal point sv values. Because of this I believe this is a urgent issue.

**EDIT: After further investigation, I've found that this issue is most noticeable on maps with lower slider velocity, and maps with very gradual increase/decrease in slider velocity. This is because in both scenarios, you will be changing slider velocities every note by a small, but equal amount. When rounding these values to 2 decimal places, the changes in between slider velocities are no longer equal, causing the staggered effect seen below.**

### Screenshots or videos

The video provided shows a taiko world cup map which has this issue. It is hard to see the issue in real time so I recommend pausing to have a closer look. I have also provided a diagram of one pattern which hopefully better showcases this problem. Top players expect the smooth sv's seen in stable, so reading the disjointed one in lazer at the moment is very uncomfortable.

https://github.com/ppy/osu/assets/106291852/15ae7bce-abc3-4f9d-b513-d14a27ef3e87

imageardtda3452345

**EDIT: Adding more examples.**

Map 2: https://osu.ppy.sh/beatmapsets/1888593#taiko/3889528 at 01:07:401

https://github.com/ppy/osu/assets/106291852/ffbe3497-39f3-4897-93c2-036fc18d653c

Map 3: https://osu.ppy.sh/beatmapsets/1182264#taiko/2464974 at 02:32:385

https://github.com/ppy/osu/assets/106291852/670f8873-4138-4b73-a1a4-2bd864794b57

Map 4: https://osu.ppy.sh/beatmapsets/1311567#taiko/2718349 at 02:43:830

https://github.com/ppy/osu/assets/106291852/2a58a13d-5cdc-4b9f-a48c-89e46613b860

Map 5: https://osu.ppy.sh/beatmapsets/1684883#taiko/3442563 at 01:08:582 

This one is very hard to notice when not in gameplay so I recommend pausing. You should be able to notice very slight staggered notes, where 2 notes are closer together than one another. 

https://github.com/ppy/osu/assets/106291852/5960b563-2794-4b9a-9a51-1ea737605d59

### Version

2023.1218.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/13706706/database.log)
[input.log](https://github.com/ppy/osu/files/13706707/input.log)
[performance.log](https://github.com/ppy/osu/files/13706708/performance.log)
[runtime.log](https://github.com/ppy/osu/files/13706709/runtime.log)
[network.log](https://github.com/ppy/osu/files/13706710/network.log)
[1702919148.input.log](https://github.com/ppy/osu/files/13706711/1702919148.input.log)
[1702919148.performance.log](https://github.com/ppy/osu/files/13706712/1702919148.performance.log)
[1702919148.runtime.log](https://github.com/ppy/osu/files/13706713/1702919148.runtime.log)
[1702919148.network.log](https://github.com/ppy/osu/files/13706714/1702919148.network.log)

### PR DESCRIPTION
**Pull request by peppy**
Was of course only done for the benefit of editor UI controls.

This affects both osu!taiko and osu!mania.

Closes https://github.com/ppy/osu/issues/25862.

TODO:

- [x] Fix editor scroll speed slider bar adjusting to stupid numbers.

### CODE REVIEW

**Comment by bdach** [comment]
!diffcalc
RULESET=taiko

**Comment by bdach** [comment]
!diffcalc
RULESET=mania

**Comment by bdach** [comment]
!diffcalc
RULESET=taiko
SCORE_PROCESSOR_A=https://github.com/bdach/osu-queue-score-statistics/tree/fix-compile-failure
SCORE_PROCESSOR_B=https://github.com/bdach/osu-queue-score-statistics/tree/fix-compile-failure

**Comment by bdach** [comment]
!diffcalc
RULESET=mania
SCORE_PROCESSOR_A=https://github.com/bdach/osu-queue-score-statistics/tree/fix-compile-failure
SCORE_PROCESSOR_B=https://github.com/bdach/osu-queue-score-statistics/tree/fix-compile-failure

**Comment by bdach** [comment]
Note that I'm not PRing the `osu-queue-score-statistics` branch mentioned above (https://github.com/bdach/osu-queue-score-statistics/tree/fix-compile-failure) for now as it'll likely be changing for a second time as migration concerns in https://github.com/ppy/osu/pull/26630 are addressed, so it seems counterproductive.

**Comment by bdach** [comment]
Diffcalc runs failed again because the sheet generator is dependent on the old structure of the `scores` table...

```
2024-01-22T08:48:19.3728453Z execution-7608342382-7030-1-importer-1   | MySqlConnector.MySqlException (0x80004005): Unknown column 's.legacy_score_id' in 'on clause'
2024-01-22T08:48:19.3730826Z execution-7608342382-7030-1-importer-1   |    at MySqlConnector.Core.ServerSession.ReceiveReplyAsyncAwaited(ValueTask`1 task) in /_/src/MySqlConnector/Core/ServerSession.cs:line 958
2024-01-22T08:48:19.3733927Z execution-7608342382-7030-1-importer-1   |    at MySqlConnector.Core.ResultSet.ReadResultSetHeaderAsync(IOBehavior ioBehavior) in /_/src/MySqlConnector/Core/ResultSet.cs:line 43
2024-01-22T08:48:19.3736277Z execution-7608342382-7030-1-importer-1   |    at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 129
2024-01-22T08:48:19.3739642Z execution-7608342382-7030-1-importer-1   |    at MySqlConnector.MySqlDataReader.CreateAsync(CommandListPosition commandListPosition, ICommandPayloadCreator payloadCreator, IDictionary`2 cachedProcedures, IMySqlCommand command, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 458
2024-01-22T08:48:19.3743761Z execution-7608342382-7030-1-importer-1   |    at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, Activity activity, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
2024-01-22T08:48:19.3746777Z execution-7608342382-7030-1-importer-1   |    at MySqlConnector.MySqlCommand.ExecuteReaderAsync(CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 330
2024-01-22T08:48:19.3749152Z execution-7608342382-7030-1-importer-1   |    at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 323
2024-01-22T08:48:19.3752047Z execution-7608342382-7030-1-importer-1   |    at Dapper.SqlMapper.QueryAsync[T](IDbConnection cnn, Type effectiveType, CommandDefinition command) in /_/Dapper/SqlMapper.Async.cs:line 434
2024-01-22T08:48:19.3757041Z execution-7608342382-7030-1-importer-1   |    at osu.Server.Queues.ScoreStatisticsProcessor.Commands.Queue.ImportHighScoresCommand.OnExecuteAsync(CancellationToken cancellationToken) in /tmp/tmp.lbIREt40LC/osu-queue-score-statistics/osu.Server.Queues.ScoreStatisticsProcessor/Commands/Queue/ImportHighScoresCommand.cs:line 119
2024-01-22T08:48:19.3761757Z execution-7608342382-7030-1-importer-1   |    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.InvokeAsync(MethodInfo method, Object instance, Object[] arguments)
2024-01-22T08:48:19.3763874Z execution-7608342382-7030-1-importer-1   |    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.OnExecute(ConventionContext context, CancellationToken cancellationToken)
2024-01-22T08:48:19.3765877Z execution-7608342382-7030-1-importer-1   |    at McMaster.Extensions.CommandLineUtils.Conventions.ExecuteMethodConvention.<>c__DisplayClass0_0.<<Apply>b__0>d.MoveNext()
2024-01-22T08:48:19.3767394Z execution-7608342382-7030-1-importer-1   | --- End of stack trace from previous location ---
2024-01-22T08:48:19.3769461Z execution-7608342382-7030-1-importer-1   |    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync(String[] args, CancellationToken cancellationToken)
2024-01-22T08:48:19.3771585Z execution-7608342382-7030-1-importer-1   |    at McMaster.Extensions.CommandLineUtils.CommandLineApplication.ExecuteAsync[TApp](CommandLineContext context, CancellationToken cancellationToken)
2024-01-22T08:48:19.3774728Z execution-7608342382-7030-1-importer-1   |    at osu.Server.Queues.ScoreStatisticsProcessor.Program.Main(String[] args) in /tmp/tmp.lbIREt40LC/osu-queue-score-statistics/osu.Server.Queues.ScoreStatisticsProcessor/Program.cs:line 27
2024-01-22T08:48:19.3776586Z execution-7608342382-7030-1-importer-1   |    at osu.Server.Queues.ScoreStatisticsProcessor.Program.<Main>(String[] args)
```

I'm not fixing this on github before smoogi comes back, so I guess I'll have to run any and all sheets locally.

**Comment by bdach** [comment]
Manual taiko spreadsheet: https://docs.google.com/spreadsheets/d/1QXLt1PDzt2uIEpYi9GVLekaNgjkqWBFU2hReRD44CvI/edit#gid=825868992

Looks promising, if I didn't screw up the score table structure updates.

**Comment by peppy** [comment]
@bdach I've pushed a WIP fix for the slider bar. See what you think of it. It works fine, except the textbox shows too much precision due to inaccuracies coming from `SliderBar`'s output I guess (and the `ToDecimal` code):

https://github.com/ppy/osu/blob/0bacf6943924ec802f86db20b2ab2f392ddd5561/osu.Game/Graphics/UserInterfaceV2/SliderWithTextBoxInput.cs#L113-L114

**Comment by bdach** [comment]
I continue to think that messing with the control is the wrong approach. I would propose this instead of the last commit:

```diff
diff --git a/osu.Game/Screens/Edit/Timing/EffectSection.cs b/osu.Game/Screens/Edit/Timing/EffectSection.cs
index 7e484433f7..9d4ef5c62a 100644
--- a/osu.Game/Screens/Edit/Timing/EffectSection.cs
+++ b/osu.Game/Screens/Edit/Timing/EffectSection.cs
@@ -52,17 +52,44 @@ void saveChanges()
 
         protected override void OnControlPointChanged(ValueChangedEvent<EffectControlPoint?> point)
         {
-            if (point.NewValue != null)
+            if (point.OldValue is EffectControlPoint oldEffectPoint)
+            {
+                scrollSpeedSlider.Current.ValueChanged -= updateControlPointFromSlider;
+                oldEffectPoint.ScrollSpeedBindable.ValueChanged -= updateSliderFromControlPoint;
+            }
+
+            if (point.NewValue is EffectControlPoint newEffectPoint)
             {
                 isRebinding = true;
 
-                kiai.Current = point.NewValue.KiaiModeBindable;
-                scrollSpeedSlider.Current = point.NewValue.ScrollSpeedBindable;
+                kiai.Current = newEffectPoint.KiaiModeBindable;
+                scrollSpeedSlider.Current = new BindableDouble
+                {
+                    MinValue = 0.01,
+                    MaxValue = 10,
+                    Precision = 0.01,
+                    Value = newEffectPoint.ScrollSpeedBindable.Value
+                };
+                scrollSpeedSlider.Current.ValueChanged += updateControlPointFromSlider;
+                newEffectPoint.ScrollSpeedBindable.ValueChanged += updateSliderFromControlPoint;
 
                 isRebinding = false;
             }
         }
 
+        private void updateControlPointFromSlider(ValueChangedEvent<double> scrollSpeed)
+        {
+            if (ControlPoint.Value is not EffectControlPoint effectPoint || isRebinding)
+                return;
+
+            effectPoint.ScrollSpeedBindable.Value = scrollSpeed.NewValue;
+        }
+
+        private void updateSliderFromControlPoint(ValueChangedEvent<double> scrollSpeed)
+        {
+            scrollSpeedSlider.Current.Value = scrollSpeed.NewValue;
+        }
+
         protected override EffectControlPoint CreatePoint()
         {
             var reference = Beatmap.ControlPointInfo.EffectPointAt(SelectedGroup.Value.Time);

```

It _appears_ to work...?

**Comment by peppy** [comment]
That looks far better than what I had if it works 👍 .

**Comment by peppy** [comment]
@bdach wanna apply your patch? I can't seem to make it apply 😓 .

**Comment by bdach** [comment]
Have applied with slight alterations. Turns out the simple unidirectional solution is even enough to support undo for now (albeit, only due to some special circumstances, as per attached inline comment).

**Review by bdach — APPROVED** [review]

**Pull request merged**
