### PR TITLE
Add Spinners

### PR DESCRIPTION
**Pull request by ColdVolcano**
Adds basic behavior of spinner, it should be good for now.

### CODE REVIEW

**Comment by arflyte** [comment]
[Spinner.zip](https://github.com/ppy/osu/files/668032/Spinner.zip)

I've attached the spinner design here.

**Comment by peppy** [comment]
the animations haven't been finalised yet, so if you implement the new design, do so with the bottom panel (full, with progress bar) and make sure everything is customisable.

**Comment by ColdVolcano** [comment]
Oh look, work to do!

**Comment by ColdVolcano** [comment]
Will complete design in separate PR

**Comment by peppy** [comment]
Sorry but this is unusable. I'll be PRing a replacement in the near future.

**Pull request closed without merging**
