### PR TITLE
Add the ability to ignore the user's mouse movement

### PR DESCRIPTION
**Pull request by RedMindZ**
A simple check in the `Handle` method is added to ignore `MouseMoveEvent` events.
The mouse movement can be disabled or enabled by setting the property `AllowUserCursorMovement`.

### CODE REVIEW

**Comment by smoogipoo** [comment]
What's the purpose of this? It's unused here so... Is it going to be used in a mod? Do you have a follow-up PR we can look at?

**Comment by RedMindZ** [comment]
This is just the base for implementing Autopilot - it requires disabling the user's ability to move the cursor. I planned on implementing it on a separate PR.

**Comment by ticotaco72** [comment]
Take in mind that touchscreen users need to be able to pause the gameplay, so it can't be blocked totally. And maybe for going with mouse outside the window on PCs.

**Comment by RedMindZ** [comment]
This doesn't disable the movement of the system's cursor, but rather only the in-game cursor, so a user can still move his mouse outside the window on PC or use the touchscreen. This should be very similar to what Autopilot does on stable, though I can't confirm.

**Comment by ticotaco72** [comment]
on touchscreen you have to click in-game button to pause gampelay

**Comment by RedMindZ** [comment]
For the same reason the user can press that button when the Relax mod disables key presses (including those coming from the mouse), they should be able to press it when cursor movement is disabled. Is there currently a way to compile the game for android? if there is, then please tell me how so I can test it.

**Comment by peppy** [comment]
I'm not sure how you're accessing the `InputManager` from the mod, but may want to consider addin this toggle inside the cursor (and use that as a vehicle for communicating cursor/input changes to the mod)?

Requires a bit of further discussion. Would help to see the usage of this in the implementation of the mod, or wherever you're using it (as a separate PR).

**Comment by RedMindZ** [comment]
To access the `InputManager` I am doing exactly what the current implementation of Relax does: I implement the `IApplicableToDrawableRuleset<OsuHitObject>` interface in the mod, and then in the function `ApplyToDrawableRuleset` I save the `OsuInputManager` to a private field.

As far as 'adding this toggle inside the cursor', I am not exactly sure what you mean by that, could you elaborate?

Lastly, I'll submit a PR for Autopilot, hopefully it will make the usage clear.

**Comment by peppy** [comment]
Please don't PR from your master branch in the future.

**Comment by peppy** [comment]
I think this is fine for now.

**Review by peppy — APPROVED** [review]

**Comment by RedMindZ** [comment]
Thanks for merging peppy! I guess I shouldn't use the master branch because merging 'master' into 
'master' is confusing right? No problem, I'll create a separate branch next time.

**Comment by iiSaLMaN** [comment]
@RedMindZ Just to point out	: PR-ing with the master branch will limit you to opening 1 PR, also the master branch isn't meant to be modified, it is the base branch, so if you modify your master for a PR and got rejected, you would've to reset your master branch which is kind-of annoying.

**Comment by RedMindZ** [comment]
Thanks for the info, I'll keep that in mind.

**Pull request merged**
