### PR TITLE
Added health replacement setting to AccuracyChallenge

### PR DESCRIPTION
**Pull request by shiumano**
Added a setting to AccuracyChallenge that prevents it from failing for reasons other than insufficient Accuracy.
When this setting is enabled, in some cases the behavior will be the same as NoFail, making the pass easier.
Therefore, with it enabled, it is set to Unranked and the score multiplier is set to 0.5x.

https://github.com/ppy/osu/assets/75152752/c00b2433-ac9e-4381-b688-1d4dbb4027bb

### CODE REVIEW

**Comment by bdach** [comment]
Not sure I see the point. The code for this is horribly ugly and this is a feature I don't know how many people even want. And you have a semi-viable alternative for this if you really want this - put on Difficulty Adjust and put HP at 0.

**Comment by shiumano** [comment]
Yes, I wrote something really awful...I am sorry to show you this.
At best I could tell at a glance how much more accuracy I needed to lose, but the cost was too great.
Shall I throw it in the trash.

**Comment by bdach** [comment]
I'd wait and see what everyone else says but to me this is a hard no.

**Comment by smoogipoo** [comment]
Let's not do this one for now. I disagree with it in principle (fail-by-accuracy and fail-by-health are not exclusive to me), but there are other combinations that can achieve similar, like setting `DA: HP0`.

**Pull request closed without merging**
