### PR TITLE
Added "swap" mod for taiko

### LINKED ISSUE #12812: Add "Flip" mod for osu!taiko
this mod would flip dons and kats, as simple as that.

it can be a really nice (and hopefully easy) addition that can keep gameplay fresh and reduce mindblock. Plus it can be good for practicing certain patterns too or for balancing out maps that put more strain on a non-dominant hand for example.

### PR DESCRIPTION
**Pull request by hlysine**
Closes #12812 
~Flip and random are put into a `MultiMod`~

### CODE REVIEW

**Comment by peppy** [comment]
Is there a specific reason for grouping it with random? I don't think this is great for discoverability. If you're trying to enforce incompatibility, there's a better way to do that (see `IncompatibleMods`).

**Comment by Henry-YSLin** [comment]
I see random as a more extreme version of mods that change patterns and break muscle memory, so flip and random are variants of each other (similar to flashlight and blinds).

**Comment by peppy** [comment]
Not sure I can agree with that one, since this isn't randomising anything.

Also loosely disagree with blinds being behind flashlight because it's such a different concept.

**Comment by Henry-YSLin** [comment]
I do agree with the discoverability issue, so here you go. In this case, I think flashlight and blinds should also be separated. Looks like an inconsistency to me if they aren't.

**Comment by peppy** [comment]
Implementation wise this seems fine, but not sure about naming. Wouldn't something like "Invert" be more fitting and understandable?

**Comment by frenzibyte** [comment]
> I do agree with the discoverability issue, so here you go. In this case, I think flashlight and blinds should also be separated. Looks like an inconsistency to me if they aren't.

I disagree, "Flip" and "Random" mods are conversion mods, they both convert the beatmap in their own way, one flips the type of objects, and the other randomizes it, I see nothing common between them other than they convert.

"Flashlight" and "Blinds" are mods that narrow what the player can see, unlike the other mods in the same section. I guess there is still some difference between them that may impose separation, but they share something between, unlike the above.

**Comment by peppy** [comment]
That is not up for discussion in this issue, please refrain.

**Comment by frenzibyte** [comment]
Right, my bad.

**Comment by Henry-YSLin** [comment]
Is the CI test failure related to this PR? I could not reproduce it locally.

**Comment by peppy** [comment]
No, it's safe to ignore.

**Comment by frenzibyte** [comment]
Not 100% on the weird inheritance between `ManiaModInvert` which inverts empty sections with hold notes and vice versa, and `TaikoModInvert` which just inverts the type of the object, they're both completely different.

While it still makes sense that what the taiko mod does is inverting and what mania mod does is also inverting, I guess returning back to the name "Flip" would be a better choice to at least separate between what the two are doing and avoid confusion between them?

**Comment by Henry-YSLin** [comment]
I'm fine with either "Flip" or "Invert". But if we are using "Invert", this taiko mod will have the same name, title and whatnot as `ManiaModInvert`, so it makes sense to extract them into a base class imo.

**Comment by Joehuu** [comment]
Also disagree on naming this mod "Flip". Just throwing another proposal but how about "Swap"?

**Review by peppy — APPROVED** [review]

**Pull request merged**
