### PR TITLE
Fix taiko circle fills missing after rewind

### LINKED ISSUE #18478: Taiko circle fill missing in editor when rewinding back after kiai starts
Really strange one. I was going to chalk it up to frame stable seeks again but something looks really wrong here, there's a sprite present where it should be but it's just... not showing? It's not transparent either:

osu_2022-05-29_14-40-25

### Discussed in https://github.com/ppy/osu/discussions/18472

<div type='discussions-op-text'>

<sup>Originally posted by **hwabis** May 29, 2022</sup>
Let the editor play until it gets to the kiai, then seek back to right before the kiai. I can consistently reproduce this on any map with a kiai section. (Also happens with the osu! (triangles) skin; the circles don't fully load.)

(Logs just in case)
[updater.log](https://github.com/ppy/osu/files/8792653/updater.log)
[database.log](https://github.com/ppy/osu/files/8792654/database.log)
[network.log](https://github.com/ppy/osu/files/8792655/network.log)
[performance.log](https://github.com/ppy/osu/files/8792656/performance.log)
[runtime.log](https://github.com/ppy/osu/files/8792657/runtime.log)

https://user-images.githubusercontent.com/62194990/170852559-06448835-6a0d-42c6-8659-00bc733965f4.mp4</div>

### PR DESCRIPTION
**Pull request by smoogipoo**
Fixes https://github.com/ppy/osu/issues/18478

Not sure on a better fix for this yet. Disabling masking in general is kinda dodgy, not entirely sure why it's done (likely so that updates continue to propagate or something) but I'd rather not break things for now.

### CODE REVIEW

**Comment by peppy** [comment]
Probably good to make a tracking issue for the masking being disabled and link inline..

**Comment by smoogipoo** [comment]
I'm not sure what the issue would be though, dunno. It'd just be something that exists in eternity?

**Comment by peppy** [comment]
Yeah maybe fine.

**Review by peppy — APPROVED** [review]
Seems to work 🙈

**Pull request merged**
