### PR TITLE
Fix "spinner" conversion for mania-specific beatmaps

### LINKED ISSUE #30836: osu!Mania Converted Standard maps do not read Spinners correctly compared to Stable
### Type

Game behaviour

### Bug description

Spinners might not be converting to Hold notes the same way between Lazer and Spinners. Upfront I want to mention that these two maps are the only examples I have so far of this issue occuring. So maybe there is some reason why it's not applying the same way to these two maps, where all other maps I have checked (about 15+ with over 4 spinners) seem to work fine between the two clients.

Mania Screenshot_2 1 1

The following is a clip of a Loved standard map that has an excessive amount of "ninja" spinners in it. You can see how the patterns are completely different between Stable and Lazer. Here is a link to this map seen in the video https://osu.ppy.sh/beatmapsets/814850

https://github.com/user-attachments/assets/091ecea9-37cc-41cc-b9c2-378c0e447e2c

You can find a longer clip showing the bug here: https://youtu.be/Bf4G5_57b_E

I believe I have an explanation for why this is happening. Spinners in Stable have a randomization effect placed on them, but this probably is not being applied to these objects in Lazer. You can see my rationale for why below.

I discovered this bug while mapping on the very first version of osu! on osekai with Mania support which is b20121003shine.test. This version of the game allows mappers to use unconventional object types for modern Mania maps such as Spinners and Sliders (rather than Hold notes)

image showing mapping in b20121003shine.test
This image is from b20121003shine.test

In Stable, Spinners appear to always be in the 3rd column on a 4 Key map in the editor, but in gameplay end up in different columns. This trait about spinners also holds true today even in the latest version of Stable.

You can see in the screenshot below the spinner appears to be in column 3, but in gameplay it is actually in column 1

| Editor  | Gameplay |
| ------------- | ------------- |
| image  | image  |

Just to show that this is also the case for Spinners in Stable, here is the same exact thing happening on the latest version of stable

| Editor  | Gameplay |
| ------------- | ------------- |
| image  | image  |

**This is not the case in Lazer.** Spinners will always appear in the 3rd column in the editor AND gameplay.

| Editor  | Gameplay |
| ------------- | ------------- |
| image | image  |

Other spinners in this map like the very last one appear to be in column 3 in the editor, but in gameplay it ends up in column 4.

| Editor  | Gameplay |
| ------------- | ------------- |
| image  | image  |

Here is Stable, same as in b20121003shine.test

| Editor  | Gameplay |
| ------------- | ------------- |
| image | image  |

But you can see in lazer it once again stays in the 3rd column, not matching stable

| Editor  | Gameplay |
| ------------- | ------------- |
| image | image |

This map was exported from b20121003shine.test and imported directly into both Stable and Lazer. I did not save once in the newer clients so I can be 100% certain that you are not looking at these hitobjects being converted to their modern Hold counterpart. You can also tell this because Sliders in Mania will play their hitsound on both the head and tail of both Sliders and Spinners. This does not happen with Hold notes.

I uploaded the map I made here so you can see what I am talking about. I made sure it's a still .osu v10 after upload and did not have it's object types converted to the modern types. This way you can actually test this map to see the bug. It's available here https://osu.ppy.sh/beatmapsets/2283436#mania/4869637

I am not able to find too many other maps that exhibit this problem. Checking other converted maps with 4 or more spinners in both clients has so far not yielded any other maps with issues as big as the two I mentioned above.

### Screenshots or videos

_No response_

### Version

2024.1115.3-lazer (and all previous versions)

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17868908/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by smoogipoo**
Fixes https://github.com/ppy/osu/issues/30836

PRing as draft for now until the diffcalc spreadsheet is generated and (hopefully) shows some more differences I can cross check.

Some commentary provided in individual commits. tl;dr: Spinners need to go through the conversion path rather than converted as simple hold notes.

### CODE REVIEW

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=mania

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=mania
NO_CONVERTS=1

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=mania
GENERATORS=score

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=mania
TOLERANCE=0

**Comment by smoogipoo** [comment]
Unless I'm doing something wrong I can't find any differences in ranked maps, neither with the spreadsheets above nor offline testing + custom code over the https://data.ppy.sh beatmap dumps (which finds the case in the added test). So this is likely an isolated scenario and I think the PR is ready to be merged but no further considerations need to be made.

**Comment by bdach** [comment]
So I was going to do minimal review on this, just basically a baseline check of a few things, and probably get it in, but something doesn't look right here.

The two known-broken beatmaps given by the issue reporter are https://osu.ppy.sh/beatmapsets/814850#osu/1901200 and https://osu.ppy.sh/beatmapsets/2283436#mania/4869637. The first one is a bit annoying to do a cross-check on, so I checked the second, seeked to the first hold note, and... I'm not sure why but it's not the same?

| stable | master | this PR |
| :-: | :-: | :-: |
| screenshot001 | osu_2024-12-11_18-37-24 | osu_2024-12-11_18-34-37 |

The hold note moved, but... not where it should...?

I even extracted conversion mappings for both maps and both are failing even on this branch, so I'm not sure what is going on...

**Comment by smoogipoo** [comment]
Good catch. Let's try this one again then...

As for https://osu.ppy.sh/beatmapsets/814850#osu/1901200, the beatmap uses negative spinner durations which we clamp to 0 to avoid exceptions in other places of the game. We _can_ throw an exception as we do for every other parsed value exceeding limits, but I'm choosing to ignore this for the time being to avoid potentially throwing many errors into the user's notifications. It's not just spinners - break times have to be validated too and I'm not sure how large the scope of that is:
https://github.com/ppy/osu/blob/ae1030197a9fac6d3b947f2e8be59b2ca4b7d27d/osu.Game.Rulesets.Mania/Beatmaps/Patterns/Legacy/PatternGenerator.cs#L103

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=mania
TOLERANCE=0
GENERATORS=pp,sr,score

**Comment by smoogipoo** [comment]
Well, the sheet is still empty. Not sure what to do other than merging at this point 😬

**Review by bdach — APPROVED** [review]
Merging it is then I guess.

If the other beatmap uses negative spinner duration then I consider that to be unsupported and undefined-behaviour loved/aspire dumbness and thus no longer care.

**Pull request merged**
