### PR TITLE
Hint bass library path when running from vscode on linux

### LINKED ISSUE #2861: Startup crash on linux
screenshot
If I click continue it keeps running but no window or console output appears.
[runtime.log](https://github.com/ppy/osu/files/2127389/runtime.log)

[debug console output](https://paste.ee/p/Qk4lF)

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/59999063-startup-crash-on-linux?utm_campaign=plugin&utm_content=tracker%2F4707269&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F4707269&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by LastExceed**
@Tom94 already did this for the framework here: ppy/osu-framework#1617

credits to @SlowLogicBoy for finding and explaining the fix here: https://github.com/ppy/osu-framework/issues/1540#issuecomment-390491900

closes #2861 

---

### CODE REVIEW

**Comment by SlowLogicBoy** [comment]
1. LD_PRELOAD and LD_LIBRARY_PATH part is only for development and only for net core, it doesn't affect released/published version of osu!.
2. libbass and libbass_fx is not an opensource library, so there is no easy way to install this on Linux or Mac.
3. It would make osu! development easier since it would require less steps to make osu! development up and running on your machine.

**Comment by VPeruS** [comment]
@SlowLogicBoy you not correct in second one, they provide .so and it's all what you need to create package https://aur.archlinux.org/packages/libbass/

**Comment by Criminalllz** [comment]
@SlowLogicBoy not correct on the first one either, firstly, mono is not being supported going forward, also rpath does not globally load all the libraries in the path, so you still need to load it globally before loading libbass_fx. Also, using rpath looks to me as basically the same as using LD_LIBRARY_PATH

For the third one; Yes, including every single library osu uses would make it easier, but we shouldn't actually do it right? Right now we are using 11MB to store libbass (on all platforms) after building. I installed it from https://un4seen.com and it takes 348KB, and other programs can make use of it.

**Comment by peppy** [comment]
This needs to be adjusted in line with the [framework launch.json](https://github.com/ppy/osu-framework/blob/master/.vscode/launch.json) (should no longer need `LD_PRELOAD` and should prepend to existing envvar rather than overwrite)

**Comment by morguldir** [comment]
If we do what is suggested in https://github.com/ppy/osu-framework/issues/1638 we won't need this at all.

**Comment by VPeruS** [comment]
We don't need preload but library_path will be required

**Comment by morguldir** [comment]
The preload part has already been made unnecassary.

The LD_LIBRARY_PATH is also unnecassaray if we use the new library structure, you have basically said it yourself.

**Comment by VPeruS** [comment]
There are two issues: segfault from libbass_fx(you solved it with direct dlopen) and missing libbass. Correct package structure solve problem where to place .so files so DllImport will load them correctly. But direct dlopen call don't know about coreclr loading rules.

**Review by peppy — APPROVED** [review]

**Pull request merged**
