### PR TITLE
Reduce memory allocation of ContextMenuItems property

### PR DESCRIPTION
**Pull request by arphox**
I saw PR #4900 and I was wondering if you are open to optimizations like I just did here.

**Explanation**
The `List<T>.ToArray` method creates a new array which it will return. After returning, at some point the GC will have to clean up the list (internal array + private variables). I changed the logic to another implementation which does not use a List, hence it is more lightweight in terms of memory allocation.

It does not have high impact or anything but I thought if we could improve the code a bit, why not.

Let me see what do you think about it, and whether are you open for fixes like these.

### CODE REVIEW

**Comment by Aergwyn** [comment]
Mmh, any intended improvement to performance should at least have some kind of benchmark showing the difference otherwise it's hard to judge. Regarding the solution I'd say this seems to be too convoluted for a probably marginal gain, if at all.

**Comment by arphox** [comment]
As I said, this does not affect performance in a visible way. The proof of my words are the reference implementation of the .NET framework, so I am quite sure that I am right (regarding memory allocation).

So if that helps to decide, it **is** better but such a little that it does not count at all.

_(It's just the performance-crazy part of my mind that hit me 😄)_

**Comment by peppy** [comment]
Generally we prefer code quality over microoptimisations like this. A possible better pathway would be to change ContextMenuItems to be an `IEnumerable` to avoid such allocations in the first place (and enable use of `yield return` etc, which will likely ready better).

**Comment by arphox** [comment]
`yield return` probably makes things even worse since it makes the compiler to generate hidden display classes with logic inside. From my current workplace experience this is a bad practice in general (in deep business logic) because developers can potentially overdose closures with context objects which reduces performance, and the worse thing is that is hard to measure since the perf hit is inside a generated class.

I think cached `ContextMenuItems` would be a better way to go, because currently the same array is returned all the time (caller probably shouldn't cache it I think because the callee may return different objects each call).

But, this part of code is really far from being "bad" in terms of performance, so let's just keep it as it is, I agree. 🙂 

Thank you @peppy for your answer, then I will stay away from PRs like this in the future and try to catch something else.

**Comment by peppy** [comment]
It's only called when required, on a user operation. We don't generally optimise for such cases. Such optimisations are valuable for repeated or every-frame task, but not here.

**Pull request closed without merging**
