### PR TITLE
Allow mouse wheel to change volume in pause and fail screen

### LINKED ISSUE #1800: Mouse wheel doesn’t adjust volume at pause screen
can not change volume when pause

At song select ,scroll between the detail and the list will change master volume
but this is annoying,because i want to scroll the list not change volume.

### PR DESCRIPTION
**Pull request by FreezyLemon**
There are two parts to this:
1. `VolumeControlReceptor` 'implementing' `IHandleGlobalInput` so that it doesn't get removed from the overlays' input queues
2. Triggering the volume change from the actual overlay. Note that we cannot let the wheel pass through normally under any circumstance, since mwheelup and mwheeldown are valid game keys -> you could click circles through the overlay. So I decided to DI the global binding manager and trigger it manually. 

This closes #1800 .

### CODE REVIEW

**Comment by peppy** [comment]
Why is #2 true? in `OverlayContainer`, anything that isn't implementing `IHandleGlobalInput` should be removed, including any gameplay handlers, no?

**Comment by peppy** [comment]
Right, this is because MouseWheel is considered a mouse queue "positional" event.

**Comment by smoogipoo** [comment]
Isn't the correct fix to change how the mouse queue is built in `OverlayContainer` to remove all but the `IHandleGlobalInput`?

**Comment by peppy** [comment]
Possibly. This is how it's already done for the keyboard input queue. A `ReceiveInputAt` check would first need to be run so we don't handle input outside the overlay's bounds, though.

**Comment by smoogipoo** [comment]
Yeah so we've encountered this same issue before with keyboard input, but the same changes haven't been done to `OverlayContainer` for it.

It's going to take quite some work but I think it's worth it in the end - you essentially want to end up with something that resembles the following:
screen shot 2018-01-11 at 5 32 59 pm

**Comment by peppy** [comment]
Why a screenshot and not a PR? :P

**Comment by smoogipoo** [comment]
I've applied a fix at an OverlayContainer level. Please see the referenced PRs. Closing this one.

**Pull request closed without merging**
