### PR TITLE
Remove local handling of realm when switching thread modes

### PR DESCRIPTION
**Pull request by peppy**
This has been replaced with a proper `SynchronizationContext` implementation.

- [x] Depends on https://github.com/ppy/osu-framework/pull/4149

### CODE REVIEW

**Review by bdach — DISMISSED** [review]

**Review by smoogipoo — DISMISSED** [review]

**Comment by smoogipoo** [comment]
Tests timed out :(

**Comment by bdach** [comment]
Not necessarily related to these changes unfortunately. Something similar happened over the weekend in https://github.com/ppy/osu/pull/14937/checks?check_run_id=3781985630.

**Comment by peppy** [comment]
This is likely going to be a local issue again, due to the new isolated tests with their own sync contexts. Hopefully.

**Comment by smoogipoo** [comment]
Cancelled after 45min runtime. Stuck again: https://github.com/ppy/osu/runs/3789878441?check_suite_focus=true

**Review by bdach — APPROVED** [review]

**Comment by peppy** [comment]
Hold off briefly on merging this one, want to look into the test failures (may be related, caused by changes in execution ordering).

**Comment by peppy** [comment]
Test failures unrelated. Going to get this one in.

**Pull request merged**
