### PR TITLE
very important typo breaking all the syntax

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by abalabahaha** [comment]
Read last comment on #2

**Comment by Hatsuney** [comment]
:kissing:

**Comment by sr229** [comment]
ehhh


what syntax?

**Comment by failedxyz** [comment]
:trollface:

**Comment by sr229** [comment]
wow. such commit. very contribute.

this pullreq must be a troll pullreq

**Comment by Codicassert** [comment]
you see, my local forked version, running in microsoft visual studio 2016,
doesn't compile it because it does not know System.PersonalPronoun.Mw,
which obviously has to be replaced by System.PersonalPronoun.Me, else this
code written in EN# will not compile, and the text will be unreadable...
also theres no comments so someone should fix that

**Comment by failedxyz** [comment]
welp

**Comment by youkoso** [comment]
wot eto prikol.

**Pull request merged**
