### PR TITLE
Automatically adjust per-hit object slider velocity in osu!catch editor

### PR DESCRIPTION
**Pull request by ekrctb**
Previously, the path of a juice stream was restricted by the slider velocity.
With this PR, the slider velocity of the juice stream is automatically adjusted so a steeper path (faster movement) is possible.
I think the new behavior is more intuitive for users.
Background: per-hit object slider velocity was not available when I initially implemented the juice stream editing.

There is still a limit of the slope of a path at the maximum slider velocity setting `10`.
However, I removed the slope-based clipping feature from `JuiceStreamPath` so the vertex are not clipped anymore. Instead, the  slider path is clipped when converted from `JuiceStreamPath`.

Note: #18147 is needed to correctly save an edited map correctly. It also affects undo/redo.

<https://github.com/ppy/osu/pull/18156/commits/4e0155fa4bac0dd8a8316f4cf1e80b610a465e17> changes `JuiceStreamPathVertex` to use time instead of distance so a `JuiceStreamPath` is unchanged when the slider velocity is changed.
The previous distance-based implementation was convenient for the slope restriction (because the limit is always `1`) but the restriction feature is removed so it is more convenient to use time instead.
Related commits: <https://github.com/ppy/osu/pull/18156/commits/37c9aac49f836bb49f57c0ea246998dcf6815144>.

The commit <https://github.com/ppy/osu/pull/18156/commits/9ffa90602bc675ed0a37eac66845b34f36948f8f> is the actual implementation of the automatic slider velocity change.

In <https://github.com/ppy/osu/commit/670922c8e563c202b6d7e396450f64ce77ecb78d>, I modified `JuiceStream` so the velocity is updated from a slider velocity change immediately. Without this commit, the selection blueprint suffices from one-frame glitches because `EditorBeatmap.Update` is batch-processed.
It also makes sense if the per-hit object `DifficultyControlPoint` as a property of a hit object, different from other control points. I believe this change has no unexpected side-effects.
Related commits: <https://github.com/ppy/osu/pull/18156/commits/7daa3d8eb79b59756fad96810012c01e3a167dfe>.

Future direction: we can hide the slider velocity in timeline because it doesn't affect editing experience other than bookkeeping of mappers.

### CODE REVIEW

**Comment by peppy** [comment]
I haven't looked into the code in detail yet, but I'm having a bit of trouble understanding the visual hinting:

https://user-images.githubusercontent.com/191335/167391684-9b1eb9b3-a9a4-44f8-9e13-a7e96f7f12ab.mp4

My expectation is that the more acute path is the hyperdash extent (if it is it should probably have  red colour instead of white), but only some positions seem to trigger hyperdash visuals. Is this a bug?


https://user-images.githubusercontent.com/191335/167392014-34f47ace-052c-41b5-a375-8b1c7c934088.mp4

Logically I might be missing something very obvious, but my expectation when dragging the juice stream is that SV will not always be integer values. Like, the length is changing but the values are always whole numbers.

**Comment by ekrctb** [comment]
> My expectation is that the more acute path is the hyperdash extent (if it is it should probably have red colour instead of white), but only some positions seem to trigger hyperdash visuals. Is this a bug?

(This is not related to this PR) The wider lines of the distance snapping are not indicating the hyperdash threshold. It is indicating the dashing catcher speed so multiple objects on the line are perfectly catchable just by holding Dash+Direction.
Probably another lines indicating the hyperdash threshold somehow (it will be the same slope as the dash line but moved in x-axis) but hit objects shouldn't be snapped to these lines.

> Logically I might be missing something very obvious, but my expectation when dragging the juice stream is that SV will not always be integer values. Like, the length is changing but the values are always whole numbers.

This is explained here <https://github.com/ppy/osu/pull/18156/files#diff-458fe97d0619dc2d1c9a8e8ed33658288b6097799f71bf30f2a748452d5ed73fR100-R104>.

> This is rounded to integers instead of using the precision of the [slider velocity] bindable because it results in a smaller number of non-redundant control points.

**Comment by peppy** [comment]
I have a general understanding of what this is doing now (thanks to @ekrctb explaining on stream) and think it's a good direction. Still need to go through the code.

**Comment by peppy** [comment]
I think this is fine to get in. I agree that we would want to hide the velocity from the timeline. Not yet sure on where that should be handled, will need further investigation as to further use cases.

**Review by peppy — APPROVED** [review]

**Pull request merged**
