### PR TITLE
Fix column lights positioned incorrectly

### PR DESCRIPTION
**Pull request by smoogipoo**

### CODE REVIEW

**Comment by peppy** [comment]
This still looks too high on the default skin:

image

**Comment by smoogipoo** [comment]
That's the explosion, not the lighting, which hasn't been done yet.

**Comment by mcendu** [comment]
> 
> 
> That's the explosion, not the lighting, which hasn't been done yet.

Would be an easy fix

**Comment by smoogipoo** [comment]
Ah hang that's a regression on the default skin, different issue though.

**Comment by peppy** [comment]
This is good to go, right?

**Review by peppy — APPROVED** [review]

**Comment by smoogipoo** [comment]
Yep

**Pull request merged**
