### PR TITLE
Switch scroll direction for beat snap

### PR DESCRIPTION
**Pull request by kongehund**
Matches stable

### CODE REVIEW

**Comment by bdach** [comment]
I was worried this was going to happen but did not double check the bindings against stable to make sure.......... unless this was explicitly intended? @peppy please advise

If this PR is to go in the note in https://github.com/ppy/osu/pull/31147#discussion_r1893818402 still applies. As in this won't actually change any bindings for users. (Why do I have to keep pointing this out? Surely you would find this out if you tested this?) The easiest solution to that would be to bump realm schema version again, and bump the version number on that specific switch block added in https://github.com/ppy/osu/pull/31147/commits/9ff4a58fa3724904c13f1117c14ab03824963dda to rerun the migration.

**Comment by peppy** [comment]
Hmm, not sure about this one. I didn't change the directionality in lazer in my PR (very intentionally, albeit without checking against stable), and still feel like what we have is more natural.

Will have a play and see how weird this feels.

**Comment by peppy** [comment]
I don't know, up/down on mouse wheel seems to be arbitrary at best when the resulting action isn't a vertical adjustment (such as this case).

I'd say we probably just match stable here and call it a day for now. Users can adjust as they see fit 🤷

**Comment by peppy** [comment]
Stable reference: https://github.com/peppy/osu-stable-reference/blob/3ea48705eb67172c430371dcfc8a16a002ed0d3d/osu!/GameModes/Edit/Modes/EditorModeCompose.cs#L214-L234

**Review by peppy — APPROVED** [review]

**Review by bdach — APPROVED** [review]
sigh

**Pull request merged**
