### PR TITLE
Force imports on the import task scheduler earlier in the import process

### PR DESCRIPTION
**Pull request by peppy**
- [x] Depends on #11802

I noticed when working on the dependent PR that some pieces of the import process are not correctly being scheduled to the `ArchiveModelManager` scheduler, instead being run on the TPL thread pool. This shifts the tasks across to the custom scheduler as soon as possible.

Note that due to `await` operations running between this and the "final" import method (where the original schedule was happening) the order of execution may not be sequential. In a test of importing from stable, all the initial tasks (obtaining the `ArchiveReader`s) complete before the final imports begin.

I've kept this as a separate PR because I'm only 99% confident in this. It seems to work in practice and feels safer, but looking for more opinions on this.

### CODE REVIEW

**Review by bdach — APPROVED** [review]
I think this makes sense.

**Comment by smoogipoo** [comment]
The following check right before the GetReader() call shows that the task is still running on the TPL:
```
if (TaskScheduler.Current == TaskScheduler.Default)
{
}
```

**Comment by peppy** [comment]
Hmm, so maybe we don't want the scheduler hidden? Does that fix it with your testing in place?

I don't remember the original reason for doing so.

**Comment by smoogipoo** [comment]
I think otherwise nested tasks (specifically the actual import) would be queued after everything else during import?

**Comment by peppy** [comment]
So really what we want is limited ingress into the import scheduler (which is kind of what the scheduler we have is doing), but probably also want a second scheduler which handles the active import(s)?

**Comment by smoogipoo** [comment]
Probably yeah. I'm not actually sure if the way we're using the scheduler now is providing much use, because if it's jumping away from the import scheduler at the first `await` then probably `createBeatmapDifficulties` is being run on the .NET threadpool, which is a significant portion (e.g. allocs from diffcalc) that can contribute to game-wide lag during import...

**Comment by peppy** [comment]
Probably best to close this and open an issue tracking that part, will do that.

**Pull request closed without merging**
