### PR TITLE
Add support for key bindings in gameplay menus

### LINKED ISSUE #4168: Can't use space/enter to retry at pause/fail screen
**Describe your problem:** Cannot use the global select keys on the restart/fail beatmap menu. Raised initially in my PR here: https://github.com/ppy/osu/pull/3718
**Screenshots or videos showing encountered issue:** N/A

**osu!lazer version:** osu!lazer version: 2019.126.0 (commit 718136a)

**Logs:** N/A

### PR DESCRIPTION
**Pull request by Scotsoo**
Add any details pertaining to developers above the break.

- Closes #4168

---

Allowing global select keys to be used on failure/pause menu

### CODE REVIEW

**Comment by Scotsoo** [comment]
I can't seem to figure out why the testEnterKeySelection test case is failing. I can't see where any GlobalActions from the IKeyBindingHandler are tested in the tests. Any guidance @peppy, @smoogipoo ?

**Comment by peppy** [comment]
Did you try debugging the test that failed?

**Comment by Scotsoo** [comment]
Yeah, I looked into it for a lot longer than it took me to make the change. 
https://github.com/ppy/osu/blob/22926bad9f53dfb6c92fbf3fadc4acd57e4f07ad/osu.Game.Tests/Visual/TestCaseGameplayMenuOverlay.cs#L258
This simulated enter press isn't getting caught by the keyBindingHandler when running the tests. However, with tests running I hit enter on my physical keyboard then the action is handled. I'll take another look tonight when I'm home. But any thoughts are appreciated

**Comment by UselessToucan** [comment]
@Scotsoo I suggest you to check [#1745](https://github.com/ppy/osu-framework/pull/1745) framework PR. There are some platform action related tests there.

**Comment by Scotsoo** [comment]
@UselessToucan Cheers, I'll take a look when I manage to sit down and put some work into this again. Thanks for the headsup!

**Review by peppy — APPROVED** [review]

**Pull request merged**
