### PR TITLE
Fix sliders not always being the correct length

### LINKED ISSUE #24708: Ranked beatmap has 1 less slidertick/combo in Lazer compared to Stable
### Type

Game behaviour

### Bug description

[`4182386`](https://osu.ppy.sh/beatmapsets/2007300#osu/4182386) shows `293` max combo in Stable (and as can be seen on the score leaderboards), but in Lazer the map only has `292` max combo. This is likely related to #24401.

### Screenshots or videos

For Stable, the editor shows that the 7th object has 1 slidertick right before the sliderend (actually after if you consider the -36ms):
screenshot4474
While for Lazer, the tick does not exist:
osu_2023-09-03_02-20-04

---

Further inspection shows that the `tickDistance`, `Velocity`, and `length` values in Lazer are slightly inconsistent with Stable.
> Notes:
> `minDistanceFromEnd` is a multiple of `Velocity`
> `distanceToEnd = length - tickDistance`
> `scoringLengthTotal` is `length`
> `minTickDistanceFromEnd` is `minDistanceFromEnd`
> `skipTick` is `true` when `distanceToEnd <= minDistanceFromEnd`

Lazer's values from debugging:
lazer slider inconsistency

Stable's values from debugging:
image
image
image

The slight differences causes Lazer to have a smaller `distanceToEnd` value and a larger `minDistanceFromEnd` value, which causes `skipTick` to be `true`, thus no slidertick is created for the slider.

---

Since I assume the server also uses the same logic as Lazer to process beatmaps, the database ends up having the wrong max combo in respect to Stable, as shown in the API response for the beatmap:
image

### Versions

2023.815.0-lazer
b20230814cuttingedge

### Logs

[network.log](https://github.com/ppy/osu/files/12505265/network.log)
[performance.log](https://github.com/ppy/osu/files/12505266/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12505267/runtime.log)
[database.log](https://github.com/ppy/osu/files/12505268/database.log)
[input.log](https://github.com/ppy/osu/files/12505269/input.log)

### PR DESCRIPTION
**Pull request by peppy**
This is another similar case where stable floating point precision comes into play due to use of `hitObjectManager.Beatmap.BpmMultiplierAt` (see https://github.com/peppy/osu-stable-reference/blob/1531237b63392e82c003c712faa028406073aa8f/osu!/GameplayElements/HitObjects/Osu/SliderOsu.cs#L680)

Closes #24708.

- [x] Depends on #24738

### CODE REVIEW

**Comment by bdach** [comment]
Looking into the [point raised on discord](https://discord.com/channels/188630481301012481/188630652340404224/1149271737394004020) about stable mappings outputting slider ticks non-chronologically, that tracks with stable code: https://github.com/peppy/osu-stable-reference/blob/1531237b63392e82c003c712faa028406073aa8f/osu!/GameplayElements/HitObjects/Osu/SliderOsu.cs#L980-L984

The last `sliderScoreTimingPoint` is pulled back by 36ms, but the list of all of them is not re-sorted afterwards. Therefore I think this is safely ignorable and we can just reorder the mappings in the json output.

I haven't checked if the lack of re-sort has any adverse effect on stable, but in my view, if it did, it'd be a pretty horrible stable bug anyways, and should be fixed in lazer by all costs, so I kinda don't care about that (...unless proven otherwise I guess)

**Comment by bdach** [comment]
I've pushed changes to fix the test failures and to adapt this to the changes in https://github.com/ppy/osu/pull/24738. Note that I'm not saying https://github.com/ppy/osu/pull/24739/commits/5c6cd879ddae01fd86b29622d51652847b99a5e7 is correct in the "matches stable" sense, but it should be correct in the "rearranged terms" sense. @peppy would appreciate a double check whenever able.

I'll do a diffcalc on this and see what comes out (because something inevitably will), and I'll double check ground truth with stable after that.

**Comment by peppy** [comment]
I think the updated code looks correct, but the diffcalc will be the true test of that.

**Comment by bdach** [comment]
Diffcalc sheet came out... empty? https://docs.google.com/spreadsheets/d/1Bw4uf8Ixwr6T0Y96kdXcqEr_slx7fC5UgExry7aEN_g/edit#gid=400707347

I find that a little hard to believe, but not sure how I could have screwed that up...

**Comment by bdach** [comment]
Well I'm not really sure what to do with this change now... The way I see it, either we just merge it and see what happens, or I guess I try to somehow rig stable to extract conversion mappings for all ranked maps / all maps period and try to cross-test that against this branch? I'm not sure how else to validate this...

@peppy @smoogipoo thoughts, ideas?

**Comment by peppy** [comment]
I think it's fine to go ahead with merge. As far as I know, ticks do not factor into diffcalc so I would assume this doesn't result in a change.

**Review by bdach — APPROVED** [review]

**Comment by bdach** [comment]
Guess we do it live and see if this goes wrong...

**Comment by smoogipoo** [comment]
> As far as I know, ticks do not factor into diffcalc

They are factored in:

https://github.com/ppy/osu/blob/0985bb05775119039ff3e9df3a226042541ad12e/osu.Game.Rulesets.Osu/Difficulty/Preprocessing/OsuDifficultyHitObject.cs#L212-L269

But it's likely that the difference is too small to matter.

**Pull request merged**
