### PR TITLE
Improve intro timings when not using osu! theme

### PR DESCRIPTION
**Pull request by peppy**
Roughly as proposed in https://github.com/ppy/osu/discussions/19687.

### CODE REVIEW

**Comment by smoogipoo** [comment]
I personally think this feels even more jank than on master.

**Review by smoogipoo — APPROVED** [review]

**Comment by peppy** [comment]
> I personally think this feels even more jank than on master.

Can you explain more? Do you feel the track is starting too early, or dislike the fade in? It is in no way supposed to feel more jank to even one person, so I'd consider rolling back if you have found issue.

**Comment by smoogipoo** [comment]
Yes, I think the track is starting too early. I didn't even notice there's a fade in.

**Comment by peppy** [comment]
Were you testing with intro theme off and voice on? Any specific intro style / beatmap?

**Comment by smoogipoo** [comment]
The worst one was triangles to me, and on beatmaps which start immediately like https://osu.ppy.sh/beatmapsets/1201605#osu/2502643

**Comment by smoogipoo** [comment]
To be clear, I don't know if this is resolvable by tweaking timings. It just feels awkward for the into to continue doing its stuff while there's completely unrelated music going off in the background. Especially since triangles is a fairly long intro

**Comment by peppy** [comment]
The other option is to just start the track from when the game starts. Might work better.

**Pull request merged**
