### PR TITLE
Hide osu!catch touch input controls when relax mod is enabled

### PR DESCRIPTION
**Pull request by Ghost1928563945**
This PR hides the TouchField when the Relax mod is enabled. Previously, the relax mod would not work because the Touch field captured the input.

### CODE REVIEW

**Comment by toadsworth-jr** [comment]
In my opinion, there's a workaround for this, and it's called "Show cursor during touch input"
Although the contributors of the project are free to minimize this comment as they see fit.

**Comment by NullifiedJosh** [comment]
> In my opinion, there's a workaround for this, and it's called "Show cursor during touch input" Although the contributors of the project are free to minimize this comment as they see fit.

It doesn't matter if there is a workaround. if there was 2 paths, one that had a barrier and one that took 10 extra minutes would you like to take the detour? No, we should fix the first problem. Also, how is it an opinion to have a work around?

**Comment by NullifiedJosh** [comment]
Sorry for asking, but this pr adds 10 lines of code. Could it be reviewed soon?

**Comment by peppy** [comment]
Your PR will be reviewed **as we find the time and effort to do so**.

Line count does not necessarily give rite of passage to an instant review or merge.

Thank you for understanding.

**Comment by o-dasher** [comment]
> Sorry for asking, but this pr adds 10 lines of code. Could it be reviewed soon?

I already did a minor review and you plainly just ignored it, i don't know what you're expecting tbh.

**Comment by NullifiedJosh** [comment]
> > Sorry for asking, but this pr adds 10 lines of code. Could it be reviewed soon?
> 
> I already did a minor review and you plainly just ignored it, i don't know what you're expecting tbh.

I don't know if this is a GitHub mobile issue, but I don't see it.Screenshot of GitHub mobile app

**Comment by smoogipoo** [comment]
I haven't reviewed this because of test failures and CI inspections https://github.com/ppy/osu/pull/20426/checks

**Comment by NullifiedJosh** [comment]
> I haven't reviewed this because of test failures and CI inspections https://github.com/ppy/osu/pull/20426/checks

Sorry, my bad. I should've checked that before asking for a review 😅.

**Comment by peppy** [comment]
I've moved your tests to the existing scene for better discoverability, and adjusted the conditional slightly. Please check my commits to understand the remaining changes I saw necessary.

**Review by peppy — APPROVED** [review]

**Pull request merged**
