### PR TITLE
Allow scaling down to 5% in popover scale dialog

### PR DESCRIPTION
**Pull request by peppy**
Request from mapper IRL.

### CODE REVIEW

**Comment by OliBomby** [comment]
How about letting it go down to 0% or even negative? Such scaling values would also produce valid results. I think 0% could be useful while scaling on a single axis to squash the axis, or turn a pattern into a stack.

**Comment by peppy** [comment]
The issue with letting it go lower would be that the slider bar gets silly.

It would need to be textbox entry only. You're welcome to propose a diff for that, I wasn't willing to put in the effort without a user request because it's more complicated.

**Comment by bdach** [comment]
This didn't actually work properly. I have made it work with https://github.com/ppy/osu/pull/30482/commits/f616c7b752bb224107be796b11311f0b0aea77aa.

**Review by bdach — APPROVED** [review]

**Comment by OliBomby** [comment]
> The issue with letting it go lower would be that the slider bar gets silly.

You mean it would get silly for negative values right? For 0% minimum scaling it shouldn't make much of a difference to the slider bar since that only makes the range 0.5% bigger.

**Pull request merged**
