### PR TITLE
Add a fallback for humanizer localization lookup failures

### LINKED ISSUE #5279: Opening multiplayer lounge causes crash
**Describe the bug:** 
Game crashes when you are trying to open multiplayer lounge

**Screenshots or videos showing encountered issue:** 
https://www.youtube.com/watch?v=3y8Op01nh44

**osu!lazer version:** 
2019.704.0

**Logs:** 
https://pastebin.com/TC2Vv0pz

**Android device Specifications:**
OS | Android 8.0 (Marshmallow); MIUI 10.2
Chipset | Qualcomm MSM8996 Snapdragon 821 
CPU | Quad-core (2x2.35 GHz Kryo & 2x1.6 GHz Kryo)
GPU | Adreno 530

### PR DESCRIPTION
**Pull request by nyquillerium**
Fixes https://github.com/ppy/osu/issues/5279

At the moment, there seems to be some internal failure on Xamarin/Mono/Humanizer's part to do two things:

* [Copy the required language satellite packages to the APK.](https://github.com/xamarin/xamarin-android/issues/2012)
* [Fallback to the default package if a culture cannot be found.](https://github.com/Humanizr/Humanizer/issues/690#issuecomment-368536282)

In either case, it might be good to have a local fallback, so this PR introduces a helper function that catches exceptions thrown by humanizer that are a result of a failure to find a localization.

This was tested on an Android device and seems to be working fine.

### CODE REVIEW

**Comment by smoogipoo** [comment]
There has to be a better way of doing this, because what you've done here is not going to handle all humanizer cases... E.g. you've missed `.Pluralize`.

**Comment by smoogipoo** [comment]
Also please give links tracking the aforementioned issues, xamarin and/or humanizer.

**Comment by nyquillerium** [comment]
We can also potentially initialize a list of loaded cultures for humanizer at startup and checking against those instead, which would allow us to implement our own `TryGetCulture` method or similar.

**Comment by smoogipoo** [comment]
Have you tried including the package reference in the android project? https://github.com/Humanizr/Humanizer/issues/380#issuecomment-362321573

**Comment by nyquillerium** [comment]
yes, thats the first thing I tried actually.

**Comment by peppy** [comment]
This needs some kind of resolution.

**Comment by peppy** [comment]
Going with this for now as a "don't have a better idea" temporary fix.

**Review by peppy — APPROVED** [review]

**Pull request merged**
