### PR TITLE
Fix spinner crashing on rewind

### LINKED ISSUE #10335: Game crashes when moving playback to a spinner in editor
**Describe the crash:** The game crashes when you move the timeline playback to the moment a spinner occurs.

**Screenshots or videos showing encountered issue:** https://www.youtube.com/watch?v=o-1qRrhwW8M

**osu!lazer version:** 2020.1002.0

**Logs:**
[network.log](https://github.com/ppy/osu/files/5319303/network.log)
[performance.log](https://github.com/ppy/osu/files/5319304/performance.log)
[database.log](https://github.com/ppy/osu/files/5319305/database.log)
[updater.log](https://github.com/ppy/osu/files/5319306/updater.log)
[runtime.log](https://github.com/ppy/osu/files/5319307/runtime.log)

**Computer Specifications:** 
image

### PR DESCRIPTION
**Pull request by peppy**
- Resolves #10335

Not sure about test coverage for this one (I guess our autoplay / rewind tests don't go far enough into a track to have hit a spinner? Also FrameStabilityContainer likely saved the day).

### CODE REVIEW

**Comment by bdach** [comment]
There was another spot that was hitting this, I pushed in a commit fixing it.

There are tests covering spinners (see `TestSceneSpinnerRotation`, for one), but I think you're right that the frame stability is what prevented this from surfacing earlier. After dumping some logs, there is a possibility for something like this to happen in editor:

```
[runtime] 2020-10-03 19:37:14 [verbose]: triggering misses at state:
[runtime] 2020-10-03 19:37:14 [verbose]: None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10)
[runtime] 2020-10-03 19:37:14 [verbose]: None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10)
[runtime] 2020-10-03 19:37:14 [verbose]: None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10)
[runtime] 2020-10-03 19:37:14 [verbose]: None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10)
[runtime] 2020-10-03 19:37:14 [verbose]: None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10)
[runtime] 2020-10-03 19:37:14 [verbose]: None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10)
[runtime] 2020-10-03 19:37:14 [verbose]: None (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50)
[runtime] 2020-10-03 19:37:14 [verbose]: None (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50)
[runtime] 2020-10-03 19:37:14 [verbose]: None (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50)
[runtime] 2020-10-03 19:37:14 [verbose]: None (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50)
[runtime] 2020-10-03 19:37:14 [verbose]: None (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50)
[runtime] 2020-10-03 19:37:14 [verbose]: IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50)
[runtime] 2020-10-03 19:37:14 [verbose]: None (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50)
[runtime] 2020-10-03 19:37:14 [verbose]: None (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50)
```

I'm not entirely sure how this can happen yet...

**Comment by bdach** [comment]
I think I can see what's happening after adding some log statements. The long and short of it that in editor, some ticks can have their results not be reverted, if the seek is so fast that they become dead before they get a chance to revert. Here's a long annotated log excerpt that I hope shows what's going wrong:

<details>
<summary>log excerpt</summary>

```
list all ticks          tick @ 7928.928577415645 added; tick lifetime: [7028.928577415645, 1.7976931348623157E+308]
and their lifetimes     tick @ 8062.85715483129 added; tick lifetime: [7162.85715483129, 1.7976931348623157E+308]
                        tick @ 8196.785718277097 added; tick lifetime: [7296.785718277097, 1.7976931348623157E+308]
                        tick @ 8330.71430966258 added; tick lifetime: [7430.7143096625805, 1.7976931348623157E+308]
                        tick @ 8464.642873108387 added; tick lifetime: [7564.642873108387, 1.7976931348623157E+308]
                        tick @ 8598.571436554193 added; tick lifetime: [7698.5714365541935, 1.7976931348623157E+308]
                        tick @ 8732.5 added; tick lifetime: [7832.5, 1.7976931348623157E+308]
                        tick @ 8866.428619325161 added; tick lifetime: [7966.428619325161, 1.7976931348623157E+308]
                        tick @ 9000.357126891613 added; tick lifetime: [8100.357126891613, 1.7976931348623157E+308]
                        tick @ 9134.285746216774 added; tick lifetime: [8234.285746216774, 1.7976931348623157E+308]
                        tick @ 9268.214253783226 added; tick lifetime: [8368.214253783226, 1.7976931348623157E+308]
                        tick @ 9402.142873108387 added; tick lifetime: [8502.142873108387, 1.7976931348623157E+308]
                        tick @ 9536.071380674839 added; tick lifetime: [8636.071380674839, 1.7976931348623157E+308]
                        tick @ 9670 added; tick lifetime: [8770, 1.7976931348623157E+308]

start dragging around   editor clock @ 0
                        editor clock @ 663.7331543394756
                        editor clock @ 1487.8905231989327
                        editor clock @ 5020.059197866841
                        editor clock @ 15756.580959079725

spinner has ended and   triggering miss results for remaining ticks at time 15756.580959079725, state is:
has unjudged ticks -    None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) @ 7928.928577415645
apply misses to them    None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) @ 8062.85715483129
                        None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) @ 8196.785718277097
                        None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) @ 8330.71430966258
                        None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) @ 8464.642873108387
                        None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) @ 8598.571436554193
                        None (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 8732.5
                        None (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 8866.428619325161
                        None (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 9000.357126891613
                        None (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 9134.285746216774
                        None (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 9268.214253783226
                        None (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 9402.142873108387
                        None (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 9536.071380674839
                        None (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 9670

application happens     applied IgnoreMiss (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) to tick @ 7928.928577415645; time of application is 15756.580959079725
successfully            applied IgnoreMiss (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) to tick @ 8062.85715483129; time of application is 15756.580959079725
                        applied IgnoreMiss (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) to tick @ 8196.785718277097; time of application is 15756.580959079725
                        applied IgnoreMiss (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) to tick @ 8330.71430966258; time of application is 15756.580959079725
                        applied IgnoreMiss (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) to tick @ 8464.642873108387; time of application is 15756.580959079725
                        applied IgnoreMiss (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) to tick @ 8598.571436554193; time of application is 15756.580959079725
                        applied IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) to tick @ 8732.5; time of application is 15756.580959079725
                        applied IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) to tick @ 8866.428619325161; time of application is 15756.580959079725
                        applied IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) to tick @ 9000.357126891613; time of application is 15756.580959079725
                        applied IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) to tick @ 9134.285746216774; time of application is 15756.580959079725
                        applied IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) to tick @ 9268.214253783226; time of application is 15756.580959079725
                        applied IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) to tick @ 9402.142873108387; time of application is 15756.580959079725
                        applied IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) to tick @ 9536.071380674839; time of application is 15756.580959079725
                        applied IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) to tick @ 9670; time of application is 15756.580959079725

seek continues past     editor clock @ 36574.814473629915
spinner...              editor clock @ 51247.56451914726
                        editor clock @ 56445.97279719527
...and then goes        editor clock @ 57994.21387880532
backwards to it again   editor clock @ 50057.91799608371
                        editor clock @ 38306.77265573148
                        editor clock @ 27780.63680626468
                        editor clock @ 17727.50848191116
                        editor clock @ 11269.46658183368
                        editor clock @ 7431.255843995695

we're in the middle of  reverted IgnoreMiss (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) of tick @ 7928.928577415645; time of revert is 7431.255843995695
the spinner             reverted IgnoreMiss (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) of tick @ 8062.85715483129; time of revert is 7431.255843995695
reverts fire, but only  reverted IgnoreMiss (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) of tick @ 8196.785718277097; time of revert is 7431.255843995695
for the alive ticks!    reverted IgnoreMiss (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) of tick @ 8330.71430966258; time of revert is 7431.255843995695

                        editor clock @ 3552.5216780234314
                        editor clock @ 4135.412216549807
seek forward again      editor clock @ 10333.088797076965

past the spinner again  triggering miss results for remaining ticks at time 10333.088797076965, state is:
some results haven't    None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) @ 7928.928577415645
been unapplied!         None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) @ 8062.85715483129
                        None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) @ 8196.785718277097
                        None (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) @ 8330.71430966258
                        IgnoreMiss (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) @ 8464.642873108387
                        IgnoreMiss (Score:0 HP:0 MaxResult:SmallBonus MaxScore:10) @ 8598.571436554193
                        IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 8732.5
                        IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 8866.428619325161
                        IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 9000.357126891613
                        IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 9134.285746216774
                        IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 9268.214253783226
                        IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 9402.142873108387
                        IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 9536.071380674839
                        IgnoreMiss (Score:0 HP:0 MaxResult:LargeBonus MaxScore:50) @ 9670

```

</details>

That should explain why it doesn't happen in gameplay. I'm not sure whether the fact that this can happen is a problem of the spinner itself rather than the editor's. The change is still semantically correct, but I don't know that we should be necessarily testing for it...?

**Comment by peppy** [comment]
Nice find on the second case.

As you found in the logging, disabling frame stability causes some weird edge cases to come up. Optimally, we want `DrawableHitObject` code to behave correctly in such cases, but for now as long as they don't crash or look stupid, it's likely not going to be an issue during actual gameplay so pretty low priority.

A better fix here may be to have the spinner reset the ticks itself, when it is guaranteed they should not be in a hit state (`time < spinner.StartTime`).

**Review by smoogipoo — APPROVED** [review]
Looks fine to me.

**Pull request merged**
