### PR TITLE
Allow section changing in options menu using up/down keys

### PR DESCRIPTION
**Pull request by abraker95**

### CODE REVIEW

**Comment by peppy** [comment]
Not sure the keys (up/down arrows) makes sense here.

**Comment by abraker95** [comment]
I would like to make them bindable to any key, but I don't know how to make that happen

**Comment by peppy** [comment]
they shouldn't be bindable to any key.

i'm thinking maybe pgdn/pgup, but those should probably also be global at a scrollablecontainer level.

**Comment by abraker95** [comment]
Ah pgdn/pgup does make more sense. I'll fix the code up the next time I get a chance

**Comment by abraker95** [comment]
Hmmmm I've never dealt with committing the sources in the submodules, so need a bit help on how to make this work.

**Pull request closed without merging**
