### PR TITLE
Handle lack of skins directory when importing from osu!stable

### LINKED ISSUE #3432: Exception occurs if skin folder is not present when importing?
(I am aware that in the `.osu` folder, the skins folder is not present)

I just feel like this should not be an *unobserved error*.
Instead the game should have a notification telling the user that the folder cannot be found,
Or just have the same message when importing beatmaps from stable fails (No installation found)

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/63671411-exception-occurs-if-skin-folder-is-not-present-when-importing?utm_campaign=plugin&utm_content=tracker%2F4707269&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F4707269&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by plankp**
Fix #3432

### CODE REVIEW

**Comment by peppy** [comment]
This is not what you want. It will disallow importing of beatmaps if the skins folder is not present.

**Comment by plankp** [comment]
But at the moment, you cannot import skins if `Songs` does not exist

**Comment by plankp** [comment]
Or should that be changed as well?

**Comment by peppy** [comment]
It's nigh impossible that someone has an osu! install with skins but not beatmaps.

**Comment by plankp** [comment]
Ok, I will make the change elsewhere and rename this PR when completed

**Comment by peppy** [comment]
You can fix the crash by cherry-picking `8b820fee5c30bb470eab23fe05d9b9c48609ed0d` from my fork, for what it's worth.

**Comment by peppy** [comment]
Personally I would have added a check just after the `stable == null` check `if (!stable.DirectoryExists(x)) { Log; return; }` to avoid it running in a thread.

**Comment by plankp** [comment]
I have updated the code to do that instead of using a try-catch

**Comment by plankp** [comment]
Just tested with the code from your fork, it does handle the lack of `Songs` properly

**Comment by plankp** [comment]
@peppy This also prevents osu from crashing if you have no beatmaps, and you have osu!lazer import stuff for you.

Ready for review

**Review by peppy — APPROVED** [review]

**Pull request merged**
