### PR TITLE
Fix issue where multiplier show wrong value when adjusting speed on preset

### PR DESCRIPTION
**Pull request by Hy0tic**
This PR reference issue [#23234](https://github.com/ppy/osu/issues/23234)

The fix was already found by [cdwcgt](https://github.com/cdwcgt) in the discussion, I did a little investigation and found that when setting `modSettingChangeTracker` to `val.NewValue` , it didn't trigger [`updateMultipler()`](https://github.com/ppy/osu/blob/master/osu.Game/Overlays/Mods/ModSelectOverlay.cs#L346) when changing the speed slider (with preset mod selected). After changing `val.NewValue` to `SelectedMods.Value`, [`updateMultipler()`](https://github.com/ppy/osu/blob/master/osu.Game/Overlays/Mods/ModSelectOverlay.cs#L346) did get called when changing the speed slider.

### CODE REVIEW

**Comment by bdach** [comment]
> I did a little investigation and found that when setting `modSettingChangeTracker` to `val.NewValue` , it didn't trigger [`updateMultipler()`](https://github.com/ppy/osu/blob/master/osu.Game/Overlays/Mods/ModSelectOverlay.cs#L346) when changing the speed slider

Until this is explained the investigation is incomplete. Can you explain why this is the case?

I'll look into this myself if not, given that nobody seems to be able to precisely explain why so far.

**Comment by Hy0tic** [comment]
> Until this is explained the investigation is incomplete. Can you explain why this is the case?
>
>I'll look into this myself if not, given that nobody seems to be able to precisely explain why so far.

I tried looking into it but no luck so far, I'll keep looking, let me know if you find out why that's the case.

**Comment by peppy** [comment]
This definitely needs investigation into why it's happening. Looks like bindable feedback going weird (we've seen this a few times in the past, but it's worth understanding again why it's happening and making sure it isn't a framework/bindable level issue).

**Comment by bdach** [comment]
I debugged this today. The failure mode has nothing to do with bindables, and is instead caused by the mod overlay's unfortunately wacky mod reference juggling.

The `SelectedMods.BindValueChanged()` callback in `ModSelectOverlay` can in some instances run recursively. This is most heavily leaned on in scenarios where `SelectedMods` is updated by an external component. In such cases, the mod select overlay needs to replace the mod instances received externally with mod instances which it owns, so that the changes made on the overlay can propagate outwards.

This in particular means that on `master`, it is possible to encounter the following scenario:

```csharp
modSettingChangeTracker?.Dispose();
updateFromExternalSelection(); // mutates SelectedMods to perform the replacement
	                        // therefore causing a recursive call

    modSettingChangeTracker?.Dispose();
    // inner call continues
    modSettingChangeTracker = new ModSettingChangeTracker(val.NewValue);

// outer call continues
modSettingChangeTracker = new ModSettingChangeTracker(val.NewValue);
```

There are two issues there:

- `val.NewValue` is not the same in the outer call as in the inner call. In fact the outer call's `NewValue` is effectively *stale* in comparison to `SelectedMods.Value`. This is the root cause of the bug.
- The above procedure leaks one `modSettingChangeTracker` instance from the inner call, which is never disposed.

To avoid this, we can (a) use `SelectedMods.Value` universally to avoid the desync, (b) move the disposal to the same side of the recursion that the creation happens on, changing the call pattern to:

```csharp
updateFromExternalSelection(); // mutates SelectedMods to perform the replacement
	                             // therefore causing a recursive call

    modSettingChangeTracker?.Dispose();
    // inner call continues
    modSettingChangeTracker = new ModSettingChangeTracker(SelectedMods.Value);

modSettingChangeTracker?.Dispose();
// outer call continues
modSettingChangeTracker = new ModSettingChangeTracker(SelectedMods.Value);
```

which, while slightly wasteful, does not cause any leaks.

The solution is definitely suboptimal, but addressing this properly would entail a major rewrite of the mod instance  management in the mods overlay, which is probably not the wisest move to make right now.

I pushed the fix above into this branch; I don't think much better can be done here, but I will request a re-review to see if anyone has any better ideas.

**Review by bdach — DISMISSED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
