### PR TITLE
Allow customizing link style in a derived class of `LinkFlowContainer`

### PR DESCRIPTION
**Pull request by ekrctb**

### CODE REVIEW

**Comment by bdach** [comment]
Is it really needed to have to derive the "link compiler" as well as the entire link flow to add formatting to a link? I think I'd rather allow formatting at the `LinkFlowContainer` level and skip the boilerplate. It seems like it might end up being a moderately frequent use case.

**Comment by ekrctb** [comment]
At least some modification to `DrawableLinkCompiler` is needed.
When `Colour` of `SpriteText` is modified (e.g. in `creationParameters` of `AddLink`), the colour is overwritten by `DrawableLinkCompiler`'s logic.
The color-changing logic of `DrawableLinkCompiler` is applied to each text because non-`SpriteText` drawable colors shouldn't be changed.

I didn't want to add another parameter to `AddLink` because there are already too many overloads.

I tried to add a property to `LinkFlowContainer` and passing to `DrawableLinkCompiler`. However, it required a more complicated code. The issue is that the colors (including the default color) are obtained via DI, but `AddLink` could be called before the `LinkFlowContainer` is loaded.

**Comment by bdach** [comment]
Well I dunno then. The entirety of `LinkFlowContainer`'s method of adding links is really awkward and inflexible imo and this isn't making it much better (arguably it's making it worse). I was hoping to maybe take a crack at cleaning it up properly from the ground up when bringing localisation support to textflow (the first step of which is yet to be reviewed).

So I'd personally prefer to keep that isolated workaround isolated for now, and address that link stuff later. Unless you need that for something you've got queued?

**Comment by ekrctb** [comment]
> Unless you need that for something you've got queued?

"featured artist" badge in beatmap overlay should be linked <https://github.com/ppy/osu/pull/14675#issuecomment-914906479>, and the text has a custom colour.

**Comment by peppy** [comment]
I'm not too offended by this change. Doesn't seem large/consequential enough to be something we can't refactor in the future?

**Review by smoogipoo — APPROVED** [review]

**Comment by bdach** [comment]
Sure, I guess. Although

> "featured artist" badge in beatmap overlay should be linked

I'd probably do this not via link flow, but by overriding `OnClick()` on the badge and using `OsuGame.HandleLink()` directly. Reasoning is general UX (seems weird to me that only the text of the badge will be clickable and not the entire thing).

**Comment by peppy** [comment]
Yeah, I'm not even sure about that link colouring being different from everywhere else. But I guess the goal here is to match osu-web initially..

**Pull request merged**
