### PR TITLE
Fix preview track persisting to play after entering multi/playlists gameplay

### LINKED ISSUE #28795: Preview on playlist persists playing
### Type

Game behaviour

### Bug description

Very minor issue. Inside the playlist multiplayer mode, preview a song and then immediately starting the song will have the preview play in-game until the preview is over.

### Screenshots or videos

image
image

Then the preview of the song keeps playing in-game until the preview of the song is over.

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16145728/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by Joehuu**
- Fixes https://github.com/ppy/osu/issues/28795

### CODE REVIEW

**Comment by smoogipoo** [comment]
Any reason to not do this in `PlayerLoader` or `Player`?

**Comment by peppy** [comment]
> Any reason to not do this in `PlayerLoader` or `Player`?

The place it is here makes sense because it applies in both exit / suspend directions. I guess we could also add a call in player in addition though?

**Review by peppy — APPROVED** [review]

**Comment by Joehuu** [comment]
> Any reason to not do this in `PlayerLoader` or `Player`?

Because `StopAnyPlaying()` needs a `IPreviewTrackOwner` and `RoomSubScreen` is already one. Would need to add `[Resolved] IPreviewTrackOwner` if done elsewhere. And I only see `StopAnyPlaying(this)` outside of tests.

**Comment by smoogipoo** [comment]
That's a given, yes. But the point brought up by @peppy above stands.

**Pull request merged**
