### PR TITLE
Fix key count being incorrectly adjusted by hard/easy mods

### LINKED ISSUE #7610: Easy mod for osu!mania halves key amount stat
**Describe the bug:** 
If you use the Easy modifier in osu!mania mode, it seems to halve all stats - including key count (which it should not). This doesn't affect gameplay, just the key count number under the beatmap details.

**Screenshots or videos showing encountered issue:** 
With the Easy modifier enabled:
Easy mod enabled
Without the Easy modifier enabled:
Without easy mod

**osu!lazer version:** 
2020.118.0
(self-compiled on Ubuntu 19.10)

**Logs:** 
...

### PR DESCRIPTION
**Pull request by peppy**
- Alternative to and closes https://github.com/ppy/osu/pull/7625.
- Closes https://github.com/ppy/osu/issues/7610.

### CODE REVIEW

**Comment by smoogipoo** [comment]
You'll still need to modify the mods to not affect the CS.

**Comment by peppy** [comment]
How come?

**Comment by smoogipoo** [comment]
Because the issue is that it changes the number of keys:

https://github.com/ppy/osu/blob/99d53982621739402831d94fc1b300a63eb571a6/osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs#L48

**Comment by smoogipoo** [comment]
Turns out this isn't actually the case...

https://github.com/ppy/osu/blob/99d53982621739402831d94fc1b300a63eb571a6/osu.Game/Rulesets/Mods/IApplicableToDifficulty.cs#L21

Veeeeeery sketchy though.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
