### PR TITLE
Click to resume (osu!standard)

### PR DESCRIPTION
**Pull request by UselessToucan**
Opening this PR because I need some help.
It [works at some degree](https://youtu.be/TVJd7MhVA0o), but there are at least 2 major problems which I'm not sure how to solve.

1. The appearance should be osu!standard styled. For example, in osu!stable we have an orange cursor. This may be solved by reusing [this OsuCursor](https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Osu/UI/Cursor/GameplayCursor.cs), but osu.Game project does not reference osu.Game.Rulesets.Osu project ("Sorry, toucan. No OsuCursor for you.").
2. Input handling. It should handle whatever you use to click circles, not just left mouse click. This may be solved by using [OsuAction](https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Osu/OsuInputManager.cs), but it is located in osu.Game.Rulesets.Osu too. ("Sorry, toucan. No OsuAction for you")

### CODE REVIEW

**Comment by UselessToucan** [comment]
It works ok in osu!standard. Now I need to get rid of some hardcoding and perform general code cleanup.
I write this comment in order to notify that this PR is not ready for code review yet, but I have some progress.

**Comment by UselessToucan** [comment]
@smoogipoo @peppy I would like to receive some feedback on the existing code. Please review it whenever you will be free.

**Comment by peppy** [comment]
highlighting for review is not going to speed up when the PR gets reviewed. please understand our resources are limited and there are other PRs waiting (and we are also working on our own changes).

This is a relatively low priority change. We have both looked over this PR but it requires some *very* serious attention to get on the right track. It also requires discussion before implementation of how things should be implemented.

**Comment by UselessToucan** [comment]
I resolved merge conflicts just in case. Recent clock related changes broke resuming gameplay from the `ResumeOverlay`(mods without cursor like Taiko are still ok).

**Comment by peppy** [comment]
This requires conflict resolution and the code is not anywhere near a mergeable state. Dropping out of milestones.

**Pull request closed without merging**
