### PR TITLE
Fix old looping samples not stopping when replacing a `SkinnableSound`'s `Samples`

### LINKED ISSUE #30365: Hitsounds loop after being removed from hold notes and then pausing in Mania Editor
### Type

Cosmetic

### Bug description

Sounds stop after leaving the editor

### Screenshots or videos

https://github.com/user-attachments/assets/96e36ecf-274f-4060-ab1a-b1b6ebd29ecd

### Version

2024.1009.1-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/17451634/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by bdach**
Closes https://github.com/ppy/osu/issues/30365.

### CODE REVIEW

**Comment by smoogipoo** [comment]
I'm having deje-vu.

Is this where we want it? What about `PoolableSkinnableSample` itself which has very similar code? Maybe it should be in both locations...

**Comment by peppy** [comment]
> What about PoolableSkinnableSample itself which has very similar code? Maybe it should be in both locations...

There's a theory that this is handled via disposal (triggered by https://github.com/ppy/osu/blob/e6f1ec57a963cf4bdc16d8c186227dd18230d6d9/osu.Game/Skinning/PoolableSkinnableSample.cs#L91)

It's a theory though.

**Review by peppy — APPROVED** [review]
If this breaks something, we're going to find out from a user. Looks fine to my eye.

**Comment by MeerukYang** [comment]
Does this also fix #30003 ?

**Pull request merged**
