### PR TITLE
Remove now unnecessary binding logic from `HUDOverlay`

### PR DESCRIPTION
**Pull request by peppy**
- [x] Depends on https://github.com/ppy/osu/pull/12670
- [x] Depends on https://github.com/ppy/osu/pull/12705
- [x] Depends on https://github.com/ppy/osu/pull/12706
- [x] Depends on https://github.com/ppy/osu/pull/12707

### CODE REVIEW

**Review by frenzibyte — CHANGES_REQUESTED** [review]
The `HitErrorDisplay` has regressed due to attempting to use a resolved dependency in constructor.

https://github.com/ppy/osu/blob/1cb10c2a2243bde4f0fcc85a5d6de338a34f28bd/osu.Game/Screens/Play/HUD/HitErrorDisplay.cs#L34-L35

should move that to BDL/LoadComplete.

---

Otherwise things look cleaned up now.

**Review by smoogipoo — DISMISSED** [review]

**Comment by frenzibyte** [comment]
@smoogipoo if you haven't noticed yet, https://github.com/ppy/osu/pull/12708#pullrequestreview-654961977 is still not resolved.

**Comment by smoogipoo** [comment]
Ah, I didn't see. Scary that this passes tests.

**Comment by peppy** [comment]
@smoogipoo are you looking at this already or shall i grab it?

**Comment by smoogipoo** [comment]
I'm not currently looking into it.

**Comment by smoogipoo** [comment]
Did you figure out why this wasn't failing any tests? I can't immediately see how your testscene changes show the issue.

**Review by smoogipoo — APPROVED** [review]

**Comment by frenzibyte** [comment]
The `ScoreProcessor` binding was at `HitErrorDisplay` which binds new judgements to `HitErrorMeter.OnNewJudgement`, while the tests were adding all these meters and invoking the method manually, rather than attaching a test score processor.

**Comment by peppy** [comment]
There was a null check in the constructor allowing an empty score processor. This no longer exists (and the resolution is explicitly non-null).

**Comment by smoogipoo** [comment]
> null check in the constructor

Aha, skipped over that.

**Review by frenzibyte — APPROVED** [review]

**Pull request merged**
