### PR TITLE
Refresh setup screen appearance to be closer to design

### PR DESCRIPTION
**Pull request by bdach**
| current `master` | this PR |
| :-: | :-: |
| osu_2021-04-03_20-55-58 | osu_2021-04-03_20-54-41 |

Mostly follows designs as attached in #2434.

Figured I'd start with this to get a decent baseline going and be able to proceed with user control changes that also follow the designs.

This won't be great reviewing, but the diff isn't monstrous. I tried to split commits in the most sane way I could imagine. Ended off splitting out a few components along the way, too.

The designs somewhat suggest that the tabs should be tabs (as in, the content should be swapped out), but given there was a scroll container already in there, I assumed it was supposed to be somewhat similar to the user profile overlay and scroll, so I followed that for now.

Not super sure about the stickyness of the background chooser. It follows the designs, but also might be a bit style over substance. If you think so, I can revert 294d911 to get to the previous state of affairs (it'll scroll off when going to a different section).

As an aside, the overlay stuff isn't very well written for extensibility. There's a lot of virtual constructor calls, which means there is pretty much no way to do dependency inversion from inside one of those `CreateContent()` things. So there might be a few eyebrow raises as to why stuff is done in a roundabout way, but I believe nothing should be *overly* terrible. I would have touched that code but the chain of necessary changes started to go out of control very quickly there, so I let it be.

### CODE REVIEW

**Comment by peppy** [comment]
For the background display, if we're going with the new design the previous version should be displayed as well (ie. show the background twice) where the second is the "selector" control. The header version doesn't look or feel like something that should be interacted with.

**Comment by bdach** [comment]
Hmm, I'd rather revert that design change then, actually. Having two backgrounds shown in the setup screen (along with another copy in the actual background) seems super redundant.

**Comment by bdach** [comment]
I've given [this suggestion from discord](https://discord.com/channels/188630481301012481/188630652340404224/828206634907598899) a go (which is moving the drag & drop logic to the chooser control, and adding a separate background file chooser), and it feels alright to me.

| existing map | blank map | after filling out |
| :-: | :-: | :-: |
| osu_2021-04-04_12-56-32 | osu_2021-04-04_12-56-45 | osu_2021-04-04_12-57-09 |

Diff size is creeping to the larger side now, but I'm not super sure how to split this sanely...

**Comment by bdach** [comment]
I suppose this should be put on hold until the design is updated.

**Comment by peppy** [comment]
@bdach seems like we can probably get this in as-is as it looks like a step in the right direction. did you have plans to make more changes on this PR or think we can merge as a stand-alone improvement pending further design updates?

**Comment by bdach** [comment]
No, I have no more pending changes for now. I blocked this only because it turned out that the design will be getting updated and I wasn't sure whether this was going to be wasted effort.

**Review by peppy — APPROVED** [review]
No real issues here, definitely feels nicer!

**Pull request merged**
