### PR TITLE
Add option to increase visibility of first object with grow mod

### PR DESCRIPTION
**Pull request by GSculerlor**
Since it's hide the approach circle like hidden mod, it make sense to add option like hidden mod to keep the approach circle visible on first object.

Demo: https://youtu.be/ab9TRcr3w7k

- [x] Depends on #4970.

### CODE REVIEW

**Comment by Aergwyn** [comment]
Why doesn't this just use the same, already existing, setting?

**Comment by GSculerlor** [comment]
@Aergwyn I thought it should be separated option since the existing option's label is intended to applied to hidden only

**Comment by peppy** [comment]
Rename the existing setting to cover all cases "Increase visibility of first object when visual impairment mods are enabled" or something.

**Comment by peppy** [comment]
Please make sure to test your changes in the future, before pushing

image

**Comment by GSculerlor** [comment]
Oops just realize it. Still figuring the simple one for the label

**Comment by peppy** [comment]
Fixed via #4970.

**Review by miterosan — APPROVED** [review]

**Review by smoogipoo — APPROVED** [review]
lgtm 👍

**Pull request merged**
