### PR TITLE
Avoid throwing / logging an error when `drawings.txt` is missing

### PR DESCRIPTION
**Pull request by peppy**
The exception was already caught, but the error is misleading when the user doesn't even have a `drawings.txt` in their tournament folder.

### CODE REVIEW

**Comment by bdach** [comment]
The old error did not make sense, sure, but I'm not super sure about just silently doing nothing instead. I guess it was a "you have to know how it works" sort of screen anyways, but still, at least *some* feedback seems a better idea than nothing...?

**Comment by peppy** [comment]
Should be done as a  UI warning message as it is on other screens. Probably with a link to a wiki page explaining the format (since I don't even know how it works).

The point is that the error would display in logs even when not using the drawings screen. I'm not sure if any other tournaments use it apart from the world cup, so in most cases it's not a relevant error.

**Review by bdach — DISMISSED** [review]
fair enough

**Comment by peppy** [comment]
I'm fine for this PR to stay open until the warning is added in the UI, for what it's worth. I'll get to that today if no one beats me.

**Comment by peppy** [comment]
I've added some messaging for this. The design is nothing special but I don't think it matters for something like this.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
