### PR TITLE
Converted all line endings to CRLF.

### PR DESCRIPTION
**Pull request by ZLima12**
I have converted all line endings for both osu and osu-framework to CRLF as requested on the osu issues page.

### CODE REVIEW

**Comment by Shredder121** [comment]
There are still quite a lot of files that haven't been normalized though.
Just so you know.

**Comment by ZLima12** [comment]
@Shredder121 Could you provide some examples? Considering that it was stated that the files were "in bad shape", perhaps there were many files that were already in CRLF.

**Comment by peppy** [comment]
they may be referring to osu-framework files. might as well merge these fixes in as they look good, though.

**Comment by peppy** [comment]
one note is that i probably wouldn't apply this to .gitmodules (i'm not sure all git clients will handle CRLF correctly).

**Comment by ZLima12** [comment]
Will do, although on second look it seems that I'm going to have to re-do it, because there are some files that didn't get converted for some reason. I am also doing osu-framework.

**Comment by Shredder121** [comment]
> @Shredder121 Could you provide some examples?

I think you've got them now.
Sorry for interrupting.

**Comment by ZLima12** [comment]
I'll create a new pull request with all files converted.

**Pull request closed without merging**
