### PR TITLE
Change osu!catch juice stream tick generation to match osu!(stable)

### LINKED ISSUE #20508: osu!catch Juice Stream incorrectly generated
### Type

Game behaviour

### Bug description

While writing code on another project; I stumbled onto an issue regarding osu!lazer vs osu! stable's working mechanisms; the issue being how a Juice Stream (maybe also Slider because of the Timing Point) is implemented. A lot of the time it seems that osu!lazer and osu! stable works but then there are times in which it breaks since the Juice Stream on osu!lazer is generating more nested objects than in osu! stable as demonstrated in the YouTube videos in the `Screenshots or videos` section.

I believe the code linked below may have allowed for this bug to happen; or either the variable of `sinceLastTick` or `timeBetweenTiny`.

https://github.com/ppy/osu/blob/8642ed76313c128e2ad698cb5a8509a869d3d67f/osu.Game.Rulesets.Catch/Objects/JuiceStream.cs#L81

The beatmap source code (while shortened) is enough for the beatmap to reproduce the bug in both stable and lazer and is located in the `Screenshots or videos` section as well.

Not sure if this does, but I believe this issue somewhat links to https://github.com/ppy/osu/issues/6184

### Screenshots or videos

[osu!catch on stable with 1 Tiny Droplet](https://www.youtube.com/watch?v=7m9pmFg0VdA)
[osu!catch on lazer with 3 Tiny Droplet](https://www.youtube.com/watch?v=A-0oAIeAGd0)

Beatmap:
osu file format v14

[General]
Mode: 2

[Difficulty]
SliderMultiplier:3
SliderTickRate:1

[TimingPoints]
15,937.5,4,2,1,50,1,0
15,-33.3333333333333,4,2,1,50,0,0

[HitObjects]
256,384,15,6,0,L|256:0,1,227

### Version

`Local Debug` and `osu! 2022.923.1-lazer`

### Logs

This seems to be more of an implementation issue than it is a user issue.

### PR DESCRIPTION
**Pull request by peppy**
Closes #20508.

I can add a test if it's deemed worthwhile. I don't know if it is for cases like this which are solved once and will basically never regress.

### CODE REVIEW

**Comment by smoogipoo** [comment]
A few pretty large changes here, should ensure that they are closer to osu-stable's values:

https://docs.google.com/spreadsheets/d/11SWRCr40D4fupulkzQkJXrXwcUc1pbsV2cu_Jwq1OCM/edit?usp=sharing

```sql
SELECT
    c.beatmap_id AS 'beatmap_id',
    c.filename AS 'beatmap',
    c.playmode != 2 AS 'is_convert',
    a.value AS 'old_tick_count',
    b.value AS 'new_tick_count'
FROM osu.osu_beatmap_difficulty_attribs a
JOIN osu_new.osu_beatmap_difficulty_attribs b
    ON b.beatmap_id = a.beatmap_id
    AND b.mods = a.mods
    AND b.mode = a.mode
    AND b.attrib_id = a.attrib_id
JOIN osu.osu_beatmaps c
    ON c.beatmap_id = a.beatmap_id
WHERE a.attrib_id = 23
    AND a.mods = 0
    AND a.value != b.value
ORDER BY ABS(a.value - b.value)
    DESC;
```

**Comment by peppy** [comment]
Just to confirm, this would require manually checking in stable that the `new_tick_count` matches?

**Comment by peppy** [comment]
On a quick check there's definitely some regressions in here.

**Comment by bdach** [comment]
Superseded by https://github.com/ppy/osu/commit/7d602c792da2446375e73d1ed211f3d7f62f432f.

More detailed explanation in https://github.com/ppy/osu/issues/20508#issuecomment-1853909745.

**Pull request closed without merging**
