### PR TITLE
Allow closing the Mod customize header by click only when it was opened by click.

### PR DESCRIPTION
**Pull request by cdwcgt**
related https://github.com/ppy/osu/discussions/29457

https://github.com/user-attachments/assets/55f258c0-353c-4400-abe1-d7432dbc4d88

I haven't tested the touch screen environment, I hope there is no problem

### CODE REVIEW

**Comment by Cai1Hsu** [comment]
i've actually proposed this with a patch attached in #29136 but peppy didn't adopted it

**Comment by bdach** [comment]
I initially ignored this because it was after @peppy's pass so I wasn't going to question anything UX but now that this is open I will.

I find the click interaction on that dropdown generally strange. You can't actually *click* the dropdown open the first time, it'll always hover-open. Then you can click it to *close* it, and only then click it to open it.

I dunno. I suppose this does what it says but I'm not super sure I'd even keep being able to click the dropdown in.

**Comment by shiumano** [comment]
> I haven't tested the touch screen environment, I hope there is no problem

In the meantime, there seems to be no problem with this.

**Comment by peppy** [comment]
> I dunno. I suppose this does what it says but I'm not super sure I'd even keep being able to click the dropdown in.

Tend to agree. Removing click-ability would work fine, as long as mobile is adequately considered.

**Comment by cdwcgt** [comment]
> Removing click-ability would work fine, as long as mobile is adequately considered.

This basically means that if the touch (mouse) leaves the panel, the panel will automatically close, which will be a poor experience for adjusting the slider.
Because the cursor can easily leave the panel when adjusting the slider
and also need consider the mod's require configuration property (difficulty adjust)

**Comment by bdach** [comment]
> This basically means that if the touch (mouse) leaves the panel, the panel will automatically close, which will be a poor experience for adjusting the slider.

Well no it shouldn't. That is what "mobile [being] adequately considered" is _supposed to mean_.

**Comment by Joehuu** [comment]
Judging by the above comments, this is superseded by https://github.com/ppy/osu/pull/29626 because it removes the click-ability.

**Pull request closed without merging**
