### PR TITLE
Add ability to "fling" notifications to dismiss them

### PR DESCRIPTION
**Pull request by peppy**
Fling to left will dismiss, to right will store to overlay (will come later).

https://user-images.githubusercontent.com/191335/189532613-868a12ed-308a-440b-833f-d7389c8460ec.mp4

- [x] Depends on #20215

### CODE REVIEW

**Comment by toadsworth-jr** [comment]
Concerning about sound design, would the flinging sounds use the Overlay close sound (or any other appropriate sound) or will it be made from scratch?

**Comment by smoogipoo** [comment]
Based solely on the video, I found it weird that the notification light stays in the original location. Is that intended, or not an easy fix to make?

**Comment by peppy** [comment]
I intend on removing the notification light for toasts. It's only really useful in the notification overlay (as it is a "read" light).

I can do that in this PR if you would prefer.

**Comment by peppy** [comment]
I've gone ahead and hidden the light. Let me know how that works for you.

**Comment by smoogipoo** [comment]
After it's flung, it should not be able to be re-flung:

https://user-images.githubusercontent.com/1329837/189594490-c9d3b634-ef51-48b7-9fb1-f9d1d81ce2a7.mp4

Infact it probably shouldn't be interactable at all at that point.

**Comment by peppy** [comment]
I've fixed that issue.

One thing I noticed which I'm not sure about is that progress notifications trigger the fling animation (because they call `Close` internally to display the `CompletionNotification`). Not sure about this one, looks kinda cool but might be distracting in practice?

https://user-images.githubusercontent.com/191335/189596516-a988e6b7-055d-4cae-be8f-a906b69325a4.mp4

**Comment by smoogipoo** [comment]
I think that's going to be distracting. Should only happen on fling imo.

**Comment by smoogipoo** [comment]
Is it intended that clicking notifications causes them to flick? Also, clicking on notifications doesn't dismiss the counter (this doesn't happen on master).

**Comment by peppy** [comment]
Left click shouldn't fling, I guess that case is a "non-user close" for animation purposes.

I also noticed the count incrementing but thought that already had test coverage and I was doing something weird. Will check on that.

**Review by smoogipoo — APPROVED** [review]

**Comment by SrIzan10** [comment]
what about flinging also to the right?

**Comment by peppy** [comment]
> what about flinging also to the right?

Please read.

**Pull request merged**
