### PR TITLE
Improve visual appearance of mania selection blueprints

### PR DESCRIPTION
**Pull request by bdach**
Been bothering me for a long while now.

This isn't by all means supposed to be the end product, it's 80% of the target result in my mind in 20% of the time. Placement blueprints are all unchanged because attempting to access anything skinnable in the placement blueprint, before there is a DHO placed in an actual column, is hell. So I'm leaving that for later.

| before | after |
| :-: | :-: |
| osu_2024-11-05_15-30-51 | osu_2024-11-05_15-33-02 |
| osu_2024-11-05_15-30-59 | osu_2024-11-05_15-33-09 |
| osu_2024-11-05_15-31-07 | osu_2024-11-05_15-33-16 |
| osu_2024-11-05_15-31-15 | osu_2024-11-05_15-33-24 |
| osu_2024-11-05_15-31-25 | osu_2024-11-05_15-33-32 |
| osu_2024-11-05_15-32-11 | osu_2024-11-05_15-33-55 |

### CODE REVIEW

**Comment by peppy** [comment]
Hmm, just going by screenshots, the case of the DDR skin gets a bit dicey because you can no longer easily see which tick the object is on. Also I think some of the blueprint lines are too thick with the new styling.

**Comment by bdach** [comment]
> the case of the DDR skin gets a bit dicey because you can no longer easily see which tick the object is on

Looking at a few screenshots of other games that use DDR style sprites, the editors seem to either [anchor notes to centre](https://tillvit.github.io/smeditor/assets/mode-cac62e2a.png) or [use a grid style instead](https://i.ytimg.com/vi/n87hEUGEvbU/maxresdefault.jpg). That is not something I can easily implement. Maybe I shouldn't just bother with trying to display circles on DDR style skins and just use boxes everywhere?

> Also I think some of the blueprint lines are too thick with the new styling

The thickness was chosen such that the selection markers on classic and triangles skins are completely filled. If you're fine with gaps showing on the inside on both, I can reduce it.

**Comment by smoogipoo** [comment]
> just use boxes everywhere

Would agree with this.

**Comment by peppy** [comment]
Just using boxes seems like a good starting point yeah.

**Comment by bdach** [comment]
I've made some changes based on above feedback. Thoughts on these?

osu_2024-11-07_09-17-35
osu_2024-11-07_09-17-49
osu_2024-11-07_09-18-00
osu_2024-11-07_09-18-13
osu_2024-11-07_09-18-25
osu_2024-11-07_09-18-40

**Comment by peppy** [comment]
I was going to suggest a gradient but it maybe doesn't look that amazing. Perhaps a solid line for the bottom part of the rectangle and a different colour or less-opaque line for the remaining three sides would feel better..

**Comment by bdach** [comment]
Something like these, then?

osu_2024-11-07_13-38-54
osu_2024-11-07_13-39-06
osu_2024-11-07_13-39-15
osu_2024-11-07_13-39-26
osu_2024-11-07_13-39-35
osu_2024-11-07_13-39-47

**Comment by bdach** [comment]
I've applied the patch verbatim.

> stable just feels better using tinting rather than this blueprint crap. Maybe we just tint again?

For selection blueprints we probably could. Placement is another beast entirely, it may take me a good two or ten days to figure out how on earth to fish out a correctly looking skinnable to put in the placement blueprint from all of the column configuration sprawl.

**Comment by peppy** [comment]
One remaining issue if we go forward with this change is that placement notes look incorrect now (while placement holds are okay seemingly):

2024-11-13 03 30 29@2x

**Comment by bdach** [comment]
Have adjusted further:

https://github.com/user-attachments/assets/b689032a-7aff-44df-809e-bc471214ed48

Also fixed the selection blueprint being broken on upscroll in https://github.com/ppy/osu/pull/30512/commits/0c4c9bd2376df86af8168658f44f4412810f5cdd.

**Review by peppy — APPROVED** [review]

**Pull request merged**
