### PR TITLE
Show mods on player loading screen

### PR DESCRIPTION
**Pull request by LeNitrous**
Adds `ModDisplay` to `PlayerLoader`  where it displays selected mods during loading. There are frequent cases where we can forget what mods were last selected.

Example:
image

### CODE REVIEW

**Comment by Joehuu** [comment]
Did you see https://github.com/ppy/osu/issues/3143#issuecomment-409103624. Probably implement this or both.

**Comment by smoogipoo** [comment]
It's weird that the build passed CI, there's a few messages for you to fix: https://ci.appveyor.com/project/peppy/osu/builds/21905592/messages

**Comment by arflyte** [comment]
Yeah, the mods are supposed to be shown at the start screen.

**Comment by LeNitrous** [comment]
The more practical way is to deal with the footer buttons.

**Comment by peppy** [comment]
I'm pretty sure this is still required, as per flyte's comment.

**Comment by LeNitrous** [comment]
Seems I confused "at the start screen" with song select. Pardon that close.

**Comment by LeNitrous** [comment]
I decided to add the mod display on the loader instead and let flyte's design be a separate issue instead.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
