### PR TITLE
Fix realm migration potentially failing for users that haven't run osu! in a long time

### PR DESCRIPTION
**Pull request by peppy**
As reported at https://github.com/ppy/osu/discussions/15530.

We need better safeties around failed migration applications (probably backup and start with a fresh database at least) but I plan on looking at that separately in the future. Along with probably storing separate development realms per schema version to better handle reviewing changes which bring the realm to a newer schema version.

### CODE REVIEW

**Comment by bdach** [comment]
There's a code style inspection here (inner local variable in method shadowing same variable in outer scope) that I'm not super sure how to fix best.

**Comment by peppy** [comment]
That's a weird one since it never shows locally for me.

**Comment by bdach** [comment]
Same here, I don't see that inspection locally, either. Maybe some old inspectcode bug that we can't solve by bumping since new inspectcode is broken too.....

**Review by bdach — APPROVED** [review]
Tested, looks to be working

**Pull request merged**
