### PR TITLE
Simplify convertible hitobject parsing and add `IHasLegacyHitObjectType`

### PR DESCRIPTION
**Pull request by smoogipoo**
The main task I wanted to solve here is to add `IHasLegacyHitObjectType` so that I can update the databased `osu_beatmap` counts from `osu-difficulty-calculator` (https://github.com/ppy/osu-difficulty-calculator/pull/233).

In the process, I thought I'd refactor this whole thing and remove the duplicate `ConvertX` hitobject types.

### CODE REVIEW

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=taiko

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=catch

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=mania

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=osu
DIFFICULTY_CALCULATOR_B=https://github.com/ppy/osu-difficulty-calculator/pull/233

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=taiko
DIFFICULTY_CALCULATOR_B=https://github.com/ppy/osu-difficulty-calculator/pull/233

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=catch
DIFFICULTY_CALCULATOR_B=https://github.com/ppy/osu-difficulty-calculator/pull/233

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=mania
DIFFICULTY_CALCULATOR_B=https://github.com/ppy/osu-difficulty-calculator/pull/233

**Comment by bdach** [comment]
Test compile failures here

**Review by bdach — COMMENTED** [review]
Source looks correct to me, but will wait for the diffcalc runs

**Comment by smoogipoo** [comment]
Not sure what happened with the first set of runs that have had spreadsheets deleted 🤔

> https://docs.google.com/spreadsheets/d/19cKPfM38bHiwU06_4QKLv8ALi21baEF7WiakK9IXiP0/edit

The change here is intended, and is likely so small scale due to the hotfix https://github.com/ppy/osu/pull/30544

Regardless, I'm pretty confident in this one now. Can rerun the previous sheets if you feel necessary.

**Review by peppy — APPROVED** [review]
Amazing improvement 💯

**Pull request merged**
