### PR TITLE
Always add to additions soundbank in `convertSoundType`

### PR DESCRIPTION
**Pull request by sw1tchbl4d3r**
The current behavior breaks some taiko maps using the hitsample filename, like [on this map](https://osu.ppy.sh/beatmapsets/1314747#taiko/2724781) at 00:45:961.
The note is a normal don/red note in lazer, while it should be a strong one like in stable.

This patch adds the additional info needed to identify a note as a finisher/strong note to the soundbank regardless of whether a hitsample filename was specified or not, to keep crucial (at least in taiko) note information.

### CODE REVIEW

**Comment by bdach** [comment]
Judging from your description this seems to be affecting beatmap conversion (notably, the fact that one note isn't strong anymore in lazer but should be), so please add a test case for this to the [beatmap conversion test](https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Taiko.Tests/TaikoBeatmapConversionTest.cs).

A guide to extract the conversion mappings from stable can be found [here](https://github.com/ppy/osu/wiki/Generating-osu!stable-conversion-mappings).

**Comment by sw1tchbl4d3r** [comment]
As seen here:
https://github.com/ppy/osu/blob/f0d11f44fc8191d6231056b1a5636757e8d0aef6/osu.Game/Rulesets/Objects/Legacy/ConvertHitObjectParser.cs#L453
though, if the plan is to make this check return a normal hitsample if the audio file isn't found, it feels like this test would break in the future if we use a nonexistant name for the audio file, should I not worry about that just yet?

**Comment by bdach** [comment]
I don't follow. Stable converts the linked beatmap in a way wherein a hit ends up being strong. In lazer the note isn't strong. The conversion test would be checking the end result of stable conversion vs lazer conversion which should be the same, so why would fixing that todo break the test? It would be a *good* thing if it broke the test, because it breaks a real end result of conversion, no?

**Comment by sw1tchbl4d3r** [comment]
The point rather is that if I were to implement a test for this, I would have to either
1) supply an audio file, or 
2) use a filename that doesn't exist
for the hitsample, because the new logic is only reached if a filename is supplied.

If we go with the second route, and use a fake filename, because maybe we can't easily add an audio file to the test, and the todo were to be fixed, we wouldn't enter the new logic either, so the test becomes useless, if that makes sense.
We would no longer be testing the new logic.

**Comment by bdach** [comment]
Okay, that makes more sense.

I'm not sure I would worry about it until it starts failing. I'd maybe leave an inline warning somewhere that the test may fail if the TODO is ever addressed, but it is a pretty edge case. More important for me to have solid coverage of conversion; it's not even entirely clear how the conversion process would get access to other beatmap files at this stage.

**Review by peppy — APPROVED** [review]

**Pull request merged**
