### PR TITLE
Start spectator at the end of gameplay

### PR DESCRIPTION
**Pull request by smoogipoo**
Prereqs:
- [x] https://github.com/ppy/osu/pull/13657

There's a few changes bundled in here:
1. The test spectator client no longer accepts an index for `SendFrames()`, it's all done internally. This just cleans up the spectator test scenes a bit.
2. `SpectatorPlayer` clears frames (which may have arrived from previous player instances in `SoloSpectator`), and seeks to the start of the next frame arrival as previously.
3. `MultiSpectatorScreen` now also seeks the master clock in a similar way, when players are ready to start. This is required on top of seeking each `SpectatorPlayer`, however I want to tie the interaction between players and the master clock a little more as a future task, specifically around seeking.
4. The `CatchUpSyncManager` no longer starts/stops the master clock. This was a conscious decision because a) it doesn't work well with seeking to the start of gameplay, and b) the sync manager shouldn't be altering the master clock in my opinion. Its single purpose should be to keep the contained player clocks in-sync as its xmldoc describes.

Preview: https://drive.google.com/file/d/1lpytl42MfM-6NnyrbgA_TLlKo_FWYMVX/view?usp=sharing

### CODE REVIEW

**Comment by smoogipoo** [comment]
Not sure what the test failures are all about - I can't repro locally. And even `TestMostInSyncUserIsAudioSource` which fails a lot on master doesn't fail on this branch anymore.

Needs more investigation.

**Comment by peppy** [comment]
@smoogipoo this is the one you're still actively investigating right?

**Comment by smoogipoo** [comment]
Currently investigating, yes.

**Comment by smoogipoo** [comment]
I've made the tests a lot more resilient, and put a prereq on #13657. There do still seem to be some failures, but they seem infrequent.
There's a deeper underlying problem with Player somewhere that I can't pinpoint yet.

**Review by peppy — APPROVED** [review]
Looks sane

**Pull request merged**
