### PR TITLE
Refactor Auto

### PR DESCRIPTION
**Pull request by thomastanck**
- Some trivial refactors

Rename targetPosition to startPosition, move frameDelay and
reactionTime to private readonly fields, and added 2 comments

- Split main loop into 2 functions.

One is the function to add a delay from the previous hit object if the
current one hasn't appeared yet for auto to "see and react to"

The other function does everything else.

- Rename and comment stuff in spinner startPosition alg.

- Move movement to start of hitobject logic out

- Rename the functions I took out

- Move spinner start pos calc out.

- Move clicking object logic out

- Fix formatting

### CODE REVIEW

**Comment by thomastanck** [comment]
@Tom94 I'd like to rewrite the auto play algorithm, actually.

My idea is to do several passes over the hitobjects. On the first pass, I identify all the circles, slider heads, slider ticks, and slider ends, and sort them by time. I also determine which of those are set during a spinner (for the really hacky 2B maps). I first try to click all the clickables (the necessary) and on each pass I progressively add more frames to less important things (spinning, following slider bodies, and finally snapping). On the very last pass, I add ButtonState to make auto actually click.

----

For objects that aren't played during a spinner:

I first try to move to all the circles, sliderheads, ensure that the cursor is in range of the slider ticks and slider ends.

After that, I fill in the sliders by following the latest slider whenever possible. I leave a time gap before any circles or sliderheads so auto has time to "snap" to them in case of 2B.

Finally I fill in the time before circles and slider heads with "snaps".

----

For objects that are played during a spinner:

I first try to move to all the circles, sliderheads, ensure that the cursor is in range of the slider ticks and slider ends. (same as before)

Now, I fill in the spinning motion, ignoring slider bodies. Again, I leave a time gap before any circles or sliderheads so auto has time to "snap" to them.

Finally I fill in the time before circles and slider heads with "snaps". Note that as objects during spinners are already definitely 2B, these snaps will all be at maximum speed (or minimum time gap).

----

After all the movement has been established, I finally set the ButtonState of all the frames accordingly to make auto tap/alternate all the objects. By doing this right at the end, it should make the code much less hackish (see L302 to 323 of this commit for the current hack).

----

This *should* make the game play 2B better. I also feel like this structure is more intuitive than the current one.

I'll probably encounter some problems with the details, but if you think this is a sane method, give me the go-ahead ^^

**Comment by peppy** [comment]
I'd say go ahead and give it a try.

I want to support multiple autoplay algorithms in the future, for what it's worth (user selectable). I think people can come up with some fun ones on top of the defaults.

**Comment by thomastanck** [comment]
Fixed a couple of stray comments.

**Comment by peppy** [comment]
Looks solid enough to merge. Still not a huge fan of the `...Base` class naming, but don't have a better alternative.

**Review by peppy — APPROVED** [review]

**Pull request merged**
