### PR TITLE
Try to match stable's cursor trail density

### PR DESCRIPTION
**Pull request by LittleEndu**
This addresses the issue in #6115 but does not close it (as this PR doesn't add the ability to adjust the density, it just makes it more in match with stable)

Quoting my comment from that issue:
> I think the issue here is that on stable, density of the trail polygons stays the same no matter what cursor size you use. So if you move your 1.0x cursor size cursor when your trail is a 8x8 file it will get a new polygon every 4px for an overlap of 4px, but if you move your 2.0x cursor size cursor keeping the same trail file dimensions, you will still get a new polygon every 4px but now you overlap 12px.

~~If something like this could be considered I can record comparison videos. Going to open the PR as a draft because this.~~

Comparison video here: https://youtu.be/iHeu8hPEYAY
This PR is top-left, current release is top-right, stable is bottom. 

Rendered another video with chroma key: https://youtu.be/CR88gzm0I7A
stable is left, this PR is middle, current release is right (and unkeyed, it looks bad with video compressions, but it also looks bad in-game, that's why I want this change)

### CODE REVIEW

**Comment by peppy** [comment]
Should you not be making this change in `LegacyCursorTrail`?

**Comment by bdach** [comment]
Please unmark as draft whenever you deem the code is ready. I will abstain from reviewing until then.

**Comment by LittleEndu** [comment]
I just wanted to know if this (changing the density of the trail to *almost* match what stable does by making it denser on higher cursor size) is something that we want to do, before marking it ready. Now that the implementation is only in legacy cursor trail, I don't see why not try to support something stable did anyway. I'll record comparison vid then mark it as ready.

**Comment by bdach** [comment]
I don't really know how to read the comparison videos, given that the trail on it is... continuous. A comparison of a non-continuous trail on stable with how it looks on lazer would actually give a frame of reference as to how the two compare.

**Comment by LittleEndu** [comment]
> I don't really know how to read the comparison videos, given that the trail on it is... continuous. A comparison of a non-continuous trail on stable with how it looks on lazer would actually give a frame of reference as to how the two compare.

The non-continuous trail isn't changed. That trail gets new sprites based on time (so the faster you move your cursor, the sparser it would be). I don't think cursor size or the dimensions of the cursortrail.png change the density of the non-continuous trail.

The comparison videos were meant to show that current release will leave bigger trails (that's trails with higher dimensions, mine is 24x24) more blocky looking which is the entire reason people increase their cursor size on stable to get more sprites per distance. Denser trails look more fluid.

**Review by smoogipoo — APPROVED** [review]
Seems to behave fine

**Pull request merged**
