### PR TITLE
Add ability to bind "back" action; add default mouse binding

### LINKED ISSUE #2410: Hardware back button not implemented
It works in osu!stable, but not in laser.

<bountysource-plugin>

---
Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/57166458-hardware-back-button-not-implemented?utm_campaign=plugin&utm_content=tracker%2F4707269&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F4707269&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by UselessToucan**
resolves #2410

### CODE REVIEW

**Comment by peppy** [comment]
Did you test this one? `MouseButton1` isn't what you think it is.

**Comment by smoogipoo** [comment]
mb1 is correct. 
screen shot 2018-05-02 at 2 38 04 pm

**Comment by UselessToucan** [comment]
@smoogipoo where exactly should the mouse back button be handled? Are there any places besides song select screens and the button system in the main menu?

**Comment by peppy** [comment]
It should probably be at an `OsuScreen` level, with an exposed `protected virtual bool AllowBackButton` for certain screens to disable.

**Comment by smoogipoo** [comment]
1. This has broken escape key handling to exit from player / playerloader.
2. I still don't think we should allow exiting the game via the back button.

Why not have two separate actions instead of grouping them together? One being specifically `Exit` (escape) and the other being `Back`?

**Review by smoogipoo — DISMISSED** [review]
as commented

**Comment by peppy** [comment]
I’m against having two bindable actions as it will be confusing from the user’s perspective (when does exit work, when does back work?)

If anything the action should be called Exit/Back IMO.

**Comment by smoogipoo** [comment]
Don't have a separate "Exit" action, just keep it as escape button?

**Comment by peppy** [comment]
Hmm, that should be fine, although we will need to consider what behaviour escape will have during gameplay then. Having it act (as it does in stable) as "toggle pause" may feel weird.

**Comment by peppy** [comment]
Why is the back action no longer bindable?

**Comment by UselessToucan** [comment]
Looks like I did not understand latest comments correctly(strating from [this](https://github.com/ppy/osu/pull/2472#issuecomment-386925092)).

1) If both esc and mouse button are suitable for the usage scenario, input should be handled using GlobalAction.
2) If only esc is suitable, input should be handled using OnKeyDown override.
Are these statements correct?

**Review by peppy — APPROVED** [review]

**Pull request merged**
