### PR TITLE
Add ability to filter out currently playing rooms

### PR DESCRIPTION
**Pull request by bdach**
- [x] Hard depends on https://github.com/ppy/osu-web/pull/11738
- [x] Probably best to get https://github.com/ppy/osu/pull/30838 in alongside as well

Addresses https://osu.ppy.sh/community/forums/topics/2013293?n=1.

https://github.com/user-attachments/assets/d3f66156-aa91-449c-8abe-2b3a46bad0f0

Contains some renames, so per-commit review may be advisable. See 637fe07b31066087361f7ed305383021f581c647 for rationale.

### CODE REVIEW

**Comment by Joehuu** [comment]
The text "Currently playing" should probably be changed to "Currently listening to" maybe.

We also seem to have a `RoomStatusPlaying` that never worked in `MultiplayerClient` and demonstrated in `TestSceneDrawableRoom` wrongly (i.e. makes no sense in a playlist context, only multiplayer):
Screenshot 2024-12-10 at 8 43 02 PM

**Comment by bdach** [comment]
> The text "Currently playing" should probably be changed to "Currently listening to" maybe.

Doesn't make much sense to me and is borderline out of scope. `"Playing {beatmap} next"` I'd maybe agree with.

**Comment by Joehuu** [comment]
I wanted to get rid of the "playing" term there to avoid confusion, but using "next" in the idle state works for me.

**Comment by peppy** [comment]
Might be good to have this setting remembered in config, similar to the dropdown next to it.

Not sure about the text for the checkbox, I prefer the stable "Show in-progress rooms" I think?

**Review by peppy — COMMENTED** [review]
As commented

**Review by peppy — APPROVED** [review]

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
