### PR TITLE
Use a nearest value to stable's required spins

### PR DESCRIPTION
**Pull request by frenzibyte**
That's the nearest I got, but not accurate.

### CODE REVIEW

**Review by 73794449 — APPROVED** [review]
All Ok. A bit harder, but in normal ranges.

**Comment by iiSaLMaN** [comment]
> All Ok. A bit harder, but in normal ranges.

Yeah I'm not quite sure about this, with my bonus spinning changes, i've realized the required spins are not accurate at all, and it seems a big issue for that change.

**Comment by peppy** [comment]
What is this based on

**Comment by iiSaLMaN** [comment]
> What is this based on

I did comparisons between stable and lazer on the bonus score gained from the spinner and I found that the required spins on lazer are a bit smaller than on stable, so I bumped up the value a bit

**Comment by peppy** [comment]
The comment above the value you changed states this, though.

Did you test against multiple length spinners? If you did, you'll find that it is *impossible* to match stable as there is acceleration involved that makes the scoring non-linear.

**Comment by iiSaLMaN** [comment]
> The comment above the value you changed states this, though.
> 
> Did you test against multiple length spinners? If you did, you'll find that it is _impossible_ to match stable as there is acceleration involved that makes the scoring non-linear.

In that case, would it be fine to adding bonus score even if it differs between stable and lazer?

**Comment by peppy** [comment]
Yes, should be fine.

**Pull request closed without merging**
