### PR TITLE
Fix the beatmap thumbnail overflow in multi-player lobby

### PR DESCRIPTION
**Pull request by normalid-awa**
Some few beatmap that the cover image was not the standard aspect ratio, and the cover image will overflow, this pr fixes the bug by changing the anchor of the image
image

### CODE REVIEW

**Comment by peppy** [comment]
You probably want to set some masking rather than pushing it off to the left (they are no longer centered).

Also I think we want the wider display? So maybe pushing the difficulty icon over is a consideration.

**Comment by normalid-awa** [comment]
> You probably want to set some masking rather than pushing it off to the left (they are no longer centered).
> 
> Also I think we want the wider display? So maybe pushing the difficulty icon over is a consideration.

I've try to set the mask but that will cover the yellow border, and the round corner will appear at four corners instead of a flat side of right, the change would only effect the image that's overflow, for the rest, they still looks like before (I compared with overlapping them together, and it seems only affect the one that overflow)

**Comment by normalid-awa** [comment]
or maybe just make the thumbnail width wider 60 => 100 and call it a day?

**Comment by peppy** [comment]
I want to know how common it is for the aspect ratio of the cover to be different at this point..

**Comment by normalid-awa** [comment]
> I want to know how common it is for the aspect ratio of the cover to be different at this point..

I only found two beatmaps that trigger this bug. Maybe it's just some rare case.

**Comment by peppy** [comment]
Please link the beatmaps. I'd rather check and fix this at the source if it's a generation issue.

**Comment by normalid-awa** [comment]
https://dev.ppy.sh/beatmapsets/1113116#osu/2325387

**Comment by normalid-awa** [comment]
The thumbnail width of the overflow beatmap are larger then others, but I used the osuapi to fetch the original image they are in same width and hight
image
image

**Comment by normalid-awa** [comment]
osu!catch and osu!mania beatmap are also occurring the bug
https://dev.ppy.sh/beatmapsets/1100729#fruits/2299711
https://dev.ppy.sh/beatmapsets/906808#mania/1892453
image

**Comment by peppy** [comment]
This is definitely not the correct approach. You're changing a component used in many places with a fix that will only work when it's left-aligned with the parent element (else you'll get overflow to the left).

I'll PR a better fix for this, alongside fixing some other issues with these panels that makes them an absolute eyesore.

**Comment by peppy** [comment]
@normalid-awa please take a look at https://github.com/ppy/osu/pull/28947!

**Pull request closed without merging**
