### PR TITLE
Add music shortcuts and a small onScreenOverlay feedback

### PR DESCRIPTION
**Pull request by Peaceultime**
I added the osu! music shortcuts feature with a adapted copy of the onScreenDisplay ~~(crap, I thought it was Overlay)~~ to give a little feedback. I am still wondering if it's better to add the onPressed to the MusicControler or to keep it in OsuGame, because it will only work when it's visible.

### CODE REVIEW

**Comment by peppy** [comment]
Did you consider using the `OnScreenDisplay` for this?

**Comment by Peaceultime** [comment]
I could but I'm bad in C# so I prefer create a new class for this. Also, I don't think it is really useful to create a new ITrackableConfigManager as MusicNotificationDisplay do the trick with less Sprites than onScreenDisplay

**Comment by peppy** [comment]
The idea is that we have just one pathway for "OSD" overalys, so this is how it would have to be done in order to make it into the code base.

**Comment by peppy** [comment]
Closing in favour of https://github.com/ppy/osu/pull/5268 (pathway to implementation using on-screen display)

**Pull request closed without merging**
