### PR TITLE
Add better click-to-dismiss logic for sheared overlays

### PR DESCRIPTION
**Pull request by peppy**
The content blocking behaviour will probably be further abstracted in the future, but this should do for now.

I've tested that this mostly works as expected with the new mod overlay (which the exception that the scroll container is a bit greedy, but feels okay).

### CODE REVIEW

**Review by frenzibyte — DISMISSED** [review]
Seems fine, going to request a second review in case I'm missing something with this.

**Comment by bdach** [comment]
Dunno what was meant in the OP when saying that this "mostly works as expected with the new mod overlay", but I found a hole - clicking on the mod multiplier display dismisses the overlay which doesn't feel right to me:

https://user-images.githubusercontent.com/20418176/164541116-8ca455af-ed05-43e2-8802-8290ce60c364.mp4

I know what the fix here would be - it would be to add another `InputBlockingContainer` in the mod multiplier - but to be honest I'm not feeling the implications of this method of handling mouse events, both code-wise and UX-wise:

* Code-wise everything in the foreground must be wrapped inside something that handles clicks lest you get that same bug again.
* From a UI/UX perspective I'm not sure that every available gap on every single overlay should automatically dismiss the overlay. On a popup, if there is a lot of available real estate on the sides, I could agree with that - but I don't know if I agree with that on the mod select overlay, because there the gaps between contents are sparse and thin and the overlay getting dismissed upon (probably accidentally) clicking on any one of them will probably lead to confusion. So I'd probably propose to disable that behaviour altogether and rely on the Escape key/the X button in the top right.

**Comment by frenzibyte** [comment]
> From a UI/UX perspective I'm not sure that every available gap on every single overlay should automatically dismiss the overlay. On a popup, if there is a lot of available real estate on the sides, I could agree with that - but I don't know if I agree with that on the mod select overlay, because there the gaps between contents are sparse and thin and the overlay getting dismissed upon (probably accidentally) clicking on any one of them will probably lead to confusion. So I'd probably propose to disable that behaviour altogether and rely on the Escape key/the X button in the top right.

I could agree with that on overlays like mod select, but I'm unsure how to feel about ones like in the [general overlay draft](https://www.figma.com/file/E6kgzLP6CGd62NPSRXLkUX/General-Overlay?node-id=0%3A1):
CleanShot 2022-04-21 at 23 03 30@2x

But it's subject to change given it's a draft, so maybe not worth mentioning just yet.

**Comment by bdach** [comment]
Yeah, I don't disagree with that, I even stated as much on the above. On a dialog with plenty of free real estate where the areas triggering exit are large enough it's fine by me. The new mod select design is not one of those.

**Comment by peppy** [comment]
I was going for "every hole works". Except maybe padding between columns and such.

I did notice the mod multiplier but that can be fixed by making it handle input.

**Review by frenzibyte — APPROVED** [review]
I think that sounds fine for now.

**Comment by bdach** [comment]
I guess we'll see how this pans out in user testing.

**Review by bdach — APPROVED** [review]

**Pull request merged**
