### PR TITLE
Fix Alt-F4 being blocked during gameplay

### LINKED ISSUE #2887: Alt F4 in-map brings up pause menu, then quit the game on second trigger
Like the title said. Since I'm familiar with Alt F4 directly quitting to map selection, this throws me off my habits. Except, Alt F4 the secons time at pause exits.

Edit: Also Alt F4 quits the game at autoplay

### PR DESCRIPTION
**Pull request by Joehuu**
Fixes #2887

### CODE REVIEW

**Comment by peppy** [comment]
The functionality was implemented to match stable. The confirm exit dialog was intended (think of it as a "save changes?" confirmation, since it will eventually block when a task is in progress). Unsure how much of this change we want.

Open to feedback.

**Comment by Joehuu** [comment]
https://github.com/ppy/osu/issues/2887#issuecomment-400641181

Did I misunderstand?

**Comment by peppy** [comment]
You didn't, but that was specifically about pause behaviour. I need a bit of time to figure what feels correct here, but as above I believe the quit confirmation should still fire under cases it is saving the user from potential distress.

**Comment by Joehuu** [comment]
Leaving the exit dialog and just letting alt-f4 bypass pause.

**Review by peppy — DISMISSED** [review]

**Comment by peppy** [comment]
@smoogipoo want to double-check this one? i had to add additional handling for fail, probably worth a second set of eyes.

**Review by peppy — DISMISSED** [review]

**Review by smoogipoo — APPROVED** [review]
Looks ok

**Pull request merged**
