### PR TITLE
Change HoldForMenu slider precision to 50

### LINKED ISSUE #6341: Hold-to-confirm should have a sane minimal value
Setting hold-to-confirm to 1ms is functionally identical to 0ms but removes all the confirmations 0ms has. A sane minimal value like 50ms (1/3 the average reaction time of a human) in addition to 0ms should be used.

### PR DESCRIPTION
**Pull request by LanTenDragon**
Fixes #6341

### CODE REVIEW

**Review by smoogipoo — APPROVED** [review]

**Comment by iiSaLMaN** [comment]
This should've been a `double` instead of `float`, will change in another PR.

**Comment by smoogipoo** [comment]
what? why?

**Comment by iiSaLMaN** [comment]
Because it's used in time calculations, which has a `double` just a code quality thing, nothing more.

**Comment by bdach** [comment]
I'm not sure that is worth the time. The values of that slider are whole numbers that can be accurately represented without rounding errors using floating point variables, no matter if single or double precision. Conversions will be lossless.

**Pull request merged**
