### PR TITLE
Add ability to rename the skin

### PR DESCRIPTION
**Pull request by normalid-awa**
- Addresses #31214 

Added a button to the skin section of the setting, when clicked, a popover will pop in, containing a text box and button for inputting the new skin name.

https://github.com/user-attachments/assets/84bbff9d-02e4-4fed-934f-15ab383b423c

### CODE REVIEW

**Comment by peppy** [comment]
This should be in the skin layout editor similar to changing beatmap metadata.

**Comment by normalid-awa** [comment]
> This should be in the skin layout editor similar to changing beatmap metadata.

image
like this? 
if it's I think it's too hidden as the editor is a *layout* editor, it shouldn't modify the metadata kinds of stuff.

**Comment by Artcens** [comment]
> like this? if so I think it's too hidden as the editor is a layout editor, it shouldn't modify the metadata kinds of stuff.

I kind of agree with this, but placing it in _settings_ also makes _settings_ more cluttered, especially with taking a whole button for one simple feature.

Since you don't want to make it "hidden," but I also want _settings_ much cleaner, my suggestion is to remake the layout of the skin section with something like this:

image

The image above is just an illustration, so take this as an idea.
might as well clean the rest of the _settings_.

**Comment by peppy** [comment]
i can live with the proposal as a stop gap until someone realises the skin editor UI/UX.

**Comment by bdach** [comment]
What we need is an actual skin management view at this point.

**Comment by peppy** [comment]
> What we need is an actual skin management view at this point. Both solutions proposed here feel bad imo.

Yes, the hope would be something like the mod presets panels or collection management overlay, where each skin is a panel or whatever and could be renamed locally.

But as a skin *author* it should be feasible to change metadata from the skin layout editor (I'm assuming you don't have an issue with that as long as it's done similarly to the beatmap editor).

Renaming skins is a very commonly requested feature so even if a button at settings feels "bad" i'd still be willing to merge it if it's isolated and works.

**Comment by bdach** [comment]
In skin layout is fine but as far as jamming it in settings goes, I'd prefer effort to go into an actual management view rather than Even More Settings.

**Comment by peppy** [comment]
I'm gonna make a call to get this in as a short-term QoL improvement with the assumption it's going to be rewritten in the future. It will benefit players immediately.

Removed localisable strings because it doesn't make sense to localise them for such a temporary usage.

**Review by peppy — APPROVED** [review]

**Pull request merged**
