### PR TITLE
Taiko visual update

### PR DESCRIPTION
**Pull request by smoogipoo**
Prereqs:
- [x] https://github.com/ppy/osu-framework/pull/748
- [x] https://github.com/ppy/osu/pull/831

Small visual update. Adds kiai time flashes to notes, fixes explosions looking EUUUGH.

* Adds kiai explosions to the hit target.
* Adds kiai flash to hit objects.
* Makes hit explosions coloured by hit object colours.
* Masks hit explosions so they don't underflow the left side of the stage.

### CODE REVIEW

**Comment by peppy** [comment]
New explosions look worse than old IMHO

**Comment by smoogipooo** [comment]
Aw :( I imagined it having particles coming out from the side in the end and possibly expanding out further or being more potent during kiai...

I definitely feel like the circle explosions were weird and off-putting though, they felt very weirdly layered.

I'll try out more things at some point if you don't want to merge this in for now, but as you said I don't want to spend too much time on this.

**Comment by smoogipooo** [comment]
I have other ideas in mind so no worries if you'd reject this though :P

**Comment by smoogipooo** [comment]
@peppy let me know if you're happy with the hit explosions as they are for now, I've made them circular but am keeping them masked since I still don't like them underflowing the left area, especially when they become very prominent due to multiple explosions being layered.

**Comment by smoogipooo** [comment]
Added summary of changes to PR description.

**Review by peppy — APPROVED** [review]

**Pull request merged**
