### PR TITLE
Reworked triangles animation and logo coloring

### PR DESCRIPTION
**Pull request by TacoGuyAT**
Added multicolor support to the triangles drawable, reworked triangles animation (speed and beat sync), added background-colored logo option

Reworked triangles inspired by this old video (youtube link): [image](https://www.youtube.com/watch?v=mCskT-NxyQY)
===
Demo (youtube link):
[image](https://www.youtube.com/watch?v=hpVuPbZBlCE)
===

### CODE REVIEW

**Comment by 3stantedja** [comment]
Just want to give you the heads-up that the lazer demo video is privated.

**Comment by TacoGuyAT** [comment]
> Just want to give you the heads-up that the lazer demo video is privated.

Whoops, fixed, thanks

**Comment by toadsworth-jr** [comment]
We cannot see the changes you have made because your YouTube demo is set to private.
Did you forget to set it to unlisted?

**Comment by bdach** [comment]
Did you read the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md)? They include the following passage:

> If you want to make _changes_ to the design, we recommend you open an issue with your intentions before spending too much time to ensure no effort is wasted.

**Comment by TacoGuyAT** [comment]
> Did you read the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md)? They include the following passage:
> 
> > If you want to make _changes_ to the design, we recommend you open an issue with your intentions before spending too much time to ensure no effort is wasted.

Uhhh no.. I'm sorry about that... Just saw it, but if it will be approved with visual changes, I'll fix guideline stuff (like moving things from master to separate branch) and review requests. It's okay if it won't be approved, it's still was fun to work on this.

**Comment by frenzibyte** [comment]
Start by describing what you've actually changed here and what's the goal of this PR, rather than just a video with a generic title.

As far as I'm seeing, triangles animation have changed to speed up every beat, and a setting has been added which changes the logo to match background colours. It's better to keep each change to its own PR, as I don't foresee the logo background colours part being accepted.

**Comment by peppy** [comment]
https://osu.ppy.sh/wiki/en/Brand_identity_guidelines

> Please use the logo as provided by the design kit without any modification.

You're welcome to PR the triangle speed adjustment, but please open a new pull request on a non-master branch without the other changes and we'll discuss there.

**Pull request closed without merging**
