### PR TITLE
Indecisive mod

### PR DESCRIPTION
**Pull request by MaxOhn**
This implements the Indecisive mod.
Took me a while to find a name for this and once I gave up I just stuck with Indecisive.
The simple idea is to alternate notes between nomod and hidden.
~~As of now it's basically just a copy of OsuModHidden.cs with a tiny tweak so some refactoring could make this more elegant.~~ OsuModIndecisive now inherits from OsuModHidden.
Preview: https://streamable.com/rc334

### CODE REVIEW

**Comment by Aergwyn** [comment]
You may wanna try to inherit from `OsuModHidden` and just override `ApplyToDrawableHitObjects` instead of copying the whole class for that single change. Should make it a lot smaller.

**Comment by MaxOhn** [comment]
If I do that and activate the hidden mod ingame then the indecisive mod will activate aswell.

**Comment by Aergwyn** [comment]
Oh. I suggest making it exclusive with Hidden.

**Comment by peppy** [comment]
I don't think this is that fun or imaginative enough to make a mod. If anyone disagrees feel free to comment and we will reconsider.

**Pull request closed without merging**
