### PR TITLE
Fix intermittent match song select test failures

### PR DESCRIPTION
**Pull request by smoogipoo**
Can be tested by adding `Thread.Sleep(2000)` at the end of `BeatmapInfoWedge.load()`. I'm not 100% sure why this specifically causes the issue so I focused on the issues only at a surface level. Others are welcome to investigate if they see this as a requirement.

619c1861cd9939d54dbf85893aeea82e6ee35f68: Fixes a test which fails when other tests are run alongside it.

It seems like this is because the current `DrawableTrack` finishes and `MusicController` changes to another beatmap. It just so happens that this happens after the `.SetDefault()` call in `SetUpSteps()`. I'm unsure why this happens atm.

Fixed by checking against the default value of the song select's `Beatmap` bindable instead.

6611ca10c2917fe5f7cfde80694c8688cd73746d: Fixes running the tests in the browser failing with:
```
[runtime] 2022-03-10 10:22:04 [error]: Realms.Exceptions.RealmClosedException: This object belongs to a closed realm.
[runtime] 2022-03-10 10:22:04 [error]: at Realms.RealmHandle.EnsureIsOpen()
[runtime] 2022-03-10 10:22:04 [error]: at Realms.ObjectHandle.GetValue(String propertyName, Metadata metadata, Realm realm)
[runtime] 2022-03-10 10:22:04 [error]: at osu.Game.Beatmaps.BeatmapInfo.get_Ruleset()
[runtime] 2022-03-10 10:22:04 [error]: at osu.Game.Tests.Visual.Multiplayer.TestSceneMultiplayerMatchSongSelect.<>c.<TestBeatmapConfirmed>b__9_9(BeatmapInfo beatmap) in /home/smgi/Repos/osu/osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerMatchSongSelect.cs:line 144
[runtime] 2022-03-10 10:22:04 [error]: at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
[runtime] 2022-03-10 10:22:04 [error]: at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
[runtime] 2022-03-10 10:22:04 [error]: at osu.Game.Tests.Visual.Multiplayer.TestSceneMultiplayerMatchSongSelect.<>c__DisplayClass9_0.<TestBeatmapConfirmed>b__1() in /home/smgi/Repos/osu/osu.Game.Tests/Visual/Multiplayer/TestSceneMultiplayerMatchSongSelect.cs:line 144
[runtime] 2022-03-10 10:22:04 [error]: at osu.Framework.Testing.Drawables.Steps.SingleStepButton.<.ctor>b__1_0()
[runtime] 2022-03-10 10:22:04 [error]: at osu.Framework.Testing.Drawables.Steps.StepButton.PerformStep(Boolean userTriggered)
[runtime] 2022-03-10 10:22:04 [error]: at osu.Framework.Testing.Drawables.Steps.StepButton.OnClick(ClickEvent e)
```

### CODE REVIEW

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
Was this in a CI run somewhere? Just curious.

**Comment by smoogipoo** [comment]
Nope, just errors I found locally while running all osu.Game tests with that `Thread.Sleep()`...

**Comment by peppy** [comment]
This is not happy 🤕

**Comment by smoogipoo** [comment]
Bah. Now it's failing to the async realm query + schedule for first selection causing the bindable to change shortly after song select is loaded but before that step is run.

Probably will need help on this one because I'm not super sure how to handle it and this is a very precarious callstack for me:
image

Maybe just need to fix the `MusicController` issue or something...

**Comment by peppy** [comment]
Do you have anything against closing this for now? Neither of your commits passes with or without the proposed `Thread.Sleep` and the original test passes 100% of tries for me over 100+ runs. Even in visual tests, I can't make the new ones pass and they don't seem to make sense on a re-read (it's supposed to be reverting to the state before song select was loaded, not to the first selection after entering).

Best to just leave what works for now?

**Comment by smoogipoo** [comment]
Sure. We'd need the second commit in some fashion for sure.

**Pull request closed without merging**
