### PR TITLE
Implement TrianglesV2 component

### PR DESCRIPTION
**Pull request by EVAST9919**
Depends on:
- [x] https://github.com/ppy/osu-resources/pull/227

Marking as draft since I'm not sure whether it's a good approach to the implementation.
All the logic is copied from `Triangles` for now so it needs further tweaking to match the design, which I'm not doing yet for reasons described above.

Differences:
- new `ColourTop` and `ColourBottom` properties which will create a texture used by the `DrawNode`
- `DrawNode` draws quads with texture partitions instead of raw triangles

Why not just to use gradient colour instead of creating a new texture? Well, I couldn't figure out how to do so.

Снимок экрана (154)

### CODE REVIEW

**Comment by peppy** [comment]
I haven't checked yet whether this is an issue with the copied or new code, but on a visual inspection it would seem there's a bias for triangles to spawn at the bottom of the area initially, which looks a bit weird:

https://user-images.githubusercontent.com/191335/201822082-45a30f3e-f431-4378-8cfa-25c232b27f51.mp4

**Review by peppy — COMMENTED** [review]
As described

**Comment by EVAST9919** [comment]
Original triangles have the same issue under the same conditions, which is visible by replacing `TrianglesV2` with `Triangles` in the same test scene. In most usage cases it's "fixed" by increasing the `TriangleScale` property which leads to lower triangle count, which makes this effect far less noticeable

**Comment by peppy** [comment]
This is looking pretty good now, but I noticed there's no way to set the border thickness of the triangles. Am I missing something? It's probably a good setting to have so we can fine-tune if required (I think they may be a bit thin right now.

**Comment by EVAST9919** [comment]
> This is looking pretty good now, but I noticed there's no way to set the border thickness of the triangles. Am I missing something? It's probably a good setting to have so we can fine-tune if required (I think they may be a bit thin right now.

Sure, will expose one.

**Comment by peppy** [comment]
@EVAST9919 to get a feel for how this will look inside the buttons I've done a naive implementation, but the colours don't seem to match. I'm not immediately sure why (the `ColourBottom` should match the background and therefore provide little visual difference, as per the design, but it's not what I'm seeing).

osu! 2022-11-23 at 08 49 45



```diff
diff --git a/osu.Desktop.slnf b/osu.Desktop.slnf
index 503e5935f5..5a44bdf9a7 100644
--- a/osu.Desktop.slnf
+++ b/osu.Desktop.slnf
@@ -16,7 +16,6 @@
       "osu.Game.Tournament.Tests\\osu.Game.Tournament.Tests.csproj",
       "osu.Game.Tournament\\osu.Game.Tournament.csproj",
       "osu.Game\\osu.Game.csproj",
-
       "Templates\\Rulesets\\ruleset-empty\\osu.Game.Rulesets.EmptyFreeform\\osu.Game.Rulesets.EmptyFreeform.csproj",
       "Templates\\Rulesets\\ruleset-empty\\osu.Game.Rulesets.EmptyFreeform.Tests\\osu.Game.Rulesets.EmptyFreeform.Tests.csproj",
       "Templates\\Rulesets\\ruleset-example\\osu.Game.Rulesets.Pippidon\\osu.Game.Rulesets.Pippidon.csproj",
@@ -24,7 +23,8 @@
       "Templates\\Rulesets\\ruleset-scrolling-empty\\osu.Game.Rulesets.EmptyScrolling\\osu.Game.Rulesets.EmptyScrolling.csproj",
       "Templates\\Rulesets\\ruleset-scrolling-empty\\osu.Game.Rulesets.EmptyScrolling.Tests\\osu.Game.Rulesets.EmptyScrolling.Tests.csproj",
       "Templates\\Rulesets\\ruleset-scrolling-example\\osu.Game.Rulesets.Pippidon\\osu.Game.Rulesets.Pippidon.csproj",
-      "Templates\\Rulesets\\ruleset-scrolling-example\\osu.Game.Rulesets.Pippidon.Tests\\osu.Game.Rulesets.Pippidon.Tests.csproj"
+      "Templates\\Rulesets\\ruleset-scrolling-example\\osu.Game.Rulesets.Pippidon.Tests\\osu.Game.Rulesets.Pippidon.Tests.csproj",
+      "../osu-resources/osu.Game.Resources/osu.Game.Resources.csproj"
     ]
   }
 }
diff --git a/osu.Game.Tests/Visual/UserInterface/TestSceneRoundedButton.cs b/osu.Game.Tests/Visual/UserInterface/TestSceneRoundedButton.cs
index 2587960275..178a68b599 100644
--- a/osu.Game.Tests/Visual/UserInterface/TestSceneRoundedButton.cs
+++ b/osu.Game.Tests/Visual/UserInterface/TestSceneRoundedButton.cs
@@ -37,7 +37,7 @@ protected override Drawable CreateContent()
                     },
                     new SettingsButton
                     {
-                        Text = "Test button",
+                        Text = "Test settings button",
                         Anchor = Anchor.Centre,
                         Origin = Anchor.Centre,
                         Enabled = { BindTarget = enabled },
diff --git a/osu.Game/Graphics/UserInterface/OsuButton.cs b/osu.Game/Graphics/UserInterface/OsuButton.cs
index dae5de2d65..885c815181 100644
--- a/osu.Game/Graphics/UserInterface/OsuButton.cs
+++ b/osu.Game/Graphics/UserInterface/OsuButton.cs
@@ -37,7 +37,7 @@ public LocalisableString Text
         /// <summary>
         /// Sets a custom background colour to this button, replacing the provided default.
         /// </summary>
-        public Color4 BackgroundColour
+        public virtual Color4 BackgroundColour
         {
             get => backgroundColour ?? defaultBackgroundColour;
             set
@@ -52,7 +52,7 @@ public Color4 BackgroundColour
         /// <summary>
         /// Sets a default background colour to this button.
         /// </summary>
-        protected Color4 DefaultBackgroundColour
+        protected virtual Color4 DefaultBackgroundColour
         {
             get => defaultBackgroundColour;
             set
@@ -90,6 +90,7 @@ public OsuButton(HoverSampleSet? hoverSounds = HoverSampleSet.Button)
                         Anchor = Anchor.Centre,
                         Origin = Anchor.Centre,
                         RelativeSizeAxes = Axes.Both,
+                        Depth = float.MaxValue,
                     },
                     Hover = new Box
                     {
diff --git a/osu.Game/Graphics/UserInterfaceV2/RoundedButton.cs b/osu.Game/Graphics/UserInterfaceV2/RoundedButton.cs
index 4477633da1..7a36ee52b8 100644
--- a/osu.Game/Graphics/UserInterfaceV2/RoundedButton.cs
+++ b/osu.Game/Graphics/UserInterfaceV2/RoundedButton.cs
@@ -5,15 +5,20 @@
 
 using System.Collections.Generic;
 using osu.Framework.Allocation;
+using osu.Framework.Extensions.Color4Extensions;
 using osu.Framework.Graphics;
 using osu.Framework.Graphics.Containers;
 using osu.Framework.Localisation;
+using osu.Game.Graphics.Backgrounds;
 using osu.Game.Graphics.UserInterface;
+using osuTK.Graphics;
 
 namespace osu.Game.Graphics.UserInterfaceV2
 {
     public class RoundedButton : OsuButton, IFilterable
     {
+        private TrianglesV2 triangles;
+
         public override float Height
         {
             get => base.Height;
@@ -35,10 +40,50 @@ private void load(OsuColour colours)
             DefaultBackgroundColour = colours.Blue3;
         }
 
+        public override Color4 BackgroundColour
+        {
+            get => base.BackgroundColour;
+            set
+            {
+                base.BackgroundColour = value;
+
+                if (IsLoaded)
+                    updateColours();
+            }
+        }
+
+        protected override Color4 DefaultBackgroundColour
+        {
+            get => base.DefaultBackgroundColour;
+            set
+            {
+                base.DefaultBackgroundColour = value;
+
+                if (IsLoaded)
+                    updateColours();
+            }
+        }
+
         protected override void LoadComplete()
         {
             base.LoadComplete();
+
             updateCornerRadius();
+
+            Add(triangles = new TrianglesV2
+            {
+                Thickness = 0.04f,
+                RelativeSizeAxes = Axes.Both,
+                Depth = float.MaxValue
+            });
+
+            updateColours();
+        }
+
+        private void updateColours()
+        {
+            triangles.ColourTop = BackgroundColour.Lighten(0.5f);
+            triangles.ColourBottom = BackgroundColour;
         }
 
         private void updateCornerRadius() => Content.CornerRadius = DrawHeight / 2;
diff --git a/osu.Game/osu.Game.csproj b/osu.Game/osu.Game.csproj
index 858cac1dac..61eaf6d071 100644
--- a/osu.Game/osu.Game.csproj
+++ b/osu.Game/osu.Game.csproj
@@ -36,7 +36,6 @@
     </PackageReference>
     <PackageReference Include="Realm" Version="10.18.0" />
     <PackageReference Include="ppy.osu.Framework" Version="2022.1113.0" />
-    <PackageReference Include="ppy.osu.Game.Resources" Version="2022.1113.0" />
     <PackageReference Include="Sentry" Version="3.23.1" />
     <PackageReference Include="SharpCompress" Version="0.32.2" />
     <PackageReference Include="NUnit" Version="3.13.3" />
@@ -44,4 +43,7 @@
     <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
     <PackageReference Include="TagLibSharp" Version="2.3.0" />
   </ItemGroup>
+  <ItemGroup>
+    <ProjectReference Include="..\..\osu-resources\osu.Game.Resources\osu.Game.Resources.csproj" />
+  </ItemGroup>
 </Project>
diff --git a/osu.sln b/osu.sln
index aeec0843be..de16246fa3 100644
--- a/osu.sln
+++ b/osu.sln
@@ -95,6 +95,8 @@ Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "osu.Game.Rulesets.Pippidon"
 EndProject
 Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "osu.Game.Rulesets.Pippidon.Tests", "Templates\Rulesets\ruleset-scrolling-example\osu.Game.Rulesets.Pippidon.Tests\osu.Game.Rulesets.Pippidon.Tests.csproj", "{1743BF7C-E6AE-4A06-BAD9-166D62894303}"
 EndProject
+Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "osu.Game.Resources", "..\osu-resources\osu.Game.Resources\osu.Game.Resources.csproj", "{C7FFF42E-B637-4297-8F08-B1BB14F8BFA3}"
+EndProject
 Global
 	GlobalSection(SolutionConfigurationPlatforms) = preSolution
 		Debug|Any CPU = Debug|Any CPU
@@ -537,6 +539,18 @@ Global
 		{1743BF7C-E6AE-4A06-BAD9-166D62894303}.Release|iPhone.Build.0 = Release|Any CPU
 		{1743BF7C-E6AE-4A06-BAD9-166D62894303}.Release|iPhoneSimulator.ActiveCfg = Release|Any CPU
 		{1743BF7C-E6AE-4A06-BAD9-166D62894303}.Release|iPhoneSimulator.Build.0 = Release|Any CPU
+		{C7FFF42E-B637-4297-8F08-B1BB14F8BFA3}.Debug|Any CPU.ActiveCfg = Debug|Any CPU
+		{C7FFF42E-B637-4297-8F08-B1BB14F8BFA3}.Debug|Any CPU.Build.0 = Debug|Any CPU
+		{C7FFF42E-B637-4297-8F08-B1BB14F8BFA3}.Debug|iPhone.ActiveCfg = Debug|Any CPU
+		{C7FFF42E-B637-4297-8F08-B1BB14F8BFA3}.Debug|iPhone.Build.0 = Debug|Any CPU
+		{C7FFF42E-B637-4297-8F08-B1BB14F8BFA3}.Debug|iPhoneSimulator.ActiveCfg = Debug|Any CPU
+		{C7FFF42E-B637-4297-8F08-B1BB14F8BFA3}.Debug|iPhoneSimulator.Build.0 = Debug|Any CPU
+		{C7FFF42E-B637-4297-8F08-B1BB14F8BFA3}.Release|Any CPU.ActiveCfg = Release|Any CPU
+		{C7FFF42E-B637-4297-8F08-B1BB14F8BFA3}.Release|Any CPU.Build.0 = Release|Any CPU
+		{C7FFF42E-B637-4297-8F08-B1BB14F8BFA3}.Release|iPhone.ActiveCfg = Release|Any CPU
+		{C7FFF42E-B637-4297-8F08-B1BB14F8BFA3}.Release|iPhone.Build.0 = Release|Any CPU
+		{C7FFF42E-B637-4297-8F08-B1BB14F8BFA3}.Release|iPhoneSimulator.ActiveCfg = Release|Any CPU
+		{C7FFF42E-B637-4297-8F08-B1BB14F8BFA3}.Release|iPhoneSimulator.Build.0 = Release|Any CPU
 	EndGlobalSection
 	GlobalSection(SolutionProperties) = preSolution
 		HideSolutionNode = FALSE

```

**Comment by EVAST9919** [comment]
@peppy turned out I didn't have to use toSRGB in the shader (for some reason), now fixed.

before:
before
After:
after
Buttons with fix applied:
Снимок экрана (166)

**Review by peppy — APPROVED** [review]

**Pull request merged**
