### PR TITLE
Add FilterControl implementation

### PR DESCRIPTION
**Pull request by kOchirasu**
Depends on: https://github.com/ppy/osu-framework/pull/559

Not really happy about the way I set colors on these controls.  Is there a better way?

Selecting items in TabControl currently does nothing. Should be easy to add.
There is some known weird behavior with random items in dropdown becoming invisible until you hover.  I will look into it later when I have time.

### CODE REVIEW

**Comment by peppy** [comment]
Crashes on difficulty sort

**Comment by 2yangk23** [comment]
Difficulty sort works fine for me.  It crashes on sorts that are not implemented yet.  I can make it just default to sort by Artist or something if preferred.

**Comment by SirCmpwn** [comment]
https://github.com/ppy/osu-framework/pull/570

please be as to is merge

**Comment by peppy** [comment]
I think this is finally in a state I'm happy with.
- [ ] Depends on https://github.com/ppy/osu-framework/pull/576

**Comment by smoogipooo** [comment]
👍

**Pull request merged**
