### PR TITLE
Added ctrl + w and ctrl + t keyboard shortcuts

### PR DESCRIPTION
**Pull request by jessmeng**
- Implemented ctrl + w and ctrl + t keyboard shortcuts
- Made changes to ChatOverlay.cs "OnKeyDown" function

### CODE REVIEW

**Comment by bdach** [comment]
Why has this been closed and reopened twice now?

**Comment by jessmeng** [comment]
Hi, I’m so sorry, I meant to make a pull request to a fork of this project that my team is working on for a class project. It took me a while to figure out how to make a pull request to the fork instead of the actual ppy/osu. It’s not ready to be committed to the actual game yet.

**Comment by bdach** [comment]
Thanks for the explanation. If need be, feel free to reach out for help either here on or the [discord server](https://discord.gg/ppy), and make sure to read the [contributing guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md) before the final PR.

**Comment by jessmeng** [comment]
Yes, will do, thank you so much! Sorry again for the inconvenience caused.

**Pull request closed without merging**
