### PR TITLE
Improve argon osu!mania hold notes visuals and fix reverse scroll direction looking wrong

### LINKED ISSUE #22216: osu!mania argon note pieces don't account for scrolling direction
### Type

Cosmetic

### Bug description

Noticed when wanting to play in the opposite direction.

### Screenshots or videos

osu!_LN73pTyMWi

### Version

2022.1228.0

### Logs

N/A

### PR DESCRIPTION
**Pull request by itsMapleLeaf**
- Fixes https://github.com/ppy/osu/issues/22216

**2023-1-31:** Uses the darkened tail with a darker line to match the tap head shadow

image

<details>
<summary>old content</summary>

**2023-1-30:** Implements the flat version without any extra elements

image

As discussed [here](https://github.com/ppy/osu/discussions/21996#discussioncomment-4747511), went with the version with a darkened tail and no sprite on the end:

</details>

### CODE REVIEW

**Comment by peppy** [comment]
Something about this still looks off. Like, the hold note is not of a structure my brain can understand.

**Comment by peppy** [comment]
This looks wrong when changing scroll direction to up:

osu! 2023-01-31 at 10 08 55

vs down:

osu! 2023-01-31 at 10 09 22

Also the existing head visual on `master` is also wrong when flipped. Want to fix both while we're here? The solid white bar should be on the opposite side as to align with the judgement area...


One additional thing: I think you should round the inner corner similar to the head:

osu! 2023-01-31 at 10 09 22

**Review by peppy — CHANGES_REQUESTED** [review]
As described.

**Comment by itsMapleLeaf** [comment]
@peppy I can fix upscroll for sure 😄 by the way, should the arrow also be flipped to point up? since I figured the arrow reflects the scroll direction

**Comment by peppy** [comment]
Yes I believe so. Feel free to split into another PR if it gets too large.

**Comment by peppy** [comment]
I'm sorry but the code in this PR is unusable. And the visuals are now back to front (your shadow piece now has the wrong corner direction).

Please:
- Copy and paste the code from `ArgonNotePiece`
- Make adjustments
- Don't use the weird `2*height` hack, it's wrong

**Review by peppy — CHANGES_REQUESTED** [review]
nah

**Comment by itsMapleLeaf** [comment]
No problem, I'll make the appropriate changes. But what do you mean by "your shadow piece now has the wrong corner direction"?

**Comment by itsMapleLeaf** [comment]
Updated

**Review by peppy — APPROVED** [review]

**Pull request merged**
