### PR TITLE
Add test scene for slider snaking animation

### PR DESCRIPTION
**Pull request by mcendu**

### CODE REVIEW

**Comment by peppy** [comment]
It would be useful if this scene also had a test where the slider didn't snake (covering all four combinations), since currently you wouldn't be able to test non-snaking sliders if you have your settings set to default (where snaking *is* already enabled).

**Comment by mcendu** [comment]
Seems like that `TestSceneSlider` does not snake.

**Comment by peppy** [comment]
As mentioned, this is because you have snaking disabled in your game-wide settings, and currently the visual test browser uses those.

Try changing your settings.

**Comment by peppy** [comment]
If that's not the case, then settings in *that test* should be added to toggle snaking, rather than making a new test scene for this.

**Comment by mcendu** [comment]
Closing in favor of #8489

**Pull request closed without merging**
