### PR TITLE
Fix beatmap card play button not working with touch inputs when not hovered

### PR DESCRIPTION
**Pull request by Joehuu**
This matches mobile web behavior.

### CODE REVIEW

**Comment by peppy** [comment]
Not sure about this. I don't think an invisible control should be tappable in the first place.

**Comment by Joehuu** [comment]
From what I see, there's no other 100% invisible control. The closest is the hold for menu button in gameplay being still partly visible. Not sure if always showing works in this case as they are shown in a list and would be more visually distracting.

Put another way, this is similar to flicking your mouse/tablet at the thumbnail (which works currently) and not seeing the play button at all. I expect that pressing/touching the thumbnail area itself will preview the map.

**Comment by peppy** [comment]
I understand the current flow, and am saying it's wrong. The control should always be partly visible, or the first tap should make it visible rather than navigating, or something else. It's currently an incorrect UX and requires @arflyte's attention.

**Comment by peppy** [comment]
@arflyte any thoughts on this?

**Comment by peppy** [comment]
@arflyte still need advice on this. i've mentioned this to you before, but to reiterate: the audio preview icon on beatmap panels is currently 100% hidden until hovered, which doesn't work great with touch interfaces (users will have to memorise the location and behaviour to ensure they get the action they expect).

**Comment by peppy** [comment]
I'm just going to go with this one. It's obvious that the UX decisions are going to be on me here, so for now I'm going to match how osu-web behaves. Will revisit in the future.

**Review by peppy — APPROVED** [review]

**Pull request merged**
