### PR TITLE
Remove all EF migrations and helper methods

### PR DESCRIPTION
**Pull request by peppy**
Had this sitting around separate from the main PR to reduce noise.

### CODE REVIEW

**Comment by frenzibyte** [comment]
Removing EF migrations immediately would block users with old databases that haven't been migrated with the latest EF migrations (which are only 3~4 months ago), I think it's a better choice to remove the migrations once `EFToRealmMigrator` itself gets removed (assuming it would, 6 months later).

**Comment by bdach** [comment]
Don't see a reason not to go forward with 6ddd2d5 though. Could just rebase out the commit with migration removal and force push as an exception because this isn't really a pull that needs per-file reviewing either way.

**Comment by peppy** [comment]
The most recent migration which is required for migration is:

`20210514062639_AddAuthorIdToBeatmapMetadata`

The ones post that point at mostly just "because we could" migrations, which are tracking properties that are decoded with beatmap decode (`CountdownOffset` and `SampleMatchesPlaybackRate`)and likely shouldn't be persisted in the first place. It's on my todo list to remove these from realm, in fact.

**Comment by smoogipoo** [comment]
What happens if a database exists from before that migration, which cannot be migrated, with many beatmaps? What happens to the files in that case when the user tries to repopulate their realm database?

**Comment by peppy** [comment]
Even the mentioned (EF) migration is not required for migration to succeed (user data will just be missing the online ID).

As for the more general question of "what happens to the files": they will remain on disk. Any import that has the same files will gracefully use the existing files on disk, but obviously there will potentially also be dangling files. This is a more general issue though, and I'd see fixing that as a manual maintenance step the user can perform at any point (most applications that have a self-managed file store also offer this). The manual step would iterate over the filesystem and purge any files not also in the database.

**Comment by smoogipoo** [comment]
Hmm okay, well as long as existing files are used gracefully then I'm fine with this as is.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
