### PR TITLE
Add global key bindings for changing current ruleset

### LINKED ISSUE #2509: Game mode change shortcuts not implemented
Using Ctrl+1, Ctrl+2 , Ctrl+3, Ctrl+4 to switch between gameplay modes like in stable isn't yet implemented.

### PR DESCRIPTION
**Pull request by ocboogie**
Resolves #2509 
Old pr #2513
https://youtu.be/eHtNzSfpzZk

Note: the crash from changing the rule set on the home screen is not a result of this change. Also that might only be happening to me

### CODE REVIEW

**Comment by peppy** [comment]
The crash you mention is fixed by #2533.

**Comment by peppy** [comment]
This is a really convoluted way of doing this. Why not just use `OnKeyDown`?

**Comment by ocboogie** [comment]
@peppy Yeah sorry I'm still trying to get familiar with this code base. I for some reason thought that `OnKeyDown` only work if the Drawable had focus.
But anyways this should be better.

**Comment by peppy** [comment]
I've made some large changes to the code to bring this up-to-par. @ocboogie please have a look and see what was required.

**Review by peppy — APPROVED** [review]

**Pull request merged**
