### PR TITLE
Move caught object stack vertical offset logic

### PR DESCRIPTION
**Pull request by ekrctb**
It is more logical and simpler to apply the offset as the drawable position in my opinion.

Split off from #13599.

### CODE REVIEW

**Review by bdach — DISMISSED** [review]
seems reasonable

**Comment by bdach** [comment]
Interestingly, one of the failing matrix runs [https://github.com/ppy/osu/runs/2979709020?check_suite_focus=true](https://github.com/ppy/osu/pull/13746/checks?check_run_id=2979635623). @ekrctb mind taking a look into the possibility that that test can intermittently fail now?

**Comment by ekrctb** [comment]
@bdach Nice catch. The stacking code uses an unseeded RNG and there has been a chance of the test failing. But because the Y offset is removed from the stacking position, the chance the test failing is now higher, made visible to the CI.
I just replaced the test with the most relaxed condition `< 0` rather than trying to find an "acceptable probability" of failure, at least until I make the stacking code to not use an unseeded RNG.

**Review by bdach — APPROVED** [review]
stress tested with `[Repeat]`, seems more solid now :+1:

**Pull request merged**
