### PR TITLE
Fade MetadataSection back in if non-null Text is set

### LINKED ISSUE #3579: Beatmap details don't return after selecting a map with no source/tags
Just go to `Disco Prince` and then navigate to another beatmap with source/tags. It won't show them.

Also if going to song select the first time, it shows whitespace on a beatmap with no source that has tags.

### PR DESCRIPTION
**Pull request by holly-hacker**
MetadataSections were not fading back in when assigning a normal value after it was null/blank.

- Closes #3579

---

Fixes Source and Tags not reappearing if they are once set to null.

### CODE REVIEW

**Review by Joehuu — DISMISSED** [review]

**Comment by smoogipoo** [comment]
I was thinking we'd fix this properly if it ever broke, and here we are :p

This is potentially going to fade the section in before the text has actually loaded, which is why the fade-in is done in [`setTextAsync`](https://github.com/ppy/osu/pull/3632/files#diff-5fe1b1b73c529f378e0ec4a55b253857R365).

Instead of this, leave the fades where they originally were, but apply them directly to `textContainer` itself, while removing the `IsPresent` override.

**Review by smoogipoo — CHANGES_REQUESTED** [review]
As commented

**Comment by HoLLy-HaCKeR** [comment]
Ah, I'm sorry, I didn't notice that there was already a fade-in. I've changed it like you said, is this what you meant?

**Comment by smoogipoo** [comment]
Yup that's it

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
