### PR TITLE
Fix overlay sidebars not scrolling to end due to parent scroll view

### LINKED ISSUE #12906: news sidebar doesn't let you scroll to the bottom when multiple dropdowns are expanded
**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43358824/119233184-03192e80-bb28-11eb-9eeb-76c10f909d4c.mp4

**osu!lazer version:** 
2021.523.0

### PR DESCRIPTION
**Pull request by Joehuu**
- Fixes https://github.com/ppy/osu/issues/12906

osu!_LPqxsgEJEb

### CODE REVIEW

**Comment by bdach** [comment]
This is kind of broken still...

https://user-images.githubusercontent.com/20418176/222980268-80f4f8c8-e800-496f-b4ca-e0d90bc01a03.mp4

I still cannot scroll the sidebar to end until I scroll the header off the screen. The sidebar scroll should always have the correct height set in screen-space so that all of it is visible, it shouldn't be getting obscured because the top-level scroll container is scrolled such that the header is still visible.

**Review by bdach — DISMISSED** [review]
as above

**Comment by Joehuu** [comment]
It matches web behavior. This PR aims to be consistent with web and should be an issue there instead.

Also, I feel like the suggestion is similar to what was said in https://github.com/ppy/osu/issues/12906#issuecomment-847463605. I did +1 it in the past but the video is gone and I don't know what it looked like. @EVAST9919 would be nice if you still have the video / changes from that comment.

**Comment by EVAST9919** [comment]
> It matches web behavior. This PR aims to be consistent with web and should be an issue there instead.
> 
> Also, I feel like the suggestion is similar to what was said in [#12906 (comment)](https://github.com/ppy/osu/issues/12906#issuecomment-847463605). I did +1 it in the past but the video is gone and I don't know what it looked like. @EVAST9919 would be nice if you still have the video / changes from that comment.

I don't have the video, but [this pr](https://github.com/ppy/osu/pull/12951) is what have been recorded there. Changes are pretty small so I recommend just trying out the code in the pr.

**Comment by bdach** [comment]
> It matches web behavior

Huh, I guess it does. Web seems to be equally broken when it comes to scrollbar behaviour. Maybe this is fine for the time being then?

**Comment by Joehuu** [comment]
> I don't have the video, but [this pr](https://github.com/ppy/osu/pull/12951) is what has been recorded there. Changes are pretty small so I recommend just trying out the code from that pr.

I did see that PR but seems to be a different direction after peppy said the last behavior (that I wanted the video of) was broken.

**Comment by EVAST9919** [comment]
> > I don't have the video, but [this pr](https://github.com/ppy/osu/pull/12951) is what has been recorded there. Changes are pretty small so I recommend just trying out the code from that pr.
> 
> I did see that PR but seems to be a different direction after peppy said the last behavior (that I wanted the video of) was broken.

Ah, wrong comment. Anyway I don't have anything related to this anymore, sorry.

**Comment by peppy** [comment]
I think this is better than what we have so let's just go with it for now.

**Review by peppy — APPROVED** [review]

**Pull request merged**
