### PR TITLE
Remove slider head circle movement (and remove setting from "classic" mod)

### LINKED ISSUE #24639: Remove slider head movement entirely
It's going away.

The main sticking point is deciding what to do with slider snaking (see discussion thread below). Not sure we have a consensus on that yet.

### Discussed in https://github.com/ppy/osu/discussions/23320

<div type='discussions-op-text'>

<sup>Originally posted by **tovc** April 26, 2023</sup>
osu!lazer changes slider heads such that they can be clicked while moving. While this may be 'proper' functionality, it cuts into the back end of the hit window for slider heads. On slow sliders, this is mostly ( but not entirely ) a non issue. On very fast sliders, such as those found in higher difficulty 'tech' maps, this can result in the back end of a slider head's hit window being nearly entirely cut off. This issue parallels the infamous issue with osu!stable's short sliders, which players usually played by deliberately hitting early. There was solace in that you wouldn't lose acc by playing them that way. In this case, losing acc is the only practical way to play such patterns.

image
the hit window of a slider head at OD8 should be ±119.5ms. In this example, the hit window is effectively -119.5ms to +32ms, as the slider head has entirely left the area where the head was. Not only does this result in a hit window nearly 40% smaller than that is intended, it also results in a hugely asymmetrical hit window.

the now infamous fast sliders in [t+pazolite - Oshama Scramble ! (IOException Edit) [Special] mapped by IOException](https://osu.ppy.sh/beatmapsets/1376308#osu/2844649) are an example of a pattern that is largely impractical to play by hitting on time. Even if you want to cry 'skill issue', they can still result in a miss for something that _feels_ like it should have at least been a 100.

I am aware that the classic mod's 'no slider head movement' functionality fixes this, but I believe that it should be default functionality, not that hidden away in a pile of mods that many players won't even touch.</div>

### PR DESCRIPTION
**Pull request by peppy**
Closes https://github.com/ppy/osu/issues/24639.

I've gone with the most simple approach animation wise, which feels quite good to me: the snaking path will only begin snaking after the head circle is hit. I can see that others came to roughly the same consensus in the original discussion, so I don't think there will be too much contention over this change.

Things to note:

- I considered having the slider ball not appear until the head is hit, but I don't think a change like this would sit well as it would potentially reduce readability
- I intentionally made the snaking only happen on a successful hit. So if you miss the slider head completely, the outwards snaking will never complete. This could be a good visual cue.
- The original plan I had animation wise was to have the portion of path before the slider ball's current position fade out on slider head hit, but this would mean duplicating the slider path. And I don't think this is a good idea from a performance perspective for such an edge case.

Here's how it looks in slow motion:

https://github.com/ppy/osu/assets/191335/75931867-2890-47c7-b963-f553a0b6cc80

It's important to note that in the majority of cases, these kinds of sliders are so fast you can't even catch this visually. It's usually hidden under the head / tail. Even when it's not, it's hard to catch:

https://github.com/ppy/osu/assets/191335/82db9ea2-dd7a-485e-a4ae-45eaa959439b

Finally, here's what missing a slider head completely looks like:

https://github.com/ppy/osu/assets/191335/4bd0ffb4-bfa1-4cee-bd93-98e49c829762

(basically, as if snaking was not enabled)

### CODE REVIEW

**Comment by monochrome22** [comment]
If fading can't be used and it's not an issue to undermine snaking sliders or have jarring visuals in edge cases, then this is probably the best solution. 
We did consider disconnected slider heads to be less jarring than teleporting, but with disconnected sliderheads, it wouldn't be possible to reduce the amount of poor visuals by not snaking when the slider is missed, and slider heads in the middle of nowhere can look very weird.

Would it be possible to have the slider body fade out quickly, like over 40ms, instead of immediately disappearing, or would that also require duplicating the slider path?

**Comment by bdach** [comment]
The failing snaking test here probably needs to be removed or just adjusted to check that on miss the slider repeat stays in place:

```diff
diff --git a/osu.Game.Rulesets.Osu.Tests/TestSceneSliderSnaking.cs b/osu.Game.Rulesets.Osu.Tests/TestSceneSliderSnaking.cs
index 630049f408..aef7dcaa59 100644
--- a/osu.Game.Rulesets.Osu.Tests/TestSceneSliderSnaking.cs
+++ b/osu.Game.Rulesets.Osu.Tests/TestSceneSliderSnaking.cs
@@ -135,9 +135,9 @@ public void TestSnakingDisabled(int sliderIndex)
         }
 
         [Test]
-        public void TestRepeatArrowDoesNotMoveWhenHit()
+        public void TestRepeatArrowDoesNotMove([Values] bool useAutoplay)
         {
-            AddStep("enable autoplay", () => autoplay = true);
+            AddStep($"set autoplay to {useAutoplay}", () => autoplay = useAutoplay);
             setSnaking(true);
             CreateTest();
             // repeat might have a chance to update its position depending on where in the frame its hit,
@@ -145,15 +145,6 @@ public void TestRepeatArrowDoesNotMoveWhenHit()
             addCheckPositionChangeSteps(() => 16600, getSliderRepeat, positionAlmostSame);
         }
 
-        [Test]
-        public void TestRepeatArrowMovesWhenNotHit()
-        {
-            AddStep("disable autoplay", () => autoplay = false);
-            setSnaking(true);
-            CreateTest();
-            addCheckPositionChangeSteps(() => 16600, getSliderRepeat, positionDecreased);
-        }
-
         private void retrieveSlider(int index)
         {
             AddStep("retrieve slider at index", () => slider = (Slider)beatmap.HitObjects[index]);

```

I don't see how that can be reconciled with the new behaviour here (if slider head missed then don't snake out).

However, loosely related to slider body "fading out" above, something that is quite noticeable is that if a slider has its slider head missed, but then begins being tracked halfway through, it fades out much faster than if it is fully missed (to the point of appearing like it fades out instantly):

https://github.com/ppy/osu/assets/20418176/05ab83e8-e59d-4a2d-ad9f-4e25365dab2b

This probably wasn't visible previously because of a combination of 2 things:

- With classic mod off, the snaking combined with slider head movement led to the fact that at the end of the slider the body was always mostly obscured by the moving head on a full miss, hiding the abrupt fade
- With classic mod on, snaking out was just off.

Now it's in a weird state wherein a slider with a missed head will not snake (because of `UpdateProgress()` always being called with 0), but this still kicks in:

https://github.com/ppy/osu/blob/5bda9a3024c46f8f7d142d6bb761a22a4e83c960/osu.Game.Rulesets.Osu/Objects/Drawables/DrawableSlider.cs#L319-L322

**Comment by bdach** [comment]
Also this *probably* fixes https://github.com/ppy/osu/issues/24464 (should verify)

**Comment by peppy** [comment]
> Would it be possible to have the slider body fade out quickly, like over 40ms, instead of immediately disappearing, or would that also require duplicating the slider path?

See my opening post.

**Comment by monochrome22** [comment]
> See my opening post.

I misread, I thought it was talking about the idea of fading the part between the slider ball and slider head, which I assume was rejected for the same performance reasons, since it would solve problems that teleporting has.

**Comment by peppy** [comment]
> Now it's in a weird state wherein a slider with a missed head will not snake (because of UpdateProgress() always being called with 0), but this still kicks in

Good catch.

**Review by bdach — APPROVED** [review]

**Pull request merged**
