### PR TITLE
Fix taiko maps sporadically not completing with Hidden mod active

### PR DESCRIPTION
**Pull request by chayleaf**
I don't know how to reproduce this issue in a test, so no tests for now. Nonetheless, this fixes the issue for me at least on [this map](https://osu.ppy.sh/beatmapsets/1899665#taiko/3915653).

This workaround is similar to #16475 (the test from that commit got eventually removed for some reason) and should fix #15472

### CODE REVIEW

**Comment by bdach** [comment]
> the test from that commit got eventually removed for some reason

That's a good question. It was removed in https://github.com/ppy/osu/pull/18764. I don't know why the existing test there wasn't moved across.

I will look into this and add appropriate test coverage for the problematic case here because I'm not merging this without.

**Comment by chayleaf** [comment]
> I will look into this and add appropriate test coverage for the problematic case

In that case you should know that this has only happened to me with HD lately (mostly because I only play HD, but there's indeed a chance it isn't reproducible without HD)

**Comment by bdach** [comment]
Still am unable to reproduce issue. And I've tried all of the mods you listed, I've tried switching threading modes, I've tried making window narrow.

I can't understate how distressing it is for me to be merging what looks like essentially random fixes to core gameplay without understanding root causes of the underlying failure.

Can you at the least record a video of how you're hitting this? Or put a breakpoint on the `ApplyResult()` call and see what `Time.Current` is, what `HitObject.GetEndTime()` is, what `ParentHitObject.GetEndTime()` is?

**Comment by chayleaf** [comment]
https://youtu.be/x8FkbH0aezM

[broken runtime.log](https://github.com/ppy/osu/files/12061983/broken.log)

specifically

```
2023-07-15 15:25:05 [verbose]: judged False cur 289770.6251126787 start 289682 end 289682 par_end 289682
```

**Comment by bdach** [comment]
Video is private, but thanks for the rest.

**Comment by chayleaf** [comment]
fixed the video link

**Comment by bdach** [comment]
Thanks. That was helpful, I have a reproducer now locally too.

Key points:

- Hidden was indeed instrumental to reproduction here, as it's messing with DHO lifetime:

  https://github.com/ppy/osu/blob/1868826d692f9d0c0fc13a9184758a1c3518a85f/osu.Game.Rulesets.Taiko/Mods/TaikoModHidden.cs#L60-L64

- Reproduction is timing dependent. What needs to happen is:
  - Strong hit is hit once, less than 30ms before the strong hit's time.
  - The code in `DrawableHit` doesn't attempt judge the inner nested hit as a miss until 30ms has passed between the first and the potential second hit.
  - However, due to `TaikoModHidden`'s meddling, the lifetime of the strong hit is cut short before 30ms can pass, meaning that `DrawableHit` never gets to judge the inner strong hit as a miss.

While I'm not sure whether what `TaikoModHidden` is doing is all that great there, the fix proposed makes sense in that context and is probably a good safety to have.

I'll push test cases here momentarily. (Since we're messing with the code that fixed https://github.com/ppy/osu/pull/16475, I'm also bringing that removed test case back here.)

**Comment by chayleaf** [comment]
> However, due to TaikoModHidden's meddling, the lifetime of the strong hit is cut short before 30ms can pass

I'll push a fix as this messes with the strong note timing

**Comment by bdach** [comment]
Please hold. I'll get it.

**Review by bdach — DISMISSED** [review]

**Comment by chayleaf** [comment]
I wonder if `Time.Current > ParentHitObject?.HitObject.GetEndTime()` should be replaced with `ParentHitObject?.Judged` (or what is the purpose of `GetEndTime` here?)

**Comment by bdach** [comment]
If you mean the check in `DrawableStrongNestedHit`, then yes, checking end time has a purpose there. Hitobjects also get killed during rewind, and the end time check is supposed to prevent the nested hit being judged as a miss during rewind.

**Review by peppy — APPROVED** [review]

**Pull request merged**
