### PR TITLE
Fix attempting to export replay from results screen after play not working

### LINKED ISSUE #24364: Replays do not export correctly immediately after completing map
### Type

Game behaviour

### Bug description

Whenever saving a replay directly after completing a map (in the result screen), the export results in a 0 byte file.

Steps to reproduce:
1. Start, and play through any map
2. Click F2 to export a replay on the result screen

### Screenshots or videos

image

### Version

2023.717.0

### Logs

[performance.log](https://github.com/ppy/osu/files/12163670/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12163671/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12163672/updater.log)
[database.log](https://github.com/ppy/osu/files/12163673/database.log)
[input.log](https://github.com/ppy/osu/files/12163674/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12163675/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12163676/network.log)

### PR DESCRIPTION
**Pull request by peppy**
Closes https://github.com/ppy/osu/issues/24364.

At some point we probably want to look at doing a higher level detach, but I don't really want to investigate the repercussions of that right now.

### CODE REVIEW

**Review by bdach — DISMISSED** [review]

**Comment by bdach** [comment]
what is this test failure... https://github.com/ppy/osu/actions/runs/5672638365/job/15372298778?pr=24367#step:5:67



how can the test pass the file existence check but then _die to a null stream_?

either it's some freak flush scenario or github actions runner filesystems have the reliability of `/dev/null`. what do i even do with this now?

**Comment by peppy** [comment]
Actually a valid concern, see 

https://github.com/ppy/osu/blob/e0823ffd036b15fd202eb8169ab6c673d54b4951/osu.Game/Database/LegacyExporter.cs#L94

https://github.com/ppy/osu-framework/blob/50f506146bb3f413e78af7e804e6f9372e14558a/osu.Framework/Platform/Storage.cs#L121-L126

**Comment by bdach** [comment]
I'm not sure what I'm supposed to be looking at there. `CreateFileSafely()` does remove a file yes, but it removes it from the initial temporary location, not its final target destination. And the rest failure involved suggests that the file appeared _and then disappeared_, at its _final_ location, no?

**Comment by peppy** [comment]
In this case, the temporary path is in the same folder, using a `_` prefix. So the temporary file would appear momentarily, then be moved to the final location.

**Review by bdach — APPROVED** [review]

**Pull request merged**
