### PR TITLE
Add remove buttons for mod entries in custom preset lists

### PR DESCRIPTION
**Pull request by CloneWith**
## Changes

To make it easier for users to remove unwanted mods in a custom mod preset.

Preview

- Add remove buttons to the left of a mod entry, with a static tooltip
- Block removing action and make the entry flash red when there is only one mode left in a preset

---

By the way should we consider add a `Use current mods` in the context menu? Thus we don't need to open the editor popup to apply mods to a preset.

## Known Problems

- [x] Since we pass a fixed hashset to the mod row, it's unable to change the state of the remove button. I'm considering using a `Bindable<Hashset<Mod>>` for that.
- [x] The use of `LocalisableString` for tooltip text is being considered.
- [ ] Update both flow containers upon mod change
- [ ] Layout adjustment

### CODE REVIEW

**Comment by bastianpedersen** [comment]
> The use of LocalisableString for tooltip text is being considered.

This is not even negotiable. It needs to be localised.

**Comment by bdach** [comment]
Before we go too far into bikeshedding here I kind of don't get why this feature exists.

- Is remaking a preset really such an issue that this is required to exist?
- Why is *removing* mods made explicitly easier? Adding mods to a preset is still as cumbersome as it presumably was before. Why distinguish removal? Why introduce such asymmetry between the two operations?

**Comment by CloneWith** [comment]
> Before we go too far into bikeshedding here I kind of don't get why this feature exists.

I could say for sure that it's here for yielding to the current version of preset popup design, since I tried not to modify that if not necessary.

My idea is that if the popup can be built into the preset list (or just add an entry to the context menu, as I've stated above), it should relieve the *asymmetry* problem.

Or if possible, we can also add a popup just for *adding* mods, for *summetry*, but I think that's going too far.

> Why introduce such asymmetry between the two operations?

This is not *introduced*, just *presented*. Removing a mod entry is considerably easier than adding and modifying one.

**Comment by bdach** [comment]
You still haven't told me why the current methods of doing this (either remaking the preset, or clicking "Use current mods") are insufficient or inadequate. I'd like the answer to that before considering this feature on merit.

**Comment by CloneWith** [comment]
> You still haven't told me why the current methods of doing this (either remaking the preset, or clicking "Use current mods") are insufficient or inadequate. I'd like the answer to that before considering this feature on merit.

Weird positioning of the popup

1. Due to the nature of popups, it disappears upon losing focus (e.g. cursor clicking outside the popup area), making it impossible to change the mod combination and the name / description at the same time (I, maybe other users, want to do this). Currently to achieve this we need to: adjust the mods first -> open the edit popup -> click `use current mods` and change the texts.
2. Popups move with the preset entry without animation, even when the entry is out of screen of at a random weird position (even with animations it won't help much whatsoever, it just feels *stuck* somewhere), see the picture above.
3. Blaming the interaction logic above, we are unable to create a preset *from the start* (i.e. get the name and description written first, then the mods. This is disabled), or consider creating a copy of an existing preset (would be good if we add that later).

From my perspective, I really hope that we can remake the preset UI, which can help directly resolve the problems above.

**Comment by bdach** [comment]
None of the problems you mention have anything to do with being able to delete a mod from the popover. I dunno why you'd want point (1), but I suppose it's not for me to decide; point (2) is borderline a bug that this change does nothing about, and for point (3) I'm not sure why you'd _need_ to start a preset by typing in the name, and creating a copy is easy enough as _just selecting the preset you want to copy_, then doing whatever you need to do to the selected mods, and then saving the result.

I dunno this feels fixing an issue nobody should have. @peppy your thoughts on this thing? I'd say we don't want it.

**Comment by peppy** [comment]
I don't see any harm in having it if the complexity overhead is minimal, but also not sure it's required. Since there's already a button explaining how to update the preset, I'd hope that most users can figure out how to remove mods using the existing flow.

Additionally, I see less value in adding a "remove" button if there's not also an "add" button.

**Comment by CloneWith** [comment]
Have tried to add a similar flow container for available mods, where we can add mods to the current preset.
The code might seem chaotic, but at least it somehow works. Subsequent details will be investigated later.

**Comment by bdach** [comment]
> Remade preset editing popup

I'm sorry but... my feedback is mostly 'just no'. This is literally duplicating the entire mod select content inside the popover. You can't do that.

Is editing a popover using one of the flows described above really such an issue?

**Comment by CloneWith** [comment]
> > Remade preset editing popup
> 
> I'm sorry but... my feedback is mostly 'just no'. This is literally duplicating the entire mod select content inside the popover. You can't do that.
> 
> Is editing a popover using one of the flows described above really such an issue?

I think you're right.
Currently my idea and design around this isn't so clear, and too much time has been spent on this without a sound outcome... I'd rather close this by now.

This part of issue is bigger than I've expected, we could create a discussion and leave it to the community if possible.

**Comment by peppy** [comment]
Thanks for trying this out regardless. Sometimes we need to try and realise it doesn't work 😅

**Pull request closed without merging**
