### PR TITLE
Ensure at least one scale popover axis is active at any time

### PR DESCRIPTION
**Pull request by bdach**
Spotted in passing when reviewing https://github.com/ppy/osu/pull/30080. The popover would very arbitrarily revert to scaling by Y axis if both checkboxes were checked off.

Not sure how this passed review.

### CODE REVIEW

**Comment by OliBomby** [comment]
I agree this is how it should behave if both axes are turned off.

Maybe we should disable the ability to turn off both axes because i dont think the user ever intends to turn off both axes and make the scale tool useless. It should automatically turn on the other checkbox if you turn off the last checkbox.

**Comment by peppy** [comment]
I don't get these checkboxes. You uncheck both and it still scales Y now?

Would appreciate if someone can ping me for new UX like this. I think these checkboxes feel really bad / confusing.

**Comment by OliBomby** [comment]
> I don't get these checkboxes. You uncheck both and it still scales Y now?
> 
> Would appreciate if someone can ping me for new UX like this. I think these checkboxes feel really bad / confusing.

osu!_VoKgpGgBDk

It's not really new UX. These have been in osu! stable for ages and they're supposed to not scale if both axes are off.

**Comment by peppy** [comment]
I didn't add those and it's stupid and really shouldn't exist.

As you propose, at very least, one axis should always be required.

**Review by peppy — COMMENTED** [review]
As proposed

**Comment by bdach** [comment]
> Would appreciate if someone can ping me for new UX like this

Originally this was added in https://github.com/ppy/osu/pull/28309 which I guess I didn't ping for reviews thinking that obviously it's in stable so it's fine. But then you authored https://github.com/ppy/osu/pull/28559 and reviewed https://github.com/ppy/osu/pull/26311 which touched (and regressed) this. I don't like pulling receipts but that sort of response makes me a little miffed.

**Comment by peppy** [comment]
It's completely on me for letting it slip through. But it's definitely the first time I've been actively aware of these checkboxes so please allow me to have a kneejerk reaction to their jank 😄.

The fact it exists on stable is also a surprise to me, but it makes more sense that it was copied across without further consideration.

**Comment by bdach** [comment]
> I propose this:

Applied verbatim, thanks.

**Review by peppy — APPROVED** [review]

**Pull request merged**
