### PR TITLE
Hide scroll speed changes in std and ctb editor

### LINKED ISSUE #29336: Scroll speed changes show up in editor for standard and ctb gamemodes
### Type

Game behaviour

### Bug description

In the osu!standard gamemode editor you can see scroll speed changes in the attributes of timing points in the timing tab and on the bottom timeline. This doesn't make sense to have in the standard gamemode editor because it doesnt affect anything and you can not even change it in the standard gamemode editor. Same applies for the ctb editor.

### Screenshots or videos

osu!_ENfUWWc3SU

### Version

2024.731.0-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16532675/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by OliBomby**
closes #29336

Test is broken because you cant make a `DrawableRuleset` of a `TestBeatmap`. Is there a better way to extract ruleset information from the beatmap?

### CODE REVIEW

**Comment by bdach** [comment]
Yeah I dunno. The conditional seems generally sane, but I'm not sure how to fix the test aside from just... fixing the test itself to not use a `TestBeatmap`.

The fact that instantiating a `DrawableRuleset` to check this worries me. I'm also acutely aware that the *other* rulesets will want to have SVs shown likely on both timelines, so I'm not super sure this is the correct direction in general. Maybe the thing here is to have settable or overridable flags, and override them on a per-ruleset basis rather than trying to backwards-reason the flag's value from drawable rulesets...? @ppy/team-client would like to hear thoughts

**Comment by OliBomby** [comment]
I think I found a decent solution.

To draw scroll speed changes is now determined by an overridable flag in `Ruleset`. This eliminates the need to instantiate a drawable ruleset entirely and removes the need for `IDrawableScrollingRuleset.VisualisationMethod`. It seems that interface value was only being used for determining whether to draw scroll speed in the editor timing section.

I also fixed an unrelated issue of missing scroll speed visualisation at the start of kiai sections. They were being drawn off-screen because of a wrong positioning calculation.
NVIDIA_Share_Z0WT4wPJ9d

**Review by smoogipoo — APPROVED** [review]
I'm a bit concerned about the scope creep in polluting `Ruleset`, but I suppose I'm fine with this for the time being.

**Comment by bdach** [comment]
> I'm a bit concerned about the scope creep in polluting `Ruleset`

That's why I was expecting more discussion to happen here rather than a quick merge.

I think we'll need to do a very API-breaking pass on `Ruleset` anyway at some point. The API is very haphazard and needs to be structured better.

**Pull request merged**
