### PR TITLE
Improve handling of beatmap collection changes in `CollectionDropdown`

### LINKED ISSUE #24315: Collections dropdown shouldn't scroll to top when adding a beatmap to a collection
I started to look into this, thinking I could fix it by handling the realm `CollectionChanged` event correctly. It turns out that this isn't enough, because `Dropdown` doesn't handle the `BindableList` `CollectionChanged` event correctly [either](https://github.com/ppy/osu-framework/blob/950a0c4931a655e2c8988684c6fba3ec2bcdfac8/osu.Framework/Graphics/UserInterface/Dropdown.cs#L232).

This will require framework changes.

Here's an osu-side change for anyone brave enough to get things started:

```diff
diff --git a/osu.Game/Collections/CollectionDropdown.cs b/osu.Game/Collections/CollectionDropdown.cs
index e435992381..5f69c462d7 100644
--- a/osu.Game/Collections/CollectionDropdown.cs
+++ b/osu.Game/Collections/CollectionDropdown.cs
@@ -43,11 +43,13 @@ public partial class CollectionDropdown : OsuDropdown<CollectionFilterMenuItem>
 
         private IDisposable? realmSubscription;
 
+        private readonly CollectionFilterMenuItem allBeatmapsItem = new AllBeatmapsCollectionFilterMenuItem();
+
         public CollectionDropdown()
         {
             ItemSource = filters;
 
-            Current.Value = new AllBeatmapsCollectionFilterMenuItem();
+            Current.Value = allBeatmapsItem;
         }
 
         protected override void LoadComplete()
@@ -61,37 +63,56 @@ protected override void LoadComplete()
 
         private void collectionsChanged(IRealmCollection<BeatmapCollection> collections, ChangeSet? changes)
         {
-            var selectedItem = SelectedItem?.Value?.Collection;
+            if (changes == null)
+            {
+                filters.Add(allBeatmapsItem);
+                filters.AddRange(collections.Select(c => new CollectionFilterMenuItem(c.ToLive(realm))));
+                if (ShowManageCollectionsItem)
+                    filters.Add(new ManageCollectionsFilterMenuItem());
+            }
+            else
+            {
+                foreach (int i in changes.DeletedIndices)
+                    filters.RemoveAt(i + 1);
 
-            var allBeatmaps = new AllBeatmapsCollectionFilterMenuItem();
+                foreach (int i in changes.InsertedIndices)
+                    filters.Insert(i + 1, new CollectionFilterMenuItem(collections[i].ToLive(realm)));
 
-            filters.Clear();
-            filters.Add(allBeatmaps);
-            filters.AddRange(collections.Select(c => new CollectionFilterMenuItem(c.ToLive(realm))));
+                var selectedItem = SelectedItem?.Value;
 
-            if (ShowManageCollectionsItem)
-                filters.Add(new ManageCollectionsFilterMenuItem());
+                foreach (int i in changes.NewModifiedIndices)
+                {
+                    var updatedItem = collections[i];
 
-            // This current update and schedule is required to work around dropdown headers not updating text even when the selected item
-            // changes. It's not great but honestly the whole dropdown menu structure isn't great. This needs to be fixed, but I'll issue
-            // a warning that it's going to be a frustrating journey.
-            Current.Value = allBeatmaps;
-            Schedule(() =>
-            {
-                // current may have changed before the scheduled call is run.
-                if (Current.Value != allBeatmaps)
-                    return;
+                    // TODO: All code below this point is pretty crap and won't work with Dropdown in its current state.
+                    // Basically, dropdown handles only a full wipe of items with new items. It also handles reselection of current.
+                    // Because we're now doing individual operations, this breaks reselection of the current items if it is updated.
+                    // Removing the next two lines would fix this issue, at least.
 
-                Current.Value = filters.SingleOrDefault(f => f.Collection != null && f.Collection.ID == selectedItem?.ID) ?? filters[0];
-            });
+                    // This is responsible for updating the state of the +/- button and the collection's name.
+                    // TODO: we can probably make the menu items update with changes to avoid this.
+                    filters.RemoveAt(i + 1);
+                    filters.Insert(i + 1, new CollectionFilterMenuItem(updatedItem.ToLive(realm)));
 
-            // Trigger a re-filter if the current item was in the change set.
-            if (selectedItem != null && changes != null)
-            {
-                foreach (int index in changes.ModifiedIndices)
-                {
-                    if (collections[index].ID == selectedItem.ID)
+                    if (updatedItem.ID == selectedItem?.Collection?.ID)
+                    {
+                        // This current update and schedule is required to work around dropdown headers not updating text even when the selected item
+                        // changes. It's not great but honestly the whole dropdown menu structure isn't great. This needs to be fixed, but I'll issue
+                        // a warning that it's going to be a frustrating journey.
+                        Current.Value = allBeatmapsItem;
+                        Schedule(() =>
+                        {
+                            // current may have changed before the scheduled call is run.
+                            if (Current.Value != allBeatmapsItem)
+                                return;
+
+                            Current.Value = filters.SingleOrDefault(f => f.Collection?.ID == selectedItem?.Collection?.ID) ?? filters[0];
+                        });
+
+                        // Trigger an external re-filter if the current item was in the change set.
                         RequestFilter?.Invoke();
+                        break;
+                    }
                 }
             }
         }

```

### Discussed in https://github.com/ppy/osu/discussions/24312

<div type='discussions-op-text'>

<sup>Originally posted by **ebolite** July 21, 2023</sup>
I have a ton of collections to sort my maps with. The issue is every time I add a map to a collection, it scrolls all the way back up to the top for some reason. It would be cool if it didn't do that so I could easily put a map in multiple collections.

https://github.com/ppy/osu/assets/22662047/c507ba15-ef4e-4a97-95eb-98fec640b214

</div>

### PR DESCRIPTION
**Pull request by frenzibyte**
- [x] Depends on https://github.com/ppy/osu-framework/pull/6061
- [x] Depends on framework bump
- Closes https://github.com/ppy/osu/issues/24315

Preview:

https://github.com/ppy/osu/assets/22781491/ccfe002b-fd10-4fce-9928-192c9941bf5d

### CODE REVIEW

**Comment by bdach** [comment]
I do not know how to fix the failing tests here.

They are failing because they were relying on drawable menu items being iterated through and returned by `.ChildrenOfType<>` in the same order as they are displayed. Due to the usage of `{Get,Set}LayoutPosition()` framework-side to reorder the items, this is not the case anymore.

The following abomination "fixes the test":

```diff
diff --git a/osu.Game.Tests/Visual/SongSelect/TestSceneFilterControl.cs b/osu.Game.Tests/Visual/SongSelect/TestSceneFilterControl.cs
index 00a0d4a849..f4c39af297 100644
--- a/osu.Game.Tests/Visual/SongSelect/TestSceneFilterControl.cs
+++ b/osu.Game.Tests/Visual/SongSelect/TestSceneFilterControl.cs
@@ -250,6 +250,11 @@ private IconButton getAddOrRemoveButton(int index)
         });
 
         private IEnumerable<Dropdown<CollectionFilterMenuItem>.DropdownMenu.DrawableDropdownMenuItem> getCollectionDropdownItems()
-            => control.ChildrenOfType<CollectionDropdown>().Single().ChildrenOfType<Dropdown<CollectionFilterMenuItem>.DropdownMenu.DrawableDropdownMenuItem>();
+        {
+            var dropdown = control.ChildrenOfType<CollectionDropdown>().Single();
+            var dropdownMenu = dropdown.ChildrenOfType<SearchContainer<Menu.DrawableMenuItem>>().Single();
+            return dropdown.ChildrenOfType<Dropdown<CollectionFilterMenuItem>.DropdownMenu.DrawableDropdownMenuItem>()
+                           .OrderBy(drawableItem => dropdownMenu.GetLayoutPosition(drawableItem));
+        }
     }
 }

```

but I will not be caught alive committing such atrocities to source, even if for test purposes. To state that this violates encapsulation would be a understatement the size of Jupiter.

I am rather disappointed that this was apparently either not caught at development time, or not signposted and warned against appropriately. I would consider running tests that cover the specific modified dropdown to be a bare minimum.

@frenzibyte Any bright ideas?

**Comment by frenzibyte** [comment]
I do not believe this is easily resolvable framework-side. It is expected behaviour from the lack of inserting a drawable between a container's children.

Given that specific code snippet, I would've queried for `FillFlowContainer<DrawableMenuItem>` and used the `FlowingChildren` property. But that being said, `Menu` already exposes a `Children` property, and that is not ordered by layout currently, so...

I'll push framework-side changes accordingly.

**Comment by bdach** [comment]
> I do not believe this is easily resolvable framework-side. (...) I'll push framework-side changes accordingly.

Which is it? And what would the changes be?

If it's going to be sorting `Children` in any way, then I dunno. I might just prefer the other thing instead, namely

> Given that specific code snippet, I would've queried for `FillFlowContainer<DrawableMenuItem>` and used the `FlowingChildren` property.

**Comment by frenzibyte** [comment]
Please disregard what I said about making a framework-side change, I misunderstood your original comment/intent. The `FlowingChildren` method should do for now until something major comes off.

**Comment by bdach** [comment]
I wrote this

```csharp
        private IEnumerable<Dropdown<CollectionFilterMenuItem>.DropdownMenu.DrawableDropdownMenuItem> getCollectionDropdownItems()
            => control.ChildrenOfType<CollectionDropdown>().Single().ChildrenOfType<SearchContainer<Menu.DrawableMenuItem>>().Single().FlowingChildren
                      .Cast<Dropdown<CollectionFilterMenuItem>.DropdownMenu.DrawableDropdownMenuItem>();
```

and it still fails 4 tests while my original workaround above fails none.

I'll leave it to you to figure out as I do not wish to spend any more time on this at present.

**Comment by frenzibyte** [comment]
Tests should be fixed with the above change. However, it contains a work around for an issue that is resolved by https://github.com/ppy/osu-framework/pull/6079. I've made it a workaround as to not require an extra framework release, but the workaround can be reverted by just following the comment there and use `Items` instead of `ItemsSource` (once the mentioned PR is merged).

**Review by peppy — APPROVED** [review]

**Pull request merged**
