### PR TITLE
Add character limit to chat text box

### LINKED ISSUE #21330: Add length limit to chat text box
Currently there is no length limit applied client-side, and any message that exceed the server-side limit will get thrown away. Ideally such errors would be elegantly handled and the message would be returned back to the user, but I've attempted at least adding a client-side length limit of 100 characters (which is the default value from web source), and I wasn't if that's what the web currently has (it's envvar-based, and it seems to exceed 100 characters).

### Discussed in https://github.com/ppy/osu/discussions/21245

<div type='discussions-op-text'>

<sup>Originally posted by **developomp** November 15, 2022</sup>
When I try to send a lengthy message in the osu!lazer client, it clears the text input regardless of whether the message was successfully delivered or not, forcing me to retype the whole thing. Adding a character length limit feature and doing the following for message input area would feel like a much better user experience in my opinion:

1. When a user sends a message, lock the text input.
2. If the message is successfully delivered, clear the text input. Notify user otherwise (give the text input a little shake maybe).</div>

### PR DESCRIPTION
**Pull request by andrewhong04**
Just a one-line change...
Animation

Fixes: https://github.com/ppy/osu/issues/21330

### CODE REVIEW

**Comment by loma-baldsson** [comment]
where does the 100-char limit come from? is it in the docs for the chat endpoint or something?

**Comment by novialriptide** [comment]
> where does the 100-char limit come from? is it in the docs for the chat endpoint or something?

Not sure, but the 100-character limit is correct, as sending a message with 101 characters returns an error.

**Comment by bdach** [comment]
Yeah no I'm not super sure about doing things this way after a brief peek in web source.

The max length of chat messages is driven by [this envvar](https://github.com/ppy/osu-web/blob/7d89312883198ebb8ba57d6afc5319db9fcc05b2/config/osu.php#L80), which does seem to default to 100. *Buuuuut* this limit [does not apply to announce channels](https://github.com/ppy/osu-web/blob/571a3645e9358e61198b24d5fb9c4ea2ce22a60c/app/Models/Chat/Channel.php#L419) which get to use the full width of the DB column of 1024. I guess for now users actually cannot send messages to announcement channels via lazer at all (even if they have the correct perms), but the fact that this is driven by an envvar that potentially changes makes me really wary of hardcoding the default client-side. I'd be happiest if this was somehow exposed via API as a channel property or something.

**Comment by novialriptide** [comment]
It seems that I would need to go in a different direction of how to implement this change, I'll close this PR for now and open a new one according to bdach's change request.

**Pull request closed without merging**
