### PR TITLE
Rename `BeatmapInfo` variables which were named `beatmap` for clarity

### PR DESCRIPTION
**Pull request by peppy**
This is a cleanup step which renames variables which make the type ambiguous, in a hope to better separate usages.

I am pushing forward with another PR chain that moved all read/writes of `Beatmap<T>.BeatmapInfo.BaseDifficulty` to `Beatmap<T>.Difficulty`. With this change doing a text search for usages of `BaseDifficulty` more easily shows which are incorrect. This helped greatly with knowing when a component is using a `BeatmapInfo` or an `IBeatmap`. A preview of these changes can be found [here](https://github.com/ppy/osu/commit/6e9b843792fbfae1456dd1c72ec5b5019a9fcf32) if that adds any context.

### CODE REVIEW

**Comment by bdach** [comment]
Just so that I understand the intent better, was this supposed to catch absolutely all fields/members that look like:

```csharp
BeatmapInfo beatmap;
```

or just the selected confusing usages? If it's the former, then I'm still seeing some left:

2021-10-02-164145_510x818_scrot

**Comment by peppy** [comment]
Intended to cover all. I'll do another pass - I thought I already got the ones in your screenshot.

**Comment by peppy** [comment]
Turns out there were actually a lot more. I was focussed on the cases which were causing confusion in my follow-up changes, but maybe it's best to blanket change all? I've pushed a commit with all remaining cases covered, see what you think.

**Comment by bdach** [comment]
I think I prefer blanket change because if we're going to be separating usages based on that then blanket renaming helps in reviewing (like the `BaseDifficulty` text based search example brought up in the OP).

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
