### PR TITLE
Storyboards implementation.

### PR DESCRIPTION
**Pull request by Damnae**

### CODE REVIEW

**Comment by peppy** [comment]
Getting a crash on https://osu.ppy.sh/s/8023:

windows_10

**Comment by Damnae** [comment]
Fixed it.

I also implemented loops, but since adding transforms removes transforms on the same property that come later, it probably won't work everywhere...

**Comment by Damnae** [comment]
Should be ready to be reviewed. I left triggers, samples and integrating it with the game for later, but all storyboards I tested were working (~30).

**Comment by peppy** [comment]
I'd consider renaming:
`StoryboardDefinition` → `Storyboard`
`Storyboard` → `DrawableStoryboard`
as this is more in line with the rest of our model/view representations.

**Review by peppy — APPROVED** [review]
looking good

**Comment by peppy** [comment]
@Damnae Let me know if you're interested in a bounty for this PR. The scale and implementation quality is definitely worthy of compensation.

**Comment by Damnae** [comment]
@peppy That would be great, thanks!

**Comment by peppy** [comment]
Awarding $800 in bounty for this. Contact me via email with a paypal account (or osu! supporter tags or whatever if you'd prefer).

**Pull request merged**
