### PR TITLE
Rename `GameType` to `MatchType` and make `enum` instead of `class`

### PR DESCRIPTION
**Pull request by peppy**
This can be merged separately from other multiplayer related changes. Note that the naming/structure may be altered depending on discussion at https://github.com/ppy/osu-web/issues/7962, but this PR should allow me to continue to refactor the other mutliplayer PR efforts forward regardless.

### CODE REVIEW

**Comment by peppy** [comment]
Note that `MatchType` here will replace `MatchRulesetType` used in https://github.com/ppy/osu/pull/14104.

**Comment by smoogipoo** [comment]
Crashes when creating a multiplayer room:
```
Unhandled exception. System.Collections.Generic.KeyNotFoundException: The given key 'Playlists' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at osu.Framework.Graphics.UserInterface.TabControl`1.<LoadComplete>b__45_0(ValueChangedEvent`1 v)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
   at osu.Framework.Bindables.Bindable`1.set_Value(T value)
   at osu.Game.Screens.OnlinePlay.Multiplayer.Match.MultiplayerMatchSettingsOverlay.MatchSettings.<load>b__38_3(ValueChangedEvent`1 type) in /home/smgi/Repos/osu/osu.Game/Screens/OnlinePlay/Multiplayer/Match/MultiplayerMatchSettingsOverlay.cs:line 272
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.TriggerValueChange(T previousValue, Bindable`1 source, Boolean propagateToBindings, Boolean bypassChecks)
   at osu.Framework.Bindables.Bindable`1.SetValue(T previousValue, T value, Boolean bypassChecks, Bindable`1 source)
   at osu.Framework.Bindables.Bindable`1.set_Value(T value)
```
Remote type is coming in as `Playlists`, which is being copied to the local room, which then attempts to set that item in the game type selector that doesn't contain a `Playlists` item:
image

**Comment by peppy** [comment]
Unfortunate. Maybe best to hold off on merging this until the osu-web changes are done.

**Comment by peppy** [comment]
I've added back the `Playlists` item to the picker for now to avoid the crash.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
