### PR TITLE
Fix possible nullref when exiting song select too fast

### LINKED ISSUE #11511: Multiplayer nullref when pressing escape
**Describe the crash:** Pressing the <kbd>ESC</kbd> key during the transition between song selection and match settings causes the game to return a `System.NullReferenceException`.

If you keep pressing any key with the notifications overlay open, the game may return other errors and may crash with an `NUnit.Framework.AssertionException` (not shown in the video).

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/43073074/104812118-630d6a80-5800-11eb-81ed-9de98ad860f4.mp4

**osu!lazer version:** 2021.109.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/5824375/runtime.log)

### PR DESCRIPTION
**Pull request by smoogipoo**
Fixes https://github.com/ppy/osu/issues/11511

### CODE REVIEW

**Comment by peppy** [comment]
Is this because the `BackButton` is made visible before song select is finished loading?

**Comment by peppy** [comment]
If so, we may want to consider a different fix, or better documentation of this quirk as it looks like it will fail in at least one other location:

https://github.com/ppy/osu/blob/b2c736b42a52c91f8780ad00602a0dd18d1e6b83/osu.Game/Screens/Ranking/ResultsScreen.cs#L273-L275

**Comment by smoogipoo** [comment]
Yeah, well the `BackButton` is global inside `OsuGame` and takes effect as soon as a screen is pushed that enables it.

**Comment by smoogipoo** [comment]
Any recommendations? One alternative is to always exit if `!IsLoaded`, does that sound better? It would match up to `OnEntering()` (only called on `LoadComplete`) and `OnExiting()` (only called if `IsLoaded`).

**Comment by peppy** [comment]
Yeah I think that makes more sense (not calling `OnBackButton` at all). Probably mention this case in the interface documentation too.

**Comment by smoogipoo** [comment]
Also discovered that this didn't fix the original case because multiplayer has its own flow of redirecting the `OnBackButton` call >_>

**Review by peppy — APPROVED** [review]

**Pull request merged**
