### PR TITLE
Timing screen more updates

### PR DESCRIPTION
**Pull request by peppy**
Refined design a bit more with help from @arflyte.

https://user-images.githubusercontent.com/191335/115213638-ae575200-a13c-11eb-8bb2-b957c78a11a7.mp4

### CODE REVIEW

**Comment by smoogipoo** [comment]
image

The padding on the right should probably be a bit larger

**Comment by smoogipoo** [comment]
Related to the previous PR, but probably something to fix here. Crashes on this map: https://osu.ppy.sh/beatmapsets/954839#osu/1993340

```
[runtime] 2021-04-19 09:56:18 [error]: System.ArgumentNullException: Value cannot be null. (Parameter 'element')
[runtime] 2021-04-19 09:56:18 [error]: at System.Attribute.GetCustomAttributes(MemberInfo element, Type type, Boolean inherit)
[runtime] 2021-04-19 09:56:18 [error]: at System.Attribute.GetCustomAttribute(MemberInfo element, Type attributeType, Boolean inherit)
[runtime] 2021-04-19 09:56:18 [error]: at System.Reflection.CustomAttributeExtensions.GetCustomAttribute[T](MemberInfo element)
[runtime] 2021-04-19 09:56:18 [error]: at osu.Framework.Extensions.ExtensionMethods.GetDescription(Object value)
[runtime] 2021-04-19 09:56:18 [error]: at osu.Game.Screens.Edit.Timing.RowAttributes.TimingRowAttribute.updateText() in /home/smgi/Repos/osu/osu.Game/Screens/Edit/Timing/RowAttributes/TimingRowAttribute.cs:line 43
[runtime] 2021-04-19 09:56:18 [error]: at osu.Game.Screens.Edit.Timing.RowAttributes.TimingRowAttribute.<load>b__4_1(ValueChangedEvent`1 _) in /home/smgi/Repos/osu/osu.Game/Screens/Edit/Timing/RowAttributes/TimingRowAttribute.cs:line 39
[runtime] 2021-04-19 09:56:18 [error]: at osu.Game.Screens.Edit.Timing.RowAttributes.TimingRowAttribute.load() in /home/smgi/Repos/osu/osu.Game/Screens/Edit/Timing/RowAttributes/TimingRowAttribute.cs:line 39
```

**Comment by peppy** [comment]
That's worrying, since `.GetDescription` is supposed to guard against all fail cases.. probably worth a framework fix. I'm guessing it falls over when the item is not actually in the enum.

**Comment by smoogipoo** [comment]
I've fixed it framework-side, merging this.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
