### PR TITLE
Add a global reduction of audio track volume

### PR DESCRIPTION
**Pull request by peppy**
Music is overpowering compared to our current game samples. We will need to do further adjustments on this, but for now let's reduce the track volume globally.

### CODE REVIEW

**Comment by smoogipoo** [comment]
I think there are better things to do than to hack this in.

**Comment by peppy** [comment]
such as?

**Comment by smoogipoo** [comment]
Not doing this, because this will never be properly fixed up. There's no issue thread, no todo message and no considerations for gameplay/editor.

The issue should be fixed at the samples themselves, the game should not be hacked around the samples.

**Comment by peppy** [comment]
Samples normalised to the highest volume levels possible couldn't provide the results I'm after. Music playback is too variable. Eventually we will address this with replaygain support or similar, but this is required for now.

**Review by smoogipoo — APPROVED** [review]
You will need to make an issue to implement ReplayGain or similar, because this can't exist going into public release.

**Comment by peppy** [comment]
already did (see https://github.com/ppy/osu/issues/1600). we can revisit once that's done (may still need some level of track reduction or amplification to balance levels, we'll see).

**Pull request merged**
