### PR TITLE
Improve multiplayer ready button/countdown button UX

### PR DESCRIPTION
**Pull request by smoogipoo**
Prereqs:
- [x] https://github.com/ppy/osu/pull/17402

### CODE REVIEW

**Comment by peppy** [comment]
I've updated tests and made some changes to the UI to hopefully feel better. If all is good I'd like to get this in an initial feature release this weekend.

**Comment by smoogipoo** [comment]
Looks good

**Comment by bdach** [comment]
With regard to the ready button behaviour alone, I've managed to find one edge case, namely that I can set a countdown, then change room to autostart, which will not stop the countdown but the UI will no longer let me stop it:

https://user-images.githubusercontent.com/20418176/160250371-d6dc5589-896a-4413-af7d-6bd767c24fd9.mp4

That said, I think that changing the room to autostart should stop any ongoing countdowns, which would make this out of scope. Not sure on everyone else's thoughts, though.

**Comment by frenzibyte** [comment]
> That said, I think that changing the room to autostart should stop any ongoing countdowns, which would make this out of scope (because that needs to happen on the server side). Not sure on everyone else's thoughts, though.

I definitely agree with that. On a similar topic, I find it slightly wrong that the auto-start functionality doesn't cancel when all players are no longer ready. Since no match can actually be started that way.

**Comment by bdach** [comment]
> I find it slightly wrong that the auto-start functionality doesn't cancel when all players are no longer ready. Since no match can actually be started that way.

seems like that was explicitly intended judging from [this discord message](https://discord.com/channels/188630481301012481/188630652340404224/956814668981227570), although i can't say i know the reason for this.

**Comment by peppy** [comment]
Seems like the countdown should restart with the auto duration in the flow above.

> > I find it slightly wrong that the auto-start functionality doesn't cancel when all players are no longer ready. Since no match can actually be started that way.
> 
> seems like that was explicitly intended judging from [this discord message](https://discord.com/channels/188630481301012481/188630652340404224/956814668981227570), although i can't say i know the reason for this.

Personally I felt this.. feels better? The game still won't start if no players are ready, but the countdown continuing is I guess because there are players non-AFK (ie. they toggled ready once). I'm open to change this in the future if we get feedback saying it doesn't feel good.

**Comment by peppy** [comment]
Going to get this in as-is. I agree the above issue should be fixed but that can be done at a slightly later point in time.

**Pull request merged**
