### PR TITLE
Add 'Paste' to `OsuTextBox` right click/long tap context menu

### PR DESCRIPTION
**Pull request by Susko3**
- Partially resolves https://github.com/ppy/osu/discussions/22565
- Resolves https://github.com/ppy/osu/discussions/15346

**Depends on:**
- [ ] https://github.com/ppy/osu/pull/24183 (for tests / mergeability)

Since using `IHasContextMenu` requires a parent `OsuContextMenuContainer`, right click to paste doesn't work in all text boxes. Instead of nesting text boxes in `OsuContextMenuContainer` everywhere, I've only added it to places where user account passwords are entered.

Only paste is added (so no copy/cut) as that's most important. Additionally, having `Copy` doesn't really work, as the selection changes from the right click (would require a framework change) and opening the context menu removes focus from the text box, rendering the selection invisible (bad UX).

### CODE REVIEW

**Comment by frenzibyte** [comment]
Any reason this isn't added over at osu-framework instead?

**Comment by Susko3** [comment]
> Any reason this isn't added over at osu-framework instead?

Could be added, but then localisation and making it highlighted would be harder. But the pasting logic could be moved to a helper function framework-side. Would make it easier to change it if adjustments are needed in the future.

Localisation would be something similar to this horrible mess:
```cs
        public override MenuItem[]? ContextMenuItems
        {
            get
            {
                var items = base.ContextMenuItems;
                if (items == null)
                    return null;

                items.First(i => i.Text.Value == @"Paste").Text.Value = CommonStrings.Paste;

                return items;
            }
        }
```

**Comment by bdach** [comment]
Real mixed feelings from me on this one...

On one side, I'd argue that attaching context menus to all textboxes ever framework-side is overkill and shouldn't be done, because I don't think all textboxes need copy/paste controls - and I don't think they should be _forced_ onto arbitrary framework consumers. Unless you do it behind a flag, but _yuck_.

On the other side, monkey patching context menu containers just to have paste work game-side is similarly teeth-pain-inducing, especially so now that we're monkey patching them _specifically_ for mobile purposes but in a while we'll get desktop users asking why every textbox isn't pastable via context menu...

On the _third_ side, I don't know what software keyboards the users reporting problems have installed, but I'm pretty sure I'm using google default on my android device, and the software keyboard supports paste via keyboard IME which makes me sorta partial to just... not doing anything about this?

Dunno. I basically see no good way out of this. Unless we figure out some way to basically fake android's hold-to-copy behaviour I guess.

**Comment by frenzibyte** [comment]
I don't see any reason placing this here in osu! IMO. It's a feature that makes sense to exist basically anywhere where there's text that can be selected, and it's added specifically to aid mobiles for better copy/paste UX, which is a feature that every framework consumer would need. Further more, there is already an issue thread tracking something similar to this for iOS in osu!framework (https://github.com/ppy/osu-framework/issues/3491, see https://github.com/ppy/osu-framework/issues/3491#issuecomment-620693398).

For localisation, having [this](https://github.com/ppy/osu/pull/24184#issuecomment-1630684895) doesn't sound that "horrible" to me, if you want a better approach you could expose some place where the framework sources its strings from and games would map them to their own localisation sources (say an abstract `FrameworkStrings` class with implementation osu! side that maps to an actual crowdin-based strings).

For context menu containers, see https://github.com/ppy/osu/pull/23334#discussion_r1241707352, at this point this feature is really just asking to add a global context menu container, period.

**Comment by peppy** [comment]
Disagree with this direction. Should be on every textbox. This is a standard feature that all users expect to exist in a UI framework.

We should also revisit a global context menu container, potentially at a game level, to make this work without having one local to each textbox.

**Comment by bdach** [comment]
Since this changeset is pretty much universally disagreed with and it doesn't seem that much of it can be salvaged, I'm going to close this for now.

**Pull request closed without merging**
