### PR TITLE
Add aliases "author" and "mapper" for creator results

### PR DESCRIPTION
**Pull request by Stoppedpuma**
Allows "author" and "mapper" to show the results of "creator"

https://github.com/ppy/osu/assets/58333920/5b0ce81e-7f0e-4ef7-88f8-ea153b7dfe27

Resolves #27101

### CODE REVIEW

**Review by smoogipoo — DISMISSED** [review]

**Comment by bdach** [comment]
I am very confused by this.

https://github.com/ppy/osu/discussions/27101#discussioncomment-8425412 claims that the website uses `author` but.... [it doesn't](https://github.com/ppy/osu-web/blob/e9b555b7955649aac19e2db01eea083607c24280/app/Libraries/Search/BeatmapsetSearchRequestParams.php#L214-L233)?

Stable [also uses `creator`](https://github.com/peppy/osu-stable-reference/blob/46cd3a10af7cc6cc96f4eba92ef1812dc8c3a27e/osu!/GameModes/Select/SongSelection.cs#L2340-L2341).

On the face of it I don't see why this shouldn't be supported, but everyone in the discussion thread seems to be mightily confused.

**Comment by tsunyoku** [comment]
I think people are confused because typing `author=Sotarks` (as an example) does filter to only Sotarks beatmaps, but it's clear to see this is just due to the search engine as `authr=Sotarks` or even just typing `Sotarks` has the same result. I imagine some people just used `author=` by habit and assumed it was intended behaviour.

**Comment by bdach** [comment]
Yeah everything has been explained in the discussion thread.

We can probably allow this and also `mapper=`, but the same change should be applied to web.

**Review by bdach — APPROVED** [review]

**Review by Joehuu — APPROVED** [review]
`mapper` may be used to filter [guest difficulties](https://osu.ppy.sh/wiki/en/Beatmap/Guest_difficulty) instead of the "[host](https://osu.ppy.sh/wiki/en/Beatmap/Beatmap_host)" (another alias?) in this case, but we don't have that data stored yet so LGTM.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
