### PR TITLE
Fix mania scroll direction not being initially set correctly

### PR DESCRIPTION
**Pull request by smoogipoo**

### CODE REVIEW

**Comment by peppy** [comment]
Might be a good idea a couple of quick tests for this in `ScrollingTestContainer` and `TestCaseEditor` (or just one if you think that's enough). they both already have the bindable flow setup.

**Comment by smoogipoo** [comment]
Testing what in particular? That bindable propagation is working? That config binding is working? Both of these are, of course, tested elsewhere. The flipping of the playfield itself is tested in every single mania testcase.

**Comment by peppy** [comment]
Yeah, just testing config -> column propagation.

**Comment by smoogipoo** [comment]
Disagree with writing tests for bindable propagation failure. Again, there's a visual test for everything in mania - notes, columns, and stages.

I put in some automated tests for notes, because that's actually new non-previously-tested logic.

But we cannot be writing tests for when issues are coding (or in this case, literally copy-paste) errors. It's redundant. If you wanted that then you would have to argue for testing that a button's colour is pink because someone missed the `Colour = Color4.Pink` line during copy-paste and it regressed.

**Review by peppy — APPROVED** [review]

**Pull request merged**
