### PR TITLE
Add "triangle particle size" setting

### PR DESCRIPTION
**Pull request by Blifaloo**
Comment: Woops I dont know how to use github

- In [Path](https://github.com/ppy/osu/blob/master/osu.Game/Graphics/Backgrounds/Triangles.cs) you can change the triangle size to 0 which makes them invisible.
- I don't know how to create a setting in the osu framework.

---
- Added triangle particle scale setting 
ezgif-1-a3b928f98a

### CODE REVIEW

**Comment by Blifaloo** [comment]
In my opinion the triangle particles distract me when playing the game.

**Comment by peppy** [comment]
That's what skins are for.

**Comment by Blifaloo** [comment]
Wait so you're going to be able to skin the particle to something invisible?

**Comment by HoutarouOreki** [comment]
IIRC the triangles don't appear after changing the skin (not sure). You can already drop .osks into lazer.

**Comment by peppy** [comment]
In the menus: no. In gameplay: yes, you already can.

**Pull request closed without merging**
