### PR TITLE
Allowing keypad enter to be used along with normal enter

### LINKED ISSUE #3717: Second enter on the keyboard doesn't start map.
On stable it does.
a

### PR DESCRIPTION
**Pull request by Scotsoo**
Add any details pertaining to developers above the break.

- Closes #3717 

---

Allows keypad enter to be used along side keyboard enter

### CODE REVIEW

**Comment by Scotsoo** [comment]
These tests are failing on my local even without this change added, is master okay?

**Comment by Scotsoo** [comment]
I have ver "2018.1112.0" pulled

**Comment by morguldir** [comment]
I think this should be fixed in osu-framework like below.
https://github.com/ppy/osu-framework/blob/a7e32b182c9f7db25673d6ab0ca8d9a31311824d/osu.Framework/Input/Bindings/KeyCombination.cs#L227-L239

**Comment by peppy** [comment]
Not sure which fix is more correct / preferred. @smoogipoo thoughts on this?

**Comment by smoogipoo** [comment]
Yeah I didn’t merge this since I wasn’t sure about it either... Have to check how it behaves in non-text input scenarios, such as pressing enter to open stuff on desktop.

**Comment by Scotsoo** [comment]
@smoogipoo any updates on this?

**Comment by smoogipoo** [comment]
Haven't had time to test how this interaction works in the OS.

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
Based on some discussions IRL and in twitter, I think it’s fine to go ahead with this change. We don’t want to combine the definition of enter/return at a framework level as the user may want to bind the keys to different actions.

We may also want to add similar action/bindings at a framework `PlatformAction` level.

**Comment by OussamaDanba** [comment]
Not sure if it's worth opening a new issue for but the keypad enter can after this PR still not be used to select options in the pause and fail screens since they're not subclasses of GlobalContainer.

**Comment by peppy** [comment]
Yes, `GameplayMenuOverlay` needs to be updated to support `GlobalAction`.

**Pull request merged**
