### PR TITLE
Change VSCode build task args to use - instead of /

### LINKED ISSUE #10721: VSCode Build Tasks don't work in git bash
**Describe the bug:** 
The build tasks in tasks.json don't work when using git bash (that comes with git for Windows) as a terminal because the arguments use / instead of -

**osu!lazer version:** 
Latest master.

**Logs:**
```
> Executing task: dotnet build --no-restore osu.Desktop /p:Configuration=Release /p:GenerateFullPaths=true /m /verbosity:m <

Microsoft (R) Build Engine version 16.4.0+e901037fe for .NET Core
Copyright (C) Microsoft Corporation. All rights reserved.        

MSBUILD : error MSB1008: Only one project can be specified.
Switch: p:Configuration=Release

For switch syntax, type "MSBuild -help"
The terminal process "C:\Program Files\Git\bin\bash.exe '-c', 'dotnet build --no-restore osu.Desktop /p:Configuration=Release /p:GenerateFullPaths=true /m /verbosity:m'" terminated with exit code: 1.
```

### PR DESCRIPTION
**Pull request by nbvdkamp**
Resolves #10721 

I've tested this on Windows in cmd, powershell and git bash and on linux in regular bash.

### CODE REVIEW

**Comment by Joehuu** [comment]
Needs to be done on other `tasks.json`s in this repo (e.g. https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Osu.Tests/.vscode/tasks.json).

**Comment by peppy** [comment]
Not 100% on this solution, but here's more information on the issue: https://stackoverflow.com/a/51171516

Provides two alternatives we may consider.

**Comment by nbvdkamp** [comment]
Using two slashes works in git bash but gives
```
MSBUILD : error MSB1001: Unknown switch.
Switch: //p:GenerateFullPaths=true

For switch syntax, type "MSBuild -help"
The terminal process "C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe -Command dotnet build --no-restore osu.Desktop //p:GenerateFullPaths=true //m //verbosity:m" terminated with exit code: 1.
```
in powershell. There's no spaces or quotes in any of the arguments so I'm not sure what other alternative you mean.

**Comment by peppy** [comment]
One option is to fix this locally (see https://github.com/git-for-windows/build-extra/blob/a9090580ee37686a53166796dffda531041e16f8/ReleaseNotes.md)

I'm not sure we should be working around this behaviour locally. If we are to do so, this needs to also be applied on about 10 other repos we have. I'm not sure enough people using git-bash as their terminal in vscode to warrant this.

**Comment by bdach** [comment]
Given that even [Microsoft docs](https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-command-line-reference?view=vs-2019) specify the posix-like `-p` switch syntax instead of the traditional windows-style `/p` one, I think I'd actually be in favour of this version as it looks to be more portable overall.

**Comment by peppy** [comment]
If it's preferred then I'm definitely fine with swapping, just want to check it's the correct direction first (and apply to other projects).

**Review by peppy — APPROVED** [review]

**Pull request merged**
