### PR TITLE
Remove old chat overlay components

### PR DESCRIPTION
**Pull request by jai-x**
Part of #17001

Goodbye old chat :wave:

### CODE REVIEW

**Review by smoogipoo — APPROVED** [review]
Would probably have gone with renaming the V2 components in this PR.

**Comment by peppy** [comment]
> Would probably have gone with renaming the V2 components in this PR.

came to ask why this wasn't done

**Comment by bdach** [comment]
Probably to make the diff read not-horribly. Rename should be done as a follow up to this, though.

**Comment by jai-x** [comment]
Yeah, didn't do the rename because it would make the PR diff harder to read and this change is already very big.

**Comment by peppy** [comment]
I dunno. Removing lines is a noop. Separate commits is all that is required IMO.

**Comment by bdach** [comment]
If you're fine viewing separate commits rather than the full diff, then splitting commits works. Otherwise git isn't going to figure out that one file was dropped in place of another and it'll show as if you essentially rewrote the file.

**Pull request merged**
