### PR TITLE
Interpolate legacy slider body colours with old "gamma-incorrect" algorithm

### LINKED ISSUE #14165: Incorrect legacy slider body transparency fade out
**Describe the bug:** The latest update changed the legacy slider body incorrectly.

**Screenshots or videos showing encountered issue:**

Previously (2021.731.0):

Currently (2021.808.0):

**osu!lazer version:** 2021.808.0

### PR DESCRIPTION
**Pull request by TheOmyNomy**
Resolves #14165

Stable doesn't use linear space / gamma-correct colour interpolation for slider bodies, and because of a recent framework change that implements such interpolation (see: https://github.com/ppy/osu-framework/pull/4657/), legacy slider bodies now look incorrect.

This PR adds the `ValueAt()` method before the linear space change to a new `LegacyUtils` class as `InterpolateNonLinear()`. This method is then used to bring the legacy slider bodies back in line with stable / how they were before.

### CODE REVIEW

**Comment by bdach** [comment]
I'm not sure why this was PR'd without discussion. I know what the fix is, and if I thought it wasn't going to be up for discussion, I would have done this already.

We need to figure out if and how the framework function should handle sRGB/linear interpolation.

**Comment by smoogipoo** [comment]
I think I’d implement this as .ToSrgb()ing the source colours and .ToLinear()ing the resultant colour. Just as a general case rule for when this inevitably comes up again in legacy skinning.

**Comment by bdach** [comment]
I suppose I could be fine with that resolution, but there are other usages in [`DrawableDrumRoll`](https://github.com/ppy/osu/blob/c8a0b6058f4ba5db1fd79707a5c6fd030997cfd7/osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableDrumRoll.cs#L173) and [`LegacyHealthDisplay`](https://github.com/ppy/osu/blob/c8a0b6058f4ba5db1fd79707a5c6fd030997cfd7/osu.Game/Skinning/LegacyHealthDisplay.cs#L83-L92) that look to also require this workaround, so I'm not sure whether that should be done locally instead of via a helper or even via `Interpolation.ValueAt()`, but with an added parameter indicating the space in which the interpolation should take place.

**Comment by frenzibyte** [comment]
I was thinking of making it like the D3 way, by adding a `gamma` parameter in the colour transforms that's set to the default `2.4`, and allow changing it to `1f` for no gamma correction. But not sure if framework should allow anything other than `2.4` and no gamma correction.

I think making it a `LegacyColourInterpolation` utility locally and defining transform methods based on it should be fine for now, then expand further if consumers do want that.

**Comment by peppy** [comment]
I'm fine with any solution that is in one place. Probably fine to add this at the framework side with an `InterpolateIncorrect` function or similar. Or the fully gamma spec if that's decided to be actually beneficial (sounds like wasted time to me, though).

I'm even okay with a local function in `LegacyUtils` class or similar, since that's the only time we're going to be using it.

**Comment by frenzibyte** [comment]
Missing legacy interpolation in the other components mentioned in https://github.com/ppy/osu/pull/14172#issuecomment-894811698.

**Comment by TheOmyNomy** [comment]
I've changed `LegacyHealthDisplay` to use non linear colour interpolation, however I'm unsure how to proceed with [`DrawableDrumRoll`](https://github.com/ppy/osu/blob/c8a0b6058f4ba5db1fd79707a5c6fd030997cfd7/osu.Game.Rulesets.Taiko/Objects/Drawables/DrawableDrumRoll.cs#L173) because the interpolation is done for both lazer and legacy skinning.

**Comment by smoogipoo** [comment]
I think it's fine not to be applied to drum rolls until it's brought up. The current implementation doesn't match stable anyway, so it can potentially be implemented when that's done.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
