### PR TITLE
Fix quit button test occasionally failing

### PR DESCRIPTION
**Pull request by peppy**

### CODE REVIEW

**Comment by smoogipoo** [comment]
Solution to fix a failing test is to remove the test? Nope.

Attach a local decoupleable framed clock to the hierarchy instead.

**Comment by peppy** [comment]
The test was pointless, just a remnant of the previous owner of the code.

**Comment by smoogipoo** [comment]
Pointless how? Because it was a simple scenario that you could think of off the top of your head? What if the logic is changed incorrectly in the future?

**Comment by peppy** [comment]
We can't start testing every transform sequence every instance it is present. It would get completely redundant. Have to focus on actual interaction tests.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
