### PR TITLE
Don't change Beatmap while bindable is disabled

### LINKED ISSUE #1719: Searching in SongSelect and pressing Enter too fast crashes the game
If you enter your search term in SongSelect and immediately press ENTER before the animation is done the game crashes:
qq
qq

### PR DESCRIPTION
**Pull request by FreezyLemon**
I found a better fix than just checking for the `Disabled` flag on the `Bindable`.
This definitely fixes #1719 and possibly #1757 (I wasn't able to reproduce it with this in place, but then again, it was difficult for me to even get that one to throw without it).

### CODE REVIEW

**Comment by peppy** [comment]
SongSelect shouldn't need to know about its current child. Also this doesn't fix many other scenarios which come up. We need to have it decide on actions based on the state of the bindable directly

**Comment by FreezyLemon** [comment]
Hm.. that's true. But I don't like just checking for `Bindable.Disabled` either.. maybe a custom class for the `Bindable<WorkingBeatmap>` that includes that kind of information?

**Comment by peppy** [comment]
See https://github.com/ppy/osu/pull/1788

**Comment by FreezyLemon** [comment]
Ah, alright. That looks way better 👍 .
Closing in favour of #1788

**Pull request closed without merging**
