### PR TITLE
Add the ablity to get the keyboard hight

### PR DESCRIPTION
**Pull request by Ghost1928563945**
| Sytem / Platform | Status |
|-|-|
| iOS | Done ✅ |
| Windows / Desktop | Not Done ❌ |
| Android | Not done ❌ |

This PR allows osu to get the height of the screen keyboard.

### CODE REVIEW

**Comment by bdach** [comment]
Why on earth would this be needed?

**Comment by jai-x** [comment]
@NullifiedJosh 
Could you provide some additional context to why you are adding this functionality?
Is there an existing issue or discussion thread where this functionality was requested by one of the dev team?
Additionally, if this were to be added, I would imagine this sort of thing should exist framework side, maybe inside `TextInputSource`? https://github.com/ppy/osu-framework/blob/master/osu.Framework/Input/TextInputSource.cs

**Comment by peppy** [comment]
This seems like something which needs to be resolved framework side (and may fit will with the safe area implementation?).

**Comment by NullifiedJosh** [comment]
@peppy what is the safe area implementation?

**Comment by NullifiedJosh** [comment]
I will close this issue and work on a framework implementation later.

**Comment by peppy** [comment]
> @peppy what is the safe area implementation?

Try searching for `safearea` in either the osu! or framework projects. There should be plenty to work with. If you're unfamiliar with the concept, google will help.

I'm not 100% sure it's the correct way to handle, but wouldn't be surprised if apple HIG docs don't have this covered as it's a very common scenario.

**Comment by NullifiedJosh** [comment]
> > @peppy what is the safe area implementation?
> 
> Try searching for `safearea` in either the osu! or framework projects. There should be plenty to work with. If you're unfamiliar with the concept, google will help.
> 
> I'm not 100% sure it's the correct way to handle, but wouldn't be surprised if apple HIG docs don't have this covered as it's a very common scenario.

Yes, I know about apple safe area, but I don't think this should be part of it. Maybe it should but maybe excluded.

**Comment by NullifiedJosh** [comment]
Moved to: ppy/osu-framework#5488

**Pull request closed without merging**
