### PR TITLE
Fix `ManiaModInvert` permanently destroying the beatmap

### LINKED ISSUE #28687: Select osu!mania difficulty increasing mods lowering stars (osu!lazer)
### Type

Game behaviour

### Bug description

This doesn't feel intentional, but in the mods for osu!mania the four mods that affect notes/view area (Fade In, Hidden, Cover, and Flashlight) all lower the star count despite being difficulty increasing mods. And additionally, Cover is unranked (but this might just be something I never noticed).

### Screenshots or videos

image
image
image

### Version

2024.625.2-lazer

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/16047261/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by smoogipoo**
Fixes https://github.com/ppy/osu/issues/28687

Steps to reproduce:
- Select a converted beatmap (osu! -> osu!mania).
- Select the invert mod
- Deselect the invert mod
- Select the constant speed mod.

Expected: Star rating should be equal to that of NM.
Actual: Star rating differs.

@peppy We may want a hotfix release for this (though I believe it's been broken since the mod's been introduced...).

### CODE REVIEW

**Comment by peppy** [comment]
@smoogipoo please take a look at 005af280f2ee8c05adb0bc0b5609b52eb40900fc. In addition to your changes, I've moved the bindable list portion to `EditorBeatmap` because having a bindable list replaced post-construction doesn't fill be with a lot of confidence.

**Comment by smoogipoo** [comment]
Any reason for not making it an `IReadOnlyList`, matching `HitObjects`?

**Comment by peppy** [comment]
> Any reason for not making it an `IReadOnlyList`, matching `HitObjects`?

I originally did, but I believe I ran into an issue. Let me check..

**Comment by smoogipoo** [comment]
Reverted the last two commits because they're too ugly to exist, requiring the beatmap class to be reworked in general.

**Comment by smoogipoo** [comment]
lgtm.

**Review by bdach — APPROVED** [review]

**Pull request merged**
