### PR TITLE
Changed Catch NF penalty to match Osu

### PR DESCRIPTION
**Pull request by Givikap120**

### CODE REVIEW

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=catch

**Comment by peppy** [comment]
For these kinds of changes are we waiting from pp committee approval?

**Comment by smoogipoo** [comment]
Yes, I always look for committee approval before diving into any SR/PP change. It's less effort that way.

**Review by Flawnpiece — APPROVED** [review]
I think having the NF penalty to match with std is something that would be welcomed in catch. There isn't really any downside to this change (don't think we will see any rise of abuse, and even so it will be very minimal).

**Review by Sorceress4628 — APPROVED** [review]
Seems to be a change most of the catch community is in favour of, we like this

**Review by bastoo0 — APPROVED** [review]

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
