### PR TITLE
Populate `MaximumStatistics` for scores imported into lazer

### LINKED ISSUE #20090: Viewing old/newly-imported local scores shows map's total combo as 0
To fix this, we'd need to attach `MaximumStatistics` values to legacy imported scores, similar to https://github.com/ppy/osu-queue-score-statistics/pull/76.

### Discussed in https://github.com/ppy/osu/discussions/20088

<div type='discussions-op-text'>

<sup>Originally posted by **Flamiii** September  2, 2022</sup>
This doesn't happen with new scores set on the latest version of osu!lazer, but all of my old local scores show the map's total max combo as 0 if you view it through the local leaderboard (this happens with all of my local scores regardless of mods, including ones imported from stable). If you view the same score through the global leaderboard, this doesn't happen.

Viewing the score through the global leaderboard (1651 total combo):
osu_2022-09-01_22-00-54

Viewing the score through the local leaderboard (0 total combo):
osu_2022-09-01_22-01-04
</div>

### PR DESCRIPTION
**Pull request by smoogipoo**
Resolves https://github.com/ppy/osu/issues/20090

Much the same implementation as https://github.com/ppy/osu-queue-score-statistics/pull/76.

### CODE REVIEW

**Comment by peppy** [comment]
Weird that you didn't notice the test failures when working on this... do the tests somehow trigger `async` where normal flow doesn't?

**Comment by smoogipoo** [comment]
Yeah so I was relying on the fact that imports via drag-drop come in via the import task scheduler. But calling `Import()` doesn't use that scheduler.

Kinda unfortunate because we've remove the synchronous pathway from `MemoryCachingComponent`/`BeatmapDifficultyCache`...

Thoughts? Should I `.Wait()` and call it a day? Should I implement the synchronous pathway again?

**Comment by peppy** [comment]
I'll have to have a look through this in more detail to understand it, but if `.Wait()` works (and seems safe enough) changing to that is probably best for now, with an inline comment.

**Comment by smoogipoo** [comment]
I've resolved it by using the difficulty calculator directly. It bypasses the cache but it's probably okay and imo the code is a bit cleaner.

**Comment by peppy** [comment]
It doesn't look like the `async`/`await` usage is adding anything anymore. The only usage I can see is the `await Task.Delay` call.  So it could probably be switched back unless I'm missing something?

**Comment by smoogipoo** [comment]
Think I should change it to a long running task? I feel kinda uneasy potentially having an entire TPL thread taken up for quite some time...

**Comment by peppy** [comment]
You definitely have a point. I'd prefer moving to full `async` but maybe something for another day? If it's a consolation, there's only going to be one thread used maximum, but it does feel like it may be suited to `LongRunning`.

**Comment by smoogipoo** [comment]
I've just reverted the logic for the time being. long running or full async flow can be tackled in a separate PR.

**Review by peppy — APPROVED** [review]

**Pull request merged**
