### PR TITLE
Delay loading of cover backgrounds in score panels

### PR DESCRIPTION
**Pull request by smoogipoo**
Stops firing off potentially hundreds of web reqs (with pagination).

### CODE REVIEW

**Comment by peppy** [comment]
Is there a case where this *isn't* what we want from `UserCoverBackground`? Just thinking maybe it should be applied to the class itself..

**Comment by smoogipoo** [comment]
The only other use that doesn't have this is `ProfileHeader`.

**Comment by peppy** [comment]
Sounds like we should definitely embed the behaviour if feasible..

**Review by bdach — APPROVED** [review]
looks alright to me 👍

**Review by peppy — APPROVED** [review]

**Pull request merged**
