### PR TITLE
Animate download button

### PR DESCRIPTION
**Pull request by LittleEndu**
When downloading large beatmaps on slow connection it might seem like the download didn't start. Having an animation makes it clear that the download is indeed happening.

I was told this needs actual designs though.

### CODE REVIEW

**Comment by LittleEndu** [comment]
Preview of what animation looks like right now: https://i.imgur.com/s4bkJdI.gif

**Comment by LittleEndu** [comment]
Something similar should be done for BeatmapSetOverlay

**Comment by peppy** [comment]
A more intuitive solution would be to fade or hide the button.

**Comment by LittleEndu** [comment]
I feel like just getting rid of a button here by fading or hiding it could mean "This beatmap couldn't be downloaded". At'least with the animation it's clear that you don't need to panic. 

Should really ask flyte what he thinks or someone else should give their opinion.

**Comment by peppy** [comment]
Yes, you should ask before adding things like this because otherwise it is just going to be wasted effort. I did mention this from the outset though!

**Comment by smoogipoo** [comment]
@arflyte Any input on the sort of feedback we should be giving users when an osu!direct download has started? This is an attempt at animating it, but hiding the button was suggested as an alternative.

**Comment by smoogipoo** [comment]
@arflyte once more

**Comment by LittleEndu** [comment]
Not only osu!direct but I feel like in the in-game interface everything that is loading something should have a constant  animation in addition to loading bar. Just something to add to the new new web design.

**Comment by smoogipoo** [comment]
At the moment we're against having the animation done this way - it just doesn't really look and feel good. Flyte has redesigns for the beatmap panel in the pipeline, so I think it's best to wait for that and consult with us before doing design stuff so we can make sure everyone is on the same page.

Closing for now.

**Pull request closed without merging**
