### PR TITLE
Avoid crash on attempting to display rooms where the ruleset cannot be resolved

### LINKED ISSUE #11309: Multiplayer potential crash after exiting a lobby and returning to lounge
```
2020-12-25 15:48:34 [error]: Failed to update room: test.
2020-12-25 15:48:34 [error]: System.NullReferenceException: Object reference not set to an instance of an object.
2020-12-25 15:48:34 [error]: at osu.Game.Online.Multiplayer.PlaylistItem.MapObjects(BeatmapManager beatmaps, RulesetStore rulesets)
2020-12-25 15:48:34 [error]: at osu.Game.Screens.Multi.Components.RoomManager.update(Room local, Room remote)
2020-12-25 15:48:34 [error]: at osu.Game.Screens.Multi.Components.RoomManager.onRoomsReceived(List`1 received)
```

### PR DESCRIPTION
**Pull request by peppy**
Closes https://github.com/ppy/osu/issues/11309.

### CODE REVIEW

**Comment by smoogipoo** [comment]
This isn't a crash right? It's just logging as an error: https://github.com/ppy/osu/blob/bef0e5cfa17c79f352528cd559ffa9a10b011d31/osu.Game/Screens/OnlinePlay/Components/RoomManager.cs#L154

And this makes it so that the room is still available in a sense - it'll bypass that try-catch and exist in the `rooms` list / be visible in the lounge listing in a half-invalid state. How about throwing a different exception or returning a bool whether it succeeded, and making it do the same actions as in the catch block but without the logging?

**Comment by peppy** [comment]
I made the original issue due to a hard crash. I'll re-test if you are adamant it isn't a crash (you can test this by commenting out the `ruleset.Value ??= ...` line  if you beat me to it.

**Comment by bdach** [comment]
It does not in fact appear to crash, in my testing. It just logs errors.

I would tend to agree with silently failing on half-broken rooms like this and making sure they're not displayed, the same way the aforementioned current catch path in `RoomManager` does:

https://github.com/ppy/osu/blob/bef0e5cfa17c79f352528cd559ffa9a10b011d31/osu.Game/Screens/OnlinePlay/Components/RoomManager.cs#L152-L158

**Comment by peppy** [comment]
Hmm, it does look to be handled. The only way I can repro an actual crash is in the create room flow, but I guess that should never actually happen?

The existing try-catch should already be covering this case, so let's just mark this as resolved.

**Pull request closed without merging**
