### PR TITLE
Add /roll command to ChannelManager

### PR DESCRIPTION
**Pull request by ShaneEverittM**
I missed this from Osu! stable and thought I could add it back myself.

### CODE REVIEW

**Comment by peppy** [comment]
Thanks for your contribution.

That said, I don't think this can exist client-side. There's too much potential for faking it, which makes it non-useful in many scenarios (ie. being used in official tournaments).

**Comment by ShaneEverittM** [comment]
I see. Is there any interest in seeing it server side? Me and my friends just like it :^)
Out of curiosity, how might someone fake it without modifying the client? Alternatively, there could be more first-class support for tournament-style pick/bans so that this could just be relegated to easter-egg/nostalgia status.

**Comment by peppy** [comment]
> Out of curiosity, how might someone fake it without modifying the client? Alternatively, there could be more first-class support for tournament-style pick/bans so that this could just be relegated to easter-egg/nostalgia status.

You could just type the result out ;)

**Comment by ShaneEverittM** [comment]
> You could just type the result out ;)

Duh, others don't see the "/roll". 🤦

**Comment by peppy** [comment]
I'll close this one for now as I think it needs more thought. Right now we don't have a concept of server-side chat commands in the new API, so I can't immediately offer any path forward, but it's definitely something we need to consider.

**Comment by peppy** [comment]
Discussing further with the web team, I think we'd be looking to make a 1st party API implementation of a chat bot and deploy it separate from other components (using the existing chat API) to handle commands like this.

**Comment by ShaneEverittM** [comment]
> Discussing further with the web team, I think we'd be looking to make a 1st party API implementation of a chat bot and deploy it separate from other components (using the existing chat API) to handle commands like this.

Yeah, after thinking about it that's what I came to as well.

**Pull request closed without merging**
