### PR TITLE
Add mod setting `AngleSharpness` to the random mod

### PR DESCRIPTION
**Pull request by Pasi4K5**
After the recent changes in #18769, some people from the community pointed out that the uncomfortable patterns the random mod was generating were the main reason they were using the mod, since it made maps that they thought were boring more engaging to play. This is my attempt to satisfy those players while still keeping the recent changes.

This adds 2 mod settings to the random mod.

- "Angle sharpness" - A higher angle sharpness value means that angles are generally sharper, and vice versa. It does that by adding two offsets to the angle calculation function.
- ~~"Angle variety" - Increases the "randomness" of angles by applying a multiplier to all standard deviations.~~

If those settings are left at default, the mod behaves just like before this PR (after #18769).

I tried to choose the ranges of the settings sliders in a way that makes it feel intuitive and prevents the user from choosing values that completely break the hit object generation.

With those two settings, players have the ability to choose whether they want mostly sharp angles, mostly wide angles or both.

And since graphs are cool, here's visual representation of how the minimum (`1`) and maximum (`10`) values of the `AngleSharpness` setting affect the angle calculation function.
`α(x) ..... Angle between hit objects in rad`
`x ........ Distance between hit objects`
image

### CODE REVIEW

**Comment by mk56-spn** [comment]
As was kind of predicable since it was implemented random settings were always a thing people were going to want. But I think that careful consideration should be taken on whether this is a direction that should be pursued. Today it's "I want my flavour of angle" the tomorrow it's " I want # square jumps  or 1-2 jumps to be options in the generation" I'm not particularly against selectable patterns . But it's worth considering that they do make refactoring and overhauling the base algorithm more tedious since considerations have to be made to how each setting gets affected when that is done. But that's enough waffling about hypotheticals. Just something I thought I should bring up

**Comment by Pasi4K5** [comment]
> As was kind of predicable since it was implemented random settings were always a thing people were going to want.
> 
> But I think that careful consideration should be taken on whether this is a direction that should be pursued. Today it's "I want my flavour of angle" the tomorrow it's " I want # square jumps or 1-2 jumps to be options in the generation" I'm not particularly against selectable patterns, but it's worth considering that they do make refactoring and overhauling the base algorithm(s) more tedious since considerations have to be made to how each setting gets affected when that is done. But that's enough waffling about hypotheticals. Just something I thought I should bring up

I get where you're coming from, but, as I already mentioned, for a lot of the players that use the random mod, uncomfortable patterns are the main appeal of (in other words the only reason why they use) the random mod. Without the settings, people who want to turn uncomfortable maps into comfortable ones can do that by using RD, but not the other way around.

Also, I would argue there's quite a big gap between being able to choose the general angles to some extent and being able to choose specific patterns like squares and 1-2 jumps, since that would require a complete rework of the mod. The 2 settings I just added basically just modify already existing parameters.

> I'm not particularly against selectable patterns, but it's worth considering that they do make refactoring and overhauling the base algorithm(s) more tedious since considerations have to be made to how each setting gets affected when that is done.

It depends on what exactly you mean by "base algorithm(s)", but generally I don't think that it would make refactoring the algorithm that much more complex. The good thing is that everything related to angle calculations is completely separated from everything else, which means that changes to angle calculations (like this one) don't affect anything else.

**Comment by peppy** [comment]
I wonder if we can combine the two new settings into just one? I'm not sure the "variety" one is that required (and in the interest of not creating settings-overload, might work better as a linear map from the "sharpness" setting?)

**Comment by Pasi4K5** [comment]
> I wonder if we can combine the two new settings into just one? I'm not sure the "variety" one is that required (and in the interest of not creating settings-overload, might work better as a linear map from the "sharpness" setting?)

I removed the `AngleVariety` setting, but I'm still applying a multiplier to the standard deviations using `AngleSharpness`. Higher `AngleSharpness.Value` -> lower stdDev multiplier since offsets get less noticeable on wider angles. Also it gets a bit more chaotic, which is probably what players who use a higher `AngleSharpness` want, and without the multiplier jump maps just go in circles and almost never switch the flow direction.

The idea behind `AngleVariety` was to give players the ability to play randomised maps with both sharp *and* wide angles, but I guess `AngleSharpness` alone solves the actual issue too.

**Comment by peppy** [comment]
Seems to work okay, so let's go with this for now.

I'd highly recommend you setup a test scene with variables like the angle as quickly adjustable settings, so you aren't testing using the gameplay flow each time. Please do this if you make further change to this mod.

**Review by peppy — APPROVED** [review]

**Pull request merged**
