### PR TITLE
Add setting to toggle gameplay cursor trail

### PR DESCRIPTION
**Pull request by Aergwyn**
- [x] depends on #4136 
- [x] depends on #4134

### CODE REVIEW

**Comment by peppy** [comment]
I'd really rather we stopped adding ruleset/skin settings at a global level...

**Comment by Poyo-SSB** [comment]
I understand why you'd hesitate to have skin-level settings outside of skins, but there are lots of options that are just unwieldy and inefficient to be exclusively kept per-skin.

As a skinner, I would much rather allow users to disable certain elements via the settings rather than making 8 permutations of my skin because different people prefer 300s/followpoints/cursor trails on or off.

It's not like there isn't a prescedent for this either—stable has a hit lighting toggle, a combo burst toggle, and lazer and stable both allow the cursor size to be changed.

Of course, all of these should be available at a skin level as well, but I think that it's good to include in the settings for the sake of convenience for skinners and players alike.

**Comment by Aergwyn** [comment]
His remark was because those settings were on the global config and not on the ruleset specific config. See dependent PR.

Although some settings will probably be temporary until the full skinning system is in place.

**Comment by peppy** [comment]
@poyo please wait until you see my plans for the skinning system. i know what i’m doing.

**Comment by peppy** [comment]
For the time being this seems fine. It will need to be moved to skins later on but let's not hold up new configuration items being added in the mean time.

**Review by peppy — DISMISSED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
