### PR TITLE
Implement spinner placements

### PR DESCRIPTION
**Pull request by smoogipoo**
Prereqs:
- [x] https://github.com/ppy/osu/pull/3656

https://streamable.com/kjb61

### CODE REVIEW

**Comment by Aergwyn** [comment]
Now I wonder how off-center spinners would play. :thinking:

**Comment by smoogipoo** [comment]
There is a reason why I didn't force them to be centred ;)

**Comment by WebFreak001** [comment]
How about we make it possible for spinners to move like sliders too?

**Comment by peppy** [comment]
For the time being spinners should be forced to the center location.

**Review by peppy — APPROVED** [review]

**Pull request merged**
