### PR TITLE
Update all dependencies (except for Moq)

### PR DESCRIPTION
**Pull request by peppy**
I have a regular repeating task to do this, in place of dependabot spam.  Seems like a good opportunity to do so.

Have tested locally and via github CI, things looks to be sane enough.

> But why not Moq

ha ha

### CODE REVIEW

**Comment by Joehuu** [comment]
FYI there are [grouped version updates for Dependabot](https://github.blog/changelog/2023-08-24-grouped-version-updates-for-dependabot-are-generally-available/) as of recent.

**Comment by peppy** [comment]
It's still too spammy and more of a pain than it's worth. Doing this manually allows me to choose a schedule I'm happy with, and it only takes 3 minutes, which is less time than checking dependabot has done what we expect it to.

**Comment by bdach** [comment]
Looks generally fine, but I'm having a bit of a pause with the messagepack updates, so I'd want to run this past android later just to be on the safe side...

Desktop appears to be fine.

**Review by bdach — APPROVED** [review]
Tested windows and android. Things generally appear to work.

**Pull request merged**
