### PR TITLE
Fix key configuration row sometimes not expanding on click

### PR DESCRIPTION
**Pull request by ekrctb**
Negative padding was used to (I guess) start autosize animation preemptively. The negative padding effectively set the height of `pressAKey` to zero. I think this is bad. I think `BypassAutoSizeAxes` should be used in such purpose.
This fixes the example illustrated on ppy/osu-framework#1552. I'm not sure if the issue needs more fix.

### CODE REVIEW

**Comment by peppy** [comment]
@smoogipoo since you're currently looking at autosize issues, can you check this out? if it is purely zero-size related, we need to decide whether this requires a framework fix (or at very least some kind of warning to the developer?)

**Comment by smoogipoo** [comment]
Were you actually able to reproduce this? I'm not able to do so on master.

**Comment by ekrctb** [comment]
Quickly scroll out while the row is fading out and scroll in. Sometimes works (I did with slowed down clock).

**Comment by ekrctb** [comment]
Video of reproduction (The attempt at 0:18 worked): https://streamable.com/2c90q

**Comment by smoogipoo** [comment]
I can confirm that this doesn't happen with my autosize validation changes, but in principle I agree with using BypassAutosizeAxes if it works - not a fan of negative paddings like this.

**Review by peppy — APPROVED** [review]

**Pull request merged**
