### PR TITLE
Fix editor exporting beatmap combo colours in wrong order

### LINKED ISSUE #21984: osu! lazer editor round-trips combo colours in an incompatible way
### Type

Game behaviour

### Bug description

I tried to use the lazer editor to address feedback on [this map](https://osu.ppy.sh/beatmapsets/1896477#osu/3908451). I changed the combo colours, toggled some combos, exported because I couldn’t find a way to upload from lazer, then imported to stable and reuploaded the map from there. I then playtested on stable and noticed that one of the combo colours was missing, and when I went back to lazer to redownload and my map, the combos had shifted.

Minimal repro:

1. Download [bug.zip](https://github.com/ppy/osu/files/10328538/bug.zip), rename to bug.osz
2. Import to lazer, open the editor, observe that the object combos are red, green, blue, magenta (good)
3. Export from lazer and import to stable, observe that the combos are now green, blue, magenta, green (bad)
4. Export from stable and import to lazer, observe that the combos are now green, blue, magenta, red (bad)

### Screenshots or videos

Changes between original and first export below. The combos are converted to lazer numbering, plus some other changes which are probably ok (adding inherited timing points that don’t change anything, clearing the new combo bit in the spinner, making each additionSet=0 explicit).

```diff
% diff -U0 <(unzip -p bug.osz '*.osu' | tr -d \\r) <(unzip -p converted.osz '*.osu' | dd status=none bs=1 skip=3)
--- /proc/self/fd/11	2023-01-01 18:25:28.288343563 +0800
+++ /proc/self/fd/12	2023-01-01 18:25:28.288343563 +0800
@@ -1 +1 @@
-osu file format v14
+osu file format v128
@@ -7 +7 @@
-Countdown: 0
+Countdown: 1
@@ -21,10 +21,6 @@
[redacted colon spacing changes]
@@ -33,6 +29,6 @@
[redacted colon spacing changes]
@@ -41,8 +36,0 @@
[redacted //Storyboard changes]
@@ -52 +40,2 @@
-
+0,-100,4,1,0,100,0,0
+501,-100,4,1,0,100,0,0
@@ -55,4 +44,4 @@
-Combo1 : 255,0,255
-Combo2 : 255,0,0
-Combo3 : 0,255,0
-Combo4 : 0,0,255
+Combo0: 255,0,255,255
+Combo1: 255,0,0,255
+Combo2: 0,255,0,255
+Combo3: 0,0,255,255
@@ -65,2 +54,2 @@
-256,192,2500,12,0,4000,0:0:0:0:
-388,240,4500,5,14,1:0:0:0:
+256,192,2500,8,0,4000,0:0:0:0:
+388,240,4500,5,14,1:1:0:0:
@@ -70 +59 @@
-194,187,6500,5,14,2:0:0:0:
+194,187,6500,5,14,2:2:0:0:
@@ -74 +63 @@
-347,111,8500,5,14,3:0:0:0:
+347,111,8500,5,14,3:3:0:0:
```

Changes between first and second exports below. 

```diff
% diff -U0 <(unzip -p converted.osz '*.osu' | dd status=none bs=1 skip=3) <(unzip -p downgraded.osz '*.osu' | tr -d \\r) 
--- /proc/self/fd/11	2023-01-01 18:37:40.793236144 +0800
+++ /proc/self/fd/12	2023-01-01 18:37:40.793236144 +0800
@@ -1 +1 @@
-osu file format v128
+osu file format v14
@@ -21,6 +21,10 @@
[redacted colon spacing changes]
@@ -29,6 +33,6 @@
[redacted colon spacing changes]
@@ -36,0 +41,8 @@
[redacted //Storyboard changes]
@@ -42,0 +55 @@
+
@@ -44,4 +57,4 @@
-Combo0: 255,0,255,255
-Combo1: 255,0,0,255
-Combo2: 0,255,0,255
-Combo3: 0,0,255,255
+Combo1 : 255,0,0
+Combo2 : 0,255,0
+Combo3 : 0,0,255
+Combo0 : 255,0,255
```

I think we convert the combo colours correctly for maps created in stable (since fixing #3206), mapping combo colours [2,3,4,1] to [1,2,3,0]. Stable ignores Combo0 (but leaves it in the file), so these converted combo colours are only correct for lazer. Then when exporting back to lazer, we map [2,3,0,1] to [1,2,3,0], treating the Combo0 that was left in the file as if we were converting a stable map with Combo4.

### Version

2022.1228.0-lazer (and stable b20230101.2)

### Logs

[database.log](https://github.com/ppy/osu/files/10328631/database.log)
[input.log](https://github.com/ppy/osu/files/10328632/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/10328633/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/10328634/network.log)
[performance.log](https://github.com/ppy/osu/files/10328635/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10328638/runtime.log)

### PR DESCRIPTION
**Pull request by frenzibyte**
- Closes https://github.com/ppy/osu/issues/21984

Stable reads combo colours starting from `Combo1`, meanwhile lazer is exporting the first combo colour as `Combo0`.

### CODE REVIEW

**Review by peppy — APPROVED** [review]

**Comment by bdach** [comment]
1. No test coverage?
2. This seems like a half job. Decoding isn't changed here, and that's wrong too. Stable ignores `Combo0`, but the `LegacyDecoder` implementation is rather rudimentary and will not do this ([only checks if the line starts with `Combo`](https://github.com/ppy/osu/blob/b4a3f872ee73c40a8f25356efca2eae2ba382e3b/osu.Game/Beatmaps/Formats/LegacyDecoder.cs#L100)).

**Comment by frenzibyte** [comment]
1. I thought about adding one but wasn't sure what kind of test coverage satisfies things here, one that checks combo starts from 1? Felt pointless, but sure can add one.
2. I wasn't sure if action was needed on the decoding side of things other than ignoring `Combo0`, which originated from lazer so...?

**Comment by peppy** [comment]
I wouldn't worry about handling broken lazer beatmaps. Probably <5 exist and it's not worth the effort.

**Comment by frenzibyte** [comment]
Also without changing decoder, adding test coverage won't be easy at all given the structure of `LegacyBeatmapEncoderTest` which solely focuses on encoding-decoding stability (and the only benefit there'll ever be is checking whether the encoder doesn't spit `Combo0`), so I'm bailing out from adding changes to this PR.

**Review by bdach — APPROVED** [review]
fine

**Pull request merged**
