### PR TITLE
Refactor combo colours retrieval to use skin config lookups instead

### PR DESCRIPTION
**Pull request by frenzibyte**
This refactors the combo colours retrieval logic to not directly read the combo colours of the skin and use, but instead add a combo colour lookup (`SkinComboColourLookup`) for skin config and retrieve the colour using it.

This is required for a further change that overrides a given combo index with another special index instead, at a skin level, which can only ever be possible with this refactor.

Side note:
 - I was thinking of moving the lookup handling logic to a `Skin`-level and add a virtual `GetComboColour` method for both `DefaultSkin` and `LegacySkin` to override, but I've refrained from doing so as currently `Skin` does not implement anything and always returns `null`, so I think it's a better choice to leave doing that for later, once it's settled how modern (lazer) skins would look like and what members they will have.

### CODE REVIEW

**Review by peppy — APPROVED** [review]
I'm pretty happy with the direction of this change.

**Comment by peppy** [comment]
Separate from the follow-up "colourhax" PR, this one looks like a good code quality improvement. @smoogipoo requesting you do a sanity check of this one to make sure you agree.

**Comment by smoogipoo** [comment]
It looks ok from me. Feel free to merge if you've tested.

**Review by smoogipoo — APPROVED** [review]
Approving based on code quality, haven't tested.

**Pull request merged**
