### PR TITLE
Update EF Core to Version 5.0.6

### PR DESCRIPTION
**Pull request by Rsplwe**

### CODE REVIEW

**Comment by peppy** [comment]
Have you tested this?

Reference you should read:
https://github.com/ppy/osu/pull/12003
https://github.com/ppy/osu/pull/12125

**Comment by Rsplwe** [comment]
Untitled

**Comment by frenzibyte** [comment]
I recommend you check these which arouse with the EF core 5.0 bump:
- https://github.com/ppy/osu/issues/12094
- https://github.com/ppy/osu/issues/12104
- https://github.com/ppy/osu/issues/12108

**Comment by Rsplwe** [comment]
> I recommend you check these which arouse with the EF core 5.0 bump:
> 
> * #12094
> * #12104
> * #12108

I've checked it and no errors occurred

**Comment by smoogipoo** [comment]
Doesn't look like you've tested enough. The very first time I tried to save a map on this branch:
```
Unhandled exception. System.InvalidOperationException: The instance of entity type 'FileInfo' cannot be tracked because another instance with the same key value for {'ID'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)
   at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Remove(TEntity entity)
   at osu.Game.Database.ArchiveModelManager`2.DeleteFile(TModel model, TFileModel file) in /home/smgi/Repos/osu/osu.Game/Database/ArchiveModelManager.cs:line 487
   at osu.Game.Database.ArchiveModelManager`2.ReplaceFile(TModel model, TFileModel file, Stream contents, String filename) in /home/smgi/Repos/osu/osu.Game/Database/ArchiveModelManager.cs:line 466
   at osu.Game.Beatmaps.BeatmapManager.Save(BeatmapInfo info, IBeatmap beatmapContent, ISkin beatmapSkin) in /home/smgi/Repos/osu/osu.Game/Beatmaps/BeatmapManager.cs:line 270
   at osu.Game.Screens.Edit.Editor.Save() in /home/smgi/Repos/osu/osu.Game/Screens/Edit/Editor.cs:line 320
   at osu.Framework.Graphics.UserInterface.Menu.DrawableMenuItem.OnClick(ClickEvent e)
   at osu.Game.Graphics.UserInterface.DrawableOsuMenuItem.OnClick(ClickEvent e) in /home/smgi/Repos/osu/osu.Game/Graphics/UserInterface/DrawableOsuMenuItem.cs:line 101
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.MouseButtonEventManager.handleClick(InputState state, List`1 targets)
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
   at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.InputManager.Update()
   at osu.Framework.Input.PassThroughInputManager.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
   at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
   at osu.Framework.Platform.GameHost.UpdateFrame()
   at osu.Framework.Threading.GameThread.ProcessFrame()
```
I.e. the editor saving issue.

**Comment by Rsplwe** [comment]
> Doesn't look like you've tested enough. The very first time I tried to save a map on this branch:
> 
> ```
> Unhandled exception. System.InvalidOperationException: The instance of entity type 'FileInfo' cannot be tracked because another instance with the same key value for {'ID'} is already being tracked. When attaching existing entities, ensure that only one entity instance with a given key value is attached. Consider using 'DbContextOptionsBuilder.EnableSensitiveDataLogging' to see the conflicting key values.
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.ThrowIdentityConflict(InternalEntityEntry entry)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry, Boolean updateDuplicate)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(TKey key, InternalEntityEntry entry)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.IdentityMap`1.Add(InternalEntityEntry entry)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.StartTracking(InternalEntityEntry entry)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState oldState, EntityState newState, Boolean acceptChanges, Boolean modifyProperties)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.InternalEntityEntry.SetEntityState(EntityState entityState, Boolean acceptChanges, Boolean modifyProperties, Nullable`1 forceStateWhenUnknownKey)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.PaintAction(EntityEntryGraphNode`1 node)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityEntryGraphIterator.TraverseGraph[TState](EntityEntryGraphNode`1 node, Func`2 handleNode)
>    at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.EntityGraphAttacher.AttachGraph(InternalEntityEntry rootEntry, EntityState targetState, EntityState storeGeneratedWithKeySetTargetState, Boolean forceStateWhenUnknownKey)
>    at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.SetEntityState(InternalEntityEntry entry, EntityState entityState)
>    at Microsoft.EntityFrameworkCore.Internal.InternalDbSet`1.Remove(TEntity entity)
>    at osu.Game.Database.ArchiveModelManager`2.DeleteFile(TModel model, TFileModel file) in /home/smgi/Repos/osu/osu.Game/Database/ArchiveModelManager.cs:line 487
>    at osu.Game.Database.ArchiveModelManager`2.ReplaceFile(TModel model, TFileModel file, Stream contents, String filename) in /home/smgi/Repos/osu/osu.Game/Database/ArchiveModelManager.cs:line 466
>    at osu.Game.Beatmaps.BeatmapManager.Save(BeatmapInfo info, IBeatmap beatmapContent, ISkin beatmapSkin) in /home/smgi/Repos/osu/osu.Game/Beatmaps/BeatmapManager.cs:line 270
>    at osu.Game.Screens.Edit.Editor.Save() in /home/smgi/Repos/osu/osu.Game/Screens/Edit/Editor.cs:line 320
>    at osu.Framework.Graphics.UserInterface.Menu.DrawableMenuItem.OnClick(ClickEvent e)
>    at osu.Game.Graphics.UserInterface.DrawableOsuMenuItem.OnClick(ClickEvent e) in /home/smgi/Repos/osu/osu.Game/Graphics/UserInterface/DrawableOsuMenuItem.cs:line 101
>    at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
>    at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
>    at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
>    at osu.Framework.Input.MouseButtonEventManager.handleClick(InputState state, List`1 targets)
>    at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
>    at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
>    at osu.Framework.Input.ButtonEventManager`1.HandleButtonStateChange(InputState state, ButtonStateChangeKind kind)
>    at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
>    at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
>    at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
>    at osu.Framework.Input.InputManager.Update()
>    at osu.Framework.Input.PassThroughInputManager.Update()
>    at osu.Framework.Graphics.Drawable.UpdateSubTree()
>    at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
>    at osu.Framework.Platform.GameHost.UpdateFrame()
>    at osu.Framework.Threading.GameThread.ProcessFrame()
> ```
> 
> I.e. the editor saving issue.

fixed.

**Comment by bdach** [comment]
you've "fixed" it by... bringing the same extension method added in #12003? and was then promptly reverted in #12125 due to performance concerns? so this is basically a revert of a revert?

have you tested beatmap carousel performance on a DB with a large amount of maps? does it perform worse? because if yes, then this is basically going in a circle. and all of those concerns were already raised in this thread by linking two pull requests and three issue reports.

i'm sorry but you need to put in more effort in understanding what we're trying to convey here. we've tried bumping, and it didn't work. so unless something fundamental changed on the EF side, this will get reverted very quickly too.

**Pull request closed without merging**
