### PR TITLE
Set initial path for Edit mode's file chooser to shared internal storage on Android

### PR DESCRIPTION
**Pull request by counter185**
Currently, the file chooser on Android starts in the app's private data directory, which can't be accessed by any other app, at least without root access. There's no way to navigate from that directory to shared storage to select a file.

This PR changes the default directory on Android to `/storage/emulated/0`, which is Android's shared storage, accessible by all apps and the user. Additionally, it adds the `GetInitialPath()` method to `OsuGame`, which can be potentially overriden for other platforms where the default app directory shouldn't be accessible by the user.

This makes creating a new beatmap from scratch on Android possible, provided that the `READ_EXTERNAL_STORAGE` permission is granted by the user. [Following the official Android docs on requesting permissions,](https://developer.android.com/training/permissions/requesting#workflow_for_requesting_permissions) I added a basic prompt that shows when starting the app for the first time. It probably needs some more work, like changing the style and making the text a localized string, but for now, it serves its purpose.

Screenshot_2021-10-22-10-14-06-659_sh ppy osulazer

Screenshot_2021-10-22-11-13-28-244_sh ppy osulazer

However, there is a bug that can't be fixed in this repo alone, and that is: the game closes itself upon opening the "grant permissions" window. 
It's caused by [this line of code in osu-framework](https://github.com/ppy/osu-framework/blob/master/osu.Framework.Android/AndroidGameActivity.cs#L80), that kills the process whenever the app goes unfocused (user goes to home screen, turns the screen off, a window not related to the current app opens, etc.)

I tried my best to follow the current code style, but if I made a mistake (very likely), feel free to modify the code however you like.

- [x] Depends on https://github.com/ppy/osu-framework/pull/4838

### CODE REVIEW

**Review by bdach — CHANGES_REQUESTED** [review]
As for the code:

**Review by Susko3 — CHANGES_REQUESTED** [review]
I've done some rudimentary testing on my Android 11 device, and this appears to work, with both `/storage/emulated/0` and `/sdcard`.

The alert box is overly intrusive. Should probably only appear when the user tries to use a file picker for the first time.

Most of this should be moved framework-side, especially changes in `GameHost` and the storage permission check. Something like `RequestStoragePermission(string infoText)` and `bool HasStoragePermission` that consumers should call and check.
Maybe have check it in `DirectorySelector` framework-side, so it's completely transparent to consumers.

Changing this

https://github.com/ppy/osu-framework/blob/c02c0858804013c503484cd89b55f81b95bdf7da/osu.Framework/Graphics/UserInterface/DirectorySelector.cs#L42

to use `GetInitialPath()` seems like the sane optiom. Instead of having a special case in the Editor file chooser, have a global sane starting directory.

`GetInitialPath()` should return `"/sdcard"` on android, and `Environment.GetFolderPath(Environment.SpecialFolder.UserProfile)` on other platforms.

**Comment by counter185** [comment]
sorry for the wait, I changed the code to use the new changes to framework. it seems to work

**Comment by bdach** [comment]
On my side I am still planning to look into `GLSurfaceView.setPreserveEGLContextOnPause()`. A very simple initial patch had one older device working seemingly 100% correctly and another newer one showing a black screen, so I need to examine the cause of the newer one failing to cooperate.

**Comment by bdach** [comment]
I was going to revive this, because the main blocker - loss of GL context on android - has been since resolved, but looking at this diff again I don't think this is the correct direction to take. In particular I don't think the editor should be responsible for showing this permissions dialog, I think the directory select component should, as already mentioned by @Susko3.

Leaning to close this pull for the time being unless there are objections.

**Comment by peppy** [comment]
I think closing is the best option for now. I agree with the location of this implementation being a bit weird.

**Pull request closed without merging**
