### PR TITLE
Don't count last section in difficulty calculation

### PR DESCRIPTION
**Pull request by holly-hacker**
In order to be [bug-for-bug compatible](https://en.wikipedia.org/wiki/Bug_compatibility) with stable's diffcalc, the last strain section should not be counted. This solves several cases in #4622 where stable reports a way lower value than lazer. This affects all gamemodes.

This is technically incorrect behavior, but IMO it's better to just follow stable until it is deprecated. Naturally, another course of action would be to update stable.

### osu!
| beatmap       | lazer old       | stable | lazer new       |
| ------------- | --------------- | ------ | --------------- |
| diffcalc-test | 6.9311451172634 | N/A    | 6.9311451160169 |

I'm testing using an outdated stable build which doesn't contain the most recent balancing updates.

### Taiko
| beatmap                | lazer old    | stable       | lazer new    |
| ---------------------- | ------------ | ------------ | ------------ |
| diffcalc-test(-strong) | 2.9811338051 | 2.9811336589 | 2.9811336589 |

Unit test matches stable perfectly now!

### Mania
| beatmap       | lazer old | stable  | lazer new |
| ------------- | --------- | ------- | --------- |
| diffcalc-test | 2.36834   | 2.27048 | 2.30316   |

### Catch
| beatmap       | lazer old | stable  | lazer new |
| ------------- | --------- | ------- | --------- |
| 1463571       | 51.0636   | 12.9724 | 13.2875   |
| 1578040       | 57.2904   | 1.62373 | 3.21903   |
| 448918        | 40.2829   | 1.20154 | 1.18474   |
| 628771        | 45.2952   | 1.97616 | 1.97592   |
| diffcalc-test | 4.20586   | 4.20191 | 4.20191   |
| 977762        | 1.77877   | 1.78872 | 1.77877   |
| 2057725       | 3.45302   | 3.44780 | 3.44947   |
| 2020384       | 6.72952   | 6.72932 | 6.72952   |
| 1533958       | 4.16960   | 4.15895 | 4.16960   |

### CODE REVIEW

**Comment by Aergwyn** [comment]
I'm really confused by this. Many areas have deliberate improvements for the sake of being better.
My naive thinking tells me that I'd rather remove the bug in stable than introduce it here too. And in case for diffcalc that seems to be possible via contributing to [osu!performance](https://github.com/ppy/osu-performance)... or am I completely off with that?

**Comment by HoLLy-HaCKeR** [comment]
I'd also rather see it fixed in stable, but I'm leaving the decision for what to do to a member of the osu! team. It's all the same to me.

**Comment by peppy** [comment]
Nice catch. We'll likely fix this at stable and do a full reprocess of affected beatmaps.

**Comment by smoogipoo** [comment]
Nice catch. We'll be applying this fix to stable when lazer's catch diffcalc is deployed, but in the meantime I'll begin a re-process with these changes.

**Comment by smoogipoo** [comment]
As mentioned previously, we're tracking this issue in stable and will be applying fixes there. Unfortunately stable wasn't updated until now even though diffcalc was deployed, will be fixed soon.

**Pull request closed without merging**
