### PR TITLE
Audio feedback improvements for song select

### PR DESCRIPTION
**Pull request by nekodex**
Tweaks to make song select feel better with the new incoming song-select samples (ppy/osu-resources#161)

Specifically:
- Removes the delay before audio feedback is played on beatmap/difficulty change
- Adds a high-pass filter to when song choice is confirmed (frees up room for the confirmation sample bass-frequencies)
- Changes the skip intro button to not re-use the `confirm-selection`

(Not sure how safe it is to _completely_ remove the beatmap/difficulty change audio feedback debounce... can add an independent one if there are issues I guess?)

### CODE REVIEW

**Review by bdach — DISMISSED** [review]
Code seems okay. Have done a local checkout with the resources pull and to an untrained ear the result sounds good. Gonna request another review to make sure though.

**Comment by peppy** [comment]
High pass filter addition feels like it doesn't leave enough left of the song, to the point I am wondering if the song is even still playing for the first second or two (is that the intention?). Prefer without, maybe we can drop the overall volume of the new effect instead? It feels louder than everything else to me.

Also we're probably going to need to do something about this at some point (sound warning)

https://user-images.githubusercontent.com/191335/141101354-c7f52641-65b8-404e-aa43-7b2a1e0b54f8.mp4

**Comment by nekodex** [comment]
> High pass filter addition feels like it doesn't leave enough left of the song, to the point I am wondering if the song is even still playing for the first second or two (is that the intention?). Prefer without, maybe we can drop the overall volume of the new effect instead? It feels louder than everything else to me.

Well, yeah... that's kind of the point. I'm trying to add a reprieve for the ears between when the is song selected and when gameplay starts.

I also wonder what volume your music is set to if the effect is so loud that you can't hear the song behind it "for the first second or two"? Testing at 100% music volume, the effect causes distortion on various songs (without the high-pass filter) as is... and without replaygain, the effect will be disproportionally louder relative to some songs.

I've decreased the high-pass frequency to reduce the intensity of the effect for now, let me know if you think that sounds better.

> Also we're probably going to need to do something about this at some point (sound warning)

Yeah, might look at adding the limiter/compressor back in... will probably sound better than just a concurrency limit in places like this?

**Comment by peppy** [comment]
Always testing with 100% on all controls. Tested with about 50 different tracks.

Will try again with the changes.

**Comment by peppy** [comment]
Still feel like the high pass shouldn't be there. I don't know what it is, but it just makes the song playback feel... underwhelming.

Also something is going to need to be done about the lack of debounce. A common workflow users have it to search around for the next map before actually stopping on it, and with this PR it gets quite noisy:

Before:

https://user-images.githubusercontent.com/191335/141267729-63a124b1-9bd4-4778-b2ac-1c9b745741ec.mp4

After:

https://user-images.githubusercontent.com/191335/141267439-f2746865-3049-41bb-a7be-42404f122ea9.mp4

For comparison, stable only has a very short debounce (something like 20ms, you can notice it if you hold F2 for random) but also has a lot lower volume for the samples:

https://user-images.githubusercontent.com/191335/141268110-f1e8f78d-e088-4de7-b543-730c9cd4a082.mp4

Maybe dropping the volume considerably would be a good starting point?

**Comment by nekodex** [comment]
I still like the idea of giving the ears a respite before gameplay starts and not blare music at 100% all the time, builds anticipation imo (a bunch of arcade rhythm games do something similar).

But if you _reaaallllly_ dislike the idea that much, two alternatives come to mind:

- Only high-pass temporarily and bring the bass back in after a short delay

https://user-images.githubusercontent.com/272140/141411494-cea90161-06a5-4499-9e1a-228ca39739ce.mov

- Remove the high-pass completely and alter the bass character of the sample to have less sub frequencies

https://user-images.githubusercontent.com/272140/141411523-ea048be4-1848-4b9b-8af1-d449866f1f2a.mov

Personally I prefer the former as I think having a bass impact there is more... impactful.

**Comment by peppy** [comment]
Yeah, was thinking the same thing with the temporary application. Can you pushed changes for the former? With the example you've provided I'm pretty happy with it, but I'd want to test on a few more examples.

**Comment by peppy** [comment]
Are you planning on adjusting the overall volume of these new effects at all? Still feels like they are a bit loud relative to everything else going on, especially on quieter sections of music.

**Comment by nekodex** [comment]
Yeah I'm working on finding a balance ATM, too soft and it gets drowned out behind louder music... too loud and peppy gets angery.

**Review by peppy — APPROVED** [review]

**Pull request merged**
