### PR TITLE
Support open profile overlay from username in more places

### LINKED ISSUE #5966: Local scores don't link to user correctly in all cases
**Describe the bug:** 
On local leaderboards for a map, scores you set on the old client don't show your profile picture correctly. Clicking on your profile picture for this play brings up an empty profile.
**Screenshots or videos showing encountered issue:** 
(Top score was set on old client, 2nd score was set on new client)
edited
**osu!lazer version:** 
2019.831.0

### PR DESCRIPTION
**Pull request by peppy**
Feel much better about doing this now that we have a defined interface.

Closes https://github.com/ppy/osu/issues/5966.

- [x] Depends on https://github.com/ppy/osu/pull/15466.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Opening from the beatmap wedge seems to open my own profile (i.e. if I first load another profile via another method, then click a user link in the wedge, it goes back to my profile).

**Comment by smoogipoo** [comment]
Oh, it looks like this is also an issue on master. Possibly a regression then?

**Comment by peppy** [comment]
That's one of the issues this PR should be resolving, I'll take a look into it.

**Comment by peppy** [comment]
@smoogipoo are you sure that's not due to being on the development server, where the target users don't exist? testing on the production servers look to work as expected.

**Comment by smoogipoo** [comment]
I tested on production. It looks like `LinkFlowContainer` only uses the online ID in `AddUserLink`.

**Pull request merged**
