### PR TITLE
Prioritize selecting exact searched acronym with select keybind

### PR DESCRIPTION
**Pull request by jhk2601**
Addresses #30001 

Nice QOL change, before searching "SY" for the synesthesia mod and pressing enter would select EZ, since selection was prioritized by column/descending order instead of accuracy. This interaction was actually pretty common and is not exclusive to EZ/SY. Videos attached to explain. (Why EZ appears when SY is searched I truly have no idea. Sy does not appear in the description. Dark magic is likely involved). Also added support for exact name searching though I'm 99 percent sure it isn't ever relevant. 

https://github.com/user-attachments/assets/002e1a21-77c0-4f4d-b08a-e070a7816860

https://github.com/user-attachments/assets/1a4d1fd9-d056-4f64-b46f-55b4ed4ce9c0

### CODE REVIEW

**Comment by SchiavoAnto** [comment]
> (Why EZ appears when SY is searched I truly have no idea. Sy does not appear in the description. Dark magic is likely involved)

I would guess it appears because "sy" is contained in "Easy".

**Comment by jhk2601** [comment]
> > (Why EZ appears when SY is searched I truly have no idea. Sy does not appear in the description. Dark magic is likely involved)
> 
> I would guess it appears because "sy" is contained in "Easy".

I'm going to pretend I knew this the whole time to preserve my faith in my ability to read.

**Review by smoogipoo — DISMISSED** [review]
I think I'm okay with this. The only one I found maybe questionable is `ad` and `da`, but it's probably okay for users to have to write `adj` to select DifficultyAdjust in the former and `day` to select Daycore in the latter.

Requesting second opinion by @ppy/team-client

**Comment by bdach** [comment]
I can get behind the idea. Not 100% on the execution. The trouble I have is that the consistency of "first result will be picked" is a bit gone with this change. If I were to suggest anything to address that it'd maybe be adding some sort of "preselect" indicator like e.g. outer glow to the mod that will be selected if you press enter.

Not sure. Going to tag in @peppy specifically as is the custom when UX discussions are taking place.

**Comment by peppy** [comment]
I think I'm okay with this, but I do agree that some kind of glow / indicator would make it absolutely amazing. If that can be added easily then it should be done here IMO. Worth spending 20-30 minutes on it if anyone wants to give it a try.

Only other consideration i'd have is whether you need to use upper case for this to work. Probably fine without case considerations though.

**Comment by bdach** [comment]
> Only other consideration i'd have is whether you need to use upper case for this to work. Probably fine without case considerations though.

Casing is explicitly ignored, e.g. "da" would prefer Difficulty Adjust over Daycore as stated above. Would you be expecting that to be case-sensitive?

**Comment by smoogipoo** [comment]
My anecdotal experience with DT (so it's not really applicable here because it's in a realm of its own), is that I type `dt` exactly. I don't like typing `dou` (have to rejig my brain to do that) and also don't like reaching reaching for the shift key which is potentially difficult to do with one hand for some mods (as my other hand is usually holding my pen).

**Comment by peppy** [comment]
Yeah that's fine, is what I was trying to say (case insensitive is probably the correct approach, just wanted to raise it as a point of discussion).

**Comment by bdach** [comment]
Alright then I guess I'll have a go at the indicator thing?

**Comment by bdach** [comment]
Alright I've done *something*:

https://github.com/user-attachments/assets/6102c448-8c75-4955-ade4-8a8759726317

Suggestions, if any?

**Comment by jhk2601** [comment]
> Alright I've done _something_:
> 
>  2024-10-18.13-24-34.mp4 
> Suggestions, if any?

Looks great to me, unobtrusive but clear what is selected, thanks for the addition. Would it be going too far to include mod presets here? (I.e. I search "1337" and that preset gets highlighted/prioritized for select). I'm not familiar enough with how presets are handled to determine if that has any edge case implications (Is naming your preset "DT" allowed?) but I think that would be a nice addition here if possible.

**Comment by bdach** [comment]
> Would it be going too far to include mod presets here?

Wouldn't do it in this pull. I'm not sure how to mix presets into all this. As in you should probably be able to quick select both a preset and a mod.

I'd like to get this in if deemed viable without going down that particular discussion.

**Comment by jhk2601** [comment]
> > Would it be going too far to include mod presets here?
> 
> Wouldn't do it in this pull. I'm not sure how to mix presets into all this. As in you should probably be able to quick select both a preset and a mod.
> 
> I'd like to get this in in the current state if deemed viable without going down that particular discussion.

alright valid, I took a quick look and it definitely feels out of scope, another time.

**Review by peppy — DISMISSED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
