### PR TITLE
Display osu!mania keycount in song select carousel panels and details

### LINKED ISSUE #12720: Maps converted to osu!mania should display key count in details
**Describe the new feature:** 
This is the details tab of an osu!mania map:
image
This is the details tab of an osu! map converted to osu!mania:
image
Currently, there is no way of finding out the key count of a converted map (as far as I know) without playing it. Not that of a big deal, but having it somewhere could improve UX.
**Proposal designs of the feature:** 
Replace circle size with key count for converted maps.
#9453 had discussion about displaying key count elsewhere. Hasn't been active since November 2020, except for duplicate issues being linked to it.

### PR DESCRIPTION
**Pull request by smoogipoo**
Resolves https://github.com/ppy/osu/issues/12720

Bit of an RFC on this one - I only did it because it makes my life easier debugging a totally unrelated change. I'm curious what people's thoughts are on this, in particular:
- That I've added it as a local implementation for now (and in `ILegacyRuleset`) because I don't want this to be exposed to the public API just yet. It's possible that it could be done better but this is an MVP that is a QOL improvement for osu!mania specifically which stable already has. There was already a similar local implementation for the details panel.
- The naming and semantics around the new properties added to `BeatmapDifficulty` - I used `EndTimeObjectCount` as opposed to `CircleCount` because that's easier to explain. Also not sure whether `BeatmapDifficulty` is the appropriate location for this?

This adds:
- `[nK]` prefix to the difficulty name in carousel panels.
- Key count display in the details panel.
- Song select `keys=` search filtering for converted beatmaps.

Video: https://drive.google.com/file/d/1bDb6ICbhaAimkQRDHhrQhOhW9QgsyAdu/view?usp=sharing

Caveats to this implementation/weirdness:
1. It doesn't update with mods. If you select the 1K mod, everything will still show up as the original key count/converted key count, and _not_ 1K. The reason I haven't added it, even though it could theoretically be done, is because it would need a bit more consideration in song select filtering.
2. Kind of unrelated weirdness - the DA mod, while it can adjust OD which is supposed to have an effect on conversion, is applied after the `BeatmapConverter` is constructed, and constructing the `ManiaBeatmapConverter` immediately computes the number of columns. [Construction](https://github.com/ppy/osu/blob/a553387c3d77d7d4e695242939fe69c41190c63a/osu.Game/Beatmaps/WorkingBeatmap.cs#L262) -> [which immediately computes TargetColumns](https://github.com/ppy/osu/blob/a553387c3d77d7d4e695242939fe69c41190c63a/osu.Game.Rulesets.Mania/Beatmaps/ManiaBeatmapConverter.cs#L47) -> [and only after this is the `BeatmapDifficulty` adjusted](https://github.com/ppy/osu/blob/a553387c3d77d7d4e695242939fe69c41190c63a/osu.Game/Beatmaps/WorkingBeatmap.cs#L286-L293). 😅

### CODE REVIEW

**Comment by peppy** [comment]
I'm pretty on board with this change.

**Review by peppy — DISMISSED** [review]

**Review by peppy — APPROVED** [review]

**Comment by AzimovParviz** [comment]
@smoogipoo sorry for posting in such an old thread, but are there any plans for implementing key count filter akin to the difficulty range slider in the current version? Having to type keys:n is not the end of the world but I feel that having a key range slider, for example, would be a great QoL addition. Thank you

**Comment by smoogipoo** [comment]
No, but there'll be a grouping filter for it when song select is re-implemented.

**Comment by AzimovParviz** [comment]
> No, but there'll be a grouping filter for it when song select is re-implemented.

Thanks for answering! Good to know. Would it then be fine for me to make a PR for this feature whenever the grouping filter is implemented?

**Pull request merged**
