### PR TITLE
Add keyboard shortcuts to actuate mod select buttons

### PR DESCRIPTION
**Pull request by JackLee9355**
Added ability to reset all mods by pressing 1 as is currently present on stable. If I somehow messed up with only 5 lines sorry, new around here and just trying to get my footing.

### CODE REVIEW

**Comment by peppy** [comment]
Not sure if we're sticking with using 1/2/3 as the keys here, but if so, they should probably be signified on the buttons cc @arflyte

**Comment by peppy** [comment]
Please fix your issues rather than merging master into your branch.

**Comment by welsar55** [comment]
This was unintentional.

**Comment by peppy** [comment]
- Pressing 2 to close and then clicking the mod button to open doesn't work.
- Button animations don't play on using keybaord shortcuts.

**Review by peppy — CHANGES_REQUESTED** [review]
as mentioned

**Review by peppy — CHANGES_REQUESTED** [review]
as mentioned

**Comment by welsar55** [comment]
Addressed the mentioned issues. I will test more thoroughly in the future.

**Comment by peppy** [comment]
I've removed the visual element of this for the time being (since the main dialog overlay also does not visually show these shortcuts, even though they exist). We are waiting on a design for this. cc/ @arflyte

**Review by peppy — APPROVED** [review]

**Pull request merged**
