### PR TITLE
Add featured artist playlist category

### PR DESCRIPTION
**Pull request by peppy**
For near-future use. Tested against https://github.com/ppy/osu-web/pull/8967 to work correctly.

osu! 2022-05-27 at 11 17 32

Also updates the colour of spotlights playlist to match new specs (see https://github.com/ppy/osu-web/pull/8957).

### CODE REVIEW

**Review by smoogipoo — DISMISSED** [review]

**Review by smoogipoo — DISMISSED** [review]

**Comment by bdach** [comment]
The border colour on spotlights rooms used to match the badge, now it no longer does:

image

If that path is to be continued then we probably want to make the featured artist rooms also match as they're using the "open" colour right now:

image

I'll make the change if you're ok with that.

**Comment by bdach** [comment]
For reference, here's how these would look with the proposed changes:

image
image

**Comment by peppy** [comment]
I'm fine with either of the proposals, your call.

**Comment by bdach** [comment]
Have pushed my changes, see if you're OK with them. Ended up splitting a colour mapping method for `RoomCategory` given that the mapping is used in multiple components.

**Review by bdach — APPROVED** [review]

**Comment by peppy** [comment]
Looks good 👍

**Pull request merged**
