### PR TITLE
Tooltips

### PR DESCRIPTION
**Pull request by jorolf**
Depends on https://github.com/ppy/osu-framework/pull/645

### CODE REVIEW

**Comment by peppy** [comment]
- Please decouple tooltips from the mouse cursor. Make a new TooltipContainer and house them in that.
- Please update your PRs. They don't build against the framework PR you mention.
- Why do tooltips disappear when the mouse moves? They shouldn't.

**Comment by peppy** [comment]
If you want to make the tooltip avoid the cursor, you're welcome to pass a reference to the TooltipContainer with the cursor (do this in OsuGame i guess?). But you shouldn't be hard coupling the tooltip and cursor.

**Comment by peppy** [comment]
Now depends on https://github.com/ppy/osu-framework/pull/648

**Comment by peppy** [comment]
don't merge this just yet, one more bug i need to fix.

**Comment by smoogipooo** [comment]
Hovering over an element to show a tool tip, dragging outside, then releasing the mouse button will cause the tool tip to still be shown even though you're not hovering over the element anymore.

**Review by smoogipoo — APPROVED** [review]
Look great.

**Pull request merged**
