### PR TITLE
Show the specific pp value in `PerformanceBreakdown`

### PR DESCRIPTION
**Pull request by cdwcgt**
related to https://github.com/ppy/osu/discussions/20288

Round to two digits (`Math.Round(Value, 2, MidpointRounding.AwayFromZero)`)

<details><summary>what it looks like</summary>
std

image
taiko
image
mania
image
</details>

mania's performance calculates seen strange, total value is `difficult value * multiplier`
but it only a difficultyValue now, so I let `ManiaPerformanceAttributes.Difficulty` also multiply by multiplier

### CODE REVIEW

**Comment by Rian8337** [comment]
Pretty sure this was avoided in https://github.com/ppy/osu/pull/16483#issuecomment-1014628153? Will leave the discretion up to the team, though.

**Comment by cdwcgt** [comment]
So the percentage is retained. Specific value as extras
In some cases, players may prefer to know the specific value of for skill.
Such like using mod:
HD(acc aim affect)
FL(flashlight bonus)
DT(speed)

**Comment by bdach** [comment]
I disagree with this PR on a conceptual level.

As [I attempted to explain before](https://github.com/ppy/osu/pull/16483#issuecomment-1014610175), values of performance attributes *are not pp points*. They are random numbers that pp points are *synthesised* out of. You could theoretically have one attribute be in a range of [1, 100000], and another in the range of [0, 1].

Nobody should care about the raw values of these attributes unless they are directly modifying the performance points algorithm. Stuff like this belongs in osu-tools, but I claim that the value of showing this to the user using a method other than percentage is zero.

**Comment by peppy** [comment]
Agree. See discussion in linked PR (#16483).

**Pull request closed without merging**
