### PR TITLE
Add "Larger Circle" mod

### PR DESCRIPTION
**Pull request by ojh050118**
Mod for people who are difficult to osu! (I'm sorry about what happened yesterday)

### CODE REVIEW

**Comment by ojh050118** [comment]
> > Mod for people who are difficult to osu!
> 
> We already have "Easy" mod. Why do we need another one mod?

Increase circle size without affecting play.

**Comment by iiSaLMaN** [comment]
> Increase circle size without affecting game play.

Should be incompatible with `Easy`

**Comment by abraker95** [comment]
We need customizable CS and AR, not a million mods

**Comment by peppy** [comment]
Please wait for mod level settings, which will allow for this degree of customisation. If you are looking to improve the mobile situation, the playfield *itself* should be scaled larger to take up more of the screen as a first step.

**Pull request closed without merging**
