### PR TITLE
Fix global bindings being lost when running tests under headless contexts

### PR DESCRIPTION
**Pull request by peppy**
This was a shocking one to track down. Only affects rider certain methods of headless execution (rider's test panel for one).

Basically, `ResetDatabase` call was occurring after `OsuGameBase` initialises key bindings (via `KeyBindingStore.Register`, which would cause the `KeyBindingContainer` at the `OsuManualInputManagerTest` to have no bindings.

One could argue "wouldn't registering that one against the `KeyBindingStore` fix this?" but unfortunately, due to some level of EF caching, it decides it doesn't need to register the key bindings the second time around as it can still see the old ones (hits the `continue` part of the loop inside `insertDefaults`).

### CODE REVIEW

**Comment by bdach** [comment]
I *think* this is fine but can't seem to manage to get a setup in that would replicate this behaviour on `master` to be able to double-check that it fixes it...

**Comment by peppy** [comment]
The replication method is to run TestChangeSelectionViaKeyboardBeforeEnter in TestPlaySongSelect, by self, from rider

**Comment by bdach** [comment]
Aha, yep, there it is. Can confirm that the fail changes to a pass.

**Review by bdach — APPROVED** [review]

**Review by smoogipoo — APPROVED** [review]
I think this is fine

**Pull request merged**
