### PR TITLE
Limit vertical visibility of osu!catch playfield to an aspect ratio of 4:3

### PR DESCRIPTION
**Pull request by frenzibyte**
Before:

https://github.com/ppy/osu/assets/22781491/abeef2c7-5853-4d95-8d7b-2412d538e9ef

After:

https://github.com/ppy/osu/assets/22781491/2fcebe49-1f0a-4694-b625-f8917dc584f1

Note that for tall window resolutions, the cutoff also applies at the bottom of the playfield, keeping the invisible part of the catcher still invisible on tall resolutions:

CleanShot 2024-02-14 at 01 31 22

This is not really intended but it's simple to keep it cut for now. If it looks really bad, the logical solution would be to introduce a vertical border, but that's only cosmetic matters and can be handled separately.

### CODE REVIEW

**Comment by SecreOsu** [comment]
I'd like to ask about the optics of a score reset on all doubletime scores for catch on lazer due to the implications of this bug. This bug caused much higher approach rates to be able to be read than normal and could potentially have been abused. If wiping all catch doubletime scores isn't an option, then perhaps only ones that go above a certain approach rate??

**Comment by peppy** [comment]
> This is not really intended but it's simple to keep it cut for now. If it looks really bad, the logical solution would be to introduce a vertical border, but that's only cosmetic matters and can be handled separately.

In stable the catcher is not cut off. If this is just to keep things simple then it's fine for now, but I don't think it is a permanent solution as it looks pretty jank.

**Comment by frenzibyte** [comment]
I've kept it that way for simplicity yes. But that being said, how is there a behavior like this in stable? Does it support tall resolutions? I'm not a regular user of the client so I don't have much knowledge when it comes to that.

**Comment by bdach** [comment]
> But that being said, how is there a behavior like this in stable?

this sort of question is pretty annoying honestly. you have access to the client source, you can run it and debug it, you can check how it behaves. relying on everyone else to check this for you just pushes the workload onto others.

**Comment by frenzibyte** [comment]
Have discussed in [discord](https://discord.com/channels/188630481301012481/188630652340404224/1207523873256636477), and I can understand what's meant here now. Apparently, when playing catch in stable on 5:4 resolution, stable upscales the entire catch playfield, making the catcher not look cut off, with the caveat of the playfield becoming slightly out of bounds on the sides:

https://github.com/ppy/osu/assets/22781491/7be27822-2dcb-4300-8c7f-db64cb5c152d

(notice part of the catcher colliding with the edges)

As concluded in discord, I've altered the code to give space for the catcher to render its bottom part:

https://github.com/ppy/osu/assets/22781491/cc7c5b7a-d134-4663-9af6-c19a90af5640

**Review by peppy — APPROVED** [review]

**Pull request merged**
