### PR TITLE
Fix SR/BPM display showing no info in multiplayer playlist rooms

### PR DESCRIPTION
**Pull request by LeaUndercover**
Fixes the SR/BPM Display in Playlist Rooms, i can't find the issue in Multiplayer rooms.
Issue #24907

Multiplayer room freemod select : 
image

Multiplayer playlist freemod select : 
image

### CODE REVIEW

**Comment by Fabiano1337** [comment]
Just checked, multiplayer rooms in release don't have freemod info. Commits seems to fix both Multi Rooms and Playlists as shown in the Screenshots

**Comment by peppy** [comment]
I'm confused. How are you testing this? Your first commit [59d3143](https://github.com/ppy/osu/pull/24922/commits/59d3143645ce5af731bd52fc4a08fc12cc0268be) has a null check which was removed which brings up some serious questions, since it would have not worked correctly in the null case ever.

**Comment by Fabiano1337** [comment]
The check for `selected.Beatmap == null` was always true which is why i removed it in commit 2040dca, so the null case never happend

**Comment by Fabiano1337** [comment]
Testing was done the following :

- Compile and Launch
- Create multiplayer lobby
- Add map, Freemod On
- Choose Mods (thats where screenshot is from)
- Create multiplayer playlist
- Add map, Freemod On
- Choose Mods (where the second screenshot is from)

**Review by peppy — APPROVED** [review]

**Pull request merged**
