### PR TITLE
Update MostPlayedBeatmaps section in line with the web version

### PR DESCRIPTION
**Pull request by EVAST9919**

### CODE REVIEW

**Comment by peppy** [comment]
Please use the existing `LinkFlowContainer` and don't update link style locally to components.

**Comment by EVAST9919** [comment]
> Please use the existing `LinkFlowContainer` and don't update link style locally to components.

It's kinda hard to use 'LinkFlowContainer' with saving the web design, because we don't have a custom adjustment for links visual representation

**Comment by peppy** [comment]
What i'm saying is just use the style provided by `LinkFlowContainer`. It shouldn't be updated on a single component level (the global style should be consistent).

**Review by peppy — CHANGES_REQUESTED** [review]
Fix link formatting

**Comment by peppy** [comment]
Did you miss something in that last commit? It doesn't seem to be changing the link formatting at all.

**Comment by EVAST9919** [comment]
Looks like I still can't understand what we are trying to achieve here..

**Comment by peppy** [comment]
Removing the custom underline format is the main thing. Links should use the standard game-wide link format (and that will change if/when it does).

**Comment by EVAST9919** [comment]
Ah, alright

**Comment by smoogipoo** [comment]
I've made a few changes to bring the styling closer to osu-web:

image

In the future, please use exactly the same sizes as osu-web for everything.

@peppy requesting your review.

**Review by smoogipoo — DISMISSED** [review]

**Comment by peppy** [comment]
I guess this is okay, but what's the fascination with Y autosize on these rows? I looked for quite a while and couldn't figure what is providing the height. Should we not be hard-defining it and then use relative Y for children?

Feels very anti-developer at the moment.

**Review by peppy — APPROVED** [review]

**Pull request merged**
