### PR TITLE
Use float types for user visual levels

### PR DESCRIPTION
**Pull request by frenzibyte**
- Uses `float` type for user visual levels (`BlurLevel` and `DimLevel`) as it should've been.
- [x] Depends on ppy/osu-framework#2816

### CODE REVIEW

**Comment by peppy** [comment]
Have you tested that this transfers values correctly in cases users already had a value set?

**Comment by iiSaLMaN** [comment]
Bringing this topic here: `BlurLevel` sometimes have `0.39999..` instead of `0.4`, not sure whether to round that value or just close this PR?

**Comment by bdach** [comment]
I'm not near a C# interactive shell right now, but I'm almost sure neither `double` or `float` can ever accurately represent a value of 0.4 due to the fact base 10 fractions don't work well with IEEE 754 floating point representations. You might get slightly *over* 0.4, instead of slightly under, but this should be handled at display time regardless of type, and for graphics calculations, if there are no extreme usages, single precision should be okay. Key thing to check at this point is that this migration doesn't mangle existing user preferences, as we're going from a more precise type to a less precise one - so you want to make sure no *horrific* truncations will take place (small ones are natural and expected in cases like this)

**Comment by iiSaLMaN** [comment]
Closing this PR for now, will work on to later.

**Pull request closed without merging**
