### PR TITLE
Change precision of replay playback speed text

### LINKED ISSUE #1618: Playback slider tooltip and text show values of different precision
Playback speed slider in replays/autoplay have a tooltip and a text for their value with different precision. These should be the same or the tooltip may be entirely unnecessary here.

qq

### PR DESCRIPTION
**Pull request by aurelilia**
Closes #1618

### CODE REVIEW

**Review by peppy — APPROVED** [review]

**Comment by smoogipoo** [comment]
no

**Comment by peppy** [comment]
apparently no

**Review by peppy — CHANGES_REQUESTED** [review]
revoking review pending no

**Review by smoogipoo — CHANGES_REQUESTED** [review]
I believe this needs a change to fix sliderbar display in the general case (e.g. where we want more than 1 d.p of accuracy) rather than this. Am currently in the process of doing this myself.

**Comment by peppy** [comment]
Closing in favour of #1856, which implements this in a more global and flexible way.

**Pull request closed without merging**
