### PR TITLE
Couple the editor waveform timeline to the audio

### PR DESCRIPTION
**Pull request by smoogipoo**
Prereqs:
- [x] https://github.com/ppy/osu/pull/2581

If the track is playing:
* Wheel input doesn't do anything.
* Timeline follows the audio.
* If user click-drags:
  * Audio stops.
  * Timeline scrolls with mouse, audio follows timeline.
  * No flicking / smooth scrolling.
  * Audio resumes upon releasing mouse.

If the track isn't playing:
* Retains smooth scrolling.

Video: https://streamable.com/guinl

### CODE REVIEW

**Comment by peppy** [comment]
`TestCaseEditorComposeTimeline` is crashing with:

image

Is this expected?

**Comment by peppy** [comment]
The test case doesn't play music and doesn't seem to be usable for me.

**Comment by peppy** [comment]
Is adding the circles.ogg a second time required? Can we not just use the resources copy (the resources project is already referenced so it should be accessible).

**Comment by smoogipoo** [comment]
The one in the resources rests within a .osz.

**Review by peppy — APPROVED** [review]

**Pull request merged**
