### PR TITLE
Rewrite `TestSceneScoresContainer` to work again

### PR DESCRIPTION
**Pull request by peppy**
Has been broken for the longest time. Catches one failure mentioned in the realm PR (have tested).

### CODE REVIEW

**Comment by smoogipoo** [comment]
Is there supposed to be a difference between the `Load scores with my best` and `Load scores with null my best` steps? They look identical.

**Comment by peppy** [comment]
I... didn't check that deep, just moved that into the right place. Will do another pass.

**Comment by peppy** [comment]
Turns out the user best wasn't even being displayed in these tests  due to missing `OnlineID` (realm branch, anyway).

**Review by smoogipoo — DISMISSED** [review]

**Comment by smoogipoo** [comment]
Test failure looks relevant :smile:

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
