### PR TITLE
Visualization of change in star difficulty from applied mods

### LINKED ISSUE #3270: Proposal for visualization of difficulty change from applying mods
Sometimes when I'm playing osu with mods, I'm curious as to what star level the map was before applying the mod, but I don't want to switch to no mod and back to find out. So I created this:
modincreaseddifficultystarvisualization
moddecreaseddifficultystarvisualization
The original star level is preserved in white and extra stars in yellow or green (matching the color for the type in the mod select menu) are added to show the star level after applying all mods.
I'm not sure this is any good, so if you don't like it feel free to say so and close the issue, but if you do like it, I have code I can PR.

Note: For this I also created code to dynamically update star difficulty to account for selected mods & modes. It works by creating a difficulty calculator from the ruleset and then using that to calculate updated difficulties. Do you want me to PR this? I know you guys have been working on database stuff to do that anyways, so you might not want this implementation.

### PR DESCRIPTION
**Pull request by zachllogan**
- Closes #3270

---

Adds the ability for StarCounter to visualize the change in difficulty do to applied mods.
moddifficultystarvisualization

### CODE REVIEW

**Comment by peppy** [comment]
Please add visual tests for this behaviour. Also, we'll need to run this past @arflyte to get his take on it.

**Comment by peppy** [comment]
The transition looks quite weird when going from no change to reduction:



The first start flashes many times, meaning it's probably having too many transforms applied to it.

Also it's a bit weird that reduction animates from the far left, but increase animated from the no-change star count.

**Comment by smoogipoo** [comment]
Has this PR been abandoned? @zachllogan

**Comment by zachllogan** [comment]
@smoogipoo It has not. I just have not had any time to work on it for a while.

**Comment by peppy** [comment]
@smoogipoo i think you recently added support for this, but didn't add the design portion showing that a change has been made. can probably close this but i think we probably want a better display showing that stars are modified by mods?

**Comment by smoogipoo** [comment]
We do. Not sure how usable this PR is though...

**Comment by peppy** [comment]
Probably worth looking at whether we can salvage this one rather than close it?

**Comment by smoogipoo** [comment]
I think there's going to be a long time before this is merged. We first need Realm support to implement disk caching of diffcalc results - we previously did try to display modded SR on each panel but that caused a lot of lag. And Realm has been going on for about 2 years already, so hard to say how long that's going to take.

**Comment by peppy** [comment]
Are you sure we need realm for this? Isn't it just calculating the difficulties of visible beatmaps? Is that the part we turned off?

**Comment by peppy** [comment]
Let's just close this one for now I think. The code quality isn't amazing.

**Comment by smoogipoo** [comment]
My mistake, we already calculate the difficulty of all visible beatmaps - didn't realise this was still the case. It's just these ones that aren't recalculated:
image

So something like this can happen :)

**Pull request closed without merging**
