### PR TITLE
Adjust song select background dimming to be more evenly applied

### LINKED ISSUE #22652: Editor randomly fails to unblur background on entering
### Type

Cosmetic

### Bug description

Found when reviewing https://github.com/ppy/osu/pull/22645.

Background is supposed to unblur on entering editor:

https://github.com/ppy/osu/blob/24961d1ac080588b16039f9a34c8e7f806626b27/osu.Game/Screens/Edit/Editor.cs#L666-L674

but it sometimes doesn't happen. I have no idea why. I am suspecting some sort of schedule-related race because `SongSelect` does a lot of scheduling on the `ApplyToBackground()` actions.

Not 100% reproducible, it's a bit trial-and-error. I believe this is best reproduced when attempting to edit a converted beatmap (i.e. with mania ruleset selected, go to editor for an osu! map).

### Screenshots or videos

https://user-images.githubusercontent.com/20418176/219110027-c07de6bf-6841-4940-bca4-c268d3530ef8.mp4

### Version

current master

### Logs

\-

### PR DESCRIPTION
**Pull request by peppy**
There were a few comments around the place over song select looking too bright when blur is disabled. Which is most definitely is. This is due to dim not being applied at all to the portion of the background which isn't covered by the "wedge" on the left.

To fix this, I've changed the global background dim at song select to match osu-stable, then reduced the additional dimming of the wedge. I tried applying to the blurred version as well, but it looks bad so I fenced the change off to only when blur is not applied. For those interested, reverting the second commit can allow testing with blur on too.

| before | after |
| -- | -- |
|osu! 2023-02-15 at 05 02 28|osu! 2023-02-15 at 05 15 41|
|osu! 2023-02-15 at 05 02 41|osu! 2023-02-15 at 05 15 30|

Closes #22652 indirectly.

### CODE REVIEW

**Comment by bdach** [comment]
In a vacuum this diff is fine - but when reviewing this I spotted https://github.com/ppy/osu/issues/22652, mostly because these changes exacerbate that issue. One of the two `ApplyToBackground()` calls that appear to be racing and causing that issue is now regulating dim as well as blur level with the changes in this PR, leading to this happening:

https://user-images.githubusercontent.com/20418176/219111426-61f15d56-b7b3-4882-84cf-144e01e5781b.mp4

I'm not super sure but it *feels* like it's a bit of a blocker in that respect...

**Review by bdach — CHANGES_REQUESTED** [review]
as above

**Comment by peppy** [comment]
While I was working on this code it seemed dangerous, so I'm almost glad that you picked up on that one!

I believe this is due to the delayed calling of `updateComponentFromBeatmap`, will look into it.

**Comment by peppy** [comment]
I've fixed this in https://github.com/ppy/osu/pull/22645/commits/394d368f165431e7bb58bc4d365ee7f7fbb6614b. Not sure how to make a test specifically for it, but the assert I added got hit multiple times in a full test suite run, so we can probably rely on brute force testing?

**Comment by bdach** [comment]
> the assert I added got hit multiple times in a full test suite run, so we can probably rely on brute force testing?

I double-checked that this is the case, and agree that that is enough.

I've fixed a code quality issue spurred by NRT enable in `ScreenWithBackgroundBeatmap` (https://github.com/ppy/osu/pull/22645/commits/ad5132ed4194380bae37331b2746333a5acead3f); seems good otherwise :+1:

**Review by bdach — APPROVED** [review]

**Pull request merged**
