### PR TITLE
Use better colours for system mods

### PR DESCRIPTION
**Pull request by bdach**
Reasoning: https://github.com/ppy/osu/pull/25348#discussion_r1382988284

| | master | this PR |
| :- | :-: | :-: |
| `ModIcon` |  |  |
| `ModSwitchSmall` (inactive) |  |  |
| `ModSwitchSmall` (active) |  |  |
| `ModSwitchTiny` (inactive) |  |  |
| `ModSwitchTiny` (active) |  |  |

### CODE REVIEW

**Comment by peppy** [comment]
I'm wondering if `ModSwitchTiny` would look better with the colours flipped..

**Comment by bdach** [comment]
> I'm wondering if `ModSwitchTiny` would look better with the colours flipped..

`ModSwitchSmall` nests a tiny so it affects both. Something like that look okay?

**Comment by Tanza3D** [comment]
must say SV2 looks really wonky on the small ones but I guess that's unrelated to this PR

**Comment by bdach** [comment]
It's also generally mostly unrelated for now; the only usage of SV2 is legacy stable scores and the only place these will ever show is mod icons on the local leaderboard, i.e. the thingies on the first 2 screenshots in the OP.

May be something that needs addressing further with song select redesigns, but yeah I'm generally not looking to fix it here.

**Comment by peppy** [comment]
I meant inverting the grey/yellow, if that's feasible. Your latest screenshots look to be using the more black fill.

**Comment by bdach** [comment]
Like such?



Or such?



I feel like the first doesn't look great, and with the second the background seems way too bright...?

**Comment by peppy** [comment]
I might be missing something very obvious, but this is what I was trying to propose:

```diff
diff --git a/osu.Game/Graphics/OsuColour.cs b/osu.Game/Graphics/OsuColour.cs
index 2e19eac572..a417164e27 100644
--- a/osu.Game/Graphics/OsuColour.cs
+++ b/osu.Game/Graphics/OsuColour.cs
@@ -162,7 +162,7 @@ public Color4 ForModType(ModType modType)
                     return Pink1;
 
                 case ModType.System:
-                    return Gray5;
+                    return Yellow;
 
                 default:
                     throw new ArgumentOutOfRangeException(nameof(modType), modType, "Unknown mod type");
diff --git a/osu.Game/Rulesets/UI/ModIcon.cs b/osu.Game/Rulesets/UI/ModIcon.cs
index d09db37f2a..d1776c5c0b 100644
--- a/osu.Game/Rulesets/UI/ModIcon.cs
+++ b/osu.Game/Rulesets/UI/ModIcon.cs
@@ -204,9 +204,7 @@ private void updateExtendedInformation()
 
         private void updateColour()
         {
-            modAcronym.Colour = modIcon.Colour = mod.Type != ModType.System
-                ? OsuColour.Gray(84)
-                : colours.Yellow;
+            modAcronym.Colour = modIcon.Colour = OsuColour.Gray(84);
 
             extendedText.Colour = background.Colour = Selected.Value ? backgroundColour.Lighten(0.2f) : backgroundColour;
             extendedBackground.Colour = Selected.Value ? backgroundColour.Darken(2.4f) : backgroundColour.Darken(2.8f);
diff --git a/osu.Game/Rulesets/UI/ModSwitchSmall.cs b/osu.Game/Rulesets/UI/ModSwitchSmall.cs
index 452a5599ba..6e96cc8e6f 100644
--- a/osu.Game/Rulesets/UI/ModSwitchSmall.cs
+++ b/osu.Game/Rulesets/UI/ModSwitchSmall.cs
@@ -88,12 +88,10 @@ private void load(TextureStore textures, OsuColour colours, OverlayColourProvide
             var modTypeColour = colours.ForModType(mod.Type);
 
             inactiveForegroundColour = colourProvider?.Background5 ?? colours.Gray3;
-            activeForegroundColour = mod.Type != ModType.System ? modTypeColour : colours.Yellow;
+            activeForegroundColour = modTypeColour;
 
             inactiveBackgroundColour = colourProvider?.Background2 ?? colours.Gray5;
-            activeBackgroundColour = mod.Type != ModType.System
-                ? Interpolation.ValueAt<Colour4>(0.1f, Colour4.Black, modTypeColour, 0, 1)
-                : modTypeColour;
+            activeBackgroundColour = Interpolation.ValueAt<Colour4>(0.1f, Colour4.Black, modTypeColour, 0, 1);
         }
 
         protected override void LoadComplete()
diff --git a/osu.Game/Rulesets/UI/ModSwitchTiny.cs b/osu.Game/Rulesets/UI/ModSwitchTiny.cs
index bb121c085c..4d50e702af 100644
--- a/osu.Game/Rulesets/UI/ModSwitchTiny.cs
+++ b/osu.Game/Rulesets/UI/ModSwitchTiny.cs
@@ -112,9 +112,7 @@ private void load(OsuColour colours, OverlayColourProvider? colourProvider)
             activeBackgroundColour = modTypeColour;
 
             inactiveForegroundColour = colourProvider?.Background2 ?? colours.Gray5;
-            activeForegroundColour = Mod.Type != ModType.System
-                ? Interpolation.ValueAt<Colour4>(0.1f, Colour4.Black, modTypeColour, 0, 1)
-                : colours.Yellow;
+            activeForegroundColour = Interpolation.ValueAt<Colour4>(0.1f, Colour4.Black, modTypeColour, 0, 1);
         }
 
         protected override void LoadComplete()

```

**Comment by bdach** [comment]
Sure, applied. I got confused because you mentioned only one switch type and mentioned switching the colours around rather than "just pick yellow for system mods".

Works for me. We'll probably need to beat web into shape to match but that generally needs to happen across the board anyway.

**Review by peppy — APPROVED** [review]

**Pull request merged**
