### PR TITLE
Reflect nested objects in the playfield correctly

### LINKED ISSUE #21561: Slider ticks are broken when putting Hard Rock and Mirror in osu! ruleset
### Type

Game Behavior

### Bug description

Encountered this a while ago when I was testing some maps with HR and I noticed that slider ticks are way off the sliderbody. No mod seems fine just adding HR makes slidertick broken.

### Screenshots or videos

https://user-images.githubusercontent.com/85861916/206177310-b2430819-ad61-4d86-baef-6083827d32c8.mp4

https://user-images.githubusercontent.com/85861916/206179852-d71f9fa9-0ce0-47f9-81ce-a145c42de817.mp4

### Version

2022.1207.0

### Logs

[database.log](https://github.com/ppy/osu/files/10175952/database.log)
[performance.log](https://github.com/ppy/osu/files/10175953/performance.log)
[runtime.log](https://github.com/ppy/osu/files/10175954/runtime.log)

### PR DESCRIPTION
**Pull request by apollo-dw**
Resolves https://github.com/ppy/osu/issues/21561

Fixes a regression in behaviour from https://github.com/ppy/osu/commit/8f3023ffd9c64c91258e3d7642d57f8431c12cd4. The nested hit objects were being reflected incorrectly, causing a strange effect on SR when mirroring mods (such as Hard Rock) were applied [(see this as an example, should be 5.84*).](https://cdn.discordapp.com/attachments/757615676310552598/1050138330739769365/osu_2022-12-07_14-52-36.jpg)

### CODE REVIEW

**Comment by bdach** [comment]
> No, the issue was that the repositioning of the slider ticks in `ReflectHorizontally()` and `ReflectVertically()` was handled incorrectly. Since the positions of nested objects are absolute (and not relative to the slider's position), they should be reflected just like the slider (e.g. `nested.Position = new Vector2(nested.X, OsuPlayfield.BASE_SIZE.Y - nested.Y`); for reflecting them horizontally), but what I did was flipping the slider ticks around the position of the slider, which is wrong.

Upon some more reflection I figured that what was *probably* intended in the original PR was to decompose the playfield reflection into a flip about the slider head and a translation to move the slider across to complete the reflection in playfield terms. But I think the reason why that didn't work is that the `.Position` assignment prior to the flip brought the slider to an inconsistent state and made the flip just fail entirely.

Something like this applied onto `master` works better:

```csharp
FlipSliderHorizontally(slider);
float targetX = OsuPlayfield.BASE_SIZE.X - slider.X;
float deltaX = targetX - slider.X;
modifySlider(slider, ho => ho.Position = new Vector2(ho.X + deltaX, ho.Y), _ => { });
osuObject.Position = new Vector2(OsuPlayfield.BASE_SIZE.X - osuObject.X, osuObject.Position.Y);
```

but at that point I prefer this PR as it is.

**Comment by Pasi4K5** [comment]
> Upon some more reflection I figured that what was _probably_ intended in the original PR was to decompose the playfield reflection into a flip about the slider head and a translation to move the slider across to complete the reflection in playfield terms.

Correct, that was what `ReflectHorizontally()` and `ReflectVertically()` were intended to do.

**Comment by bdach** [comment]
I've pushed some menial cleanups, and added a test covering the desired behaviour of all three methods involved in this mess.

I think this is in a better place now, but I will ask for a re-review before proceeding.

**Review by bdach — APPROVED** [review]

**Comment by peppy** [comment]
When reviewing the original, I was under the false assumption that the changed code was local to mirror mod, not shared across the whole game. I guess that happened at some point. Shows the value in having proper test coverage over these kinds of central functions, for sure.

**Review by peppy — APPROVED** [review]

**Pull request merged**
