### PR TITLE
Prevent overlays from showing in intro/outro sequences

### LINKED ISSUE #2461: Overlays are openable during intro and exit transitions
Video shows it all really
https://youtu.be/gvlq2V0StRM

### PR DESCRIPTION
**Pull request by Aergwyn**
closes #2461

An alternative I found would be to add it right in `OsuGame.OnPressed` but that would basically stop all global keybinds...

### CODE REVIEW

**Comment by peppy** [comment]
This stops overlays from being shown in many other screens (due to the interaction with `ShowOverlaysOnEnter`).

Also let's rename all instances of `ShowOverlays` to `AllowOverlays` and `ShowOverlaysOnEnter` to `HideOverlaysOnEnter` (requires logic inversion).

**Review by peppy — CHANGES_REQUESTED** [review]
as proposed

**Comment by Aergwyn** [comment]
In which screens is it supposed to show them which they aren't?
With this change `HideOverlaysOnEnter = true` prevents them to open as long as you are on the screen.
Was it supposed to only close them on entering/resuming once? I'm a bit confused what seems to be wrong.

**Comment by peppy** [comment]
The only screens which should completely disallow overlays should be the intro/outro. All others should be unaffected by your PR (currently it's applying to all screens which override that property).

**Review by peppy — APPROVED** [review]

**Pull request merged**
