### PR TITLE
Fix `Disclaimer` screen handling user change events after initial display

### PR DESCRIPTION
**Pull request by peppy**
Unnecessary overhead, but also should resolve a production hard crash.

### CODE REVIEW

**Comment by peppy** [comment]
I briefly looked into how the `First()` call could fail, but couldn't find anything immediately. Not sure if anyone wants to dig deeper, but probably not too important, and related to `supportFlow`'s children being `Expire`d on completion of the animation.

**Comment by smoogipoo** [comment]
I... Don't think the `.Drawables` reference is safe _at all_.

It seems like it should fail exactly when `!TextFlowContainer.partsCache.IsValid`, which should actually be pretty much all the time here.

**Comment by peppy** [comment]
Should it not be exposed in that case? Is there a better way of doing this?

**Comment by bdach** [comment]
`ITextPart.Drawables` is pretty unsafe now that I think about it. The point of it was to accommodate weird osu! usages without blowing everything up. Probably a bad idea, in retrospect.

As for what *should* be better, there's a [`DrawablePartsRecreated`](https://github.com/ppy/osu-framework/blob/2d4142c5433492868f1ba7a2f670afeb84a9e906/osu.Framework/Graphics/Containers/ITextPart.cs#L27) event. The event delegate argument should be always safe to access.

**Comment by smoogipoo** [comment]
To clarify, it seems that the code is originally being saved by this `RecreateAllParts()` call in `TextFlowContainer.LoadAsyncComplete()`:
https://github.com/ppy/osu-framework/blob/2414ddfa19a7fa96a5ccad1966a8c2ef0620ed47/osu.Framework/Graphics/Containers/TextFlowContainer.cs#L147-L153
Which just so happens to occur before this code in `Disclaimer.load()` is called for the first time. That then causes the part's drawables to be created immediately upon `AddLink()` (`AddText()`).

I'm not sure exactly of the proper way to handle this but possibly storing the result of the inner expression could work. Something like this:
```diff
diff --git a/osu.Game/Screens/Menu/Disclaimer.cs b/osu.Game/Screens/Menu/Disclaimer.cs
index 24412cd85e..fe0396031a 100644
--- a/osu.Game/Screens/Menu/Disclaimer.cs
+++ b/osu.Game/Screens/Menu/Disclaimer.cs
@@ -146,16 +146,17 @@ private void load(OsuColour colours)
                     supportFlow.AddText(" to help support osu!'s development", formatSemiBold);
                 }

-                heart = supportFlow.AddIcon(FontAwesome.Solid.Heart, t =>
+                supportFlow.AddIcon(FontAwesome.Solid.Heart, t =>
                 {
+                    heart = t;
+
                     t.Padding = new MarginPadding { Left = 5, Top = 3 };
                     t.Font = t.Font.With(size: 20);
                     t.Origin = Anchor.Centre;
                     t.Colour = colours.Pink;
-                }).Drawables.First();

-                if (IsLoaded)
-                    animateHeart();
+                    Schedule(animateHeart);
+                });

                 if (supportFlow.IsPresent)
                     supportFlow.FadeInFromZero(500);
@@ -247,7 +248,7 @@ private string getRandomTip()

         private void animateHeart()
         {
-            heart.FlashColour(Color4.White, 750, Easing.OutQuint).Loop();
+            heart?.FlashColour(Color4.White, 750, Easing.OutQuint).Loop();
         }
     }
 }
```
@bdach thoughts?

**Comment by smoogipoo** [comment]
> As for what _should_ be better, there's a [`DrawablePartsRecreated`](https://github.com/ppy/osu-framework/blob/2d4142c5433492868f1ba7a2f670afeb84a9e906/osu.Framework/Graphics/Containers/ITextPart.cs#L27) event. The event delegate argument should be always safe to access.

It's kind of weird, right? Because that will get called immediately upon the call, so you couldn't:
```
var part = AddText(..);
part.DrawablePartsRecreated += ...; // Event missed from the above call.
```

**Comment by bdach** [comment]
Yeah, you're right, it wouldn't get the initial call.

In fact when I side-eye all existing usages of `ITextPart.Drawables` all but one look wrong (especially `DrawableLinkCompiler`, which looks *comically* wrong). The only use case that actually looks to require it is in `ScreenEntry` (part of the registration flow), which is used for the cool colour change effect when the password length changes.

Maybe the thing to do here is a framework fix? Add a lock to `TextPart` and copy out the drawables list outwardly to protect against badness?

**Comment by bdach** [comment]
I haven't tested if @smoogipoo's version works but if it does then I'm fine with going with that for the time being.

**Comment by peppy** [comment]
I can try applying that as well. If it doesn't break things it seems like an improvement. But I'd also want to block it from running at all post-suspend.

**Comment by bdach** [comment]
Yeah, for sure.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
