### PR TITLE
Add more beat snap divisors (with panel feature)

### LINKED ISSUE #2316: Add support for unusual beat snaps
There are rare cases where 1/5 or 1/7 beatsnap is used in a song. This is uncommon, but some songs are simply unrankable due to this.
https://osu.ppy.sh/s/647360 - Example of a 1/5 map that could easily be ranked if 1/5 was supported

The current workaround to 1/5 is to multiply the bpm by five, use 1/1 snapping, and have a 5/4 meter. It's dumb.

Because 1/5 and other weird snaps are so uncommon, they should only be accessible via an extra panel or by editing the .osu file, else new mappers would be confused by them. Regardless, it needs support somehow

### PR DESCRIPTION
**Pull request by Rekkonnect**
Closes [#2316](https://github.com/ppy/osu/issues/2316)

Details:
- Added the following beat snap divisors: 1/32, 1/9, 1/18, 1/24, 1/5, 1/7, 1/11
- Added panels fearure to switch between the Normal, Triplets and Other beat snap divisors:
- - Normal: 1/2, 1/4, 1/8, 1/16, 1/32
- - Triplets: 1/3, 1/6, 1/9, 1/12, 1/18, 1/24
- - Other: 1/5, 1/7, 1/11
- Added feature to keep the last used beat snap divisor in each panel which is set when switching back to one panel.

### CODE REVIEW

**Comment by peppy** [comment]
This PR is a bit out-of-date, but I've brought the code up to standards by transplanting on to master.

The UX offered by this implementation is still not too bad. May be worth considering, at least as a reference.

```diff
diff --git a/osu.Game.Tests/Visual/Editing/TestSceneBeatDivisorControl.cs b/osu.Game.Tests/Visual/Editing/TestSceneBeatDivisorControl.cs
index ed7bb9e301..1816138003 100644
--- a/osu.Game.Tests/Visual/Editing/TestSceneBeatDivisorControl.cs
+++ b/osu.Game.Tests/Visual/Editing/TestSceneBeatDivisorControl.cs
@@ -33,16 +33,16 @@ public class TestSceneBeatDivisorControl : OsuManualInputManagerTestScene
                 Size = new Vector2(90, 90)
             };
 
-            tickSliderBar = beatDivisorControl.ChildrenOfType<SliderBar<int>>().Single();
-            tickMarkerHead = tickSliderBar.ChildrenOfType<EquilateralTriangle>().Single();
+            tickSliderBar = beatDivisorControl.ChildrenOfType<SliderBar<int>>().SingleOrDefault();
+            tickMarkerHead = tickSliderBar.ChildrenOfType<EquilateralTriangle>().SingleOrDefault();
         });
 
         [Test]
         public void TestBindableBeatDivisor()
         {
-            AddRepeatStep("move previous", () => bindableBeatDivisor.Previous(), 4);
+            AddRepeatStep("move previous", () => bindableBeatDivisor.PreviousNormalDivisor(), 4);
             AddAssert("divisor is 4", () => bindableBeatDivisor.Value == 4);
-            AddRepeatStep("move next", () => bindableBeatDivisor.Next(), 3);
+            AddRepeatStep("move next", () => bindableBeatDivisor.NextNormalDivisor(), 3);
             AddAssert("divisor is 12", () => bindableBeatDivisor.Value == 12);
         }
 
diff --git a/osu.Game/Screens/Edit/BindableBeatDivisor.cs b/osu.Game/Screens/Edit/BindableBeatDivisor.cs
index 1a350d7261..a3abed1313 100644
--- a/osu.Game/Screens/Edit/BindableBeatDivisor.cs
+++ b/osu.Game/Screens/Edit/BindableBeatDivisor.cs
@@ -9,18 +9,96 @@
 
 namespace osu.Game.Screens.Edit
 {
-    public class BindableBeatDivisor : BindableInt
+    public class BindableBeatDivisor : BindableNumber<int>
     {
-        public static readonly int[] VALID_DIVISORS = { 1, 2, 3, 4, 6, 8, 12, 16 };
+        private DivisorPanelType panel = DivisorPanelType.Normal;
+
+        public int LastNormalDivisor = 1;
+        public int LastTripletDivisor = 1;
+        public int LastOtherDivisor = 1;
+
+        public static readonly int[] VALID_DIVISORS = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 11, 12, 16, 18, 24, 32 };
+        public static readonly int[] VALID_NORMAL_DIVISORS = { 1, 2, 4, 8, 16, 32 };
+        public static readonly int[] VALID_TRIPLET_DIVISORS = { 1, 3, 6, 9, 12, 18, 24 };
+        public static readonly int[] VALID_OTHER_DIVISORS = { 1, 5, 7, 11 };
+
+        /// <summary>An event that occurs when the <see cref="ValidDivisors"/> property has changed.</summary>
+        public event Action ValidDivisorsChanged;
 
         public BindableBeatDivisor(int value = 1)
             : base(value)
         {
         }
 
-        public void Next() => Value = VALID_DIVISORS[Math.Min(VALID_DIVISORS.Length - 1, Array.IndexOf(VALID_DIVISORS, Value) + 1)];
+        /// <summary>Triggers the <see cref="ValidDivisorsChanged"/> event.</summary>
+        public virtual void TriggerValidDivisorsChanged()
+        {
+            ValidDivisorsChanged?.Invoke();
+        }
+
+        public void NextPanel()
+        {
+            Panel = (DivisorPanelType)((int)(panel + 1) % 3);
+        }
+
+        public void PreviousPanel()
+        {
+            Panel = (DivisorPanelType)((int)(panel + 2) % 3);
+        }
+
+        public void NextDivisor()
+        {
+            switch (panel)
+            {
+                case DivisorPanelType.Normal:
+                    NextNormalDivisor();
+                    return;
+
+                case DivisorPanelType.Triplets:
+                    NextTripletDivisor();
+                    return;
+
+                case DivisorPanelType.Other:
+                    NextOtherDivisor();
+                    return;
+
+                default:
+                    return;
+            }
+        }
+
+        public void PreviousDivisor()
+        {
+            switch (panel)
+            {
+                case DivisorPanelType.Normal:
+                    PreviousNormalDivisor();
+                    return;
+
+                case DivisorPanelType.Triplets:
+                    PreviousTripletDivisor();
+                    return;
+
+                case DivisorPanelType.Other:
+                    PreviousOtherDivisor();
+                    return;
+
+                default:
+                    return;
+            }
+        }
+
+        public void NextNormalDivisor() => Value = VALID_NORMAL_DIVISORS[Math.Min(VALID_NORMAL_DIVISORS.Length - 1, Array.IndexOf(VALID_NORMAL_DIVISORS, Value) + 1)];
+
+        public void PreviousNormalDivisor() => Value = VALID_NORMAL_DIVISORS[Math.Max(0, Array.IndexOf(VALID_NORMAL_DIVISORS, Value) - 1)];
+
+        public void NextTripletDivisor() => Value = VALID_TRIPLET_DIVISORS[Math.Min(VALID_TRIPLET_DIVISORS.Length - 1, Array.IndexOf(VALID_TRIPLET_DIVISORS, Value) + 1)];
+
+        public void PreviousTripletDivisor() => Value = VALID_TRIPLET_DIVISORS[Math.Max(0, Array.IndexOf(VALID_TRIPLET_DIVISORS, Value) - 1)];
+
+        public void NextOtherDivisor() => Value = VALID_OTHER_DIVISORS[Math.Min(VALID_OTHER_DIVISORS.Length - 1, Array.IndexOf(VALID_OTHER_DIVISORS, Value) + 1)];
 
-        public void Previous() => Value = VALID_DIVISORS[Math.Max(0, Array.IndexOf(VALID_DIVISORS, Value) - 1)];
+        public void PreviousOtherDivisor() => Value = VALID_OTHER_DIVISORS[Math.Max(0, Array.IndexOf(VALID_OTHER_DIVISORS, Value) - 1)];
 
         public override int Value
         {
@@ -28,21 +106,68 @@ public override int Value
             set
             {
                 if (!VALID_DIVISORS.Contains(value))
+                    throw new ArgumentOutOfRangeException($"Provided divisor is not in {nameof(VALID_DIVISORS)}");
+
+                base.Value = value;
+            }
+        }
+
+        public DivisorPanelType Panel
+        {
+            get => panel;
+            set
+            {
+                switch (panel)
                 {
-                    // If it doesn't match, value will be 0, but will be clamped to the valid range via DefaultMinValue
-                    value = Array.FindLast(VALID_DIVISORS, d => d < value);
+                    case DivisorPanelType.Normal:
+                        LastNormalDivisor = Value;
+                        goto default;
+
+                    case DivisorPanelType.Triplets:
+                        LastTripletDivisor = Value;
+                        goto default;
+
+                    case DivisorPanelType.Other:
+                        LastOtherDivisor = Value;
+                        goto default;
+
+                    default:
+                        TriggerValidDivisorsChanged();
+                        break;
                 }
 
-                base.Value = value;
+                panel = value;
+
+                switch (panel)
+                {
+                    case DivisorPanelType.Normal:
+                        ValidDivisors = VALID_NORMAL_DIVISORS;
+                        base.Value = LastNormalDivisor;
+                        goto default;
+
+                    case DivisorPanelType.Triplets:
+                        ValidDivisors = VALID_TRIPLET_DIVISORS;
+                        base.Value = LastTripletDivisor;
+                        goto default;
+
+                    case DivisorPanelType.Other:
+                        ValidDivisors = VALID_OTHER_DIVISORS;
+                        base.Value = LastOtherDivisor;
+                        goto default;
+
+                    default:
+                        TriggerValidDivisorsChanged();
+                        return;
+                }
             }
         }
 
+        public int[] ValidDivisors = VALID_NORMAL_DIVISORS;
+
         protected override int DefaultMinValue => VALID_DIVISORS.First();
         protected override int DefaultMaxValue => VALID_DIVISORS.Last();
         protected override int DefaultPrecision => 1;
 
-        protected override Bindable<int> CreateInstance() => new BindableBeatDivisor();
-
         /// <summary>
         /// Retrieves the appropriate colour for a beat divisor.
         /// </summary>
@@ -101,4 +226,11 @@ public static int GetDivisorForBeatIndex(int index, int beatDivisor)
             return 0;
         }
     }
+
+    public enum DivisorPanelType
+    {
+        Normal = 0,
+        Triplets = 1,
+        Other = 2
+    }
 }
diff --git a/osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs b/osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs
index de63b265d2..4cc1f325a4 100644
--- a/osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs
+++ b/osu.Game/Screens/Edit/Compose/Components/BeatDivisorControl.cs
@@ -13,6 +13,7 @@
 using osu.Framework.Graphics.Sprites;
 using osu.Framework.Graphics.UserInterface;
 using osu.Framework.Input.Events;
+using osu.Framework.Input.States;
 using osu.Game.Graphics;
 using osu.Game.Graphics.UserInterface;
 using osuTK;
@@ -23,6 +24,8 @@ namespace osu.Game.Screens.Edit.Compose.Components
 {
     public class BeatDivisorControl : CompositeDrawable
     {
+        private DivisorPanelText panelText;
+        private DivisorText divisorText;
         private readonly BindableBeatDivisor beatDivisor = new BindableBeatDivisor();
 
         public BeatDivisorControl(BindableBeatDivisor beatDivisor)
@@ -62,7 +65,7 @@ private void load(OsuColour colours)
                                         RelativeSizeAxes = Axes.Both,
                                         Colour = Color4.Black
                                     },
-                                    new TickSliderBar(beatDivisor, BindableBeatDivisor.VALID_DIVISORS)
+                                    new TickSliderBar(beatDivisor)
                                     {
                                         RelativeSizeAxes = Axes.Both,
                                     }
@@ -95,13 +98,13 @@ private void load(OsuColour colours)
                                                     new DivisorButton
                                                     {
                                                         Icon = FontAwesome.Solid.ChevronLeft,
-                                                        Action = beatDivisor.Previous
+                                                        Action = beatDivisor.PreviousDivisor
                                                     },
-                                                    new DivisorText(beatDivisor),
+                                                    divisorText = new DivisorText(beatDivisor),
                                                     new DivisorButton
                                                     {
                                                         Icon = FontAwesome.Solid.ChevronRight,
-                                                        Action = beatDivisor.Next
+                                                        Action = beatDivisor.NextDivisor
                                                     }
                                                 },
                                             },
@@ -118,32 +121,115 @@ private void load(OsuColour colours)
                         },
                         new Drawable[]
                         {
-                            new TextFlowContainer(s => s.Font = s.Font.With(size: 14))
+                            new Container
                             {
-                                Padding = new MarginPadding { Horizontal = 15 },
-                                Text = "beat snap divisor",
-                                RelativeSizeAxes = Axes.X,
-                                TextAnchor = Anchor.TopCentre
-                            },
+                                RelativeSizeAxes = Axes.Both,
+                                Padding = new MarginPadding { Horizontal = 5 },
+                                Children = new Drawable[]
+                                {
+                                    new Container
+                                    {
+                                        RelativeSizeAxes = Axes.Both,
+                                        Padding = new MarginPadding { Horizontal = 5 },
+                                        Child = new GridContainer
+                                        {
+                                            RelativeSizeAxes = Axes.Both,
+                                            Content = new[]
+                                            {
+                                                new Drawable[]
+                                                {
+                                                    new TextFlowContainer(s => s.Font = OsuFont.Default.With(size: 11))
+                                                    {
+                                                        Padding = new MarginPadding { Horizontal = 0 },
+                                                        Text = "beat snap divisor",
+                                                        RelativeSizeAxes = Axes.Both,
+                                                        TextAnchor = Anchor.TopCentre
+                                                    },
+                                                },
+                                            },
+                                            ColumnDimensions = new[]
+                                            {
+                                                new Dimension(),
+                                            }
+                                        }
+                                    }
+                                }
+                            }
+                        },
+                        new Drawable[]
+                        {
+                            new Container
+                            {
+                                RelativeSizeAxes = Axes.Both,
+                                Padding = new MarginPadding { Horizontal = 5 },
+                                Children = new Drawable[]
+                                {
+                                    new Container
+                                    {
+                                        RelativeSizeAxes = Axes.Both,
+                                        Padding = new MarginPadding { Horizontal = 5 },
+                                        Child = new GridContainer
+                                        {
+                                            RelativeSizeAxes = Axes.Both,
+                                            Content = new[]
+                                            {
+                                                new Drawable[]
+                                                {
+                                                    new DivisorButton
+                                                    {
+                                                        Icon = FontAwesome.Solid.ChevronLeft,
+                                                        Action = beatDivisor.PreviousPanel,
+                                                        //Anchor = Anchor.BottomRight
+                                                    },
+                                                    panelText = new DivisorPanelText(beatDivisor),
+                                                    new DivisorButton
+                                                    {
+                                                        Icon = FontAwesome.Solid.ChevronRight,
+                                                        Action = beatDivisor.NextPanel,
+                                                        //Anchor = Anchor.BottomRight
+                                                    }
+                                                },
+                                            },
+                                            ColumnDimensions = new[]
+                                            {
+                                                new Dimension(),
+                                                new Dimension(GridSizeMode.Absolute, 50),
+                                                new Dimension()
+                                            }
+                                        }
+                                    }
+                                }
+                            }
                         }
                     },
                     RowDimensions = new[]
                     {
-                        new Dimension(GridSizeMode.Absolute, 30),
+                        new Dimension(GridSizeMode.Absolute, 25),
+                        new Dimension(GridSizeMode.Absolute, 25),
+                        new Dimension(GridSizeMode.Absolute, 11),
                         new Dimension(GridSizeMode.Absolute, 25),
                     }
                 }
             };
+
+            beatDivisor.BindValueChanged(updateDivisorsText);
+            beatDivisor.ValidDivisorsChanged += updatePanelText;
+
+            updatePanelText();
         }
 
-        private class DivisorText : SpriteText
+        private void updateDivisorsText(ValueChangedEvent<int> divisor) => divisorText.Text = $"1/{divisor.NewValue}";
+        private void updatePanelText() => panelText.Text = $"{beatDivisor.Panel}";
+
+        private class DivisorPanelText : SpriteText
         {
-            private readonly Bindable<int> beatDivisor = new Bindable<int>();
+            private readonly BindableBeatDivisor beatDivisor = new BindableBeatDivisor();
 
-            public DivisorText(BindableBeatDivisor beatDivisor)
+            public DivisorPanelText(BindableBeatDivisor bd)
             {
-                this.beatDivisor.BindTo(beatDivisor);
+                beatDivisor.BindTo(bd);
 
+                Font = OsuFont.Default.With(size: 12);
                 Anchor = Anchor.Centre;
                 Origin = Anchor.Centre;
             }
@@ -153,11 +239,24 @@ private void load(OsuColour colours)
             {
                 Colour = colours.BlueLighter;
             }
+        }
 
-            protected override void LoadComplete()
+        private class DivisorText : SpriteText
+        {
+            private readonly Bindable<int> beatDivisor = new Bindable<int>();
+
+            public DivisorText(BindableBeatDivisor bd)
             {
-                base.LoadComplete();
-                beatDivisor.BindValueChanged(val => Text = $"1/{val.NewValue}", true);
+                beatDivisor.BindTo(bd);
+
+                Anchor = Anchor.Centre;
+                Origin = Anchor.Centre;
+            }
+
+            [BackgroundDependencyLoader]
+            private void load(OsuColour colours)
+            {
+                Colour = colours.BlueLighter;
             }
         }
 
@@ -188,16 +287,11 @@ private class TickSliderBar : SliderBar<int>
         {
             private Marker marker;
 
-            [Resolved]
-            private OsuColour colours { get; set; }
-
             private readonly BindableBeatDivisor beatDivisor;
-            private readonly int[] availableDivisors;
 
-            public TickSliderBar(BindableBeatDivisor beatDivisor, params int[] divisors)
+            public TickSliderBar(BindableBeatDivisor bd)
             {
-                CurrentNumber.BindTo(this.beatDivisor = beatDivisor);
-                availableDivisors = divisors;
+                CurrentNumber.BindTo(beatDivisor = bd);
 
                 Padding = new MarginPadding { Horizontal = 5 };
             }
@@ -205,30 +299,58 @@ public TickSliderBar(BindableBeatDivisor beatDivisor, params int[] divisors)
             [BackgroundDependencyLoader]
             private void load()
             {
-                foreach (int t in availableDivisors)
+                //foreach (var t in availableDivisors)
+                //{
+                //    AddInternal(new Tick(t)
+                //    {
+                //        Anchor = Anchor.TopLeft,
+                //        Origin = Anchor.TopCentre,
+                //        RelativePositionAxes = Axes.X,
+                //        X = getMappedPosition(t)
+                //    });
+                //}
+
+                //AddInternal(marker = new Marker());
+
+                //CurrentNumber.ValueChanged += v =>
+                //{
+                //    marker.MoveToX(getMappedPosition(v), 100, Easing.OutQuint);
+                //    marker.Flash();
+                //};
+            }
+
+            protected override void LoadComplete()
+            {
+                base.LoadComplete();
+
+                beatDivisor.ValidDivisorsChanged += updateDivisors;
+                updateDivisors();
+            }
+
+            private void updateDivisors()
+            {
+                for (int i = Children.Count - 1; i >= 0; i--)
+                    RemoveInternal(Children[i]); // Remove all ticks to change the panel
+
+                foreach (int t in beatDivisor.ValidDivisors)
                 {
-                    AddInternal(new Tick
+                    AddInternal(new Tick(t)
                     {
                         Anchor = Anchor.TopLeft,
                         Origin = Anchor.TopCentre,
                         RelativePositionAxes = Axes.X,
-                        Colour = BindableBeatDivisor.GetColourFor(t, colours),
                         X = getMappedPosition(t)
                     });
                 }
 
                 AddInternal(marker = new Marker());
+                CurrentNumber.BindValueChanged(moveMarker, true);
             }
 
-            protected override void LoadComplete()
+            private void moveMarker(ValueChangedEvent<int> pos)
             {
-                base.LoadComplete();
-
-                CurrentNumber.BindValueChanged(div =>
-                {
-                    marker.MoveToX(getMappedPosition(div.NewValue), 100, Easing.OutQuint);
-                    marker.Flash();
-                }, true);
+                marker.MoveToX(getMappedPosition(pos.NewValue), 100, Easing.OutQuint);
+                marker.Flash();
             }
 
             protected override void UpdateValue(float value)
@@ -242,13 +364,11 @@ protected override bool OnKeyDown(KeyDownEvent e)
                 switch (e.Key)
                 {
                     case Key.Right:
-                        beatDivisor.Next();
-                        OnUserChange(Current.Value);
+                        beatDivisor.NextDivisor();
                         return true;
 
                     case Key.Left:
-                        beatDivisor.Previous();
-                        OnUserChange(Current.Value);
+                        beatDivisor.PreviousDivisor();
                         return true;
 
                     default:
@@ -264,41 +384,40 @@ protected override bool OnMouseDown(MouseDownEvent e)
 
             protected override void OnMouseUp(MouseUpEvent e)
             {
-                marker.Active = false;
                 base.OnMouseUp(e);
+                marker.Active = false;
             }
 
             protected override bool OnClick(ClickEvent e)
             {
-                handleMouseInput(e.ScreenSpaceMousePosition);
+                handleMouseInput(e.CurrentState);
                 return true;
             }
 
-            protected override void OnDrag(DragEvent e)
-            {
-                handleMouseInput(e.ScreenSpaceMousePosition);
-            }
+            protected override bool OnDragStart(DragStartEvent e) => true; // todo: check
 
-            protected override void OnDragEnd(DragEndEvent e)
+            protected override void OnDrag(DragEvent e)
             {
-                handleMouseInput(e.ScreenSpaceMousePosition);
+                handleMouseInput(e.CurrentState);
             }
 
-            private void handleMouseInput(Vector2 screenSpaceMousePosition)
+            private void handleMouseInput(InputState state)
             {
                 // copied from SliderBar so we can do custom spacing logic.
-                float xPosition = (ToLocalSpace(screenSpaceMousePosition).X - RangePadding) / UsableWidth;
+                float xPosition = (ToLocalSpace(state?.Mouse.Position ?? Vector2.Zero).X - RangePadding) / UsableWidth;
 
-                CurrentNumber.Value = availableDivisors.OrderBy(d => Math.Abs(getMappedPosition(d) - xPosition)).First();
-                OnUserChange(Current.Value);
+                CurrentNumber.Value = beatDivisor.ValidDivisors.OrderBy(d => Math.Abs(getMappedPosition(d) - xPosition)).First();
             }
 
-            private float getMappedPosition(float divisor) => MathF.Pow((divisor - 1) / (availableDivisors.Last() - 1), 0.90f);
+            private float getMappedPosition(float divisor) => (float)Math.Pow((divisor - 1) / (beatDivisor.ValidDivisors.Last() - 1), 0.90f);
 
             private class Tick : CompositeDrawable
             {
-                public Tick()
+                private readonly int divisor;
+
+                public Tick(int d)
                 {
+                    divisor = d;
                     Size = new Vector2(2.5f, 10);
 
                     InternalChild = new Box { RelativeSizeAxes = Axes.Both };
@@ -306,6 +425,12 @@ public Tick()
                     CornerRadius = 0.5f;
                     Masking = true;
                 }
+
+                [BackgroundDependencyLoader]
+                private void load(OsuColour colours)
+                {
+                    Colour = BindableBeatDivisor.GetColourFor(divisor, colours);
+                }
             }
 
             private class Marker : CompositeDrawable

```

**Comment by frenzibyte** [comment]
I agree the offered UX is good, can imagine the "Other" section turning into a "Custom" section where the user can enter an arbitrary beat divisor.

**Comment by bdach** [comment]
how do i apply the patch above to check it out? trying to merge `master` predictably fails with a merge conflict, i can't apply the patch on top of the merge conflict, nor can i apply it onto this branch as is.

**Comment by frenzibyte** [comment]
Should work by applying the patch on a fresh branch on top of `master`.

**Comment by AlFasGD** [comment]
I was expecting peppy to push the changes himself since he already mentioned bringing the code for the up-to-date `master`.

**Comment by bdach** [comment]
i just did and it immediately crashed, but i fixed it (`BindableBeatDivisor` is missing an implementation for `CreateInstance()` in the patch above).

i guess what is there is sort of functional, save some graphical issues:

2022-02-06-192924_135x68_scrot

but as people want arbitrary 1/n snaps then i think i'd like to try something different first. will propose in the relevant issue thread whenever i get around to trying it, unless there is consensus that the ux proposed here is tolerable as is.

**Pull request closed without merging**
