### PR TITLE
Add kick button (and required server shared interface updates)

### PR DESCRIPTION
**Pull request by peppy**
https://user-images.githubusercontent.com/191335/128997900-a2b604dd-c833-45d1-b9b5-18172a5aa24b.mp4

### CODE REVIEW

**Comment by bdach** [comment]
Out of curiosity, is there a particular reason for why giving host is in the context menu, while kicking a player is outside of it? Seems slightly wonky UX-wise. I guess the primary argument would be frequency of usage, although I don't really know how often players need to be kicked from rooms...

**Comment by frenzibyte** [comment]
In my opinion, I think it's better that the kick is in both the dropdown and in the participants list, as I would think the dropdown to contain all operations applicable to a participant, and a button as a shortcut to kick quickly without having to open the dropdown.

**Comment by bdach** [comment]
Then, following that logic, why is there no button for giving host? One argument would be frequency of use, as I mentioned above, but I'd personally probably assume giving host will be used *more* than kicking, not less (at least until automatic host rotate gets implemented, I suppose).

**Comment by peppy** [comment]
Host transfer also needs a button. I believe it probably wasn’t added due to lack of design.

**Review by smoogipoo — APPROVED** [review]
lgtm

**Pull request merged**
