### PR TITLE
Update login overlay appearance to match new designs

### PR DESCRIPTION
**Pull request by letsgoawaydev**
This is a small issue that bugged me for a while, I dont know if it was intentional or not, but I have changed the spacing on the LoginForm to be more inline with the Settings Overlay.
Before - 
Before
After - 
osu!_VhUv6HqJTY

This can probably improve accessibility for mobile users because the buttons are more spaced out.

### CODE REVIEW

**Comment by peppy** [comment]
What you have feels way too spaced out.

@arflyte can you please advise on correct spacing here

**Comment by letsgoawaydev** [comment]
yeah now that i look at it it does look really spaced out.
image
heres another one i made at one point which has the text closer but it still does feel very spaced out

**Comment by Joehuu** [comment]
> What you have feels way too spaced out.
> 
> @arflyte can you please advise on correct spacing here

Might look better if the background is updated to the new design? It is still translucent.

**Comment by Joehuu** [comment]
I've tried my best to update the login overlay to match new designs (while keeping the old layout):
osu!_VhUv6HqJTY
osu!_2ErwCmALLy

I've pushed commits that should be read individually with no whitespace.

**Review by peppy — APPROVED** [review]

**Pull request merged**
