### PR TITLE
Basic networking / API authentication.

### PR DESCRIPTION
**Pull request by peppy**
Depends on minor framework updates https://github.com/ppy/osu-framework/pull/13.
- Can login using username/password.
- Can authenticate using access token.
- Automatic access token refreshing when a refresh token is present.

To test this out, manually set your username and password in `game.ini` (non-encrypted for now) and uncomment the code in `OsuGame`'s `Load()`.

Still to be done:
- Tidy-up on API layer. I think it can still be made cleaner.
- Proper bindable updating and disconnect handling on property changes.
- Choosing a managed encryption library to replace/assist DPAPI (native windows only).

### CODE REVIEW

**Comment by avail** [comment]
'non-encrypted for now' - I have some c++ code that could be ported to c# that utilizes Credui and hashes the file per-system, so that even copying the exact same file to a different system and running it fails to read it. Here's a paste http://pastebin.com/6XPqZsL9

**Comment by peppy** [comment]
There's plenty of available libraries which I'd prefer to use (because they are standardised and maintained); check out Nuget.

**Comment by avail** [comment]
This is built into windows, and would require no third party library, just a wrapper or two for credui funcs.

**Comment by peppy** [comment]
DPAPI is built-in to windows, and I already had that working. the reason i left it out is because we *need* cross-platform support.

**Comment by avail** [comment]
Oh, I haven't though of that while posting. Apologies.

**Pull request merged**
