### PR TITLE
Make comboColours skinnable

### LINKED ISSUE #3460: Add support for skin ComboColours
Is that a feature that combo colours from beatmaps (when it has one) override these from skin.ini ?

- [x] Question about #2254.

### PR DESCRIPTION
**Pull request by Dragicafit**
Sets priority to the skin from skin.ini (was the beatmap before).

Resolves #3460

### CODE REVIEW

**Comment by Dragicafit** [comment]
It is now conform to the legacy : 
- toggle "beatmap skins" will use the colours and the index of colours from the beatmap (for example : 12-12-123-1234)
- not selecting it will use the colours from skin.ini (or default) and will create normal index (1234-1234-1234)

**Comment by smoogipoo** [comment]
The problem is that `LocalSkinOverrideContainer` is giving the beatmap configuration over the user's skin configuration. The `beatmapSkins` check is missing from `GetValue()`.

**Review by smoogipoo — CHANGES_REQUESTED** [review]
As commented

**Comment by Dragicafit** [comment]
Yeah, this is what I done on GetComboColours because I didn't know if I could change GetValue.
And I add a combo index for the user's skin configuration.

**Comment by Dragicafit** [comment]
Ok, and were can I change the ComboIndex (https://github.com/ppy/osu/pull/3497#issuecomment-425209207), in the BeatmapProcessor.PreProcess() or in DrawableOsuHitObject.SkinChanged() or somewhere else ?

**Comment by smoogipoo** [comment]
Can you explain what you mean by the combo index modifications? As far as I've tested:

1. Having 1 combo colour in the beatmap skin - gameplay will use that one colour for all hitobjects.
2. Having 1 combo colour in the skin - gameplay will use that one colour for all hitobjects.

So it's just doing `index % colours.Count` with no default colours, which is what the original code and your updated code already does.

**Comment by Dragicafit** [comment]
A lot of beatmap has an offset (`ComboOffset`) for a new combo which change the index (`ComboIndex`).

For example in legacy (beatmap : 166623) with 4 combo colours : 
- When beatmap skin is enable, the offset is used (index : 1,2,5,6,9,10,13,14,15 and colors : 2,3,2,3,2,3,2,3,4)
- When beatmap skin is disable, there is no offset (index : 1,2,3,4,5,6,7,8,9 and colors : 2,3,4,1,2,3,4,1,2)

And in lazer, the offset is always present in `BeatmapProcessor.PreProcess` (index : 1,2,5,6,9,10,13,14,15 and colors : 2,3,2,3,2,3,2,3,4)

PS : combo1 is always the last combo.

**Pull request closed without merging**
