### PR TITLE
Change spinner score display to show when reaching max bonus score

### PR DESCRIPTION
**Pull request by peppy**
Just a quick / best effort implementation. Might adjust animations in the future.

Addresses https://github.com/ppy/osu/discussions/25172.

https://github.com/ppy/osu/assets/191335/159f2694-d057-4344-b3c6-c4e7b97cd41e

### CODE REVIEW

**Comment by peppy** [comment]
@nekodex might be worth adding a special sound after hitting the bonus? A minor variant on the standard bonus sound?

**Comment by toadsworth-jr** [comment]
What would happen for legacy skins, though? Is it still going to use old behavior?

**Review by bdach — APPROVED** [review]
What is here so far looks good.

I'm not sure to me if the request for additional sound samples should be interpreted as blocking this or not though.

**Comment by peppy** [comment]
Non blocking

**Pull request merged**
