### PR TITLE
Added the converted osu and mime .svg files

### PR DESCRIPTION
**Pull request by ghost**
as recommended by [peppy](https://github.com/flathub/sh.ppy.osu/pull/134#issuecomment-1807057350), as i said in the original pr, they are rough and was converted from the existing png ones, if better quality .svg icons or the original raw files is found i update this pr

### CODE REVIEW

**Comment by Tanza3D** [comment]
those are horrific
for the former (osz file) i think it'd be a nice idea to try get a new one, i'd be happy to give that a shot if peppy's okay with it
for the latter (osu! logo) im certain that's in vector somewhere, but if not i think recreating it should be a better route than this bad trace, would also be happy to do this

**Comment by bdach** [comment]
For visibility, I asked for better versions of these internally.

**Comment by agatemosu** [comment]
I know that on osu-web there is the background and the letters in two separate SVGs
https://github.com/ppy/osu-web/blob/master/public/images/layout/osu-logo-white.svg
https://github.com/ppy/osu-web/blob/master/public/images/layout/osu-logo-triangles.svg

**Comment by Tanza3D** [comment]
> I know that on osu-web there is the background and the letters (like the main menu) of the logo in two separate SVGs https://github.com/ppy/osu-web/blob/master/public/images/layout/osu-logo-white.svg https://github.com/ppy/osu-web/blob/master/public/images/layout/osu-logo-triangles.svg

different logo, that's not lazer's

**Comment by Tanza3D** [comment]
best recreation of `mime.svg` i can do

mime

**Comment by Vilianexe** [comment]
> best recreation of `mime.svg` i can do
> 
> mime

want me to update with this version on the commit?

**Comment by Tanza3D** [comment]
> > best recreation of `mime.svg` i can do
> > mime
> 
> want me to update with this version on the commit?

up to you

**Comment by bdach** [comment]
The original assets for the file type icons are apparently these illustrator files: [icons.zip](https://github.com/ppy/osu/files/13343658/icons.zip)

I don't have illustrator so I can't very easily make use of these though.

**Comment by Tanza3D** [comment]
original assets were quite complex and messy when converted to svg and made use of transparent black layers instead of just solid darker pinks (which i felt could be bad for performance) so i've taken some time with the original to clean it up a bit and remove unnecessary paths and such

## original
osu_Beatmap_Pack_Icon-original

## cleaned
osu_Beatmap_Pack_Icon-cleaned

only thing is that the shadow is completely missing from these as illustrator can only export those as images embedded inside the svgs, can try add it on myself if wanted
(thanks to nhiil for doing the base ai to svg conversion for me, stopped paying for adobe years ago lol)

**Comment by Vilianexe** [comment]
pr updated :)

**Comment by bdach** [comment]
I'm going to go ahead and close this since I'm not certain we'll be using either of these assets anymore at this point.

**Pull request closed without merging**
