### PR TITLE
Show toolbar when game is paused

### PR DESCRIPTION
**Pull request by rednir**
Discussed in #14013

I wasn't sure whether to make changes to `GameplayMenuOverlay` or `Player`, but decided on the latter.

### CODE REVIEW

**Comment by smoogipoo** [comment]
This looks fine for standard but I'm less convinced about mania/taiko/catch which don't have a delay before unpause.

**Comment by rednir** [comment]
The other options I can think of right now are:
 - show toolbar only on fail overlay, not pause overlay. You could argue that this would feel inconsistent.
 - add a short delay after resume is clicked.
      - An upside to this is that the player is given more time to react, and it also more closely matches osu! stable behaviour. I've tried this out with 300ms and personally think it feels pretty natural. It also resolves the mania "pop" transition.

**Comment by peppy** [comment]
You do know you can bind a key to show the toolbar, right?

**Comment by peppy** [comment]
Before considering this further I'm going to need to check on the updated designs and have a think how these interactions/animations should be implemented. I don't foresee this happening in the imminent future (I have a plan to do a huge polish pass on UI/UX/animation once other higher priority tasks are completed).

If this is seen as an imminent QoL improvement then we can consider it in the mean time, else it may be worth waiting.

**Comment by smoogipoo** [comment]
Let's close this and continue in discussion then?

**Comment by peppy** [comment]
I think that makes more sense for now. There are already other areas in the game where the toolbar's show/hide causes really awkward movement that annoys me.

**Pull request closed without merging**
