### PR TITLE
Smoothen the footer mods button resizing

### PR DESCRIPTION
**Pull request by EVAST9919**
test2

### CODE REVIEW

**Comment by jorolf** [comment]
Have you tried using ``AutoSizeEasing`` and ``AutoSizeDuration``?

**Comment by EVAST9919** [comment]
> Have you tried using `AutoSizeEasing` and `AutoSizeDuration`?

I didn't even know, what that such a useful thing exists.

**Comment by peppy** [comment]
Not sure we want this implemented in such a weird way. If it can be done using `AutoSizeEasing` i'd be okay with it, but considering the mod display is going to have to be redone (to smoothly display new mods rather than pop in) this will probably regress quite quickly.

**Comment by EVAST9919** [comment]
Must be made in a different way

**Pull request closed without merging**
