### PR TITLE
Add `VisualSettings` in `GameplayMenuOverlay`

### LINKED ISSUE #3853: Make visual settings usable while gameplay is paused
**Describe the feature:** Possibility to change visual settings while in gameplay (and paused)

### PR DESCRIPTION
**Pull request by cdwcgt**
- Resolves https://github.com/ppy/osu/issues/3853

Allows players to modify visual settings when paused or failed.

https://github.com/ppy/osu/assets/34775378/b6fee247-b60b-4604-9f81-0293f3608769

### CODE REVIEW

**Comment by bdach** [comment]
> image

the overlap between the main buttons and the added visual settings panel looks really bad. it's even worse when UI scaling is changed.

osu_2023-05-13_15-07-31

**Comment by cdwcgt** [comment]
Wouldn't it be better to close it by default?
Or, change location?
image
image

**Comment by Joehuu** [comment]
I would look at the comments in the issue I linked and my past PR at https://github.com/ppy/osu/pull/5188.

**Comment by cdwcgt** [comment]
I have seen the pr and try to show it only on `Player` and `Playerloader`, detach it from HudOverlay to get out of failanimationLayer but it will be difficult to confirm the position, the box model will not work.
Players can customize the layout of `HudOverlay`, but it does not affect `PlayerLoader` and `GameplayMenu`.
And PlayerLoader and GamePlayMenu are in different IScreen (`PlayerLoader ` and `Players `), so I haven't found a way to display it using only one exposure layer.

In fact, the most important thing is that the layout of `HudOvlay` will change its position

**Comment by monochrome22** [comment]
It doesn't look like it's possible to make the VisualSettings overlay look good on top of the pause overlay without larger design changes. 
Maybe do it same way as stable: have the settings be collapsed by default and if they are hovered then fade the pause overlay so that the player can see the gameplay. Also, https://github.com/ppy/osu/issues/7285 should be added to make custom skin toggle look better.

**Comment by frenzibyte** [comment]
I don't think this PR can live on any longer without further design considerations, the UX feels quite horrible as-is. @ppy/team-client should this be closed?

**Comment by peppy** [comment]
I've already mentioned this to flyte and he has been working on a new design for the pause screen which accommodates for this.

Whether this PR can live on or  not depends on whether it is refactored to not require two copies of the visual settings to exist. There's already one copy in the HUD. This should be moved to a layer where it can also be displayed at the pause screen.

**Comment by frenzibyte** [comment]
Well, it doesn't look to be doing that in here, not sure if it's worth spending time refactoring it before the new design comes in first.

**Comment by peppy** [comment]
It's a small LOC change and will need reconsideration so let's close for now.

**Pull request closed without merging**
