### PR TITLE
Wraps "repel" and "magnetized" mods into a base class

### PR DESCRIPTION
**Pull request by o-dasher**
This pull request aims to address code repetition between `OsuModRepel` and `OsuModMagnetized` mods by creating a base class `CursorBasedHitObjectPositionMod` (This naming seens odd but i couldn't think of anything else) which both mods inherit from.

### CODE REVIEW

**Comment by bdach** [comment]
[This was not done originally very intentionally.](https://github.com/ppy/osu/pull/18607#discussion_r893933408) I didn't think that code reuse in this particular case worked well.

This PR is a little better in that respect, but there is so little shared code, that I question if this is even worth it.

**Comment by peppy** [comment]
It may make more sense if this is being done as a prerequisite to a new mod which is being worked on – is that the case?

**Comment by o-dasher** [comment]
> It may make more sense if this is being done as a prerequisite to a new mod which is being worked on – is that the case?

That's not the case, i just figured out that this could be simplified and did it for the sake of code quality and ease of use

**Comment by peppy** [comment]
I think in the interest of simplicity, let's keep these separate for now. If there's ever a third mod of the same variety, it may be time to consider combining some code, although i'm not sure inheritance is the correct path.

**Pull request closed without merging**
