### PR TITLE
Take custom bank name length into account when collapsing sample point indicators

### LINKED ISSUE #31312: Sample point indicators do not collapse when the custom name is overlapping
### Type

Game behaviour

### Bug description

Hi. Look at this:
image

### Screenshots or videos

_No response_

### Version

2024.1219.2

### Logs

[compressed-logs.zip](https://github.com/user-attachments/files/18262110/compressed-logs.zip)

### PR DESCRIPTION
**Pull request by bdach**
RFC. Would close https://github.com/ppy/osu/issues/31312.

Not super happy with the performance overhead of this, but this is already a heuristic-based implementation to avoid every-frame `.ChildrenOfType<>()` calls or similar, so not super sure how to do better. The `Array.Contains()` check stands out in profiling, but without it the indicators can collapse *too* eagerly sometimes.

| before | after |
| :-: | :-: |
|  |  |

### CODE REVIEW

**Review by smoogipoo — APPROVED** [review]

**Comment by rvneXe** [comment]
Umm is the video below caused by this PR? Should I make a new issue?

https://github.com/user-attachments/assets/80025d5b-e88e-4348-b9b5-99dfb408083d

**Comment by bdach** [comment]
i don't see anything wrong there

**Comment by rvneXe** [comment]
> i don't see anything wrong there

like the mechanism looking a little over-reacting. Collapsing even when the input name isn't that wide just rely on "3-characters long so I'm gonna collapse it"

**Comment by bdach** [comment]
it's doing that because there are 3 indicators on the slider that are almost touching. the thing is collapsing because any longer name causes overlaps. that is intentional.

**Pull request merged**
