### PR TITLE
Fix channel presence being handled incorrectly

### LINKED ISSUE #3554: Pre-loaded channels aren't marked as joined
I noticed this from a few releases, I guess this happens from the release for the new API version (#3494):
## Issue
Pre-loaded channels aren't marked in `Chat Channels` as joined (except for `#lazer` and `#osu`: they are marked)
## Video (no audio)
https://streamable.com/hhbsn
In the video, I show `#italian` and `#help` channels as an example, then I try to close them (with middle mouse, to clarify), and opening them again solves the problem (but it would not surprise me if reopening the game the issue appears again).

### PR DESCRIPTION
**Pull request by peppy**
- Fixes a crash on leaving active tab channel.
- Closes #3554.
- Generally makes channel instance handlings a bit more logical.

### CODE REVIEW

**Comment by smoogipoo** [comment]
1. PM channels aren't added with the `PM` type (ChannelManager:80)
2. Posting to PM channels doesn't work.
3. The following will happen when opening a second PM channel:

```
Unhandled Exception: [runtime:error] 11/21/2018 11:21:49: An unhandled error has occurred.
[runtime:error] 11/21/2018 11:21:49: System.Collections.Generic.KeyNotFoundException: The given key 'MrXenox' was not present in the dictionary.
[runtime:error] 11/21/2018 11:21:49: at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
[runtime:error] 11/21/2018 11:21:49: at osu.Framework.Graphics.UserInterface.TabControl`1.<.ctor>b__22_2(T newSelection)
[runtime:error] 11/21/2018 11:21:49: at osu.Framework.Configuration.Bindable`1.set_Value(T value)
[runtime:error] 11/21/2018 11:21:49: at osu.Game.Overlays.ChatOverlay.<>c__DisplayClass24_0.<currentChannelChanged>b__0() in /Users/smoogipoo/Repos/osu/osu.Game/Overlays/ChatOverlay.cs:line 218
[runtime:error] 11/21/2018 11:21:49: at osu.Framework.Threading.Scheduler.Update()
```

**Review by smoogipoo — DISMISSED** [review]
As commented

**Comment by smoogipoo** [comment]
1. Previous chat history doesn't load in PM channels.
2. Still able to crash by opening a second PM channel:

```
[runtime:error] 11/22/2018 04:07:06: System.Collections.Generic.KeyNotFoundException: The given key 'peppy' was not present in the dictionary.
[runtime:error] 11/22/2018 04:07:06: at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
[runtime:error] 11/22/2018 04:07:06: at osu.Framework.Graphics.UserInterface.TabControl`1.<.ctor>b__22_2(T newSelection)
[runtime:error] 11/22/2018 04:07:06: at osu.Framework.Configuration.Bindable`1.set_Value(T value)
[runtime:error] 11/22/2018 04:07:06: at osu.Game.Overlays.ChatOverlay.<>c__DisplayClass24_0.<currentChannelChanged>b__0() in /Users/smoogipoo/Repos/osu/osu.Game/Overlays/ChatOverlay.cs:line 218
```

**Comment by peppy** [comment]
Please try with someone that isn't me.

**Comment by smoogipoo** [comment]
I have tried with 4 users at this point, all the same

**Comment by peppy** [comment]
As discussed, the PM history issue reported is an expected behaviour for admin-level users.

Will look at the crash

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
