### PR TITLE
Fix OpenTK hint on project file

### LINKED ISSUE #551: Missing OpenTK hint reference on osu.Desktop project file.
When building with Mono 4.4.1 under Gentoo Linux, the build fails due to a missing hint reference to the OpenTK assembly on osu.Desktop. I think opening an issue is standard practice, so...

### PR DESCRIPTION
**Pull request by ekisu**
Fixes #551.

### CODE REVIEW

**Comment by peppy** [comment]
does anyone else building on mono run into this issue?

**Comment by ElegantMonkey** [comment]
If they're building on a case-sensitive filesystem, there's also a little problem with OptionDropDown.cs and OptionEnumDropDown.cs under osu.Game/Overlays/Options. It seems they're referenced with "OptionDropdown.cs" and "OptionEnumDropdown.cs" on the solution.

**Comment by peppy** [comment]
please submit a fix for this one if you are able to

**Comment by ElegantMonkey** [comment]
#553 fixes it.

**Comment by ZLima12** [comment]
I'm not sure what issue is trying to be corrected here. Are you able to build at all without this fix?

**Comment by ElegantMonkey** [comment]
No, I'm unable to build without this fix. The build log with the errors is as follows:
```
Build FAILED.

Warnings:

/media/anime/Dados/osu/osu.sln (default targets) ->
(Build target) ->
/media/anime/Dados/osu/osu.Game/osu.Game.csproj (default targets) ->
/usr/lib64/mono/xbuild/14.0/bin/Microsoft.CSharp.targets (CoreCompile target) ->

	Configuration/OsuConfigManager.cs(175,61): warning CS0612: `osu.Game.Configuration.OsuConfig.ConfineMouseToFullscreen' is obsolete
	Database/ScoreDatabase.cs(24,33): warning CS0414: The private field `osu.Game.Database.ScoreDatabase.ipc' is assigned but its value is never used
	Database/BeatmapDatabase.cs(29,35): warning CS0414: The private field `osu.Game.Database.BeatmapDatabase.ipc' is assigned but its value is never used

/media/anime/Dados/osu/osu.sln (default targets) ->
(Build target) ->
/media/anime/Dados/osu/osu.Desktop/osu.Desktop.csproj (default targets) ->
/usr/lib64/mono/4.5/Microsoft.Common.targets (ResolveAssemblyReferences target) ->

	/usr/lib64/mono/4.5/Microsoft.Common.targets:  warning : Reference 'OpenTK, Version=2.0.0.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4' not resolved

Errors:

/media/anime/Dados/osu/osu.sln (default targets) ->
(Build target) ->
/media/anime/Dados/osu/osu.Desktop/osu.Desktop.csproj (default targets) ->
/usr/lib64/mono/4.5/Microsoft.CSharp.targets (CoreCompile target) ->

	Overlays/VersionManager.cs(16,7): error CS0246: The type or namespace name `OpenTK' could not be found. Are you missing an assembly reference?
	Overlays/VersionManager.cs(17,7): error CS0246: The type or namespace name `OpenTK' could not be found. Are you missing an assembly reference?
```

**Comment by ZLima12** [comment]
Did you try running `nuget restore` in the project root first?

**Comment by ElegantMonkey** [comment]
Yes, I did use nuget restore. There are a few other dependencies too, and OpenTK is also used in other parts of the program, yet this is the only place where the build fails.

Also, mono doesn't really have a embedded nuget executable, so I downloaded it from the nuget website and ran it with mono. I don't think it makes a difference, but maybe it's worth noting. Also, I built it with xbuild (equivalent to msbuild).

**Comment by peppy** [comment]
Before continuing, could you please update your mono to 4.8 and try again on a clean checkout? No one else has reported this issue, and if anything it is a mono bug or user error, so let's find the true cause.

**Comment by ZLima12** [comment]
It builds fine for me on Arch, Mono 4.8.0.495, and a clean checkout on the latest commit.

**Comment by peppy** [comment]
ditto for me on macos (latest) with mono 4.8.0 nuget 2.12.0.0

**Comment by Bobo1239** [comment]
So on my setup (Arch Linux; Mono 4.8.9.495; NuGet 3.5.0.1996) running `xbuild` the first time fails as @ElegantMonkey described but running the command a second time succeeds without any error.

**Comment by ElegantMonkey** [comment]
Strangely, running `xbuild` twice on Mono 4.4.1 does succeed, as @Bobo1239 pointed out. I'll update to Mono 4.8.

**Comment by ElegantMonkey** [comment]
Okay, after updating to Mono 4.8.0.495, cloning the repository on a new place, running `nuget restore`, and running `xbuild`, the result is the same. First build fails, second build works.

**Comment by hexchain** [comment]
On Arch Linux, Mono JIT compiler version 4.8.0 (Stable 4.8.0.495/e4a3cf3), nuget 2.14.0.0 and clean checkout, I have the same problem - first time building fails, second time succeeds.

Do we need a CI for Linux builds?

**Comment by ElegantMonkey** [comment]
I'm not really experienced with C#/Mono, so I don't really know how to fix this. However, something interesting I found on the build log was this. When building the osu.Desktop project:
```
Project "/media/anime/Dados/clean/osu/osu.Desktop/osu.Desktop.csproj" (Build target(s)):
	
	Target PrepareForBuild:
		Configuration: Debug Platform: AnyCPU
	
	Target ResolveAssemblyReferences:
/usr/lib64/mono/4.5/Microsoft.Common.targets:  warning : Reference 'OpenTK, Version=2.0.0.0, Culture=neutral, PublicKeyToken=bad199fe84eb3df4' not resolved
[...]
		For searchpath bin/Debug/
		Considered '/media/anime/Dados/clean/osu/osu.Desktop/bin/Debug/OpenTK' as a file, but the file does not exist
		Considered '/media/anime/Dados/clean/osu/osu.Desktop/bin/Debug/OpenTK.exe' as a file, but the file does not exist
		Considered '/media/anime/Dados/clean/osu/osu.Desktop/bin/Debug/OpenTK.dll' as a file, but the file does not exist
	
	Target CopyFilesMarkedCopyLocal:
[...]
		Copying file from '/media/anime/Dados/clean/osu/osu-framework/osu.Framework.Desktop/bin/Debug/OpenTK.dll' to '/media/anime/Dados/clean/osu/osu.Desktop/bin/Debug/OpenTK.dll'
[...]
	
	Target GenerateSatelliteAssemblies:
	No input files were specified for target GenerateSatelliteAssemblies, skipping.
	
	Target CoreCompile:
		Tool /usr/lib64/mono/4.5/mcs.exe execution started with arguments: /noconfig /debug: [this line is way too long]
Overlays/VersionManager.cs(16,7): error CS0246: The type or namespace name `OpenTK' could not be found. Are you missing an assembly reference?
Overlays/VersionManager.cs(17,7): error CS0246: The type or namespace name `OpenTK' could not be found. Are you missing an assembly reference?
	Task "Csc" execution -- FAILED
	Done building target "CoreCompile" in project "/media/anime/Dados/clean/osu/osu.Desktop/osu.Desktop.csproj".-- FAILED
	
Done building project "/media/anime/Dados/clean/osu/osu.Desktop/osu.Desktop.csproj".-- FAILED

Build FAILED.
```

It seems like the OpenTK DLL is being searched in the output build path, however the project searches for it before it's copied. When building for a second time, it's already there, and the build succeeds. I'll look if there's a way to reorder this.

**Comment by ElegantMonkey** [comment]
[buildlog.txt](https://github.com/ppy/osu/files/880548/buildlog.txt)

The full build log, if anyone is interested.

**Comment by kj415j45** [comment]
you can try to open osu.sln in monodevelop(not in command line),then let **it** run `nuget restore`

**Comment by ElegantMonkey** [comment]
The NuGet binary shipped with MonoDevelop 6.0 (version 2.8.7) won't even manage to restore all the packages. Restoring with a newer NuGet through the command line and building on MonoDevelop yields the same results.

**Comment by peppy** [comment]
@ElegantMonkey Well spotted. I think it's fine to merge this if it fixes the problem.

**Comment by ElegantMonkey** [comment]
Uhh... I think this is still kinda hackish, as you said - I manually added it on the project file. I just suggested added it in packages.config - which isn't in this pull request. Sorry if you thought that I already put the change on packages.config in this pull request.

**Comment by benzrf** [comment]
Not sure if this is the right issue to comment on, but it mentions some relevant stuff—right now, building fails for me on Arch, but if I `mv packages/sharpcompress.0.15.2/ packages/SharpCompress.0.15.2`, it works.

**Comment by peppy** [comment]
you'll probably need to correct the case of the reference in that case.

and no this likely isn't the right place to comment :P

**Pull request merged**
