### PR TITLE
Fix possible MusicController nullref

### PR DESCRIPTION
**Pull request by smoogipoo**
Because Beatmap bindable can be set by testcases, this is a possibility.

TestCases really need to not change the beatmap bindable but that's a pretty big change.

### CODE REVIEW

**Comment by peppy** [comment]
If that's the case, shouldn't the `MusicController` test case ensure the beatmap is set as required?

The beatmap it's binding to is a `NonNullable`, so I don't think this is the correct way to fix this.

**Comment by smoogipoo** [comment]
It's not that the beatmap is null. It's that the beatmap set is null, which happens from testcases that set their own beatmaps.

**Comment by peppy** [comment]
The first null coalesce can be removed then.

I'd rather fix the testcase instead of this class. BeatmapSet is supposed to be non-null too. As mentioned though, MusicController should be setting a valid beatmap before it loads the component.

**Comment by smoogipoo** [comment]
It's not any one testcase. At the moment it's literally every testcase that modifies the beatmap, including but not limited to AllPlayers.

Can remove the first null coalesce, sure. But I don't think beatmaps are supposed to always have a beatmap set. The instantiation of a beatmap would be absolutely insane then.

**Comment by peppy** [comment]
each testcase that uses a beatmap should set a relevant beatmap on startup, even so.

**Comment by smoogipoo** [comment]
You're missing the point of this change.

**Comment by peppy** [comment]
This change is still valid. I'm saying *on top of this* test cases should be specifying valid defaults so order of execution is not an issue.

**Review by peppy — APPROVED** [review]

**Comment by smoogipoo** [comment]
Testcases should set defaults that are applicable only to _them_ and those defaults should not be seen by nor have an affect on other testcases.

The beatmap is isolated to testcases in my GameBeatmap PR, which follows this principle.

**Pull request merged**
