### PR TITLE
Refactor performance calculators with local functions

### PR DESCRIPTION
**Pull request by huoyaoyuan**
Also add back changes of `float` to `double` which has regressed in conflict of #8934 .

### CODE REVIEW

**Comment by bdach** [comment]
The type changes should have been split - either as a separate PR, or at least at commit boundary - from the refactors IMO. Now it's hard to tell them apart.

**Comment by smoogipoo** [comment]
These are supposed to closely match implementations on osu-performance, so I don't want refactoring to happen just yet.

Also personally not a fan of turning everything into local functions conceptually. It doesn't separate code enough.

**Comment by huoyaoyuan** [comment]
> These are supposed to closely match implementations on osu-performance

That repo uses `float`, but the state of this repo before #6974 is a mixture of `float` and `double`. You should tell me this in that PR.

> Also personally not a fan of turning everything into local functions conceptually. It doesn't separate code enough.

Personally, I think that putting intermediate calculation values into class members is a bad factor. Classes shouldn't be state-full if unnecessary.

**Comment by smoogipoo** [comment]
Changing of floats to doubles is fine. Other changes should not be applied - line refactorings, removal of methods, local functions, etc.

Having class functions doesn't make a class stateful. In-fact these methods are already non-stateful. If you're really concerned about that then these should be `readonly struct`s with appropriate abstractions, but I see that as unnecessary at this point in time - keep it simple for something that isn't yet complete (it'll have to replace osu-performance before I consider anything like that).

**Comment by huoyaoyuan** [comment]
Closing to reopen one for float-to-double unification right now.

**Pull request closed without merging**
