### PR TITLE
Pause logic clean up

### PR DESCRIPTION
**Pull request by ocboogie**
If you time it right you can get both pause and fail overlays up.
bug

### CODE REVIEW

**Comment by peppy** [comment]
Pause logic is currently a huge mess. Here are some recommended steps to clean it up if you feel like taking on the task:

- `TogglePaused` can be removed (never used).
- Remove the `else` condition from `Pause` method (and invert the conditional `if (canPause || force)` to an early return.
- Make `IsPaused => sourceClock.IsRunning` and stop manually setting it.

All of these changes require testing.

Also I dislike your fix because you haven't identified why the race occurs in the first place. We should be figuring why it happens and addressing that, not adding a hacky "oh we'll just close it" as a fix.

**Review by peppy — CHANGES_REQUESTED** [review]
as commented

**Comment by ocboogie** [comment]
I agree. I'll start working on making pause logic better as you suggested

**Comment by ocboogie** [comment]
It seems like pause executes milliseconds before failing but the fail code is running still.
I logged the time in milliseconds:
Pause: 63627608726184
Fail: 63627608726199
Any guidance on how to fix this?

**Comment by peppy** [comment]
In the future please make a named feature branch rather than PRing from your master branch.

**Pull request closed without merging**
