### PR TITLE
Misc hover/select sound usage updates

### PR DESCRIPTION
**Pull request by nekodex**
A few misc changes:
- Re-adds on-click feedback to the news overlay sidebar (the month headers)
- Re-adds on-click feedback to dropdown headers
- Adds open/close sounds to menus (re-using dropdown sounds... for now?)
- Adds hover/select/join sounds to the multiplayer games listing

partially addresses #14082

### CODE REVIEW

**Comment by frenzibyte** [comment]
Currently opening editor triggers a menu open sample, coming from `EditorMenuBar` which inherits from `OsuMenu`. Seems like that should not play any sounds on `AnimateOpen`/`AnimateClose`.

**Review by frenzibyte — CHANGES_REQUESTED** [review]
As above, otherwise looks good.

**Comment by bdach** [comment]
I've fixed the above with a local guard checking that the menu is not a `TopLevelMenu`.

Possibly arguable that those menus shouldn't have `Animate{Open,Close}` called on them in the first place, but that'd be a framework amendment, so not sure whether that's something for now or later. Depends on how much this is desired to be in the next release or not, I suppose.

**Review by bdach — DISMISSED** [review]

**Comment by frenzibyte** [comment]
Hard one to decide, one may want to perform transforms when showing a menu bar (I can envision that potentially happening with editor at some point).

Not playing on `TopLevelMenu` sounds logically sufficient.

**Review by frenzibyte — DISMISSED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
