### PR TITLE
Allow spinners to be reversed

### PR DESCRIPTION
**Pull request by nbvdkamp**
To match stable.

### CODE REVIEW

**Comment by bdach** [comment]
The resize handles are pretty busted if a spinner is selected. They should probably be blocked.

As an aside the temporal reversing doesn't work so well if a spinner is part of the selection, but that's a pre-existing issue.

**Comment by nbvdkamp** [comment]
> As an aside the temporal reversing doesn't work so well if a spinner is part of the selection, but that's a pre-existing issue.

What cases do you mean by that? It seems to work as expected for the stuff I've tried so far.

**Comment by bdach** [comment]
I would expect reversing 2 times to bring the objects back to their original state, which doesn't happen 100% in the case of sliders (seemed to get shorter in length). Probably going to have to do with trimming end time to match snapping.

**Comment by peppy** [comment]
I think this is probably fine to merge as-is (the remaining issues seem separate?).

That said, it crashes on trying to reverse a selection of two spinners:

```
Unhandled exception. System.InvalidOperationException: Sequence contains no elements
   at System.Linq.ThrowHelper.ThrowNoElementsException()
   at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)
   at osu.Game.Rulesets.Osu.Edit.OsuSelectionHandler.HandleReverse() in /Users/dean/Projects/osu/osu.Game.Rulesets.Osu/Edit/OsuSelectionHandler.cs:line 50
   at osu.Game.Screens.Edit.Compose.Components.SelectionBox.<recreate>b__30_0() in /Users/dean/Projects/osu/osu.Game/Screens/Edit/Compose/Components/SelectionBox.cs:line 168
   at osu.Game.Screens.Edit.Compose.Components.SelectionBoxDragHandleButton.OnClick(ClickEvent e) in /Users/dean/Projects/osu/osu.Game/Screens/Edit/Compose/Components/SelectionBoxDragHandleButton.cs:line 53
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at osu.Framework.Input.ButtonEventManager`1.PropagateButtonEvent(IEnumerable`1 drawables, UIEvent e)
   at osu.Framework.Input.MouseButtonEventManager.handleClick(InputS[runtime] 2020-11-13 04:08:07 [error]: An unhandled error has occurred.
tate state, List`1 targets)
   at osu.Framework.Input.MouseButtonEventManager.HandleButtonUp(InputState state, List`1 targets)
   at osu.Framework.Input.ButtonEventManager`1.handleButtonUp(InputState state)
   at osu.Framework.Input.InputManager.HandleMouseButtonStateChange(ButtonStateChangeEvent`1 e)
   at osu.Framework.Input.UserInputManager.HandleInputStateChange(InputStateChangeEvent inputStateChange)
   at osu.Framework.Input.StateChanges.ButtonInput`1.Apply(InputState state, IInputStateChangeHandler handler)
   at osu.Framework.Input.InputManager.Update()
   at osu.Framework.Input.PassThroughInputManager.Update()
   at osu.Framework.Graphics.Drawable.UpdateSubTree()
```

**Review by peppy — DISMISSED** [review]
crashes, as mentioned

**Comment by bdach** [comment]
Weird, I did check that case and it seemed to be behaving fine...

**Comment by nbvdkamp** [comment]
Are you sure that crash happens on this branch? It happens on master for me but I can't reproduce it on this branch.

**Comment by peppy** [comment]
I can't repro any more... seems I may have been on the wrong branch.

**Comment by bdach** [comment]
@nbvdkamp please don't merge master if there are no conflicts, we will do so ourselves when the time is right.

My comment about the drag handles being visible and behaving badly if a spinner is part of the selection has not been addressed yet.

**Comment by nbvdkamp** [comment]
> @nbvdkamp please don't merge master if there are no conflicts, we will do so ourselves when the time is right.
Will do.

> My comment about the drag handles being visible and behaving badly if a spinner is part of the selection has not been addressed yet.

I can look at fixing that but I don't see how it's related to this PR

**Comment by bdach** [comment]
Sure, that's a separate PR I suppose.

**Review by bdach — APPROVED** [review]

**Pull request merged**
