### PR TITLE
Clean up SoloScoreInfo serialised output

### PR DESCRIPTION
**Pull request by smoogipoo**
Some values were getting submitted and stored to the database, when they don't need to/shouldn't be. Inclusive of https://github.com/ppy/osu/pull/19380, this is the new data:

```json
{
    "mods": [
        {
            "acronym": "HR",
            "settings": {}
        },
        {
            "acronym": "HD",
            "settings": {}
        }
    ],
    "rank": "SH",
    "passed": true,
    "user_id": 124493,
    "accuracy": 0.9983190452176836,
    "build_id": null,
    "ended_at": "2016-09-20T01:51:49+00:00",
    "max_combo": 2385,
    "base_score": 593900,
    "beatmap_id": 129891,
    "ruleset_id": 0,
    "started_at": null,
    "statistics": {
        "ok": 5,
        "meh": 0,
        "miss": 0,
        "great": 1978
    },
    "bonus_score": 0,
    "total_score": 132408001,
    "maximum_scoring_values": {
        "max_combo": 2385,
        "base_score": 594900,
        "bonus_score": 0,
        "large_ticks_count": 0,
        "small_ticks_count": 0,
        "basic_objects_count": 1983
    }
}
```
These are just surefire things, I haven't removed `started_at`, `ended_at`, `build_id`, `ruleset_id` or `beatmap_id` because I'm not 100% sure on them and they're serialised by the highscore importer.

Ignore:
- `0` values in `maximum_scoring_values` object.
- Empty mod settings.
- `accuracy` and `total_score`

### CODE REVIEW

**Comment by nanaya** [comment]
osu-web currently recreates the json before storing to database and thus any extras sent by the client are ignored.

It also uses attributes from `ScoreToken` (and ignores values from client): `ruleset_id`, `started_at` (from `created_at`), `beatmap_id`, `user_id`, `build_id`. And `ended_at` is always the request time.

What's actually stored in the database is defined [here](https://github.com/ppy/osu-web/blob/a45c14bd011dbf53b91a5bc631ae7e1a1abad1a1/app/Models/Solo/ScoreData.php#L106-L123) (and [here](https://github.com/ppy/osu-web/blob/a45c14bd011dbf53b91a5bc631ae7e1a1abad1a1/app/Models/Solo/ScoreDataStatistics.php#L83-L106) for the `statistics` field).

**Comment by smoogipoo** [comment]
> osu-web currently recreates the json before storing to database and thus any extras sent by the client are ignored.

Perfect, so this basically only affects the `osu-queue-score-statistics` high score importer.

> It also uses attributes from `ScoreToken` (and ignores values from client): `ruleset_id`, `started_at` (from `created_at`), `beatmap_id`, `user_id`, `build_id`. And `ended_at` is always the request time.
> 
> What's actually stored in the database is defined [here](https://github.com/ppy/osu-web/blob/a45c14bd011dbf53b91a5bc631ae7e1a1abad1a1/app/Models/Solo/ScoreData.php#L106-L123) (and [here](https://github.com/ppy/osu-web/blob/a45c14bd011dbf53b91a5bc631ae7e1a1abad1a1/app/Models/Solo/ScoreDataStatistics.php#L83-L106) for the `statistics` field).

Seems to match well then. The rest are still required here because they're set by the high score importer.

---

To cut down on the size of the table, we should be able to get rid of `ruleset_id`, `beatmap_id`, `ruleset_id`, since they're also present in the row itself. For example `osu-queue-score-statistics` does this mapping when reading the row:
https://github.com/ppy/osu-queue-score-statistics/blob/7276869732adc7ac4489417f11d2efa8a9c74856/osu.Server.Queues.ScoreStatisticsProcessor/Models/SoloScore.cs#L28-L45

**Comment by peppy** [comment]
Seems to be okay. We still should look at the remaining pieces (empty `settings` and zero `statistics`) separately.

**Review by peppy — APPROVED** [review]

**Comment by smoogipoo** [comment]
I didn't update the description but as of https://github.com/ppy/osu/pull/19575/commits/2d9da07eb69bfbeb1e9ff65fb50920ee7c6ec0b7 and https://github.com/ppy/osu-queue-score-statistics/pull/66 it doesn't write zero statistics.

Empty mod settings are a bit difficult, because I think "truly empty" mod statistics only come from the highscore importer whereas lazer will always serialise all settings regardless of if they're default. And I'm fairly certain it does so for a reason, or at least there was a reason we made it do so in recent times but I can't remember the specifics of...

**Comment by peppy** [comment]
A reason may have been to avoid the situation where a default value is changed. But I'm not sure how valid that is.

We probably still want to remove these defaults eventually as they add a lot of overhead to an otherwise simple data structure.

**Pull request merged**
