### PR TITLE
Fix incorrect access to realm object in beatmap editor

### PR DESCRIPTION
**Pull request by peppy**
Fix `ModelManager` not correctly re-retrieving realm objects before performing operations

Falls into the age-old trap of attempting to retrieve an item from realm without first ensuring that realm is in an up-to-date state.

Consider this scenario:

- Editor is entered from main menu, causing it to create a new beatmap from its async `load()` method.
- Editor opens correctly, then main thread performs a file operations on the same beatmap.
- Main thread is potentially not refreshed yet, and will result in `null` instance when performing the re-fetch in `performFileOperation`.

I've fixed this by using the safe implementation inside `RealmLive<T>`.  Feels like we want this is one place which is always used as the correct method.

On a quick search, there are 10-20 other usages of `Realm.Find<T>` which could also have similar issues, but it'll be a bit of a pain to go through and fix each of these. In 99.9% of cases, the accesses are on instances which couldn't have just been created (or the usage of recently-imported/created is blocked by realm subscription flows, ie.  baetmap import) so I'm not touching them for now.

Something to keep in mind when working with realm going forward though.

This fixes a flaky test which has still been pinging in recent times (https://teamcity.ppy.sh/buildConfiguration/Osu_Build/42448?hideProblemsFromDependencies=false&hideTestsFromDependencies=false&expandBuildTestsSection=true).

### CODE REVIEW

**Comment by bdach** [comment]
Seems generally logical, but I'll wait for CI run before going further as on a quick check the test doesn't seem to want to flake on master on my box.

**Comment by bdach** [comment]
Well, unfortunately CI says no, because `RealmLive` always starts a transaction when performing writes, and it seems sometimes `performFileOperation()` was being called from within transactions already, causing

```
2023-08-16 05:49:56 [error]: The Realm is already in a write transaction
2023-08-16 05:49:56 [error]: Realms.Exceptions.RealmInvalidTransactionException: The Realm is already in a write transaction
2023-08-16 05:49:56 [error]: at Realms.Realm.BeginWrite()
2023-08-16 05:49:56 [error]: at osu.Game.Database.RealmLive`1.<>c__DisplayClass9_0.<PerformWrite>b__0(T t) in /home/runner/work/osu/osu/osu.Game/Database/RealmLive.cs:line 126
2023-08-16 05:49:56 [error]: at osu.Game.Database.RealmLive`1.<>c__DisplayClass7_0.<PerformRead>b__0(Realm r) in /home/runner/work/osu/osu/osu.Game/Database/RealmLive.cs:line 79
2023-08-16 05:49:56 [error]: at osu.Game.Database.RealmAccess.Run(Action`1 action) in /home/runner/work/osu/osu/osu.Game/Database/RealmAccess.cs:line 425
2023-08-16 05:49:56 [error]: at osu.Game.Database.RealmLive`1.PerformRead(Action`1 perform) in /home/runner/work/osu/osu/osu.Game/Database/RealmLive.cs:line 74
2023-08-16 05:49:56 [error]: at osu.Game.Database.RealmLive`1.PerformWrite(Action`1 perform) in /home/runner/work/osu/osu/osu.Game/Database/RealmLive.cs:line 124
2023-08-16 05:49:56 [error]: at osu.Game.Database.ModelManager`1.performFileOperation(TModel item, Action`1 operation) in /home/runner/work/osu/osu/osu.Game/Database/ModelManager.cs:line 51
2023-08-16 05:49:56 [error]: at osu.Game.Database.ModelManager`1.AddFile(TModel item, Stream contents, String filename) in /home/runner/work/osu/osu/osu.Game/Database/ModelManager.cs:line 42
2023-08-16 05:49:56 [error]: at osu.Game.Beatmaps.BeatmapManager.<>c__DisplayClass39_0.<save>b__0(Realm r) in /home/runner/work/osu/osu/osu.Game/Beatmaps/BeatmapManager.cs:line 467
```

Probably need to do a local manual refresh then somewhere? Not sure.

**Comment by peppy** [comment]
Funny because it passed locally.

**Comment by peppy** [comment]
My other option for this was to move that refresh logic into a static helper method and replace it everywhere. I'll try for that.

**Comment by peppy** [comment]
I've switched to using an extension method. In a future (or now I guess) we could ban usage of `Find<T>` and replace with this method.

**Review by bdach — APPROVED** [review]

**Pull request merged**
