### PR TITLE
Fixed banana generation on catch specific maps

### PR DESCRIPTION
**Pull request by frankhjwx**
Fix the bug when generating bananas on catch specific maps because of lacking ` IHasXPosition` property.

### CODE REVIEW

**Comment by peppy** [comment]
Your PR description says `IHasEndTime` but the diff is adding `IHasXPosition`.

**Comment by frankhjwx** [comment]
Sorry it's my fault, catch objects should have `IHasXPosition` property for object generating.

**Comment by peppy** [comment]
i’m not sure this is the correct fix as spinners in catch don’t actually _have_ an x position.

**Comment by smoogipoo** [comment]
A better fix would be to re-order `CatchBeatmapConverter` to generate spinners if there is no position data, rather than returning early.

**Comment by frankhjwx** [comment]
@smoogipoo That's right, the main problem is caused by `if (positionData == null)` judgement in `CatchBeatmapConvertor`

**Review by peppy — DISMISSED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
