### PR TITLE
Refactor skills - move logic out of inheritance hierarchy

### PR DESCRIPTION
**Pull request by joseph-ireland**
- [x] Depends on #15014

Split out the implementations of strain peaks, decaying values, and exponential weighted sums into their own functions apart from the Skill inheritance hierarchy.

In preparation for a PR to add a list of attributes for each hit object - see https://github.com/ppy/osu/discussions/14934

The simplest implementation of that would requre skills to have their own Process(DIfficultyHitObject) function in order to have access to current and cumulative strain. Leaving the inheritance hierarchy as is would result in a confusing ping pong of method calls up and down the inheritance hierarchy.

Note: This affects difficulty values.  Some of the simplifications make it slightly awkward to keep the initial strain value as 1, so I change the starting value to zero - see the relevant commit below.

It doesn't make sense for strain to start at 1 anyway - it's basically an unconfigurable strain for the first hit object which isn't affected by SkillMultiplier

### CODE REVIEW

**Review by bdach — DISMISSED** [review]

**Comment by bdach** [comment]
requesting review from committee wrt the initial strain change

**Comment by peppy** [comment]
Why is this adjusting values and also majorly changing structure? Why are those two things not done separately?

**Comment by bdach** [comment]
Several merge conflicts to be resolved here, unfortunately :(

**Review by bdach — COMMENTED** [review]
The structure seems fine to me. A few nitpicks with the docs but I consider the blockers resolved.

**Comment by GoldenMine0502** [comment]
I can't understand why straindecaybase and sectionlength should go into parameter.
why you did it? and how do we anticipate through it?

**Comment by smoogipoo** [comment]
Gonna close this for the time being since there's going to be some heavy merge conflicts. Feel free to rebase and open a new PR as I still think it's a good direction.

**Pull request closed without merging**
