### PR TITLE
Fix mania slider conversion never generating two hold notes

### PR DESCRIPTION
**Pull request by starburst997**

### CODE REVIEW

**Comment by nl-tatatat** [comment]
Its called isDoubleSample so doesn't that mean and?

**Comment by Aergwyn** [comment]
Could you please describe what exactly this fixes and change the title to be more descriptive?

**Comment by starburst997** [comment]
Well isn't it checking for a string variable being both "hitclap" and "hitfinish" at the same time?

`sample.Name == SampleInfo.HIT_CLAP && sample.Name == SampleInfo.HIT_FINISH`

It would never return `true`

**Review by smoogipoo — APPROVED** [review]
🤦‍♂️

**Pull request merged**
