### PR TITLE
Implement basic bookmark support in editor

### PR DESCRIPTION
**Pull request by bdach**
https://github.com/user-attachments/assets/8f248cb2-0bf5-4a7e-a841-903e97e5816d

RFC.

## [Move bookmarks out of `BeatmapInfo`](https://github.com/ppy/osu/commit/808934581fa0956e111941efef55fb99f69c54bf)

Not sure why I didn't do that in https://github.com/ppy/osu/pull/28473...

## [Implement basic bookmark support in editor](https://github.com/ppy/osu/commit/d60b7f479801f7a08ea588f17241abaff937ece2)

Should work, but is a bit touch-and-go:

- Bookmarks only display on bottom timeline. I thought a bit about having them show on the top timeline too, but I'm not sure I can fit it in there and not make the timeline even more oversaturated with info than it already is.
- I added the same bookmark hotkeys that are in stable, but two of them are not bound, and that's seek to previous/next bookmark - that is because their binding is taken by seeking to previous/next object now:
  https://github.com/ppy/osu/blob/f09d8f097a8b875c531da1e387a79acaf2ea0149/osu.Game/Input/Bindings/GlobalActionContainer.cs#L151-L152
- The only exposed way to mutate the bookmarks from the UI that is not the hotkey is in the timing menu. That's different from stable where there are bookmark controls near the bottom timeline, but again, not sure how to make that happen without cluttering things further.
- Not sure about using red (dangerous) stuff in the top menu. Might need a colour change at the least.

I'm hoping this will be considered as an ok baseline to build upon at least, but am open to adjustments as necessary. To that end I didn't even try to write tests for this, until the shape has solidified; once that happens, I will consider adding test coverage.

### CODE REVIEW

**Comment by peppy** [comment]
Ctrl+Shift+Left or Ctrl+Alt+Left should work for bindings I think.

Not sure about this being in the "timing" menu, wouldn't be the first place I'd look for bookmark controls. Still thinking about where would work best though.

**Comment by frenzibyte** [comment]
Never been an editor user, but considering the functionality I've seen from the video, I find "View" to be a good initial place for it as opposed to "Timing". Although it's a bit too crowded in that tab...

Randomly looking through Safari's menu tabs inspired me to say, maybe "Bookmarks" deserves its own tab in the top-level menu? It's unique from anything else, it's not purely visual to be in "View", nor  does it bare any perceivable changes to beatmap timing to be in a tab named "Timing", so maybe it should just be its own tab item in the top menu?

**Comment by bdach** [comment]
> Ctrl+Shift+Left or Ctrl+Alt+Left should work for bindings I think.

Doesn't appear to fail relevant tests if I checked them all, so applied in https://github.com/ppy/osu/pull/30960/commits/dc4a51bef8a2269c975b6738cec1d575ef879cd9.

> Not sure about this being in the "timing" menu, wouldn't be the first place I'd look for bookmark controls. Still thinking about where would work best though.

Was best place I could think of that already exists without inventing a new one.

> Never been an editor user, but considering the functionality I've seen from the video, I find "View" to be a good initial place for it as opposed to "Timing". Although it's a bit too crowded in that tab...

Pretty opposed to this, it makes no sense to put it in view. View is for things that affect the visual appearance of the editor, not for actual things that are saved to a beatmap etc.

**Comment by peppy** [comment]
As mentioned IRL, probably change this to use `alt`-`left`/`right` as the new binding choice conflicts with seeking between sample points on hitobjects.

2024-12-10 13 56 21@2x

**Review by peppy — APPROVED** [review]

**Pull request merged**
