### PR TITLE
Rewinding random beatmap selection (shift f2) now fills a stack that will be popped on next f2

### PR DESCRIPTION
**Pull request by JDECOMBE**
Rewinding random beatmap selection (Shift F2) now fills a stack that will be popped on next F2. Whenever that stack is empty, new F2 will be random.

For beatmaps A, B, C, D and E:
#### Previously:
F2 (random B) > F2 (random C) > F2 (random A) > Shift F2 (C) > Shift F2 (B) > F2 (random …)
#### Now:
F2 (random B) > F2 (random C) > F2 (random A) > Shift F2 (C) > Shift F2 (B) > ***F2 (C) > F2 (A)*** > F2 (random …)

This is something that has been bothering me in stable for quite some times, and I think that this is quite useful whenever looking for something to play using F2.

### CODE REVIEW

**Comment by bdach** [comment]
Not sure why this was PR'd without prior discussion. What if I *want* a truly random selection after a <kbd>Shift</kbd>+<kbd>F2</kbd>?

Also *if* this is going to be a thing then it needs solid test coverage at least because the added complexity in logic is making my head spin.

**Comment by JDECOMBE** [comment]
-> ` the added complexity in logic is making my head spin`
 
There isn't really much logic that was added, it's quite similar to what's done to create the Shift-F2 mechanic in the first place: when Shift-F2, add to a stack. When F2, simply pop from the stack if not empty or just randomize like before if empty.

-> `What if I want a truly random selection after a Shift+F2?`
Just go to the end of the stack, I feel like most of the time you Shift-F2 three to five times at most. And I don't really see a moment when you absolutely wouldn't want this new behavior. 

-> `Not sure why this was PR'd without prior discussion.`
Tbh I was playing stable and lost track of a map because of this for the nth time and I just decided to see if I could make it work in lazer...
I agree with you, it just felt like an improvement I'd like to see and that's it, didn't know how things worked around here and I thought that making the code could help understanding this proposition easily.

-> `Also if this is going to be a thing then it needs solid test coverage at least`
I planned on making those if the proposition (not PR) got approved.

**Comment by bdach** [comment]
> There isn't really much logic that was added

The shuffle/rewind logic was already quite complex. Now it's even more complex; there is `previouslyVisitedRandomSets` and `randomSelectedBeatmaps` and also `randomSelectedPreviousBeatmaps`, and multiple code branches were added to read from the right queue at the right time.

The best way to deal with complexity such as this is not have in the first place unless it's absolutely unavoidable, and I don't personally believe it is required. Especially for a feature such as this which works silently without any indication to the user as to *how* it works. With this feature the "random" button is only random if there was no rewind; you would have to externally explain to the user that the random button has two-way undo semantics.

> Not sure why this was PR'd without prior discussion.

As per [contribution guidelines](https://github.com/ppy/osu/blob/master/CONTRIBUTING.md):

> If you wish to work on something with the intention of having it included in the official distribution, please open an issue for discussion and we will give you what you need from a design perspective to proceed.

**Comment by JDECOMBE** [comment]
Everything you said makes sense to me.
Do you want me to close this PR and create an issue on this matter tomorrow ?
Sorry for the misused of the "issue/PR" process

**Comment by bdach** [comment]
I'd hold off on doing anything with this pull for now until we're sure that the other team members share my point of view.

**Comment by JDECOMBE** [comment]
I understand the feeling behind your points (not expected behavior and overloading the UX with modifiers). Nevertheless, I'd say that this can become handy (from personal experience, I mainly use F2 to search for maps to play, and not go back bother me at least once per session). Using another modifier (ctrl ?) could be a decent option, as it would make the feature available without changing the default behavior.
I don't really know how many people would use this feature though, I am only speaking for me and a few friends who get bothered by this.
What should I do with this PR ? 
Thanks to both of you for your feedback !

**Comment by bdach** [comment]
I think it would be best to close this and move this to a discussion thread wherein maybe we can find a better place for this functionality. One idea that could work is having a "selection history" view in the now playing overlay here:

2022-01-07-123928_547x872_scrot

It would be a general feature useful for more contexts than just random. Again, whether that's the direction to take should be decided after the appropriate discussion is had.

**Pull request closed without merging**
