### PR TITLE
Improve scroll tracking of selected item

### LINKED ISSUE #10934: Beatmap carousel always scrolls from top when filtering
**Describe the bug:** 
Because all beatmap Y positions move closer to the top when applying a more narrow filter, all scrolling seems to scroll from the top even thought the beatmap might have already been on screen below the selected beatmap. Same vice-versa - when expanding/removing the filter, all scrolling seems to happen from bottom.

**Screenshots or videos showing encountered issue:** 
https://imgur.com/a/y2vBAl6 (gif would have been over 10MB)

**osu!lazer version:** 
Unpushed code at #8384 (it's difficult to see in actual releases because the selection after filtering is random)
master is at 09f905355d2052a6f15c4c52178fec0e4f206775

edit: Example video from 2020.1121.0: https://imgur.com/a/gVqtzNz

### PR DESCRIPTION
**Pull request by peppy**
Fixes many of the animation edge cases / glitches of song select along the way.

I've described each change in detail in the commit messages, so suggest you read those during review to better understand reasoning (although there is also inline commenting which hopefully covers most of what is going on).

Closes #10934.
Supersedes and closes #10955. I went in a different direction to that version when implementing this.

master:

this PR:

Previous worst case scenario (last beatmap in list, meaning largest Y value for panel):

### CODE REVIEW

**Comment by LittleEndu** [comment]
It would be awesome if scrolling on random could be restored. Scrolling seems to happen if you <kbd>Shift</kbd>+<kbd>F2</kbd> but only once, there's definitely something inconsistent going on. 

Filtering + randomizing seems to act the most inconsistent: https://youtu.be/q2xxIyd8kN8

**Comment by peppy** [comment]
@LittleEndu should be better now, please give it a test.

**Comment by LittleEndu** [comment]
I can still get some weird behaviour when I force the selection to change. Sometimes the selected beatmap needs to scroll onto screen, sometimes there are panels flying across other panels that were already on screen.

https://youtu.be/8jPv7vycOBU is with #8384 applied such so you know what's going to be selected.

https://youtu.be/Gm2UQZaOd3U and https://youtu.be/Pbp2c7TbW4s are just this PR. Still can get some weird behaviour if the filter results in just a few beatmaps to remain. 

Also found #10987 while testing this, but that isn't caused by this PR. Although this means you can't really tell how ruleset changing looks like. Only other thing I can think to check is ``presentBeatmap`` and that seems to work just fine with a satisfying seek just like random does now.

**Comment by peppy** [comment]
that behaviour is expected. panels which were not newly retrieved from pool will be animated.

further work could be done to add animation back to pooled panels but that's not happening in this PR.

**Review by smoogipoo — APPROVED** [review]
Seems to work as expected and the changes look sane :+1:

**Pull request merged**
