### PR TITLE
Allow mod buttons to not be stacked

### PR DESCRIPTION
**Pull request by smoogipoo**
Useful for freemod, where stacking really doesn't make sense.

### CODE REVIEW

**Comment by peppy** [comment]
Woah, I'm 100% against this. I don't think we should be rearranging the layout of mods just to work around an issue like this. Do you have any alternatives?

**Comment by smoogipoo** [comment]
The case is a code complexity case. ModButtons aren't meant to handle MultiMods, and neither does the rest of the overlay.

Put it this way, if you want stacking to work, then it requires rewriting ModSelectOverlay / not using ModSelectOverlay for freemods. I'm unwilling to do that with current designs or by hacking onto the current designs - I want flyte's new designs so I can implement such a rewrite once only.

**Comment by peppy** [comment]
Is it feasible to just show the base mod (ie. DT but not NC) and have it count for both as a temporary measure?

**Comment by smoogipoo** [comment]
I don't think I can convince you unless you try it yourself. Again I had it that way and the amount of complexity and hackery made me think again.

**Comment by peppy** [comment]
I'm willing to take your word for it, as long as we agree that this needs to be fixed as soon as the new mod select design is ready as a priority. I'd really hope that the ordering/position of mods on the dialog isn't changing depending on where you open the dialog from (thought based on what i've seen in the new design this may actually be less of a problem in the first place..)

**Comment by smoogipoo** [comment]
Discussed in voice chat. The gist of it is that I found it hard to implement it with stacked mods because of all the structures in `ModSelectOverlay` that don't lend themselves well to that sort of workflow. If flyte's new designs have stacking then I'm willing to implement it and agree on that path forward, and figure out what to do with fine-tuning for cases like mania's HD/FI, keymods, and osu!'s BL/FL, if those are concerns.

Eventually we probably want to have some sort of search functionality as the list of mods grows, too.

**Review by peppy — APPROVED** [review]

**Pull request merged**
