### PR TITLE
Add extended info support to tiny mod switches

### PR DESCRIPTION
**Pull request by Joehuu**
- Needed for https://github.com/ppy/osu/pull/22237

Mostly copied from `ModIcon`, but:
- `ModSwitchTiny.Mod` is immutable so kept it that way
- `showExtendedInformation` defaults to false as current usages don't need it
- little tweak to font size

https://github.com/ppy/osu/assets/35318437/ddda6117-e557-4f90-96f7-f885a6c52afd

### CODE REVIEW

**Comment by Tanza3D** [comment]
thought i'd drop my thoughts on this - text colour's a little off from the switches but im guessing that's intentional. design looks good

**Review by peppy — APPROVED** [review]
Seems to do the job

**Comment by Loreos7** [comment]
I'm against such a design of mod icons, because it is impossible to understand from the abbreviations at a glance which mods were applied to the score. It is much easier to distinguish records by unique icons.

**Comment by peppy** [comment]
All well and good, but these are already used all over the place. You're better off opening a discussion separate from this PR, which is doing not much more than adding support for multipliers.

**Pull request merged**
