### PR TITLE
Fix slider border not reverting to default color

### LINKED ISSUE #4698: Slider Border color doesn't revert to default until map restart
**Describe the bug:** Basically I've noticed on **[this map](https://osu.ppy.sh/beatmapsets/618500#osu/1303748)** that the slider border color doesn't revert to the default one when the user tries to disable the beatmap skin.
**_This seems to happen with the default osu!lazer skin, with other skins the slider border changes color as expected._**
Storyboard and Hitsounds seem to work normally.

**Screenshots or videos showing encountered issue:** 

Video: https://streamable.com/8k4m1

Beatmap Skin turned on:
osu_2019-05-02_15-19-06

Beatmap Skin turned off:
osu_2019-05-02_15-19-11

**osu!lazer version:** 2019.502.0

**Logs:** N/A

### PR DESCRIPTION
**Pull request by Joehuu**
Fixes #4698.

---

### CODE REVIEW

**Comment by peppy** [comment]
The same fix should probably apply to the other two colours in this method.

**Comment by Joehuu** [comment]
Those two are already defined by the combo colours, I think. Anyway, they don't seem broken and it reverts correctly.

**Comment by peppy** [comment]
I'm not sure what you mean by "defined by combo colours". The point is, if this method is called twice, it will not correctly restore the fallback colour.

**Comment by Joehuu** [comment]
Not sure how to apply same fix (`Color4.White`) to other colours.

**Comment by peppy** [comment]
@Joehuu See my last commit for the correct fix for the other two.

**Review by peppy — APPROVED** [review]

**Pull request merged**
