### PR TITLE
Add support for "argon" default skin to expand columns when on mobile devices

### LINKED ISSUE #23377: Improve playability of osu!mania on small touch screen devices
### Type

Crash to desktop

### Bug description

awfully small hitbox placement which is really hard to use on mobile

### Screenshots or videos

Screenshot_2023-05-02-23-07-21-710_sh ppy osulazer

### Version

2023.419.0

### Logs

> 
[database.log](https://github.com/ppy/osu/files/11377400/database.log)
[runtime.log](https://github.com/ppy/osu/files/11377401/runtime.log)
[network.log](https://github.com/ppy/osu/files/11377402/network.log)
[performance.log](https://github.com/ppy/osu/files/11377403/performance.log)

### PR DESCRIPTION
**Pull request by peppy**
Closes https://github.com/ppy/osu/issues/23377.

Note that screenshots are taken at a less-wide-than-most-phones-these-days aspect ratio, so if anything, on a device there will be more padding on the sides. Also note that I set an upper limit to the width at lower key counts. We could adjust this based on feedback, but it's basically in place to stop the game from looking silly.

---

Should ease those looking to play the game on mobile until we (potentially) have a better solution in the future.

If this works out well, we can consider rolling it out to other skins.

| Keys |  |
|--------|--------|
| 4 | CleanShot 2023-11-02 at 06 17 51 |
| 5 | CleanShot 2023-11-02 at 06 18 17|
| 7 | CleanShot 2023-11-02 at 06 12 42 |
| 20 | CleanShot 2023-11-02 at 06 18 57|

### CODE REVIEW

**Comment by bdach** [comment]
Took some screenshots on my device.

| keys | single stage | dual stages |
| :-: | :-: | :-: |
| 1 | 1k | 1+1k |
| 2 | 2k | 2+2k |
| 3 | 3k | 3+3k |
| 4 | 4k | 4+4k |
| 5 | 5k | 5+5k |
| 6 | 6k | 6+6k |
| 7 | 7k | 7+7k |
| 8 | 8k | 8+8k |
| 9 | 9k | 9+9k |
| 10 | 10k | 10+10k |

7k and 9k single-stage are of particular note - in both, the bar line does not cover the entire width of the stage anymore:

image
image

likely due to whatever this is:

https://github.com/ppy/osu/blob/e18d0b64de9ee5cb67328818c92d983ee346c514/osu.Game.Rulesets.Mania/UI/Stage.cs#L92

That said I do think tweaking the column width in those cases is actually the better option there. Exceeding 1366 width means that there is a likelihood of issues stemming from the stage no longer fitting on the screen (due to foibles in how `ScalingContainer` works).

**Review by bdach — CHANGES_REQUESTED** [review]
see above

**Comment by peppy** [comment]
Nice catch. I've adjusted sizing down a bit.

**Comment by bdach** [comment]
Looks better now:

| keys | single stage | dual stages |
| -: | :-: | :-: |
| 1k | 1k | 1k+1k |
| 2k | 2k | 2k+2k |
| 3k | 3k | 3k+3k |
| 4k | 4k | 4k+4k |
| 5k | 5k | 5k+5k |
| 6k | 6k | 6k+6k |
| 7k | 7k | 7k+7k |
| 8k | 8k | 8k+8k |
| 9k | 9k | 9k+9k |
| 10k | 10k | 10k+10k |

**Review by bdach — APPROVED** [review]

**Comment by Susko3** [comment]
Maybe this could use [touchscreen detection](https://github.com/ppy/osu/pull/25348) instead of `RuntimeInfo.IsMobile`? (No idea how you'd get dependency injection though.)

The wider columns feels pretty good to use even on a touchscreen on windows.
And someone playing on their android/ios tablet with a keyboard might expect the default column width.

**Comment by peppy** [comment]
> Maybe this could use [touchscreen detection](https://github.com/ppy/osu/pull/25348) instead of `RuntimeInfo.IsMobile`? (No idea how you'd get dependency injection though.)
> 
> The wider columns feels pretty good to use even on a touchscreen on windows. And someone playing on their android/ios tablet with a keyboard might expect the default column width.

Not sure. This is intentionally scoped right now to get things released in the fastest way possible. If we're adding complications I'd want to reassess the situation. ie. make this a custom argon skin instead (Argon touch or something).

**Pull request merged**
