### PR TITLE
Run EF migrations before migrating to realm

### PR DESCRIPTION
**Pull request by peppy**
Turns out that there are more than zero users that are upgrading from old databases. I think we probably want to support this for now.

Tested against database in https://github.com/ppy/osu/discussions/16700 and one other I had locally, both work correctly.

We can reassess removing these when the time comes.

### CODE REVIEW

**Comment by bdach** [comment]
Out of curiosity how was this diff produced? 78a0d5d's commit message reads as if it reverts the merge of the entirety of https://github.com/ppy/osu/pull/16502, but that pull also removed some EF helpers (6ddd2d5) and they don't seem to have been brought back here.

So I guess my question is: was the merge commit reverted but then amended with the re-removal of the helpers? Seems like a weird way to do it. I would have just reverted bb5b945 and that one commit alone, rather than revert the entire merge and then fix it up in post in a bit of a confusing manner.

**Comment by peppy** [comment]
Sure I'll change it and force push.  Not sure which is more correct in this case.

**Review by frenzibyte — APPROVED** [review]
Seems to work testing from an old version and also latest prior-to-realm version to ensure nothing funny happens when there's nothing to migrate.

**Comment by bdach** [comment]
Seems to work in my testing. From the previous review discussion keeping migrations was the preferred initial choice anyway so I don't see a reason not to merge this.

**Review by bdach — APPROVED** [review]

**Pull request merged**
