### PR TITLE
Update netstandard with the latest master changes

### PR DESCRIPTION
**Pull request by smoogipoo**

### CODE REVIEW

**Comment by smoogipoo** [comment]
I've reupdated, this is still going to fail with CI errors + warnings, but those are coming up because resharper doesn't understand debug vs release with netstandard yet.

Those should be fixed on master.

**Review by peppy — DISMISSED** [review]
/shrug i was told to

**Comment by smoogipoo** [comment]
@peppy can you admin merge this in? Resharper/rider is super duper broken and providing wrong inspections. All but one or two of those are incorrect inspections, and locally it's even worse:

screen shot 2018-01-05 at 12 38 15 pm

**Comment by peppy** [comment]
Forcefully merging pending potential r# fixes.

**Pull request merged**
