### PR TITLE
Increase Speed difficulty for maps by accounting for High BPM Streams and Stamina

### PR DESCRIPTION
**Pull request by minwoo0jo**
I've been thinking for a while that it was strange that there was nothing that accounted for stamina in the diffcalc algorithm, so I finally decided to put in my 2 cents regarding this topic.

Xexxar's pull request gives clear reasons why aim players have advantages over stamina players in the current ranking system, and for the most part, I would agree. Therefore, I will just jump right into what I propose to do about this imbalance.

Proposals:
Okay, so let's start with the main thing I'm proposing to change. Since speed itself scales so much with distance, I've added a new type of strain called stamina. This is basically identical to how speed value is calculated, but will only go up to a 30% bonus at max distance, as opposed to the 163% bonus for speed. This is otherwise dealt with in an identical fashion to speed, until a certain threshold.

When it reaches this threshold (currently set at the equivalent of 50 stacked 1/4 notes in a row at 220 BPM), it will trigger the speed strain to start decaying less between notes. The threshold is then raised and once reached again, can trigger the change to decay again. There is an upper cap on this, which occurs after the threshold has been reached approximately 65 times, but most playable maps will not get anywhere near this.

If there is a sufficient amount of time between two notes (currently set at the equivalent of 150 BPM 1/4 timing), the decay will rapidly approach the original value again. This means high BPM repeat burst type maps will not be affected nearly as much, but that can be a change for another time.

My second proposal is to make the final speed value scale much more heavily with the accuracy. With high BPM long streams starting to be valued higher, it's important that the accuracy be kept up high for a sizable amount of pp. I've changed the way the final speed value scales with accuracy from

speedValue *= 0.5f + accuracy / 2.0f;

to

speedValue *= 0.5f + Math.Pow(accuracy, 0.5 + ODSquared * 0.025) / 2.0f;

However, as stated earlier, speed is not only used to calculate tapping strain, but also aim involving spaced streams. I am fully aware that many maps might be overly nerfed by this, and I don't expect this particular change of the pull request to survive any extensive testing.

Data:
So this is the weakest part of the pull request, and I will have to ask others to assist me later on as I have not tested an extensive list of maps.

Nevertheless, here are a few screenshots showing some of the changes.
edit: Sorry I forgot to revert a small change and accidentally had wrong values. They should be correct now.

Star Rating: http://puu.sh/AyJON/d7bfa0f764.png http://puu.sh/AyJPR/f70352316c.png - nomod
http://puu.sh/AyJSo/406ff16fe2.png - DT

PP: http://puu.sh/AyJLw/3983f1fb1b.png http://puu.sh/AyJIQ/21145c37f0.png

Values on the right are without my change and the values on the left are with my change.

Thank you for reading!

### CODE REVIEW

**Comment by Mini-Gaunt** [comment]
A couple things:
1. 50 stacked objects is too many, I would consider lowering it to 20 or 25. I would also consider scaling the number of objects that are in a stream with its bpm, it is unreasonable to ask someone to stream a really high bpm for 25 notes when we are approaching the limit of the human body.
2. When talking about stamina, you don't suddenly regain stamina while doing singletaps between streams. (ex. Everything Will Freeze [Time Freeze]) there are 240 bpm 1/2s circles and sliders in between streams. The amount of stamina required is much higher than if there were no circles/sliders between the streams. I would consider changing the 150bpm 1/4ths triggering the decay to anything lower than 220 bpm 1/2s

Other than those two minor tweaks to the numbers, you did a really good job. Nice one.

**Comment by minwoo0jo** [comment]
1. Don't get me wrong. The condition to trigger the buff is not a simple "hit 50 notes and the buff will trigger" and more of a "hit a certain strain value and the buff will trigger" how many notes required to hit this will be highly dependent on the BPM and also spacing to a smaller extent.

For example, while it takes 50 stacked notes to hit the required stamina strain at 220 BPM, it takes only 17 to trigger at 270 BPM.

However, I'm not really too sure about the specific numbers and will be perfectly willing to change them if needed.

2. You're right, stamina doesn't fully recover in situations like the one you described in everything will freeze. However, it still should recover at least a little bit because it is still less straining than having to stream the whole way through. Not only that, consider if the whole thing was stacked. The 1/2 notes would be pretty easy to just slowly stream through while completely recovering stamina. It would be highly abusable in this case if 1/2 timing just froze the current decay rate, allowing for situations where the player is recovering stamina, yet the game will not trigger the stamina recovery mechanic.

By the way, when the stamina recovery triggers, it doesn't instantly change the decay back to the original value. It's just much faster going back down than it was going up.

**Comment by minwoo0jo** [comment]
Although it might seem like an okay change based on the data I provided, please keep in mind that I provided data on maybe 40 maps and that's definitely not enough to get a good idea of how this change affects osu as a whole. If anyone can and would like to help me with getting some more extensive data on this that would be greatly appreciated.

**Comment by smoogipoo** [comment]
Closing as this has already been done in a different way (see "High BPM streams" section of https://osu.ppy.sh/home/news/2019-02-05-new-changes-to-star-rating-performance-points).

**Pull request closed without merging**
