### PR TITLE
Ensure audio filters can't be attached before load (or post-disposal)

### LINKED ISSUE #27225: Song audio gets really muffled overtime in lazer
### Type

Game behaviour

### Bug description

As I was playing I noticed that the song audio sounds very muffled, everything else sounded fine like the sfx and on pc in general, so not a hardware issue. When I continued to play, the audio suddenly went even more muffled and was barely hearable. When I restarted the game everything went back to normal.

### Screenshots or videos

Muffled https://streamable.com/0cfcg7
Unmuffled (after restart) https://streamable.com/kanemh

### Version

2024.131.0

### Logs

I don't have the logs since the bug occurred yesterday and I didn't think at all of saving it, it was on reddit where I was suggested to report this to github after some time. Sorry if this can't be looked on without a log.

### PR DESCRIPTION
**Pull request by peppy**
Will probably fix https://github.com/ppy/osu/issues/27225?

### CODE REVIEW

**Comment by Kyouran01** [comment]
Sorry, I have no idea what this means..

**Comment by frenzibyte** [comment]
This doesn't look like it would help. The only game usage of the `Cutoff` property is via transforms, and all transforms are being processed by the `AudioFilter` components themselves, so I would imagine they would never run post disposal, unless something is fundamentally wrong with the drawable hierarchy (which I hope is not the case?). 

I'm wondering if async disposal has something to do with this, like the update thread processing through the `AudioFilter.UpdateSubTree()` method after `Dispose` has been called already...I'm not really sure if that's the case (I can't say I know async disposal too well), but if what I'm saying has some sense in it, I think you could guard against that by never allowing an audio filter to be attached after `Dispose` is called.

**Comment by peppy** [comment]
> unless something is fundamentally wrong with the drawable hierarchy (which I hope is not the case?).

cutoff being set in BDL can definitely cause this, and we've seen it happen before. it could run after disposal.

**Comment by frenzibyte** [comment]
I'm not sure. Disposal running after BDL makes sense, but I can't see how it applies here. For that to occur, the initial cutoff of an `AudioFilter` must be set to a value that has an effect on the audio, and the only use case that matches this criteria is the following line in `PlayerLoader`:
https://github.com/ppy/osu/blob/583e71634f309ce5e7d56ffcd2796644ad981c4b/osu.Game/Screens/Play/PlayerLoader.cs#L429

But then, that means `PlayerLoader.OnEntering` would have been called while the screen is disposed for the entire issue to occur, right? But that event is invoked when `Screen.LoadComplete` is invoked first, so the pieces aren't connecting here.

I'm willing to disregard looking into this any further and call it "async disposal weirdness" as the changes in this PR are valid to my eyes already and I'm not sure sparring a discussion for this is worth anyone's time right now.

**Review by frenzibyte — APPROVED** [review]

**Comment by bdach** [comment]
Maybe also does something for https://github.com/ppy/osu/issues/24100?

**Review by bdach — APPROVED** [review]

**Pull request merged**
