### PR TITLE
Fix beatmap card song preview progress sometimes showing past progress for one frame

### PR DESCRIPTION
**Pull request by Joehuu**
Similar to https://github.com/ppy/osu/pull/22607, but harder to reproduce / know if this change fixes it.

Process of reproducing (in master):
- Play ~1/4 of at least two previews and repeat (takes about 10 times until the visual bug happens)

https://user-images.githubusercontent.com/35318437/218588319-e9ad4f31-d194-4edf-9af7-10a4c399283e.mp4

You can reproduce it with one preview, but the behavior will change to pause (same as web) so trying to reproduce via ^ is more correct.

### CODE REVIEW

**Comment by bdach** [comment]
Do you have an explanation for why `Update()` is wrong here? I'd rather not have to go and find out myself if I can avoid it.

**Comment by Joehuu** [comment]
I do not as I don't have a good understanding of `Update()` and `UpdateAfterChildren()`.

I know that linking another PR that was merged with a similar fix is not an excuse to why I can't explain the code side of these fixes.

**Comment by peppy** [comment]
This is going to be due to the delay of the (re)starting of the `PreviewTrack` playback due to threading (it will run on the audio thread). Until the track is restarted, its `CurrentTime` will be the same as when it stopped.

I think therefore that this fix may not *always* work (if there are some *very* inopportune frame timings).

Could you give this a try instead?

```diff
diff --git a/osu.Game/Audio/PreviewTrack.cs b/osu.Game/Audio/PreviewTrack.cs
index 2c63c16274..d625566ee7 100644
--- a/osu.Game/Audio/PreviewTrack.cs
+++ b/osu.Game/Audio/PreviewTrack.cs
@@ -98,6 +98,9 @@ public void Stop()
 
             Track.Stop();
 
+            // Ensure the track is reset immediately on stopping, so the next time it is started it has a correct time value.
+            Track.Seek(0);
+
             Stopped?.Invoke();
         }
;
```

**Review by peppy — CHANGES_REQUESTED** [review]
As proposed.

**Comment by Joehuu** [comment]
I found that the visual bug is 99% reproducible on single thread with v-sync in master. I retested with my solution and it still fixes it.

> Could you give this a try instead?

That solution works too. Will apply that instead.

**Comment by peppy** [comment]
> I found that the visual bug is 99% reproducible on single thread with v-sync in master. I retested with my solution and it still fixes it.

Yeah, that sounds correct. But to provide you with a better understanding of how it could fail, imagine this scenario in multi-threaded mode:

```csharp
PreviewTrack.Stop()
    UpdateThread.Update
    AudioThread.Update
    // track is in a state with CurrentTime > 0
    UpdateThread.Update
        -> click is handled and play is queued on audio thread
    // In the 99.99% majority scenario, AudioThread.Update would run here as it is running at 1,000hz and generally waiting for operations to run
    UpdateThread.UpdateAfterChildren // your UpdateAfterChildren code would run here
    // In the 0.00001% scenario, AudioThread.Update may not have run until here, which may still result in the visual discrepancy
```

**Review by peppy — APPROVED** [review]

**Pull request merged**
