### PR TITLE
Adjust some mod multipliers for initial leaderboard sanity

### PR DESCRIPTION
**Pull request by peppy**
There may be others we want to adjust. Note that these are basically placeholder safe values (lower is better) so we can allow these scores on the leaderboard without people complaining about unfairness... unless they are complaining the multiplier is too low (which is fine for now).

RFC, mainly to identify any other mods which need to be adjusted.

### CODE REVIEW

**Comment by longnguyen2004** [comment]
There's also HT to think about. With the current multiplier (0.7x at default settings), it's significantly higher than both osu! (0.3x) and osu!mania (0.5x). This can lead to the leaderboard being filled with HT scores, on maps that don't have a lot of S rank nomod scores due to its difficulty ([example](https://osu.ppy.sh/beatmapsets/1948301#mania/4032124)), disincentivizing players to go for nomod.

**Comment by peppy** [comment]
> There's also HT to think about. With the current multiplier (0.7x at default settings), it's significantly higher than both osu! (0.3x) and osu!mania (0.5x). This can lead to the leaderboard being filled with HT scores, on maps that don't have a lot of S rank nomod scores due to its difficulty ([example](https://osu.ppy.sh/beatmapsets/1948301#mania/4032124)), disincentivizing players to go for nomod.

Thanks for pointing this one out. I've changed the range to `0.1x ... 0.5x` with `0.3x` being the default multiplier at 75% playback.

**Review by bdach — APPROVED** [review]
Seems fine from a correctness standpoint.

I don't feel qualified to talk about the balance aspects but I can generally agree that starting too low is generally preferable to starting too high.

**Comment by TextAdventurer12** [comment]
I believe [this](https://www.desmos.com/calculator/nmae2qhmrz) is the curve on a graph against rate. I'm not a huge fan of the massive jump from 0.9x to 1.0x, since the difficulty change is definitely less than 40%, but I agree with bdach that underestimation is better than overestimation

**Review by smoogipoo — APPROVED** [review]

**Comment by longnguyen2004** [comment]
> I believe [this](https://www.desmos.com/calculator/nmae2qhmrz) is the curve on a graph against rate. I'm not a huge fan of the massive jump from 0.9x to 1.0x, since the difficulty change is definitely less than 40%, but I agree with bdach that underestimation is better than overestimation

There will be future changes down the line (see https://github.com/ppy/osu/pull/25733), this is just to make sure we don't have a flood of HT scores on the leaderboard for now.

**Comment by cdwcgt** [comment]
if `Synesthesia` have 0.8 multiplier, so is that mean mania play with `Timing-based note colouring` need have 0.8x?

**Comment by longnguyen2004** [comment]
> if `Synesthesia` have 0.8 multiplier, so is that mean mania play with `Timing-based note colouring` need have 0.8x?

Yes, but it needs to be turned into a mod first

**Pull request merged**
