### PR TITLE
Improve the feel of hovering components in the skin editor toolbox

### PR DESCRIPTION
**Pull request by peppy**
Previously the expand and contract of elements were not aligned chronologically, which could create ugly changes in content height of the view itself (making it very hard to target buttons once one or more were expanded).

This changes things up to ensure that the expand and contract animations (usually) happen together.

Before:

https://user-images.githubusercontent.com/191335/219610487-de4e6d8a-b375-4a03-a11e-c6db365f017e.mp4

After:

https://user-images.githubusercontent.com/191335/219610816-049f59e2-1d86-434e-9459-5591150e288d.mp4

### CODE REVIEW

**Comment by bdach** [comment]
Managed to break this slightly:

1. Hover a toolbox item
2. Unhover the item, but do not hover any other item (can be done by exiting the toolbox completely to the right)
3. Come back to the item hovered in step (1)
4. The item will spontaneously contract after a second

https://user-images.githubusercontent.com/20418176/219800176-b9eb4ad6-e925-49f9-a246-f9881a71c6ef.mp4

**Review by bdach — CHANGES_REQUESTED** [review]
as above

**Comment by bdach** [comment]
Actually, on second thought, the fix is trivial, so I pushed it (https://github.com/ppy/osu/pull/22672/commits/2aa4481f6802feed215633d62c43044aa5ef38cb). Please double-check it though.

**Review by bdach — APPROVED** [review]

**Comment by peppy** [comment]
Nice catch, fix looks good 👍 .

**Pull request merged**
