### PR TITLE
Add ability to change timings of follow point display

### PR DESCRIPTION
**Pull request by chrisny286**
two sliderbars added that change the values for the fadeout delay(preEmpt) and the time at which followpoints start to appear(offset value)

might as well add an option to change the point distance if this seems to be a nice idea.

---

Added settings under gameplay to modify slider rendering.
[short video](https://puu.sh/CA3Eo/2c82af79d0.mp4)

### CODE REVIEW

**Comment by peppy** [comment]
First of all, I'm not sure if we want to give customisation over game elements which could potentially give an advantage to gameplay.

Secondly, this is something which should exist at a skin configuration level. We don't yet have a UI for that, but it definitely doesn't belong where it is (especially since it only affects osu! ruleset but it being placed in game-wide settings).

**Comment by chrisny286** [comment]
Okay, so addressing the first point: 
The values for the offset and timing could be limited so that at no point you could display followpoints ahead of the preset timing that was given before.
That way it would also be in line with the current stable build where usually every skin has animated followlines which blend out the first ~200ms and also the last ~200ms because the default with only the followpoint.png is too crowded

Second point:
So that the skin.ini file contains this information and can be adjusted per skin? 
some options in stable also only have effects on certain rulesets though are stored in the user.cfg (like mania bpm scaling scrollspeed for example)

**Comment by peppy** [comment]
We already have per-ruleset settings implemented (see `OsuSettings.cs`).

Also yes and no. skin.ini is a legacy file format and likely not what we will be using going forward. That said, databasing of skin settings is not quite ready yet, so we can't add it there just yet.

**Comment by smoogipoo** [comment]
Closing this for now since this will need a complete rewrite to:
1. Use the new follow point structure.
2. Use the skin settings.

And skin settings are awaiting further implementation as a prerequisite (such as databasing, for a start).

**Pull request closed without merging**
