### PR TITLE
Fix broken recent scores section in user overlay

### PR DESCRIPTION
**Pull request by EVAST9919**

### CODE REVIEW

**Comment by peppy** [comment]
Where are you seeing this? Please open an `osu-web` issue if it's still happening. It should have been fixed via https://github.com/ppy/osu-web/pull/4679.

**Comment by EVAST9919** [comment]
Screenshot_1

**Comment by peppy** [comment]
Please post an issue against osu-web. A bool should not be null.

**Comment by peppy** [comment]
Made it for you https://github.com/ppy/osu-web/issues/4705

**Pull request closed without merging**
