### PR TITLE
Add `maximum_statistics` to `ScoreInfo`

### PR DESCRIPTION
**Pull request by smoogipoo**
Supersedes / closes https://github.com/ppy/osu/pull/19380

Example of how this looks in scores: https://gist.github.com/smoogipoo/27f5fee15cb8d1723c97f2bf20101d48

This PR just adds the `maximum_statistics` dictionary to `ScoreInfo`. It does not make use of the dictionary yet. An explanation of everything is below.

## Introduction

Computing total score is currently very complex. osu!lazer has to:
1. Retrieve maximum combo of the beatmap. This is sometimes (but not always) done by [invoking the difficulty calculator](https://github.com/ppy/osu/blob/4627e4f53b96a6571c63ab5cf08accede4877537/osu.Game/Scoring/ScoreManager.cs#L160-L186).
2. Figure out the "actual accuracy". In particular, there is a [special case for mania](https://github.com/ppy/osu/blob/4627e4f53b96a6571c63ab5cf08accede4877537/osu.Game/Rulesets/Scoring/ScoreProcessor.cs#L343-L344) for legacy scores.

These two points make the calculations very non-portable and several projects need to be able to compute total scores in real-time. To resolve this, extra data is to be attached to `ScoreInfo` in one of two formats:

<table>
<tr>
<th><a href="https://github.com/ppy/osu/pull/19380">1: Storing maximum scoring values</a></th>
<th>2: Storing maximum statistics</th>
</tr>
<tr valign="top">
<td>

```json
{
    "max_combo": 1,
    "statistics": {
        "great": 1,
        "miss": 99,
        "small_tick_miss": 10,
        "large_tick_miss": 10,
        "ignore_miss": 1
    },
    "base_score": 300,
    "bonus_score": 0,
    "maximum_scoring_values": {
        "base_score": 30400,
        "bonus_score": 50,
        "max_combo": 110,
        "large_ticks_count": 10,
        "small_ticks_count": 10
    },
    "legacy_total_score": 0
}
```

</td>
<td>
    
```json
{
    "max_combo": 1,
    "statistics": {
        "great": 1,
        "miss": 99,
        "small_tick_miss": 10,
        "large_tick_miss": 10,
        "ignore_miss": 1
    },
    "maximum_statistics": {
        "great": 100,
        "large_bonus": 1,
        "large_tick_hit": 10,
        "small_tick_hit": 10
    },
    "legacy_total_score": 0
}
```

</td>
</tr>
</table>

From either of the above two formats, it should be possible to compute total score with _just_ the data present in the individual scores.

This PR attaches the `maximum_statistics` dictionary from format 2. The reason why will be explained below.

## What calculations are expected for scores?

In general, for any score that is either a pass (complete statistics) or fail (partial statistics):
- **Accuracy**: Should be displayed as it was at the point of fail or completion.
- **Tick counts**: Should be displayed as it was at the point of fail or completion as `(X hit)/(Y total)`.
- **Total score**: Should be displayed relative to the full beatmap.

## When should the maximum values be recorded?

**Accuracy** can be computed solely from the score's statistics.  
- We need all basic judgements in a ruleset to have the same maximum result. We can't have hitobjects giving both Great and Perfect as the maximum. There is currently nothing preventing this.
- Assuming the above rule is satisfied, we can use [`Ruleset.GetValidHitResults()`](https://github.com/ppy/osu/blob/bc851c174b808b6d72a56a96cc89820fe31effd1/osu.Game/Rulesets/Ruleset.cs#L340-L347) to get the maximum basic hit result.

For **ticks**, we can sum together the hit/miss counts.

**Total score** is the only variable that cannot be represented at the point of fail or completion using just the score's statistics. This is where the maximum values will come in. Therefore the **maximum values must be relative to the full beatmap**.

## Recomputing scores

What if the raw hit result values, the accuracy/combo portions, or the mod multipliers are changed?

With **format 1**, we cannot recompute `maximum_scoring_values` without running through the beatmap.
- For example, suppose a score with the `Sudden Death` mod with the only stored statistics being `{ "miss": 1 }`. How could the maximum base score be recomputed given that it is a summation of basic + ticks and the score has no ticks hit or missed?

With **format 2**, no computation is required.
- The `ScoreProcessor.ComputeScore()` method will immediately adjust to the new values.

**Format 1 is not recommended for these reasons, and this PR implements format 2.**

## What about accuracy?

Accuracy is not stored to scores. Instead, it is calculated as required by both osu!stable and osu!web.

This **does not change** with osu!lazer.

## What about combo?

**osu!lazer scores**
- Everything that affects combo is present in score statistics.

**osu!stable scores**:
- **osu!**: Slider ticks/repeats/ends are **not present** in score statistics.
- **osu!taiko**: Everything that affects combo is present in score statistics.
- **osu!catch**: Everything that affects combo is present in score statistics.
- **osu!mania**: Hold note ticks are **not present** in score statistics.

For osu! and osu!mania, one way to resolve this is by a marker hit result `LegacyComboIncrease` that is only present in the maximum statistics, gives no base score, and is unable to be used by rulesets.

## What about bonus score?

**osu!lazer scores**:
- Bonus is present in score statistics.

**osu!stable scores**:
- **osu!**: Spinners bonus is **not present** in statistics.
- **osu!taiko**: Drum rolls and spinners are **not present** in statistics.
- **osu!catch**: Bananas are **not present** in statistics.
- **osu!mania**: Does not have bonus.

In general, there is no solution to this. An attempt of replicating osu!stable scoring and figuring out the score discrepancy can be tried, but it will be an approximation at best.

### CODE REVIEW

**Review by peppy — DISMISSED** [review]

**Comment by peppy** [comment]
@frenzibyte are you going to be available to review this over the coming day or two? I want to keep pushing forward with these changes, so may merge without your review if required.

**Comment by frenzibyte** [comment]
Looking into reviewing it now.

**Comment by peppy** [comment]
@smoogipoo I think it would do well to move a lot of the information in the OP of this PR to a wiki page (on this repo) as it will help people understand how the score structures play together. Can probably copy mostly verbatim and build on it as we go.

**Comment by smoogipoo** [comment]
Sure. The OP was mostly what I was questioning myself on while going through everything, but it's written in the third person. Feel free to copy&paste into a wiki.

**Comment by peppy** [comment]
I guess it needs a bit of rephrasing to make sense, else it's referring to the way-it-was-until-now too much.

**Review by frenzibyte — APPROVED** [review]
Pretty well thought, looks good.

**Pull request merged**
