### PR TITLE
Fix selecting a slider correcting its path

### PR DESCRIPTION
**Pull request by Naxesss**
Currently, if you select a slider that has an invalid path (e.g. too large bounding box), it will be converted to Bezier. I figure this should only happen if you actually modify the path, else things like linking timestamps would potentially break things.

https://user-images.githubusercontent.com/30292137/114435303-4d6fcd00-9bc4-11eb-96da-eb7d9a98d808.mp4

Cause being the `runOnceImmediately` and `updatePathType` here:
```cs
slider.Path.Version.BindValueChanged(_ =>
{
    PointsInSegment = slider.Path.PointsInSegment(ControlPoint);
    updatePathType();
}, runOnceImmediately: true);
```

This fixes that. [Reference map](https://osu.ppy.sh/beatmapsets/756794#osu/1605148).

### CODE REVIEW

**Comment by frenzibyte** [comment]
Worth adding a test case along any fix if feasible, to make sure it doesn't regress unintentionally in the future.

**Comment by Naxesss** [comment]
I would do that, but since all existing tests start out with the slider selected (and thus the constructor having already run), I would probably need to make an entire editor test scene for this alone, which seems a bit overkill.

It is possible I'm overlooking some simple way to test this, though.

**Comment by frenzibyte** [comment]
Shouldn't be a problem I believe, you would want to assert that the path isn't actually corrected until the slider path is changed, that's the point of it.

**Comment by peppy** [comment]
There are definitely some tests where a slider doesn't start selected (was working with `QuickDeletion` tests earlier as one example) so it should be pretty simple to add test coverage for this. Definitely good to have around.

**Comment by Naxesss** [comment]
Test case basically just selects the slider and checks if it's been modified. Have confirmed it fails before this PR's changes.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
