### PR TITLE
Improve iOS importing and file system

### LINKED ISSUE #5274: iOS Universal Links
Creating issue for visibility:

Need to set up apple-app-site-association for universal links in iOS for linking beatmaps on the osu! website to osu!direct in game, etc.

### LINKED ISSUE #5485: Files app integration for iOS import/export
Related to #5272 and #5445 
**Copy to** option in share UI and **file location** in _Files_ does not show up.
**Version:** _latest release_
**OS:** _iOS 13 Public Beta 3_
**Images:**
9078F761-4920-48A4-8961-66BEED1A4FA6
AD941896-121B-47DF-A465-92633DEA6A57

### LINKED ISSUE #5500: Add iOS document configuration
> ITMS-90737: Missing Document Configuration - By declaring the CFBundleDocumentTypes key in your app, you've indicated that your app is able to open documents. Please set the UISupportsDocumentBrowser key to "YES" if your app uses a UIDocumentBrowserViewController. Otherwise, set the LSSupportsOpeningDocumentsInPlace key in the Info.plist to "YES" (recommended) or "NO" to specify whether the app can open files in place. All document-based apps must include one of these configurations. For more information, visit https://developer.apple.com/document-based-apps/.

Required in addition to https://github.com/ppy/osu/pull/5445

### LINKED ISSUE #5545: Improve iOS file system
Things to be done:

- [x] ~~In #5533 I made a mistake. Opening osu! files makes osu! crash. I'll fix it.~~ Finished.

- [ ] ~~Since it will auto backup files to iCloud, it's better to use `/Library/Document/` instead of `/Document/`.~~ Unnecessary

- [x]  ~~Then the document directory can be empty, so we can use it to import files. Like #5485 and #5272. Just use "Import from stable" is fine. And we can create a directory (like "Inbox") to accept zipped files.~~ Finished. Just drag and drop your directories from stable to iTunes and you can import them in osu!lazer

- [x] ~~Maybe just one line in `Info.plist` can solve #5274.~~ Finished. Tons of changes.

Creating for visibility. PR welcome to my fork.

### PR DESCRIPTION
**Pull request by dtsdao**
- Fixes #5545.
- [x] Depends on https://github.com/ppy/osu/pull/6685.

### Custom URL Scheme

- Added `HandleUrl` function in `OsuGame`

- Added custom URL types

- Might be easier to complete this part on other platforms?

### Fix importing issue

- Fixes #5500. Fixes #5485.

- Enable "import from stable"

- Be able to open osu! files

Be tested on iOS 12.4 Simulator and real device.

## Function preview:

https://streamable.com/bf0lw

### CODE REVIEW

**Comment by peppy** [comment]
The static class here feels back-to-front. Why is this not provided by `Game` and then executed using `DI`?

**Comment by dtsdao** [comment]
Yes that's kind of weird. It's better to move it to `Game`.

**Comment by swoolcock** [comment]
Very nice, I'll check it out myself when I can.

Note that this does NOT fix #5274 as the apple-app-site-association file handles redirecting complete URLs to applications, not just `osu://` ones.  We should be able to (optionally) redirect beatmap page links (`https://osu.ppy.sh/beatmapsets/997970#osu/2087452` etc.) to osu!direct within Lazer.

More information here:
https://developer.apple.com/documentation/uikit/inter-process_communication/allowing_apps_and_websites_to_link_to_your_content/enabling_universal_links

**Comment by dtsdao** [comment]
@swoolcock To be honest I haven't seen much application of this feature now. Maybe only App Store is using this. 
In most situations we use URI Scheme as "Jump To" function, like this PR.

**Comment by swoolcock** [comment]
Universal Links via apple-app-site-association are the preferred method of deep linking now rather than custom URL prefixes.

osu:// links will still be supported, but we *must* provide a method of deep linking using https.  It adds an extra level of security as we can prevent other apps from hijacking deep links.

**Comment by peppy** [comment]
That can be handled in a separate PR, right?

**Comment by swoolcock** [comment]
@peppy Correct.  My concern was only that this PR's description incorrectly contained an auto-close for issue #5274 (I removed it).

**Comment by peppy** [comment]
Aha, right, missed that.

**Comment by peppy** [comment]
As a heads-up I'm going to remove the "import from stable" from this PR for now. It is half-baked and not so useful. Plus, exposing the app via `UIFileSharingEnabled` currently allows a user to potentially delete files they shouldn't.

**Comment by peppy** [comment]
It will require proper migration of data, but looks like a good path forward.

**Review by ThatStella7922 — APPROVED** [review]

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
