### PR TITLE
nerfing fast non-spaced(overlapped) streams

### PR DESCRIPTION
**Pull request by GoldenMine0502**
a basecode to nerf acute high bpm stream and doubletap. 
because no one could do doubletap on spaced streams.
finally it is multiplied on speedBonus. 

but this code make some speed players discourage.
it makes hidamari no uta be taken about 150pp.
and other stream maps be taken about 0-5pp in average. 
                 
We could consider to apply this code on angleBonus.

### CODE REVIEW

**Comment by GoldenMine0502** [comment]
In average, the streams have a lot of percentage to hit with doubletap

I think the streams make a lot of normal dt maps be buffed, and hidamari also.

As we only nerf non-spaced and fast stream, we willn’t affect on normal spaced streams like sidetracked day, or etc.

Statisticsally, it makes hidamari no uta be taken about 150pp.
and other stream maps be taken about 0-5pp in average.

we also could consider use this on angleBonus to nerf acute stream buff like https://osu.ppy.sh/ss/17104627/6175

**Comment by GoldenMine0502** [comment]
I did a lot of changes on other repo
please check this statistics as only VARIANCE
(before)
  == Aether Realm - The Sun, The Moon, The Star (ItsWinter) [Mourning Those Things I've Long Left Behind].osu ==
1370pp +
2536pp +HDHR
4464pp +DTHD
  == Apol - Hidamari no Uta (-Keitaro) [Expert].osu ==
234pp +
371pp +HDHR
759pp +DTHD
  == Camellia - Exit This Earth's Atomosphere (Camellia's ''PLANETARY200STEP'' Remix) (ProfessionalBox) [Primordial Nucleosynthesis].osu ==
1514pp +
2645pp +HDHR
6069pp +DTHD
  == GYZE - HONESTY (Bibbity Bill) [DISHONEST].osu ==
616pp +
924pp +HDHR
2168pp +DTHD
  == sabi - true DJ MAG top ranker's song Zenpen (katagiri Remix) (Nathan) [KEMOMIMI EDM SQUAD].osu ==
1032pp +
1662pp +HDHR
5405pp +DTHD
  == SYU (from GALNERYUS) - REASON (BarkingMadDog) [A THOUSAND SWORDS].osu ==
747pp +
1086pp +HDHR
2895pp +DTHD
  == VINXIS - Sidetracked Day (Chanci) [Sojourn Collab].osu ==
531pp +
819pp +HDHR
2142pp +DTHD
  == VINXIS - Sidetracked Day (DendyHere) [Infinity Inside].osu ==
479pp +
714pp +HDHR
1712pp +DTHD
  == Zekk - Fluctuation (Acylica) [Last Stand].osu ==
875pp +
1410pp +HDHR
4013pp +DTHD



(after)
  == Aether Realm - The Sun, The Moon, The Star (ItsWinter) [Mourning Those Things I've Long Left Behind].osu ==
1368pp +
2534pp +HDHR
3922pp +DTHD
  == Apol - Hidamari no Uta (-Keitaro) [Expert].osu ==
234pp +
371pp +HDHR
627pp +DTHD
  == Camellia - Exit This Earth's Atomosphere (Camellia's ''PLANETARY200STEP'' Remix) (ProfessionalBox) [Primordial Nucleosynthesis].osu ==
1514pp +
2645pp +HDHR
5849pp +DTHD
  == GYZE - HONESTY (Bibbity Bill) [DISHONEST].osu ==
616pp +
924pp +HDHR
1978pp +DTHD
  == sabi - true DJ MAG top ranker's song Zenpen (katagiri Remix) (Nathan) [KEMOMIMI EDM SQUAD].osu ==
1032pp +
1662pp +HDHR
5301pp +DTHD
  == SYU (from GALNERYUS) - REASON (BarkingMadDog) [A THOUSAND SWORDS].osu ==
747pp +
1086pp +HDHR
2622pp +DTHD
  == VINXIS - Sidetracked Day (Chanci) [Sojourn Collab].osu ==
531pp +
819pp +HDHR
1876pp +DTHD
  == VINXIS - Sidetracked Day (DendyHere) [Infinity Inside].osu ==
479pp +
714pp +HDHR
1513pp +DTHD
  == Zekk - Fluctuation (Acylica) [Last Stand].osu ==
875pp +
1410pp +HDHR
3918pp +DTHD

**Comment by peppy** [comment]
!pp check osu

**Comment by GoldenMine0502** [comment]
where could i do this ;-;

**Comment by GoldenMine0502** [comment]
i think it needs to more discuss how should we handle half stacked note

**Comment by GoldenMine0502** [comment]
i updated my scores to get better pp

the statistics for four players related this patch:
https://docs.google.com/document/d/1erjgkqcQOZLWrov-Td-z0WerszFoD5RWoA3xEUKqmPE/edit?usp=sharing

as a result, it makes hidamari no uta decreases 150pp,
aetrna plays nerfed 20pp in average,
and other players no affection.



we could consider to alleviate 50 nerf. it needs discuss.

**Comment by Wieku** [comment]
This code has many issues and has some false claims.
It's reinventing the wheel (using in-place Lerp instead of using Interpolation.Lerp), Clamp function is reinvented and it's incorrect causing all 200BPM streams to be nerfed.
And Anze's Hidamari no Uta play is nerfed by 141.5pp prior to this change:
[Anze-master.txt](https://github.com/ppy/osu/files/7246434/Anze-master.txt)

**Comment by GoldenMine0502** [comment]
i understand why i alleviates my code much but nerfs a lot of

but it nerfs normal 1/6 (even jumps) patterns i think

maybe applying both things, the weaker would be better

**Comment by GoldenMine0502** [comment]
i remarked below code:
`
            // Aim to nerf cheesy rhythms (Very fast consecutive doubles with large deltatimes between)
            //if (osuPrevious != null && strainTime < greatWindowFull && osuPrevious.StrainTime > strainTime)
            //    strainTime = Interpolation.Lerp(osuPrevious.StrainTime, strainTime, speedWindowRatio);

            // Cap deltatime to the OD 300 hitwindow.
            // 0.93 is derived from making sure 260bpm OD8 streams aren't nerfed harshly, whilst 0.92 limits the effect of the cap.
            //strainTime /= Math.Clamp((strainTime / greatWindowFull) / 0.93, 0.92, 1);
`

and tested with 
`        
    private const double min_doubletap_nerf = 0.75; // minimum speedBonus value (eventually on stacked)
    private const double max_doubletap_nerf = 1.0; // maximum speedBonus value 
    private const double threshold_fully_contributing = 1.0; // minimum distance not influenced
`

i got this result, maybe same with yours as a result
[anze_aetrna_records.txt](https://github.com/ppy/osu/files/7246621/anze_aetrna_records.txt)

**Comment by Wieku** [comment]
But this code nerfs all >200BPM streams, not only non-spaced ones. This PR is a wrong way to approach such problem anyways. The problem with Hidamari no Uta is not that stream at the end, but the fact the rest of the map is too easy compared to it.

**Comment by GoldenMine0502** [comment]
okay, i have slight anxiety on 400bpm+ jump maps, but the solution looks not bad

originally the code is for nerfing acute stream spam

**Comment by GoldenMine0502** [comment]
i found fatal error on my code and i fixed.

it nerfs anze's hidamari no uta 90pp now (without all >200bpm stream nerf)
and totally it nerfs 200pp+.

in addition, i nerfed the pattern acute stream spam like https://osu.ppy.sh/ss/17106883/b4ed
but this is slight variance.

(if you are depressed, find my stupid code error lol)

**Comment by GoldenMine0502** [comment]
i posted statistics without lerp

[anze_aetrna_records.txt](https://github.com/ppy/osu/files/7247099/anze_aetrna_records.txt)

**Comment by GoldenMine0502** [comment]
reason why i'm nervious about the lerp code

for example, https://osu.ppy.sh/beatmaps/1954859?mode=osu
this map is 330bpm jump (165bpm) but it is nerfed cuz of it
live 409pp -> 365pp

**Review by stanriders — CHANGES_REQUESTED** [review]
Unfortunately this proposal is flawed from the start - you're trying to combat doubletapping by nerfing **every** stacked stream, without considering if it was doubletapped or not in any way. This issue is not something that can be dealt within difficulty calculation - if a stream is doubletappable that doesn't mean it's easier to play and therefore should be nerfed. There are already measures in performance calculation against doubletapping, as well as at least one pending (#15035) so I don't think we even need something extra in that field.
There are a couple of code issues as well, but they don't really matter if conceptually this should not be merged in the first place. I don't think I should close this PR though, that's up to @smoogipoo

**Comment by GoldenMine0502** [comment]
In the case of nerfing doubletap, this is not ideal solution and no one could present the best solution as you know. and this is not for only doubletap, but also DT farming maps.
This code doesn't nerf all streams because it just nerfs only speedbonus.

Do you really think past progression is always correct? If then, why we change the algorithm?
why we are struggling stemina on speed value?
speed value is only for physical value. not?

in ONLY the writed code, i acknowledge it needs to modify something. but this code have probablity for nerfing acute stream patterns, or etc. for example, at #15323, i use similar code on NoteVariance.

in newest speed, i can't find any anglebonus so i couldn't apply it.

as a result,  i use similar code on other parts, so up to smoogipoo.

**Comment by stanriders** [comment]
"dt farming maps" is a very broad term. What maps are you talking about? Do they even need to be nerfed? Will they be nerfed by your solution? How much should they be nerfed and why? Are they the only maps that gonna be affected by this nerf? There are a lot of questions regarding reasoning of this PR

**Comment by GoldenMine0502** [comment]
okay agreed.

i checked whether this nerfs some alternative maps but it works
when all reviews are completed, i will change all of them.

i will close it.

**Pull request closed without merging**
