### PR TITLE
Add more MIME types to Android share intent filter

### PR DESCRIPTION
**Pull request by Susko3**
Discussed in #11558 

But I don't think the issue is fully addressed. With this PR, osu! can receive shared files from Chrome on Android, but still can't open them with a view intent filter.

### CODE REVIEW

**Comment by bdach** [comment]
Your method of pulling changes from upstream to your fork is incorrect. Please see [this GitHub article](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/syncing-a-fork) for instructions on how this is properly done.

**Review by bdach — APPROVED** [review]
I have not tested these changes in detail, but I suppose I see no harm in including these.

Not merging because I'm not sure what to do with the garbage first commit. I guess this could be squashed if need be.

**Comment by peppy** [comment]
We may want to hold off on taking this action until https://github.com/ppy/osu-web/issues/7202 is finalised, as that may resolve the issue itself, potentially?

**Comment by Susko3** [comment]
I think we *can* implement this PR before we finalize https://github.com/ppy/osu-web/issues/7202

Once the new MIME types are implemented on the server, we would then add those to the share *and* view intent filters in a new PR.

When we add the new MIME types, we would still keep the ones proposed in this PR. We could remove `application/download`, but I think that's unnecessary. We should keep it in case a user comes across a file that was downloaded before the MIME type on the server was changed.

**Comment by bdach** [comment]
The way I see it, having proper types specific to osu! is miles better than this stop-gap overly generic solution.

To me, it's mostly just a question of opinion at this point whether it's worth merging this before the web-side issue is resolved. I have no strong opinion on this matter, nor do I consider it important enough to form one. I've approved mostly because I don't see a huge reason not to go ahead with the change.

**Comment by peppy** [comment]
Okay let's just get this in in the mean time, and update once the mime types are finalised.

**Pull request merged**
