### PR TITLE
Fix song select matching label not using right terminology

### PR DESCRIPTION
**Pull request by Joehuu**
The beatmap terminology has been confusing as we've been mixing up the terms internally, see this table:

| Internal (in code) | Wiki term (user shown) |
| --- | --- |
| Beatmap | [Difficulty](https://osu.ppy.sh/wiki/en/Beatmap/Difficulty) |
| Beatmap set | [Beatmap](https://osu.ppy.sh/wiki/en/Beatmap) |

Before:
osu!_QMEZshT8M0

After:
osu!_BZEIotadPV

~Not sure if it should be the other way around (i.e. `1,117 matching difficulties (217 beatmaps)`). I prefer the smaller number first though.~

### CODE REVIEW

**Comment by peppy** [comment]
I considered this when making the change but don't want two numbers. And just saying "x difficulties matching" looks weird/wrong.

**Comment by Joehuu** [comment]
The only solution is to be more verbose with "x matching beatmap difficulties".

**Comment by peppy** [comment]
Still prefer what I had 🤷

**Comment by Joehuu** [comment]
Not sure how to proceed in fixing the main issue I was trying to fix (two different numbers, same labels):
osu!_TrGdEyWOaD
osu!_ZQ0kCZ5F4y

**Comment by peppy** [comment]
Making the first one count difficulties (not sets) is probably best.

**Comment by Joehuu** [comment]
> Making the first one count difficulties (not sets) is probably best.

My question then is should the labels change to "beatmap difficulties"? If not, the wiki is wrong with the terminology and should be changed.

**Comment by peppy** [comment]
Another option would be to just use "matches" and remove the "beatmap" part completely. Shall we go with that to avoid any confusion?

**Comment by Joehuu** [comment]
Making the label ambiguous works, have applied.

**Review by peppy — APPROVED** [review]
🤷

**Pull request merged**
