### PR TITLE
Fix crashes when attempting to change from a custom ruleset with mods selected to another

### LINKED ISSUE #30163: Attempting to change from a custom ruleset with mods selected to another results in a crash
### Type

Crash to desktop

### Bug description

I came across this crash while ensuring that my ruleset (tau) works as intended with the latest osu release. To cause the crash, switch the ruleest to tau, enable the Lite mod within the conversion section, then switch to mania.

Initial thoughts are that `TauModLite` uses the `LT` acronym, and thus osu tries to enable the mod due to mania having a similar acronym, however upon looking into mania's mod set, it doesn't appear to have any mods with `LT` as an acronym.

Offending line is as follows:

https://github.com/taulazer/tau/blob/abe5104bade1bd34392e197c475ba8c072a34137/osu.Game.Rulesets.Tau/Mods/TauModLite.cs#L42

Definitely needs some more investigation, however unsure if this is an issue on my end.

### Screenshots or videos

_No response_

### Version

2024.1009.0

### Logs

[1728466199.runtime.log](https://github.com/user-attachments/files/17305918/1728466199.runtime.log)

### PR DESCRIPTION
**Pull request by bdach**
RFC. Closes https://github.com/ppy/osu/issues/30163.

If I'm to be blunt, the decoupled stuff in song select makes my head spin. I spent a solid 20 minutes thinking how I was going to fix this one but then finally realised that generally most of the cause there was the fact that `AdvancedStats` was seeing the new rulesets *before* the "ensure global selected mods are valid for current ruleset" logic, and so decided to just _delay_ that until the decoupled transfer thingamajig happens.

I was honestly considering combining `BeatmapInfo`, `Ruleset`, and `Mods` into one property on `AdvancedStats`. I figured I'd rather not push my luck and try the baseline version first, but I honestly think that direction is going to be required at some point to properly corral all of the decoupled madness taking place in song select.

The nice thing is that due to this, one previous hack is now removable after `AdvancedStats` has been weaned off the global mods bindable. I think this is a win all things considered? But I'm unsure of how ugly this in general is compared to the current state...

### CODE REVIEW

**Comment by peppy** [comment]
> If I'm to be blunt, the decoupled stuff in song select makes my head spin.

Have brought this up (likely IRL) that it needs to not exist, and be handled more local to the places that debounce needs to apply.

**Comment by LumpBloom7** [comment]
I did a quick test on this branch, and the crash still occurs for the same reason. (mods not being valid for the updated ruleset) 

Swapping [these two lines](https://github.com/ppy/osu/pull/30195/files#diff-c8d1101dcb514b9463df0207fb5894f566114bcef48c6cf0780a9c04b2bbcb6fR876-R877) around seems to avoid the crash by ensuring that mods are in a sane state beforehand. The ruleset will still be wrong when updating the statistics after mod changes, but it should correct itself when the method is run again when the ruleset changes.

**Comment by bdach** [comment]
> I did a quick test on this branch, and the crash still occurs for the same reason.

I... have no idea how that happened. I swear on anything holy that I did test, with that line *somewhere* in there, then went to commit, noticed it missing, and added it back where I thought it should have gone. And probably tested after? But clearly not.

Anyway, the fact that swapping these lines "fixes" this truly speaks to the quality of this fix. I'll let the review process judge this. I have nothing better to offer, other than maybe this:

> I was honestly considering combining `BeatmapInfo`, `Ruleset`, and `Mods` into one property on `AdvancedStats`

**Review by peppy — APPROVED** [review]
Seems to work? Code looks better than before the change?

**Pull request merged**
