### PR TITLE
Game extensions

### PR DESCRIPTION
**Pull request by luaneko**
Add support for game extensions.

Here is a [use case](https://github.com/phosphene47/osu-extensions).

### CODE REVIEW

**Comment by peppy** [comment]
This isn't really a direction we are planning on going> osu! is extensible via mods and rulesets for the time being. Please PR changes in other areas directly rather than trying to make a generic "load-anything" extension loader.

More details on what you're trying to do here would be great if the above doesn't seem feasible.

**Comment by phosphene47** [comment]
I imagined the "extensions" system to work similar to the [osu!Sync](https://github.com/OsuSync/Sync) program, which adds additional features to the game that *do not affect the gameplay directly*. One popular plugin is [RealTimePPDisplayer](https://github.com/OsuSync/RealTimePPDisplayer), which displays performance points rewarded by a score in the play screen.
I intend to implement this feature using this "extensions" system, as I thought such *additional* features do not belong to the game natively.

**Comment by swoolcock** [comment]
Note that any kind of dynamic assembly loading will not work on iOS.

**Comment by peppy** [comment]
we’d love to see this as a native feature. it has been discussed before. any reason you wouldn’t see it fitting as such?

**Comment by peppy** [comment]
As previously discussed with evast, i’m not against asdding such games in as easter eggs. “Alternative main menus” would be done via skinning or not at all.

**Pull request closed without merging**
