### PR TITLE
Fix banana showers not clearing the plate when missing the last banana

### LINKED ISSUE #13326: Banana showers will only clear the plate if the last banana is caught
**Describe the bug:** Banana showers will not clear the osu!catch plate despite ending / starting a new combo, unless the Autoplay mod is used. The attached video shows the same beatmap three times; 
1) In Stable (plate will clear)
2) In Lazer (plate will not clear)
3) In Lazer with Autoplay (plate will clear)

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/47401343/120709285-f0eea700-c4bc-11eb-8871-cde7150d05c7.mp4

beatmap in video:
[beatmap.zip](https://github.com/ppy/osu/files/6594245/beatmap.zip)

**osu!lazer version:** 2021.602.0

**Logs:** n/a

### PR DESCRIPTION
**Pull request by Darius-Wattimena**
Fixes #13326

I figured we should only explode the plate of the catcher or update the combo display if we have a `PalpableCatchHitObject`.
Because of this, checking the type is much better than calling the `IsScorable` method (which created issues). We could alternatively check if the `result.Judgement` is an `IgnoreJudgement`, although now the check is the same as how `Catcher.OnNewResult` does it.

### CODE REVIEW

**Comment by peppy** [comment]
This looks about correct, but we may want some test coverage? It shouldn't be a huge reach to add a new test case to https://github.com/ppy/osu/blob/6944151486e677bfd11f2390163aca9161defbbf/osu.Game.Rulesets.Catch.Tests/TestSceneCatcher.cs#L192-L191.

**Comment by ekrctb** [comment]
> This looks about correct, but we may want some test coverage? It shouldn't be a huge reach to add a new test case to https://github.com/ppy/osu/blob/6944151486e677bfd11f2390163aca9161defbbf/osu.Game.Rulesets.Catch.Tests/TestSceneCatcher.cs#L192-L191.

Because this test scene doesn't create a `CatcherArea` but only create a `Catcher`, this plate clearing logic cannot be tested.

<https://github.com/ppy/osu/blob/6944151486e677bfd11f2390163aca9161defbbf/osu.Game.Rulesets.Catch.Tests/TestSceneCatcherArea.cs>

is the test scene for `CatcherArea`.
(I'm not sure whether this plate clearing logic should belong to `Catcher` or `CatcherArea`. Out of scope of this PR though)

**Comment by Darius-Wattimena** [comment]
> (I'm not sure whether this plate clearing logic should belong to `Catcher` or `CatcherArea`. Out of scope of this PR though)

Don't think this is out of the scope of the PR and I agree that there should be some kind of test covering this logic to make sure it runs as intended. I never really made any integration tests in C# but I'll give it a shot tonight.

It probably belongs in both as `Catcher` should handle the unit tests covering the `Explode` and `Drop` methods and in `CatcherArea` the tests should handle the `OnNewResult` method covering all lines of the logic.

**Comment by peppy** [comment]
I think you may have misunderstood - @ekrctb is proposing moving actual non-test logic (which is definitely out of scope of this change).

If you need any help with the test let us know, I'm happy to jump in and create one if required.

**Comment by Darius-Wattimena** [comment]
> I think you may have misunderstood - @ekrctb is proposing moving actual non-test logic (which is definitely out of scope of this change).

Yes, I figured, my bad.

After thinking about it a bit more today I think moving it to the `Catcher` class makes sense as:
- We are otherwise doing the same check on both the `CatcherArea` and `Catcher`
- Calling `Catcher#Explode` and `Catcher#Drop` is now done directly from the actual class instead of doing it via the variable

Even when this is a bit out of scope, not changing this would not feel right.

**Review by bdach — APPROVED** [review]
Seems like a reasonable solution. Going to wait for confirmation from someone else first just to make sure, though.

**Review by smoogipoo — APPROVED** [review]
lgtm

**Pull request merged**
