### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by peppy**
Mainly for a `Clowd.Squirrel` bump to fix https://github.com/ppy/osu/discussions/17190.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Need to update the Android project (at least? maybe iOS too) - build failing.

**Comment by peppy** [comment]
Yeah forgot about the framework requirements..

**Comment by smoogipoo** [comment]
Still need to update Realm + Diffplex in the iOS project. Hopefully this can all go away once we start using the `net6.0-ios` target...

**Comment by bdach** [comment]
There were a few more missing still (moq in mobile test projects, realm in android props file). I believe there should be no more though, and I am saying that after doing a bit of grepping...

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
