### PR TITLE
Add basic custom data directory support

### PR DESCRIPTION
**Pull request by peppy**
A first step towards adding user configurable data directory location. Migration support / UI will come as a future PR.

To make use of this as-is, move your data to a new location and create a new file `storage.ini` with:

`FullPath = /new/location`

- Closes (kinda?) https://github.com/ppy/osu/issues/960
- [x] Depends on https://github.com/ppy/osu-framework/pull/3522

### CODE REVIEW

**Comment by peppy** [comment]
Hold off on this one for now. `CustomStorage : NativeStorage` may not work well with other host storage implementations and there's no obvious solution to this, so may need some rethinking.

**Comment by bdach** [comment]
This change breaks custom ruleset loading. Logs show a doubly-appended `rulesets` directory prefix:

```
2020-05-09 17:33:52 [error]: Failed to load ruleset osu.Game.Rulesets.Tau
2020-05-09 17:33:52 [error]: System.IO.FileNotFoundException: Could not load file or assembly 'C:\Users\dachb\AppData\Roaming\osu\rulesets\rulesets\osu.Game.Rulesets.Tau.dll'. The system cannot find the path specified.
2020-05-09 17:33:52 [error]: File name: 'C:\Users\dachb\AppData\Roaming\osu\rulesets\rulesets\osu.Game.Rulesets.Tau.dll'
```

The reason is located here:

https://github.com/ppy/osu/blob/2d492102509ae8e1f07970c7f705495379455fc7/osu.Game/Rulesets/RulesetStore.cs#L146-L149

`rulesetStorage.GetFiles()` returns paths relative to the *root* storage, while `rulesetStorage.GetFullPath()` assumes the path is relative to the *sub*storage, therefore appending the `rulesets/` folder a second time.

**Review by bdach — CHANGES_REQUESTED** [review]
As above.

**Comment by peppy** [comment]
Nice catch. Should be fixed with more path manipulation. Hopefully we don't nest these directory requests too much, since each layer will add quite a few extra string operations (though this seems to be a relative rare call).

**Review by bdach — APPROVED** [review]
Yep, looks good here now. Tested it a little bit and seems to be working fine. 👍

**Review by smoogipoo — APPROVED** [review]
Looks fine to me for now. Only (minor) issue is `OpenInNativeExplorer()` not really working for subpaths since it just forwards to the underlying storage.
Where this comes up in in the editor - `Export Package` will redirect to `/osu/` rather than `/osu/exports/`.

But I imagine fixing this will require an o!f change that exposes `OpenInNativeExplorer(string path)`.

**Pull request merged**
