### PR TITLE
Apply an audio distortion matching confirmation progress on dangerous buttons

### PR DESCRIPTION
**Pull request by CenTdemeern1**
# What the fizzle is this?
This PR applies an audio distortion effect (specifically, it slides down the frequency) to the music while confirming a dangerous action.
The further the progress is, the more the audio distorts.

I showed this to Flyte, and he thought it was interesting.

# Videos:
### Latest version:
Uploaded on alt because I got copyright claimed (which is understandable), the video will sadly ***run ads against my will*** because of said copyright claim.
Note that at 0:41 I start *canceling the popups with the escape key.* Don't get confused.
https://youtu.be/p8gouF7cqSA

### Original video I showed to Flyte and others:
https://youtu.be/1zUQw23Cdko

### CODE REVIEW

**Comment by CenTdemeern1** [comment]
Okay, let's discuss it then. (And I'll discuss stuff like this in the osu!dev server as well from now on, I was just scared to do so initially because I'm just scared it'll get flagged as "discussed in the wrong place" again.)
Contrary to what you seem to have said, I have in fact shared this with multiple people and in public places.
I have gotten generally positive feedback, with one person *actually giving constructive feedback*.

**Comment by frenzibyte** [comment]
In general, the only public place you should share UX changes in would be in either a discussion thread (most recommended, for easiest visibility), or osu!dev discord. There's no point in sharing it anywhere else.

**Comment by CenTdemeern1** [comment]
Should I make a discussion thread now?

**Comment by frenzibyte** [comment]
Not worth it since you've already opened a PR for it, so discussion will go here.

**Comment by Sublimelime** [comment]
I like this, though I feel that it's hard to notice if you don't partially hold the button, due to how short the hold time is. If you hold all the way through, you get merely a small "whoop" effect before the delete goes through. May be a good idea to increase the length of time needed to hold to delete after this, OR make this distortion happen upon _hovering_ the button.

As the former might get annoying, I vote for trying on-hover.

**Comment by CenTdemeern1** [comment]
Currently the effect is linked to the bar progress, so if it's going to happen on hover it'll need some changes.
I'm fine with making those changes though

**Comment by nekodex** [comment]
As a disclaimer, I kind of already have a rough something in mind for how I want the hold buttons to sound (a pitch-rising ticking/clicking or something similar), and this change would likely clash with it.

If I ignore that, my gut reaction is that this change feels kinda odd. In my mind there's a disconnect between "hold to execute" and the "distortion" (aka pitching down the music) - it might make sense when deleting the currently selected beatmap, but that's not always what the button is used for (e.g. deleting scores/skins). The low-pass effect on popups works because the dialog is forcing your attention to it (i.e. blurring out the background both visually and sonically). This change, in comparison, feels arbitrary.

Also, as others have brought up, it ends up being somewhat inaudible when the button is just being held... combine that with the necessary sample(s) to work in places where music isn't playing, and yeah, chances are the sample(s) will likely drown out this effect anyway. 🤷‍♂️

**Comment by peppy** [comment]
I could also see a track volume fade-to-zero working quite well depending on how the samples are implemented for the control.

As this is only a few line change, let's close this for now and wait for what @nekodex comes up with, take it from there.

**Pull request closed without merging**
