### PR TITLE
Fix keybind clear button always clearing first keybind regardless of target

### PR DESCRIPTION
**Pull request by Joehuu**
Before:
fHD4nyQ6JP

After:
UqVJsVQqXD

### CODE REVIEW

**Comment by peppy** [comment]
- This needs test coverage.
- I'm not sure how this fix works (or if it's the correct approach). Would be very helpful to add xmldoc to the `updateBindTarget` and the reasoning for the conditional added as a local comment.

**Review by peppy — CHANGES_REQUESTED** [review]
as proposed

**Comment by bdach** [comment]
What's the status of this PR?

**Comment by Joehuu** [comment]
Was thinking if I should write the code here as I'm not sure of the changes, but I pushed commits.

Test is probably wrong because I had to expose `KeyBindingRow`'s `FillFlowContainer<KeyButton> buttons` which in turn had to expose `KeyBindingRow.KeyButton` to public. Not sure how else to check if the keybinding is cleared. And the test scene right now is using the game's keybindings instead of a dummy, but that's another issue.

**Comment by smoogipoo** [comment]
I've re-privatised the buttons. Seems ok.

**Review by smoogipoo — APPROVED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
