### PR TITLE
Fix beatmap difficulties no longer being refreshed correctly when filter status changes

### LINKED ISSUE #16752: Beatmap carousel panels do not show correctly after changing ruleset
See following video:

https://user-images.githubusercontent.com/20418176/152240679-c92d4afa-d3c7-40dd-8900-f5607aedafd2.mp4

Regressed in #16716.

### PR DESCRIPTION
**Pull request by peppy**
This regressed with https://github.com/ppy/osu/pull/16716/files#diff-5c1acf993805bef85672afa52a88567a5b009fb98b346db743d8ebc2a501a4f7R124 as `DrawableCarouselBeatmapSet` was relying on `Select` being called more than once.

This felt very incorrect, so I've created a new flow specifically to handle the filter changes which should trigger beatmap panel recreation.

The new test coverage focuses on the `Drawable` panels unlike all existing ones, so should give us a bit of new overall coverage as a result.

Closes https://github.com/ppy/osu/issues/16752.

### CODE REVIEW

**Comment by bdach** [comment]
This change looks relatively straightforward and fixes the ruleset switch case I found, *but*... unfortunately, I found another one, one related to unload logic this time:

https://user-images.githubusercontent.com/20418176/152419700-f618f881-dac8-4a3f-9631-2681244f005c.mp4

Unsure whether that is to be fixed here or as a separate issue.

**Comment by peppy** [comment]
Nice catch. Will fix here.

**Comment by peppy** [comment]
I can't seem to reproduce what you're seeing in tests or gameplay..

**Comment by peppy** [comment]
I've pushed a fix for this (the cause is quite obvious from reading through the code) but not too sure how to repro this for test coverage. Probably fine without it?

**Comment by smoogipoo** [comment]
Latest changes don't seem to have fully fixed disappearing beatmaps. I think a stable way to reproduce this is the following:
1. Import https://osu.ppy.sh/beatmapsets/552702#osu/1216282
2. Filter song select to "ambiguity" (should be one diff displayed).
3. Empty filter.
4. Scroll until the set panel is off screen.

https://user-images.githubusercontent.com/1329837/152551386-a7b18bca-b060-4e24-81db-fcdb3af6a3a8.mp4

**Comment by smoogipoo** [comment]
Also the above repro can be used to repro @bdach 's original issue.

**Comment by peppy** [comment]
Hmm, can you repro on the last release?

**Comment by smoogipoo** [comment]
Can't repro any brokenness on the last release.

**Comment by bdach** [comment]
Somehow [f5cedf3](https://github.com/ppy/osu/pull/16763/commits/f5cedf3e875d325602e6ab72bb1cb6426d512765) fixed @smoogipoo's case but then also broke normal scrolling/selection in the same exact way...

https://user-images.githubusercontent.com/20418176/152599169-f8d966c0-2782-4276-95d2-d162afb57014.mp4

**Comment by peppy** [comment]
I guess you didn't try adding the height adjust in both paths? It should as you'd expect fix it.

Will revert to how it was running previous to the already merged regression and go with it m.

**Comment by smoogipoo** [comment]
I don't know how to repro this, but I have another similar issue which is that sets sometimes don't get their alpha updated. Here's a full length video (because I don't know how to repro this yet) where I do a bunch of random things.

https://user-images.githubusercontent.com/1329837/152631223-fe235e15-0b33-41ac-9a75-1faa2b42633b.mp4

You can see the effects of what I'm seeing from 2:00 onwards.

**Comment by peppy** [comment]
Closing for now, will reassess after release (see #16782).

**Pull request closed without merging**
