### PR TITLE
Implement the necessary interfaces to allow replay rewinding

### PR DESCRIPTION
**Pull request by smoogipoo**
Prereqs:
- [x] https://github.com/ppy/osu-framework/pull/1132
- [x] https://github.com/ppy/osu-framework/pull/1136
- [x] https://github.com/ppy/osu-framework/pull/1142

This is only working for osu! right now, and even then it's not completely perfect yet. I am tracking a list of bugs related to replay rewinding in https://github.com/ppy/osu/milestone/25

This does not completely work with mania/taiko/catch yet (~and in-fact will currently crash in taiko~ crashing is hackily avoided for now), but it's not like it worked in the first place, and I want to keep this small with further fixes coming up tomorrow(?).

But it's a start.

### CODE REVIEW

**Comment by peppy** [comment]
As discussed rather than switching from transform helpers just to make rewinding working, a framework change is going to allow state-seeking on `Transformable`s to avoid the need of "initial state" setter methods in many cases.

Marking as blocked pending that framework change.

**Comment by smoogipoo** [comment]
Looks cleaner with the removal of `UpdateInitialState` :)

**Comment by smoogipoo** [comment]
https://github.com/ppy/osu/pull/1453/commits/5277c3c1647c86b33c04ee98ea35d1c54fe52aca I'm pretty sure this is what we want in any case. Doesn't fix the issue, but I believe the underlying issue is somewhere in replay handler as it doesn't handle fast forward perfectly either.

**Comment by peppy** [comment]
Not sure `-1` is a good value to use (in the case of two frames closer than that in the replay this could cause issues).

**Comment by peppy** [comment]
Anyways let's get this in as "better-than-before" behaviour and work on further fixes individually.

**Review by peppy — APPROVED** [review]

**Pull request merged**
