### PR TITLE
Fix collections being imported from BDL thread

### PR DESCRIPTION
**Pull request by smoogipoo**
Supersedes / closes https://github.com/ppy/osu/pull/11817

The loading and mapping (`readCollections`) still happens in the async context. `importCollections` only adds to the global bindable, and should happen on the update thread rather than the BDL thread.

100% repro with https://github.com/ppy/osu/pull/11818:
```
[runtime] 2021-02-18 07:11:22 [error]: osu.Framework.Graphics.Drawable+InvalidThreadForMutationException: Cannot mutate the InternalChildren of a Ready Drawable while not on the load or update threads. Consider using Schedule to schedule the mutation operation.
[runtime] 2021-02-18 07:11:22 [error]: at osu.Framework.Graphics.Drawable.EnsureMutationAllowed(String member)
[runtime] 2021-02-18 07:11:22 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.ClearInternal(Boolean disposeChildren)
[runtime] 2021-02-18 07:11:22 [error]: at osu.Framework.Graphics.Containers.FlowContainer`1.ClearInternal(Boolean disposeChildren)
[runtime] 2021-02-18 07:11:22 [error]: at osu.Framework.Graphics.Containers.Container`1.Clear(Boolean disposeChildren)
[runtime] 2021-02-18 07:11:22 [error]: at osu.Framework.Graphics.UserInterface.Dropdown`1.setItems(IEnumerable`1 items)
[runtime] 2021-02-18 07:11:22 [error]: at osu.Framework.Graphics.UserInterface.Dropdown`1.<.ctor>b__29_1(Object _, NotifyCollectionChangedEventArgs __)
[runtime] 2021-02-18 07:11:22 [error]: at osu.Framework.Bindables.BindableList`1.clear(BindableList`1 caller)
[runtime] 2021-02-18 07:11:22 [error]: at osu.Framework.Bindables.BindableList`1.clear(BindableList`1 caller)
[runtime] 2021-02-18 07:11:22 [error]: at osu.Framework.Bindables.BindableList`1.Clear()
[runtime] 2021-02-18 07:11:22 [error]: at osu.Game.Collections.CollectionFilterDropdown.collectionsChanged() in /home/smgi/Repos/osu/osu.Game/Collections/CollectionFilterDropdown.cs:line 68
[runtime] 2021-02-18 07:11:22 [error]: at osu.Game.Collections.CollectionFilterDropdown.<load>b__10_0(Object _, NotifyCollectionChangedEventArgs __) in /home/smgi/Repos/osu/osu.Game/Collections/CollectionFilterDropdown.cs:line 50
[runtime] 2021-02-18 07:11:22 [error]: at osu.Framework.Bindables.BindableList`1.add(T item, BindableList`1 caller)
[runtime] 2021-02-18 07:11:22 [error]: at osu.Framework.Bindables.BindableList`1.add(T item, BindableList`1 caller)
[runtime] 2021-02-18 07:11:22 [error]: at osu.Framework.Bindables.BindableList`1.Add(T item)
[runtime] 2021-02-18 07:11:22 [error]: at osu.Game.Collections.CollectionManager.importCollections(List`1 newCollections) in /home/smgi/Repos/osu/osu.Game/Collections/CollectionManager.cs:line 163
[runtime] 2021-02-18 07:11:22 [error]: at osu.Game.Collections.CollectionManager.load() in /home/smgi/Repos/osu/osu.Game/Collections/CollectionManager.cs:line 64
```

### CODE REVIEW

**Comment by peppy** [comment]
Are you 100% sure we don't want the call in `load()` to be blocking until it completes?

**Comment by smoogipoo** [comment]
It's just handing off the mutation of the global bindable to the update thread. The parsing of the database file and querying of BeatmapManager is still done synchronously in `readCollection`.

**Comment by smoogipoo** [comment]
So the issue here is that `SongSelect` loads the `CollectionFilterDropdown`, which binds to the collection changed in its BDL. 

Another possible fix, which I'll also apply here, is moving the bind to `LoadComplete()`.

But that wouldn't fix all scenarios. For example, suppose reading collections took so long that the user was able to fully enter song select. If the BDL of CollectionManager then modified the game-wide bindable while still on the BDL thread, then it's going to cause a similar exception (except https://github.com/ppy/osu-framework/blob/72eef659d4374052e04021361ba1549bafa7c442/osu.Framework/Graphics/Drawable.cs#L2570-L2571).

So I think we definitely want this to run on the update thread.

**Comment by smoogipoo** [comment]
I've forced pushed this one backwards to cover _just_ the CollectionManager side of things. The commit I had fully overlaps with https://github.com/ppy/osu/pull/11817 .

**Review by peppy — APPROVED** [review]

**Pull request merged**
