### PR TITLE
Prevent parallax effect when the game window isn't focused

### PR DESCRIPTION
**Pull request by ghost**
Should fix issue #429.

### CODE REVIEW

**Comment by peppy** [comment]
Not sure this is the right solution. I think parallax should still work when not in focus. We just need to stop input from being passed through to the game when minimised.

**Comment by thatsabop** [comment]
As far as I'm concerned, would something like [this](https://github.com/ppy/osu-framework/pull/239/commits/6888bf17995a32affbedffe070a4b21406f058f6) be the way to go?

**Comment by peppy** [comment]
it needs to be specific to minimised, not just `!IsActive`.

also rather than setting a default state, just don't update the state.

**Comment by peppy** [comment]
Fixed via https://github.com/ppy/osu-framework/pull/625.

**Pull request closed without merging**
