### PR TITLE
Remove low BPM barline increase in taiko

### PR DESCRIPTION
**Pull request by nl-tata**
Remove code that I am almost 100% sure that makes barlines every 1/1 instead of 4/1 at or below 75bpm. 

Currently it is unrankable to have a map at or below 75 bpm. Having the BPM of a map subject to rules is utterly silly. There are examples of this rule being enforced, such as https://osu.ppy.sh/forum/p/6255493#p6255493 and in this mapset https://osu.ppy.sh/s/673311 . This isn't a ranking criteria issue though, this is a game engine issue. If it is unrankable to have unpleasing barlines that the game itself creates, the solution isn't to force the mapper to deal with it. Its to fix the game. Thats what I suggest to do. There should be barlines every 4/1 no matter the BPM. It shouldn't be on the mapper to correct barline issues, it should be on the game.

---

Currently in osu!taiko, if the bpm of a map is at or below 75bpm bar lines are drawn every 1/1 instead of every 4/1 which is the norm for maps above 75 bpm. This is problematic, as it goes against the taiko ranking criteria. It "[hinders] gameplay experience aesthetically by adding unnecessary bar lines.".

This change removes these extra bar lines.

### CODE REVIEW

**Comment by nl-tatatat** [comment]
wait is this osu!lazer? haha. This change was meant for stable osu!, but I guess also including it in lazer is good too. This problem is affecting osu!taiko right now. There wasn't really anything on the github indicating it was lazer.

**Comment by peppy** [comment]
Sounds fair. If we come to a consensus here that this is OK to change I will port it back to stable.

**Comment by nl-tatatat** [comment]
uhh... woops. Well I'll leave this to you guys until an agreement is came to!

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
Okay I guess this wasn't actually tested, because it's wrong

**Pull request merged**
