### PR TITLE
Add search box to chat overlay

### PR DESCRIPTION
**Pull request by Maks1mio**
I've been wanting to suggest this for a long time, and even left a message in Figma saying:

image

In general, I propose a pull request. I think it could have been done better than what I did.

https://github.com/user-attachments/assets/01accf64-65e4-4f7a-87fc-4794ca6c8014

I think it'll be a good user experience.

### CODE REVIEW

**Review by bdach — CHANGES_REQUESTED** [review]

**Comment by bdach** [comment]
@peppy code quality issues notwithstanding, any UX feedback on this? I'm not sure this should be limited to searching PM channels, I'd say the textbox should be topmost and allow searching public channels by name too?

**Comment by peppy** [comment]
> @peppy code quality issues notwithstanding, any UX feedback on this? I'm not sure this should be limited to searching PM channels, I'd say the textbox should be topmost and allow searching public channels by name too?

Yep, sounds fine with your proposed change.

**Comment by Maks1mio** [comment]
When I'm at home, I'm be ready to edit the code

**Comment by bdach** [comment]
I'm just gonna apply the changes myself to speed this up.

**Comment by Maks1mio** [comment]
ok thanks 😋

**Comment by bdach** [comment]
After:

https://github.com/user-attachments/assets/f0d8e1b2-e7d8-43da-8c71-3ab7306283f4

@ppy/team-client requesting second review as I rewrote every line.

**Review by bdach — APPROVED** [review]

**Comment by peppy** [comment]
We probably need a `PlatformAction.Search` don't we 😅

**Comment by bdach** [comment]
> We probably need a `PlatformAction.Search` don't we 😅

Probably, but if you wanna go down that way we'd probably need to re-examine a bunch of UX (mod select comes to mind first and foremost?)

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
Can happen later, just feels like i should be able to focus search here quickly

**Pull request merged**
