### PR TITLE
Port merged tooling updates from framework

### PR DESCRIPTION
**Pull request by huoyaoyuan**
Simple port of ppy/osu-framework#2896, ppy/osu-framework#2906, ppy/osu-framework#2935 and part of ppy/osu-framework#2921.

### CODE REVIEW

**Comment by huoyaoyuan** [comment]
CodeFactor claims for `build.sh`, but it doesn't triggers for framework.

**Review by bdach — COMMENTED** [review]
A bit tiring to review manually, but on a cursory glance looks correct.

**Comment by smoogipoo** [comment]
The blocker on this for us right now is having rider configs - maybe it should be copied from the osu.Desktop configs.

**Comment by huoyaoyuan** [comment]
> The blocker on this for us right now is having rider configs - maybe they should be copied from the existing configs.

Which setting is blocking? I merged the three setting files, and the merge tool changed some tabs. Or may I do a manual merge only for custom dictionary?

**Comment by smoogipoo** [comment]
It’s missing the run configs for the filtered solutions. May need me or peppy to go through it if you don’t have rider.

**Comment by huoyaoyuan** [comment]
I do have rider, but only use it for feature parity checking. Please help to add them because I'm not familiar.

**Comment by bdach** [comment]
I think if you copy the entire `.idea/.idea.osu/.idea/runConfigurations` folder over to `.idea/.idea.osu.Desktop/.idea/runConfigurations` they'll show up when opening `osu.Desktop.slnf`. It's not ideal, I'd make that a symlink, but Windows. Also possibly debatable if having run configs for the full solution is necessary any longer.

**Review by peppy — APPROVED** [review]

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
