### PR TITLE
Make reverse arrows not follow snaking when they are already hit

### LINKED ISSUE #8283: Reverse arrow follows snaking out sliders
**Describe the bug:** 
When a repeating slider snakes out, the reverse arrow follows it instead of fading out on the spot. This looks weird on skins that have the "arrow" placed outside the slider.

**Screenshots or videos showing encountered issue:** 
Noticed on this vid from my last issue: https://www.youtube.com/watch?v=n03vo6jni9Y

**osu!lazer version:** 
2020.312.0

### PR DESCRIPTION
**Pull request by LittleEndu**
Fixes #8283

### CODE REVIEW

**Comment by peppy** [comment]
At very least this should have a comment explaining why it's done. Optimally, it would also have a test testing that the repeat is still following on miss. Also, this should probably be applied to `DrawableSliderTail` too, for future-proofing.

**Comment by LittleEndu** [comment]
> Also, this should probably be applied to ``DrawableSliderTail`` too, for future-proofing.

``DrawableSliderTail`` does not implement ``ITrackSnaking``. Unsure how this would apply.

**Comment by peppy** [comment]
It will need to once it displays `sliderendcircle` (see todo in the class).

**Comment by LittleEndu** [comment]
> Optimally, it would also have a test testing that the repeat is still following on miss.

Sliders don't follow snaking in the test. Would test both ways if there is a way to force snaking.

**Comment by peppy** [comment]
You could adjust the config setting in LocalConfig, I believe (check how other tests do it).

**Comment by LittleEndu** [comment]
I was going to add a comment to ``DrawableSliderTail`` but InspectCode wasn't happy about "Redundant control flow jump statement" and I wouldn't know how to implement the rest of the function.

**Comment by peppy** [comment]
For future reference, the test should be part of the PR, not dependent on it (makes for very annoying review). I'll let it fly this one time due to this being a relatively small change.

**Review by peppy — DISMISSED** [review]

**Pull request merged**
