### PR TITLE
Fix initialize beatmap change animation of the music controller

### PR DESCRIPTION
**Pull request by marco-stephan**
Before: https://streamable.com/nvjww
Afterwards: https://streamable.com/hh6gt

### CODE REVIEW

**Comment by peppy** [comment]
Can you please add a description to the PR explaining what this achieves? The title alone doesn't make it clear so I don't know what I'm looking at visually.

**Comment by MrTheMake** [comment]
Yes, of course, sorry. The music controller transforms a visual beatmap change upon open it for the first time. As there was no beatmap before, that doesn't make sense designwise.

**Comment by MrTheMake** [comment]
Added videos of the change

**Comment by RemieRichards** [comment]
That's the same video twice.

**Comment by MrTheMake** [comment]
Whoops. Updated second video.

**Review by peppy — APPROVED** [review]

**Pull request merged**
