### PR TITLE
Correctly handle multiple online score ID types

### LINKED ISSUE #24229: Leaderboard replays are unavailable
### Type

Game behaviour

### Bug description

Get a Qualified mapset downloaded
Pick #1 spot on the leaderboard
Click on the Replay download button
Notice that it's unavailable

### Screenshots or videos

image

### Version

2023.621.0-lazer

### Logs

[network.log](https://github.com/ppy/osu/files/12061119/network.log)
[performance.log](https://github.com/ppy/osu/files/12061120/performance.log)
[runtime.log](https://github.com/ppy/osu/files/12061121/runtime.log)
[updater.log](https://github.com/ppy/osu/files/12061122/updater.log)
[database.log](https://github.com/ppy/osu/files/12061123/database.log)
[input.log](https://github.com/ppy/osu/files/12061124/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12061125/legacy-ipc.log)

```[tasklist]
### Tasks
- [x] Verify that stable score import correctly populates the `has_replay` column
- [ ] https://github.com/ppy/osu-web/pull/10495
- [ ] https://github.com/ppy/osu-web/pull/10492
- [ ] https://github.com/ppy/osu/pull/24669
- [x] osu-server-spectator deploy (for https://github.com/ppy/osu-server-spectator/pull/181 and https://github.com/ppy/osu-server-spectator/pull/186)
- [ ] https://github.com/ppy/osu-web/pull/10437
- [ ] https://github.com/ppy/osu-infrastructure/issues/24
- [ ] https://github.com/ppy/osu/pull/24794
- [ ] osu-server-spectator game package bump for the above change
```

### LINKED ISSUE #25117: The score is shown twice on the result screen
### Type

Cosmetic

### Bug description

When I click the score in a local leaderboard It's shown twice on the result screen.

### Screenshots or videos

image

### Version

2023.1008.1

### Logs

[runtime.log](https://github.com/ppy/osu/files/12896466/runtime.log)
[performance-audio.log](https://github.com/ppy/osu/files/12896467/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/12896468/performance-draw.log)
[performance-input.log](https://github.com/ppy/osu/files/12896469/performance-input.log)
[performance-update.log](https://github.com/ppy/osu/files/12896470/performance-update.log)
[database.log](https://github.com/ppy/osu/files/12896472/database.log)
[input.log](https://github.com/ppy/osu/files/12896474/input.log)
[legacy-ipc.log](https://github.com/ppy/osu/files/12896475/legacy-ipc.log)
[network.log](https://github.com/ppy/osu/files/12896476/network.log)
[performance.log](https://github.com/ppy/osu/files/12896477/performance.log)
[updater.log](https://github.com/ppy/osu/files/12896478/updater.log)

### PR DESCRIPTION
**Pull request by bdach**
- Closes https://github.com/ppy/osu/issues/24229
- Closes https://github.com/ppy/osu/issues/25117
- [x] Depends on https://github.com/ppy/osu-infrastructure/issues/24

This is going to be hard-stuck on the dependency chain for a while; I'm only PRing it to conclude the chain of changes.

This PR executes the plan outlined in https://github.com/ppy/osu/issues/24229#issuecomment-1696195628 for encoding, decoding, and storing online score IDs to realm. This will finally allow stuff like replay download to fully work correctly end-to-end (although an `osu-server-spectator` bump will be required after this change for the encoder changes to propagate to replays recorded server-side.

While I'm temporarily marking this as draft, most of this is generally tested full-stack to work, with the exception of stable replay handling via online download paths as testing that locally is a pain. Will do more testing (and undraft) once the dependency chain progresses enough for that to be viable.

### CODE REVIEW

**Comment by bdach** [comment]
Just as commentary: while the prerequisites of this pull will likely be obsoleted by https://github.com/ppy/osu-infrastructure/issues/24, the changes in this one should still be valid.

**Comment by peppy** [comment]
> Just as commentary: while the prerequisites of this pull will likely be obsoleted by [ppy/osu-infrastructure#24](https://github.com/ppy/osu-infrastructure/issues/24), the changes in this one should still be valid.

Are you able to split the relevant changes out? I think we're likely definitely going ahead with ppy/osu-infrastructure#24, so may as well clean things up here.

**Comment by bdach** [comment]
> Are you able to split the relevant changes out?

I've just force-pushed the dependent commits out for now. There was zero code overlap and zero conflicts, so the hope is that it will be enough.

That said, I have **not tested this** yet which is why I'm keeping this as draft for the time being. I don't want this PR to go in before work on https://github.com/ppy/osu-infrastructure/issues/24 is completed and verified as working correctly, as otherwise this change may do more damage than good by putting garbage data where it don't belong.

**Comment by peppy** [comment]
@bdach we might be at the point this can be revisited.

**Comment by bdach** [comment]
I've tested this some and yes, things look to be working pretty well. The only thing I was unable to test is that legacy score imports work correctly, because something seems to be off with `private-staging` as described [on](https://discord.com/channels/188630481301012481/188630616286167041/1167059520946700378) [discord](https://discord.com/channels/188630481301012481/1097318920991559880/1167059632523591711).

Taking this out of draft as such.

**Comment by bdach** [comment]
As it turns out (after private-staging was sorted), legacy score import was *not* working quite correctly just yet. The scenario involved here is something along the lines of:

1. Import score via stable-recorded replay
2. The replay should show as downloaded when looking at leaderboards even if they were fetched from API

They previously wouldn't be, I pushed some commits that should make it so. https://github.com/ppy/osu/pull/24794/commits/526ee6e14070a2ba0d09ad544353be52796e698c may be a point of contention here but I think it makes sense? I can split the model jiggling out of this on request.

**Comment by peppy** [comment]
I'm looking at the complexity around the replay flags and wondering why we can't switch to this:

```diff
diff --git a/osu.Game.Tests/Visual/Gameplay/TestSceneReplayDownloadButton.cs b/osu.Game.Tests/Visual/Gameplay/TestSceneReplayDownloadButton.cs
index 6ccf73d8ff..5b32f380b9 100644
--- a/osu.Game.Tests/Visual/Gameplay/TestSceneReplayDownloadButton.cs
+++ b/osu.Game.Tests/Visual/Gameplay/TestSceneReplayDownloadButton.cs
@@ -213,7 +213,7 @@ public void CreateButtonWithNoScore()
             OnlineID = hasOnlineId ? online_score_id : 0,
             Ruleset = new OsuRuleset().RulesetInfo,
             BeatmapInfo = beatmapManager.GetAllUsableBeatmapSets().First().Beatmaps.First(),
-            Hash = replayAvailable ? "online" : string.Empty,
+            HasOnlineReplay = replayAvailable,
             User = new APIUser
             {
                 Id = 39828,
diff --git a/osu.Game/Scoring/IScoreInfo.cs b/osu.Game/Scoring/IScoreInfo.cs
index cde48c3be3..a1d076b8c2 100644
--- a/osu.Game/Scoring/IScoreInfo.cs
+++ b/osu.Game/Scoring/IScoreInfo.cs
@@ -22,8 +22,6 @@ public interface IScoreInfo : IHasOnlineID<long>
 
         double Accuracy { get; }
 
-        bool HasReplay { get; }
-
         long LegacyOnlineID { get; }
 
         DateTimeOffset Date { get; }
diff --git a/osu.Game/Scoring/ScoreInfo.cs b/osu.Game/Scoring/ScoreInfo.cs
index 722d83cac8..d712702331 100644
--- a/osu.Game/Scoring/ScoreInfo.cs
+++ b/osu.Game/Scoring/ScoreInfo.cs
@@ -94,8 +94,6 @@ public class ScoreInfo : RealmObject, IHasGuidPrimaryKey, IHasRealmFiles, ISoftD
 
         public double Accuracy { get; set; }
 
-        public bool HasReplay => !string.IsNullOrEmpty(Hash) || HasOnlineReplay;
-
         [Ignored]
         public bool HasOnlineReplay { get; set; }
 
diff --git a/osu.Game/Screens/Ranking/ReplayDownloadButton.cs b/osu.Game/Screens/Ranking/ReplayDownloadButton.cs
index b6166e97f6..df5f9c7a8a 100644
--- a/osu.Game/Screens/Ranking/ReplayDownloadButton.cs
+++ b/osu.Game/Screens/Ranking/ReplayDownloadButton.cs
@@ -37,7 +37,7 @@ private ReplayAvailability replayAvailability
                 if (State.Value == DownloadState.LocallyAvailable)
                     return ReplayAvailability.Local;
 
-                if (Score.Value?.HasReplay == true)
+                if (Score.Value?.HasOnlineReplay == true)
                     return ReplayAvailability.Online;
 
                 return ReplayAvailability.NotAvailable;

```

**Comment by bdach** [comment]
> I'm looking at the complexity around the replay flags and wondering why we can't switch to this:

Looks like we can because `ScoreDownloadTracker` was inlining the local case anyhow:

https://github.com/ppy/osu/blob/f931f4c324f96063a3964fc660daf06d99e657d2/osu.Game/Online/ScoreDownloadTracker.cs#L52

so, applied.

**Review by peppy — DISMISSED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
