### PR TITLE
Add support for legacy skins' circle explode animation

### PR DESCRIPTION
**Pull request by peppy**
Turned out to work better as an implementation at `DrawableHitCircle` for now. Just trying to keep things simple rather than over-engineering.

@smoogipoo interested in your thoughts on this. Whether `HasImplementation` makes sense, and how we should standardise it (`IHasSkinAvailability` or a better named interface for intermediary classes that potentially have skinnable children, to pass the messaging on).

### CODE REVIEW

**Comment by smoogipoo** [comment]
It seems weird to me that it's the responsibility of the parenting object to determine how a child should behave in the cases that it does/doesn't have a skin implementation. I'd prefer if it were handled at every individual location instead.

**Comment by peppy** [comment]
Yeah, but while all these individual elements are grouped together with one behaviour I feel like this is okay? Obviously it's not the final iimplementation of this stuff (we still have insane performance issues due to the bindable/event flow) but as a stop-gap I think it is actually cleaner and easier to parse than moving this to a per-drawable implementation.

**Comment by smoogipoo** [comment]
Optimisation is a whole different thing. As long as the design of hitcircles is going to fundamentally remain the same, I believe it's worth structuring things in a way that others can understand, and this to me feels completely differently to how we're doing things in general. I really don't want this structure to pollute the rest of the skinnable components if others take examples from it.

The explosion container changes I also question... Why can't we work out a value that works for both stable and lazer? How far are we trying to match stable?

**Comment by peppy** [comment]
To the point things feel good.

So you are against merging this as a temporary thing, even though the current live version is janky as hell?

**Comment by peppy** [comment]
New PR coming tomorrow to resolve this in a much better way.

**Pull request closed without merging**
