### PR TITLE
Implement scrolling to each section of options

### PR DESCRIPTION
**Pull request by ddevault**
Note: on desktop the icons on the sidebar don't show up and I'm not sure why. They show up in the draw viz but not on the actual overlay. It's correct on VisualTests.

Depends on https://github.com/ppy/osu-framework/pull/274

Does not implement seperate transitions for the main options panel and the nav

### CODE REVIEW

**Comment by peppy** [comment]
Rather than explicitly adding each of the OptionsSideNav buttons / actions / etc. it should be all handled in OptionsOverlay itself.

ie. make an `AddSection` method and handle the button adding in that (the icon could be specified in `OptionsSection` as a `internal virtual FontAwesome Icon`. AddSection could either create the `SidebarButton`s itself or call a method in OptionsSection to return the button (allowing per-section button customisation.. not sure if we'll ever need that though).

Underlying rule being to automate as much as possible to minimise implementation overhead when adding new sections or options.

**Comment by peppy** [comment]
Also I'd recommend *not* reusing `ToolbarButton` for this specific case. They are very tailored for the toolbar and won't work well in the options sidebar.

Consider that like the old osu!, when hovering the sidebar icons will need to show their text to the right and the tooltip that is present in `ToolbarButton` won't work well in this use case.

**Comment by SirCmpwn** [comment]
:+1:

**Comment by SirCmpwn** [comment]
Ready for review/merge. Take note of https://github.com/ppy/osu/pull/131/commits/1ce6a7285af4211bfb9555bd260e228ccc174f32, it contains opinions

**Comment by SirCmpwn** [comment]
Note: the opinionated commit is actually 4d04eb6

**Pull request merged**
