### PR TITLE
Scale down beatmap cards

### PR DESCRIPTION
**Pull request by stanriders**
Resolves #30649 

Before-after:
Extra:
image
image

Normal:
image
image

### CODE REVIEW

**Comment by bdach** [comment]
At this point I question these local scale overrides. Just change the metrics of the cards to reflect this everywhere?

**Comment by peppy** [comment]
Have you checked the remaining usage of this in a list view (`SpotlightsLayout`)? It sounds like this should be applied there too.. at which point I'd maybe consider changing the base specs and adjusting the cases that *don't* want the smaller scale to increase it.

**Comment by stanriders** [comment]
Fair enough, I'll scale the card itself

**Comment by stanriders** [comment]
I didn't scale beatmap badges as they've seem to be correctly sized for the smaller card already, and didn't change the nano-sized cards at all since they seem to be fine too

**Comment by peppy** [comment]
Keep in mind when reviewing this that some usages are now smaller than they used to be (one example is the solo spectator screen).

**Review by bdach — DISMISSED** [review]
I don't think you got everything. In particular the various badges on the cards seem to have grown in size, relatively speaking, and so has the difficulty bar display:

| master | this PR |
| :-: | :-: |
| osu_2024-11-19_12-01-48 | osu_2024-11-19_12-02-18 |

**Comment by stanriders** [comment]
> I don't think you got everything. In particular the various badges on the cards seem to have grown in size, relatively speaking, and so has the difficulty bar display:

As I've said, I didn't change badges because they looked too small for the original size already, as for the other differences I think that's probably because I didn't scale elements _exactly_ 0.8x, but to the closest integer size (so things that were 12 became 10 instead of 9.6 and such) 
I'll recheck just in case though

**Review by peppy — APPROVED** [review]

**Pull request merged**
