### PR TITLE
OptionsOverlay improvements

### PR DESCRIPTION
**Pull request by EVAST9919**

### CODE REVIEW

**Review by lunafreya — COMMENTED** [review]
Are you sure? Put a back button when you can also close the settings panel via top-left settings button?

**Comment by EVAST9919** [comment]
Oh, true

**Comment by peppy** [comment]
Have you tried making the fadein/fadeout instant to see if it fixes the relayout issue you were experiencing?

**Comment by peppy** [comment]
also can you rebase to remove the backbutton commits? kinda pointless having them in this PR now.

**Comment by EVAST9919** [comment]
can I just reopen this PR?

**Comment by peppy** [comment]
not the right approach for this. doesn't follow naming conventions (`eventLetterboxing`?) and doesn't look correct.

closing for now

**Pull request closed without merging**
