### PR TITLE
Add support for negative ParallaxAmount in ParallaxContainer

### PR DESCRIPTION
**Pull request by ghost**
Use the absolute value of ParallaxContainer to make sure we're not scaling things down when trying to use a negative ParallaxAmount.

(ParallaxAmount was set to -0.2f for demonstration purposes.)

[Old](https://i.gyazo.com/2897d46b26e403830f19f677f3c3f415.mp4)
[New](https://i.gyazo.com/74d6b8e2172d5a3117d9539530508ccd.mp4)

### CODE REVIEW

**Comment by smoogipoo** [comment]
When would you ever set `ParallaxAmount` to be a negative value? I think we should throw an exception instead.

**Comment by KoziLord** [comment]
Negative ParallaxAmount makes the background move against the mouse instead of with it (you can see that in the two links I provided).

**Comment by peppy** [comment]
If we're going to support negative parallax this should be documented in xmldoc.

**Comment by KoziLord** [comment]
I'll see what I can do

**Comment by peppy** [comment]
There is no point in continuously merging master into your branch.

**Comment by KoziLord** [comment]
Right, sorry

**Review by peppy — APPROVED** [review]

**Pull request merged**
