### PR TITLE
Add key to enable iOS 18's game mode

### PR DESCRIPTION
**Pull request by hrfarmer**
In iOS 18, Apple's added a Game Mode to iOS, similar to what they added on macOS, and this plist key enables it.
Reference: [https://youtu.be/SgshkDg1QN8?si=rBlukBrAP0JEBNF5&t=498](https://youtu.be/SgshkDg1QN8?si=rBlukBrAP0JEBNF5&t=498)

### CODE REVIEW

**Comment by peppy** [comment]
Please link actual apple documentation for this, not a youtube video.

Also please force push away your broken commit.

**Comment by hrfarmer** [comment]
Unless I'm blind I can't find anything in the actual documentation yet referencing it (which I guess? makes sense considering WWDC Day 1 was like 2 days ago), so should I just close this until Apple has more information?

**Comment by peppy** [comment]
Sounds good.

**Comment by Sukuratchi** [comment]
> I can't find anything in the actual documentation yet referencing it 

Seems like they added some docs as I've found the following: https://developer.apple.com/documentation/xcode/build-settings-reference#Supports-Game-Mode

**Pull request closed without merging**
