### PR TITLE
Remove the nullable disable annotations in the class belongs to the migration namespace.

### PR DESCRIPTION
**Pull request by andy840119**
Remove the `#nullable disable` annotation in the class belongs to the migration namespace.
Because migration does not nullable issue, so there's no need to have extra fix.

And here's the removing script:
```bash
#!/bin/bash

for file in $( find "$@" -type f -name '*.cs' ); do
    # remove the nullable disable line generate in another script
    # install the brew install gnu-sed and use gsed instead of the sed commend.
    
    # see: https://unix.stackexchange.com/a/93909
    gsed -i 'N;/\n#nullable disable/d' "$file"
done
```
Notice that the script is just a lazy way to remove the `#nullable disable` annotate in the class, manual fix compile error is still required.

step:
1. create the script.
2. Than ` brew install gawk` because osx does not have the `sed` commend.
3. run `bash remove_disable_null.sh osu.Game/Migrations` to remove the `#nullable disable` annotation.

### CODE REVIEW

**Comment by andy840119** [comment]
I'm not sure did you means run a script to remove all `#nullable disable` in a single PR?
I'm not sure about that because some of the property still need to check should let it nullable or not by hand(the experience in my project).
https://github.com/karaoke-dev/karaoke/pull/1406/files#diff-eeaa097989badc58b465c6056570b4856dc6218eb1cc501f506b2ad8dd8340d1R165
https://github.com/karaoke-dev/karaoke/issues/1390

**Comment by bdach** [comment]
I don't really follow. If automated removing of `#nullable disable` is wrong even if the end result passes compilation, then so is this PR? Did you check all of the files in this namespace manually?

**Review by smoogipoo — APPROVED** [review]
I don't mind doing it this way, personally.

**Comment by smoogipoo** [comment]
I think what @bdach was getting to is that he would prefer this removal of `#nullable disable` was done automatically for _all_ files that don't require any changes (embedding nullables in code), and then doing a second pass for those which do require such changes.

I personally don't mind doing it this way and applying all required modifications in the first pass on a per-namespace basis. It's a much of a muchness at the end of the day imo.

**Pull request merged**
