### PR TITLE
Consider case sensitivity when sorting beatmaps in song select

### LINKED ISSUE #26817: Lazer sorting does not include uppercase letters
### Type

Cosmetic

### Bug description

Example:

Xi (x is uppercase),
and
xi (x is lowercase),
is mixed up with themselves, and is not sorted by size of letter

### Screenshots or videos

image

### Version

2024.130.2-lazer

### Logs

Unrelated

### PR DESCRIPTION
**Pull request by vmexec**
fixes #26817

Screenshot 2024-01-31 at 15 51 43

### CODE REVIEW

**Comment by bdach** [comment]
gonna be honest here not even sure if the issue has any merit. is this a stable behaviour or something?

**Comment by frenzibyte** [comment]
I don't see a reason not to make this respect casing (looks weird having letter cases unsorted), unless it could have performance implications. That being said, all other sort modes should also respect case, not only artist.

**Comment by syscats** [comment]
> I don't see a reason not to make this respect casing (looks weird having letter cases unsorted), unless it could have performance implications. That being said, all other sort modes should also respect case, not only artist.

fixed c:
i doubt it could have any performance implications honestly

**Comment by frenzibyte** [comment]
Stable uses case-sensitive ordering method, as denoted by [this line](https://github.com/peppy/osu-stable-reference/blob/7519cafd1823f1879c0d9c991ba0e5c7fd3bfa02/osu!/GameplayElements/Beatmaps/BeatmapTreeManager.cs#L342) (which is `StringComparison.CurrentCulture` under the hood).

**Review by peppy — APPROVED** [review]

**Comment by frenzibyte** [comment]
Hold off on this one. Turns out there is a major difference between stable's sorting method (`StringComparison.CurrentCulture`) and lazer's sorting method (`StringComparison.Ordinal`). I'll resolve and summarize the difference shortly.

**Comment by peppy** [comment]
>  Turns out there is a major difference between stable's sorting method (StringComparison.CurrentCulture) and lazer's sorting method (StringComparison.Ordinal). I'll resolve and summarize the difference shortly.

Using current culture adds internationalisation overheads. I very strongly recommend against that path.

**Comment by frenzibyte** [comment]
I'm not referring to the use of that comparison mode specifically. Here's what I mean:
```csharp
List<string> test = new List<string> { "A", "B", "C", "D", "a", "b", "c", "d" };
test.Sort((a, b) => string.Compare(a, b, StringComparison.Ordinal));
Console.WriteLine($"Sort A-Z using ordinal (lazer): [{string.Join(", ", test)}]");

test = new List<string> { "A", "B", "C", "D", "a", "b", "c", "d" };
test.Sort((a, b) => string.Compare(a, b, StringComparison.InvariantCulture));
Console.WriteLine($"Sort A-Z using current/invariant culture (stable): [{string.Join(", ", test)}]");
```
```
Sort A-Z using ordinal (lazer): [A, B, C, D, a, b, c, d]
Sort A-Z using current/invariant culture (stable): [a, A, b, B, c, C, d, D]
```

Notice with ordinal, all strings starting with lowercase letters are shifted all the way to the end of the list, meanwhile on current/invariant culture mode, strings are correctly sorted alphabetically with lowercase letters appearing before uppercase letters.

The current/invariant culture behaviour (aka stable) can be replicated without the internationalisation overhead by comparing with `OrdinalIgnoreCase`, then if the strings are equal (case insensitive), another comparison is performed using `Ordinal`:

```csharp
test = new List<string> { "A", "B", "C", "D", "a", "b", "c", "d" };
test.Sort((a, b) =>
{
    int result = string.Compare(a, b, StringComparison.OrdinalIgnoreCase);
    if (result == 0)
        result = -string.Compare(a, b, StringComparison.Ordinal); // negative to place lowercase letters before uppercase.
    return result;
});
Console.WriteLine($"Sort A-Z using ignore-case-ordinal + ordinal: [{string.Join(", ", test)}]");
```
```
Sort A-Z using ignore-case-ordinal + ordinal (this comment's proposal): [a, A, b, B, c, C, d, D]
```

**Comment by peppy** [comment]
Lazer's sort with this PR looks more in line with what I'd expect.

**Comment by frenzibyte** [comment]
I'm not necessarily opposed to this behaviour, but I feel it might confuse people, especially those coming from stable which expect the sorting method to be completely alphabetic rather than uppercase-alphabetic followed by lowercase-alphabetic. I'm fine with rolling it out, but I'll leave it to your call.

**Review by frenzibyte — APPROVED** [review]

**Pull request merged**
