### PR TITLE
skip button shortcut

### PR DESCRIPTION
**Pull request by Alex4386**
Capable of pressing skip button with X or Z

### CODE REVIEW

**Comment by peppy** [comment]
This shouldn't be added locally. It should be done at a `PlayerInputManager` level.

**Comment by Alex4386** [comment]
Thanks for your feedback! @peppy

**Comment by Alex4386** [comment]
It seems to [[PlayerInputManager]] enables and disables the mouse input. Could you give me some advice?

**Comment by peppy** [comment]
Check `OsuKeyConversionInputManager`. Basically consider this: the key bindings will be set by the user. The Z and X keys are only ever valid in osu! mode.

It's also debatable whether they should be used to interact with the UI in the first place.

**Comment by Alex4386** [comment]
Thanks! I will check it out right away.

**Comment by Alex4386** [comment]
And I forgot that users **can change** the key bindings.

**Comment by Alex4386** [comment]
@peppy 
Finally, I knew how to check whether or not user set the custom key.
Is there any way that to know the custom key that user changed?

**Comment by peppy** [comment]
key binding is not implemented yet.

**Comment by Alex4386** [comment]
image
Right, There is no key bindings yet. (Just checked it now)

So, I need a handler for the custom key is set, is it right?

**Comment by peppy** [comment]
honestly i wouldn't be adding what you're adding unless you have the confidence to implement the full key binding system

**Comment by Alex4386** [comment]
I understood. 
Since full key binding is not complete, It could be a bottleneck for future keybinding system.

Anyways, Thanks for your explanation about how osu! behaves on key inputs.

**Pull request closed without merging**
