### PR TITLE
Fix Relax mod not working with osu! ruleset

### LINKED ISSUE #5184: Relax mod is broken in latest release.
In latest release **_2019.628.1_**, the relax mod appears to be broken. The relax mod does not hit the circles even if your cursor is exactly in the circle’s position on time.
**Video:** https://youtu.be/euQ06KIJRys

### PR DESCRIPTION
**Pull request by frenzibyte**
`IsHovered` doesn't get updated anymore due to `HandlePositionalInput` not set to true, which breaks Relax mod, in that line below. 
https://github.com/ppy/osu/blob/43d83b35d04c7f32e639e02e889a3e33df4953a1/osu.Game.Rulesets.Osu/Mods/OsuModRelax.cs#L43

The slider and spinner didn't break because slider uses the ball's hover, while the spinner doesn't require anything to be set
https://github.com/ppy/osu/blob/43d83b35d04c7f32e639e02e889a3e33df4953a1/osu.Game.Rulesets.Osu/Mods/OsuModRelax.cs#L44

Closes #5184

### CODE REVIEW

**Comment by peppy** [comment]
- The issue title doesn't explain what this is fixing but should
- The code change doesn't have an inline comment but should (so we actually *know* why this is there).
- Your issue body should explain where relax is using this (a permalink to the line in question would be satisfactory).

**Comment by smoogipoo** [comment]
It should be handled on a per-hitobject in any-case imo (in this case, `DrawableOsuHitObject`).

**Comment by peppy** [comment]
That too. This is probably going to be breaking more than just relax (now or in the future).

**Comment by iiSaLMaN** [comment]
> * The issue title doesn't explain what this is fixing but should
> * The code change doesn't have an inline comment but should (so we actually _know_ why this is there).
> * Your issue body should explain where relax is using this (a permalink to the line in question would be satisfactory).

> It should be handled on a per-hitobject in any-case imo (in this case, DrawableOsuHitObject).

Resolved.

**Review by peppy — APPROVED** [review]

**Pull request merged**
