### PR TITLE
Refactor `LatencyCursorContainer` to display menu cursor when inactive

### LINKED ISSUE #18718: Menu cursor is invisible when external link popup is shown during latency certifier
### Type

Game behaviour

### Bug description

The menu cursor does not appear for menus when the latency certifier is open, I've tested this on both Windows 10 and Linux and both have the same error

### Screenshots or videos

https://user-images.githubusercontent.com/58333920/173891005-3c8da4d2-b7a6-40b6-9997-c014aa56a30c.mp4

### Version

2022.615.0-lazer

### Logs

[logs.zip](https://github.com/ppy/osu/files/8911870/logs.zip)

### PR DESCRIPTION
**Pull request by frenzibyte**
- Closes #18718 

`MenuCursorContainer` already provides the logic to switch between a menu cursor and a custom cursor, but `LatencyCursorContainer` required a minor refactor to become an actual `CursorContainer`.

Note that the menu cursor remains hidden when hovering on the settings and linked labels as they do not steal hover from the latency area, but will hide when hovering on the back button or opening up a dialog:

https://user-images.githubusercontent.com/22781491/174125587-7899bf6c-5ba9-4a8c-9bd7-820a374c1610.mp4

~~Also in beb03316400ddbffecdf84943fb5e6f0a486d165, menu cursor will appear when hovering over latency certifier buttons~~

### CODE REVIEW

**Comment by bdach** [comment]
> Also in https://github.com/ppy/osu/commit/beb03316400ddbffecdf84943fb5e6f0a486d165, menu cursor will appear when hovering over latency certifier buttons:

How is this wanted? It makes it so that you can compare framerate when hovering over the button and when hovering just beneath it. It kind of helps to cheat on the certification process, no?

**Comment by frenzibyte** [comment]
I don't follow how that can result in cheating, though? Is it because it allows you to see the difference between unlimited and limited on the same area..? Can't the same apply to popup dialog, which this PR introduces as well?

**Comment by bdach** [comment]
If showing the cursor at full fps is allowed, then the intentional fade-out between both halves of the latency certifier makes no sense. The edge there is "blurred" precisely so that there's no hard edge that you can use to make the comparison easier.

I don't think this applies to the dialog because the dialog happens to be covering the edge between the halves.

**Comment by frenzibyte** [comment]
I see, will revert the button change for now since it's not in scope of this PR to discuss about.

**Review by peppy — APPROVED** [review]

**Pull request merged**
