### PR TITLE
Add confirmation dialog when about to discard a playlist

### LINKED ISSUE #19444: Include warning when canceling playlist creation
### Type

Game behaviour

### Bug description

When creating playlists, to prevent the user from accidentally discarding a playlist they created, a warning should be displayed similar to the one in the editor. Mobile releases are more susceptible to this UX problem since one of their fingers can accidentally tap the back button, discarding all work.

### Screenshots or videos

https://user-images.githubusercontent.com/75596775/181500237-e5fff7b7-e82f-4ece-9b34-902fb9db8ff4.mp4

### Version

2022.723.0

### Logs

[logs.zip](https://github.com/ppy/osu/files/9209210/logs.zip)

### PR DESCRIPTION
**Pull request by peppy**
The confirmation will only show if items have been added to the playlist.

Closes https://github.com/ppy/osu/issues/19444.

### CODE REVIEW

**Comment by Joehuu** [comment]
This doesn't work with the home button or window exit, should be done on `OnExiting`.

**Comment by peppy** [comment]
That's not going to be easy, as this is stopping a settings *overlay* within a screen.

**Comment by frenzibyte** [comment]
Was going to say. Simplest solution would be to bring back the settings overlay immediately on `OnExiting`, and that won't cause any visual side effects since the exiting event is raised immediately after the back button event. Albeit a bit dodgy.
```diff
diff --git a/osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs b/osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
index 5b3ed0059d..72b3f17acd 100644
--- a/osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
+++ b/osu.Game/Screens/OnlinePlay/Match/RoomSubScreen.cs
@@ -288,23 +288,8 @@ public override bool OnBackButton()
         {
             if (Room.RoomID.Value == null)
             {
-                if (dialogOverlay == null || Room.Playlist.Count == 0)
-                {
-                    settingsOverlay.Hide();
-                    return base.OnBackButton();
-                }
-
-                // if the dialog is already displayed, block exiting until the user explicitly makes a decision.
-                if (dialogOverlay.CurrentDialog is ConfirmDiscardChangesDialog)
-                    return true;
-
-                dialogOverlay?.Push(new ConfirmDiscardChangesDialog(() =>
-                {
-                    settingsOverlay.Hide();
-                    this.Exit();
-                }));
-
-                return true;
+                settingsOverlay.Hide();
+                return base.OnBackButton();
             }
 
             if (UserModsSelectOverlay.State.Value == Visibility.Visible)
@@ -348,8 +333,30 @@ public override void OnResuming(ScreenTransitionEvent e)
             Scheduler.AddOnce(updateRuleset);
         }
 
+        private bool exitConfirmed;
+
         public override bool OnExiting(ScreenExitEvent e)
         {
+            if (!exitConfirmed && dialogOverlay != null && Room.RoomID.Value == null && Room.Playlist.Count > 0)
+            {
+                // if the dialog is already displayed, block exiting until the user explicitly makes a decision.
+                if (dialogOverlay.CurrentDialog is ConfirmDiscardChangesDialog)
+                    return true;
+
+                // in a setup screen, exiting screen will hide the settings overlay on OnBackButton,
+                // but we want to bring it back since we're blocking exit.
+                settingsOverlay.Show();
+
+                dialogOverlay?.Push(new ConfirmDiscardChangesDialog(() =>
+                {
+                    exitConfirmed = true;
+                    settingsOverlay.Hide();
+                    this.Exit();
+                }));
+
+                return true;
+            }
+
             RoomManager?.PartRoom();
             Mods.Value = Array.Empty<Mod>();
 
```

**Comment by peppy** [comment]
@frenzibyte want to apply that change? i think it looks fine, and probably good enough to get in for now.

**Comment by frenzibyte** [comment]
I've went ahead with a bit of a different change that doesn't involve reverting operations done in `OnBackButton`.  Have a second look on it.

**Review by frenzibyte — DISMISSED** [review]

**Comment by peppy** [comment]
I guess it's okay, I was just avoiding this kind of complexity (similar to what the editor is doing).

Tests are failing though.

**Comment by frenzibyte** [comment]
Was due to the dialog blocking tests from exiting room sub screen. Fixed with local overrides similar to editor tests.

**Review by frenzibyte — APPROVED** [review]

**Pull request merged**
