### PR TITLE
Remove links on disclaimer

### LINKED ISSUE #4650: Clicking the text before Lazer starts on iOS will crash
https://streamable.com/nzs95 

Version: latest

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

### LINKED ISSUE #4816: osu! sound in disclaimer
**Describe the bug:** When you hover in the middle of the window while the disclaimer is there the audio/hover sound is played. I don't know if it's intended or not.

**Screenshots or videos showing encountered issue:** https://streamable.com/nljlk

**osu!lazer version:** 2019.514.0

**Logs:** N/A

### PR DESCRIPTION
**Pull request by Joehuu**
Closes #4650 & fixes #4816.

---

### CODE REVIEW

**Comment by smoogipoo** [comment]
Not sure about this one. The crash is an issue with the framework and should be resolved by https://github.com/ppy/osu-framework/pull/2592.

I'd consider displaying the cursor visible during the disclaimer.

**Comment by peppy** [comment]
Agree on cursor displaying if anything.

**Comment by Joehuu** [comment]
Clicking external links anywhere will result in a dialog overlay to pop up, but overlays don't show on startup screens atm. Commented on https://github.com/ppy/osu/issues/4650#issuecomment-506773377.

**Comment by Joehuu** [comment]
Closing, needs to be resolved via a external link dialog bypass on intro links and showing cursor on intro.

**Pull request closed without merging**
