### PR TITLE
Fix a potential crash when exiting play during the results screen transition

### LINKED ISSUE #11682: Exception when entering player during exit transition
After watching a replay, I exited via pressing escape right as the completion transition was happening:

```
[runtime] 2021-02-05 08:28:15 [error]: osu.Framework.Screens.ScreenStack+ScreenHasChildException: Cannot perform Exit when a child is already present. Use MakeCurrent instead.
[runtime] 2021-02-05 08:28:15 [error]: at osu.Framework.Screens.ScreenStack.Exit(IScreen source)
[runtime] 2021-02-05 08:28:15 [error]: at osu.Framework.Screens.ScreenExtensions.Exit(IScreen screen)
[runtime] 2021-02-05 08:28:15 [error]: at osu.Game.Screens.Play.Player.performUserRequestedExit() in /home/smgi/Repos/osu/osu.Game/Screens/Play/Player.cs:line 513
[runtime] 2021-02-05 08:28:15 [error]: at osu.Game.Graphics.Containers.HoldToConfirmContainer.Confirm() in /home/smgi/Repos/osu/osu.Game/Graphics/Containers/HoldToConfirmContainer.cs:line 52
[runtime] 2021-02-05 08:28:15 [error]: at osu.Game.Screens.Play.HUD.HoldForMenuButton.Button.Confirm() in /home/smgi/Repos/osu/osu.Game/Screens/Play/HUD/HoldForMenuButton.cs:line 187
[runtime] 2021-02-05 08:28:15 [error]: at osu.Game.Graphics.Containers.HoldToConfirmContainer.<BeginConfirm>b__12_0(HoldToConfirmContainer _) in /home/smgi/Repos/osu/osu.Game/Graphics/Containers/HoldToConfirmContainer.cs:line 47
[runtime] 2021-02-05 08:28:15 [error]: at osu.Framework.Graphics.Transforms.TargetGroupingTransformTracker.invokePendingRemovalActions()
[runtime] 2021-02-05 08:28:15 [error]: at osu.Framework.Graphics.Transforms.Transformable.updateTransforms(Double time, Boolean forceRewindReprocess)
[runtime] 2021-02-05 08:28:15 [error]: at osu.Framework.Graphics.Drawable.UpdateSubTree()
[runtime] 2021-02-05 08:28:15 [error]: at osu.Framework.Graphics.Containers.CompositeDrawable.UpdateSubTree()
```

### PR DESCRIPTION
**Pull request by peppy**
The Confirm call in `HoldToConfirmContainer`s is chained to transforms, so it can potentially run during the transition to a new screen. We were guarding against this in the `Restart` flow already, but not the exit flow.

Closes https://github.com/ppy/osu/issues/11682.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Pause -> Continue (don't click orange cursor) -> Pause. This now exits to song selection.
Pause -> Continue (click the orange cursor) -> Pause. This now exits to song selection.

Seems like the Continue -> Pause process is generally just broken, regardless of whether you pause via esc key or the hold-to-quit button.

**Comment by smoogipoo** [comment]
Retry from results screen crashes the game:
```
Unhandled exception. osu.Framework.Screens.ScreenStack+ScreenNotCurrentException: Cannot perform Exit on a non-current screen.
   at osu.Framework.Screens.ScreenStack.Exit(IScreen source)
   at osu.Framework.Screens.ScreenExtensions.Exit(IScreen screen)
   at osu.Game.Screens.Play.Player.PerformExit(Boolean showDialogFirst) in /home/smgi/Repos/osu/osu.Game/Screens/Play/Player.cs:line 517
   at osu.Game.Screens.Play.Player.Restart() in /home/smgi/Repos/osu/osu.Game/Screens/Play/Player.cs:line 547
   at osu.Game.Screens.Ranking.RetryButton.<load>b__6_0() in /home/smgi/Repos/osu/osu.Game/Screens/Ranking/RetryButton.cs:line 51
```
These changes are quite hard to review because of the large complexity, so I'm falling back on real-world testing for now.

**Comment by peppy** [comment]
Luckily both of the issues reported were simple fixes. Both now have test coverage.

**Comment by smoogipoo** [comment]
Pressing escape from the orange cursor screen should bring up the pause overlay again, rather than quitting gameplay.

**Comment by peppy** [comment]
Right, so that case already had test coverage, but the test scene is calling `Player.Pause` rather than the user flow (via `PerformExit`). I'm going to change the whole scene to trigger a user pause, rather than external.

Are you okay with making `Pause` protected? Currently it is only used by tests:

20210215 160901 (JetBrains Rider)

**Comment by smoogipoo** [comment]
Is this something like a bypass? Where the user-pause-specific stuff shouldn't happen like delays/blocking the pause, etc, in various test scenes. Because if so, then maybe `Pause()` should still be public for those scenes? Or I guess they can re-expose as public for their own uses.

**Comment by peppy** [comment]
The `Pause` function internally already has those checks, so it's not really that. I guess it can remain as is, no real harm either way.

**Comment by bdach** [comment]
`TestSceneScreenNavigation.TestSongContinuesAfterExitPlayer` test failures here look like actual failures.

**Comment by peppy** [comment]
Turns out there's actually a separate `FailOverlay` I wasn't accounting for. TIL.

**Review by smoogipoo — APPROVED** [review]
lgtm

**Pull request merged**
