### PR TITLE
Fix potential crash in tests when attempting to lookup key bindings in cases the lookup is not available

### PR DESCRIPTION
**Pull request by peppy**
Reproduce with `TestScenePlayerLoader` after toggling HUD to hidden in local config file.

### CODE REVIEW

**Comment by frenzibyte** [comment]
Keep in mind the failure will still be reproducible when running tests in Release configuration (where the regular `OsuConfigManager` variant will be used and the lookup actions would still be left uninitialised).

I was wondering about just initialising them by default:
```diff
diff --git a/osu.Game/Configuration/OsuConfigManager.cs b/osu.Game/Configuration/OsuConfigManager.cs
index 07d2026c65..fb8daf44cb 100644
--- a/osu.Game/Configuration/OsuConfigManager.cs
+++ b/osu.Game/Configuration/OsuConfigManager.cs
@@ -240,9 +240,9 @@ public override TrackedSettings CreateTrackedSettings()
             };
         }

-        public Func<Guid, string> LookupSkinName { private get; set; }
+        public Func<Guid, string> LookupSkinName { private get; set; } = _ => "Unknown";

-        public Func<GlobalAction, LocalisableString> LookupKeyBindings { get; set; }
+        public Func<GlobalAction, LocalisableString> LookupKeyBindings { get; set; } = _ => "Unknown";
     }

     // IMPORTANT: These are used in user configuration files.
```

but I suppose that defeats the point of [the assertions in `CreateTrackedSettings()`](https://github.com/ppy/osu/blob/623d6d6d2d0635b55da3d99d499b0ef5a085b618/osu.Game/Configuration/OsuConfigManager.cs#L189-L191).

**Comment by peppy** [comment]
That's what I originally had. Not sure though. I think I prefer a throw than accidentally breaking everything to become "unknown".

**Comment by frenzibyte** [comment]
One idea I had in mind is to move out the implementation of these lookup actions from `OsuGame` to `OsuGameBase`, as it doesn't seem to be harmful:
```diff
diff --git a/osu.Game/OsuGame.cs b/osu.Game/OsuGame.cs
index fb81e4fd14..23f5abbd12 100644
--- a/osu.Game/OsuGame.cs
+++ b/osu.Game/OsuGame.cs
@@ -663,20 +663,6 @@ protected override void LoadComplete()
             ScoreManager.PostNotification = n => Notifications.Post(n);
             ScoreManager.PostImport = items => PresentScore(items.First().Value);

-            // make config aware of how to lookup skins for on-screen display purposes.
-            // if this becomes a more common thing, tracked settings should be reconsidered to allow local DI.
-            LocalConfig.LookupSkinName = id => SkinManager.Query(s => s.ID == id)?.ToString() ?? "Unknown";
-
-            LocalConfig.LookupKeyBindings = l =>
-            {
-                var combinations = KeyBindingStore.GetReadableKeyCombinationsFor(l);
-
-                if (combinations.Count == 0)
-                    return ToastStrings.NoKeyBound;
-
-                return string.Join(" / ", combinations);
-            };
-
             Container logoContainer;
             BackButton.Receptor receptor;

diff --git a/osu.Game/OsuGameBase.cs b/osu.Game/OsuGameBase.cs
index 8b75de9718..d06bbf5d20 100644
--- a/osu.Game/OsuGameBase.cs
+++ b/osu.Game/OsuGameBase.cs
@@ -30,6 +30,7 @@
 using osu.Game.Input;
 using osu.Game.Input.Bindings;
 using osu.Game.IO;
+using osu.Game.Localisation;
 using osu.Game.Online;
 using osu.Game.Online.API;
 using osu.Game.Online.Chat;
@@ -389,6 +390,20 @@ protected override void LoadComplete()
             fpsDisplayVisible.TriggerChange();

             FrameStatistics.ValueChanged += e => fpsDisplayVisible.Value = e.NewValue != FrameStatisticsMode.None;
+
+            // make config aware of how to lookup skins for on-screen display purposes.
+            // if this becomes a more common thing, tracked settings should be reconsidered to allow local DI.
+            LocalConfig.LookupSkinName = id => SkinManager.Query(s =>s.ID == id)?.ToString() ?? "Unknown";
+
+            LocalConfig.LookupKeyBindings = l =>
+            {
+                var combinations = KeyBindingStore.GetReadableKeyCombinationsFor(l);
+
+                if (combinations.Count == 0)
+                    return ToastStrings.NoKeyBound;
+
+                return string.Join(" / ", combinations);
+            };
         }

         protected override IReadOnlyDependencyContainer CreateChildDependencies(IReadOnlyDependencyContainer parent) =>
```

**Comment by bdach** [comment]
I can't really find myself agreeing with this solution given it only works in debug mode. Sure, in development 98% of the time nobody is going to be running release, but that is a double-edged sword - making debug-specific fixes also makes it more likely for a release-only problem to slip by at some point.

Would prefer one of the solutions given above. Not sure which one I like best - probably the one in `OsuConfigManager` because I don't really want `OsuGameBase` to grow too much if it can be avoided.

**Comment by peppy** [comment]
Fair enough. I've moved to `OsuConfigManager`.

**Review by frenzibyte — APPROVED** [review]

**Pull request merged**
