### PR TITLE
Fix rewind incorrectly selecting the same beatmap

### LINKED ISSUE #25904: After randomly selecting every beatmap more than once, rewind keeps selecting the same beatmap
### Discussed in https://github.com/ppy/osu/discussions/25890

<div type='discussions-op-text'>

<sup>Originally posted by **LittleEndu** December 19, 2023</sup>
Was told to open an issue but logs are required and I can't generate ones right now 🤷 

https://github.com/ppy/osu/pull/23312#issuecomment-1859772108

https://github.com/ppy/osu/blob/469a659938dfb3c696c9a9fb51c7252214014a31/osu.Game/Screens/Select/BeatmapCarousel.cs#L623-L624

This used to be a stack, but after changing it to list, rewind now selects from back but removes from front, causing the selection of the same beatmap until every instance of it has been removed</div>

### PR DESCRIPTION
**Pull request by sukinathan**
Fixes #25904

### CODE REVIEW

**Comment by peppy** [comment]
Please add test coverage (ie. add a test which fails without your change) somewhere around here:

https://github.com/ppy/osu/blob/b884f1af4aada2a8e196be5b0102b19c354df79a/osu.Game.Tests/Visual/SongSelect/TestSceneBeatmapCarousel.cs#L417-L474

**Review by peppy — DISMISSED** [review]
Needs test

**Comment by ntransw** [comment]
Added a working test, although I wasn't sure how to populate `randomSelectedBeatmaps` with duplicates to reproduce the failure outside of just calling `nextRandom()` excessively.

**Comment by bdach** [comment]
Test fails on master, so it'll work.

**Review by bdach — DISMISSED** [review]

**Comment by bdach** [comment]
@ntransw no need to merge master. please read contributing guidelines. now i have to re-approve the CI run that i was gonna see if it passes.

**Review by bdach — APPROVED** [review]

**Pull request merged**
