### PR TITLE
Fix up replay playback speed slider having a different tooltip than the displayed number

### LINKED ISSUE #1618: Playback slider tooltip and text show values of different precision
Playback speed slider in replays/autoplay have a tooltip and a text for their value with different precision. These should be the same or the tooltip may be entirely unnecessary here.

qq

### PR DESCRIPTION
**Pull request by smoogipoo**
Prereqs:
- [x] https://github.com/ppy/osu-framework/pull/1320

This PR has mostly transformed into just osu!-side changes for Bindables, with an after-the-fact fix to replay settings >_>

Closes #1618

### CODE REVIEW

**Comment by peppy** [comment]
Looks good, but two things I noticed:

- BindableInt precision (above 1) doesn't seem to be working at all
- There are no tests for precision values above 1. I think this is an important one to test as it makes the bar more coarse in movement, say minvalue 0 maxvalue 100 precision 10 (currently untestable).

**Review by peppy — DISMISSED** [review]

**Comment by peppy** [comment]
Will leave this approved and up to you whether you want to merge or fix the cited issues with precisions above one (probably best to do so).

**Comment by smoogipoo** [comment]
Will look into the aforementioned issues before merging.

**Comment by smoogipoo** [comment]
Added dependency on https://github.com/ppy/osu-framework/pull/1320

**Review by peppy — APPROVED** [review]

**Pull request merged**
