### PR TITLE
Reverse order of `Score` and `Health` processing to allow fail conditions to read from updated score

### PR DESCRIPTION
**Pull request by peppy**
For #18402.

Not sure if this will pass tests, but from reading through the code it looks like it may be okay?

### CODE REVIEW

**Comment by ggliv** [comment]
Should probably supersede #18626 if we're taking this approach.

**Comment by bdach** [comment]
> Not sure if this will pass tests

Swing and a miss unfortunately.

**Comment by peppy** [comment]
I had a feeling the ordering was to block increments after a fail, but I couldn't see how this was happening when reading the code. Will work through it tomorrow.

**Comment by peppy** [comment]
Just going to close this. Don't have a valid solution in mind.

For future visitors: this fails because `HealthProcessor` sets `FailedAtJudgement`:

https://github.com/ppy/osu/blob/27c497145f87449ac17c08796fc57026d3129f2e/osu.Game/Rulesets/Scoring/HealthProcessor.cs#L37

Is this isn't set at the precise place it is, `ScoreProcessor` will continue to happily accept all judgements into the future.

**Pull request closed without merging**
