### PR TITLE
Apply new rider metadata changes

### PR DESCRIPTION
**Pull request by peppy**
@smoogipoo please check this doesn't get changed/obliterated by non-eap builds before merging.

### CODE REVIEW

**Comment by smoogipoo** [comment]
How do you trigger this file to be updated by Rider?

**Comment by peppy** [comment]
Just by looking at a project in any recent EAP build.

**Comment by smoogipoo** [comment]
I can't get EAP 10 to change this file, but I also can't get the stable build to revert these changes.

**Review by smoogipoo — APPROVED** [review]

**Comment by peppy** [comment]
Weird. I only made this change because @frenzibyte reported the same thing, I've just been dealing with it for a while now. Can't find any documentation on what it means.

**Pull request merged**
