### PR TITLE
Add special logic to song select to avoid obvious clipping when notifications are displayed

### PR DESCRIPTION
**Pull request by peppy**
Not sure if we will keep this going forward (there will likely be an opaque tab control on the notifications overlay similar to options) but let's go with this for now.

### CODE REVIEW

**Review by kmoore43 — APPROVED** [review]

**Comment by Aergwyn** [comment]
I played around switching between master and this change and moving the whole UI makes it really uncomfortable. It's not so noticeable in MainMenu but a moving UI in SongSelect makes me feel a bit dizzy.
Elements on the right side hanging in screen or getting pushed off also appear weird.
qq
Could it maybe only shove in the side that is opened? In a way like resizing the width of the window would appear.

**Comment by peppy** [comment]
See my extended commit comment. This will likely be hidden in a similar way to the settings panel

**Comment by peppy** [comment]
As a side note, it was always supposed to behave like this. The pushing behaviour regressed when I flattened the screen stack to fix nested input events last week.

**Review by smoogipoo — APPROVED** [review]
I think this is ok for now, but I think the scrollbar should be hidden.

**Pull request merged**
