### PR TITLE
Change accuracy challenge mod fail trigger to "max achievable" (and allow customisation)

### PR DESCRIPTION
**Pull request by cdwcgt**
- Relevant https://github.com/ppy/osu/discussions/22546
- ~~Depends on https://github.com/ppy/osu/pull/23679~~

after https://github.com/ppy/osu/pull/18626 was merged, the mod can fail the player at any time, and can use `MaximumAccuracy` in the `scoreProcessor` to implement the new acc mode

as required by https://github.com/ppy/osu/pull/18402#issuecomment-1386707533, when you choose `MaximumAchievable`  mode, Accuracy Challenge will failed player when Minimum Accuracy cannot be achieve.

https://user-images.githubusercontent.com/34775378/234523235-11e4ddea-d441-43c0-9652-9c664fd80a8f.mp4

### CODE REVIEW

**Comment by monochrome22** [comment]
Relevant https://github.com/ppy/osu/discussions/22546

It was decided in Discord that adding Maximum Accuracy as an option is not the way forward. 
https://discord.com/channels/188630481301012481/188630652340404224/1084764127123230730

**Comment by bdach** [comment]
> Of course, this issue should be discussed elsewhere but not this pr

Pray tell, where else would you discuss the validity of adding a setting, rather than *in the PR that adds the setting*? The relevant conversation even says that adding this setting is *a worse option than not having it at all and defaulting to max achievable*.

**Comment by cdwcgt** [comment]
Okay, I thought it should be in other related issus like #22546, so I got it.

**Comment by peppy** [comment]
I've seen this mentioned elsewhere (either changelog or youtube comments most likely) where the user expectation was "maximum achievable" should be the default.

I'm not against this, but needs consensus amongst us at least.

**Comment by cdwcgt** [comment]
So we have two options.
1. remove "Standard" mode, and leave "maximum achievable" mode.
2. set "maximum achievable" mode as default and keep "Standard" mode.

I personally prefer the second, the second may be useful in some special mp rooms or playlists.

**Comment by peppy** [comment]
I'm neutral as to whether the default should be changed or an option added

cc/ @ppy/team-client

**Comment by monochrome22** [comment]
Not team, but definitely the default should be changed to Maximum. Standard has no practical uses. With Standard, the goal is not to get a score with a certain accuracy, but rather the goal is to get far enough into the map that you don't die to a random 100. This can be fun, but it can't be used for actual scores, because the mod would fail the player even if they were on track to potentially getting the accuracy that they wanted. 
Having the mod be unpractical by default and forcing players to change an option to actually make it useful would simply be poor design.

As for whether or not Standard should be kept as an option: it can indeed be used for fun in a multiplayer lobby, though it's very niche and I can't imagine it becoming common. However, the only issue with keeping it would be that it would clutter the UI, but the Accuracy Challenge mod doesn't have many options, meaning you wouldn't need to scroll even if there's an option to switch to Standard, so clutter isn't really a problem, so it should be fine to keep Standard as an option.

**Comment by cdwcgt** [comment]
In fact, I haven't considered setting "Standard" as the default.

What I want to know now is whether "standard" should be removed.

It should be seen from the two options I mentioned.

**Comment by Sleepteiner** [comment]
I think the "Standard" accuracy mode should stay in the game. It is the most efficient way that I can think of to go for a better accuracy score on a map. If you are ahead of your goal accuracy at any point in the map (including the first circle) your chances of actually finishing with your goal accuracy is dramatically higher, so having an auto-retry function when the player falls below a certain accuracy would save me a ton of time as an accuracy-focused player.

Once lazer becomes the main client, I will likely use the Accuracy Challenge mod with the standard accuracy mode very frequently, especially if accuracy minimums with precision down to a hundredth of a percent are added and assuming the Accuracy Challenge mod will show up on nomod leaderboards like SD and PF.

**Comment by monochrome22** [comment]
> It is the most efficient way that I can think of to go for a better accuracy score on a map. If you are ahead of your goal accuracy at any point in the map (including the first circle) your chances of actually finishing with your goal accuracy is dramatically higher

That's an interesting idea, I wonder how well it would work in practice. I went through some of my replays and found multiple plays where I got accuracy drops early, then SSed the rest. Have you tried playing with the current Accuracy Challenge mod? Did you find that it works to your expectation and saves you time? I feel like you would at the very least end up with as many unnecessary retries as you would get good retries. You might be able to test it by setting requirement to 99%.

In any case, even if it works, maximum should still definitely be the default; the described usage case here is pretty niche, it would only work for very high accuracy players who rarely get 100s. And even if it doesn't work as well as expected, it's still a potential practical usage case (which I didn't think of), so Standard should definitely be kept as an option.

**Comment by monochrome22** [comment]
These higher precision settings are not very precise. 

https://github.com/ppy/osu/assets/122969285/b8699fc2-fbbe-4dfa-9efb-bc1ce5299741

In my opinion, if you're going to allow more precise settings, then it should be an input box, like for seed for random mod.

inputbox

Value should be 90.00 by default. If the users sets a value below 60.00, then it resets to 60.00. If they set a value above 99.99, then it resets to 99.99.

**Comment by bdach** [comment]
I'm not sure setting accuracy goals with 0.01% granularity even needs to be a thing. Again with the weird scope creep and out-of-scope changes...

**Comment by Sleepteiner** [comment]
> Have you tried playing with the current Accuracy Challenge mod? Did you find that it works to your expectation and saves you time? I feel like you would at the very least end up with as many unnecessary retries as you would get good retries.

I've messed around with the mod for probably a couple hours now. There are unnecessary retries technically, but the further you get in the map, the rarer they become. For years I've basically used this method in stable just without the auto-retry feature. I figure out how far I have to get into the map without getting a 100 to stay above my target accuracy and then I would retry pretty much every time I get a 100 before that point. This mod does that for me automatically, saving me time.

If I really mess up a pattern like a stream, especially early in the map, the chances of recovering are often small enough to the point that it is better to just retry. One strategy could also be setting the target accuracy on the mod a percent below what you are actually aiming for, which would allow the player to have those "SS the rest of the map to recover" moments more frequently. On hard maps with this mod, getting past the first hard section while still being above the target accuracy is exciting because it means that the target accuracy is actually doable for sure.

> I'm not sure setting accuracy goals with 0.01% granularity even needs to be a thing.

It would increase the cases where this mod is useful by a ton, in my opinion. If a player gets 98.15% and wants to improve their accuracy using this mod, the jump to 99% is huge in a lot of cases. And if the player gets 99.55% on a marathon map, then this mod as it is just can't be used well.

**Comment by monochrome22** [comment]
> Again with the weird scope creep and out-of-scope changes... 

I agree it's out of scope, I just thought if it is going to be added then it should be added properly. 

>Why not allow users to set a value below 60.00? 

I said it because of this: https://github.com/ppy/osu/pull/18402#discussion_r1084806447. Though that applied to the slider, it might be fine to allow any value with input box.
Anyway we're getting ahead of ourselves, the precise values are likely out of scope for this PR, the only change for now should be changing default to maximum and having standard as an option.

**Review by bdach — APPROVED** [review]

**Comment by bdach** [comment]
@ppy/team-client requesting second check

**Comment by peppy** [comment]
I get that this is sharing strings from an existing implementation, but I do think this could be improved:

osu! 2023-05-30 at 04 26 55

"Accuracy mode" -> "Fail mode" or "Trigger mode" or "Fail trigger mode"
"Stadard" -> "Immediate" or "Point in time"

Not going to request the changes in this PR because they'd likely also invoke similar changes on the other component using the strings. Something to reconsider in the future, especially if we see confusion around the messaging.

**Comment by peppy** [comment]
Also a cool follow-up would be to make mods like this able to display special HUD elements, such as details of the accuracy cutoff. Something like a new HUD component "Mod Details" which can be placed by the user, but contains details provided by any number of active mods.

**Review by peppy — APPROVED** [review]

**Pull request merged**
