### PR TITLE
Make last control point not able to make an implicit segment

### LINKED ISSUE #12286: Red slider tail anchor only emulates one anchor
**Describe the bug:** When importing maps made in stable editor, a red slider tail anchor is interpreted as only one anchor instead of two. This doesn't seem to affect gameplay, but it makes some sliders look weird without it.

**Screenshots or videos showing encountered issue:** 

image

image

**osu!lazer version:** 2021.331.0

**Logs:**
[runtime.log](https://github.com/ppy/osu/files/6253915/runtime.log)
[database.log](https://github.com/ppy/osu/files/6253916/database.log)
[performance.log](https://github.com/ppy/osu/files/6253917/performance.log)
[network.log](https://github.com/ppy/osu/files/6253918/network.log)

### PR DESCRIPTION
**Pull request by smoogipoo**
Fixes https://github.com/ppy/osu/issues/12286

One thing that could be discussed is whether this should be applied only to the final segment, or to any segment. I've chosen the second due to simplicity but doing the first is only a matter of adding a `bool`. I don't know the correct answer to this especially because it's a lazer-only feature, so if anyone has any thoughts do shout them out.  For comparison:

All segments (this branch):
all-segments
Only last segment:
only-last-segment
I.e. In this case the implicit segment is guaranteed to be linear.

Top 10000 SR changes: https://docs.google.com/spreadsheets/d/1u4ciPa183CR4HYqEYSydo1CjEpfg5QM3eU0jLgLsctQ/edit?usp=sharing

/b/81974 shows another case of this:
| bad | good |
| --- | --- |
| bad | good |

I confirmed this beatmap now also matches osu-stable via conversion mappings.

### CODE REVIEW

**Comment by smoogipoo** [comment]
Side note: I'll need to refactor this code again at some point - it's very messy. Please try to look past that for now...

**Comment by peppy** [comment]
Bit confused about the first scenario you mention (whether it should only apply to the last point or not). To clarify, this only applies to conversions from stable, right? In which case, should we not be making that decision based on whether any beatmaps are affected by this?

**Comment by smoogipoo** [comment]
Stable's case is a slider string that looks like: `B|1:1|2:2|3:3|3:3|4:4|5:5|5:5`
In this case, the fix is only to make that last `5:5` point not a new segment.

The lazer case is a slider string that looks like: `B|1:1|2:2|3:3|3:3|B|4:4|5:5|5:5`
You can imagine that second `B` being any path type, so it's technically two completely different sliders attached together. In this case, what I've done is applied the fix to both "segments" so that there's no implicit segment in either.

**Comment by bdach** [comment]
I'd tend to agree with doing it for all segments to reduce edgecaseness, if I'm understanding the issue correctly.

**Comment by peppy** [comment]
I'm still not 100% on understanding this. Does it change the potential UX in the editor if the user clicks in the same place twice or otherwise?

**Comment by peppy** [comment]
From what I can see, it's very hard to create the extra node in lazer at the same location as the next segment. But making this change means, from what I can gather, than on saving and loading in the lazer editor, sliders are going to change in shape in such cases. I'm not sure that's how we want to leave things?

One argument to make is that this is in the legacy conversion code so would, in theory, not affect the lazer editor in the near future. If you can confirm that's the path forward here then I'm fine with that.

**Comment by peppy** [comment]
That said, I'm still not understanding the sliders in your first two screenshots in this PR. I don't understand where the extra "new segment" is coming from and why it's disappearing in one of the two cases.

**Comment by peppy** [comment]
As discussed in voice, let's go with this as-is. The above issues only exist because we are using the legacy encoder in the editor, which (hopefully) won't always be the case. Once that is changed, this logic will no longer be applied to lazer edited beatmaps, as a user would expect.

**Review by peppy — APPROVED** [review]

**Pull request merged**
