### PR TITLE
Don't update SubTreeMasking in `OsuPlayfield`

### PR DESCRIPTION
**Pull request by EVAST9919**
This pr helps in cases when there are many objects present on the screen (mostly low AR) and barely has effect in "normal" gameplay.
`UpdateSubTreeMasking` is used to compute `IsMaskedAway` property which is used to determine whether we should not draw objects outside the container with masking enabled, however this operation is quite expensive. And in this particular case it's a waste of resources because there's no scenario in which anything on the playfield will be masked away (or I can't think of any except may be some maps in which circles fully are outside the playfield, but these are super rare most likely).

Centipede with ar0 was used in this example:
|master|pr|
|---|---|
|master|pr|

Normal "partial" masking isn't affected as seen here:
|master|pr|
|---|---|
|master|pr|

### CODE REVIEW

**Comment by peppy** [comment]
I think this is a pretty good optimisation, but I'd want confirmation from at leat one other person that this is not overstepping what consumer code should be doing, and not going to potentially break in some future renderer changes.

To me it looks like we *should* be able to do this, so I'd hope that we can allow this change.

**Review by peppy — DISMISSED** [review]

**Comment by EVAST9919** [comment]
> which could probably be removed with this change:
> 
> https://github.com/ppy/osu/blob/1fb19e712922871adca31db706afd27ebb0a247f/osu.Game/Rulesets/Objects/Drawables/DrawableHitObject.cs#L635

But this pr aims only for osu! for now and removing this will affect other rulesets?

**Comment by peppy** [comment]
Can confirm that we can remove the local optimisation from `DrawableHitObject` with this in place.

One may wonder whether we should be avoiding doing masking calculations in a lot more places (ie. anything which isn't a scroll view).

**Comment by peppy** [comment]
> But this pr aims only for osu! for now and removing this will affect other rulesets?

Sure, I guess that's somewhat good reasoning to leave it in place.

**Comment by smoogipoo** [comment]
Renderer will be unaffected by this.

I'm quite concerned that you're getting such a big difference in performance. This should be a fairly lean step, containing only rectangle intersections (and validations of `ScreenSpaceDrawQuad` that would happen at some point later on anyway).

But okay, if those results can be verified then I can't say no. I'm not particularly attached to this.

> One may wonder whether we should be avoiding doing masking calculations in a lot more places (ie. anything which isn't a scroll view).

Certainly something to consider, especially if the performance difference elsewhere is as drastic.

**Comment by peppy** [comment]
As a data point, even without the AR0 application that evast did, I was seeing a reduction in frame time of up to 50% while paused in centipede.

**Review by smoogipoo — DISMISSED** [review]

**Comment by peppy** [comment]
I think this change is revealing another test failure which has been intermittent until now (but is pretty consistent now) in `TestAllSamplesStopDuringSeek`, will investigate before merging.

**Review by tooruu — APPROVED** [review]

**Review by peppy — APPROVED** [review]

**Pull request merged**
