### PR TITLE
Implementing a proper fail scene

### LINKED ISSUE #3361: Add a fade-out animation before the fail menu
In the standard osu!, there's a small animation where all the circles fall to the bottom of the screen before the fail menu appears (retry/exit).

In osu!lazer the fail menu appears without any animation. I find that quite distracting, as I don't have any time to realize what happened, as the menu appears all of a sudden, without a warning (except for the HP bar, of course). It also makes it easier to accidentally click on an option after failing. 

In my opinion, some sort of animation, whether it's a simple fade-out or falling circles, should be added into the game, at least as an optional graphics setting.

### PR DESCRIPTION
**Pull request by frenzibyte**
### **#4640**

### CODE REVIEW

**Comment by iiSaLMaN** [comment]
[Video Preview](https://cdn-b-east.streamable.com/video/mp4/obbgy.mp4?token=dt0xOtoqi6L--hQzSPI62Q&expires=1555563995), Thanks to @Poyo-SSB

**Comment by LovelyA72** [comment]
Do we still want to keep the same design of fall off pitch down?

**Comment by iiSaLMaN** [comment]
Well, if there's any other good ideas that i'm capable of then tell me

**Comment by iiSaLMaN** [comment]
Closed due to issue with my fork, will be recreated

**Comment by peppy** [comment]
Can you explain the issue?

**Comment by iiSaLMaN** [comment]
It's not related to coding or anything, i was just using the base branch for this pull request so i couldn't make another branch for the SH and XH grading pull request

**Pull request closed without merging**
