### PR TITLE
Add GitHub actions workflow

### LINKED ISSUE #12641: Migrate Lazer to GitHub Actions
To maintain consistency between projects, it might be a good idea to also port Lazer to Actions. This would be similar to https://github.com/ppy/osu-framework/issues/4288, though there would be some changes needed to fit better on Lazer as the project builds differently from Framework.

### PR DESCRIPTION
**Pull request by smoogipoo**
Closes https://github.com/ppy/osu/issues/12641

Prereq:

- [x] https://github.com/ppy/osu/pull/13500

Mostly the same as the osu-framework workflows, with minor differences as to which sln/projects/namings.

Test run seen here: https://github.com/smoogipoo/osu/pull/22/checks

### CODE REVIEW

**Comment by bdach** [comment]
The other test failure (related to #12094 / beatmap recommender) should be probably dealt with before this goes in, but I can't actually reproduce without blind trial & error and it's a bit difficult to see where the nullref is coming from there...

**Comment by smoogipoo** [comment]
@peppy Are you able to test the failure above? It looks to be macOS only.

https://github.com/smoogipoo/osu/pull/22/checks?check_run_id=2829956199

**Comment by peppy** [comment]
> @peppy Are you able to test the failure above? It looks to be macOS only.
> 
> https://github.com/smoogipoo/osu/pull/22/checks?check_run_id=2829956199

Just to confirm, the only failures that required testing are fixed via https://github.com/ppy/osu/pull/13511, correct?

**Review by peppy — APPROVED** [review]

**Comment by smoogipoo** [comment]
Correct.

**Pull request merged**
