### PR TITLE
Change clicking source/tags on song select to filter instead of searching online

### PR DESCRIPTION
**Pull request by frenzibyte**
As mentioned in https://github.com/ppy/osu/discussions/18959#discussioncomment-3060746, clicking on source/tags in song select should filter by the selected term, rather than searching online.

Didn't overthink the implementation of this too much, as I don't believe it'll live much longer.

---

https://user-images.githubusercontent.com/22781491/179146189-89c8053d-c4e0-4af5-bb16-aa269a993f94.mp4

### CODE REVIEW

**Comment by peppy** [comment]
Any reason you aren't changing the search text using the same method as in other places?

https://github.com/ppy/osu/blob/e1b434b5dc3b685dc55b2d806fa8fb72fd852ee7/osu.Game/Screens/Select/NoResultsPlaceholder.cs#L148

**Comment by frenzibyte** [comment]
As in accessing the search textbox directly via `SongSelect.FilterControl.SearchTextBox` is not a good move? Wasn't sure if defining a method at `SongSelect` or creating a `LinkAction` for song select filtering is worth the effort.

**Comment by peppy** [comment]
I'd want to be able to arbitrarily modify the `FilterCriteria` externally, optimally.

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
I've exposed just the `BindableString` as proposed, otherwise seems fine 👍 .

**Pull request merged**
