### PR TITLE
Remove unused bass.dll from android project

### PR DESCRIPTION
**Pull request by miterosan**
~~This PR deduplicates most of the android related properties.~~

bass.dll is unused and not included in the apk.
(content is ignored)

### CODE REVIEW

**Comment by peppy** [comment]
Have you made sure all this works with Visual Studio / Visual Studio for Mac? I know previously I tried moving things to props but it was not aware, which meant if you ever tried to make changes in the GUI they would be silently ignored (and never take effect).

**Comment by miterosan** [comment]
I cannot test this against visual studio for mac.

Visual studio 2019 does not complain / touch the files as long you do not use the gui based settings tabs "Android Options" and "Build"

**Comment by peppy** [comment]
Yes, can you try changing those settings and see if they work? If they don't, then we should probably *not* use props (because in the past I haven't realised and spent hours wondering why things don't work).

**Comment by miterosan** [comment]
Setting anything in the gui overrides (propertyoverride) the 'default' from props

**Comment by miterosan** [comment]
But you can not see the defaults in the gui of course

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
Are you sure this isn't used by the windows emulator with an x86 image? Seems like it would be (unless it's sourcing from NativeLibs correctly?)

**Comment by miterosan** [comment]
It is not included in the final apk.

I confirmed that everything still works by running it in both emulator and on my phone.

**Pull request merged**
