### PR TITLE
Implement skinnable mod display

### PR DESCRIPTION
**Pull request by Tom94**
Addresses https://github.com/ppy/osu/discussions/30596

Also makes the mod display initialization sequence (start expanded, then unexpand) controlled by HUDOverlay rather than mod display itself. This enabled different treatment depending on whether the mod display is viewed in the skin editor or in the player.

### CODE REVIEW

**Comment by peppy** [comment]
Hmm, something looks to have changed here behaviour wise. During local gameplay, the mods now stay visible through the whole play whereas they used to fade away after a second or two.

**Review by peppy — COMMENTED** [review]
As commented.

**Comment by bdach** [comment]
> During local gameplay, the mods now stay visible through the whole play whereas they used to fade away after a second or two.

Should be fixed with https://github.com/ppy/osu/pull/30993/commits/772ac2d3261595d1b23e97661f091ac41829bb88.

**Comment by peppy** [comment]
My remaining concerns are that there is now going to be a doubled-up mod display when in replay mode, and during the start of gameplay. I guess the fully "correct" way to implement this would be to migrate that element to the "break" or "intro" layer of the skinning system, which we don't have prepared just yet.

@bdach I guess you're okay with this being the case for now? I'm pretty indifferent as by default a user is not inconvenienced by this. It's just an oddity if you have added this new element.

---

A more important concern for me is that this looks weird in the skin editor when viewing with no mods:

osu! 2024-12-20 at 05 11 01

This would be an amicable fix for me:

```diff
diff --git a/osu.Game/Screens/Play/HUD/ModDisplay.cs b/osu.Game/Screens/Play/HUD/ModDisplay.cs
index 417ce355a5..e0b149191a 100644
--- a/osu.Game/Screens/Play/HUD/ModDisplay.cs
+++ b/osu.Game/Screens/Play/HUD/ModDisplay.cs
@@ -22,6 +22,8 @@ namespace osu.Game.Screens.Play.HUD
     /// </summary>
     public partial class ModDisplay : CompositeDrawable, IHasCurrentValue<IReadOnlyList<Mod>>
     {
+        public const float INITIAL_SCALE = 0.6f;
+
         private ExpansionMode expansionMode = ExpansionMode.ExpandOnHover;
 
         public ExpansionMode ExpansionMode
@@ -72,6 +74,7 @@ public ModDisplay(bool showExtendedInformation = true)
             this.showExtendedInformation = showExtendedInformation;
 
             AutoSizeAxes = Axes.Both;
+            Scale = new Vector2(INITIAL_SCALE);
 
             InternalChild = iconsContainer = new ReverseChildIDFillFlowContainer<ModIcon>
             {
@@ -93,7 +96,7 @@ private void updateDisplay(ValueChangedEvent<IReadOnlyList<Mod>> mods)
             iconsContainer.Clear();
 
             foreach (Mod mod in mods.NewValue.AsOrdered())
-                iconsContainer.Add(new ModIcon(mod, showExtendedInformation: showExtendedInformation) { Scale = new Vector2(0.6f) });
+                iconsContainer.Add(new ModIcon(mod, showExtendedInformation: showExtendedInformation));
         }
 
         private void updateExpansionMode(double duration = 500)
diff --git a/osu.Game/Screens/Play/HUD/SkinnableModDisplay.cs b/osu.Game/Screens/Play/HUD/SkinnableModDisplay.cs
index 819484e8ba..cfcc5c8163 100644
--- a/osu.Game/Screens/Play/HUD/SkinnableModDisplay.cs
+++ b/osu.Game/Screens/Play/HUD/SkinnableModDisplay.cs
@@ -10,6 +10,8 @@
 using osu.Game.Rulesets.Mods;
 using osu.Game.Skinning;
 using osu.Game.Localisation.SkinComponents;
+using osu.Game.Rulesets.UI;
+using osuTK;
 
 namespace osu.Game.Screens.Play.HUD
 {
@@ -32,7 +34,13 @@ public partial class SkinnableModDisplay : CompositeDrawable, ISerialisableDrawa
         [BackgroundDependencyLoader]
         private void load()
         {
-            InternalChild = modDisplay = new ModDisplay();
+            InternalChildren = new Drawable[]
+            {
+                // Provide a minimum autosize.
+                new Container { Size = ModIcon.MOD_ICON_SIZE * ModDisplay.INITIAL_SCALE },
+                modDisplay = new ModDisplay(),
+            };
+
             modDisplay.Current = mods;
             AutoSizeAxes = Axes.Both;
         }

```

**Review by peppy — COMMENTED** [review]
As commented.

**Comment by bdach** [comment]
> My remaining concerns are that there is now going to be a doubled-up mod display when in replay mode, and during the start of gameplay. I guess the fully "correct" way to implement this would be to migrate that element to the "break" or "intro" layer of the skinning system, which we don't have prepared just yet.
> 
> @bdach I guess you're okay with this being the case for now? I'm pretty indifferent as by default a user is not inconvenienced by this. It's just an oddity if you have added this new element.

As you said, I'm not sure how I would resolve this right now. There are no tools to do this, and I don't want to make any changes to skinning systems since I see that as "your turf" so to speak.

> A more important concern for me is that this looks weird in the skin editor when viewing with no mods:
> (...)
> This would be an amicable fix for me:

Applied, although I had to back out the part that pulled up the scale application to a higher level, since it broke the mod display on the footer which has scale applied to it directly:

https://github.com/ppy/osu/blob/767be9d0d680b46c3c016256492b742b6ea86087/osu.Game/Screens/Select/FooterButtonMods.cs#L47-L54

**Review by peppy — APPROVED** [review]

**Pull request merged**
