### PR TITLE
Add looping animation to slider reverse arrows

### LINKED ISSUE #7374: Add bounce animation to reverse arrow
Reverse arrow is bouncing to the beat in the stable version, so I think it should be doing so in osu!lazer as well. Maybe add an settings toggle to deal with this?
Personally I am used to seeing the reverse arrow bouncing and the animation makes maps a little easier to read for me.

### PR DESCRIPTION
**Pull request by Wieku**
Fixes #7374

I'm not sure about changing the animDuration. On very fast repeating sliders (like in The Big Black) previous values caused arrows to disappear almost instantly.

### CODE REVIEW

**Review by frenzibyte — CHANGES_REQUESTED** [review]
Have you checked `BeatSyncedContainer`, will make this code pretty much simple.

**Comment by Wieku** [comment]
Originally reverse arrows don't use slider timing point BPM but they pulse at constant 200BPM.

**Comment by Wieku** [comment]
If I remember there were arguments about having reverse arrows pulsing with the song or at constant 200bpm, some people wanted to have pulse disabled. So maybe we can add two checkboxes to settings called `Enable slider reverse arrow pulse` and `Match arrow pulse to beatmap bpm`? I want to hear more voices about that.

**Comment by peppy** [comment]
Settings and configuration for animations will come in the future as a skin drawable level setting. Implement a sane default to begin with.

**Comment by Wieku** [comment]
Yeah, I removed the settings and kept repeat points synced to timing points. The only one concern I have with this is that inheriting `BeatSyncedContainer` causes repeat point to eat 1Kb memory more.

**Comment by smoogipoo** [comment]
don't worry about memory consumption.

**Comment by peppy** [comment]
I've added some changes to make the animation occur more frequently (to closer match stable but still beatsync).

**Review by peppy — DISMISSED** [review]

**Comment by peppy** [comment]
I've also removed some of the extra complexity of the animation you had (it was unnecessary and incorrectly animating in the case of the `Math.Min` - just let it play as it is).

**Review by peppy — DISMISSED** [review]

**Comment by Wieku** [comment]
That complexity was added to have reverse arrow smoothly scale to it's original size as slider ball gets close and to allow it to normally scale up to `1.5` after being hit. Without that check reverse arrow could scale up to `1.95`. That `if (Clock.CurrentTime < repeatPoint.StartTime)` check was added after some testing on my side.

**Comment by Wieku** [comment]
I made a comparison:
* [How it looked before changes](https://streamable.com/omuq5)
* [How it looks now](https://streamable.com/2dql1)
* [How it looks when I change `timingPoint.BeatLength` to `TimeUntilNextBeat`](https://streamable.com/zr9o0)
* [Previous one, but we keep time and limiting clauses](https://streamable.com/0kaw9)

**Comment by peppy** [comment]
The reverse arrow *should* scale up to 1.95. In lazer each sprite, object animation has a purpose. One should not change to make another look better. If we decide it doesn't look good, we should be changing the actual animation, not stopping it at a certain arbitrary time.

I think it looks fine.

**Review by smoogipoo — DISMISSED** [review]

**Review by smoogipoo — APPROVED** [review]

**Comment by Wieku** [comment]
In the 3rd video you can see that during some fade outs random reverse arrows suddenly get really big and I think it doesn't look well. It's visible during gameplay and probably players gonna report it as a glitch (that's why I mentioned I added those checks after playing for some time, it was looking way better and more responsive).

**Comment by peppy** [comment]
It's normal. The reverse arrow is moving; the hitobject is exploded; they are additive.

**Comment by Wieku** [comment]
After some more testing it is visible on slower maps. So we can leave it like that. But I think at least we should change `timingPoint.BeatLength` to `TimeUntilNextBeat` to have smoother animation.

**Comment by peppy** [comment]
You don't want `TimeUntilNextBeat` but rather the final beatlength. If you use `TimeUntilNextBeat` and the game was to apply the transform at 50ms to the next beat it would do a full scale in 50ms, looking very unnatural.

**Comment by Wieku** [comment]
Right, I forgot about that. So move `double beatLength` as a protected property or just sum `TimeUntilNextBeat` with `TimeSinceLastBeat` because the sum of this too is basically the final beatlength?

**Comment by peppy** [comment]
I'd probably expose that in `BeatSyncedContainer`, but I'd rather that was done separately (the scope of changes on that class is already too large for this PR). If you do add it, it'd be nice to have test coverage of divisor and other untested pieces of `BeatSyncedContainer` too.

**Pull request merged**
