### PR TITLE
Fix osu!catch scrolling speed

### PR DESCRIPTION
**Pull request by Hanamuke**
Scrolling speed now only depends on AR. It uses the same preempt as osu! (and stable)

### CODE REVIEW

**Comment by Hanamuke** [comment]
1) The git diff is completely drunk, sorry about that
2) I made measurements and it seems OK. It's failry safe to say that the default lazer scrolling speed is the same as stable AR5

**Comment by smoogipoo** [comment]
I think a better way to do this is to make a new `ConstantSpeedVisualiser` that implements `ISpeedChangeVisualiser` and does a linear interpolation. Then add a config setting for it (`SpeedChangeVisualisationMethod`) and add it to `ScrollingHitObjectContainer`.

From there the idea is to set `ScrollingPlayfield.VisibleTimeRange` to the AR-dependent value that matches stable.

Eventually the setting should be at a per-ruleset level, with each ruleset providing its own default, and we can move it as such in a future PR.

This should allow other rulesets to use constant + adjustable speed.

**Comment by Hanamuke** [comment]
I trust this should be what you had in mind. As a side effect, users can chose to play osu!catch with something other than constant speed, or choose to play osu!taiko with constant speed (for instance). This is not conform to stable, but i guess that it can always be changed later.

**Comment by peppy** [comment]
Yes, this looks about right. Please hold off on merging while I have a think about this one. We may want to disallow constant in certain modes (under the policy of not adding new features in lazer we may take away at a later point).

**Comment by smoogipoo** [comment]
We'll definitely want to disallow constant (and just changing the scrolling in general) in certain modes _for ranking_. But when that happens the following must happen:

1. Scrolling type must be a per-ruleset setting.
2. "Disabled" scrolling modes should be allowable via an unranked mod.

There are cases in which people want to disable speed changes even in mania/taiko, but it should be a "just for fun" thing.

**Comment by peppy** [comment]
I'd argue that should be a mod implementation rather than a ruleset/global setting. No settings should cause a ruleset to become 'unranked'.

**Comment by smoogipoo** [comment]
I never said a setting should cause the ruleset to become unranked. I said the setting should be moved to a mod when we need to consider it being unranked.

**Comment by peppy** [comment]
Ah yep, misread. That sounds fine.

As discussed, we should probably just remove this dropdown right now as there's no way for it to work well for all rulesets we have implemented. Best to just hardcode the `VisualisationMethod` per ruleset for the time being.

**Comment by Hanamuke** [comment]
Sounds good, but it should probably be implemented as automatic control points, and be unrelated to visualisation imho

**Comment by peppy** [comment]
It could still be available in the editor. We're talking specifically about global gameplay settings.

**Comment by Hanamuke** [comment]
So, I removed the scrolling visualisation from the settings. Maybe some things can be changed, such as moving SpeedChangeVisualisationMethod.cs to the ruleset level (scrolling? Configuration). Maybe using a bindable would be better than my implementation too. I could also prepare another patch that allows other scrolling modes than he native one as unranked fun mods.

**Review by smoogipoo — APPROVED** [review]
Good stuff 👍

**Review by smoogipoo — CHANGES_REQUESTED** [review]

**Review by smoogipoo — APPROVED** [review]
It's hard to test this because the proportions don't match, but this does match stable's calculations regarding scroll speed, so let's do it 👍

**Pull request merged**
