### PR TITLE
Remove non-overlapping velocity buff from Aim in osu!

### PR DESCRIPTION
**Pull request by apollo-dw**
This change aims to significantly reduce the severity of the recent abuse case for the velocity change bonus. [The abuse case in question is a ranked map called Zan'ei](https://osu.ppy.sh/beatmapsets/1759729#osu/3601629), which features jump patterning that the aim system rewards too high of a bonus to.

The change literally just removes the "non-overlapping" part of the bonus. It's worth mentioning that the jumps still recieve a bonus through `distRatio`, however it is now significantly smaller. Some maps which deserved the buff are unfortunately nerfed such as Trance Dance Anarchy [Don't Look Back] and Wizard's Tower [Occultist], but it's currently not feasible to fix the algorithm in such a way where Zan'ei is nerfed and those remain buffed: it'd require a full rewrite to the velocity change algorithm and (I suspect) to angle bonus algorithms. You can consider this a step so that things keep working for now 😅 

[Zan'ei map leaderboard with this change](https://i.imgur.com/B0HvLhS.png)

---

SR/PP changes sheet: https://docs.google.com/spreadsheets/d/1nsUnS9zIWCHiH-SRyvs2NV_d6pRzIQqDH4z__0XSq7g/edit

As of https://github.com/ppy/osu/pull/19004/commits/7ab75606a1b51e24a27b931e1d80d6f5452e02a3

### CODE REVIEW

**Review by stanriders — DISMISSED** [review]
I'm fine with this since it barely affects any maps, but has great potential for abuse

**Comment by smoogipoo** [comment]
SR/PP changes sheet added to description.

**Comment by smoogipoo** [comment]
Awaiting two approvals before merge on this one.

**Review by emu1337 — DISMISSED** [review]

**Review by smoogipoo — APPROVED** [review]

**Comment by Leclowndu93150** [comment]
nah it is good like that

**Pull request merged**
