### PR TITLE
Allow the buttons of MenuOverlay to be pressed with keys

### PR DESCRIPTION
**Pull request by marco-stephan**
Imitates osu!stable's behavior

### CODE REVIEW

**Comment by peppy** [comment]
This doesn't sound right.

Gameplay keys should either only work in gameplay, or they should work globally at an InputManager level. This shouldn't be implemented in a specific component.

**Comment by peppy** [comment]
This is still not right. Exiting and selecting a button are different actions completely. Exiting doesn't trigger the selected button.

**Comment by MrTheMake** [comment]
Would it be better if the button's corresponding action is directly assigned to ExitAction instead of triggering the button?

**Comment by peppy** [comment]
i don’t get it

why not just close this PR and carry on?

let exiting be a default glass bal to the game everything else implemented locally

**Comment by MrTheMake** [comment]
Ok, closing

**Pull request closed without merging**
