### PR TITLE
#5390's fix

### PR DESCRIPTION
**Pull request by QingQiz**
The method is to split beatmap set and merge adjacent betamap sets with the same ID after sorting

Since this method modifies the logic of root carousel, the unit tests are adjusted accordingly

[This](https://github.com/ppy/osu/compare/master...QingQiz:osu:master#diff-437bd878785b8f4f58e4aca38024be5bb60f6a2c16567504c50ccddcbcedc7edR855-R899) is the test of the issue mentioned by #5390 (use star rating instead of length)

### CODE REVIEW

**Comment by peppy** [comment]
Please read the contribution guide. Do not PR from master. Do not PR multiple fixes on a single PR.

**Comment by QingQiz** [comment]
Do you mean the solution does not meed the osu lazer's expectation?

**Comment by bdach** [comment]
Correct, it does not. Please talk to us about direction first before PRing any code. Especially as a new contributor.

**Comment by peppy** [comment]
I'll give you a few pointers since you seemingly did put quite a bit of effort into this:

- Please look at other PRs to get an idea for how we format commit messages and pull request titles
- Please read the contribution guidelines https://github.com/ppy/osu/blob/master/CONTRIBUTING.md. For instance, you have PR'd this from a `master` branch which is frowned upon.
- Don't create new acronyms like `bm` in your variable names – we have never used this elsewhere in the project.

And then on this particular change, I'm not sure where to begin but I'll summarise why I'm not willing to consider this proposed method:
- We already have ongoing work being done to update the song select design to new design language (see https://www.figma.com/file/DXKwqZhD5yyb1igc3mKo1P/Song-Select-Draft-2?node-id=0%3A1). This includes a new display mode for single difficulties.
- The logic you've added increases complexity of an already complex system, to the point I can't follow what's going on anymore. If anything, the carousel needs to be simplified rather than complicated further.
- Going forward, we intend to move more of the carousel pagination and display to relying on lazy loading from realm. This change is likely not compatible with that direction (at very least it will make migrating to it more complicated)
- You are creating a beatmap set panel per difficulty then throwing away most. This is not going to be good for performance and allocations.

Also in brief testing I've noticed at least one issue:

https://user-images.githubusercontent.com/191335/178893590-f0d09986-8c2c-4d41-b1b0-9b3ba8a884b5.mp4

Good job getting it working to the point you did, but unfortunately I cannot see this being merged.

**Comment by QingQiz** [comment]
Thanks for your reply, hope we can see the new design implemented soon

**Pull request closed without merging**
