### PR TITLE
Add padding to the bottom of the beatmap listing overlay to avoid hovered panels exceeding visible bounds

### LINKED ISSUE #16120: Beatmap card difficulty dropdown isn't visible when at the bottom of beatmap listing
### Discussed in https://github.com/ppy/osu/discussions/16119

<div type='discussions-op-text'>

<sup>Originally posted by **Sinamer** December 16, 2021</sup>
When you search for specific beatmaps and the amount of items is limited, difficulty dropdown of a beatmap card is covered by the end of page.

https://user-images.githubusercontent.com/53346335/146408971-8b1987e4-5794-4a89-b95a-da133a1b364e.mp4

</div>

### PR DESCRIPTION
**Pull request by peppy**
Closes https://github.com/ppy/osu/issues/16120.

Not sure about the `400` height specification here, seems too tall for the dropdown? I get that this probably follows what osu-web is doing, but still unsure it needs to ever be that tall.. would propose we reduce to around 200 as part of this PR?

### CODE REVIEW

**Comment by bdach** [comment]
Web is actually doing `height: 40vh;` or similar iirc, which means "40% of available client height" translating to lazer. I didn't replicate that strictly as it was pretty finicky and felt unnecessary.

No immediate strong opinion about reducing to 200, I'd have to go and see how many difficulties it would display without a scroll.

**Comment by peppy** [comment]
Right. Not so easy to match in lazer currently.

We can just go with this as-is if you'd prefer, I don't feel too strongly about the height change.

**Comment by bdach** [comment]
I've removed a stray blank line and applied the same to the spotlights rankings view, as that has cards that could potentially suffer from the same:

osu_2022-01-03_18-42-44

I've also checked out what the dropdown in height reduction to 200 would look like, and the dropdown will still fit ~10 difficulties before adding scrolling, which seems enough:

2022-01-03-184518_584x419_scrot

I'll leave the decision of whether or not to reduce the height to you but I'm not against it.

**Review by bdach — DISMISSED** [review]

**Comment by peppy** [comment]
Let's go with 200, it looks better in terms of padding (400 feels slightly too much).

**Review by bdach — APPROVED** [review]

**Pull request merged**
