### PR TITLE
Fix import testcases randomly failing

### PR DESCRIPTION
**Pull request by peppy**
Temporary workaround for https://github.com/aspnet/EntityFrameworkCore/issues/9994.
Also adds more transactional logic and centralises transaction commits to the context.

### CODE REVIEW

**Review by smoogipoo — DISMISSED** [review]

**Comment by smoogipoo** [comment]
What's the state of this? Is this ready to merge?

**Comment by peppy** [comment]
I'm honestly not sure if the underlying issue is even fixed. Will need to run this on CI another 20 times.

**Comment by peppy** [comment]
Might as well merge this for now; will revisit fixing context stuff in the near future.

**Comment by smoogipoo** [comment]
Merge even though the thread sleep stuff isn't working? This isn't going to achieve its original purpose without that :(

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
