### PR TITLE
Add support for legacy skin "cursormiddle" display

### PR DESCRIPTION
**Pull request by peppy**
- [x] Depends on https://github.com/ppy/osu/pull/5462
- [x] Depends on https://github.com/ppy/osu/pull/5421

### CODE REVIEW

**Review by smoogipoo — APPROVED** [review]

**Comment by Morilli** [comment]
Hm, when testing with my skin it seemed that the ingame cursor is smaller than it is on master (the size is correct on master)

**Comment by peppy** [comment]
Please ensure you haven't customised the size settings. We've tested across multiple skins and it seems to be correct here.

**Comment by Morilli** [comment]
I haven't changed any settings; the cursor size is set to 1x. I just changed from master to this branch. See attached screenshots for the size difference.
Base Profile Screenshot 2019 07 30 - 17 07 14 33
Base Profile Screenshot 2019 07 30 - 17 07 56 47

**Comment by peppy** [comment]
Could you compare to stable at precisely the same screen size? Make sure your gamefield/ui scale is all default on lazer.

**Comment by Morilli** [comment]
I have all settings related to scaling (UI scaling, screen scaling) on their default value in lazer. I'm using 1920x1080 full screen resolution in all cases. Here is how it looks on stable:
osu! Screenshot 2019 07 30 - 17 17 44 95

**Comment by peppy** [comment]
Can you open an issue for this, and provide your skin elements (`cursor@2x` and `cursormiddle@2x` at least)? We're still figuring out the scaling of this element, so I'm going to merge this as-is and we will fix the size regression in a future PR.

**Comment by Morilli** [comment]
Sure, will do.

**Pull request merged**
