### PR TITLE
Add easing to osu! hit object fade in

### LINKED ISSUE #5770: Slider head and slider body uneven fade in opacity
**Describe the bug:** 
The slider head does not fade in with the same opacity as sliderbody
**Screenshots or videos showing encountered issue:** 
[https://streamable.com/jcl40](url)
**osu!lazer version:** 
2019.814.0

### PR DESCRIPTION
**Pull request by frenzibyte**
Closes #5770

### CODE REVIEW

**Comment by peppy** [comment]
What is this based on?

**Comment by iiSaLMaN** [comment]
> What is this based on?

I'm not sure what you mean..?

**Comment by peppy** [comment]
How are you finding that this is the correct value for easing? Have you done frame-by-frame comparisons? Are you referring to a wiki?

**Comment by iiSaLMaN** [comment]
> How are you finding that this is the correct value for easing? Have you done frame-by-frame comparisons? Are you referring to a wiki?

I hope I can do frame-by-frame comparisons but it seems impossible with my current computer, 
I was gonna ask if BLuR can do comparisons to see if my PR makes it 1:1 to stable, should've linked the branch instead...

**Comment by peppy** [comment]
You can't just guess at these values. I know for a fact this is 100% incorrect. There is no easting on hitobject fade in.

**Comment by BLuRTuts** [comment]
If there is no easing the only thing I can think of is just a simple delay. If so then you'll probably have to look for the problem in the code. I could try upping the fps of the recording and finding a time value but that will be a janky solution.

**Comment by peppy** [comment]
The original issue points out a potential discrepancy between sliders and hitcircles. You've changed the duration universally. I'm not sure how this works.

**Comment by iiSaLMaN** [comment]
Will close this as an incorrect solution.

**Pull request closed without merging**
