### PR TITLE
Allow failing with "relax" and "autopilot" mods

### PR DESCRIPTION
**Pull request by rushiiMachine**
Addresses https://github.com/ppy/osu/discussions/13229 

I have changed the Relax mod to allow the player to fail, and as a result removing the NF/PF/SD mod exclusions with Relax. A significant portion of players that play on Relax-specific private servers use some sort of osu! stable patcher that does the same thing as this PR since, as an example, it's frustrating when trying to grind an SS with Relax. I don't see why Relax should essentially be bundled with NoFail as that should be enableable separately.

Additionally, while not covered in the discussion post linked above, Autopilot falls into the same category here and I think it should be addressed in the same way as Relax.

---

A significant portion of players that play primarily using relax mod have asked for the ability to compile relax with other mods, such as "perfect". This wasn't possible until now as relax blocked failing.

This change allows both "relax" and "autopilot" mods to fail, and as a result allows combining "no fail", "perfect" and "sudden death" with them.

If you're a relax player and want to keep the mod as relaxing as you remember it to, you can make a mod preset with RX+NF!

### CODE REVIEW

**Comment by smoogipoo** [comment]
I think historically the reason for keeping this was that it's for "relaxing play" or something like that. But to be honest, I would be okay with having it be allowed to fail... @peppy thoughts?

**Comment by peppy** [comment]
Sounds fine to me.

**Review by peppy — APPROVED** [review]

**Comment by bdach** [comment]
Uh well this is headed towards merge much faster than I'd expect it to?

What are the implications of merging this on stable? Is stable relax also going to get changed too, or is this a "don't care about stable" sort of merge?

**Comment by Ratchet0203** [comment]
Does this make RX/AP compatible with Accuracy Challenge as well? If not, I think it should.

**Comment by bdach** [comment]
> Does this make RX/AP compatible with Accuracy Challenge as well? If not, I think it should.

yes it will / does

**Comment by peppy** [comment]
> Uh well this is headed towards merge much faster than I'd expect it to?
> 
> What are the implications of merging this on stable? Is stable relax also going to get changed too, or is this a "don't care about stable" sort of merge?

don't care too much. apparently replays are already broken (as in they don't work), so it's going to need future consideration.



> Does this make RX/AP compatible with Accuracy Challenge as well? If not, I think it should.

yes

**Comment by rushiiMachine** [comment]
> What are the implications of merging this on stable? Is stable relax also going to get changed too, or is this a "don't care about stable" sort of merge?

Doing this on stable would be great as well, given it's unranked on stable not a lot of changes would be needed either

**Comment by smoogipoo** [comment]
It is not going to happen on stable.

**Pull request merged**
