### PR TITLE
Fix incorrect keyboard navigation order in score panel list 

### LINKED ISSUE #14665: Score panels are not correctly ordered if you scroll using the directional arrows
**Describe the bug:** As title. You can check this with any beatmap ranking.
In the example below, I've always pressed only the left arrow on the keyboard.

**Screenshots or videos showing encountered issue:** 

leaderboard

**osu!lazer version:** `2021.907.0`

### PR DESCRIPTION
**Pull request by bdach**
Closes #14665.

Solution is a little LINQ-y, but so was the previous code, and the new code should be *pretty much* comparably LINQ-y, so may be fine...?

### CODE REVIEW

**Comment by bdach** [comment]
The test failure is, uh... not encouraging, but I have no idea where it came from, either. In response to it I've stressed the test for 1k runs locally in single-thread mode and saw no failures.

**Comment by peppy** [comment]
A bit ominous that a newly added test would fail like that.. I can't immediately see how that could happen (or reproduce) but I'm going to leave this running overnight to try and get something.

**Comment by bdach** [comment]
Curiously I spotted a panel-related test failure [on another, unrelated workflow run](https://github.com/ppy/osu/pull/14682/checks?check_run_id=3546627803). Maybe this is some sort of freak accident which was triggered by something else entirely (like the recent changes in headless test runner)?

**Comment by peppy** [comment]
it's probably something incorrect in the test scene outside of your changes, yeah.

also didn't repro in many runs overnight

**Comment by peppy** [comment]
Going to get this in as-is. We can deal with the test failure if/when it appears again.

**Review by peppy — APPROVED** [review]

**Pull request merged**
