### PR TITLE
Add ability to hide a whole beatmapset from song select

### PR DESCRIPTION
**Pull request by nihodi**
Might want to add something similar to a `BeatmapDeleteDialog` to prevent accidental hides.

### CODE REVIEW

**Comment by bdach** [comment]
I guess this stems from the discussion in #20636? Still probably would have been better to ask directly if this is wanted first before PRing.

I'm not sure this is wanted/needed given that there are now two "destructive" options presented to the user that differ very subtly from each other. I'm personally leaning that this shouldn't be a thing.

**Comment by nihodi** [comment]
As for the reason I have not asked directly is because I took this as a sort of "training" to become more familiar with the lazer code-base as I am interested in contributing further. Since it was basically complete, I thought I'd just submit a PR and see if there was any further interest.

Yeah, having two different "destructive" actions that nearly do the same thing can be confusing, but on the other hand, it makes sense to be able to easily hide a beatmapset if it is possible to hide a single beatmap.

**Comment by peppy** [comment]
How do you unhide? I don't understand.

**Comment by bdach** [comment]
Only method available right now would be to unhide everything via the maintenance options.

**Comment by peppy** [comment]
The idea behind hiding was to allow hiding individual difficulties (as a replacement for deleting them), not full beatmap sets.

Maybe I can get behind it if a filter to show all hidden beatmaps is first added, as proposed.

**Comment by nihodi** [comment]
Yep, might've jumped the gun a little. I think I'll close for now, and maybe it could be revisited in the future?

**Pull request closed without merging**
