### PR TITLE
Fix flashlight position in taiko

### LINKED ISSUE #19460: Flashlight position may be misplaced after in-game restart
### Type

Game behaviour

### Bug description

When you initiate a restart in game (also with sudden death or perfect) the flashlight custom size setting is not taken into account.
This happens only in osu!taiko.

### Screenshots or videos

osu_2022-07-29_15-59-51
custom flashlight size

osu_2022-07-29_16-00-14
first playthrough looks fine

osu_2022-07-29_16-00-21
after quick restart it breaks

### Version

2022.723.0-lazer

### Logs

[database.log](https://github.com/ppy/osu/files/9220582/database.log)
[performance.log](https://github.com/ppy/osu/files/9220583/performance.log)
[network.log](https://github.com/ppy/osu/files/9220584/network.log)
[runtime.log](https://github.com/ppy/osu/files/9220585/runtime.log)

### PR DESCRIPTION
**Pull request by naipofo**
fixes #19460

### CODE REVIEW

**Comment by frenzibyte** [comment]
Please provide a brief description of the solution and how you ended up with it, as I have absolutely no idea how `DrawInfo` invalidation has anything to do with restarting gameplay, without having to dig deep and finding out the reason behind it.

**Comment by naipofo** [comment]
From what i understand, the padding calculated at https://github.com/ppy/osu/blob/27ec8f3ae61bc7be4733defc67cfe21f86fdf316/osu.Game.Rulesets.Taiko/UI/TaikoPlayfield.cs#L217 does not get applied to the flashlight after a restart, so it ends up too close to the left edge. Making `flashlightProperties` invalidate on `DrawInfo` triggers the invalidation after the padding is calculated and applied to `HitTarget`, used by `TaikoModFlashlight` to position the flashlight.

**Comment by frenzibyte** [comment]
Please never ever open PRs from your master branch (see [contributing guidelines](https://github.com/ppy/osu/blob/f79d749feafb1386b17e3b3e01a3e68d2a2fc77c/CONTRIBUTING.md)). Also the fork name is not supposed to be different from the original repo name.

**Comment by frenzibyte** [comment]
Uh, sorry about this. @naipofo can you please open another PR with a topic branch rather than `master`.

**Pull request closed without merging**
