### PR TITLE
Lighten playfield during breaks

### LINKED ISSUE #2502: Background stays dimmed during break times
This feature was just changed (on 100% dim) on stable to match lazer's current behaviour, which is to keep the background dim the same during gameplay and break time. I would argue that one of the few times you actually see the background is during break times and thus there should be an option to show the background during them.

I don't know what the general consensus around this issue is as I have not heard any player mention that the background should stay dimmed (even if it's set to 100% or something)

### PR DESCRIPTION
**Pull request by ocboogie**
Resolves #2502
https://youtu.be/-XPmcYJuhR0

I could make a setting if you guys think that's a good idea.

### CODE REVIEW

**Comment by LittleEndu** [comment]
For it to match osu stable (which is the end goal) the toggle setting is a requirement

**Comment by ocboogie** [comment]
Alright I'll add that and fix the bugs making the tests crash

**Comment by ocboogie** [comment]
Alright should be ready to merge.
https://youtu.be/eelT6-h-jeE
I could also add this setting to the Visual Settings panel. [This](https://i.imgur.com/O1qGiAa.png). But I personally don't think that's necessary. It's a setting most people will only change once. We don't want to shove it in people's faces.

**Comment by peppy** [comment]
This should probably read "Lighten playfield during breaks" and have the polarity reversed. I think it reads a bit better.

**Comment by ocboogie** [comment]
That makes sense. I couldn't come up with anything good. That's what I was looking for.

**Comment by peppy** [comment]
Why..?

**Comment by ocboogie** [comment]
Wait no

**Comment by ocboogie** [comment]
I made a new pull request with the better name. And I will change the naming in the code.

**Pull request closed without merging**
