### PR TITLE
Fix traceable sliders incorrectly being opaque

### LINKED ISSUE #14449: Traceable's slider bodies look weird
**Describe the bug:** Traceable's slider body is opaque, this has been happening in recent versions, only with legacy skins (lazer default looks okay). Probably since that slide body colour fix.

**Screenshots or videos showing encountered issue:**
some random version back in may
image

latest version
image

**osu!lazer version:** 2021.820.0-lazer

### PR DESCRIPTION
**Pull request by peppy**
Closes https://github.com/ppy/osu/issues/14449.
Regressed in https://github.com/ppy/osu/pull/14205.

### CODE REVIEW

**Comment by frenzibyte** [comment]
Test coverage would be best to have given that this is a regression caused indirectly.

**Comment by peppy** [comment]
I'm not sure what kind of coverage would be warranted here

**Comment by frenzibyte** [comment]
A `ModTestScene` that confirms all hitobjects (in both default and default legacy skin) are properly hidden, by checking the opacity of the relevant pieces. I can look at writing one just to make sure such regression never occurs.

**Comment by peppy** [comment]
The issue here was the accent colour of the hit object. Unless you just want a test reading back the accent colour to make sure it's set correctly (which would have failed anyway due to the use of `new` in that regression PR), I don't know how/what to guard against.

**Comment by frenzibyte** [comment]
Right... I would've thought checking `AccentColour` is enough but didn't realize the `new` in there.

**Review by frenzibyte — DISMISSED** [review]

**Review by bdach — CHANGES_REQUESTED** [review]
see above

**Review by bdach — APPROVED** [review]

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
