### PR TITLE
Implement detection for touch devices

### PR DESCRIPTION
**Pull request by o-dasher**
Naive implementation of touch device detection. This aims to provide at least the TD mod when submitting a score. It does not work for skin elements such as the PP counter.
The reason for this being implemented at least as is, is because multiple scores are being sent to the Lazer servers without being properly flagged as TD, so it would be better for new scores as of now to be properly flagged.

### CODE REVIEW

**Comment by peppy** [comment]
Thanks for your PR.

I would have preferred a discussion thread before such a large PR was created, as this may not align with our forward direction.

A few notes without reading the diff:

- In lazer we have better ways of detecting touch, such as checking input handlers and device specs, so I'm not sure this kind of method should be used in the first place. Using a basic detection method like this may be unwanted, depending on how we intend to judge touch.
- I'd much rather the touch mod, if it remains a mod, is applied automatically game-wide so it's visible at song select etc. (and potentially has touch specific options, like increasing the size of circles for smaller devices)
- Lazer leaderboards still have a reset clause, so there's no real issue with scores not being marked

I'll leave this open to simmer, but I don't foresee it having priority in my own review queue.

**Comment by o-dasher** [comment]
> - In lazer we have better ways of detecting touch, such as checking input handlers and device specs, so I'm not sure this kind of method should be used in the first place. Using a basic detection method like this may be unwanted, depending on how we intend to judge touch.
I think this method deals great with all cases. Also i forgot to mention this aims to be a better implementation of something i did a while ago. https://github.com/ppy/osu/pull/20137 and it also accounts for computers that may send input trough mouse events rather than the normal touch input as smoogi mentioned before.
> - I'd much rather the touch mod, if it remains a mod, is applied automatically game-wide so it's visible at song select etc. (and potentially has touch specific options, like increasing the size of circles for smaller devices)
This also seems like a great way to go around this. Although this would also need further discussion 😅

**Comment by frenzibyte** [comment]
I've marked this PR as draft for now as it's pending further discussion on correct direction.

**Comment by o-dasher** [comment]
This should be fixed with https://github.com/ppy/osu/pull/25348.

**Pull request closed without merging**
