### PR TITLE
Fix compiling Xamarin projects in VS2017

### PR DESCRIPTION
**Pull request by ticotaco72**
fixes for now #5392 but this is kinda bad solution i think so issue shuold exist until fixed at xamarin and system.threading.tasks.extentions side

note that this nuget package shouldn't be updated until it's resolved in other way

could be resolved too by referencing dll not nuget i think

and adds some warnings about downgrading the package

https://stackoverflow.com/questions/52747838/xamarin-can-not-resolve-reference-system-threading-tasks-extensions-referen

https://github.com/dotnet/corefx/issues/29585

### CODE REVIEW

**Comment by ticotaco72** [comment]
added the same for ios cause i saw that there's `_._` too but don't know if it's necessary

**Comment by peppy** [comment]
Please add a comment in the .props files linking to the issue and mentioning it's a workaround.

**Comment by peppy** [comment]
The linked corefx issue is already resolved and released in a build we are using. Why is this not fixed?

**Comment by ticotaco72** [comment]
@peppy ok, i have some searching and there's it
in latests nuget packages for `System.Threading.Tasks.Extensions` there's facade file `_._` that's provided to xamarin android instead of dll while building. xamarin is supposed to give in its own implementation, and that was done with this commit
https://github.com/xamarin/xamarin-android/commit/bf2b59ce6ea13640668dd6385ef287938d2628d7
but it isn't included in latest xamarin version for vs 2015 which is 9.1.7.0; it's included in vs 2019 version though

further reading:
https://github.com/xamarin/xamarin-android/issues/2466
https://github.com/mono/mono/issues/10142
https://github.com/mono/mono/pull/9968
https://github.com/xamarin/xamarin-android/pull/2450
https://github.com/xamarin/xamarin-android/commit/0ea0725c2e9ca86b665ed49dfef0e0146251f7f9

**Comment by ticotaco72** [comment]
the issue is that we use new package but not new xamarin because it's not much possible in vs 2019

**Comment by peppy** [comment]
I see. This is *specifically* for vs2017?

Is there any reason you can't upgrade to the latest?

**Comment by ticotaco72** [comment]
Yes, this is specifically for vs2017.

Probably I could upgrade but I didn't need it before, so I didn't upgrade, because it takes time and disk space. Will see if it is option. Anyway vs2017 isn't that old, and many people still use it, so we should support it I think.

If this is merged it can be reverted once (probably) next version of vs2017 is deployed

**Comment by ticotaco72** [comment]
No issues using vs2019 but still not closing because Vs 2017 can be used as a fallback

**Comment by YoDevil** [comment]
> I see. This is _specifically_ for vs2017?
> 
> Is there any reason you can't upgrade to the latest?

Yes this is only an issue for vs2017.
Reason why *i* cannot upgrade to vs2019 is because Android deployment is broken ( #5410 )

**Comment by peppy** [comment]
Have you confirmed this is needed for iOS compilation too?

**Comment by ticotaco72** [comment]
idk, i can't check this because i deleted vs2017 and anyway i'm not on mac nor have iphone;

from what i read it should work without this workaround on vs2017 15.9.14; could someone confirm?

**Comment by ticotaco72** [comment]
resolved conflicts

**Comment by peppy** [comment]
If you deleted vs2017 is it safe to say this fix is no longer needed for you? If so, we'll likely just close this PR.

**Comment by ticotaco72** [comment]
there's new version vs 2017 so maybe fix is included in it, if not than moving to vs 2019 seems as a best option

**Comment by ticotaco72** [comment]
won't delete branch for while if someone would still use vs 2017

**Comment by MappingSteve** [comment]
Confirming this is still an issue for me on vs 2017. I'll probably migrate to 2019, but IMHO 2017 should still be supported for others.

Details:
VS Enterprise 2017, Versi
on 15.9.15
Xamarin - 4.12.3.83
Xamarin.Android SDK - 9.1.7.0
Xamarin.Forms 4.2.0.709249
-- includes --
System.Reactive 4.1.6
System.Threading.Tasks.Extensions 4.5.3


Resulting error building for Android:

Can not resolve reference: `System.Threading.Tasks.Extensions`, referenced by `System.Reactive`. Please add a NuGet package or assembly reference for `System.Threading.Tasks.Extensions`, or remove the reference to `System.Reactive`.	LiveCaddie.Droid		

If remove System.Reactive nuget, and rebuild, the build is successful.

**Comment by MappingSteve** [comment]
I've confirmed that rebuilding, in VS 2019, the project described in my previous comment - succeeds.

Details:
VS Community 2019, Version 16.2.3
Xamarin - 16.2.0.95
Xamarin.Android SDK - 9.4.1.0

These are unchanged:
System.Reactive 4.1.6
System.Threading.Tasks.Extensions 4.5.3

**Pull request closed without merging**
