### PR TITLE
Edit mods description and multiplier

### LINKED ISSUE #2108: HalfTime/Daycore multipliers were changed
HalfTime and Daycore multipliers are swapped from 0.30x to 0.50x on all modes instead mania. Mania from 0.50x to 0.30x. From this PR #883.

### PR DESCRIPTION
**Pull request by Joehuu**
Resolves #2108 if it wasn't supposed to be edited. Made code better, and fixed hard rock on all modes. Added period at the end of some descriptions to make it consistent. Don't know if adding "text" to that file edits the titles of the mods. Edit new descriptions if bad. I might not get all the errors on code and modifications, so correct me.
And last question, do all unranked mods have 0.00x multiplier?

### CODE REVIEW

**Comment by jacksonisiah** [comment]
> And last question, do all unranked mods have 0.00x multiplier?

yes.

**Comment by jorolf** [comment]
But wouldn't that mean that the score will always show 0 for unranked mods? :neutral_face:

**Comment by Frontear** [comment]
@jorolf If I'm not mistaken, lazer only gives score for the hit window value, and doesn't multiply by the combo. That should result in no score. Unlike in old osu, where the combo would increase the score (combo * hitwindow value), new osu ignores combo when deciding score. Will this be changed, or is intentional?

**Comment by Joehuu** [comment]
Going to close this and will do it the right way next time.

**Pull request closed without merging**
