### PR TITLE
Fix `Player` potentially running `MakeCurrent` when already removed from the screen stack

### LINKED ISSUE #12919: Hold-for-menu button may crash when pressing exit key if it's masked away
**Describe the bug:** Moving bottom anchor progress bar cause key stroke and back button move. If back button go out of screen, press back is not possible (quick retry then back still work.)

If trying to move item back after failed attempt to back. The game crash.

**Screenshots or videos showing encountered issue:** 

https://user-images.githubusercontent.com/7066150/119265770-0daff280-bc12-11eb-8f35-5801699821ba.mp4

**osu!lazer version:** 2021.523.0

**Logs:**
[database.log](https://github.com/ppy/osu/files/6528294/database.log)
[network.log](https://github.com/ppy/osu/files/6528295/network.log)
[performance.log](https://github.com/ppy/osu/files/6528296/performance.log)
[performance-audio.log](https://github.com/ppy/osu/files/6528297/performance-audio.log)
[performance-draw.log](https://github.com/ppy/osu/files/6528298/performance-draw.log)
[performance-update.log](https://github.com/ppy/osu/files/6528299/performance-update.log)
[runtime.log](https://github.com/ppy/osu/files/6528300/runtime.log)
[updater.log](https://github.com/ppy/osu/files/6528301/updater.log)

### PR DESCRIPTION
**Pull request by peppy**
Closes #12919.

Is pretty race-y so not sure figuring out a test setup is worthwhile.

### CODE REVIEW

**Comment by smoogipoo** [comment]
I don't understand what this is fixing, can you explain how this occurs? Isn't this potentially going to fail on anything further, such as the `this.Exit()` call?

**Comment by peppy** [comment]
See the attached issue for what this is attempting to fix. Will double check the case you mention; seems awfully bad that it doesn't trigger any test failures if it's actually an issue.

**Comment by peppy** [comment]
Ah, no, this is correct logic. The code block there is an early escape in the case the screen is *already* not current. It's the case where the game has already started proceeding to the results screen (or is already there).

**Comment by smoogipoo** [comment]
It took me 30 reads to understand the issue - I thought it was something else. As far as I understand, the issue is that exit doesn't get called if the button is masked away? In the video the user presses escape 20 times and nothing happens.

But isn't this the incorrect solution to that anyway, as opposed to making sure the button is _never_ masked away?

Also, this isn't fixing the crash anyway - move the button offscreen, then press escape many times, then move the button back into view and it crashes as before.

**Comment by peppy** [comment]
How does it crash with this fix applied? Does the child screen still return non-null?

I've already fixed the button getting masked in #12921; this was just intended to be a safety addition.

**Comment by smoogipoo** [comment]
> Does the child screen still return non-null

There is no child screen. That's the thing - this is fixing an issue that isn't documented anywhere, neither in the linked issue nor in any test. I'm not saying there isn't an issue, but it's not the linked one that's for sure.

As you said, the primary fix is #12921, but there could still be an issue here - it just isn't tested or anything anywhere.

**Comment by peppy** [comment]
Are we looking at different things here?

Game returns to song select:
```csharp
2021-05-23 14:48:08 [verbose]: Screen changed ← PlaySongSelect
```

`PerformExit` is called and crashes:
```csharp
2021-05-23 14:48:08 [error]: An unhandled error has occurred.
2021-05-23 14:48:08 [error]: osu.Framework.Screens.ScreenStack+ScreenNotInStackException: Cannot perform MakeCurrent on a screen not in a ScreenStack.
2021-05-23 14:48:08 [error]: at osu.Framework.Screens.ScreenStack.MakeCurrent(IScreen target)
2021-05-23 14:48:08 [error]: at osu.Framework.Screens.ScreenExtensions.MakeCurrent(IScreen screen)
2021-05-23 14:48:08 [error]: at osu.Game.Screens.Play.Player.PerformExit(Boolean showDialogFirst)
2021-05-23 14:48:08 [error]: at osu.Game.Screens.Play.Player.<createOverlayComponents>b__91_0(
```

**Comment by smoogipoo** [comment]
Again, this doesn't fix that. Please try it, I gave a repro in my comment above: https://github.com/ppy/osu/pull/12922#issuecomment-846766210

**Comment by peppy** [comment]
Right, so the added check needs to go inside and early return, rather than being part of the outer conditional?

**Comment by smoogipoo** [comment]
I don't know what the fix is, or whether this is appropriate, or whether the appropriate solution is to make sure that the button is never masked away as I mentioned above.

All I know is this doesn't fix it, and here's `GetChildScreen()` at the call site:
image
(i.e. the `PlayerLoader` from the runtime.log you missed)

**Comment by peppy** [comment]
That is the most dangerous implementation i've ever seen. How is this a thing??

**Comment by smoogipoo** [comment]
This might be a framework issue with `GetChildScreen()` returning the wrong value here.

**Review by smoogipoo — APPROVED** [review]

**Comment by peppy** [comment]
Let me bump framework here; we're still on `524`.

**Comment by smoogipoo** [comment]
524 is enough: https://github.com/ppy/osu-framework/commit/e993f15536ae219c5fbd2dcec73ff04ae237aae2, but sure

**Comment by peppy** [comment]
Ah go ahead then

**Pull request merged**
