### PR TITLE
Make hitcircle number skinnable using skin.ini

### PR DESCRIPTION
**Pull request by Dragicafit**
Adds HitboxNumberFont in skin.ini (Fonts) to make skin for number skinnable
Works in the same way as ComboColours and AccentColour
Default is Venera
Does not work if the beatmap has a skin integrated (same issue as combo colours)

- one answer to #3455

### CODE REVIEW

**Comment by peppy** [comment]
- Where does the term "hitbox" come from? We don't use it anywhere.
- Have you actually tested this? There's no way it could work. Skin fonts aren't being loaded or handled.

**Comment by Dragicafit** [comment]
- I wanted to use hitcircle number instead of hitbox number (my bad).
- This works :

skin.ini :
[Fonts]
HitboxNumberFont: Arial

produces :
with skin
default :
without skin

**Comment by peppy** [comment]
That's not Arial. It's just falling back to the default framework font. lazer/o-f uses a bitmap font system and will not read from your system fonts.

**Comment by Dragicafit** [comment]
Ah.
I don't know if it could work but I will try something like : 
Add a font.fnt in the skin folder;
Fonts.AddStore(new GlyphStore(Resources, "the font file in the skin")); somewhere

**Pull request closed without merging**
