### PR TITLE
Fix test failures due to logger pollution

### PR DESCRIPTION
**Pull request by peppy**
As seen at https://github.com/ppy/osu/pull/13831/checks?check_run_id=3025050307. I can't confirm that this will fix the issue but it looks like the only plausible reason. I have confirmed that the logging is not coming from the local (first logging is guaranteed to be after `SetupForRun`).

### CODE REVIEW

**Comment by peppy** [comment]
Amazingly this [failed](https://ci.appveyor.com/project/peppy/osu/builds/39925408) on the exact case I was trying to fix. I'm not sure how this is happening any more, but safe to say this fix alone is not enough. Open to any ideas.

**Comment by peppy** [comment]
Never mind, found some seriously bad code causing this.

**Comment by peppy** [comment]
Last commit was incorrectly pushed to `master`, if there's any issue with it can be undone in review of this PR. Should be pretty obvious what was going on either way.

**Review by bdach — APPROVED** [review]
makes sense

**Pull request merged**
