### PR TITLE
Reduce argon Taiko kiai flashing

### PR DESCRIPTION
**Pull request by Xinnoh**
https://github.com/ppy/osu/issues/21569

I tried taiko and found kiai to be unplayable due to flashing, cut brightness from 0.3 to 0.15 and it was much better.

The videos don't show how bad the issue was. It was really bad with high note density + the rest of the screen being dark, https://github.com/ppy/osu/issues/21569 has a better showcase

Old
https://github.com/ppy/osu/assets/30382015/ac57138e-32de-42d5-9f3c-bd3408c1be7b

new
https://github.com/ppy/osu/assets/30382015/15656b87-2f7e-49f4-a63b-2af75118e236

### CODE REVIEW

**Comment by peppy** [comment]
I don't think the impact is there anymore. I'll have a play with the tween settings and intensity.

**Comment by Xinnoh** [comment]
If it gets moved to a lower priority task or would need more work to fully implement, I'd still suggest just implementing this in some form for the time being.
When choosing between having a low impact kiai or giving players migraines, personally I'd prefer the former. My head legit hurt for a bit after testing the values.

**Comment by peppy** [comment]
You can change skins or use a self compilation in the mean time ;)

**Comment by peppy** [comment]
In my comment above I misunderstood where this was being applied. It actually looks fine, so let's go with it.

**Review by peppy — APPROVED** [review]

**Pull request merged**
