### PR TITLE
Add chat /join command

### PR DESCRIPTION
**Pull request by hbnrmx**
adds part of #5595

If possible I would like to keep `/j` around though.

### CODE REVIEW

**Comment by peppy** [comment]
please provide a use case for this. channels are stored server-side now so this should be seldom used enough that typing three characters less is not a beneficial saving.

**Comment by hbnrmx** [comment]
Users who use `/j` in stable won't have to relearn this behaviour.
It's not as ambiguous as with the `/p` because you have to specify another argument.
It doesn't produce any extra effort.

**Comment by smoogipoo** [comment]
I would like to see `/j` removed also. It should be very seldom used (along with `/p`) with the new chat system and persistence, as previously stated.

We may reconsider at a later point when more people use lazer.

**Comment by hbnrmx** [comment]
Alright, thanks for considering it. Removed for now.

**Review by peppy — APPROVED** [review]

**Pull request merged**
