### PR TITLE
Fix filenames containing japanese not being read correctly

### LINKED ISSUE #28010: Video does not play if the file name of the background video is in non-Ascii characters
### Type

Game behaviour

### Bug description

If the file name is in Japanese or other language, the background video will not play.

### Screenshots or videos

https://github.com/ppy/osu/assets/75152752/ab20d31d-645d-468b-8102-812c72798f33

### Version

2024.412.1

### Logs

[logs.zip](https://github.com/ppy/osu/files/15138334/logs.zip)

### PR DESCRIPTION
**Pull request by peppy**
After far too much time investigating this, the encoding situation is not great right now.

- Stable [sets the "default code page"](https://github.com/peppy/osu-stable-reference/blob/c29ebd7fc52113013fb4ac2db230699d81e1fe2c/osu!/GameBase.cs#L3099) to be used for encoding filenames to Shift-JIS (932):
- Lazer does nothing (therefore using UTF-8).

When importing to lazer, stable files are assumed to be UTF-8. This means that the linked beatmaps don't work correctly. Forcing lazer to decompress *and* compress using Shift-JIS will fix this.

Here's a rough idea of how things look for japanese character filenames in current `master`:

| | stable | lazer |
|--------|--------|--------|
| export encoding | shift-jis | utf8 |
| utf8 [bit flag](https://superuser.com/a/1507988) set | ❌ | ❌ |
| import stable export osz | ✅  | ❌ |
| import lazer export osz | ❌ | ✅ |
| windows unzip | ❌ | ❌ |
| macos unzip | ✅ | ✅ |

and after this change

| | stable | lazer |
|--------|--------|--------|
| export encoding | shift-jis | shift-jis |
| utf8 [bit flag](https://superuser.com/a/1507988) set | ❌ | ✅ (for `.olz`) |
| import stable export osz | ✅  | ✅ |
| import lazer export osz | ✅ | ✅ |
| windows unzip | ❌ | ✅ (for `.olz`) |
| macos unzip | ✅ | ✅ |

A future endeavour to improve compatibility would be to look at setting the utf8 flag in lazer, switching the default to utf8, and ensuring the stable supports this flag (I don't believe it does right now).

Closes https://github.com/ppy/osu/issues/28010

### CODE REVIEW

**Comment by bdach** [comment]
> Stable sets the \"default code page\" to be used for encoding filenames to Shift-JIS (932)

dear lord 🙈🙈🙈🙈

**Comment by peppy** [comment]
Yeah, that's about where I am.

I spent too long making this work and I'm not 100% sure we should be supporting this (instead looking to fix stable and commit to using the UTF8 flag instead). Depending on reception of this PR I can look at doing that, but it's probably going to be a bit of a mess to make that work on stable's end.

Also while the beatmaps in the issue were mostly graveyarded, it seems like this will be an issue for some ranked beatmaps too, so getting things working as a first step might be okay..

2024-04-30 09 31 03@2x

**Comment by bdach** [comment]
Okay so before I go too far into reviewing this here's my loose thoughts...

My vague feelings are such that:
- stable should not be touched at all because any attempt to do so is probably going to Break Things Horribly
- however we should really be aiming to use utf-8 going forward because it just works for everything.

Which I guess would make it so that I could be fine with using shift jis so long as it is constrained to actual legacy paths. For beatmaps that's sorta doable (export `.osz`s using shift jis, export `.olz`s using utf-8). Not sure about skins, but given lazer skins have things that stable can't read I'd be probably ok with exporting `.osk`s using utf-8 too.

So I guess the proposal would be to:
- export `.osz`s using shift jis
- export `.olz`s and `.osk`s using utf-8
- when importing, try utf-8 first always and then fall back to shift jis on failure

How's that sounding? Do you think it's worth the hassle? Because there is a possible world where we just switch to the shift jis thing for now and only revisit this again when redoing beatmap/skin formats entirely (no idea when that's gonna be a thing that's happening).

**Comment by peppy** [comment]
Yeah that sounds fine. I'll see if SharpCompress supports the UTF-8 bit flag. If it does we can start setting that for non-legacy exports and likely call it a day.

**Comment by peppy** [comment]
Well it looks like it should work, but it doesn't. Stepping into libraries isn't possible on .NET anymore () so I can't check this easily, but..

```diff
diff --git a/osu.Game/Database/BeatmapExporter.cs b/osu.Game/Database/BeatmapExporter.cs
index f37c57dea5..01ef09d3d7 100644
--- a/osu.Game/Database/BeatmapExporter.cs
+++ b/osu.Game/Database/BeatmapExporter.cs
@@ -17,6 +17,8 @@ public BeatmapExporter(Storage storage)
         {
         }
 
+        protected override bool UseFixedEncoding => false;
+
         protected override string FileExtension => @".olz";
     }
 }
diff --git a/osu.Game/Database/LegacyArchiveExporter.cs b/osu.Game/Database/LegacyArchiveExporter.cs
index 1d9d252220..30c76bd20f 100644
--- a/osu.Game/Database/LegacyArchiveExporter.cs
+++ b/osu.Game/Database/LegacyArchiveExporter.cs
@@ -23,6 +23,11 @@ namespace osu.Game.Database
     public abstract class LegacyArchiveExporter<TModel> : LegacyExporter<TModel>
         where TModel : RealmObject, IHasNamedFiles, IHasGuidPrimaryKey
     {
+        /// <summary>
+        /// Whether to always use Shift-JIS encoding for archive filenames (like osu!stable did).
+        /// </summary>
+        protected virtual bool UseFixedEncoding => true;
+
         protected LegacyArchiveExporter(Storage storage)
             : base(storage)
         {
@@ -32,7 +37,7 @@ public override void ExportToStream(TModel model, Stream outputStream, ProgressN
         {
             using (var writer = new ZipWriter(outputStream, new ZipWriterOptions(CompressionType.Deflate)
                    {
-                       ArchiveEncoding = ZipArchiveReader.DEFAULT_ENCODING
+                       ArchiveEncoding = UseFixedEncoding ? ZipArchiveReader.DEFAULT_ENCODING : new ArchiveEncoding()
                    }))
             {
                 int i = 0;

```

osz path: succeeds
osl path: fails (filenames get destroyed on export-import)

2024-04-30 20 16 20@2x

This SHOULD work due to the `Efs` flag taking precedence on import (and therefore not using the custom code page), but isn't for some reason.

https://github.com/adamhathcock/sharpcompress/blob/6fc4b045fde70c42df738d203c453082354e9558/src/SharpCompress/Common/Zip/Headers/LocalEntryHeader.cs#L34

https://github.com/adamhathcock/sharpcompress/blob/6fc4b045fde70c42df738d203c453082354e9558/src/SharpCompress/Writers/Zip/ZipWriter.cs#L175

**Comment by bdach** [comment]
It doesn't work because...

- `new ArchiveEncoding()` [uses `Encoding.Default`](https://github.com/adamhathcock/sharpcompress/blob/ab5535eba365ec8fae58f92d53763ddf2dbf45af/src/SharpCompress/Common/ArchiveEncoding.cs#L29-L30)
- `Encoding.Default` is [this](https://github.com/dotnet/runtime/blob/2ad47cd52ebe57c1b4c2e28f95cc4eed6fcb354d/src/libraries/System.Private.CoreLib/src/System/Text/Encoding.cs#L79-L80). Note the `encoderShouldEmitUTF8Identifier: false`.
- The [equality check you linked](https://github.com/adamhathcock/sharpcompress/blob/6fc4b045fde70c42df738d203c453082354e9558/src/SharpCompress/Writers/Zip/ZipWriter.cs#L175-L177) that determines if the `Efs` flag is set uses `UTF8Encoding.Equals()` which is [this](https://github.com/dotnet/runtime/blob/2ad47cd52ebe57c1b4c2e28f95cc4eed6fcb354d/src/libraries/System.Private.CoreLib/src/System/Text/UTF8Encoding.cs#L879-L884).
- `Encoding.UTF8` has `encoderShouldEmitUTF8Identifier = true` set so the equality check fails due to that flag mismatching. Roll credits.

I can't even, or I don't really want to even. The important thing is that if you do

```diff
diff --git a/osu.Game/Database/LegacyArchiveExporter.cs b/osu.Game/Database/LegacyArchiveExporter.cs
index 30c76bd20f..b0e5304ffd 100644
--- a/osu.Game/Database/LegacyArchiveExporter.cs
+++ b/osu.Game/Database/LegacyArchiveExporter.cs
@@ -3,6 +3,7 @@
 
 using System.IO;
 using System.Linq;
+using System.Text;
 using System.Threading;
 using osu.Framework.Logging;
 using osu.Framework.Platform;
@@ -37,7 +38,7 @@ public override void ExportToStream(TModel model, Stream outputStream, ProgressN
         {
             using (var writer = new ZipWriter(outputStream, new ZipWriterOptions(CompressionType.Deflate)
                    {
-                       ArchiveEncoding = UseFixedEncoding ? ZipArchiveReader.DEFAULT_ENCODING : new ArchiveEncoding()
+                       ArchiveEncoding = UseFixedEncoding ? ZipArchiveReader.DEFAULT_ENCODING : new ArchiveEncoding(Encoding.UTF8, Encoding.UTF8)
                    }))
             {
                 int i = 0;

```

on top of your patch above it _appears_ to work on a quick check.

**Comment by peppy** [comment]
> Encoding.Default is [this](https://github.com/dotnet/runtime/blob/2ad47cd52ebe57c1b4c2e28f95cc4eed6fcb354d/src/libraries/System.Private.CoreLib/src/System/Text/Encoding.cs#L79-L80). Note the encoderShouldEmitUTF8Identifier: false.

Wow, I believe I was looking at a completely different version of this (likely from a different .NET version). 🤯

**Comment by peppy** [comment]
Tested working on windows (native unzip) and lazer round trip 👍

**Comment by bdach** [comment]
Funny thing but in my testing it appears stable doesn't do this completely right either. It does the magic set of the magic encoding static variable in the export path, but not in the _import_ path, so as far as I can tell unless your ambient system encoding is already shift jis, the import will fail to decode the filenames properly. I fixed it locally by setting the magic encoding static variable to the magic shift jis encoding and it seems to work.

**Review by bdach — APPROVED** [review]

**Pull request merged**
