### PR TITLE
Fix storyboard using incorrect path separator

### PR DESCRIPTION
**Pull request by james58899**
fix #1844 cause storyboard broken on windows
because DB use / as separate

### CODE REVIEW

**Review by jimchen5209 — APPROVED** [review]
It fixed successfully on my windows device.

**Comment by smoogipoo** [comment]
This sounds more like a broken OSZ decoder, which seems to use forward-slashes in all cases. I believe we always want to use the system's separator char.

Thoughts, @peppy ?

screen shot 2018-01-24 at 2 59 31 pm

**Comment by peppy** [comment]
We're using forward slashes exclusively internal to the game, currently (see examples: https://github.com/ppy/osu/blob/master/osu.Game.Rulesets.Catch/UI/CatcherArea.cs#L127 https://github.com/ppy/osu/blob/master/osu.Game/Audio/SampleInfo.cs#L22 and many more)

**Comment by smoogipoo** [comment]
But we also discussed using Path.Combine for those cases also...

**Comment by peppy** [comment]
Therefore I believe using forward slashes here is also correct. If it's not reading files correctly in linux then the issue needs to be solved at a lower level.

**Comment by smoogipoo** [comment]
(Discussed IRL) So the way we're going forward is anything internally will use forward-slashes, and they will be converted to backslashes only at the point where filesystem access is done.

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
