### PR TITLE
Fix saving layouts on some stable imported skins failing

### PR DESCRIPTION
**Pull request by peppy**
This completely refactors the wait skin hashing is done. Previous iterations were designed to allow for many different import cases - specifically retaining folder/filename metadata that was expected from stable - but at the end of the day the hashing was incorrect post-import (ie. when attempting to save the skin).

All skin metadata is written out to the `skin.ini` at point of import now, including any naming changes we have made. I opted to not write a full `LegacySkinEncoder` because it's not required yet, and may never be. This is just enough to get us by until we have better systems in place. 

I've also changed the transfer logic to also include the download filename in all cases. Previously this would only be the case for stable imports. I can add that back depending on consensus during review, else I think it's fine to go with this and see what users say, if anything.

Bit of a time sink, but this would have been required to some degree before writing the realm imported (at least the cleaning up of tests).

I haven't added tests for migration, but have tested manually. If testing manually, you may need to remove the migration from the `_EFMigrations` table manually if running more than once (it doesn't automatically get removed when reverting to a previous commit hash).

Closes #15199.

### CODE REVIEW

**Comment by peppy** [comment]
Was a bit of a blind spot as I was selectively only running tests in the skinning scope. I'll look to fix the failures first of all.

**Comment by peppy** [comment]
Turns out you were right. Making this work is a bit hard, and definitely out of scope of this change. I've changed the logic to always use a unique hash in the case of zero-file imports, which should be better than what we previously has.

**Review by bdach — COMMENTED** [review]
As for the source:

**Comment by peppy** [comment]
Actually on second thought, that's also going against the whole point of this PR, which is to provide stable hashing. The `skin.ini` *needs* to exist for every skin.

**Comment by bdach** [comment]
> that's also going against the whole point of this PR

Yeah I had the feeling it would.

So I guess the added `skin.ini` should explicitly specify version `latest`, for one. There's also the question of what to do with modified default skins, because with the way they're set up right now even if you add a `skin.ini` for them, they can't read it because they don't receive the correct resource store to do so in ctor.

Well either that, or check the existence of *either* `skin.ini` or the lazer layout json file. That would cover the modified default skin case I think.

**Review by bdach — COMMENTED** [review]
Seems to not-crash in locally testing a little bit. A few notes but nothing that seems major.

**Review by bdach — DISMISSED** [review]
Looks fine to me, but going to request another once-over because I've seen this diff a fair few times and probably best to get a fresher perspective just in case.

**Review by smoogipoo — APPROVED** [review]
I can't find a way to repro the errors so let's merge

**Pull request merged**
