### PR TITLE
Add ability to quick exit from results screen

### PR DESCRIPTION
**Pull request by peppy**

### CODE REVIEW

**Comment by bdach** [comment]
I guess this works but I do find the fact that "quick" exit takes longer than just a plain back button / <kbd>Esc</kbd> press unless you set activation time to zero?

Was there some reasoning behind that implementation?

**Comment by smoogipoo** [comment]
Fwiw one reason I didn't merge this PR, and what I was hoping @bdach would also pick up on, is that there's a small period of time after the confirmation where the results screen becomes fully visible while transitioning to song select.

So it goes visible -> black screen -> visible -> song select.

Kinda looks jank to me :(

**Comment by Wheisss** [comment]
> I guess this works but I do find the fact that "quick" exit takes longer than just a plain back button / Esc press unless you set activation time to zero rather humorous?
> 
> Was there some reasoning behind that implementation?

Hi, I'm the one who did the suggestion, in all fairness i do have my quick buttons set to instantly activate so yeah, I don't remember  how it behave when a delay is set but since the quick retry already works in the result screen, i do not see why should the quick exit not work in the same way.
 The reasoning for this i did in my [discussion post](https://github.com/ppy/osu/discussions/27919) the day before yesterday.

Cheers

**Comment by peppy** [comment]
> Was there some reasoning behind that implementation?

Mostly to stay in line with the binding being called "Quick exit (hold)" but I agree a hold is not really necessary here so let's remove it.

**Review by Joehuu — APPROVED** [review]

**Comment by smoogipoo** [comment]
Can't the "Back" keybind be bound to a second key instead? I don't understand why it _must_ be quick exit, why we're giving special handling for this keybind.

**Review by bdach — APPROVED** [review]

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
