### PR TITLE
Ensure all mods are incompatible in both ways

### PR DESCRIPTION
**Pull request by tsunyoku**
After https://github.com/ppy/osu/pull/19200 and https://github.com/ppy/osu/pull/19201, it seemed appropriate to add an extra test that all mods are two-way incompatible.

### CODE REVIEW

**Comment by tsunyoku** [comment]
Tests seem to be failing as it finds to find the instance of the mod it's comparing to. The line which is causing it: https://github.com/ppy/osu/pull/19203/files#diff-38c0d7d7fdbeef4006389cbdab55fdb19f0c26c9152d500287ea7e8d91ed7765R39

Kinda unsure why, maybe someone else has an idea?

**Comment by ggliv** [comment]
Mods can declare incompatibility with other mods that may not necessarily be included in the same ruleset. For example, `CatchModHalfTime` inherits incompatibility with `ModAdaptiveSpeed` from `ModRateAdjust` despite the catch ruleset not having an implementation of `ModAdaptiveSpeed`.

I'd suggest that you run the test locally with a debugger attached before pushing more commits to avoid unnecessary CI congestion.

**Comment by peppy** [comment]
> Kinda unsure why, maybe someone else has an idea?

Are you unable to debug this locally? It should be immediately apparent by checking what the fail cases are (this is a 100% failure).

**Comment by peppy** [comment]
As this seemed abandoned I fixed the remaining issue with the test. Looks to work as expected.

**Review by peppy — APPROVED** [review]

**Pull request merged**
