### PR TITLE
Add legacy skin "sliderendcircle" support

### LINKED ISSUE #7206: Display slider end and reverse arrow circle
**Proposal designs of the feature:** Disabled by default. Enabled if skin contains `hitcircle.png`. An option for that may or may not be added.

Very likely dupe & would do it myself.

### PR DESCRIPTION
**Pull request by peppy**
- Closes https://github.com/ppy/osu/issues/7206
- Replaces and closes https://github.com/ppy/osu/pull/7210.
- [x] Depends on #10322.

# Non-repeats

stable:

lazer:

# Repeats

stable:

lazer:

### CODE REVIEW

**Comment by LittleEndu** [comment]
How does this work with hidden?

**Comment by peppy** [comment]
No idea, you'll have to try it.

**Comment by smoogipoo** [comment]
It doesn't work with HD.

**Comment by peppy** [comment]
Is the expected behaviour that they should not be shown at all?

**Comment by smoogipoo** [comment]
Should fade along with the head it looks like.

**Comment by smoogipoo** [comment]
Same thing also happens for repeats - the circle fades out but the arrow stays, which is going to need special handling.

**Comment by peppy** [comment]
I've added hidden support, but haven't visually compared it to ensure 1:1 yet. I *think* it's correct though.

**Review by smoogipoo — APPROVED** [review]
Seems to behave alright

**Pull request merged**
