### PR TITLE
Avoid showing time of play on results screen when autoplay

### LINKED ISSUE #13940: Autoplay and Cinema mod show "1 January 0001" as the play date
**Describe the bug:** As title. Without those mods, score panels show the correct date and time.

**Screenshots or videos showing encountered issue:** 

- Normal score

- With Cinema

- With Autoplay

**osu!lazer version:** `2021.720.0-lazer`

### PR DESCRIPTION
**Pull request by peppy**
Closes https://github.com/ppy/osu/issues/13940.

An alternative to hiding completely would be to show "Played automatically" or some other text, if we want to make it clear why there's no timestamp there. Not sure if required.

Also not sure how much we want to add new nullable values like this. Am open to another approach if that's the case.

No text (current PR status):

With text:

### CODE REVIEW

**Comment by crownys** [comment]
I personally cannot think of scenarios where players would need to see the extra text, especially while using Cinema. However I see no major reason to exclude it other than it being kind of redundant info. If someone else could make a case for its usefulness I probably wouldn't be opposed to it. Right now the current no text seems good to me.

**Comment by peppy** [comment]
In the interest of avoiding null reliance and also breaking EFcore, I've changed this to be based on `default` equality instead.

**Review by bdach — APPROVED** [review]
I think nothing is better. "Played automatically" would arguably be a duplicate piece of information, as the username already indicates autoplay, and the link of default date -> score is automatic is pretty weak anyhow.

Shame about discarding the nullability, but given that it's forced by higher powers such as EF...

**Review by smoogipoo — APPROVED** [review]
lgtm

**Pull request merged**
