### PR TITLE
Make slider ends count for score

### PR DESCRIPTION
**Pull request by Shawdooow**

### CODE REVIEW

**Comment by smoogipoo** [comment]
Instead of this, how about first making the end into an invisible, AlwaysPresent `DrawableHitObject`? It'll basically copy `CheckForJudgements` from `DrawableSliderTick`.

Following that, `Slider.CheckForJudgements` can be changed to do `judgementsCount = NestedHitObjects.Count(h => h.IsHit)`.

**Review by smoogipoo — CHANGES_REQUESTED** [review]
As described, I think this is a more future-proof method.

**Comment by peppy** [comment]
Please improve the title of this PR too. It's very cryptic at the moment.

**Comment by smoogipoo** [comment]
I'm giving this PR one more day for the requested changes to be made, at which point I'll be taking it over.

**Comment by smoogipoo** [comment]
As I mentioned, I don't think this is the proper way to go about this. Please see my referencing PR for a more future-proof method.

**Pull request closed without merging**
