### PR TITLE
Rework playfield scaling/aspect ratio adjustment

### PR DESCRIPTION
**Pull request by smoogipoo**
* `RulesetContainer.PlayfieldArea` doesn't exist anymore.
  * Implemented individually in each playfield via `Size`.
  * Playfield size is (1, 1) (relative) by default.
* `RulesetContainer.GetAspectAdjustedSize()` doesn't exist anymore.
  * Now handled in individual rulesets, via what I call a `PlayfieldLayer`, which will also be used in the editor.
  * In the case of osu! and catch, `PlayfieldLayer` handles both aspect and scaling.
  * In the case of taiko, `PlayfieldLayer` handles aspect.
* `Playfield` now exposes `HitObjectContainer` for derived playfields to add at some point in their hierarchy.
  * No more content overrides.
* `Playfield` is now a `CompositeDrawable`.

Along with https://github.com/smoogipoo/osu/tree/fix-catch-scale, results in the following:

| Beatmap | osu! 1024x768 | osu! 1440x900 | catch 1024x768 | catch 1440x900 |
| --------- | --------------- | --------------- | ---------------- | ---------------- |
| 351188 | tear_rain_1024x768_osu-stable_osu tear_rain_1024x768_osu-lazer_osu | tear_rain_1440x900_osu-stable_osu tear_rain_1440x900_osu-lazer_osu | tear_rain_1024x768_osu-stable_catch tear_rain_1024x768_osu-lazer_catch | tear_rain_1440x900_osu-stable_catch tear_rain_1440x900_osu-lazer-catch
| 1282209 | skyshards_1024x768_osu-stable_osu skyshards_1024x768_osu-lazer_osu | skyshards_1440x900_osu-stable_osu skyshards_1440x900_osu-lazer_osu | skyshards_1024x768_osu-stable_catch skyshards_1024x768_osu-lazer_catch | skyshards_1440x900_osu-stable_catch image

It's not 100% exact, but the remaining differences are related to playfield sizes, no longer due to scale. Exactness wasn't really the point of this PR.

### CODE REVIEW

**Comment by Hanamuke** [comment]
So, i understand i will have to use Size my PR right?

**Comment by smoogipoo** [comment]
Correct

**Comment by smoogipoo** [comment]
For comparison's sake, with this is master @ 1440x900 with the same catcher width as in the screenshots, my motivation for this PR:

osu_2018-09-21_16-10-02

**Comment by peppy** [comment]
I'm not so happy with the `PlayfieldLayer` naming. The term layer is used for the layers inside the playfield, and generally should be used in the case there is more than one related layers in my opinion.

How about `PlayfieldContainer` or `PlayfieldLayerContainer`?

**Comment by smoogipoo** [comment]
Wouldn't you say a PlayfieldContainer is something that contains a playfield? Whereas this is more of a `ContainerContainedByPlayfield`.

**Comment by peppy** [comment]
I dunno, the way we've used `Container` until now doesn't work as you said

- `PauseContainer` doesn't contain a pause.
- `RulesetContainer` doesn't contain a ruleset (just stuff related to the ruleset).
- `PaginatedContainer`, `OverlayContainer` etc.

I'm fine with another name, but don't agree with layer when there's only one layer involved.

**Comment by smoogipoo** [comment]
* `PauseContainer` contains the `PauseOverlay`
* Yes, this was the discussion when we renamed it to `RulesetContainer` - because it "contained" the entire ruleset.
* `PaginatedContainer` is a container that contains items while providing pagination.
* I'll give you `OverlayContainer`.

**Comment by peppy** [comment]
I'm okay with an alternative if you want to separate what "Container" means and rename the other instances. The issue is coming up with a term (strongly against layer unless as i said, there are other adjacent and related layers).

**Comment by smoogipoo** [comment]
The thing is that "layer" in this case ties directly into the editor, where we _do_ have "CreateLayerContainer()`, which is going to return exactly this container.

**Comment by smoogipoo** [comment]
`PlayfieldAdjustmentContainer`?

**Comment by peppy** [comment]
sure

**Review by peppy — APPROVED** [review]

**Pull request merged**
