### PR TITLE
Pp Refactoring: Merged multipliers that do the same thing

### PR DESCRIPTION
**Pull request by Givikap120**
This was made to avoid confusion - "which multiplier I have to change"?
Also, for consistency purposes all multipliers were renamed to `difficulty_multiplier`

### CODE REVIEW

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=taiko

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=catch

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=mania

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=taiko

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=catch

**Comment by smoogipoo** [comment]
!diffcalc
RULESET=mania

**Comment by smoogipoo** [comment]
Looks like a few changes in the catch sheet, albeit on an edge-case map (likely every map has _some_ difference small enough to not appear in the sheet).

Speaking of, how were the catch changes calculated out?

**Comment by Givikap120** [comment]
> Looks like a few changes in the catch sheet, albeit on an edge-case map (likely every map has _some_ difference small enough to not appear in the sheet).
> 
> Speaking of, how were the catch changes calculated out?

It's very weird that it had any change, because I checked #1 player profile - and he had 0 difference on all maps
what is expected because it had 900 skill multiplier
then sqrt(900) = 30
and 0.153 * 30 = 4.59

**Comment by Givikap120** [comment]
looking on this - I think it's 100% floating point moment
image

**Comment by Givikap120** [comment]
Also, this score is indeed 232pp, not 231pp as sheet claims
image

**Comment by smoogipoo** [comment]
Doesn't sqrt(900) assume there are only 900 strains?

**Comment by Givikap120** [comment]
> Doesn't sqrt(900) assume there are only 900 strains?

of course not
900 is just multiplier to strain
the number of strains have nothing to do with it

**Review by smoogipoo — APPROVED** [review]

**Pull request merged**
