### PR TITLE
Change `OnlineID` to non-nullable to allow for indexing in Realm

### PR DESCRIPTION
**Pull request by peppy**
The actual data migration is not required as we haven't had any clients actually loading data (just a version bump would be enough to appease realm), but I've added it just to give an example of how it should be done. I've also tested it with sample data.

Of note:
- We can't get the mapped type name because the [extension method is internal](https://github.com/realm/realm-dotnet/blob/master/Realm/Realm/Extensions/ReflectionExtensions.cs#L46), so I'm just doing a `string.Replace`.
- All integer values are stored internally as `long`/`Int64`, which is why the seemingly weird cast is required.

### CODE REVIEW

**Comment by smoogipoo** [comment]
> Every missed null-check on online ID is basically a latent bug

At least this is a realm-only property for the time being? Every other usage seems to still refer to e.g. `OnlineBeatmapId`, which this forwards to. @peppy confirm?

**Review by smoogipoo — APPROVED** [review]

**Comment by peppy** [comment]
Right, so the cases where we do `something?.Beatmap.OnlineID` specifically?

**Comment by bdach** [comment]
That's right, those would be the worst ones.

**Comment by peppy** [comment]
I think it shouldn't be too bad, we'll just need to pay attention when migrating to the new property.

Guess it's one reason null propagations aren't great, especially as we are moving more towards `nullable enabled` land.

**Pull request merged**
