### PR TITLE
Implement "extra" beatmap card size

### PR DESCRIPTION
**Pull request by bdach**
Nearing the end of #14216.

https://user-images.githubusercontent.com/20418176/145291563-35bae5a8-05cd-4c15-b17c-bdbdc4bd1d51.mp4

Now, this diff is predicated on one central and potentially controversial assumption - namely, the way this was implemented was by copying the existing card into a new one and tweaking the component layout to meet design, rather than try to inherit things in a correct manner for the visuals to match.

The reason why I did it this way is that [there are several other card sizes designed and not yet implemented](https://www.figma.com/file/oYJ9WkzXGvbPWBz6NxeyGr/UI%2FBeatmap-Card?node-id=112%3A2350), and I feel that it is not realistic to be able to fit them all into one component in a comprehensible manner. In short, I opted for composition of smaller components with some duplication of glue code rather than inheritance, and I feel that the changes that I had to make to the normal card to mold it into extra (especially around laying out the statistics in a grid) vindicate this choice.

When it comes to reviewing, I would therefore propose the following approach:

* Check out a32492c and inspect the cosmetic differences between the "normal" card and the "extra" card (reusing some constants, renaming where required)
* And then check out the rest of the commits here (in bulk, or individually) to see what visual changes had to be made to transform the "normal" card into "extra".

I am providing the diff for step (1) below for review convenience:

<details>
<summary>Differences between <code>BeatmapCard.cs</code> and <code>BeatmapCardExtra.cs</code> at a32492c</summary>

```diff
$ diff -c0 BeatmapCard.cs BeatmapCardExtra.cs                                                                                              beatmap-card/extra ✔ origin/beatmap-card/extra
*** BeatmapCard.cs	2021-12-08 18:30:55.236635689 +0100
--- BeatmapCardExtra.cs	2021-12-08 23:05:31.729078117 +0100
***************
*** 31 ****
!     public class BeatmapCard : OsuClickableContainer
--- 31 ----
!     public class BeatmapCardExtra : OsuClickableContainer
***************
*** 33,37 ****
-         public const float TRANSITION_DURATION = 400;
-         public const float CORNER_RADIUS = 10;
- 
-         public Bindable<bool> Expanded { get; } = new BindableBool();
- 
--- 32 ----
***************
*** 41 ****
--- 37,38 ----
+         public Bindable<bool> Expanded { get; } = new BindableBool();
+ 
***************
*** 67 ****
!         public BeatmapCard(APIBeatmapSet beatmapSet)
--- 64 ----
!         public BeatmapCardExtra(APIBeatmapSet beatmapSet)
***************
*** 96 ****
!                             Width = icon_area_width + 2 * CORNER_RADIUS,
--- 93 ----
!                             Width = icon_area_width + 2 * BeatmapCard.CORNER_RADIUS,
***************
*** 112 ****
!                             Padding = new MarginPadding { Right = CORNER_RADIUS },
--- 109 ----
!                             Padding = new MarginPadding { Right = BeatmapCard.CORNER_RADIUS },
***************
*** 158 ****
!                             X = height - CORNER_RADIUS,
--- 155 ----
!                             X = height - BeatmapCard.CORNER_RADIUS,
***************
*** 160 ****
!                             CornerRadius = CORNER_RADIUS,
--- 157 ----
!                             CornerRadius = BeatmapCard.CORNER_RADIUS,
***************
*** 405 ****
!                 targetWidth = targetWidth - icon_area_width + CORNER_RADIUS;
--- 402 ----
!                 targetWidth = targetWidth - icon_area_width + BeatmapCard.CORNER_RADIUS;
***************
*** 413 ****
!             mainContent.ResizeWidthTo(targetWidth, TRANSITION_DURATION, Easing.OutQuint);
--- 410 ----
!             mainContent.ResizeWidthTo(targetWidth, BeatmapCard.TRANSITION_DURATION, Easing.OutQuint);
***************
*** 416 ****
!             statisticsContainer.FadeTo(showDetails ? 1 : 0, TRANSITION_DURATION, Easing.OutQuint);
--- 413 ----
!             statisticsContainer.FadeTo(showDetails ? 1 : 0, BeatmapCard.TRANSITION_DURATION, Easing.OutQuint);
***************
*** 418,419 ****
!             rightAreaBackground.FadeColour(downloadTracker.State.Value == DownloadState.LocallyAvailable ? colours.Lime0 : colourProvider.Background3, TRANSITION_DURATION, Easing.OutQuint);
!             rightAreaButtons.FadeTo(showDetails ? 1 : 0, TRANSITION_DURATION, Easing.OutQuint);
--- 415,416 ----
!             rightAreaBackground.FadeColour(downloadTracker.State.Value == DownloadState.LocallyAvailable ? colours.Lime0 : colourProvider.Background3, BeatmapCard.TRANSITION_DURATION, Easing.OutQuint);
!             rightAreaButtons.FadeTo(showDetails ? 1 : 0, BeatmapCard.TRANSITION_DURATION, Easing.OutQuint);
***************
*** 429,430 ****
!             idleBottomContent.FadeTo(showProgress ? 0 : 1, TRANSITION_DURATION, Easing.OutQuint);
!             downloadProgressBar.FadeTo(showProgress ? 1 : 0, TRANSITION_DURATION, Easing.OutQuint);
--- 426,427 ----
!             idleBottomContent.FadeTo(showProgress ? 0 : 1, BeatmapCard.TRANSITION_DURATION, Easing.OutQuint);
!             downloadProgressBar.FadeTo(showProgress ? 1 : 0, BeatmapCard.TRANSITION_DURATION, Easing.OutQuint);
```

</details>

Due to the diff size, the "extra" card will be used in the beatmap listing overlay in a follow-up pull request.

### CODE REVIEW

**Comment by peppy** [comment]
Heavily unsure about this direction. `osu-web` uses a single class to cover both these designs. Can understand that considering all the other sizes that may be implemented in the future, this kind of code separation is warranted, but I'd also suggest that the parts which can be split out into new components should be.

And maybe even suggest a base class with the very basics of the design, or if you want to avoid any design logic, the basic flow handling (ie. the download tracking and expansion logic).

Before going ahead with this change, I'd be curious to know if you tried this up front or if the direction in this PR was chosen without experimentation?

At very least, if we're copy-pasting large sections of code like this, I'd want to see inline comments saying that is the case, so we don't update one location and forget another.

**Review by peppy — COMMENTED** [review]
Code looks fine, card behaves correctly - just need to sort out the inheritance/structural considerations.

**Comment by bdach** [comment]
> I'd be curious to know if you tried this up front or if the direction in this PR was chosen without experimentation?

I will admit I haven't tried anything else, but on the other side I can't see much more that *can* be split out, that isn't already a component. I could probably split out the tracker and dimmed state, and that's about it, because:

* Some card sizes don't seem to have the left preview thumbnail thing.
* Sizings, spacings and layout changes all over. The smaller cards don't even share the base dimensions, even when it comes to the right button expandable panel thing, that's smaller there too.
* Download tracking and scaling behaviours is something that web doesn't have, and even that will differ across sizes (different elements will be hidden to make way for progress bar depending on size).

I dunno. Web has it much easier because it doesn't have some behaviour the client has, and even then honestly CSS allows for much more flexibility and declarativeness than the framework does. And in my view it's better to start separately and maybe then unify in post rather than to start locking in a structure that will be difficult to swap out later.

**Comment by bdach** [comment]
On second thought maybe I could improve code sharing across both implementations, although it would be limited in scope and I'm not sure the end result will look much better. But I'll give it a go and link a wip branch here.

**Comment by peppy** [comment]
Sounds good. At very least I'd want to see how it looked before going with this PR's structure.

**Comment by bdach** [comment]
Finally got round to making a draft branch with what I'd consider "relatively safe" for splitting out into common pieces. Link: https://github.com/ppy/osu/compare/master...bdach:beatmap-card/extra-wip?expand=1

Common logic sharing is done in all commits past 3fa4547 on the branch above. The total diffstat of that is a bit too large for my liking, so I'd probably PR the commonising first and make this pull dependent on that.

I'm not 100% sold on that branch, because the designs are very edgecasey and I don't really feel like I can guarantee that some assumption I made when extracting pieces won't change in the future. But it is less verbose in comparison for sure.

**Comment by peppy** [comment]
I think I do prefer that version. Can also agree with the uncertainty factor, but if anything I would be pushing for the designs to share more (visually) to allow for transitions between them. If that ever happens.

Can see a few areas that could potentially be shared further, but probably not worth the effort until we have everything in place for certain.

Are you able to commit on top of this branch?

(as an aside, I really dislike the `BeatmapCard` and `BeatmapCardExtra` naming. The first should probably also have a size name, like `BeatmapCardNormal`, then you can name the `abstract` class `BeatmapCard` maybe).

**Comment by bdach** [comment]
Yeah, I can push all of those changes here if XL diff isn't a problem.

Would also do the rename outright as suggested but unsure that won't wreak even more havoc on this change...

**Comment by peppy** [comment]
Think it's fine, large but still isolated code.

**Comment by bdach** [comment]
Have pushed what I had on that wip branch here. It'll look weird on the UI since I just merged that back to this PR'd branch for simplicity of operations.

Didn't do the renames here, because on trying that it makes this diff just unintelligible. Can do as a follow up change in a separate PR.

**Review by peppy — APPROVED** [review]

**Comment by peppy** [comment]
Let's go with this. Did you want to do the renames on a separate PR?

**Comment by bdach** [comment]
Yep, renames will happen next as a follow up to this.

**Pull request merged**
